Repository run-llama/llama_index, pull requests merged in 2023-11, with the labels that each got.

#7991 Add support for SingleStoreDB as vectorstore
  docs/community/integrations/vector_stores.md
  docs/module_guides/storing/vector_stores.md
  llama_index/vector_stores/__init__.py
  llama_index/vector_stores/singlestoredb.py
  tests/vector_stores/test_singlestoredb.py
Labels: vector store

#8609 Add Astra DB VectorStore functionality
  CHANGELOG.md
  docs/community/integrations/vector_stores.md
  docs/module_guides/storing/vector_stores.md
  llama_index/vector_stores/__init__.py
  llama_index/vector_stores/astra.py
  tests/vector_stores/test_astra.py
Labels: vector store

#8626 Google Vertex Support
  docs/examples/llm/vertex.ipynb
  docs/module_guides/models/llms/modules.md
  llama_index/llms/__init__.py
  llama_index/llms/loading.py
  llama_index/llms/vertex.py
  llama_index/llms/vertex_utils.py
  tests/llms/test_vertex.py
Labels: llm

#8625 Deepmemory support
  docs/optimizing/advanced_retrieval/deep_memory.ipynb
  llama_index/vector_stores/deeplake.py
  poetry.lock
Labels: vector store

#8672 passing max_tokens to the `Cohere` llm
  llama_index/llms/cohere.py
Labels: llm

#8694 Consolidates `black` in `pre-commit`
  .pre-commit-config.yaml
  Makefile
  README.md
  docs/community/integrations/graphsignal.md
  docs/community/integrations/guidance.md
  docs/community/integrations/lmformatenforcer.md
  docs/community/integrations/using_with_langchain.md
  docs/community/integrations/vector_stores.md
  docs/getting_started/customization.rst
  docs/module_guides/deploying/agents/tools/usage_pattern.md
  docs/module_guides/deploying/agents/usage_pattern.md
  docs/module_guides/deploying/chat_engines/usage_pattern.md
  docs/module_guides/deploying/query_engine/usage_pattern.md
  docs/module_guides/evaluating/usage_pattern.md
  docs/module_guides/evaluating/usage_pattern_retrieval.md
  docs/module_guides/indexing/composability.md
  docs/module_guides/indexing/document_management.md
  docs/module_guides/loading/documents_and_nodes/usage_documents.md
  docs/module_guides/loading/documents_and_nodes/usage_metadata_extractor.md
  docs/module_guides/loading/documents_and_nodes/usage_nodes.md
  docs/module_guides/loading/node_parsers/root.md
  docs/module_guides/models/embeddings.md
  docs/module_guides/models/llms/usage_custom.md
  docs/module_guides/models/llms/usage_standalone.md
  docs/module_guides/models/prompts/usage_pattern.md
  docs/module_guides/observability/callbacks/token_counting_migration.md
  docs/module_guides/querying/node_postprocessors/root.md
  docs/module_guides/querying/output_parser.md
  docs/module_guides/querying/response_synthesizers/response_synthesizers.md
  docs/module_guides/querying/response_synthesizers/root.md
  docs/module_guides/querying/router/root.md
  docs/module_guides/storing/customization.md
  docs/module_guides/storing/save_load.md
  docs/module_guides/storing/storing.md
  docs/module_guides/supporting_modules/service_context.md
  docs/optimizing/advanced_retrieval/query_transformations.md
  docs/optimizing/basic_strategies/basic_strategies.md
  docs/understanding/evaluating/cost_analysis/usage_pattern.md
  docs/understanding/loading/loading.md
  docs/understanding/putting_it_all_together/apps/fullstack_app_guide.md
  docs/understanding/putting_it_all_together/apps/fullstack_with_delphic.md
  docs/understanding/putting_it_all_together/chatbots/building_a_chatbot.md
  docs/understanding/putting_it_all_together/q_and_a.md
  docs/understanding/putting_it_all_together/q_and_a/terms_definitions_tutorial.md
  docs/understanding/putting_it_all_together/q_and_a/unified_query.md
  docs/understanding/putting_it_all_together/structured_data.md
  docs/understanding/querying/querying.md
  docs/understanding/storing/storing.md
  docs/understanding/using_llms/using_llms.md
Labels: enhancement

#8779 Fixed embeddings `__all__`
  CHANGELOG.md
  llama_index/embeddings/__init__.py
Labels: bug

#8784 Latest `huggingface_hub`'s recommended model
  CHANGELOG.md
  llama_index/llms/huggingface.py
  tests/embeddings/test_huggingface.py
Labels: embedding

#8994 Fix TextNode instantiation on SupabaseVectorIndexDemo
  docs/examples/vector_stores/SupabaseVectorIndexDemo.ipynb
Labels: lgtm

#9000 fix openai agent
  llama_index/agent/openai_agent.py
  tests/agent/openai/test_openai_agent.py
Labels: lgtm

#9003 fix bugs for litellm==1.1.1
  llama_index/llms/litellm.py
  llama_index/llms/litellm_utils.py
Labels: lgtm

#9007 [Bug]: ChromaReader incorrect indexing of result in create_documents
  llama_index/readers/chroma.py
Labels: bug, lgtm

#9002 [Docs] grammar
  docs/index.rst
Labels: lgtm

#9008 Fix: missing docs dependencies
  poetry.lock
  pyproject.toml
Labels: lgtm

#9010 Docs & code example: Fixed a typo in IngestionPipeline (e was missing)
  CHANGELOG.md
  docs/examples/metadata_extraction/EntityExtractionClimate.ipynb
  docs/examples/metadata_extraction/PydanticExtractor.ipynb
  docs/module_guides/indexing/metadata_extraction.md
Labels: lgtm

#9014 Pending documentation renames for c3 -> condense_plus_context
  docs/api_reference/query/chat_engines.rst
  docs/module_guides/deploying/chat_engines/modules.md
  docs/module_guides/deploying/chat_engines/usage_pattern.md
  llama_index/chat_engine/condense_plus_context.py
Labels: lgtm

#9025 fix prompt helper error
  CHANGELOG.md
  llama_index/indices/prompt_helper.py
Labels: lgtm

#9026 More precise testing `OpenAILike`
  CHANGELOG.md
  tests/llms/test_openai_like.py
Labels: enhancement, llm, lgtm

#9031 Fixing `mypy` for Python 3.8
  CHANGELOG.md
  llama_index/indices/managed/vectara/base.py
  llama_index/response/notebook_utils.py
  pyproject.toml
Labels: bug, lgtm

#9035 [BUG] fix #9018. AzureOpenAI logic for determining function call
  CHANGELOG.md
  docs/examples/chat_engine/chat_engine_openai.ipynb
  llama_index/llms/openai.py
Labels: lgtm

#9040 fix: continue instead of forcing exception openai astream chat
  llama_index/llms/openai.py
Labels: size:XS

#9042 Loosened `dataclasses-json` and removed `pandas`'s `jinja2` extra
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  tests/query_engine/test_pandas.py
Labels: enhancement, size:XXL

#9053 Expand STR_OR_RESPONSE_TYPE
  llama_index/query_engine/custom.py
Labels: lgtm, size:XS

#9051 Fix : Spelling mistake fixed | Anand Vishwakarma
  docs/examples/multi_modal/ChromaMultiModalDemo.ipynb
Labels: lgtm, size:XS

#9043 feat: fastembed embedding support
  CHANGELOG.md
  docs/examples/embeddings/fastembed.ipynb
  docs/module_guides/models/embeddings.md
  llama_index/embeddings/__init__.py
  llama_index/embeddings/fastembed.py
  tests/embeddings/test_fastembed.py
Labels: lgtm, size:L

#9032 `OpenAILike` ability to not infer `max_tokens`
  CHANGELOG.md
  llama_index/llms/openai.py
  llama_index/llms/openai_like.py
  tests/llms/test_openai_like.py
Labels: enhancement, llm, lgtm, size:M

#9056 [version] bump to v0.9.5
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#9044 Minor clarifications on transformations docs
  docs/module_guides/loading/ingestion_pipeline/root.md
  docs/module_guides/loading/ingestion_pipeline/transformations.md
  docs/module_guides/loading/node_parsers/modules.md
  docs/module_guides/models/embeddings.md
Labels: lgtm, size:M

#9059 Testing whether Algolia will understand a sitemap
  docs/_static/sitemap.xml
Labels: size:XS

#9063 Adding all orphaned content to sitemap for Algolia
  docs/_static/sitemap.xml
Labels: size:M

#9060 Fix ReAct Output Parser for Multi-line action inputs
  llama_index/agent/react/output_parser.py
  tests/agent/react/test_react_output_parser.py
Labels: size:S

#9036 Download modules
  llama_index/command_line/__init__.py
  llama_index/command_line/command_line.py
  llama_index/download/download_utils.py
  llama_index/llama_pack/download.py
  pyproject.toml
Labels: size:L

#9027 [DRAFT]: Add progress bar for file loaders
  llama_index/readers/file/base.py
Labels: size:S

#9090 add headers to openai clients
  CHANGELOG.md
  llama_index/llms/azure_openai.py
  llama_index/llms/openai.py
Labels: size:S

#9068 pack docs
  docs/community/integrations.md
  llama_index/llama_pack/__init__.py
  llama_index/llama_pack/download.py
Labels: size:S

#9072 add llama packs example notebook
  docs/community/integrations.md
  docs/examples/llama_hub/llama_packs_example.ipynb
  docs/understanding/loading/llamahub.md
Labels: size:L

#9091 [version] bump to v0.9.6
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#9065 Multiple fixes to make various API reference docs visible to Algolia
  docs/Makefile
  docs/api_reference/index.rst
  docs/api_reference/node.rst
  docs/api_reference/readers.rst
  docs/api_reference/service_context/node_parser.rst
  docs/api_reference/storage/vector_store.rst
  docs/conf.py
  docs/requirements.txt
  llama_index/vector_stores/__init__.py
Labels: size:M

#9093 Bug fix: QueryEngineTool's chat/achat method returns python built-in input func instead of query_str
  llama_index/tools/query_engine.py
Labels: lgtm, size:XS

#9094 [version] small bump for docs
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#9081 Add aws_region_name parameter to Bedrock LLM
  docs/examples/llm/bedrock.ipynb
  llama_index/llms/bedrock.py
Labels: size:M

#9045 Image to Image Retrieval with example
  docs/examples/multi_modal/image_to_image_retrieval.ipynb
  llama_index/core/base_multi_modal_retriever.py
  llama_index/core/image_retriever.py
  llama_index/indices/multi_modal/base.py
  llama_index/indices/multi_modal/retriever.py
  llama_index/schema.py
Labels: lgtm, size:XL

#9105 Adding comprehensive docs for SimpleDirectoryReader
  docs/.gitignore
  docs/module_guides/loading/loading.md
  docs/module_guides/loading/simpledirectoryreader.md
Labels: lgtm, size:L

#9106 fix download loaders [v0.9.6.post2]
  llama_index/VERSION
  llama_index/download/download_utils.py
  llama_index/llama_pack/download.py
  pyproject.toml
Labels: size:S

#9100 fix: remove print call from _llm_extract_triplets
  llama_index/indices/knowledge_graph/base.py
Labels: size:XS

#9109 add llamapacks to docs
  docs/community/integrations.md
  docs/community/llama_packs/root.md
  docs/examples/llama_hub/llama_pack_resume.ipynb
Labels: lgtm, size:L

#9108 Restoring `requests` dependency and loosening `urllib` dependency
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: enhancement, lgtm, size:M

#9107 [new feature] Add jsonl for JsonReader Class
  llama_index/readers/json.py
  tests/readers/test_json.py
Labels: lgtm, size:M

#9103 Adjust ReAct system prompt examples to match default `FnSchema`
  llama_index/agent/react/prompts.py
Labels: lgtm, size:XS

#9073 Removing context from metadata when None
  llama_index/objects/table_node_mapping.py
  tests/objects/test_node_mapping.py
Labels: lgtm, size:M

#9077 fix: Check is usage is None
  llama_index/callbacks/token_counting.py
Labels: size:XS

#9067 Update VoyageEmbedding
  llama_index/embeddings/voyageai.py
Labels: size:S

#9087 feat: support pgvecto.rs as a VectorStore
  CHANGELOG.md
  docs/community/integrations/vector_stores.md
  docs/examples/vector_stores/PGVectoRsDemo.ipynb
  docs/module_guides/storing/vector_stores.md
  llama_index/vector_stores/__init__.py
  llama_index/vector_stores/pgvecto_rs.py
  llama_index/vector_stores/utils.py
Labels: vector store, size:L

#9115 Vectara summarization
  docs/examples/managed/vectaraDemo.ipynb
  llama_index/indices/managed/vectara/base.py
  llama_index/indices/managed/vectara/query.py
  llama_index/indices/managed/vectara/retriever.py
  tests/indices/managed/test_vectara.py
Labels: size:XL

#9116 Make retriever callback manager less painful
  docs/examples/agent/multi_document_agents-v1.ipynb
  docs/examples/finetuning/rerankers/cohere_custom_reranker.ipynb
  docs/examples/index_structs/knowledge_graph/KnowledgeGraphIndex_vs_VectorStoreIndex_vs_CustomIndex_combined.ipynb
  docs/examples/low_level/fusion_retriever.ipynb
  docs/examples/low_level/oss_ingestion_retrieval.ipynb
  docs/examples/low_level/retrieval.ipynb
  docs/examples/query_engine/CustomRetrievers.ipynb
  docs/examples/retrievers/bm25_retriever.ipynb
  llama_index/core/base_retriever.py
Labels: size:L

#9113 add resume to docs
  docs/community/llama_packs/root.md
Labels: lgtm, size:XS

#9122 Add missing colab for MM example
  docs/examples/multi_modal/replicate_multi_modal.ipynb
Labels: size:XS

#9123 Small chat engine updates
  CHANGELOG.md
  llama_index/chat_engine/condense_plus_context.py
  llama_index/chat_engine/context.py
Labels: size:S

#9129 Fix condense plus context chat engine
  docs/examples/chat_engine/chat_engine_condense_plus_context.ipynb
  llama_index/chat_engine/condense_plus_context.py
  tests/chat_engine/test_condense_plus_context.py
Labels: size:L

#9131 [version] bump to v0.9.7
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#9134 Fix ref_doc_id existence
  llama_index/node_parser/interface.py
Labels: lgtm, size:XS

#9112 Fix exception callback handling
  llama_index/callbacks/base.py
Labels: size:S

#9117 Multi Modal Summary Tables
  docs/module_guides/models/multi_modal.md
Labels: lgtm, size:L

#9064 Nerdai/feature 8728 objectindex persist
  CHANGELOG.md
  docs/examples/objects/object_index.ipynb
  docs/module_guides/indexing/modules.md
  llama_index/objects/base.py
  llama_index/objects/base_node_mapping.py
  llama_index/objects/table_node_mapping.py
  llama_index/objects/tool_node_mapping.py
  tests/objects/test_base.py
  tests/objects/test_node_mapping.py
Labels: size:XL

#9137 pass more args through global context
  CHANGELOG.md
  llama_index/service_context.py
Labels: size:S

#9138 add missing llm override for service_context
  llama_index/service_context.py
Labels: size:XS

#9126 refactor: list creation in weaviate.py for efficiency
  llama_index/vector_stores/weaviate.py
Labels: size:S

#9124 Add MiniGPT-4 MM model for MM LLM comparison
  docs/examples/multi_modal/replicate_multi_modal.ipynb
  llama_index/multi_modal_llms/replicate_multi_modal.py
Labels: lgtm, size:L

#9144 Update MM docs with image to image retrieval and new models
  docs/module_guides/models/multi_modal.md
  docs/use_cases/multimodal.md
Labels: size:XS

#9148 better description of Neo4j graph schema
  llama_index/graph_stores/neo4j.py
Labels: lgtm, size:M

#9121 async metadata extractors
  llama_index/async_utils.py
  llama_index/extractors/interface.py
  llama_index/extractors/marvin_metadata_extractor.py
  llama_index/extractors/metadata_extractors.py
Labels: size:L

#9154 Init Multi Modal Pydantic Program
  docs/examples/multi_modal/multi_modal_pydantic.ipynb
  llama_index/multi_modal_llms/__init__.py
  llama_index/program/__init__.py
  llama_index/program/multi_modal_llm_program.py
  tests/program/test_multi_modal_llm_program.py
Labels: size:XL

#9161 vector_stores/weaviate: run get_node_similarity before to_node
  llama_index/vector_stores/weaviate.py
Labels: lgtm, size:XS

#9162 [version] bump to v0.9.8.post1
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#9163 Add try and exception for MM Model runs
  docs/examples/multi_modal/replicate_multi_modal.ipynb
Labels: lgtm, size:M

#9168 add full-stack projects docs page
  docs/community/full_stack_projects.md
  docs/index.rst
  docs/understanding/putting_it_all_together/putting_it_all_together.md
Labels: size:M

#9170 Fixing Missing KeyError
  llama_index/objects/table_node_mapping.py
Labels: lgtm, size:XS

#9174 fix: llms.AzureOpenAI missing `azure_deployment` arg alias
  CHANGELOG.md
  llama_index/llms/azure_openai.py
Labels: size:S

#9179 Pass down attributes to underlying sentence splitter in Hierarchical node parser
  llama_index/node_parser/relational/hierarchical.py
Labels: size:XS

#9186 Refactoring MM LLM Classes/Abstraction
  docs/examples/multi_modal/openai_multi_modal.ipynb
  llama_index/llms/base.py
  llama_index/multi_modal_llms/__init__.py
  llama_index/multi_modal_llms/base.py
  llama_index/multi_modal_llms/openai.py
  llama_index/multi_modal_llms/openai_utils.py
  llama_index/multi_modal_llms/replicate_multi_modal.py
  tests/program/test_multi_modal_llm_program.py
Labels: size:XXL

#9189 Update Replicate MM notebook for stream complete and async calls
  docs/examples/multi_modal/replicate_multi_modal.ipynb
Labels: size:L

#9194 Fix Chroma Multi Filters
  docs/examples/vector_stores/chroma_metadata_filter.ipynb
  llama_index/vector_stores/chroma.py
Labels: size:M

#9207 Error during async streaming of OpenAIAgent & multi tool calls
  llama_index/llms/openai.py
Labels: size:S

#9193 Update Astra DB integration for API changes
  CHANGELOG.md
  llama_index/vector_stores/astra.py
Labels: size:L

#9213 Allowing newest `scikit-learn`
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: enhancement, dependencies, lgtm, size:XL

#9215 Fix incorrect LLAMA_HUB_CONTENTS_URL
  CHANGELOG.md
  llama_index/download/download_utils.py
Labels: size:XS

#9151 `make_localai` factory and `LocalAI` demo notebook
  CHANGELOG.md
  docs/api_reference/llms/openai_like.rst
  docs/examples/llm/localai.ipynb
  llama_index/llms/__init__.py
  llama_index/llms/localai.py
  llama_index/llms/openai_like.py
  tests/llms/test_localai.py
  tests/llms/test_openai_like.py
Labels: enhancement, llm, lgtm, size:L

#9221 [version] bump to v0.9.9
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#9224 Linking `OpenAILike` in doc's LLM Implementations
  docs/api_reference/llms.rst
Labels: documentation, size:XS

#9216 Init More Advanced Metadata Filter for Vector Store
  docs/examples/vector_stores/chroma_metadata_filter.ipynb
  llama_index/vector_stores/__init__.py
  llama_index/vector_stores/awadb.py
  llama_index/vector_stores/bagel.py
  llama_index/vector_stores/cassandra.py
  llama_index/vector_stores/chroma.py
  llama_index/vector_stores/cogsearch.py
  llama_index/vector_stores/dashvector.py
  llama_index/vector_stores/docarray/base.py
  llama_index/vector_stores/elasticsearch.py
  llama_index/vector_stores/lancedb.py
  llama_index/vector_stores/lantern.py
  llama_index/vector_stores/metal.py
  llama_index/vector_stores/milvus.py
  llama_index/vector_stores/mongodb.py
  llama_index/vector_stores/myscale.py
  llama_index/vector_stores/opensearch.py
  llama_index/vector_stores/pgvecto_rs.py
  llama_index/vector_stores/pinecone.py
  llama_index/vector_stores/postgres.py
  llama_index/vector_stores/qdrant.py
  llama_index/vector_stores/redis.py
  llama_index/vector_stores/rocksetdb.py
  llama_index/vector_stores/simple.py
  llama_index/vector_stores/supabase.py
  llama_index/vector_stores/tair.py
  llama_index/vector_stores/tencentvectordb.py
  llama_index/vector_stores/timescalevector.py
  llama_index/vector_stores/types.py
  llama_index/vector_stores/typesense.py
  llama_index/vector_stores/weaviate.py
  llama_index/vector_stores/zep.py
  tests/vector_stores/test_metadata_filters.py
Labels: lgtm, size:L

#9222 Amazon Bedrock Embeddings New models
  docs/examples/embeddings/bedrock.ipynb
  llama_index/embeddings/bedrock.py
Labels: size:L

#9190 PromptLayer integration
  CHANGELOG.md
  docs/examples/callbacks/PromptLayerHandler.ipynb
  docs/module_guides/observability/observability.md
  llama_index/callbacks/global_handlers.py
  llama_index/callbacks/promptlayer_handler.py
Labels: size:L

#9234 Alphabetized `modules.md` and added LocalAI
  docs/module_guides/models/llms/modules.md
Labels: documentation, lgtm, size:L

#9237 Fix headers of Vector Store doc pages.
  docs/examples/vector_stores/CognitiveSearchIndexDemo.ipynb
  docs/examples/vector_stores/RedisIndexDemo.ipynb
  docs/examples/vector_stores/ZepIndexDemo.ipynb
Labels: size:S

#9125 feat: reuse file ids for assistant
  CHANGELOG.md
  llama_index/agent/openai_assistant_agent.py
Labels: size:S

#9239 [version] bump to v0.9.10
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S
