Repository run-llama/llama_index, pull requests merged in 2023-10, with the labels that each got.

#7940 Clarifai integration for Embeddings
  CHANGELOG.md
  docs/core_modules/model_modules/embeddings/modules.md
  docs/examples/embeddings/clarifai.ipynb
  llama_index/embeddings/__init__.py
  llama_index/embeddings/clarifai.py
Labels: embedding

#7942 `LocalAI` removing `max_tokens` from payload
  CHANGELOG.md
  llama_index/llms/localai.py
  llama_index/llms/openai.py
  tests/llms/test_localai.py
Labels: llm

#7866 Add support for MongoDB Atlas $vectorSearch vector search
  CHANGELOG.md
  llama_index/vector_stores/mongodb.py
  tests/vector_stores/test_mongodb.py
Labels: vector store

#7815 Update document summary index
  CHANGELOG.md
  docs/core_modules/query_modules/retriever/retriever_modes.md
  docs/examples/index_structs/doc_summary/DocSummary.ipynb
  llama_index/indices/__init__.py
  llama_index/indices/document_summary/__init__.py
  llama_index/indices/document_summary/base.py
  llama_index/indices/document_summary/retrievers.py
  llama_index/indices/utils.py
  tests/indices/document_summary/conftest.py
  tests/indices/document_summary/test_index.py
  tests/indices/document_summary/test_retrievers.py
Labels: index

#8017 Apply kwarg filters in WeaviateVectorStore
  llama_index/vector_stores/weaviate.py
Labels: vector store

#8019 Fix: ChromaVectorStore can attempt to add in excess of chromadb batch…
  llama_index/vector_stores/chroma.py
Labels: vector store

#8075 Fixed `HuggingFaceLLM` missing f-str
  CHANGELOG.md
  llama_index/llms/huggingface.py
Labels: bug

#8107 Passing `mypy` in Python 3.8
  CHANGELOG.md
  llama_index/indices/managed/vectara/base.py
  llama_index/indices/struct_store/sql_query.py
  llama_index/llm_predictor/vellum/prompt_registry.py
  llama_index/llms/llama_utils.py
  llama_index/node_parser/file/markdown.py
  llama_index/text_splitter/sentence_splitter.py
  llama_index/vector_stores/rocksetdb.py
  llama_index/vector_stores/zep.py
  pyproject.toml
Labels: bug

#8131 `react_agent_with_query_engine` more intuitive ordering
  docs/examples/agent/react_agent_with_query_engine.ipynb
Labels: enhancement

#8120 `CompletionResponse` docs on fields
  llama_index/llms/base.py
Labels: documentation

#8125 Simplifying `ReActAgent` and missing `super()`
  CHANGELOG.md
  llama_index/agent/react/base.py
Labels: bug

#8144 Documenting `LLMMetadata`
  llama_index/llms/base.py
Labels: documentation

#8171 Fixed bug with duplicate `FORMAT_STR` in prompt
  CHANGELOG.md
  llama_index/output_parsers/selection.py
  llama_index/selectors/llm_selectors.py
  tests/selectors/test_llm_selectors.py
Labels: bug

#8154 Repr for JSON conversion errors
  llama_index/output_parsers/selection.py
Labels: enhancement

#8188 More detailed `BaseEmbedding` docstrings
  llama_index/embeddings/base.py
  llama_index/embeddings/huggingface_utils.py
Labels: documentation

#8195 Support for PyTorch MPS backend where possible
  CHANGELOG.md
  llama_index/embeddings/adapter.py
  llama_index/embeddings/huggingface.py
  llama_index/finetuning/embeddings/adapter.py
  llama_index/readers/file/image_caption_reader.py
  llama_index/readers/file/image_reader.py
  llama_index/readers/file/image_vision_llm_reader.py
  llama_index/readers/file/slides_reader.py
  llama_index/utils.py
Labels: enhancement

#8194 Not re-writing `RedisVectorStore.__init__` in notebook
  docs/examples/vector_stores/RedisIndexDemo.ipynb
  llama_index/vector_stores/redis.py
Labels: documentation

#8189 Consolidating query prepending
  CHANGELOG.md
  llama_index/embeddings/clarifai.py
  llama_index/embeddings/huggingface.py
  llama_index/embeddings/huggingface_optimum.py
  llama_index/embeddings/huggingface_utils.py
  llama_index/embeddings/text_embeddings_inference.py
Labels: enhancement

#8190 Fixed missing spaces in prompt templates
  CHANGELOG.md
  llama_index/prompts/default_prompts.py
  llama_index/selectors/prompts.py
Labels: bug

#8159 Improve MyScale Hybrid Search and Add `DELETE` for MyScale vector store
  CHANGELOG.md
  docs/core_modules/data_modules/storage/vector_stores.md
  docs/examples/vector_stores/MyScaleIndexDemo.ipynb
  llama_index/vector_stores/myscale.py
Labels: vector store

#8212 Clarifications/simplifications in S3 and Redis notebooks
  docs/core_modules/data_modules/storage/save_load.md
  docs/examples/vector_stores/RedisIndexDemo.ipynb
Labels: documentation

#8173 add tencent vectordb as vector store
  docs/core_modules/data_modules/storage/vector_stores.md
  docs/examples/vector_stores/TencentVectorDBIndexDemo.ipynb
  llama_index/vector_stores/__init__.py
  llama_index/vector_stores/tencentvectordb.py
  tests/vector_stores/test_tencentvectordb.py
Labels: vector store

#8223 Add Bedrock LLM
  docs/core_modules/model_modules/llms/modules.md
  docs/examples/llm/bedrock.ipynb
  llama_index/llms/__init__.py
  llama_index/llms/bedrock.py
  llama_index/llms/bedrock_utils.py
  llama_index/llms/loading.py
  tests/llms/test_bedrock.py
Labels: llm

#8211 Predibase LLM Integration - prompt method deprecation update
  llama_index/llms/predibase.py
Labels: llm

#8098 Hugging Face Inference API
  CHANGELOG.md
  llama_index/embeddings/__init__.py
  llama_index/embeddings/huggingface.py
  llama_index/embeddings/huggingface_utils.py
  llama_index/embeddings/pooling.py
  llama_index/llms/__init__.py
  llama_index/llms/huggingface.py
  tests/embeddings/test_huggingface.py
  tests/llms/test_huggingface.py
Labels: enhancement

#7772 Add integration for DashVector (vector store)
  CONTRIBUTING.md
  docs/community/integrations/vector_stores.md
  docs/core_modules/data_modules/storage/vector_stores.md
  docs/examples/data_connectors/DashvectorReaderDemo.ipynb
  docs/examples/vector_stores/DashvectorIndexDemo.ipynb
  llama_index/data_structs/struct_type.py
  llama_index/readers/__init__.py
  llama_index/readers/dashvector.py
  llama_index/vector_stores/__init__.py
  llama_index/vector_stores/dashvector.py
  pyproject.toml
Labels: vector store

#7885 Litellm/fixes
  llama_index/llms/litellm.py
  tests/llms/test_litellm.py
Labels: llm

#8080 Add `PGVectorStore` schema param.
  llama_index/vector_stores/postgres.py
  tests/vector_stores/test_postgres.py
Labels: vector store

#8233 Add ai21 llm
  docs/core_modules/model_modules/llms/modules.md
  docs/examples/llm/ai21.ipynb
  llama_index/llms/__init__.py
  llama_index/llms/ai21.py
  llama_index/llms/ai21_utils.py
  tests/llms/test_ai21.py
Labels: llm

#8272 `HuggingFaceInferenceAPI` example notebook
  docs/examples/llm/huggingface.ipynb
Labels: documentation

#8267 Brought back `toml-sort` to `pre-commit`
  .pre-commit-config.yaml
  Makefile
  pyproject.toml
Labels: enhancement

#8263 Added `LocationConstraint` for local `test_s3_kvstore`
  tests/storage/kvstore/test_s3_kvstore.py
Labels: bug

#8271 Add Llava MultiModal QA examples for Tesla 10k RAG
  docs/examples/multi_modal/llava_multi_modal_tesla_10q.ipynb
Labels: retrieval

#8501 Removed `requirements.txt` and `data_requirements.txt`
  README.md
  data_requirements.txt
  requirements.txt
Labels: enhancement

#8550 Add Bedrock Embedding
  CHANGELOG.md
  docs/examples/embeddings/bedrock.ipynb
  llama_index/embeddings/__init__.py
  llama_index/embeddings/bedrock.py
Labels: embedding

#8467 `Pooling` in `HuggingFaceEmbedding` with PyTorch
  CHANGELOG.md
  llama_index/embeddings/huggingface.py
  llama_index/embeddings/pooling.py
Labels: enhancement
