Repository run-llama/llama_index, pull requests merged in 2023-12, with the labels that each got.

#9238 Add GPT4-V and Microsoft Table transformer experiments with PDF which has tables.
  docs/examples/multi_modal/multi_modal_pdf_tables.ipynb
  docs/use_cases/multimodal.md
Labels: size:S

#9248 Update sbert_rerank.py: added "device" parameter to SentenceTransform…
  llama_index/postprocessor/sbert_rerank.py
Labels: size:S

#9250 Add pydantic tests for more Multi-Modal LLMs
  docs/examples/multi_modal/multi_modal_pydantic.ipynb
  docs/module_guides/models/multi_modal.md
  llama_index/multi_modal_llms/replicate_multi_modal.py
Labels: lgtm, size:L

#9252 add headers to openai embedding clients
  llama_index/embeddings/azure_openai.py
  llama_index/embeddings/openai.py
Labels: lgtm, size:S

#9256 Added call to Llamahub proxy to track download numbers
  llama_index/download/download_utils.py
  llama_index/llama_dataset/download.py
  llama_index/llama_pack/download.py
  llama_index/readers/download.py
  llama_index/tools/download.py
Labels: size:M

#9259 Update anthropic_utils.py
  llama_index/llms/anthropic_utils.py
Labels: size:XS

#9260 Pinecone Metadata filter
  docs/examples/vector_stores/chroma_metadata_filter.ipynb
  docs/examples/vector_stores/pinecone_metadata_filter.ipynb
  llama_index/vector_stores/pinecone.py
  llama_index/vector_stores/types.py
Labels: size:L

#9264 Changes for MM docs and Pydantic Examples
  docs/examples/multi_modal/multi_modal_pydantic.ipynb
  docs/module_guides/models/multi_modal.md
  docs/use_cases/multimodal.md
Labels: lgtm, size:L

#9253 Move download datasets logic our of download_utils.py
  llama_index/command_line/command_line.py
  llama_index/download/dataset.py
  llama_index/download/module.py
  llama_index/download/utils.py
  llama_index/llama_dataset/download.py
  llama_index/llama_pack/download.py
  llama_index/readers/download.py
  llama_index/tools/download.py
Labels: lgtm, size:XL

#9266 make reference_context optional
  CHANGELOG.md
  llama_index/llama_dataset/base.py
  llama_index/llama_dataset/rag.py
Labels: size:M

#9275 Add `anthropic.claude-v2:1` model tokens
  llama_index/llms/bedrock_utils.py
Labels: size:XS

#9283 [version] bump to v0.9.11
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#9284 labelled + labeled
  llama_index/indices/multi_modal/base.py
  llama_index/llama_dataset/__init__.py
  llama_index/llama_dataset/rag.py
Labels: size:S

#9281 AutoRetrievel Filter using OpenAI agent and multi-filters
  docs/examples/agent/openai_agent_query_cookbook.ipynb
Labels: size:L

#9290 Fix dataset url
  llama_index/download/dataset.py
Labels: size:XS

#9302 Init Weaviate Meta Data filter
  docs/examples/vector_stores/WeaviateIndex_metadata_filter.ipynb
  llama_index/vector_stores/weaviate.py
Labels: size:M

#9301 add resuse_client option
  CHANGELOG.md
  llama_index/embeddings/azure_openai.py
  llama_index/embeddings/openai.py
  llama_index/llms/azure_openai.py
  llama_index/llms/openai.py
Labels: size:L

#9300 Allow `delete_kwargs` in vector store, use them in WeaviateVectorStore
  llama_index/indices/vector_store/base.py
  llama_index/vector_stores/weaviate.py
Labels: lgtm, size:XS

#9298 Handling the case where the response does not have a "usage" in the token counts function
  llama_index/callbacks/token_counting.py
Labels: lgtm, size:S

#9296 Improve `Vertex` hints
  docs/examples/llm/vertex.ipynb
  llama_index/llms/vertex.py
  llama_index/llms/vertex_utils.py
Labels: lgtm, size:M

#9265 Bedrock embedding query for cohere was not in the correct format
  llama_index/embeddings/bedrock.py
  poetry.lock
  pyproject.toml
  tests/embeddings/test_bedrock.py
  tests/llms/test_bedrock.py
Labels: lgtm, size:L

#9304 support python 3.12
  llama_index/embeddings/openai.py
  poetry.lock
  pyproject.toml
Labels: size:XS

#9303 Init Qdrant Metadata filter
  docs/examples/vector_stores/Qdrant_metadata_filter.ipynb
  llama_index/vector_stores/qdrant.py
Labels: lgtm, size:L

#9257 Added support for vllm framework
  CHANGELOG.md
  docs/examples/llm/vllm.ipynb
  docs/module_guides/models/llms/modules.md
  llama_index/llms/__init__.py
  llama_index/llms/vllm.py
  llama_index/llms/vllm_utils.py
  tests/llms/test_vllm.py
Labels: size:XXL

#9306 Solve Empty Text Vector Store with MM vector stores. Update MM docs
  docs/module_guides/models/multi_modal.md
  llama_index/indices/multi_modal/retriever.py
Labels: size:S

#9316 bug fix for using mmr
  docs/examples/managed/vectaraDemo.ipynb
  llama_index/indices/managed/vectara/retriever.py
Labels: lgtm, size:L

#9317 [version] bump to v0.9.12
  CHANGELOG.md
Labels: size:S

#9318 missing files
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#9320 Refactor Image Store into StorageContext
  llama_index/indices/multi_modal/base.py
  llama_index/indices/multi_modal/retriever.py
  llama_index/storage/storage_context.py
Labels: lgtm, size:S

#9322 Pass kwargs to MM Query Engine for retriever
  llama_index/query_engine/multi_modal.py
Labels: lgtm, size:XS

#9323 Limit GPT4V models to supported ones
  llama_index/multi_modal_llms/openai.py
Labels: size:XS

#9328 remove comma
  llama_index/llms/openai.py
Labels: size:XS

#9329 fix another comma
  llama_index/embeddings/openai.py
Labels: size:XS

#9330 update savepath name for FAISS
  CHANGELOG.md
  llama_index/vector_stores/faiss.py
Labels: size:S

#9326 Add MM rst API doc
  docs/api_reference/index.rst
  docs/api_reference/multi_modal.rst
  docs/api_reference/multi_modal/openai.rst
  docs/api_reference/multi_modal/replicate.rst
Labels: size:M

#9333 Make OpenAIAgent compatible with OpenAILike
  llama_index/agent/openai_agent.py
Labels: lgtm, size:XS

#9344 Fix links and typo in llava_multi_modal_tesla_10q.ipynb
  docs/examples/multi_modal/llava_multi_modal_tesla_10q.ipynb
Labels: lgtm, size:S

#9349 [version] bump to v0.9.13
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#9351 move system prompt for context chat engine
  llama_index/chat_engine/context.py
Labels: size:XS

#9354 Upd Llava Model version from Replicate
  llama_index/multi_modal_llms/replicate_multi_modal.py
Labels: size:XS

#9360 Change Llava Old Model to MM LLM
  docs/examples/multi_modal/llava_multi_modal_tesla_10q.ipynb
  llama_index/multi_modal_llms/replicate_multi_modal.py
Labels: size:L

#9363 add ollama pack example
  docs/community/llama_packs/root.md
  docs/examples/llama_hub/llama_pack_ollama.ipynb
Labels: size:L

#9341 add Ollama Embedding class
  docs/examples/embeddings/ollama_embedding.ipynb
  llama_index/constants.py
  llama_index/embeddings/__init__.py
  llama_index/embeddings/base.py
  llama_index/embeddings/ollama_embedding.py
  llama_index/llms/__init__.py
Labels: size:L

#9365 Upd changelog
  CHANGELOG.md
Labels: size:XS

#9285 Implement FlagEmbeddingReranker for search re-ranking
  docs/examples/node_postprocessor/FlagEmbeddingReranker.ipynb
  llama_index/postprocessor/__init__.py
  llama_index/postprocessor/flag_embedding_reranker.py
Labels: size:L

#9381 Add AsyncInferenceClient complete response
  llama_index/llms/huggingface.py
Labels: lgtm, size:XS

#9382 Update FlagEmbeddingReranker Class and example
  CHANGELOG.md
  docs/examples/node_postprocessor/FlagEmbeddingReranker.ipynb
  llama_index/postprocessor/flag_embedding_reranker.py
Labels: lgtm, size:L

#9369 Modify typing of vector_store to satisfy mypy
  llama_index/storage/storage_context.py
Labels: size:XS

#9389 add zephyr 3b test
  docs/module_guides/models/llms.md
Labels: size:XS

#9395 Fix HuggingFaceInferenceAPIEmbedding with sentence transformers
  llama_index/embeddings/huggingface.py
  tests/embeddings/test_huggingface.py
Labels: size:S

#9393 Fix Url Truncation in MetadataRepalcementDemo Notebook
  docs/examples/node_postprocessor/MetadataReplacementDemo.ipynb
Labels: size:XS

#9402 [Docs] Fix link in /node_parsers/root.md
  docs/module_guides/loading/node_parsers/root.md
Labels: lgtm, size:XS

#9400 Remove unneeded where clause in postgres hybrid search query
  llama_index/vector_stores/postgres.py
Labels: lgtm, size:S

#9357 Init Llava Demo Example
  docs/examples/multi_modal/llava_demo.ipynb
Labels: lgtm, size:XS

#9410 Check if __init__.py file exist in download/module.py to avoid crash when using download_loader
  llama_index/download/module.py
Labels: size:XS

#9420 Feat/PgVector Support custom hnsw.ef_search and ivfflat.probes
  docs/examples/vector_stores/postgres.ipynb
  llama_index/vector_stores/postgres.py
Labels: lgtm, size:L

#9430 Issue 8605
  docs/examples/vector_stores/OpensearchDemo.ipynb
  llama_index/vector_stores/opensearch.py
Labels: lgtm, size:L

#9424 fix F1 score definition, update copyright year
  docs/conf.py
  docs/optimizing/evaluation/evaluation.md
Labels: lgtm, size:XS

#9422 Discussion#8390 : Added sql_only hook to return only sql without running it
  llama_index/indices/struct_store/sql_query.py
  llama_index/indices/struct_store/sql_retriever.py
  tests/indices/struct_store/test_sql_query.py
Labels: lgtm, size:L

#9391 Update docs to highlight ingestion
  docs/module_guides/loading/documents_and_nodes/usage_documents.md
  docs/module_guides/loading/loading.md
  docs/understanding/loading/loading.md
Labels: size:L

#9438 code fix azurecosmosmongo.py
  llama_index/vector_stores/azurecosmosmongo.py
Labels: lgtm, size:XS

#9362 Bug fix for `asyncio_mod` in `LabelledRagDataset`
  llama_index/llama_dataset/base.py
Labels: lgtm, size:XS

#9441 Add MistralAI Embeddings
  docs/examples/embeddings/mistralai.ipynb
  docs/module_guides/models/embeddings.md
  llama_index/embeddings/__init__.py
  llama_index/embeddings/mistralai.py
Labels: lgtm, size:L

#9412 Only capture valid python function names in ReAct output
  llama_index/agent/react/output_parser.py
  tests/agent/react/test_react_output_parser.py
Labels: lgtm, size:S

#9442 [version] bump version to 0.9.14
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#9444 Add MistralAI LLM Endpoint.
  docs/examples/llm/mistralai.ipynb
  docs/module_guides/models/llms/modules.md
  llama_index/llms/__init__.py
  llama_index/llms/mistral.py
  llama_index/llms/mistralai_utils.py
Labels: lgtm, size:XL

#9446 [version] bump version to 0.9.14.post1
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#9447 fix: validate api key
  llama_index/embeddings/openai.py
  llama_index/llms/openai_utils.py
  tests/embeddings/test_base.py
  tests/ingestion/test_pipeline.py
Labels: lgtm, size:M

#9449 Revert "fix: validate api key (#9447)"
  llama_index/embeddings/openai.py
  llama_index/llms/openai_utils.py
  tests/embeddings/test_base.py
  tests/ingestion/test_pipeline.py
Labels: size:M

#9451 add query transform guide
  docs/examples/query_transformations/query_transform_cookbook.ipynb
  docs/optimizing/advanced_retrieval/advanced_retrieval.md
  llama_index/retrievers/fusion_retriever.py
Labels: size:XL

#9461 Update MM pydantic example
  docs/examples/multi_modal/llava_demo.ipynb
  docs/examples/multi_modal/multi_modal_pydantic.ipynb
Labels: size:L

#9462 [version] bump version to 0.9.14.post2
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#9465 post3
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#9367 OpenAIAssistantAgent.from_existing, bugfixes: _achat, etc
  llama_index/agent/openai_assistant_agent.py
  tests/agent/openai/test_openai_assistant_agent.py
Labels: lgtm, size:L

#9466 Add async support for mistral embeddings
  llama_index/embeddings/mistralai.py
  llama_index/llms/mistral.py
Labels: size:M

#9467 Refactor OpenAI MM model api key to resolve_openai_credentials
  llama_index/multi_modal_llms/base.py
  llama_index/multi_modal_llms/openai.py
Labels: size:M

#9468 update maintainers
  pyproject.toml
Labels: size:XS

#9456 Fixed some grammatical mistakes
  docs/api_reference/query.rst
  docs/optimizing/evaluation/e2e_evaluation.md
Labels: size:XS

#9455 Make ollama support additional_kwargs correctly
  llama_index/embeddings/ollama_embedding.py
  llama_index/llms/ollama.py
Labels: size:XS

#9440 Introduce Google Generative Language Semantic Retriever
  docs/community/integrations/managed_indices.md
  docs/examples/managed/GoogleDemo.ipynb
  docs/module_guides/querying/retriever/retrievers.md
  llama_index/indices/managed/google/generativeai/__init__.py
  llama_index/indices/managed/google/generativeai/base.py
  llama_index/response_synthesizers/google/generativeai/__init__.py
  llama_index/response_synthesizers/google/generativeai/base.py
  llama_index/vector_stores/google/generativeai/__init__.py
  llama_index/vector_stores/google/generativeai/base.py
  llama_index/vector_stores/google/generativeai/genai_extension.py
  poetry.lock
  pyproject.toml
  tests/indices/managed/__init__.py
  tests/indices/managed/test_google.py
  tests/response_synthesizers/test_google.py
  tests/vector_stores/test_google.py
Labels: size:XXL

#9452 Add a Gemini models for text and multi-modal.
  docs/examples/llm/gemini.ipynb
  docs/examples/multi_modal/gemini.ipynb
  docs/module_guides/models/multi_modal.md
  llama_index/llms/__init__.py
  llama_index/llms/gemini.py
  llama_index/llms/gemini_utils.py
  llama_index/multi_modal_llms/__init__.py
  llama_index/multi_modal_llms/gemini.py
  tests/llms/test_gemini.py
  tests/llms/test_palm.py
Labels: lgtm, size:XXL

#9485 [version] bump to v0.9.15
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#9486 use persist dir in faiss
  llama_index/vector_stores/faiss.py
Labels: size:XS

#9476 Gemini Embedding
  docs/examples/embeddings/gemini.ipynb
  llama_index/embeddings/__init__.py
  llama_index/embeddings/gemini.py
Labels: size:L

#9498 Merge Gemini Same Role Chat Message
  docs/examples/multi_modal/gemini.ipynb
  llama_index/llms/gemini.py
  llama_index/llms/gemini_utils.py
Labels: lgtm, size:M

#9501 Teeny stray link causing weirdness
  docs/understanding/loading/loading.md
Labels: size:XS

#9505 Fixing CHANGELOG for wrong PR ID
  CHANGELOG.md
Labels: bug, lgtm, size:XS

#9500 Overhauling docs for VectorStoreIndex
  docs/module_guides/indexing/indexing.md
  docs/module_guides/indexing/modules.md
  docs/module_guides/indexing/usage_pattern.md
  docs/module_guides/indexing/vector_store_guide.ipynb
  docs/module_guides/indexing/vector_store_index.md
Labels: lgtm, size:L

#9511 Expanding use-cases docs
  docs/understanding/putting_it_all_together/q_and_a.md
  docs/use_cases/chatbots.md
  docs/use_cases/q_and_a.md
Labels: lgtm, size:M

#9494 Fix small bug in string method of NodeWithScore
  llama_index/schema.py
Labels: size:XS

#9504 Added missing `default=None` to `LLM.system_prompt`
  CHANGELOG.md
  llama_index/llms/llm.py
Labels: bug, size:S

#9508 Update PDFReader
  llama_index/readers/file/docs_reader.py
Labels: size:M

#9513 Updating Spelling Mistakes
  docs/module_guides/models/llms.md
  docs/optimizing/fine-tuning/fine-tuning.md
Labels: size:XS

#9502 Allowing `LOCALAI_DEFAULTS` to work with `__ror__`
  llama_index/llms/localai.py
Labels: bug, lgtm, size:XS

#9516 FIxed DOcs grmmatical issues
  experimental/openai_fine_tuning/train_questions.txt
Labels: size:XS

#9526 fix: improve PgVectorStore Retrieval by not fetching unnecessary columns
  llama_index/vector_stores/postgres.py
Labels: size:M

#9497 Allow build/search params for MilvusVectorStore
  llama_index/vector_stores/milvus.py
  tests/vector_stores/test_milvus.py
Labels: size:M

#9517 Fixed Docs Spelling Mistakes
  CHANGELOG.md
  docs/changes/deprecated_terms.md
  docs/community/integrations/graph_stores.md
  docs/community/integrations/guidance.md
  docs/community/integrations/vector_stores.md
  docs/getting_started/concepts.md
  docs/getting_started/discover_llamaindex.md
  docs/module_guides/models/llms.md
  docs/optimizing/advanced_retrieval/query_transformations.md
  docs/optimizing/basic_strategies/basic_strategies.md
  docs/optimizing/building_rag_from_scratch.md
  docs/use_cases/agents.md
  examples/gatsby/gatsby_license.txt
Labels: size:M

#9489 Fix len check
  llama_index/evaluation/dataset_generation.py
Labels: lgtm, size:XS

#9473 Fix Bedrock LLMs
  llama_index/llms/bedrock.py
  llama_index/llms/bedrock_utils.py
  tests/llms/test_bedrock.py
Labels: lgtm, size:L

#9533 Improving "agents" section of Putting It All Together
  docs/examples/agent/openai_forced_function_call.ipynb
  docs/understanding/putting_it_all_together/agents.md
Labels: lgtm, size:M

#9535 Optional deps docs
  docs/getting_started/installation.md
Labels: lgtm, size:XS

#9537 added _node_type to metadata
  llama_index/vector_stores/milvus.py
Labels: size:XS

#9538 Cut release for 0.9.15.post1
  llama_index/VERSION
  pyproject.toml
Labels: lgtm, size:XS

#9539 Logan/hf fix 3
  llama_index/VERSION
  llama_index/llms/huggingface.py
  pyproject.toml
Labels: size:XS

#9542 fix pydantic fields to float
  docs/examples/multi_modal/gemini.ipynb
Labels: size:XS

#9547 Title vs content difference for Gemini Embedding
  llama_index/embeddings/gemini.py
Labels: size:XS

#9540 Updated Links in deprecated_terms.md
  docs/changes/deprecated_terms.md
Labels: size:S

#9406 [WIP] Add prometheus evaluation notebook
  docs/examples/data/images/prometheus_paper_card.png
  docs/examples/evaluation/prometheus_evaluation.ipynb
  llama_index/evaluation/correctness.py
  llama_index/evaluation/eval_utils.py
Labels: lgtm, size:XXL

#9545 Add support for auth service accounts for Google Semantic Retriever
  docs/examples/managed/GoogleDemo.ipynb
  llama_index/indices/managed/google/generativeai/__init__.py
  llama_index/response_synthesizers/google/generativeai/__init__.py
  llama_index/vector_stores/google/generativeai/__init__.py
  llama_index/vector_stores/google/generativeai/base.py
  llama_index/vector_stores/google/generativeai/genai_extension.py
  tests/indices/managed/test_google.py
  tests/response_synthesizers/test_google.py
  tests/vector_stores/test_google.py
Labels: size:L

#9534 Fleshing out "Understanding evaluation" section a bit
  docs/understanding/evaluating/evaluating.md
Labels: size:M

#9554 add a device in optimum push #9541
  llama_index/embeddings/huggingface_optimum.py
Labels: size:XS

#9557 add starling 7b
  docs/module_guides/models/llms.md
Labels: size:XS

#9555 ollama: strip invalid `formatted` option
  llama_index/llms/ollama.py
Labels: size:XS

#9558 Update Ollama API for ollama v0.1.16
  llama_index/llms/ollama.py
Labels: size:S

#9530 Add hybrid search to neo4j vector store
  docs/examples/vector_stores/Neo4jVectorDemo.ipynb
  llama_index/vector_stores/neo4jvector.py
Labels: size:L

#9529 fix/Reintroduce `WHERE` filter to the Sparse Query for PgVectorStore
  llama_index/vector_stores/postgres.py
Labels: size:S

#9559 nit: fix gemini notebook
  docs/examples/multi_modal/gemini.ipynb
Labels: size:XS

#9564 Update OpenAI fine-tuning with latest changes
  llama_index/finetuning/openai/base.py
Labels: lgtm, size:XS

#9563 Gemini Model Checks
  docs/examples/multi_modal/gemini.ipynb
  llama_index/multi_modal_llms/gemini.py
Labels: size:S

#9556 add MongoDB Vector Search vector store to docs
  llama_index/vector_stores/__init__.py
  llama_index/vector_stores/mongodb.py
Labels: size:XS

#9570 Update openai_agent_query_cookbook.ipynb
  docs/examples/agent/openai_agent_query_cookbook.ipynb
Labels: size:XS

#9573 Add mixtral 8x7b model to anyscale available models
  llama_index/llms/anyscale_utils.py
Labels: size:XS

#9528 Integrations: Gradient[Embeddings,LLM] - sdk-upgrade
  llama_index/embeddings/gradient.py
  llama_index/llms/gradient.py
  tests/llms/test_gradient.py
Labels: size:L

#9464 Add OpenRouter, with Mixtral demo
  CHANGELOG.md
  docs/examples/llm/openrouter.ipynb
  docs/module_guides/models/llms/modules.md
  llama_index/llms/__init__.py
  llama_index/llms/openrouter.py
Labels: size:L

#9550 Fix langchain integrations doc page
  docs/api_reference/langchain_integrations/base.rst
Labels: size:XS

#9584 agent refactor: step-wise execution
  docs/_static/agents/agent_step_execute.png
  docs/api_reference/agents.rst
  docs/examples/agent/agent_runner/agent_runner.ipynb
  docs/examples/agent/agent_runner/agent_runner_rag.ipynb
  docs/module_guides/deploying/agents/agent_runner.md
  docs/module_guides/deploying/agents/modules.md
  docs/module_guides/deploying/agents/root.md
  llama_index/agent/__init__.py
  llama_index/agent/legacy/__init__.py
  llama_index/agent/legacy/context_retriever_agent.py
  llama_index/agent/legacy/openai_agent.py
  llama_index/agent/legacy/react/__init__.py
  llama_index/agent/legacy/react/base.py
  llama_index/agent/legacy/retriever_openai_agent.py
  llama_index/agent/openai/__init__.py
  llama_index/agent/openai/base.py
  llama_index/agent/openai/step.py
  llama_index/agent/openai/utils.py
  llama_index/agent/openai_assistant_agent.py
  llama_index/agent/react/agent.py
  llama_index/agent/react/base.py
  llama_index/agent/react/step.py
  llama_index/agent/runner/__init__.py
  llama_index/agent/runner/base.py
  llama_index/agent/runner/parallel.py
  llama_index/agent/types.py
  llama_index/program/openai_program.py
  tests/agent/openai/test_openai_agent.py
  tests/agent/react/test_react_agent.py
  tests/agent/runner/__init__.py
  tests/agent/runner/test_base.py
Labels: size:XXL

#9587 [version] bump version to 0.9.16
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#9588 Fix pickle again, add unit test
  llama_index/llms/llm.py
  llama_index/schema.py
  tests/indices/vector_store/test_simple.py
Labels: size:M

#9567 Init Benchmark Retrieval Effectiveness
  docs/examples/managed/manage_retrieval_benchmark.ipynb
Labels: lgtm, size:XXL

#9591 Update ollama.py
  llama_index/llms/ollama.py
Labels: size:XS

#9593 import using bridge [0.9.16.post1]
  llama_index/VERSION
  llama_index/agent/runner/parallel.py
  llama_index/agent/types.py
  llama_index/embeddings/fastembed.py
  pyproject.toml
Labels: lgtm, size:S

#9595 Removing `types-protobuf` as required dependency
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: bug, size:XS

#9594 fix mix up b/w 'formatted' and 'format' params for ollama api call
  llama_index/llms/ollama.py
Labels: size:S

#9598 fix(azure_openai.py): add missing return to subclass override
  llama_index/llms/azure_openai.py
Labels: size:XS

#9495 FEATURE: Cohere ReRank Relevancy Metric for Retrieval Eval
  docs/examples/evaluation/retrieval/retriever_eval.ipynb
  llama_index/evaluation/retrieval/base.py
  llama_index/evaluation/retrieval/evaluator.py
  llama_index/evaluation/retrieval/metrics.py
  llama_index/evaluation/retrieval/metrics_base.py
Labels: lgtm, size:L

#9608 fix: out of index get latest tool call
  llama_index/agent/openai/step.py
Labels: lgtm, size:S

#9606 Adding an optional auth token to the TextEmbeddingInference class
  llama_index/embeddings/text_embeddings_inference.py
Labels: size:S

#9599 Fix Gemini Chat Mode
  docs/examples/llm/gemini.ipynb
  llama_index/llms/gemini.py
Labels: lgtm, size:L

#9601 [example] adding user feedback
  docs/examples/agent/agent_runner/agent_runner_rag_controllable.ipynb
  docs/module_guides/deploying/agents/modules.md
  llama_index/agent/openai/step.py
  llama_index/agent/react/step.py
  llama_index/agent/runner/base.py
  llama_index/agent/runner/parallel.py
  llama_index/agent/utils.py
  tests/agent/openai/test_openai_agent.py
  tests/agent/react/test_react_agent.py
Labels: size:XXL

#9615 [version] bump version to 0.9.17
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#9617 nit: add Colab badge
  docs/examples/agent/agent_runner/agent_runner_rag_controllable.ipynb
Labels: size:S

#9616 Fix Stream Chat for Gemini MM LLM
  llama_index/multi_modal_llms/gemini.py
Labels: size:M

#9614 bundle nltk tiktoken v2
  .github/workflows/publish_release.yml
  .pre-commit-config.yaml
  llama_index/_static/nltk_cache/.gitignore
  llama_index/_static/tiktoken_cache/.gitignore
  llama_index/finetuning/cross_encoders/dataset_gen.py
  llama_index/indices/keyword_table/utils.py
  llama_index/memory/chat_memory_buffer.py
  llama_index/node_parser/text/utils.py
  llama_index/postprocessor/optimizer.py
  llama_index/utils.py
  pyproject.toml
  tests/memory/test_chat_memory_buffer.py
Labels: size:L

#9621 Update openrouter.ipynb google colab badge
  docs/examples/llm/openrouter.ipynb
Labels: lgtm, size:XS

#9622 bump to dev version
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#9628 install with dev in publish workflow
  .github/workflows/publish_release.yml
Labels: size:XS

#9629 use pip for publish
  .github/workflows/publish_release.yml
Labels: size:XS

#9586 Update pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:XS

#9632 FIx Doc links and other documentation issue
  CHANGELOG.md
  docs/module_guides/models/embeddings.md
  docs/understanding/understanding.md
  docs/use_cases/agents.md
  docs/use_cases/chatbots.md
  docs/use_cases/extraction.md
  docs/use_cases/multimodal.md
Labels: size:S
