Repository run-llama/llama_index, pull requests merged in 2024-10, with the labels that each got.

#16277 Re-factor `WorkflowHandler.run_step()` so user manually emits Event to start next step in worfklow
  docs/docs/understanding/workflows/observability.md
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/llama_index/core/workflow/handler.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: lgtm, size:L

#16315 Add cookbook for Anthropic Contextual Retrieval
  docs/docs/examples/cookbooks/contextual_retrieval.ipynb
Labels: lgtm, size:XXL

#16317 [FIX] broken workflow unit test
  llama-index-core/tests/workflow/test_workflow.py
Labels: lgtm, size:XS

#16320 [Feature Request] Ability to cancel workflow execution
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/llama_index/core/workflow/errors.py
  llama-index-core/llama_index/core/workflow/handler.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: lgtm, size:M

#16321 fix async client init
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-redis/llama_index/storage/chat_store/redis/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-redis/pyproject.toml
Labels: size:S

#16331 test: add test for agent async fn to increase coverage
  llama-index-core/tests/agent/custom/test_simple_function.py
Labels: lgtm, size:M

#16337 Rremoving safety settings from generation config for Vertex AI models
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py
  llama-index-integrations/llms/llama-index-llms-vertex/pyproject.toml
Labels: lgtm, size:XS

#16250 Enable context serialization in workflows
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/llama_index/core/workflow/context_serializers.py
  llama-index-core/llama_index/core/workflow/handler.py
  llama-index-core/llama_index/core/workflow/utils.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: lgtm, size:L

#16339 bump deps for bm25
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/pyproject.toml
Labels: size:XS

#16332 Add Airtrain + Llama Index cookbook
  docs/docs/examples/cookbooks/airtrain.ipynb
  docs/mkdocs.yml
Labels: lgtm, size:L

#16341 v0.11.15
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/multi_modal_llms/huggingface.md
  docs/docs/api_reference/storage/chat_store/upstash.md
  docs/docs/api_reference/tools/oracleai.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/pyproject.toml
  llama-index-integrations/selectors/llama-index-selectors-notdiamond/pyproject.toml
  llama-index-integrations/selectors/llama-index-selectors-notdiamond/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#16342 feat: add webUrl to get_resource_info
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/llama_index/readers/microsoft_sharepoint/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/pyproject.toml
Labels: lgtm, size:XS

#16347 Fix PyPI publish for llama-index-vector-stores-oracledb
  llama-index-integrations/vector_stores/llama-index-vector-stores-oracledb/pyproject.toml
Labels: lgtm, size:XS

#16329 MilvusVectorStore: Add support for nested MetadataFilters and FilterOperator.IS_EMPTY
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/tests/test_vector_stores_milvus.py
Labels: lgtm, size:M

#16356 fix hf mm publish
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/pyproject.toml
Labels: size:XS

#16354 Raise warning instead of error
  llama-index-core/llama_index/core/indices/vector_store/base.py
  llama-index-core/tests/indices/vector_store/test_simple.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/tests/conftest.py
Labels: lgtm, size:M

#16351 adding vertex endpoint embedding
  docs/docs/examples/embeddings/vertex_embedding_endpoint.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-vertex-endpoint/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-vertex-endpoint/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-vertex-endpoint/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-vertex-endpoint/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-vertex-endpoint/llama_index/embeddings/vertex_endpoint/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-vertex-endpoint/llama_index/embeddings/vertex_endpoint/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-vertex-endpoint/llama_index/embeddings/vertex_endpoint/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-vertex-endpoint/llama_index/embeddings/vertex_endpoint/utils.py
  llama-index-integrations/embeddings/llama-index-embeddings-vertex-endpoint/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-vertex-endpoint/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-vertex-endpoint/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-vertex-endpoint/tests/test_embeddings_vertex_endpoint.py
Labels: lgtm, size:XL

#16349 Adding support in FireworksAI for Meta 3.2 Models: 1b-instruct; 3b-instruct; 11b-vision; 90b-vision
  llama-index-integrations/llms/llama-index-llms-fireworks/llama_index/llms/fireworks/utils.py
  llama-index-integrations/llms/llama-index-llms-fireworks/pyproject.toml
Labels: lgtm, size:XS

#16350 Adding MongoDB hybrid search example to cookbook, cleaning up existing MongoDB examples
  docs/docs/examples/cookbooks/mongodb_retrieval_strategies.ipynb
  docs/docs/examples/vector_stores/MongoDBAtlasVectorSearch.ipynb
  docs/docs/examples/vector_stores/MongoDBAtlasVectorSearchRAGFireworks.ipynb
  docs/docs/examples/vector_stores/MongoDBAtlasVectorSearchRAGOpenAI.ipynb
Labels: lgtm, size:XXL

#16316 Treat non-dict JSON function arguments as empty (instead of unexpected raise)
  llama-index-core/llama_index/core/llms/llm.py
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_utils.py
Labels: lgtm, size:M

#16362 Deleting widgets that make mkdocs barf
  docs/docs/examples/cookbooks/mongodb_retrieval_strategies.ipynb
Labels: lgtm, size:XXL

#16309 Fix OpenAIMultiModal: Refactor OpenAI update_tool_calls
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/llama_index/multi_modal_llms/openai/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/pyproject.toml
Labels: lgtm, size:L

#16364 Suppress token detaching exception during workflow tracing
  llama-index-core/llama_index/core/instrumentation/dispatcher.py
Labels: lgtm, size:S

#16366 v0.11.16
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#16138 Azure CosmosDB NoSql Storage Integrations
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azurecosmosnosql/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azurecosmosnosql/Makefile
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azurecosmosnosql/README.md
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azurecosmosnosql/llama_index/storage/chat_store/azurecosmosnosql/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azurecosmosnosql/llama_index/storage/chat_store/azurecosmosnosql/__init__.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azurecosmosnosql/llama_index/storage/chat_store/azurecosmosnosql/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azurecosmosnosql/pyproject.toml
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azurecosmosnosql/tests/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azurecosmosnosql/tests/__init__.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azurecosmosnosql/tests/test_storage_azurecosmosnosql_chat_store.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-azurecosmosnosql/BUILD
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-azurecosmosnosql/Makefile
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-azurecosmosnosql/README.md
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-azurecosmosnosql/llama_index/storage/docstore/azurecosmosnosql/BUILD
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-azurecosmosnosql/llama_index/storage/docstore/azurecosmosnosql/__init__.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-azurecosmosnosql/llama_index/storage/docstore/azurecosmosnosql/base.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-azurecosmosnosql/pyproject.toml
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-azurecosmosnosql/tests/BUILD
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-azurecosmosnosql/tests/__init__.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-azurecosmosnosql/tests/test_storage_document_store_azurecosmosnosql.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-azurecosmosnosql/BUILD
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-azurecosmosnosql/Makefile
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-azurecosmosnosql/README.md
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-azurecosmosnosql/llama_index/storage/index_store/azurecosmosnosql/BUILD
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-azurecosmosnosql/llama_index/storage/index_store/azurecosmosnosql/__init__.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-azurecosmosnosql/llama_index/storage/index_store/azurecosmosnosql/base.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-azurecosmosnosql/pyproject.toml
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-azurecosmosnosql/tests/BUILD
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-azurecosmosnosql/tests/__init__.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-azurecosmosnosql/tests/test_storage_index_store_azurecosmosnosql.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-azurecosmosnosql/BUILD
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-azurecosmosnosql/Makefile
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-azurecosmosnosql/README.md
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-azurecosmosnosql/llama_index/storage/kvstore/azurecosmosnosql/BUILD
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-azurecosmosnosql/llama_index/storage/kvstore/azurecosmosnosql/__init__.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-azurecosmosnosql/llama_index/storage/kvstore/azurecosmosnosql/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-azurecosmosnosql/pyproject.toml
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-azurecosmosnosql/tests/BUILD
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-azurecosmosnosql/tests/__init__.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-azurecosmosnosql/tests/test_storage_azurecosmosnosql_kv_store.py
Labels: lgtm, size:XL

#16371 Make unit testing (usually) mandatory
  .github/pull_request_template.md
Labels: lgtm, size:XS

#16372 run coverage during unit tests, require minimum coverage
  pants.toml
Labels: size:S

#16395 docs: update BGEM3Demo.ipynb
  docs/docs/examples/managed/BGEM3Demo.ipynb
Labels: lgtm, size:XS

#16401 Fix ZyteWebReader article parsing
  docs/docs/examples/data_connectors/WebPageDemo.ipynb
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/zyte_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:M

#16408 don't include tool calls if there was none
  .github/workflows/coverage.yml
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:S

#16410 Fix ChatMessage serialization with janky openai types
  .github/workflows/coverage.yml
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai.py
Labels: size:M

#16314 Add ObjectBox Vector Store Integration
  docs/docs/examples/vector_stores/ObjectBoxIndexDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-objectbox/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-objectbox/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-objectbox/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-objectbox/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-objectbox/llama_index/vector_stores/objectbox/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-objectbox/llama_index/vector_stores/objectbox/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-objectbox/llama_index/vector_stores/objectbox/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-objectbox/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-objectbox/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-objectbox/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-objectbox/tests/test_objectbox.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-objectbox/tests/test_vector_stores_objectbox.py
Labels: lgtm, size:XL

#16406 feat: add Docling reader and node parser
  .github/workflows/coverage.yml
  docs/docs/examples/data_connectors/DoclingReaderDemo.ipynb
  llama-index-integrations/node_parser/llama-index-node-parser-docling/.gitignore
  llama-index-integrations/node_parser/llama-index-node-parser-docling/BUILD
  llama-index-integrations/node_parser/llama-index-node-parser-docling/Makefile
  llama-index-integrations/node_parser/llama-index-node-parser-docling/README.md
  llama-index-integrations/node_parser/llama-index-node-parser-docling/llama_index/node_parser/docling/BUILD
  llama-index-integrations/node_parser/llama-index-node-parser-docling/llama_index/node_parser/docling/__init__.py
  llama-index-integrations/node_parser/llama-index-node-parser-docling/llama_index/node_parser/docling/base.py
  llama-index-integrations/node_parser/llama-index-node-parser-docling/pyproject.toml
  llama-index-integrations/node_parser/llama-index-node-parser-docling/tests/BUILD
  llama-index-integrations/node_parser/llama-index-node-parser-docling/tests/__init__.py
  llama-index-integrations/node_parser/llama-index-node-parser-docling/tests/data/inp_li_doc.json
  llama-index-integrations/node_parser/llama-index-node-parser-docling/tests/data/out_get_nodes_from_docs.json
  llama-index-integrations/node_parser/llama-index-node-parser-docling/tests/data/out_parse_nodes.json
  llama-index-integrations/node_parser/llama-index-node-parser-docling/tests/test_node_parser_docling.py
  llama-index-integrations/readers/llama-index-readers-docling/.gitignore
  llama-index-integrations/readers/llama-index-readers-docling/BUILD
  llama-index-integrations/readers/llama-index-readers-docling/Makefile
  llama-index-integrations/readers/llama-index-readers-docling/README.md
  llama-index-integrations/readers/llama-index-readers-docling/llama_index/readers/docling/BUILD
  llama-index-integrations/readers/llama-index-readers-docling/llama_index/readers/docling/__init__.py
  llama-index-integrations/readers/llama-index-readers-docling/llama_index/readers/docling/base.py
  llama-index-integrations/readers/llama-index-readers-docling/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-docling/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-docling/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-docling/tests/test_readers_docling.py
Labels: lgtm, size:XXL

#16376 MultiModal.HuggingFaceMultiModal: fix errors and README, add stream_complete
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/README.md
Labels: lgtm, size:M

#16425 chore: fix Docling example (Colab env integration, typos)
  docs/docs/examples/data_connectors/DoclingReaderDemo.ipynb
Labels: lgtm, size:L

#16431 fix(bug): fixed bug with ensuring the metadata_mapping value
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/tests/test_azureaisearch.py
Labels: lgtm, size:M

#16420 Notebook fixes for prompt completion
  docs/docs/examples/llm/nvidia_text_completion.ipynb
Labels: lgtm, size:S

#16422 CorrectiveRAG Notebook Error fixes
  docs/docs/examples/workflow/corrective_rag_pack.ipynb
Labels: lgtm, size:S

#16416 docs: update comment syntactic error
  llama-index-core/llama_index/core/agent/custom/simple.py
  llama-index-core/llama_index/core/agent/legacy/react/base.py
  llama-index-core/llama_index/core/agent/react_multimodal/step.py
  llama-index-integrations/agent/llama-index-agent-coa/llama_index/agent/coa/step.py
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/reflective/tool_interactive_reflection.py
  llama-index-integrations/agent/llama-index-agent-llm-compiler/llama_index/agent/llm_compiler/step.py
  llama-index-legacy/llama_index/legacy/agent/custom/simple.py
  llama-index-legacy/llama_index/legacy/agent/legacy/react/base.py
  llama-index-legacy/llama_index/legacy/agent/react/base.py
  llama-index-legacy/llama_index/legacy/agent/react/step.py
  llama-index-legacy/llama_index/legacy/agent/react_multimodal/step.py
  llama-index-packs/llama-index-packs-agents-coa/llama_index/packs/agents_coa/step.py
  llama-index-packs/llama-index-packs-agents-llm-compiler/llama_index/packs/agents_llm_compiler/step.py
Labels: lgtm, size:S

#16413 LlamaMultiModal class bug fix
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/llama_index/multi_modal_llms/huggingface/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/tests/__pycache__/__init__.cpython-312.pyc
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/tests/__pycache__/test_multi_modal_llms_huggingface.cpython-312-pytest-8.3.3.pyc
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/tests/test_images/2dogs.jpg
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/tests/test_images/5cats.jpg
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/tests/test_images/girl_rabbit.jpg
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/tests/test_images/man_read.jpg
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/tests/test_multi_modal_llms_huggingface.py
Labels: lgtm, size:L

#16435 update install command
  .readthedocs.yaml
Labels: size:XS

#16417 Add Zyte serp integration
  docs/docs/examples/data_connectors/ZyteSerpDemo.ipynb
  llama-index-integrations/readers/llama-index-readers-zyte-serp/.gitignore
  llama-index-integrations/readers/llama-index-readers-zyte-serp/BUILD
  llama-index-integrations/readers/llama-index-readers-zyte-serp/Makefile
  llama-index-integrations/readers/llama-index-readers-zyte-serp/README.md
  llama-index-integrations/readers/llama-index-readers-zyte-serp/llama_index/readers/zyte_serp/BUILD
  llama-index-integrations/readers/llama-index-readers-zyte-serp/llama_index/readers/zyte_serp/__init__.py
  llama-index-integrations/readers/llama-index-readers-zyte-serp/llama_index/readers/zyte_serp/base.py
  llama-index-integrations/readers/llama-index-readers-zyte-serp/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-zyte-serp/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-zyte-serp/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-zyte-serp/tests/test_readers_zyte_serp.py
Labels: size:XL

#16308 Add llm integration with Intel Gaudi in llama-index-llms-gaudi
  llama-index-integrations/llms/llama-index-llms-gaudi/.gitignore
  llama-index-integrations/llms/llama-index-llms-gaudi/BUILD
  llama-index-integrations/llms/llama-index-llms-gaudi/Makefile
  llama-index-integrations/llms/llama-index-llms-gaudi/README.md
  llama-index-integrations/llms/llama-index-llms-gaudi/examples/BUILD
  llama-index-integrations/llms/llama-index-llms-gaudi/examples/README.md
  llama-index-integrations/llms/llama-index-llms-gaudi/examples/basic.py
  llama-index-integrations/llms/llama-index-llms-gaudi/llama_index/llms/gaudi/BUILD
  llama-index-integrations/llms/llama-index-llms-gaudi/llama_index/llms/gaudi/__init__.py
  llama-index-integrations/llms/llama-index-llms-gaudi/llama_index/llms/gaudi/base.py
  llama-index-integrations/llms/llama-index-llms-gaudi/llama_index/llms/gaudi/utils.py
  llama-index-integrations/llms/llama-index-llms-gaudi/pyproject.toml
Labels: lgtm, size:XXL

#16436 v0.11.17
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:M

#16444 Fix neo4j database connection
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/base.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-neo4jvector/llama_index/vector_stores/neo4jvector/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-neo4jvector/pyproject.toml
Labels: size:S

#16448 feat: add chatpgt-4o-latest model
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:XS

#16440 Remove Python version upper bound from fireworks package to support latest python version
  llama-index-integrations/embeddings/llama-index-embeddings-fireworks/pyproject.toml
Labels: lgtm, size:XS

#16445 Fixed sql_retriever.py bug
  llama-index-core/llama_index/core/indices/struct_store/sql_retriever.py
Labels: lgtm, size:XS

#16447 Fix: Handle Empty Nodes List in Retrieval while adding text
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/base.py
Labels: lgtm, size:XS

#16492 docs: make build work with latest llama_deploy updates
  docs/mkdocs.yml
  docs/poetry.lock
  docs/pyproject.toml
  docs/scripts/merge_llama_deploy_docs.py
Labels: lgtm, size:M

#16491 Corrected Bedrock example
  docs/docs/examples/embeddings/bedrock.ipynb
Labels: lgtm, size:XS

#16481 chore: Avoid InvalidStateError edge case
  llama-index-core/llama_index/core/workflow/workflow.py
Labels: lgtm, size:XS

#16439 Fix typo in Property Graph Index docs (lpg_index_guide.md) and update args
  docs/docs/module_guides/indexing/lpg_index_guide.md
Labels: lgtm, size:XS

#16494 Update model name typo in Qdrant utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
Labels: lgtm, size:XS

#16489 Fixed issue #14728 for similarity score from Weaviate
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/tests/test_vector_stores_weaviate.py
Labels: lgtm, size:M

#16486 LINK: checking relative path ref correction in q_and_a docs page
  docs/docs/understanding/putting_it_all_together/q_and_a/index.md
Labels: lgtm, size:S

#16446 add zhipuai llm class
  llama-index-integrations/llms/llama-index-llms-zhipuai/.gitignore
  llama-index-integrations/llms/llama-index-llms-zhipuai/BUILD
  llama-index-integrations/llms/llama-index-llms-zhipuai/Makefile
  llama-index-integrations/llms/llama-index-llms-zhipuai/README.md
  llama-index-integrations/llms/llama-index-llms-zhipuai/llama_index/llms/zhipuai/BUILD
  llama-index-integrations/llms/llama-index-llms-zhipuai/llama_index/llms/zhipuai/__init__.py
  llama-index-integrations/llms/llama-index-llms-zhipuai/llama_index/llms/zhipuai/base.py
  llama-index-integrations/llms/llama-index-llms-zhipuai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-zhipuai/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-zhipuai/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-zhipuai/tests/test_llms_zhipuai.py
Labels: lgtm, size:XL

#16502 Add Argilla tutorial to evaluation examples
  docs/docs/examples/evaluation/step_back_argilla.ipynb
  docs/mkdocs.yml
Labels: lgtm, size:XS

#16496 Propagate default_headers in AnthropicMultiModal
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/llama_index/multi_modal_llms/anthropic/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/pyproject.toml
Labels: lgtm, size:XS

#16478 Add anthropic bedrock
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-anthropic/tests/test_llms_anthropic.py
Labels: lgtm, size:L

#16510 Update README.md
  README.md
Labels: lgtm, size:S

#16512 Quick fix to workflow streaming docs
  docs/docs/understanding/workflows/stream.md
Labels: lgtm, size:S

#16437 Add vector store integration for Nile (multi-tenant postgres)
  docs/docs/examples/vector_stores/NileVectorStore.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/examples/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/examples/multitenant.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/llama_index/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/llama_index/py.typed
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/llama_index/vector_stores/nile/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/llama_index/vector_stores/nile/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/llama_index/vector_stores/nile/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/poetry.lock
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/tests/test_vector_stores_nile.py
Labels: lgtm, size:XXL

#16515 fix[chroma]: Chroma versions 0.5.7-0.5.12 deprecation
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/pyproject.toml
Labels: lgtm, size:XS

#16527 Fix Databricks `structured_predict`
  llama-index-integrations/llms/llama-index-llms-databricks/llama_index/llms/databricks/base.py
  llama-index-integrations/llms/llama-index-llms-databricks/pyproject.toml
Labels: lgtm, size:S

#16531 Fix async methods in azure chat store
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azure/llama_index/storage/chat_store/azure/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azure/pyproject.toml
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azure/tests/test_chat_store_azure_chat_store.py
Labels: size:L

#16099 feat: add solar pro llm and document parser
  llama-index-integrations/llms/llama-index-llms-upstage/llama_index/llms/upstage/base.py
  llama-index-integrations/llms/llama-index-llms-upstage/llama_index/llms/upstage/utils.py
  llama-index-integrations/llms/llama-index-llms-upstage/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-upstage/README.md
  llama-index-integrations/readers/llama-index-readers-upstage/examples/UpstageDocumentParseReader.ipynb
  llama-index-integrations/readers/llama-index-readers-upstage/examples/UpstageLayoutAnalysisReader.ipynb
  llama-index-integrations/readers/llama-index-readers-upstage/llama_index/readers/upstage/__init__.py
  llama-index-integrations/readers/llama-index-readers-upstage/llama_index/readers/upstage/document_parse.py
  llama-index-integrations/readers/llama-index-readers-upstage/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-upstage/tests/test_readers_upstage.py
Labels: lgtm, size:XL

#16305 Added Document360Reader. Contributed by the PLACE team.
  llama-index-integrations/readers/llama-index-readers-document360/.gitignore
  llama-index-integrations/readers/llama-index-readers-document360/BUILD
  llama-index-integrations/readers/llama-index-readers-document360/Makefile
  llama-index-integrations/readers/llama-index-readers-document360/README.md
  llama-index-integrations/readers/llama-index-readers-document360/examples/document360.ipynb
  llama-index-integrations/readers/llama-index-readers-document360/llama_index/readers/document360/BUILD
  llama-index-integrations/readers/llama-index-readers-document360/llama_index/readers/document360/__init__.py
  llama-index-integrations/readers/llama-index-readers-document360/llama_index/readers/document360/base.py
  llama-index-integrations/readers/llama-index-readers-document360/llama_index/readers/document360/entities/__init__.py
  llama-index-integrations/readers/llama-index-readers-document360/llama_index/readers/document360/entities/article.py
  llama-index-integrations/readers/llama-index-readers-document360/llama_index/readers/document360/entities/article_slim.py
  llama-index-integrations/readers/llama-index-readers-document360/llama_index/readers/document360/entities/category.py
  llama-index-integrations/readers/llama-index-readers-document360/llama_index/readers/document360/entities/project_version.py
  llama-index-integrations/readers/llama-index-readers-document360/llama_index/readers/document360/errors.py
  llama-index-integrations/readers/llama-index-readers-document360/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-document360/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-document360/tests/test_readers_document360.py
Labels: lgtm, size:XXL

#16535 add build files
  llama-index-integrations/readers/llama-index-readers-document360/llama_index/readers/document360/entities/BUILD
  llama-index-integrations/readers/llama-index-readers-document360/tests/BUILD
Labels: size:XS

#16487 Fix format temp function
  llama-index-integrations/tools/llama-index-tools-weather/llama_index/tools/weather/base.py
  llama-index-integrations/tools/llama-index-tools-weather/pyproject.toml
Labels: lgtm, size:XS

#16345 Add Memgraph integration
  docs/docs/examples/property_graph/property_graph_memgraph.ipynb
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/BUILD
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/Makefile
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/README.md
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/llama_index/graph_stores/memgraph/BUILD
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/llama_index/graph_stores/memgraph/__init__.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/llama_index/graph_stores/memgraph/kg_base.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/llama_index/graph_stores/memgraph/property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/pyproject.toml
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/tests/BUILD
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/tests/__init__.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/tests/test_graph_stores_memgraph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/tests/test_pg_stores_memgraph.py
Labels: size:XXL

#16393 Use efficient kNN filtering, fix filtering when input value is array of string
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/tests/test_opensearch_client.py
Labels: lgtm, size:XL

#16539 fix timescale vector store class
  llama-index-integrations/vector_stores/llama-index-vector-stores-timescalevector/llama_index/vector_stores/timescalevector/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-timescalevector/pyproject.toml
Labels: size:XS

#16542 Update base.py
  llama-index-integrations/embeddings/llama-index-embeddings-oracleai/llama_index/embeddings/oracleai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-oracleai/pyproject.toml
Labels: lgtm, size:S

#16545 distance strategy fix..
  llama-index-integrations/vector_stores/llama-index-vector-stores-oracledb/llama_index/vector_stores/oracledb/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-oracledb/pyproject.toml
Labels: lgtm, size:XS

#16541 Update README.md for Oracle AI Vector Store
  llama-index-integrations/vector_stores/llama-index-vector-stores-oracledb/README.md
Labels: lgtm, size:L

#16544 Fix generate_qa_embedding_pairs usage in the examples
  docs/docs/examples/finetuning/embeddings/finetune_embedding.ipynb
Labels: lgtm, size:S

#16537 docs: fix dead links in the documentation
  docs/docs/getting_started/starter_tools/rag_cli.md
  docs/docs/module_guides/indexing/metadata_extraction.md
  docs/docs/module_guides/models/llms/usage_custom.md
  docs/docs/understanding/putting_it_all_together/q_and_a/terms_definitions_tutorial.md
  llama-index-core/CONTRIBUTING.md
Labels: lgtm, size:M

#16536 Fix Oracle vector store integration
  llama-index-integrations/vector_stores/llama-index-vector-stores-oracledb/llama_index/vector_stores/oracledb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-oracledb/pyproject.toml
Labels: lgtm, size:S

#16532 support timeout param in litellmembedding
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/llama_index/embeddings/litellm/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/pyproject.toml
Labels: lgtm, size:S

#16519 feat[elasticsearch]: Add Support for Custom Metadata Keyword Suffix in Elasticsearch Integration
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/tests/test_vector_stores_elasticsearch.py
Labels: lgtm, size:M

#16552 Typo in Vectorstore docs
  docs/docs/examples/vector_stores/WeaviateIndex_auto_retriever.ipynb
  docs/docs/examples/vector_stores/chroma_auto_retriever.ipynb
Labels: lgtm, size:XS

#16513 update zhipuai llm and fix issues
  llama-index-integrations/llms/llama-index-llms-zhipuai/README.md
  llama-index-integrations/llms/llama-index-llms-zhipuai/llama_index/llms/zhipuai/base.py
  llama-index-integrations/llms/llama-index-llms-zhipuai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-zhipuai/tests/test_llms_zhipuai.py
Labels: lgtm, size:M

#16560 allow passing in openai clients directly
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:XS

#16559 Fix pydantic errors in upstash_chat_store
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-upstash/llama_index/storage/chat_store/upstash/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-upstash/pyproject.toml
Labels: lgtm, size:XS

#16564 Query Planning Workflow
  docs/docs/examples/workflow/planning_workflow.ipynb
  docs/docs/module_guides/workflow/index.md
Labels: size:L

#16568 Added check for fine-tuned models in function_calling method
  .github/workflows/build_package.yml
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:S

#16571 Add support for mistral latest models
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/utils.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
Labels: size:S

#16548 Refine CONTRIBUTING.md Documentation
  CONTRIBUTING.md
Labels: lgtm, size:XL

#16557 feat: postgres chat store Integration
  docs/docs/module_guides/storing/chat_stores.md
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/.gitignore
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/Makefile
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/README.md
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/llama_index/storage/chat_store/postgres/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/llama_index/storage/chat_store/postgres/__init__.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/llama_index/storage/chat_store/postgres/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/pyproject.toml
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/tests/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/tests/__init__.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/tests/test_chat_store_postgres_chat_store.py
Labels: lgtm, size:XL

#16585 Fix structured predict type hints
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/cypher_template.py
  llama-index-core/llama_index/core/llms/llm.py
  llama-index-core/llama_index/core/program/utils.py
  llama-index-core/llama_index/core/query_engine/retriever_query_engine.py
  llama-index-core/llama_index/core/response_synthesizers/accumulate.py
  llama-index-core/llama_index/core/response_synthesizers/base.py
  llama-index-core/llama_index/core/response_synthesizers/factory.py
  llama-index-core/llama_index/core/response_synthesizers/refine.py
  llama-index-core/llama_index/core/response_synthesizers/tree_summarize.py
Labels: lgtm, size:L

#16581 Add DiskANN for Azure Cosmos DB Mongo vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosmongo/llama_index/vector_stores/azurecosmosmongo/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosmongo/pyproject.toml
Labels: lgtm, size:M

#16554 Add OpenClip support through OpenVINO embedding
  docs/docs/examples/embeddings/openvino.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/llama_index/embeddings/huggingface_openvino/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/llama_index/embeddings/huggingface_openvino/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/pyproject.toml
Labels: lgtm, size:L

#16551 add zhipuai multi modal llm class
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-zhipuai/.gitignore
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-zhipuai/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-zhipuai/Makefile
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-zhipuai/README.md
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-zhipuai/llama_index/multi_modal_llms/zhipuai/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-zhipuai/llama_index/multi_modal_llms/zhipuai/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-zhipuai/llama_index/multi_modal_llms/zhipuai/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-zhipuai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-zhipuai/tests/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-zhipuai/tests/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-zhipuai/tests/test_multi_modal_llms_zhipuai.py
Labels: lgtm, size:XL

#16327 Use port of redirect uri in credential file to run local server in GoogleDocsReader
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/docs/base.py
  llama-index-integrations/readers/llama-index-readers-google/pyproject.toml
Labels: lgtm, size:S

#16550 Add vector store integration of OceanBase
  docs/docs/community/integrations/vector_stores.md
  docs/docs/examples/vector_stores/OceanBaseVectorStore.ipynb
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/llama_index/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/llama_index/py.typed
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/llama_index/vector_stores/oceanbase/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/llama_index/vector_stores/oceanbase/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/llama_index/vector_stores/oceanbase/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/tests/test_vector_stores_oceanbase.py
Labels: lgtm, size:XXL

#16558 Kdbai v1.4
  docs/docs/examples/vector_stores/KDBAI_Advanced_RAG_Demo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-kdbai/llama_index/vector_stores/kdbai/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-kdbai/llama_index/vector_stores/kdbai/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-kdbai/pyproject.toml
Labels: lgtm, size:XL

#16586 fix: pass params to VectorStoreQuery
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/vector.py
Labels: lgtm, size:S

#16590 disable failing zenguard test
  llama-index-packs/llama-index-packs-zenguard/tests/test_packs_zenguard.py
Labels: size:S

#16597 Use Replicate streaming API
  llama-index-integrations/llms/llama-index-llms-replicate/llama_index/llms/replicate/base.py
  llama-index-integrations/llms/llama-index-llms-replicate/pyproject.toml
Labels: lgtm, size:XS

#16598 fix: receive warnings from dbms server in neo4j queries
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: lgtm, size:S

#16589 Feat: IBM watsonx.ai Chat integration
  llama-index-integrations/llms/llama-index-llms-ibm/llama_index/llms/ibm/base.py
  llama-index-integrations/llms/llama-index-llms-ibm/llama_index/llms/ibm/utils.py
  llama-index-integrations/llms/llama-index-llms-ibm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ibm/tests/test_ibm.py
Labels: lgtm, size:L

#16521 Add embedding integration with Intel Gaudi in llama-index-embeddings-gaudi
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/examples/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/examples/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/examples/basic.py
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/examples/graphrag.py
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/examples/requirements.txt
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/llama_index/embeddings/gaudi/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/llama_index/embeddings/gaudi/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/llama_index/embeddings/gaudi/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/llama_index/embeddings/gaudi/utils.py
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-gigachat/llama_index/embeddings/gigachat/base.py
Labels: lgtm, size:XL

#16603 Raise errors in instrumentation properly
  llama-index-core/llama_index/core/instrumentation/dispatcher.py
Labels: size:XS

#16606 v0.11.19
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/CONTRIBUTING.md
  docs/docs/api_reference/embeddings/gaudi.md
  docs/docs/api_reference/multi_modal_llms/openvino.md
  docs/docs/api_reference/multi_modal_llms/zhipuai.md
  docs/docs/api_reference/storage/chat_store/postgres.md
  docs/docs/api_reference/storage/vector_store/oceanbase.md
  docs/docs/examples/multi_modal/openvino_multimodal.ipynb
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:XXL

#16618 workflow docs nit
  docs/docs/module_guides/workflow/index.md
  llama-index-core/llama_index/core/workflow/__init__.py
Labels: lgtm, size:S

#16617 correct wording in introduction
  docs/docs/index.md
Labels: lgtm, size:XS

#16624 Fix drawing for HITL
  llama-index-utils/llama-index-utils-workflow/llama_index/utils/workflow/draw.py
  llama-index-utils/llama-index-utils-workflow/pyproject.toml
Labels: lgtm, size:M

#16627 Fix index
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-vectara/tests/test_indices_managed_vectara.py
Labels: size:L

#16509 Add support for Couchbase for DocStore & IndexStore
  docs/docs/module_guides/storing/docstores.md
  docs/docs/module_guides/storing/index_stores.md
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-couchbase/.gitignore
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-couchbase/BUILD
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-couchbase/Makefile
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-couchbase/README.md
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-couchbase/llama_index/storage/docstore/couchbase/BUILD
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-couchbase/llama_index/storage/docstore/couchbase/__init__.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-couchbase/llama_index/storage/docstore/couchbase/base.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-couchbase/pyproject.toml
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-couchbase/tests/BUILD
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-couchbase/tests/__init__.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-couchbase/tests/test_docstore_couchbase.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-couchbase/.gitignore
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-couchbase/BUILD
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-couchbase/Makefile
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-couchbase/README.md
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-couchbase/llama_index/storage/index_store/couchbase/BUILD
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-couchbase/llama_index/storage/index_store/couchbase/__init__.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-couchbase/llama_index/storage/index_store/couchbase/base.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-couchbase/pyproject.toml
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-couchbase/tests/BUILD
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-couchbase/tests/__init__.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-couchbase/tests/test_index_store_couchbase.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-couchbase/.gitignore
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-couchbase/BUILD
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-couchbase/Makefile
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-couchbase/README.md
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-couchbase/llama_index/storage/kvstore/couchbase/BUILD
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-couchbase/llama_index/storage/kvstore/couchbase/__init__.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-couchbase/llama_index/storage/kvstore/couchbase/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-couchbase/pyproject.toml
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-couchbase/tests/BUILD
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-couchbase/tests/__init__.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-couchbase/tests/test_kvstore_couchbase.py
Labels: size:XL

#15753 Reka llamaindex integration (llm and multi-modal-llm)
  llama-index-integrations/llms/llama-index-llms-reka/.gitignore
  llama-index-integrations/llms/llama-index-llms-reka/BUILD
  llama-index-integrations/llms/llama-index-llms-reka/Makefile
  llama-index-integrations/llms/llama-index-llms-reka/README.md
  llama-index-integrations/llms/llama-index-llms-reka/llama_index/llms/reka/BUILD
  llama-index-integrations/llms/llama-index-llms-reka/llama_index/llms/reka/__init__.py
  llama-index-integrations/llms/llama-index-llms-reka/llama_index/llms/reka/base.py
  llama-index-integrations/llms/llama-index-llms-reka/llama_index_reka_samplenotebook.ipynb
  llama-index-integrations/llms/llama-index-llms-reka/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-reka/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-reka/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-reka/tests/test_llms_reka.py
  llama-index-integrations/llms/llama-index-llms-reka/tests/test_reka.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-reka/.gitignore
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-reka/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-reka/Makefile
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-reka/README.md
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-reka/llama_index/multi_modal_llms/reka/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-reka/llama_index/multi_modal_llms/reka/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-reka/llama_index/multi_modal_llms/reka/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-reka/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-reka/tests/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-reka/tests/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-reka/tests/test_multi_modal_llms_reka.py
  poetry.lock
Labels: lgtm, size:XXL

#16643 update anthropic model names
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: size:S

#16632 add missing dependency for mongodb kvstore
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-mongodb/pyproject.toml
Labels: size:XS

#16636 fix: skip processing of choice.delta when it is None
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/llama_index/multi_modal_llms/openai/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/pyproject.toml
  llama-index-legacy/llama_index/legacy/llms/openai.py
  llama-index-legacy/llama_index/legacy/multi_modal_llms/openai.py
Labels: lgtm, size:M

#16655 fix typo in OpenVINO multimodal example
  docs/docs/examples/multi_modal/openvino_multimodal.ipynb
  llama-index-legacy/llama_index/legacy/llms/openai.py
Labels: size:XS

#16651 Make neo4j schema refresh configurable
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/base.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: lgtm, size:S

#16648 Add TLM's explainability feature and update docs
  docs/docs/examples/cookbooks/cleanlab_tlm_rag.ipynb
  docs/docs/examples/llm/cleanlab.ipynb
  llama-index-integrations/llms/llama-index-llms-cleanlab/llama_index/llms/cleanlab/base.py
  llama-index-integrations/llms/llama-index-llms-cleanlab/pyproject.toml
Labels: lgtm, size:L

#16661 fix docs build
  docs/docs/api_reference/llms/reka.md
  docs/docs/api_reference/multi_modal_llms/reka.md
  docs/docs/api_reference/storage/docstore/couchbase.md
  docs/docs/api_reference/storage/index_store/couchbase.md
  docs/docs/api_reference/storage/kvstore/couchbase.md
  docs/mkdocs.yml
  docs/scripts/prepare_for_build.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-reka/pyproject.toml
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-couchbase/pyproject.toml
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-couchbase/pyproject.toml
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-couchbase/pyproject.toml
Labels: lgtm, size:M

#16662 add retry logic to requests in cases where access token expires
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/llama_index/readers/microsoft_sharepoint/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/tests/test_readers_microsoft_sharepoint.py
Labels: lgtm, size:M

#16663 Update Messaging in Demo Notebook
  docs/docs/examples/managed/vectaraDemo.ipynb
Labels: lgtm, size:L

#16665 Fix BUG where the api_key parameter is not set when calling DashScopeRerank.
  llama-index-integrations/postprocessor/llama-index-postprocessor-dashscope-rerank/llama_index/postprocessor/dashscope_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-dashscope-rerank/pyproject.toml
Labels: lgtm, size:XS

#16667 Add support for cohere multi-modal embeddings
  docs/docs/examples/embeddings/cohereai.ipynb
  docs/docs/examples/multi_modal/cohere_multi_modal.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/llama_index/embeddings/cohere/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/pyproject.toml
Labels: lgtm, size:M

#16682 fix: show `Workflow`'s constructor documentation
  docs/docs/api_reference/workflow/workflow.md
Labels: lgtm, size:XS

#16683 Various docs tweaks
  docs/docs/getting_started/concepts.md
  docs/docs/llama_cloud/llama_parse.md
  docs/docs/understanding/agent/index.md
  docs/docs/understanding/loading/llamacloud.md
  docs/docs/understanding/rag/index.md
  docs/mkdocs.yml
  docs/overrides/main.html
Labels: lgtm, size:L

#16684 More docs tweaks
  docs/docs/examples/agent/lats_agent.ipynb
  docs/docs/llama_cloud/index.md
  docs/docs/llama_cloud/llama_parse.md
  docs/docs/module_guides/workflow/index.md
Labels: lgtm, size:M

#16685 v0.11.20
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#16698 update bedrock models
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
Labels: size:S

#16699 Fix anthropic multimodal deps conflict, update models
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/llama_index/multi_modal_llms/anthropic/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/pyproject.toml
Labels: size:XS

#16695 add nvidia/llama-3.2-nv-rerankqa-1b-v1 to set of supported models
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/pyproject.toml
Labels: lgtm, size:XS

#16694 add nvidia/llama-3.2-nv-embedqa-1b-v1 to set of supported models
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
Labels: lgtm, size:XS

#16692 adding additional claude model name, for vertex AI
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: lgtm, size:XS

#16691 Add RAG with LlamaCloud example with OpenAI LLM
  docs/docs/examples/llm/openai.ipynb
Labels: lgtm, size:L

#16658 add Toolhouse cookbook
  docs/docs/examples/cookbooks/toolhouse_llamaindex.ipynb
Labels: lgtm, size:L

#16690 Fix typo in openvino clip model doc
  docs/docs/examples/embeddings/openvino.ipynb
Labels: lgtm, size:XS

#16671 [Fix]Error that occurs when querying a Weaviate database that is not built with llama-index
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/pyproject.toml
Labels: lgtm, size:XS

#16700 fix deeplake (again)
  llama-index-integrations/vector_stores/llama-index-vector-stores-deeplake/pyproject.toml
Labels: size:XS

#16702 add new sonnet3.5 to function calling bedrock converse models
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
Labels: size:XS

#16686 Fixing a verbose issue and making sql errors more informative
  llama-index-core/llama_index/core/indices/struct_store/sql_retriever.py
  llama-index-core/llama_index/core/utilities/sql_wrapper.py
Labels: lgtm, size:XS

#16677 feat: update Docling reader & node parser to Docling v2
  docs/docs/examples/data_connectors/DoclingReaderDemo.ipynb
  docs/docs/module_guides/loading/connector/modules.md
  llama-index-integrations/node_parser/llama-index-node-parser-docling/README.md
  llama-index-integrations/node_parser/llama-index-node-parser-docling/llama_index/node_parser/docling/base.py
  llama-index-integrations/node_parser/llama-index-node-parser-docling/pyproject.toml
  llama-index-integrations/node_parser/llama-index-node-parser-docling/tests/test_node_parser_docling.py
  llama-index-integrations/readers/llama-index-readers-docling/README.md
  llama-index-integrations/readers/llama-index-readers-docling/llama_index/readers/docling/base.py
  llama-index-integrations/readers/llama-index-readers-docling/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-docling/tests/test_readers_docling.py
Labels: lgtm, size:XL

#16673 Fixed issue with persistence, rearranged and added new options to construction of HnswlibVectorStore
  docs/docs/community/integrations/vector_stores.md
  docs/docs/examples/vector_stores/HnswlibIndexDemo.ipynb
  docs/docs/module_guides/storing/vector_stores.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-hnswlib/llama_index/vector_stores/hnswlib/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-hnswlib/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-hnswlib/tests/test_vector_stores_hnswlib.py
  poetry.lock
  pyproject.toml
Labels: lgtm, size:L

#16646 feat: add permissions to one drive
  llama-index-integrations/readers/llama-index-readers-microsoft-onedrive/llama_index/readers/microsoft_onedrive/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-onedrive/pyproject.toml
Labels: lgtm, size:L

#16653 Added get_nodes() function in AISearch vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
Labels: lgtm, size:M

#16610 Pipeshift llama index integration
  docs/docs/api_reference/llms/pipeshift.md
  docs/docs/examples/llm/pipeshift.ipynb
  docs/docs/module_guides/models/llms/modules.md
  docs/mkdocs.yml
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/llms/llama-index-llms-pipeshift/.gitignore
  llama-index-integrations/llms/llama-index-llms-pipeshift/BUILD
  llama-index-integrations/llms/llama-index-llms-pipeshift/Makefile
  llama-index-integrations/llms/llama-index-llms-pipeshift/README.md
  llama-index-integrations/llms/llama-index-llms-pipeshift/llama_index/llms/pipeshift/BUILD
  llama-index-integrations/llms/llama-index-llms-pipeshift/llama_index/llms/pipeshift/__init__.py
  llama-index-integrations/llms/llama-index-llms-pipeshift/llama_index/llms/pipeshift/base.py
  llama-index-integrations/llms/llama-index-llms-pipeshift/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-pipeshift/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-pipeshift/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-pipeshift/tests/test_llms_pipeshift.py
Labels: lgtm, size:XL

#16645 Add missing awaits in azure chat store
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azure/llama_index/storage/chat_store/azure/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azure/pyproject.toml
Labels: size:S

#16705 fix: bump marvin
  llama-index-integrations/extractors/llama-index-extractors-marvin/pyproject.toml
Labels: lgtm, size:XS

#16706 build: fix Docling reader package build
  llama-index-integrations/readers/llama-index-readers-docling/pyproject.toml
Labels: lgtm, size:XS

#16715 Update readme for Upstage DocumentParse
  llama-index-integrations/readers/llama-index-readers-upstage/README.md
Labels: lgtm, size:XS

#16724 fix return type check on workflows
  llama-index-core/llama_index/core/workflow/workflow.py
Labels: lgtm, size:XS

#16723 Improve Bedrock Tool Calling
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: lgtm, size:M

#16722 Add Vectara Query Tool
  llama-index-integrations/tools/llama-index-tools-vectara-query/.gitignore
  llama-index-integrations/tools/llama-index-tools-vectara-query/BUILD
  llama-index-integrations/tools/llama-index-tools-vectara-query/Makefile
  llama-index-integrations/tools/llama-index-tools-vectara-query/README.md
  llama-index-integrations/tools/llama-index-tools-vectara-query/examples/vectara_query.ipynb
  llama-index-integrations/tools/llama-index-tools-vectara-query/llama_index/tools/vectara_query/BUILD
  llama-index-integrations/tools/llama-index-tools-vectara-query/llama_index/tools/vectara_query/__init__.py
  llama-index-integrations/tools/llama-index-tools-vectara-query/llama_index/tools/vectara_query/base.py
  llama-index-integrations/tools/llama-index-tools-vectara-query/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-vectara-query/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-vectara-query/tests/__init__.py
  llama-index-integrations/tools/llama-index-tools-vectara-query/tests/test_tools_vectara_query.py
Labels: lgtm, size:XL
