Repository run-llama/llama_index, pull requests merged in 2024-03, with the labels that each got.

#11491 Add: FeishuWikiReader
  llama-index-integrations/readers/llama-index-readers-feishu-wiki/.gitignore
  llama-index-integrations/readers/llama-index-readers-feishu-wiki/BUILD
  llama-index-integrations/readers/llama-index-readers-feishu-wiki/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-feishu-wiki/Makefile
  llama-index-integrations/readers/llama-index-readers-feishu-wiki/README.md
  llama-index-integrations/readers/llama-index-readers-feishu-wiki/llama_index/readers/feishu_wiki/BUILD
  llama-index-integrations/readers/llama-index-readers-feishu-wiki/llama_index/readers/feishu_wiki/__init__.py
  llama-index-integrations/readers/llama-index-readers-feishu-wiki/llama_index/readers/feishu_wiki/base.py
  llama-index-integrations/readers/llama-index-readers-feishu-wiki/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-feishu-wiki/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-feishu-wiki/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-feishu-wiki/tests/test_readers_feishu_wiki.py
Labels: lgtm, size:L

#11524 fix ollama query engine pack notebook.
  docs/examples/llama_hub/llama_pack_ollama.ipynb
Labels: lgtm, size:XS

#11530 Fixed some minor gramatical issues
  docs/presentations/materials/2024-02-28-rag-bootcamp-vector-institute.ipynb
  docs/use_cases/chatbots.md
  docs/use_cases/multimodal.md
Labels: lgtm, size:S

#11536 Add mixedbread reranker cookbook
  docs/cookbooks/mixedbread_reranker.ipynb
  docs/module_guides/querying/node_postprocessors/node_postprocessors.md
Labels: size:L

#11542 Updated the simple fusion to handle duplicate nodes
  llama-index-core/llama_index/core/retrievers/fusion_retriever.py
  llama-index-legacy/llama_index/legacy/retrievers/fusion_retriever.py
Labels: lgtm, size:S

#11544 fix import error in CLI
  llama-index-cli/llama_index/cli/command_line.py
  llama-index-cli/pyproject.toml
Labels: size:XS

#11463 VideoDB Integration for Retrievers
  docs/examples/retrievers/videodb_retriever.ipynb
  docs/module_guides/querying/retriever/retrievers.md
  llama-index-integrations/retrievers/llama-index-retrievers-videodb/.gitignore
  llama-index-integrations/retrievers/llama-index-retrievers-videodb/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-videodb/MAKEFILE
  llama-index-integrations/retrievers/llama-index-retrievers-videodb/README.md
  llama-index-integrations/retrievers/llama-index-retrievers-videodb/llama_index/retrievers/videodb/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-videodb/llama_index/retrievers/videodb/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-videodb/llama_index/retrievers/videodb/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-videodb/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-videodb/tests/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-videodb/tests/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-videodb/tests/test_retrievers_videdb.py
Labels: lgtm, size:XL

#11548 Prevent async_response_gen from Stalling with asyncio Timeout
  llama-index-core/llama_index/core/chat_engine/types.py
Labels: lgtm, size:S

#11513 Add async capability to OpensearchVectorStore
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/tests/docker-compose.yml
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/tests/test_opensearch_client.py
Labels: lgtm, size:L

#11324 feat: adds langfuse callback handler
  docs/examples/callbacks/LangfuseCallbackHandler.ipynb
  docs/module_guides/observability/observability.md
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/callbacks/global_handlers.py
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/BUILD
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/Makefile
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/README.md
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/llama_index/callbacks/langfuse/BUILD
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/llama_index/callbacks/langfuse/__init__.py
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/llama_index/callbacks/langfuse/base.py
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/pyproject.toml
Labels: lgtm, size:L

#11551 Logan/v0.10.15
  CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-ollama/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:S

#11575 GHA: Add Check for repo source
  .github/workflows/publish_release.yml
  .github/workflows/publish_sub_package.yml
Labels: lgtm, size:XS

#11576 docs: fixes LangfuseCallbackHandler link
  docs/examples/callbacks/LangfuseCallbackHandler.ipynb
  docs/module_guides/observability/callbacks/root.md
  docs/module_guides/observability/observability.md
Labels: lgtm, size:S

#11566 Fix Issue 11565 - The MilvusVectorStore MetaDataFilters FilterCondition.OR is ignored
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
Labels: lgtm, size:XS

#11583 add syntatic sugar to create chat prompt / chat message more easily
  docs/examples/customization/prompts/chat_prompts.ipynb
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/llama_index/core/prompts/base.py
Labels: lgtm, size:L

#11577 Corrected colab links
  docs/module_guides/models/llms.md
Labels: lgtm, size:S

#11571 Fix URLs in Prompts documentation
  docs/module_guides/models/prompts.md
Labels: lgtm, size:XS

#11562 tqdm: add tdqm.gather
  llama-index-core/llama_index/core/base/embeddings/base.py
  llama-index-core/llama_index/core/embeddings/multi_modal_base.py
  llama-index-legacy/llama_index/legacy/core/embeddings/base.py
  llama-index-legacy/llama_index/legacy/embeddings/multi_modal_base.py
Labels: lgtm, size:M

#11572 Feature: Improve batch embedding generation throughput for Cohere in Bedrock
  docs/examples/embeddings/bedrock.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/llama_index/embeddings/bedrock/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/tests/test_bedrock.py
Labels: lgtm, size:L

#11563 Fix empty metadata error for CSV Reader
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/tabular/base.py
Labels: lgtm, size:XS

#11611 Solve issue in custom_agent document , RetryAgentWorker._run_step() got an unexpected keyword argument 'input'
  docs/examples/agent/custom_agent.ipynb
Labels: lgtm, size:XS

#11603 Updated model information for Perplexity.ai
  llama-index-integrations/llms/llama-index-llms-perplexity/llama_index/llms/perplexity/base.py
  llama-index-integrations/llms/llama-index-llms-perplexity/pyproject.toml
Labels: lgtm, size:S

#11613 Updated AzureCosmosDBMongoDBVectorSearch to Pydantic Vector Store base class
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosmongo/llama_index/vector_stores/azurecosmosmongo/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosmongo/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosmongo/tests/test_vector_stores_azurecosmosmongo.py
Labels: lgtm, size:S

#11617 fix composable retrieval
  docs/examples/query_engine/recursive_retriever_agents.ipynb
  llama-index-core/llama_index/core/indices/base.py
Labels: lgtm, size:S

#11618 Bumped Opensearch Integration Version
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
Labels: lgtm, size:XS

#11612 Update anthropic models
  docs/examples/llm/anthropic.ipynb
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: lgtm, size:L

#11623 Add Anthropic Multi Modal
  docs/examples/multi_modal/anthropic_multi_modal.ipynb
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/.gitignore
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/Makefile
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/README.md
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/llama_index/multi_modal_llms/anthropic/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/llama_index/multi_modal_llms/anthropic/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/llama_index/multi_modal_llms/anthropic/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/llama_index/multi_modal_llms/anthropic/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/tests/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/tests/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/tests/test_multi-modal-llms_anthropic.py
Labels: lgtm, size:XL

#11628 typo in chat refine prompt
  llama-index-core/llama_index/core/prompts/chat_prompts.py
Labels: lgtm, size:XS

#11622 Added Nest Asyncio to Opensearch Client Init to Support ASGI applicat…
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
Labels: lgtm, size:XS

#11631 fix pydantic
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/llama_index/vector_stores/clickhouse/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/pyproject.toml
Labels: size:XS

#11639 extend claude 3 multimodal cookbook
  docs/examples/multi_modal/anthropic_multi_modal.ipynb
  llama-index-core/llama_index/core/program/multi_modal_llm_program.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/llama_index/multi_modal_llms/anthropic/utils.py
Labels: lgtm, size:S

#11636 fix anthropic tokenizer
  docs/examples/llm/anthropic.ipynb
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
Labels: size:M

#11643 Update multimodal anthropic docs
  docs/module_guides/models/multi_modal.md
Labels: lgtm, size:XS

#11511 Fixes for Gemini inside Vertex
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/llama_index/core/utilities/gemini_utils.py
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/utils.py
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/utils.py
  llama-index-integrations/llms/llama-index-llms-vertex/pyproject.toml
Labels: lgtm, size:L

#11656 Improve Anthropic MM models
  docs/examples/multi_modal/anthropic_multi_modal.ipynb
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/llama_index/multi_modal_llms/anthropic/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/pyproject.toml
Labels: size:M

#11669 Check for none from queue
  llama-index-core/llama_index/core/chat_engine/types.py
Labels: lgtm, size:XS

#11359 make mongo tutorial faster
  docs/examples/vector_stores/MongoDBAtlasVectorSearchRAGFireworks.ipynb
Labels: lgtm, size:XS

#11378 Add to BaseSQLTableQueryEngine refine synthesis template
  llama-index-core/llama_index/core/indices/struct_store/sql_query.py
Labels: lgtm, size:M

#11003 fix: ignore outdated pack examples
  llama-index-packs/llama-index-packs-agent-search-retriever/examples/_example.py
  llama-index-packs/llama-index-packs-agent-search-retriever/pyproject.toml
  llama-index-packs/llama-index-packs-arize-phoenix-query-engine/examples/arize_phoenix_llama_pack.ipynb
  llama-index-packs/llama-index-packs-arize-phoenix-query-engine/examples/example.py
  llama-index-packs/llama-index-packs-arize-phoenix-query-engine/pyproject.toml
  llama-index-packs/llama-index-packs-corrective-rag/pyproject.toml
  llama-index-packs/llama-index-packs-rag-evaluator/examples/example.py
  llama-index-packs/llama-index-packs-rag-evaluator/llama_index/packs/rag_evaluator/base.py
  llama-index-packs/llama-index-packs-rag-evaluator/pyproject.toml
Labels: lgtm, size:M

#11674 fix router query engine
  llama-index-core/llama_index/core/query_engine/router_query_engine.py
Labels: lgtm, size:XS

#11676 offline environment: only download when nltk data is missing
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/unstructured/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:XS

#11667 feat: relative score fusion (QueryFusionRetriever)
  docs/examples/retrievers/relative_score_dist_fusion.ipynb
  docs/module_guides/querying/retriever/retrievers.md
  llama-index-core/llama_index/core/retrievers/fusion_retriever.py
Labels: lgtm, size:L

#11678 Fix func name spelling
  llama-index-core/llama_index/core/ingestion/data_sources.py
Labels: lgtm, size:XS

#11626 JSONReader load_data metadata
  llama-index-core/llama_index/core/readers/json.py
  llama-index-integrations/readers/llama-index-readers-json/llama_index/readers/json/base.py
Labels: lgtm, size:S

#11694 mega nit
  llama-index-packs/llama-index-packs-raptor/examples/raptor.ipynb
Labels: size:XS

#11387 Hierarchical agent for all things Finance
  llama-index-packs/llama-index-packs-finchat/.gitignore
  llama-index-packs/llama-index-packs-finchat/BUILD
  llama-index-packs/llama-index-packs-finchat/Makefile
  llama-index-packs/llama-index-packs-finchat/README.md
  llama-index-packs/llama-index-packs-finchat/examples/BUILD
  llama-index-packs/llama-index-packs-finchat/examples/example.py
  llama-index-packs/llama-index-packs-finchat/llama_index/packs/finchat/BUILD
  llama-index-packs/llama-index-packs-finchat/llama_index/packs/finchat/__init__.py
  llama-index-packs/llama-index-packs-finchat/llama_index/packs/finchat/base.py
  llama-index-packs/llama-index-packs-finchat/pyproject.toml
Labels: size:XL

#11699 Update mappings.json
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
Labels: lgtm, size:M

#11695 fix out of index for _extract_rel_text_keywords when use neo4j Neo4jG…
  llama-index-core/llama_index/core/indices/knowledge_graph/retrievers.py
Labels: size:S

#11701 Return proper response type in synthesizer
  llama-index-core/llama_index/core/response_synthesizers/base.py
Labels: size:S

#11671 [+] Added document metadata to the summary node dictionary.
  llama-index-core/llama_index/core/indices/document_summary/base.py
Labels: lgtm, size:XS

#11662 inheirt callback manager
  llama-index-core/llama_index/core/indices/struct_store/sql_query.py
Labels: size:S

#11657 fix: Qdrant collection exists check
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
Labels: lgtm, size:XS

#11702 Astra DB vector store: rephrase the warning about indexing
  llama-index-integrations/vector_stores/llama-index-vector-stores-astra-db/llama_index/vector_stores/astra_db/base.py
Labels: lgtm, size:XS

#11675 fix agent streaming?
  llama-index-core/llama_index/core/agent/react/step.py
  llama-index-core/llama_index/core/agent/runner/base.py
  llama-index-core/llama_index/core/agent/runner/parallel.py
  llama-index-core/llama_index/core/chat_engine/types.py
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/step.py
  llama-index-integrations/agent/llama-index-agent-openai/tests/test_openai_agent.py
Labels: size:M

#11717 Make other nodes parsing for element parser configurable
  llama-index-core/llama_index/core/node_parser/relational/base_element.py
Labels: lgtm, size:S

#11722 Resolve circle import
  llama-index-core/llama_index/core/node_parser/relational/base_element.py
Labels: size:XS

#11720 Logan/verson v0.10.17
  CHANGELOG.md
  llama-index-cli/pyproject.toml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-json/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-astra-db/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#11723 changelog
  CHANGELOG.md
Labels: size:M

#11668 fixed but when using Vectara query engine in non-summary mode
  docs/examples/retrievers/vectara_auto_retriever.ipynb
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/base.py
Labels: lgtm, size:M

#11726 Update vertex.ipynb - updating title
  docs/examples/llm/vertex.ipynb
Labels: lgtm, size:XS

#11733 Ensure load and search tool spec loads documents
  llama-index-core/llama_index/core/tools/tool_spec/load_and_search/base.py
Labels: size:S

#11748 fix(docs): bge-m3 != bge-small-en-v1.5
  docs/getting_started/starter_example_local.md
Labels: lgtm, size:XS

#11742 Update base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/pyproject.toml
Labels: lgtm, size:XS

#11728 template + bump
  .github/pull_request_template.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: size:S

#11734 Prevent forced flush() on document add
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:XS

#11759 fix: relative score fusion bug
  llama-index-core/llama_index/core/retrievers/fusion_retriever.py
Labels: size:XS

#11665 Fixes for SimpleDirectoryReader
  docs/examples/data_connectors/simple_directory_reader.ipynb
  docs/examples/data_connectors/simple_directory_reader_remote_fs.ipynb
  docs/module_guides/loading/simpledirectoryreader.md
  llama-index-core/llama_index/core/readers/file/base.py
Labels: lgtm, size:M

#11721 Updates to VoyageEmbedding
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/llama_index/embeddings/voyageai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/tests/test_embeddings_voyageai.py
Labels: lgtm, size:L

#11697 Cohere Context citations chat engine pack + Jupyter notebook
  llama-index-packs/llama-index-packs-cohere-citation-chat/.gitignore
  llama-index-packs/llama-index-packs-cohere-citation-chat/BUILD
  llama-index-packs/llama-index-packs-cohere-citation-chat/CHANGELOG.md
  llama-index-packs/llama-index-packs-cohere-citation-chat/Makefile
  llama-index-packs/llama-index-packs-cohere-citation-chat/README.md
  llama-index-packs/llama-index-packs-cohere-citation-chat/examples/BUILD
  llama-index-packs/llama-index-packs-cohere-citation-chat/examples/cohere_citation_chat_example.ipynb
  llama-index-packs/llama-index-packs-cohere-citation-chat/examples/example.py
  llama-index-packs/llama-index-packs-cohere-citation-chat/llama_index/packs/cohere_citation_chat/BUILD
  llama-index-packs/llama-index-packs-cohere-citation-chat/llama_index/packs/cohere_citation_chat/__init__.py
  llama-index-packs/llama-index-packs-cohere-citation-chat/llama_index/packs/cohere_citation_chat/base.py
  llama-index-packs/llama-index-packs-cohere-citation-chat/llama_index/packs/cohere_citation_chat/citations_context_chat_engine.py
  llama-index-packs/llama-index-packs-cohere-citation-chat/llama_index/packs/cohere_citation_chat/types.py
  llama-index-packs/llama-index-packs-cohere-citation-chat/llama_index/packs/cohere_citation_chat/utils.py
  llama-index-packs/llama-index-packs-cohere-citation-chat/pyproject.toml
  llama-index-packs/llama-index-packs-cohere-citation-chat/tests/BUILD
  llama-index-packs/llama-index-packs-cohere-citation-chat/tests/__init__.py
  llama-index-packs/llama-index-packs-cohere-citation-chat/tests/test_packs_cohere_citation_chat.py
Labels: lgtm, size:XL

#11719 fix: allow guideline evaluator with bedrock
  llama-index-core/llama_index/core/evaluation/base.py
Labels: lgtm, size:S

#11635 Add Initial Support for TiDB Vector Store
  docs/community/integrations/vector_stores.md
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/examples/tidb_vector.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/llama_index/vector_stores/tidbvector/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/llama_index/vector_stores/tidbvector/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/llama_index/vector_stores/tidbvector/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/poetry.lock
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/tests/test_vector_stores_tidbvector.py
Labels: lgtm, size:XL

#11761 Feat/mymagic-return-output
  docs/examples/llm/mymagic.ipynb
  llama-index-integrations/llms/llama-index-llms-mymagic/llama_index/llms/mymagic/base.py
Labels: lgtm, size:XS

#10671 Code Hierarchy Node Parser v0.10
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-packs/llama-index-packs-code-hierarchy/.gitignore
  llama-index-packs/llama-index-packs-code-hierarchy/BUILD
  llama-index-packs/llama-index-packs-code-hierarchy/README.md
  llama-index-packs/llama-index-packs-code-hierarchy/examples/CodeHierarchyNodeParserUsage.ipynb
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/BUILD
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/__init__.py
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/base.py
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/code_hierarchy.py
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/query_engine.py
  llama-index-packs/llama-index-packs-code-hierarchy/pyproject.toml
  llama-index-packs/llama-index-packs-code-hierarchy/tests/BUILD
  llama-index-packs/llama-index-packs-code-hierarchy/tests/__init__.py
  llama-index-packs/llama-index-packs-code-hierarchy/tests/test_code_hierarchy_no_skeleton.py
  llama-index-packs/llama-index-packs-code-hierarchy/tests/test_code_hierarchy_with_skeleton.py
  llama-index-packs/llama-index-packs-code-hierarchy/tests/test_query_engine.py
  llama-index-packs/llama-index-packs-code-hierarchy/tests/test_utility_methods.py
Labels: lgtm, size:XXL

#11763 Logan/v0.10.18
  CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-core/llama_index/core/utilities/gemini_utils.py
  llama-index-core/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-vectara/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-mymagic/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#11765 The PrivateAttr should be imported from llama_index.core.bridge.pydantic instead of pydantic
  llama-index-integrations/embeddings/llama-index-embeddings-dashscope/llama_index/embeddings/dashscope/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-dashscope/pyproject.toml
Labels: lgtm, size:XS

#11766 Minor improvement for TiDB Vector
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/examples/tidb_vector.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/poetry.lock
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/pyproject.toml
Labels: lgtm, size:XS

#11775 remove unneeded chroma deps
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/pyproject.toml
Labels: size:XS

#11768 docs: Updated Qdrant usage examples
  docs/examples/vector_stores/QdrantIndexDemo.ipynb
Labels: lgtm, size:M

#11778 feat: nested metadata filters (PGVectorStore)
  docs/examples/vector_stores/postgres.ipynb
  llama-index-core/llama_index/core/vector_stores/types.py
  llama-index-core/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
Labels: lgtm, size:L

#11769 nit: add link to code hierarchy notebook
  llama-index-packs/llama-index-packs-code-hierarchy/examples/CodeHierarchyNodeParserUsage.ipynb
Labels: lgtm, size:XS

#11685 add claude3 benchmarks
  docs/module_guides/models/llms.md
Labels: lgtm, size:XS

#11640 Integration in Google Sheets Reader to load the Sheets into Pandas Dataframes
  docs/examples/data_connectors/GoogleSheetsDemo.ipynb
  llama-index-integrations/readers/llama-index-readers-google/README.md
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/sheets/base.py
  llama-index-integrations/readers/llama-index-readers-google/pyproject.toml
Labels: lgtm, size:XL

#11464 Update ReAct prompt for multilingual support
  llama-index-core/llama_index/core/agent/react/prompts.py
Labels: lgtm, size:S

#11466 Create new RTF integration
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/__init__.py
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/rtf/BUILD
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/rtf/README.md
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/rtf/__init__.py
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/rtf/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-file/tests/test_rtf.py
Labels: lgtm, size:M

#11795 Add LogProb type to core.base.llms module
  llama-index-core/llama_index/core/base/llms/types.py
Labels: lgtm, size:S

#11819 bump mistralai deps
  llama-index-integrations/embeddings/llama-index-embeddings-mistralai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-mistralai/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-mistralai/tests/BUILD
Labels: size:S

#11821 Update verifying connection
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/base.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: lgtm, size:XS

#11805 Adds new LabelledSimpleDataset (llama-dataset)
  llama-index-core/llama_index/core/llama_dataset/base.py
  llama-index-core/llama_index/core/llama_dataset/simple.py
Labels: lgtm, size:L

#11825 Fixes for add and delete Methods in LanceDBVectorStore
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/llama_index/vector_stores/lancedb/base.py
Labels: size:XS

#11774 added table comment to Table Info in SQLDatabase
  llama-index-core/llama_index/core/utilities/sql_wrapper.py
Labels: lgtm, size:S

#11836 fix obj insert_nodes
  llama-index-core/llama_index/core/indices/base.py
  llama-index-core/llama_index/core/indices/vector_store/base.py
Labels: lgtm, size:S

#11840 Fixed some gramatical mistakes
  docs/understanding/using_llms/privacy.md
  docs/understanding/using_llms/using_llms.md
Labels: lgtm, size:S

#11270 add modelscope llm support
  docs/examples/llm/modelscope.ipynb
  docs/module_guides/models/llms/modules.md
  llama-index-integrations/llms/llama-index-llms-modelscope/.gitignore
  llama-index-integrations/llms/llama-index-llms-modelscope/BUILD
  llama-index-integrations/llms/llama-index-llms-modelscope/Makefile
  llama-index-integrations/llms/llama-index-llms-modelscope/README.md
  llama-index-integrations/llms/llama-index-llms-modelscope/llama_index/llms/modelscope/BUILD
  llama-index-integrations/llms/llama-index-llms-modelscope/llama_index/llms/modelscope/__init__.py
  llama-index-integrations/llms/llama-index-llms-modelscope/llama_index/llms/modelscope/base.py
  llama-index-integrations/llms/llama-index-llms-modelscope/llama_index/llms/modelscope/utils.py
  llama-index-integrations/llms/llama-index-llms-modelscope/pyproject.toml
Labels: lgtm, size:L

#11454 [Feature Request]: add PowerPoint support to Confluence reader #10592
  llama-index-integrations/readers/llama-index-readers-confluence/llama_index/readers/confluence/base.py
  llama-index-integrations/readers/llama-index-readers-confluence/pyproject.toml
Labels: lgtm, size:L

#11494 add baidu vectordb as vector store
  docs/examples/vector_stores/BaiduVectorDBIndexDemo.ipynb
  docs/module_guides/storing/vector_stores.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-baiduvectordb/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-baiduvectordb/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-baiduvectordb/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-baiduvectordb/llama_index/vector_stores/baiduvectordb/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-baiduvectordb/llama_index/vector_stores/baiduvectordb/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-baiduvectordb/llama_index/vector_stores/baiduvectordb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-baiduvectordb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-baiduvectordb/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-baiduvectordb/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-baiduvectordb/tests/test_vector_stores_baiduvectordb.py
Labels: lgtm, size:XL

#11558 Add QueryUnderstandingAgent LlamaPack
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-packs/llama-index-packs-query-understanding-agent/.gitignore
  llama-index-packs/llama-index-packs-query-understanding-agent/BUILD
  llama-index-packs/llama-index-packs-query-understanding-agent/Makefile
  llama-index-packs/llama-index-packs-query-understanding-agent/README.md
  llama-index-packs/llama-index-packs-query-understanding-agent/examples/query_understanding_agent.ipynb
  llama-index-packs/llama-index-packs-query-understanding-agent/llama_index/packs/query_understanding_agent/BUILD
  llama-index-packs/llama-index-packs-query-understanding-agent/llama_index/packs/query_understanding_agent/__init__.py
  llama-index-packs/llama-index-packs-query-understanding-agent/llama_index/packs/query_understanding_agent/base.py
  llama-index-packs/llama-index-packs-query-understanding-agent/llama_index/packs/query_understanding_agent/step.py
  llama-index-packs/llama-index-packs-query-understanding-agent/pyproject.toml
  llama-index-packs/llama-index-packs-query-understanding-agent/requirements.txt
  llama-index-packs/llama-index-packs-query-understanding-agent/tests/BUILD
  llama-index-packs/llama-index-packs-query-understanding-agent/tests/__init__.py
  llama-index-packs/llama-index-packs-query-understanding-agent/tests/test_packs_query_understanding_agent.py
Labels: lgtm, size:XL

#11709 Adds llamafile support for local LLM and embeddings
  docs/examples/embeddings/llamafile.ipynb
  docs/examples/llm/llamafile.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-llamafile/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-llamafile/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-llamafile/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-llamafile/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-llamafile/llama_index/embeddings/llamafile/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-llamafile/llama_index/embeddings/llamafile/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-llamafile/llama_index/embeddings/llamafile/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-llamafile/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-llamafile/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-llamafile/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-llamafile/tests/test_embeddings_llamafile.py
  llama-index-integrations/llms/llama-index-llms-llamafile/.gitignore
  llama-index-integrations/llms/llama-index-llms-llamafile/BUILD
  llama-index-integrations/llms/llama-index-llms-llamafile/Makefile
  llama-index-integrations/llms/llama-index-llms-llamafile/README.md
  llama-index-integrations/llms/llama-index-llms-llamafile/llama_index/llms/llamafile/BUILD
  llama-index-integrations/llms/llama-index-llms-llamafile/llama_index/llms/llamafile/__init__.py
  llama-index-integrations/llms/llama-index-llms-llamafile/llama_index/llms/llamafile/base.py
  llama-index-integrations/llms/llama-index-llms-llamafile/poetry.lock
  llama-index-integrations/llms/llama-index-llms-llamafile/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-llamafile/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-llamafile/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-llamafile/tests/test_llms_llamafile.py
Labels: lgtm, size:XXL

#11724 Google readers integrations doc and drive updates
  llama-index-integrations/readers/llama-index-readers-google/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/calendar/README.md
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/docs/README.md
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/drive/README.md
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/drive/base.py
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/gmail/README.md
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/keep/README.md
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/sheets/README.md
  llama-index-integrations/readers/llama-index-readers-google/pyproject.toml
Labels: lgtm, size:L

#11855 Add logprobs field to `CompletionResponse`
  llama-index-core/llama_index/core/base/llms/types.py
Labels: lgtm, size:XS

#11856 Fix stream chat param error in CondenseQuestionChatEngine
  llama-index-core/llama_index/core/chat_engine/condense_question.py
Labels: lgtm, size:XS

#11867 add retries for openai LLM rate limit errors
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:S

#11807 [Bug Fix] Fix a parameter passing issue.
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface/pyproject.toml
Labels: size:XS

#11862 fix: add postpreprocess_output_processor to json_query.py
  llama-index-core/llama_index/core/indices/struct_store/json_query.py
Labels: lgtm, size:XS

#11874 use proper retriever kwargs
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
Labels: size:XS

#11870 Logan/v0.10.19
  CHANGELOG.md
  llama-index-cli/llama_index/cli/command_line.py
  llama-index-cli/pyproject.toml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-finance/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:M

#11872 fix(PGVectorStore): Use OR in text search; correct IN behaviour
  docs/examples/vector_stores/postgres.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/test_postgres.py
Labels: lgtm, size:L

#11793 Add LogProb llm type and OpenAI logprobs
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:M

#11866 Add Query Pipeline Agent Example for Multi-PDFs
  docs/examples/agent/agent_runner/agent_around_query_pipeline_with_HyDE_for_PDFs.ipynb
Labels: lgtm, size:XS

#11800 Add Retriever to llama-index-networks
  llama-index-networks/examples/demo/contributor-1/contributor_1/app.py
  llama-index-networks/examples/demo/contributor-1/poetry.lock
  llama-index-networks/examples/demo/contributor-1/pyproject.toml
  llama-index-networks/examples/demo/contributor-2/contributor_2/app.py
  llama-index-networks/examples/demo/contributor-2/poetry.lock
  llama-index-networks/examples/demo/contributor-2/pyproject.toml
  llama-index-networks/examples/demo/contributor-3/contributor_3/app.py
  llama-index-networks/examples/demo/contributor-3/poetry.lock
  llama-index-networks/examples/demo/contributor-3/pyproject.toml
  llama-index-networks/examples/demo/network_query_engine.ipynb
  llama-index-networks/examples/simple/network_query_engine.py
  llama-index-networks/examples/simple/query_engine_contributor.py
  llama-index-networks/examples/simple/retriever_contributor.py
  llama-index-networks/llama_index/networks/__init__.py
  llama-index-networks/llama_index/networks/contributor/__init__.py
  llama-index-networks/llama_index/networks/contributor/query_engine/BUILD
  llama-index-networks/llama_index/networks/contributor/query_engine/__init__.py
  llama-index-networks/llama_index/networks/contributor/query_engine/client.py
  llama-index-networks/llama_index/networks/contributor/query_engine/service.py
  llama-index-networks/llama_index/networks/contributor/retriever/BUILD
  llama-index-networks/llama_index/networks/contributor/retriever/__init__.py
  llama-index-networks/llama_index/networks/contributor/retriever/client.py
  llama-index-networks/llama_index/networks/contributor/retriever/service.py
  llama-index-networks/llama_index/networks/network/BUILD
  llama-index-networks/llama_index/networks/network/__init__.py
  llama-index-networks/llama_index/networks/network/query_engine.py
  llama-index-networks/llama_index/networks/network/retriever.py
  llama-index-networks/llama_index/networks/query_engine/__init__.py
  llama-index-networks/llama_index/networks/schema/contributor.py
  llama-index-networks/pyproject.toml
  llama-index-networks/tests/contributor/query_engine/BUILD
  llama-index-networks/tests/contributor/query_engine/test_client.py
  llama-index-networks/tests/contributor/query_engine/test_service.py
  llama-index-networks/tests/contributor/retriever/BUILD
  llama-index-networks/tests/contributor/retriever/test_retriever_client.py
  llama-index-networks/tests/contributor/retriever/test_retriever_service.py
  llama-index-networks/tests/network/BUILD
  llama-index-networks/tests/network/test_query_engine.py
  llama-index-networks/tests/network/test_retriever.py
Labels: lgtm, size:L

#11887 docs: fix astra-db notebook install cmd
  docs/examples/vector_stores/AstraDBIndexDemo.ipynb
Labels: lgtm, size:XS

#11914 Bugfix: CitationQueryEngine.from_args defaulted to Open AI
  llama-index-core/llama_index/core/query_engine/citation_query_engine.py
Labels: lgtm, size:XS

#11902 Fixed import error for ChatMessage
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/base.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
Labels: lgtm, size:S

#11910 bump astrapy to 0.7.7
  llama-index-integrations/vector_stores/llama-index-vector-stores-astra-db/poetry.lock
  llama-index-integrations/vector_stores/llama-index-vector-stores-astra-db/pyproject.toml
Labels: lgtm, size:XS

#11880 Fix Visualization for Query Pipeline notebook
  docs/examples/pipeline/query_pipeline_sql.ipynb
Labels: lgtm, size:M

#11913 Added pytesseract support for ImageReader
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/image/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:L

#11916 Add Anthropic haiku model
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/llama_index/multi_modal_llms/anthropic/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/pyproject.toml
Labels: lgtm, size:S

#11896 fix: pymupdf must be optional because is AGPLv3 licensed
  docs/examples/agent/openai_retrieval_benchmark.ipynb
  docs/examples/finetuning/gradient/gradient_structured.ipynb
  docs/examples/finetuning/openai_fine_tuning_functions.ipynb
  docs/examples/low_level/evaluation.ipynb
  docs/examples/low_level/fusion_retriever.ipynb
  docs/examples/low_level/oss_ingestion_retrieval.ipynb
  docs/examples/low_level/response_synthesis.ipynb
  docs/examples/low_level/retrieval.ipynb
  docs/examples/low_level/router.ipynb
  docs/examples/low_level/vector_store.ipynb
  docs/examples/param_optimizer/param_optimizer.ipynb
  docs/examples/prompts/emotion_prompt.ipynb
  docs/examples/prompts/prompt_optimization.ipynb
  docs/examples/prompts/prompts_rag.ipynb
  docs/examples/query_engine/pdf_tables/recursive_retriever.ipynb
  docs/examples/retrievers/auto_merging_retriever.ipynb
  docs/examples/retrievers/composable_retrievers.ipynb
  docs/examples/retrievers/ensemble_retrieval.ipynb
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/pymu_pdf/README.md
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:M

#11873 keyval_docstore and mongodb docstore updated to accept custom collections suffix
  llama-index-core/llama_index/core/storage/docstore/keyval_docstore.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-mongodb/llama_index/storage/docstore/mongodb/base.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-mongodb/pyproject.toml
Labels: lgtm, size:M

#11919 Anthropic Haiku model cookbook
  docs/cookbooks/anthropic_haiku.ipynb
  docs/module_guides/models/llms/modules.md
Labels: lgtm, size:XS

#11923 Update anthropic cookbook with response speed comparision
  docs/cookbooks/anthropic_haiku.ipynb
Labels: lgtm, size:L

#11885 Add Auto-retriever tutorial for Weaviate
  docs/examples/vector_stores/WeaviateIndex_auto_retriever.ipynb
Labels: lgtm, size:XL

#11955 fix: public links in langfuse cookbook
  docs/examples/callbacks/LangfuseCallbackHandler.ipynb
Labels: lgtm, size:XS

#10754 Feature/databricks vector search
  docs/examples/vector_stores/DatabricksVectorSearchDemo.ipynb
  docs/module_guides/storing/vector_stores.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-databricks/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-databricks/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-databricks/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-databricks/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-databricks/llama_index/vector_stores/databricks/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-databricks/llama_index/vector_stores/databricks/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-databricks/llama_index/vector_stores/databricks/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-databricks/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-databricks/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-databricks/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-databricks/tests/test_vector_stores_databricks_vector_search.py
Labels: lgtm, size:XL

#11954 Prem AI LlamaIndex integration (migrating PR from org account to personal account)
  docs/examples/embeddings/premai.ipynb
  docs/examples/llm/premai.ipynb
  docs/module_guides/models/llms/modules.md
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/embeddings/llama-index-embeddings-premai/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-premai/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-premai/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-premai/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-premai/llama_index/embeddings/premai/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-premai/llama_index/embeddings/premai/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-premai/llama_index/embeddings/premai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-premai/llama_index/embeddings/premai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-premai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-premai/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-premai/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-premai/tests/test_embeddings_prem.py
  llama-index-integrations/llms/llama-index-llms-premai/.gitignore
  llama-index-integrations/llms/llama-index-llms-premai/BUILD
  llama-index-integrations/llms/llama-index-llms-premai/Makefile
  llama-index-integrations/llms/llama-index-llms-premai/README.md
  llama-index-integrations/llms/llama-index-llms-premai/llama_index/llms/premai/BUILD
  llama-index-integrations/llms/llama-index-llms-premai/llama_index/llms/premai/__init__.py
  llama-index-integrations/llms/llama-index-llms-premai/llama_index/llms/premai/base.py
  llama-index-integrations/llms/llama-index-llms-premai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-premai/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-premai/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-premai/tests/test_llms_prem.py
Labels: lgtm, size:XXL

#11927 fix: postgres metadata filters
  docs/examples/vector_stores/postgres.ipynb
  llama-index-core/llama_index/core/vector_stores/types.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/test_postgres.py
Labels: lgtm, size:L

#11883 Incorrect warning message on HuggingFaceLLM tokenizer
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py
Labels: lgtm, size:XS

#11956 + gpt-35-turbo-0125 for AZURE_TURBO_MODELS
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:XS

#11949 Feat: Add async streaming support to `query_engine`
  llama-index-core/llama_index/core/base/response/schema.py
  llama-index-core/llama_index/core/response_synthesizers/base.py
  llama-index-core/llama_index/core/response_synthesizers/refine.py
  llama-index-core/llama_index/core/types.py
Labels: lgtm, size:L

#11959 Implement opensearch doc deletion
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
Labels: lgtm, size:XS

#11924 Update integratins with Pathway: retriever and reader
  docs/examples/data_connectors/PathwayReaderDemo.ipynb
  docs/examples/retrievers/pathway_retriever.ipynb
  llama-index-integrations/readers/llama-index-readers-pathway/llama_index/readers/pathway/base.py
  llama-index-integrations/readers/llama-index-readers-pathway/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-pathway/llama_index/retrievers/pathway/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-pathway/pyproject.toml
Labels: lgtm, size:XL

#11858 Improved ArangoDB Reader Readme.
  llama-index-integrations/readers/llama-index-readers-arango-db/README.md
Labels: lgtm, size:XS

#11710 Add Solar chat model
  docs/examples/llm/solar.ipynb
  docs/module_guides/models/llms/modules.md
  llama-index-integrations/llms/llama-index-llms-solar/.gitignore
  llama-index-integrations/llms/llama-index-llms-solar/BUILD
  llama-index-integrations/llms/llama-index-llms-solar/Makefile
  llama-index-integrations/llms/llama-index-llms-solar/README.md
  llama-index-integrations/llms/llama-index-llms-solar/llama_index/llms/solar/BUILD
  llama-index-integrations/llms/llama-index-llms-solar/llama_index/llms/solar/__init__.py
  llama-index-integrations/llms/llama-index-llms-solar/llama_index/llms/solar/base.py
  llama-index-integrations/llms/llama-index-llms-solar/pyproject.toml
Labels: lgtm, size:L

#11868 [WIP] Init llama_parse json node parser
  llama-index-core/llama_index/core/node_parser/__init__.py
  llama-index-core/llama_index/core/node_parser/relational/__init__.py
  llama-index-core/llama_index/core/node_parser/relational/base_element.py
  llama-index-core/llama_index/core/node_parser/relational/llama_parse_json_element.py
  llama-index-core/llama_index/core/node_parser/relational/markdown_element.py
  llama-index-core/llama_index/core/node_parser/relational/unstructured_element.py
  llama-index-core/llama_index/core/node_parser/relational/utils.py
Labels: size:L

#11871 JSONReader Option to maintain valid json structure
  llama-index-core/llama_index/core/readers/json.py
  llama-index-core/tests/readers/test_json.py
  llama-index-integrations/readers/llama-index-readers-json/llama_index/readers/json/base.py
  llama-index-integrations/readers/llama-index-readers-json/pyproject.toml
Labels: lgtm, size:M

#11968 fix (llms/openai): don't try to get logprobs from None content
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:XS

#11861 Wholesitereader pass driver arg
  llama-index-integrations/readers/llama-index-readers-web/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/whole_site/README.md
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/whole_site/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:M

#11939 Expose "safe_serialization" parameter from AutoModel to HuggingFaceEm…
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/llama_index/embeddings/huggingface/base.py
Labels: lgtm, size:XS

#11962 v0.10.20
  CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-core/storage/default__vector_store.json
  llama-index-core/storage/docstore.json
  llama-index-core/storage/graph_store.json
  llama-index-core/storage/image__vector_store.json
  llama-index-core/storage/index_store.json
  llama-index-core/storage/object_node_mapping.pickle
  llama-index-integrations/llms/llama-index-llms-vertex/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-google/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:L

#11986 [FIX] - PydanticResponse Bug
  llama-index-core/llama_index/core/base/response/schema.py
  llama-index-core/llama_index/core/instrumentation/events/synthesis.py
  llama-index-core/llama_index/core/instrumentation/span_handlers/simple.py
  llama-index-core/llama_index/core/response_synthesizers/base.py
Labels: lgtm, size:M

#11663 Add Claude 3 Sonnet model to AWS Bedrock & update to support Messages API - Text Only, Not Multimodal
  llama-index-core/llama_index/core/llms/callbacks.py
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock/tests/test_bedrock.py
Labels: lgtm, size:M

#11993 vbump for core
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
Labels: size:XS

#11992 Add Async LogProbs to OpenAI Completion
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:S

#11994 Add Mistral provider to Bedrock
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock/tests/test_bedrock.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
Labels: lgtm, size:M

#11998 Fix typo in unstructured_web README.md
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/unstructured_web/README.md
Labels: lgtm, size:XS

#11982 remove space from MarkdownNodeParser Header metadata
  llama-index-core/llama_index/core/node_parser/file/markdown.py
  llama-index-core/tests/node_parser/test_markdown.py
Labels: lgtm, size:S

#12038 Remove llama_hub_url keyword from download_llama_dataset of command…
  llama-index-cli/llama_index/cli/command_line.py
Labels: lgtm, size:XS

#12033 anthropic notebook nit
  docs/examples/llm/anthropic.ipynb
Labels: lgtm, size:XS

#12050 chore: bump vector-store-postgres
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
Labels: lgtm, size:XS

#11881 DiffPrivacy ICL Pack - OpenAI Completion LLMs
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/.gitignore
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/BUILD
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/Makefile
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/README.md
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/examples/basic_demo/README.md
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/examples/basic_demo/_create_agnews_simple_dataset.ipynb
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/examples/basic_demo/demo_usage.ipynb
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/examples/symptom_2_disease/BUILD
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/examples/symptom_2_disease/README.md
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/examples/symptom_2_disease/__init__.py
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/examples/symptom_2_disease/_create_symptom_2_disease_simple_dataset.py
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/examples/symptom_2_disease/_download_raw_symptom_2_disease_data.py
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/examples/symptom_2_disease/error_report.json
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/examples/symptom_2_disease/event_handler.py
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/examples/symptom_2_disease/main.py
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/llama_index/packs/diff_private_simple_dataset/BUILD
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/llama_index/packs/diff_private_simple_dataset/__init__.py
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/llama_index/packs/diff_private_simple_dataset/base.py
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/llama_index/packs/diff_private_simple_dataset/events.py
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/llama_index/packs/diff_private_simple_dataset/privacy_mechanism.py
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/llama_index/packs/diff_private_simple_dataset/templates.py
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/poetry.lock
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/pyproject.toml
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/tests/BUILD
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/tests/__init__.py
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/tests/test_packs_diff_private_examples_gen.py
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/tests/test_templates.py
Labels: lgtm, size:XXL

#11981 Opensearch test and documentation
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/tests/test_opensearch_client.py
Labels: lgtm, size:M
