Repository run-llama/llama_index, pull requests merged in 2024-08, with the labels that each got.

#15076 v0.10.59
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/textembed.md
  docs/docs/api_reference/extractors/llama_extract.md
  docs/docs/api_reference/packs/longrag.md
  docs/docs/api_reference/postprocessor/tei_rerank.md
  docs/docs/api_reference/readers/gitlab.md
  docs/docs/api_reference/storage/graph_stores/falkordb.md
  docs/docs/api_reference/workflow/context.md
  docs/docs/api_reference/workflow/events.md
  docs/docs/api_reference/workflow/workflow.md
  docs/docs/module_guides/querying/index.md
  docs/docs/understanding/querying/querying.md
  docs/mkdocs.yml
  docs/prepare_for_build.py
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-ollama/llama_index/embeddings/ollama/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-ollama/pyproject.toml
  llama-index-integrations/graph_stores/llama-index-graph-stores-falkordb/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openllm/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-dashscope-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-tei-rerank/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#15022 Removes gradient.ai integration
  docs/docs/examples/finetuning/gradient/data.jsonl
  docs/docs/examples/finetuning/gradient/gradient_fine_tuning.ipynb
  docs/docs/examples/finetuning/gradient/gradient_structured.ipynb
  docs/docs/examples/finetuning/gradient/gradient_text2sql.ipynb
  llama-index-finetuning/llama_index/finetuning/gradient/BUILD
  llama-index-finetuning/llama_index/finetuning/gradient/__init__.py
  llama-index-finetuning/llama_index/finetuning/gradient/base.py
  llama-index-finetuning/tests/gradient/BUILD
  llama-index-finetuning/tests/gradient/__init__.py
  llama-index-finetuning/tests/gradient/test_gradient_classes.py
  llama-index-integrations/embeddings/llama-index-embeddings-gradient/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-gradient/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-gradient/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-gradient/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-gradient/llama_index/embeddings/gradient/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-gradient/llama_index/embeddings/gradient/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-gradient/llama_index/embeddings/gradient/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-gradient/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-gradient/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-gradient/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-gradient/tests/test_embeddings_gradient.py
  llama-index-integrations/llms/llama-index-llms-gradient/.gitignore
  llama-index-integrations/llms/llama-index-llms-gradient/BUILD
  llama-index-integrations/llms/llama-index-llms-gradient/Makefile
  llama-index-integrations/llms/llama-index-llms-gradient/README.md
  llama-index-integrations/llms/llama-index-llms-gradient/llama_index/llms/gradient/BUILD
  llama-index-integrations/llms/llama-index-llms-gradient/llama_index/llms/gradient/__init__.py
  llama-index-integrations/llms/llama-index-llms-gradient/llama_index/llms/gradient/base.py
  llama-index-integrations/llms/llama-index-llms-gradient/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-gradient/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-gradient/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-gradient/tests/test_llms_gradient.py
  llama-index-legacy/llama_index/legacy/finetuning/gradient/BUILD
  llama-index-legacy/llama_index/legacy/finetuning/gradient/__init__.py
  llama-index-legacy/llama_index/legacy/finetuning/gradient/base.py
Labels: lgtm, size:XXL

#14998 fix(sql_wrapper): dont mention foreign keys when theres none
  llama-index-core/llama_index/core/utilities/sql_wrapper.py
  llama-index-core/tests/utilities/test_sql_wrapper.py
Labels: lgtm, size:S

#15077 update openvino components
  docs/docs/examples/embeddings/openvino.ipynb
  docs/docs/examples/llm/openvino.ipynb
  docs/docs/examples/node_postprocessor/openvino_rerank.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/llama_index/embeddings/huggingface_openvino/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/tests/test_embeddings_huggingface_openvino.py
  llama-index-integrations/llms/llama-index-llms-openvino/llama_index/llms/openvino/base.py
  llama-index-integrations/llms/llama-index-llms-openvino/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/llama_index/postprocessor/openvino_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/pyproject.toml
Labels: lgtm, size:L

#15086 Docs: Fix broken link
  docs/docs/community/integrations/trulens.md
Labels: lgtm, size:XS

#15089 bugfixes for attribute check when retrieving site and correct parsing of file_path
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/llama_index/readers/microsoft_sharepoint/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/pyproject.toml
Labels: lgtm, size:S

#15092 MLflow Quickstart Guide
  docs/docs/examples/observability/MLflow.ipynb
  docs/docs/examples/observability/mlflow_single_trace_quickstart.png
  docs/docs/examples/observability/mlflow_tracing_quickstart.png
  docs/docs/examples/observability/mlflow_ui_registered_model.png
  docs/docs/examples/observability/mlflow_ui_run.png
Labels: lgtm, size:L

#15098 fix docs build
  docs/docs/api_reference/embeddings/gradient.md
  docs/docs/api_reference/llms/gradient.md
  docs/docs/examples/embeddings/gradient.ipynb
  docs/docs/examples/llm/gradient_base_model.ipynb
  docs/docs/examples/llm/gradient_model_adapter.ipynb
Labels: size:XL

#15048 Update README.md
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/maps/README.md
Labels: lgtm, size:XS

#15093 fix: Handle nested MetadataFilters for Redis vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/pyproject.toml
Labels: lgtm, size:S

#15099 remove bad docs
  docs/docs/api_reference/extractors/llama_extract.md
  docs/mkdocs.yml
Labels: size:XS

#15102 update typing for workflow timeouts
  llama-index-core/llama_index/core/workflow/workflow.py
Labels: size:XS

#15085 Fixed minor bug in DynamicLLMPathExtractor as well as default output parsers not working
  llama-index-core/llama_index/core/indices/property_graph/transformations/dynamic_llm.py
Labels: lgtm, size:L

#15045 Update WordLift Vector Store
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/llama_index/vector_stores/wordlift/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/api/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/api/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/api/vector_search_nodes_api.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/api/vector_search_queries_api.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/api_client.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/api_response.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/configuration.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/docs/Filter.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/docs/NodeRequest.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/docs/PageVectorSearchQueryResponseItem.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/docs/VectorSearchNodesApi.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/docs/VectorSearchQueriesApi.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/docs/VectorSearchQueryRequest.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/docs/VectorSearchQueryResponseItem.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/exceptions.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/models/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/models/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/models/filter.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/models/node_request.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/models/page_vector_search_query_response_item.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/models/vector_search_query_request.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/models/vector_search_query_response_item.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/rest.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/test/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/test/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/test/test_filter.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/test/test_node_request.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/test/test_page_vector_search_query_response_item.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/test/test_vector_search_nodes_api.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/test/test_vector_search_queries_api.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/test/test_vector_search_query_request.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/manager_client/test/test_vector_search_query_response_item.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/poetry.lock
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/tests/test_wordlift.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/tests/wiremock/__files/account/me/response_1.json
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/tests/wiremock/__files/vector-search/queries/response_1.json
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/tests/wiremock/mappings/account/me/request_1.json
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/tests/wiremock/mappings/entities/request_1.json
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/tests/wiremock/mappings/vector-search/nodes-collection/request_1.json
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/tests/wiremock/mappings/vector-search/queries/request_1.json
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/utils/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/utils/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/utils/utils.py
Labels: lgtm, size:XXL

#15047 Update base.py to use @atexit for cleanup
  llama-index-integrations/llms/llama-index-llms-vllm/llama_index/llms/vllm/base.py
  llama-index-integrations/llms/llama-index-llms-vllm/pyproject.toml
Labels: lgtm, size:XS

#15104 doc: fix the broken embedding link
  docs/docs/understanding/storing/storing.md
Labels: lgtm, size:XS

#15108 Update neo4j LPG relationship proeprties
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: lgtm, size:S

#15111 fix neo4j property graph bug
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: size:XS

#15119 Add GraphRAGV2
  docs/docs/examples/cookbooks/GraphRAG_v2.ipynb
Labels: lgtm, size:XXL

#15121 fix: :bug: Fix langchain-pinecone and pinecone-client downgrade (#15120)
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/pyproject.toml
Labels: lgtm, size:XS

#15124 update StartEvent usage
  docs/docs/examples/workflow/function_calling_agent.ipynb
  docs/docs/examples/workflow/react_agent.ipynb
  docs/docs/module_guides/workflow/index.md
  llama-index-core/llama_index/core/workflow/events.py
Labels: size:S

#15125 v0.10.60
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/poetry.lock
Labels: size:M

#15130 Fix Predibase Integration for HuggingFace-hosted fine-tuned adapters
  docs/docs/examples/llm/predibase.ipynb
  llama-index-integrations/llms/llama-index-llms-predibase/llama_index/llms/predibase/base.py
  llama-index-integrations/llms/llama-index-llms-predibase/pyproject.toml
Labels: lgtm, size:M

#15131 Fix __str__ method for AsyncStreamingResponse
  llama-index-core/llama_index/core/base/response/schema.py
Labels: lgtm, size:XS

#15123 Add relik kg constructor
  llama-index-integrations/retrievers/llama-index-retrievers-relik/.gitignore
  llama-index-integrations/retrievers/llama-index-retrievers-relik/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-relik/Makefile
  llama-index-integrations/retrievers/llama-index-retrievers-relik/README.md
  llama-index-integrations/retrievers/llama-index-retrievers-relik/llama_index/retrievers/relik/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-relik/llama_index/retrievers/relik/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-relik/llama_index/retrievers/relik/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-relik/pyproject.toml
Labels: lgtm, size:L

#15068 Update neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
Labels: lgtm, size:XS

#15000 Fix: Gemini 1.0 Pro Vision has been official deprecated, switch default model to gemini-1.5-flash
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
Labels: lgtm, size:S

#15150 feat: add `default_headers` to Fireworks model
  llama-index-integrations/llms/llama-index-llms-fireworks/llama_index/llms/fireworks/base.py
Labels: lgtm, size:XS

#15064 feat(integration): add a global handler for Literal AI
  docs/docs/module_guides/observability/index.md
  llama-index-core/llama_index/core/callbacks/global_handlers.py
  llama-index-integrations/callbacks/llama-index-callbacks-literalai/.gitignore
  llama-index-integrations/callbacks/llama-index-callbacks-literalai/BUILD
  llama-index-integrations/callbacks/llama-index-callbacks-literalai/Makefile
  llama-index-integrations/callbacks/llama-index-callbacks-literalai/README.md
  llama-index-integrations/callbacks/llama-index-callbacks-literalai/examples/BUILD
  llama-index-integrations/callbacks/llama-index-callbacks-literalai/examples/literalai_example.py
  llama-index-integrations/callbacks/llama-index-callbacks-literalai/llama_index/callbacks/literalai/BUILD
  llama-index-integrations/callbacks/llama-index-callbacks-literalai/llama_index/callbacks/literalai/__init__.py
  llama-index-integrations/callbacks/llama-index-callbacks-literalai/llama_index/callbacks/literalai/base.py
  llama-index-integrations/callbacks/llama-index-callbacks-literalai/pyproject.toml
Labels: lgtm, size:L

#15149 fix doc
  docs/docs/examples/embeddings/sagemaker_embedding_endpoint.ipynb
  docs/docs/examples/llm/bedrock.ipynb
  docs/docs/examples/llm/sagemaker_endpoint_llm.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-sagemaker-endpoint/llama_index/embeddings/sagemaker_endpoint/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/base.py
  llama-index-integrations/llms/llama-index-llms-sagemaker-endpoint/llama_index/llms/sagemaker_endpoint/base.py
  llama-index-legacy/llama_index/legacy/llms/sagemaker_llm_endpoint.py
Labels: lgtm, size:S

#15153 make workflow context able to collect multiples of the same event
  llama-index-core/llama_index/core/workflow/context.py
Labels: lgtm, size:S

#15129 Add streaming for async mode, also fix the casting for streaming modes
  llama-index-core/llama_index/core/indices/struct_store/sql_query.py
Labels: lgtm, size:S

#15134 keyval index store and mongodb index store updated to accept custom collection suffix
  llama-index-core/llama_index/core/storage/index_store/keyval_index_store.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-azure/llama_index/storage/index_store/azure/base.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-dynamodb/llama_index/storage/index_store/dynamodb/base.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-elasticsearch/llama_index/storage/index_store/elasticsearch/base.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-firestore/llama_index/storage/index_store/firestore/base.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-mongodb/llama_index/storage/index_store/mongodb/base.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-postgres/llama_index/storage/index_store/postgres/base.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-redis/llama_index/storage/index_store/redis/base.py
Labels: lgtm, size:L

#15116 Create context manager to instrument event and span tags
  docs/docs/examples/instrumentation/basic_usage.ipynb
  docs/docs/examples/instrumentation/instrumentation_observability_rundown.ipynb
  docs/docs/module_guides/observability/instrumentation.md
  llama-index-core/llama_index/core/instrumentation/dispatcher.py
  llama-index-core/llama_index/core/instrumentation/events/__init__.py
  llama-index-core/llama_index/core/instrumentation/events/base.py
  llama-index-core/llama_index/core/instrumentation/span/base.py
  llama-index-core/llama_index/core/instrumentation/span_handlers/base.py
  llama-index-core/llama_index/core/instrumentation/span_handlers/null.py
  llama-index-core/llama_index/core/instrumentation/span_handlers/simple.py
  llama-index-core/tests/instrumentation/test_dispatcher.py
  llama-index-integrations/callbacks/llama-index-callbacks-agentops/llama_index/callbacks/agentops/base.py
Labels: lgtm, size:L

#15154 Tweaks to workflow docs
  docs/docs/examples/workflow/reflection.ipynb
  docs/docs/module_guides/workflow/index.md
Labels: size:L

#14845 NVIDIA LlamaIndex Base URL Validation
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/poetry.lock
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_base_url.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_mode_switch.py
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/base.py
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_base_url.py
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_mode_switch.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_base_url.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_mode_switch.py
Labels: lgtm, size:L

#14983 Add LLM for AlibabaCloud PaiEas
  docs/docs/examples/llm/paieas.ipynb
  llama-index-integrations/llms/llama-index-llms-paieas/.gitignore
  llama-index-integrations/llms/llama-index-llms-paieas/BUILD
  llama-index-integrations/llms/llama-index-llms-paieas/Makefile
  llama-index-integrations/llms/llama-index-llms-paieas/README.md
  llama-index-integrations/llms/llama-index-llms-paieas/llama_index/llms/paieas/BUILD
  llama-index-integrations/llms/llama-index-llms-paieas/llama_index/llms/paieas/__init__.py
  llama-index-integrations/llms/llama-index-llms-paieas/llama_index/llms/paieas/base.py
  llama-index-integrations/llms/llama-index-llms-paieas/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-paieas/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-paieas/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-paieas/tests/test_llms_paieas.py
Labels: lgtm, size:XL

#15141 feat: add default_headers to Gemini model
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
Labels: lgtm, size:S

#15177 OpenAI: Support new strict functionality in tool param
  docs/docs/examples/llm/openai.ipynb
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:M

#15182 fix: use parent source node to node relationships if possible
  llama-index-core/llama_index/core/node_parser/interface.py
  llama-index-core/tests/ingestion/test_pipeline.py
Labels: lgtm, size:S

#15179 Neo4j property graph client side batching
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: lgtm, size:L

#15172 Use node hash instead of node text to match nodes in fusion retriever
  llama-index-core/llama_index/core/retrievers/fusion_retriever.py
Labels: lgtm, size:M

#15176 Add support for full MetadataFilters in Opensearch (all operators and…
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/CHANGELOG.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/tests/test_opensearch_client.py
Labels: lgtm, size:L

#15167 feat: Allow None metadata filter by using IS_EMPTY operator
  llama-index-core/llama_index/core/vector_stores/simple.py
  llama-index-core/llama_index/core/vector_stores/types.py
  llama-index-core/tests/vector_stores/test_simple.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
Labels: lgtm, size:M

#15126 PropertyGraphStore support for Amazon Neptune
  docs/docs/examples/property_graph/property_graph_neptune.ipynb
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/README.md
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/__init__.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/analytics.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/analytics_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/base.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/base_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/database.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/database_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/neptune.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/pyproject.toml
Labels: lgtm, size:XXL

#15140 Add support for `fields` projection and update sample Notebook
  docs/docs/vector_stores/wordlift_vector_store_demo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/examples/data/paul_graham/paul_graham_essay.txt
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/examples/wordlift_vector_store_demo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/llama_index/vector_stores/wordlift/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/pyproject.toml
Labels: lgtm, size:XXL

#15184 v0.10.62
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/storage/graph_stores/neptune.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#15185 Add support for gpt-4o-2024-08-06
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/llama_index/multi_modal_llms/openai/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/pyproject.toml
Labels: lgtm, size:XS

#15205 [Bug]:Perplexity LLM integration list outdated
  llama-index-integrations/llms/llama-index-llms-perplexity/llama_index/llms/perplexity/base.py
  llama-index-integrations/llms/llama-index-llms-perplexity/pyproject.toml
Labels: lgtm, size:S

#15207 Update output_parser.py
  llama-index-experimental/llama_index/experimental/query_engine/pandas/output_parser.py
  llama-index-experimental/pyproject.toml
Labels: lgtm, size:XS

#15186 Add Llamatrace to workflow notebooks
  docs/docs/examples/workflow/function_calling_agent.ipynb
  docs/docs/examples/workflow/rag.ipynb
  docs/docs/examples/workflow/react_agent.ipynb
Labels: lgtm, size:L

#15194 Remove deprecated `ServiceContext` from the `evaluation` package
  llama-index-core/llama_index/core/evaluation/dataset_generation.py
  llama-index-core/tests/evaluation/test_batch_runner.py
  llama-index-core/tests/evaluation/test_dataset_generation.py
Labels: lgtm, size:M

#15217 feat: add sharepoint site id option
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/llama_index/readers/microsoft_sharepoint/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/pyproject.toml
Labels: lgtm, size:M

#15225 Fix relik extractor skip error
  llama-index-integrations/extractors/llama-index-extractors-relik/llama_index/extractors/relik/base.py
  llama-index-integrations/extractors/llama-index-extractors-relik/pyproject.toml
Labels: lgtm, size:XS

#15219 Remove deprecated `ServiceContext` from the `question_gen` package
  llama-index-core/llama_index/core/evaluation/dataset_generation.py
  llama-index-core/llama_index/core/question_gen/llm_generators.py
  llama-index-core/tests/evaluation/test_batch_runner.py
  llama-index-core/tests/evaluation/test_dataset_generation.py
  llama-index-core/tests/question_gen/test_llm_generators.py
Labels: lgtm, size:M

#15209 Sub Question Query Engine as workflow
  docs/docs/examples/workflow/sub_question_query_engine.ipynb
Labels: lgtm, size:XS

#15227 Allow for images in Anthropic messages
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: lgtm, size:S

#15210 fix: add num_workers in decorator to resolve step parallelism issue
  llama-index-core/llama_index/core/workflow/decorators.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_decorator.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: lgtm, size:L

#15202 Fixed slack client ref in ToolSpec
  llama-index-integrations/tools/llama-index-tools-slack/llama_index/tools/slack/base.py
  llama-index-integrations/tools/llama-index-tools-slack/pyproject.toml
Labels: lgtm, size:XS

#15229 fix mistral integration
  docs/docs/examples/llm/mistralai.ipynb
  llama-index-finetuning/llama_index/finetuning/mistralai/base.py
  llama-index-finetuning/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-mistralai/llama_index/embeddings/mistralai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-mistralai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/base.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
Labels: lgtm, size:L

#15232 Update Mixture Of Agents llamapack with workflows
  llama-index-packs/llama-index-packs-mixture-of-agents/README.md
  llama-index-packs/llama-index-packs-mixture-of-agents/llama_index/packs/mixture_of_agents/base.py
  llama-index-packs/llama-index-packs-mixture-of-agents/pyproject.toml
Labels: lgtm, size:L

#15244 v0.10.63
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/storage/graph_stores/neptune.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#15249 Remove usage of `ServiceContext` in Colbert integration
  llama-index-integrations/indices/llama-index-indices-managed-colbert/llama_index/indices/managed/colbert/base.py
  llama-index-integrations/indices/llama-index-indices-managed-colbert/llama_index/indices/managed/colbert/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-colbert/pyproject.toml
Labels: lgtm, size:S

#15262 doc: add num_workers workflow example
  docs/docs/examples/workflow/parallel_execution.ipynb
Labels: lgtm, size:L

#15254 fix: children nodes not carrying metadata from source nodes
  llama-index-core/llama_index/core/node_parser/interface.py
  llama-index-core/tests/node_parser/test_node_parser.py
Labels: lgtm, size:M

#15253 Remove API key from code example
  llama-index-packs/llama-index-packs-vanna/examples/vanna.ipynb
Labels: lgtm, size:XS

#15252 Workflows: fix the validation error in the decorator
  llama-index-core/llama_index/core/workflow/decorators.py
  llama-index-core/tests/workflow/test_decorator.py
Labels: lgtm, size:XS

#15257 Correct Import Statement in 'Using as a Retriever' Section
  docs/docs/module_guides/querying/router/index.md
Labels: lgtm, size:XS

#15239 add generation prompt to HF chat template
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openvino/pyproject.toml
Labels: lgtm, size:S

#15226 Fix fs.open path type
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/docs/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:XS

#15240 Update models supported by Cleanlab TLM
  llama-index-integrations/llms/llama-index-llms-cleanlab/llama_index/llms/cleanlab/base.py
  llama-index-integrations/llms/llama-index-llms-cleanlab/pyproject.toml
Labels: lgtm, size:M

#15241 feat: Support Milvus collection properties
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:S

#15189 Scene index support
  docs/docs/examples/multi_modal/multi_modal_videorag_videodb.ipynb
  docs/docs/examples/retrievers/videodb_retriever.ipynb
  docs/mkdocs.yml
  llama-index-integrations/retrievers/llama-index-retrievers-videodb/llama_index/retrievers/videodb/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-videodb/pyproject.toml
Labels: lgtm, size:XXL

#15235 fix: strip '''sql (Markdown SQL code snippet) in SQL Retriever
  llama-index-core/llama_index/core/indices/struct_store/sql_retriever.py
Labels: lgtm, size:XS

#15183 Add the workflows cookbook to the workflows examples
  docs/docs/examples/workflow/workflows_cookbook.ipynb
  docs/mkdocs.yml
Labels: lgtm, size:XS

#15267 [version] bump version to 0.10.64
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#15260 Feature: added multiprocessing for creating hf embedddings
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/llama_index/embeddings/huggingface/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/pyproject.toml
Labels: lgtm, size:L

#15277 chore: bump nltk version
  llama-index-core/pyproject.toml
  llama-index-legacy/pyproject.toml
  llama-index-packs/llama-index-packs-streamlit-chatbot/pyproject.toml
  poetry.lock
Labels: lgtm, size:XS

#15279 vertex docs typo
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py
Labels: lgtm, size:XS

#15286 chore: update all the lockfiles referencing nltk
  llama-index-core/poetry.lock
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/poetry.lock
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/poetry.lock
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/poetry.lock
  llama-index-integrations/readers/llama-index-readers-microsoft-onedrive/poetry.lock
  llama-index-utils/llama-index-utils-workflow/poetry.lock
Labels: lgtm, size:XS

#15247 fix: MarvinMetadataExtractor functionality and apply async support
  docs/docs/examples/metadata_extraction/MarvinMetadataExtractorDemo.ipynb
  llama-index-integrations/extractors/llama-index-extractors-marvin/llama_index/extractors/marvin/base.py
  llama-index-integrations/extractors/llama-index-extractors-marvin/pyproject.toml
Labels: lgtm, size:L

#15294 Docs: Update Dependencies and Fix Typo in Pairwise Comparison Evaluator
  docs/docs/examples/finetuning/llm_judge/pairwise/finetune_llm_judge.ipynb
Labels: lgtm, size:XS

#15288 chore: bump black version
  llama-index-utils/llama-index-utils-workflow/poetry.lock
  llama-index-utils/llama-index-utils-workflow/pyproject.toml
Labels: lgtm, size:XS

#15299 chore: only show errors from pants during unit testing
  Makefile
Labels: lgtm, size:XS, topic:CI

#15301 chore: remove `ServiceContext` usage from experimental package
  llama-index-experimental/llama_index/experimental/query_engine/pandas/pandas_query_engine.py
  llama-index-experimental/pyproject.toml
Labels: lgtm, size:S

#15300 chore: stop using `ServiceContext` from the clickhouse integration
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/llama_index/vector_stores/clickhouse/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/pyproject.toml
Labels: lgtm, size:S

#15296 feat: add default_headers to Gemini multi-model
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/llama_index/multi_modal_llms/gemini/base.py
Labels: lgtm, size:S

#15236 Box tools for AI Agents
  llama-index-integrations/tools/llama-index-tools-box/.gitignore
  llama-index-integrations/tools/llama-index-tools-box/BUILD
  llama-index-integrations/tools/llama-index-tools-box/Makefile
  llama-index-integrations/tools/llama-index-tools-box/README.md
  llama-index-integrations/tools/llama-index-tools-box/examples/box_ai_extract.ipynb
  llama-index-integrations/tools/llama-index-tools-box/examples/box_ai_prompt.ipynb
  llama-index-integrations/tools/llama-index-tools-box/examples/box_extract.ipynb
  llama-index-integrations/tools/llama-index-tools-box/examples/box_search.ipynb
  llama-index-integrations/tools/llama-index-tools-box/examples/box_search_by_metadata.ipynb
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/BUILD
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/__init__.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/ai_extract/BUILD
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/ai_extract/__init__.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/ai_extract/base.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/ai_prompt/BUILD
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/ai_prompt/__init__.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/ai_prompt/base.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/search/BUILD
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/search/__init__.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/search/base.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/search_by_metadata/BUILD
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/search_by_metadata/__init__.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/search_by_metadata/base.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/text_extract/BUILD
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/text_extract/__init__.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/text_extract/base.py
  llama-index-integrations/tools/llama-index-tools-box/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-box/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-box/tests/__init__.py
  llama-index-integrations/tools/llama-index-tools-box/tests/conftest.py
  llama-index-integrations/tools/llama-index-tools-box/tests/test_tools_box.py
  llama-index-integrations/tools/llama-index-tools-box/tests/test_tools_box_ai_extract.py
  llama-index-integrations/tools/llama-index-tools-box/tests/test_tools_box_ai_prompt.py
  llama-index-integrations/tools/llama-index-tools-box/tests/test_tools_box_search.py
  llama-index-integrations/tools/llama-index-tools-box/tests/test_tools_box_search_by_metadata.py
  llama-index-integrations/tools/llama-index-tools-box/tests/test_tools_box_text_extract.py
Labels: lgtm, size:XXL

#15305 [version] bump version to 0.10.65
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-microsoft-onedrive/pyproject.toml
  llama-index-legacy/pyproject.toml
  llama-index-packs/llama-index-packs-streamlit-chatbot/pyproject.toml
  llama-index-utils/llama-index-utils-workflow/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#15307 fix: dont recreate filtering keys to index mapping (already created ones)
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
Labels: lgtm, size:XS

#15287 Check if hnsw index exists
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/test_postgres.py
Labels: lgtm, size:M

#15314 Box refactor: Box File to Llama-Index Document adaptor
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxAPI/box_api.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxAPI/box_llama_adaptors.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReader/base.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderAIExtraction/base.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderAIPrompt/base.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderTextExtraction/base.py
  llama-index-integrations/readers/llama-index-readers-box/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-box/tests/test_readers_box_ai_extract.py
  llama-index-integrations/readers/llama-index-readers-box/tests/test_readers_box_ai_prompt.py
  llama-index-integrations/readers/llama-index-readers-box/tests/test_readers_box_reader.py
  llama-index-integrations/readers/llama-index-readers-box/tests/test_readers_box_text_extraction.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/ai_extract/base.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/ai_prompt/base.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/search/base.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/search_by_metadata/base.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/text_extract/base.py
  llama-index-integrations/tools/llama-index-tools-box/pyproject.toml
Labels: lgtm, size:XL

#15309 chore: remove usage of ServiceContext from packs
  llama-index-packs/llama-index-packs-auto-merging-retriever/llama_index/packs/auto_merging_retriever/base.py
  llama-index-packs/llama-index-packs-auto-merging-retriever/pyproject.toml
  llama-index-packs/llama-index-packs-cohere-citation-chat/llama_index/packs/cohere_citation_chat/citations_context_chat_engine.py
  llama-index-packs/llama-index-packs-cohere-citation-chat/pyproject.toml
  llama-index-packs/llama-index-packs-dense-x-retrieval/llama_index/packs/dense_x_retrieval/base.py
  llama-index-packs/llama-index-packs-dense-x-retrieval/pyproject.toml
  llama-index-packs/llama-index-packs-fusion-retriever/llama_index/packs/fusion_retriever/hybrid_fusion/base.py
  llama-index-packs/llama-index-packs-fusion-retriever/llama_index/packs/fusion_retriever/query_rewrite/base.py
  llama-index-packs/llama-index-packs-fusion-retriever/pyproject.toml
  llama-index-packs/llama-index-packs-multi-document-agents/llama_index/packs/multi_document_agents/base.py
  llama-index-packs/llama-index-packs-multi-document-agents/pyproject.toml
  llama-index-packs/llama-index-packs-multi-tenancy-rag/llama_index/packs/multi_tenancy_rag/base.py
  llama-index-packs/llama-index-packs-multi-tenancy-rag/pyproject.toml
  llama-index-packs/llama-index-packs-nebulagraph-query-engine/llama_index/packs/nebulagraph_query_engine/base.py
  llama-index-packs/llama-index-packs-nebulagraph-query-engine/pyproject.toml
  llama-index-packs/llama-index-packs-neo4j-query-engine/llama_index/packs/neo4j_query_engine/base.py
  llama-index-packs/llama-index-packs-neo4j-query-engine/pyproject.toml
  llama-index-packs/llama-index-packs-ollama-query-engine/llama_index/packs/ollama_query_engine/base.py
  llama-index-packs/llama-index-packs-ollama-query-engine/pyproject.toml
  llama-index-packs/llama-index-packs-rag-cli-local/llama_index/packs/rag_cli_local/base.py
  llama-index-packs/llama-index-packs-rag-cli-local/pyproject.toml
  llama-index-packs/llama-index-packs-ragatouille-retriever/llama_index/packs/ragatouille_retriever/base.py
  llama-index-packs/llama-index-packs-ragatouille-retriever/pyproject.toml
  llama-index-packs/llama-index-packs-recursive-retriever/llama_index/packs/recursive_retriever/small_to_big/base.py
  llama-index-packs/llama-index-packs-recursive-retriever/pyproject.toml
  llama-index-packs/llama-index-packs-resume-screener/llama_index/packs/resume_screener/base.py
  llama-index-packs/llama-index-packs-resume-screener/pyproject.toml
  llama-index-packs/llama-index-packs-sentence-window-retriever/llama_index/packs/sentence_window_retriever/base.py
  llama-index-packs/llama-index-packs-sentence-window-retriever/pyproject.toml
  llama-index-packs/llama-index-packs-snowflake-query-engine/llama_index/packs/snowflake_query_engine/base.py
  llama-index-packs/llama-index-packs-snowflake-query-engine/pyproject.toml
  llama-index-packs/llama-index-packs-stock-market-data-query-engine/llama_index/packs/stock_market_data_query_engine/base.py
  llama-index-packs/llama-index-packs-stock-market-data-query-engine/pyproject.toml
  llama-index-packs/llama-index-packs-streamlit-chatbot/llama_index/packs/streamlit_chatbot/base.py
  llama-index-packs/llama-index-packs-streamlit-chatbot/pyproject.toml
  llama-index-packs/llama-index-packs-voyage-query-engine/llama_index/packs/voyage_query_engine/base.py
  llama-index-packs/llama-index-packs-voyage-query-engine/pyproject.toml
  llama-index-packs/llama-index-packs-zephyr-query-engine/llama_index/packs/zephyr_query_engine/base.py
  llama-index-packs/llama-index-packs-zephyr-query-engine/pyproject.toml
Labels: lgtm, size:L

#15310 15275 feature request make all events accessible like mappings
  llama-index-core/llama_index/core/workflow/events.py
  llama-index-core/tests/workflow/test_event.py
Labels: lgtm, size:L

#15259 feat: make send_event assign the target step
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: lgtm, size:M

#15188 bug: Semantic double merging splitter creates chunks larger thank chunk size
  llama-index-core/llama_index/core/node_parser/text/semantic_double_merging_splitter.py
  llama-index-core/tests/node_parser/test_semantic_double_merging_splitter.py
Labels: lgtm, size:M

#15145 Update code_hierarchy.py adding php support
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/code_hierarchy.py
  llama-index-packs/llama-index-packs-code-hierarchy/pyproject.toml
Labels: lgtm, size:S

#15331 chore: bump deprecated actions
  .github/workflows/build_package.yml
  .github/workflows/codeql.yml
  .github/workflows/lint.yml
  .github/workflows/publish_release.yml
  .github/workflows/publish_sub_package.yml
  .github/workflows/unit_test.yml
Labels: lgtm, size:S

#15360 chore: let dependabot monitor Github actions
  .github/dependabot.yml
Labels: lgtm, size:XS, topic:CI

#15372 Add citation query engine with workflows
  docs/docs/examples/workflow/citation_query_engine.ipynb
Labels: lgtm, size:XL

#15365 GCSReader: Implementing ResourcesReaderMixin and FileSystemReaderMixin
  llama-index-integrations/readers/llama-index-readers-gcs/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-gcs/README.md
  llama-index-integrations/readers/llama-index-readers-gcs/llama_index/readers/gcs/base.py
  llama-index-integrations/readers/llama-index-readers-gcs/pyproject.toml
Labels: size:L

#15358 fix bug when caling llama-index-postprocessor-dashscope-rerank
  llama-index-integrations/postprocessor/llama-index-postprocessor-dashscope-rerank/llama_index/postprocessor/dashscope_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-dashscope-rerank/pyproject.toml
Labels: lgtm, size:XS, package:llama-index-postprocessor-dashscope-rerank

#15220 Feat: Wrapper for SambaNova (Sambaverse and SambaStudio) with Llama-index
  docs/docs/examples/llm/sambanova.ipynb
  llama-index-integrations/llms/llama-index-llms-sambanova/.gitignore
  llama-index-integrations/llms/llama-index-llms-sambanova/BUILD
  llama-index-integrations/llms/llama-index-llms-sambanova/Makefile
  llama-index-integrations/llms/llama-index-llms-sambanova/README.md
  llama-index-integrations/llms/llama-index-llms-sambanova/llama_index/llms/sambanova/BUILD
  llama-index-integrations/llms/llama-index-llms-sambanova/llama_index/llms/sambanova/__init__.py
  llama-index-integrations/llms/llama-index-llms-sambanova/llama_index/llms/sambanova/base.py
  llama-index-integrations/llms/llama-index-llms-sambanova/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-sambanova/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-sambanova/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-sambanova/tests/test_llms_sambanova.py
Labels: lgtm, size:XL

#15248 Remove `ServiceContext` from the `core` package
  llama-index-cli/llama_index/cli/rag/base.py
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-cli/pyproject.toml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/base/base_retriever.py
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-core/llama_index/core/composability/joint_qa_summary.py
  llama-index-core/llama_index/core/evaluation/answer_relevancy.py
  llama-index-core/llama_index/core/evaluation/context_relevancy.py
  llama-index-core/llama_index/core/evaluation/correctness.py
  llama-index-core/llama_index/core/evaluation/faithfulness.py
  llama-index-core/llama_index/core/evaluation/guideline.py
  llama-index-core/llama_index/core/evaluation/pairwise.py
  llama-index-core/llama_index/core/evaluation/relevancy.py
  llama-index-core/llama_index/core/evaluation/semantic_similarity.py
  llama-index-core/llama_index/core/indices/base.py
  llama-index-core/llama_index/core/indices/multi_modal/base.py
  llama-index-core/llama_index/core/indices/service_context.py
  llama-index-core/llama_index/core/indices/tree/select_leaf_retriever.py
  llama-index-core/llama_index/core/indices/vector_store/retrievers/auto_retriever/auto_retriever.py
  llama-index-core/llama_index/core/llama_dataset/generator.py
  llama-index-core/llama_index/core/postprocessor/llm_rerank.py
  llama-index-core/llama_index/core/postprocessor/node.py
  llama-index-core/llama_index/core/query_engine/citation_query_engine.py
  llama-index-core/llama_index/core/query_engine/flare/answer_inserter.py
  llama-index-core/llama_index/core/query_engine/flare/base.py
  llama-index-core/llama_index/core/query_engine/jsonalyze_query_engine.py
  llama-index-core/llama_index/core/query_engine/knowledge_graph_query_engine.py
  llama-index-core/llama_index/core/query_engine/retry_source_query_engine.py
  llama-index-core/llama_index/core/query_engine/router_query_engine.py
  llama-index-core/llama_index/core/query_engine/sql_join_query_engine.py
  llama-index-core/llama_index/core/query_engine/sql_vector_query_engine.py
  llama-index-core/llama_index/core/query_engine/sub_question_query_engine.py
  llama-index-core/llama_index/core/retrievers/router_retriever.py
  llama-index-core/llama_index/core/service_context.py
  llama-index-core/llama_index/core/settings.py
  llama-index-packs/llama-index-packs-longrag/llama_index/packs/longrag/base.py
  llama-index-packs/llama-index-packs-longrag/pyproject.toml
Labels: lgtm, size:L

#15403 v0.10.66
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/indices/bge_m3.md
  docs/docs/api_reference/llms/sambanova.md
  docs/docs/api_reference/tools/box.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-sambanova/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
  llama-index-legacy/pyproject.toml
  llama-index-packs/llama-index-packs-streamlit-chatbot/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:L

#15408 Add JSONAlyze Query Engine using workflows cookbook
  docs/docs/examples/workflow/JSONalyze_query_engine.ipynb
Labels: lgtm, size:XL

#15324 Use backticks to escape label
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/analytics_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/pyproject.toml
Labels: lgtm, size:XS

#15415 Fixed issue #15414 and added ability to do partial matchfor Neptune Analytics
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/analytics_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/base_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/pyproject.toml
Labels: lgtm, size:S

#15404 escape json in structured llm
  llama-index-core/llama_index/core/llms/structured_llm.py
  llama-index-core/tests/llms/test_structured_llm.py
Labels: lgtm, size:M

#15437 update completion_to_prompt of HF pipeline
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openvino/pyproject.toml
Labels: lgtm, size:S

#15429 Fix missing 'self' in example notebook.
  docs/docs/examples/cookbooks/GraphRAG_v2.ipynb
Labels: lgtm, size:XS

#15428 Add workaround for Handling MySQL Protocol Limitations in TiDB Vector with insert_batch_size
  docs/docs/examples/vector_stores/TiDBVector.ipynb
Labels: lgtm, size:S

#15352 Cleanlab's cookbook
  docs/docs/examples/cookbooks/cleanlab_tlm_rag.ipynb
Labels: docs, lgtm, size:XL

#15333 When building a vector store with use_async=True it doesn't set a TTL on records
  llama-index-core/llama_index/core/vector_stores/types.py
Labels: size:XS

#15367 Vertexai embedding enhancement
  llama-index-integrations/embeddings/llama-index-embeddings-vertex/CHANGELOG.md
  llama-index-integrations/embeddings/llama-index-embeddings-vertex/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-vertex/llama_index/embeddings/vertex/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-vertex/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-vertex/tests/test_embeddings_vertex.py
Labels: lgtm, size:L, package:llama-index-embeddings-vertex

#15144 feat: add tool calling for cohere
  llama-index-integrations/llms/llama-index-llms-cohere/llama_index/llms/cohere/base.py
  llama-index-integrations/llms/llama-index-llms-cohere/llama_index/llms/cohere/utils.py
  llama-index-integrations/llms/llama-index-llms-cohere/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-cohere/tests/test_llms_cohere.py
  llama-index-integrations/llms/llama-index-llms-cohere/tests/test_rag_inference.py
Labels: lgtm, size:XL

#15152 Add get/set API to the Context and make it coroutine-safe
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/tests/workflow/test_context.py
Labels: lgtm, size:L, topic:workflows

#15397 Fix LangChainDeprecationWarning
  llama-index-core/llama_index/core/bridge/langchain.py
Labels: lgtm, size:XS

#15160 Ports over LongRAGPack, Corrective RAG Pack, and Self-Discover Pack to Workflows
  docs/docs/examples/workflow/corrective_rag_pack.ipynb
  docs/docs/examples/workflow/long_rag_pack.ipynb
  docs/docs/examples/workflow/self_discover_workflow.ipynb
  llama-index-packs/llama-index-packs-corrective-rag/examples/corrective_rag.ipynb
  llama-index-packs/llama-index-packs-corrective-rag/llama_index/packs/corrective_rag/base.py
  llama-index-packs/llama-index-packs-corrective-rag/pyproject.toml
  llama-index-packs/llama-index-packs-longrag/examples/longrag.ipynb
  llama-index-packs/llama-index-packs-longrag/llama_index/packs/longrag/base.py
  llama-index-packs/llama-index-packs-longrag/pyproject.toml
  llama-index-packs/llama-index-packs-self-discover/examples/self_discover.ipynb
  llama-index-packs/llama-index-packs-self-discover/llama_index/packs/self_discover/base.py
  llama-index-packs/llama-index-packs-self-discover/pyproject.toml
Labels: lgtm, size:XXL

#15456 chore: remove leftover occurences of `GradientFinetuneEngine`
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-legacy/llama_index/legacy/finetuning/__init__.py
  llama-index-legacy/pyproject.toml
Labels: lgtm, size:XS

#15448 Exposed NeptuneQueryException and added additional debug information
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/__init__.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/analytics.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/analytics_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/database.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/database_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/pyproject.toml
Labels: lgtm, size:S

#15443 docs: promote openllmetry to one-click integration
  docs/docs/module_guides/observability/index.md
Labels: lgtm, size:M

#15297 feat: Integrating Azure OpenAI Finetuning
  llama-index-finetuning/llama_index/finetuning/__init__.py
  llama-index-finetuning/llama_index/finetuning/azure_openai/BUILD
  llama-index-finetuning/llama_index/finetuning/azure_openai/__init__.py
  llama-index-finetuning/llama_index/finetuning/azure_openai/base.py
  llama-index-finetuning/pyproject.toml
  llama-index-finetuning/tests/azure_openai/BUILD
  llama-index-finetuning/tests/azure_openai/__init__.py
  llama-index-finetuning/tests/azure_openai/test_azure_openai_classes.py
  llama-index-finetuning/tests/test_base.py
Labels: lgtm, size:L

#15473 avoid nltk 3.9 since its broken
  llama-index-core/pyproject.toml
Labels: size:XS

#15278 Add GigaChat embedding
  docs/docs/examples/embeddings/gigachat.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-gigachat/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-gigachat/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-gigachat/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-gigachat/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-gigachat/llama_index/embeddings/gigachat/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-gigachat/llama_index/embeddings/gigachat/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-gigachat/llama_index/embeddings/gigachat/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-gigachat/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-gigachat/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-gigachat/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-gigachat/tests/test_embeddings_gigachat.py
Labels: lgtm, size:L

#15431 feat: support to configure the base url of jina.ai
  llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-jinaai/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-jinaai-rerank/llama_index/postprocessor/jinaai_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-jinaai-rerank/pyproject.toml
Labels: lgtm, size:S

#15302 Enhance PreprocessReader
  docs/docs/examples/data_connectors/PreprocessReaderDemo.ipynb
  llama-index-integrations/readers/llama-index-readers-preprocess/llama_index/readers/preprocess/base.py
  llama-index-integrations/readers/llama-index-readers-preprocess/pyproject.toml
Labels: lgtm, size:L

#15474 v0.10.67
  .github/workflows/unit_test.yml
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#15478 use ollama client for embeddings
  llama-index-integrations/embeddings/llama-index-embeddings-ollama/llama_index/embeddings/ollama/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-ollama/pyproject.toml
Labels: size:M

#15311 Bug-15158: Fixing the issues in loading file paths
  llama-index-integrations/readers/llama-index-readers-bitbucket/llama_index/readers/bitbucket/base.py
  llama-index-integrations/readers/llama-index-readers-bitbucket/pyproject.toml
Labels: lgtm, size:S

#15454 Adds an Instrumentation Span Handler to Langfuse
  docs/docs/module_guides/observability/index.md
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/README.md
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/llama_index/callbacks/langfuse/__init__.py
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/llama_index/callbacks/langfuse/langfuse_instrumentation.py
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/pyproject.toml
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/static/state_of_the_union_short.txt
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/tests/BUILD
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/tests/__init__.py
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/tests/test_langfuse_instrumentation.py
Labels: lgtm, size:XXL

#15492 Revert Langfuse SpanHandler PR
  docs/docs/module_guides/observability/index.md
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/README.md
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/llama_index/callbacks/langfuse/__init__.py
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/llama_index/callbacks/langfuse/langfuse_instrumentation.py
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/pyproject.toml
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/static/state_of_the_union_short.txt
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/tests/BUILD
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/tests/__init__.py
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/tests/test_langfuse_instrumentation.py
Labels: lgtm, size:XXL

#15490 add truncate support
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_truncate.py
Labels: lgtm, size:L

#15494 check remote reader urls
  llama-index-integrations/readers/llama-index-readers-remote/llama_index/readers/remote/base.py
  llama-index-integrations/readers/llama-index-readers-remote/pyproject.toml
Labels: size:S

#15496 allow s3 in remote reader
  llama-index-integrations/readers/llama-index-readers-remote/llama_index/readers/remote/base.py
  llama-index-integrations/readers/llama-index-readers-remote/pyproject.toml
Labels: size:XS

#15498 Fix publishing at the top-level?
  poetry.lock
  pyproject.toml
Labels: size:XS

#15503 publish_release fix again
  .github/workflows/publish_release.yml
Labels: size:XS

#15508 fix mistral embeddings usage
  llama-index-integrations/embeddings/llama-index-embeddings-mistralai/llama_index/embeddings/mistralai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-mistralai/pyproject.toml
Labels: size:S

#15507 Issue-15505 Added code to expose structured schema for Neptune
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/base.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/base_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/neptune.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/pyproject.toml
Labels: lgtm, size:M

#15506 Fix Issue 15504 - Remove requirement to specify "allowed_query_fields" parameter when using "cypher_validator" in TextToCypher retriever
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/text_to_cypher.py
Labels: lgtm, size:S

#15509 vbump mm gemini deps
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/pyproject.toml
Labels: size:XS

#15516 update lmformatenforcer docs
  docs/docs/examples/output_parsing/lmformatenforcer_regular_expressions.ipynb
Labels: size:XS

#15491 Support token counting for llama-index integration with bedrock
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
Labels: lgtm, size:M

#15525 More Pydantic V2 Migration (core)
  llama-index-core/llama_index/core/base/embeddings/base.py
  llama-index-core/llama_index/core/bridge/pydantic.py
Labels: lgtm, size:S

#15517 escape docstring
  llama-index-core/llama_index/core/vector_stores/types.py
Labels: lgtm, size:XS

#15524 Fix incorrect type in OpenAI token usage report
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai.py
Labels: lgtm, size:M

#15521 to support static input shape for openvino embedding and reranker
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/llama_index/embeddings/huggingface_openvino/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/llama_index/postprocessor/openvino_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/pyproject.toml
Labels: lgtm, size:M

#15501 Improve token counter to handle more response types
  llama-index-core/llama_index/core/callbacks/token_counting.py
Labels: lgtm, size:L

#15512 enhance google drive reader for improved functionality and usability
  llama-index-integrations/readers/llama-index-readers-google/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-google/README.md
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/drive/base.py
  llama-index-integrations/readers/llama-index-readers-google/pyproject.toml
Labels: lgtm, size:L

#15532 update some links on tools page
  docs/docs/module_guides/deploying/agents/tools.md
Labels: lgtm, size:XS
