Repository run-llama/llama_index, pull requests merged in 2024-11, with the labels that each got.

#16771 v0.11.21
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/siliconflow.md
  docs/docs/api_reference/memory/mem0.md
  docs/docs/api_reference/postprocessor/siliconflow_rerank.md
  docs/docs/api_reference/tools/vectara_query.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/memory/llama-index-memory-mem0/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#16785 fix empty index + generation synthesizer
  llama-index-core/llama_index/core/response_synthesizers/generation.py
  llama-index-core/tests/response_synthesizers/test_generate.py
Labels: size:L

#16790 fix/await-async-embeddings
  llama-index-integrations/embeddings/llama-index-embeddings-gemini/llama_index/embeddings/gemini/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-gemini/pyproject.toml
Labels: lgtm, size:XS

#16647 Improvement/sambanova integration
  docs/docs/examples/llm/sambanova.ipynb
  llama-index-integrations/llms/llama-index-llms-sambanova/README.md
  llama-index-integrations/llms/llama-index-llms-sambanova/llama_index/llms/sambanova/__init__.py
  llama-index-integrations/llms/llama-index-llms-sambanova/llama_index/llms/sambanova/base.py
  llama-index-integrations/llms/llama-index-llms-sambanova/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-sambanova/tests/test_llms_sambanova.py
Labels: lgtm, size:XXL

#16792 Fix ChromaDB Integration
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/llama_index/vector_stores/chroma/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/pyproject.toml
Labels: lgtm, size:XS

#16794 nits to llm notebooks
  docs/docs/examples/llm/fireworks.ipynb
  docs/docs/examples/llm/gemini.ipynb
  docs/docs/examples/llm/openai.ipynb
  docs/docs/examples/llm/upstage.ipynb
Labels: size:XL

#16798 vbump sambanova
  llama-index-integrations/llms/llama-index-llms-sambanova/README.md
  llama-index-integrations/llms/llama-index-llms-sambanova/pyproject.toml
Labels: size:S

#16799 Logan/sambanova fix
  docs/docs/examples/llm/sambanova.ipynb
  llama-index-integrations/llms/llama-index-llms-sambanova/llama_index/llms/sambanova/__init__.py
  llama-index-integrations/llms/llama-index-llms-sambanovacloud/.gitignore
  llama-index-integrations/llms/llama-index-llms-sambanovacloud/BUILD
  llama-index-integrations/llms/llama-index-llms-sambanovacloud/Makefile
  llama-index-integrations/llms/llama-index-llms-sambanovacloud/README.md
  llama-index-integrations/llms/llama-index-llms-sambanovacloud/llama_index/llms/sambanovacloud/BUILD
  llama-index-integrations/llms/llama-index-llms-sambanovacloud/llama_index/llms/sambanovacloud/__init__.py
  llama-index-integrations/llms/llama-index-llms-sambanovacloud/llama_index/llms/sambanovacloud/base.py
  llama-index-integrations/llms/llama-index-llms-sambanovacloud/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-sambanovacloud/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-sambanovacloud/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-sambanovacloud/tests/test_llms_sambanova.py
Labels: size:M

#16806 update filters, update version
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/llama_index/vector_stores/chroma/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/pyproject.toml
Labels: size:XS

#16809 Fix abstract method signature error
  llama-index-integrations/llms/llama-index-llms-dashscope/llama_index/llms/dashscope/base.py
  llama-index-integrations/llms/llama-index-llms-dashscope/pyproject.toml
Labels: lgtm, size:S

#16817 remove beam search param for latest vllm
  llama-index-integrations/llms/llama-index-llms-vllm/llama_index/llms/vllm/base.py
  llama-index-integrations/llms/llama-index-llms-vllm/pyproject.toml
Labels: size:S

#16804 Doc-fix at Understanding/Workflows/state.md for "TypeError: 'coroutine' object is not subscriptable"
  docs/docs/understanding/workflows/state.md
Labels: lgtm, size:XS

#16789 Logan/markdown splitter improve metadata
  llama-index-core/llama_index/core/node_parser/file/markdown.py
  llama-index-core/tests/node_parser/test_markdown.py
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/pyproject.toml
Labels: size:L

#16818 Hotfix: Chain Query Configuration
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-vectara/tests/test_indices_managed_vectara.py
Labels: lgtm, size:M

#16819 support sparse embedding models, fix delete for serverless for pinecone
  docs/docs/examples/vector_stores/PineconeIndexDemo-Hybrid.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/llama_index/vector_stores/pinecone/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/llama_index/vector_stores/pinecone/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/pyproject.toml
Labels: size:L

#16820 Fixed the JSON Format of Generated Sub-Question (double curly brackets)
  llama-index-core/llama_index/core/question_gen/prompts.py
Labels: lgtm, size:XS

#16822 fix: `required_exts` for one drive reader
  llama-index-integrations/readers/llama-index-readers-microsoft-onedrive/llama_index/readers/microsoft_onedrive/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-onedrive/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-microsoft-onedrive/tests/test_readers_microsoft_onedrive.py
Labels: lgtm, size:S

#16823 Add Anthropic Claude Haiku 3.5 to the list of supported Claude models
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: lgtm, size:XS

#16821 bring back support for prompt templates in context chat engines
  llama-index-core/llama_index/core/chat_engine/condense_plus_context.py
  llama-index-core/llama_index/core/chat_engine/context.py
  llama-index-core/llama_index/core/chat_engine/utils.py
Labels: size:M

#16825 Add Anthropic Claude Haiku 3.5 to the list of supported Claude models for bedrock and bedrock-converse integrations
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/llama_index/multi_modal_llms/anthropic/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/pyproject.toml
Labels: lgtm, size:S

#16824 fix ibm tests
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-ibm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ibm/tests/BUILD
Labels: size:S

#16830 More tolerant definition of LLMMetadata information
  llama-index-integrations/llms/llama-index-llms-dashscope/llama_index/llms/dashscope/base.py
  llama-index-integrations/llms/llama-index-llms-dashscope/pyproject.toml
Labels: lgtm, size:S

#16802 feat: Support for api_version and Azure AI model inference service
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/llama_index/embeddings/azure_inference/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/tests/test_embeddings_azure_inference.py
  llama-index-integrations/llms/llama-index-llms-azure-inference/README.md
  llama-index-integrations/llms/llama-index-llms-azure-inference/llama_index/llms/azure_inference/base.py
  llama-index-integrations/llms/llama-index-llms-azure-inference/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-azure-inference/tests/test_llms_azure_inference.py
Labels: lgtm, size:L

#16836 [docs]: Mem0 example docs modification
  docs/docs/examples/memory/Mem0Memory.ipynb
  docs/mkdocs.yml
Labels: lgtm, size:M

#16829 Add ColPali as reranker
  docs/docs/examples/node_postprocessor/ColPaliRerank.ipynb
  llama-index-integrations/postprocessor/llama-index-postprocessor-colpali-rerank/.gitignore
  llama-index-integrations/postprocessor/llama-index-postprocessor-colpali-rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-colpali-rerank/Makefile
  llama-index-integrations/postprocessor/llama-index-postprocessor-colpali-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-colpali-rerank/llama_index/postprocessor/colpali_rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-colpali-rerank/llama_index/postprocessor/colpali_rerank/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-colpali-rerank/llama_index/postprocessor/colpali_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-colpali-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-colpali-rerank/tests/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-colpali-rerank/tests/test_postprocessor_colpali_rerank.py
Labels: lgtm, size:L

#16842 Fix Asignee and Reporter metadata for Epics in JiraReader
  llama-index-integrations/readers/llama-index-readers-jira/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-jira/llama_index/readers/jira/base.py
  llama-index-integrations/readers/llama-index-readers-jira/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-jira/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-jira/tests/test_readers_jira.py
Labels: lgtm, size:L

#16848 Fix link to llama_deploy docs
  docs/docs/module_guides/workflow/index.md
Labels: lgtm, size:XS

#16849 fix docs build
  docs/docs/api_reference/llms/sambanova.md
  docs/mkdocs.yml
Labels: size:XS

#13038 Adds "Llamaindex-python" user agent to ai search requests
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/tests/test_azureaisearch.py
Labels: lgtm, size:M

#16853 fix var name in pinecone vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/llama_index/vector_stores/pinecone/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/pyproject.toml
Labels: size:XS

#16852 Fix workflow timeout streaming
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_streaming.py
Labels: size:M

#16841 [Feature] Include `_data` in `Event` serialization by default.
  llama-index-core/llama_index/core/workflow/events.py
  llama-index-core/tests/workflow/test_event.py
Labels: lgtm, size:M

#16855 Revert "Adds "Llamaindex-python" user agent to ai search requests (#1…
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/tests/test_azureaisearch.py
Labels: lgtm, size:M

#16831 Wordpress - allow options to set custom post types
  llama-index-integrations/readers/llama-index-readers-wordpress/README.md
  llama-index-integrations/readers/llama-index-readers-wordpress/llama_index/readers/wordpress/base.py
  llama-index-integrations/readers/llama-index-readers-wordpress/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-wordpress/tests/test_readers_wordpress.py
Labels: lgtm, size:L

#16803 Update pipeline.py
  llama-index-core/llama_index/core/ingestion/pipeline.py
  llama-index-core/llama_index/core/readers/file/base.py
  llama-index-legacy/llama_index/legacy/ingestion/pipeline.py
  llama-index-legacy/llama_index/legacy/readers/file/base.py
  llama-index-legacy/pyproject.toml
Labels: lgtm, size:S

#16843 Dglogo/nv sub q query eng
  docs/docs/examples/agent/nvidia_sub_question_query_engine.ipynb
Labels: lgtm, size:XS

#16764 fix ollama messages convert when including tool calls info
  llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
  llama-index-integrations/llms/llama-index-llms-ollama/pyproject.toml
Labels: lgtm, size:XS

#16859 Update Vectara RAG Pack Messaging
  llama-index-packs/llama-index-packs-vectara-rag/README.md
Labels: lgtm, size:S

#16864 Fix modelscope 'pipeline' referenced before assignment.
  llama-index-integrations/llms/llama-index-llms-modelscope/llama_index/llms/modelscope/base.py
  llama-index-integrations/llms/llama-index-llms-modelscope/llama_index/llms/modelscope/utils.py
  llama-index-integrations/llms/llama-index-llms-modelscope/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-modelscope/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-modelscope/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-modelscope/tests/test_modelscope.py
Labels: lgtm, size:M

#16868 rename databricks imports
  docs/docs/api_reference/llms/databricks.md
  docs/docs/examples/llm/databricks.ipynb
  llama-index-integrations/llms/llama-index-llms-databricks/pyproject.toml
Labels: size:XS

#16884 fix bug: `top_n` param should be used in __init__ function
  llama-index-integrations/postprocessor/llama-index-postprocessor-tei-rerank/llama_index/postprocessor/tei_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-tei-rerank/pyproject.toml
Labels: lgtm, size:XS

#16887 Fix Jira reader tests
  llama-index-integrations/readers/llama-index-readers-jira/tests/test_readers_jira.py
Labels: size:XS

#16873 Add the modelscope embedding feature.
  docs/docs/examples/embeddings/modelscope.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-modelscope/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-modelscope/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-modelscope/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-modelscope/llama_index/embeddings/modelscope/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-modelscope/llama_index/embeddings/modelscope/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-modelscope/llama_index/embeddings/modelscope/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-modelscope/llama_index/embeddings/modelscope/utils.py
  llama-index-integrations/embeddings/llama-index-embeddings-modelscope/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-modelscope/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-modelscope/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-modelscope/tests/test_modelscope.py
Labels: lgtm, size:L

#16882 skip model validation for nvdev llm models
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/base.py
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
Labels: lgtm, size:XS

#16883 skip model validation for nvdev embedding models
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
Labels: lgtm, size:XS

#16872 Added docstrings and unit tests for `core.multimodal`
  llama-index-core/llama_index/core/multi_modal_llms/generic_utils.py
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  llama-index-core/tests/multi_modal_llms/BUILD
  llama-index-core/tests/multi_modal_llms/test_base_multi_modal_llm_metadata.py
  llama-index-core/tests/multi_modal_llms/test_generic_utils.py
Labels: lgtm, size:L

#16892 fix not valid redirections in docs `getting_started/concepts`
  docs/docs/getting_started/concepts.md
Labels: lgtm, size:XS

#16895 Add UserAgent header "llamaindex-python" for azure search
  docs/docs/examples/vector_stores/AzureAISearchIndexDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/tests/test_azureaisearch.py
Labels: lgtm, size:M

#16904 fix typo and correct 404 url links
  docs/docs/examples/vector_stores/ChromaIndexDemo.ipynb
  docs/docs/module_guides/loading/connector/index.md
  docs/docs/module_guides/supporting_modules/settings.md
Labels: lgtm, size:XS

#16909 use new anthropic token counting api
  docs/docs/examples/llm/anthropic.ipynb
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: size:S

#16907 feat: add relative file path google drive
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/drive/base.py
  llama-index-integrations/readers/llama-index-readers-google/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-google/tests/test_readers_google_drive.py
Labels: lgtm, size:L

#16913 fix: Fix GraphRAG notebook V2
  docs/docs/examples/cookbooks/GraphRAG_v2.ipynb
Labels: lgtm, size:S

#16896 New function for `core.multi_modal_llms.generic_utils` & Anthropic LLM model updates
  llama-index-core/llama_index/core/multi_modal_llms/generic_utils.py
  llama-index-core/tests/multi_modal_llms/test_generic_utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
Labels: lgtm, size:L

#16886 Kùzu: Update relationship table label nomenclature
  llama-index-integrations/graph_stores/llama-index-graph-stores-kuzu/llama_index/graph_stores/kuzu/kuzu_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-kuzu/llama_index/graph_stores/kuzu/utils.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-kuzu/pyproject.toml
Labels: lgtm, size:L

#16912 [version] Bump llama-index-readers-file dependency to version 0.3.0
  llama-index-integrations/readers/llama-index-readers-gcs/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-github/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-joplin/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-mbox/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-obsidian/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-pandas-ai/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-pebblo/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-s3/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/pyproject.toml
  llama-index-networks/pyproject.toml
  llama-index-packs/llama-index-packs-code-hierarchy/pyproject.toml
  llama-index-packs/llama-index-packs-recursive-retriever/pyproject.toml
  llama-index-packs/llama-index-packs-resume-screener/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:M

#16862 Llama index readers gitbook
  llama-index-integrations/readers/llama-index-readers-gitbook/.gitignore
  llama-index-integrations/readers/llama-index-readers-gitbook/BUILD
  llama-index-integrations/readers/llama-index-readers-gitbook/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-gitbook/Makefile
  llama-index-integrations/readers/llama-index-readers-gitbook/README.md
  llama-index-integrations/readers/llama-index-readers-gitbook/llama_index/readers/gitbook/BUILD
  llama-index-integrations/readers/llama-index-readers-gitbook/llama_index/readers/gitbook/__init__.py
  llama-index-integrations/readers/llama-index-readers-gitbook/llama_index/readers/gitbook/base.py
  llama-index-integrations/readers/llama-index-readers-gitbook/llama_index/readers/gitbook/gitbook_client.py
  llama-index-integrations/readers/llama-index-readers-gitbook/poetry.lock
  llama-index-integrations/readers/llama-index-readers-gitbook/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-gitbook/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-gitbook/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-gitbook/tests/fixtures/BUILD
  llama-index-integrations/readers/llama-index-readers-gitbook/tests/fixtures/page_content_response.json
  llama-index-integrations/readers/llama-index-readers-gitbook/tests/fixtures/pages_response.json
  llama-index-integrations/readers/llama-index-readers-gitbook/tests/fixtures/space_response.json
  llama-index-integrations/readers/llama-index-readers-gitbook/tests/test_gitbook_client.py
  llama-index-integrations/readers/llama-index-readers-gitbook/tests/test_simple_gitbook_reader.py
Labels: lgtm, size:XL

#16919 v0.11.23
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/modelscope.md
  docs/docs/api_reference/llms/siliconflow.md
  docs/docs/api_reference/postprocessor/colpali_rerank.md
  docs/docs/api_reference/readers/gitbook.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#16924 Hotfix: Forgot to increment `llama-index-llms-anthropic` to `v0.4.1`
  .github/workflows/coverage.yml
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: lgtm, size:XS

#16931 remove open telemetry docs
  docs/docs/api_reference/callbacks/opentelemetry.md
Labels: size:XS

#16928 Ky/dynamic pg triplet retrieval limit
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/llm_synonym.py
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/vector.py
Labels: lgtm, size:M

#16933 add support for files endpoints
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/base.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/tests/test_indices_managed_llama_cloud.py
Labels: lgtm, size:L

#16934 allow skipping waiting for ingestion when uploading file
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/base.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
Labels: lgtm, size:M

#16942 Fix async streaming with bedrock converse
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: size:M

#16947 Swap out Mendable for RunLLM
  docs/docs/javascript/mendablesearch.js
  docs/docs/javascript/runllm.js
  docs/mkdocs.yml
Labels: lgtm, size:M

#16938 Minor doc fixes
  docs/docs/understanding/workflows/basic_flow.md
  docs/docs/understanding/workflows/concurrent_execution.md
  docs/docs/understanding/workflows/index.md
  docs/docs/understanding/workflows/stream.md
Labels: lgtm, size:XS

#16936 Remove an extra word
  llama-index-core/llama_index/core/agent/react/templates/system_header_template.md
Labels: lgtm, size:XS

#16949 Update broken notebook URLs
  docs/docs/examples/property_graph/property_graph_advanced.ipynb
  docs/docs/examples/property_graph/property_graph_basic.ipynb
  docs/docs/examples/property_graph/property_graph_falkordb.ipynb
  docs/docs/examples/property_graph/property_graph_kuzu.ipynb
  docs/docs/examples/property_graph/property_graph_memgraph.ipynb
  docs/docs/examples/property_graph/property_graph_neo4j.ipynb
  docs/docs/examples/property_graph/property_graph_tidb.ipynb
  docs/pyproject.toml
Labels: lgtm, size:S

#16751 Raspawar/add vlm support
  docs/docs/examples/multi_modal/nvidia_multi_modal.ipynb
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/.gitignore
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/Makefile
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/README.md
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/llama_index/multi_modal_llms/nvidia/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/llama_index/multi_modal_llms/nvidia/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/llama_index/multi_modal_llms/nvidia/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/llama_index/multi_modal_llms/nvidia/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/tests/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/tests/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/tests/conftest.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/tests/test_api_key.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/tests/test_available_models.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/tests/test_multi_modal_nvidia.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/tests/test_utils.py
Labels: lgtm, size:XXL

#16835 feat: add get_permission_info to resource reader mixin + readers
  llama-index-core/llama_index/core/readers/base.py
  llama-index-core/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-microsoft-onedrive/llama_index/readers/microsoft_onedrive/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-onedrive/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/llama_index/readers/microsoft_sharepoint/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/pyproject.toml
Labels: lgtm, size:M

#16954 Weaviate vector store kwargs
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/tests/test_vector_stores_weaviate.py
Labels: lgtm, size:S

#16927 Add ID support for LlamaCloudIndex & update from_documents logic
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/api_utils.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/base.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/tests/test_indices_managed_llama_cloud.py
Labels: lgtm, size:XL

#16948 Fix dependencies for llama-index-vector-stores-mongodb
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/pyproject.toml
Labels: lgtm, size:XS

#16963 Remove "ask a person" button from RunLLM
  docs/docs/javascript/runllm.js
Labels: lgtm, size:XS

#16965 feat: Resolving UserWarning about llama-index-llms-dashscope
  llama-index-integrations/llms/llama-index-llms-dashscope/llama_index/llms/dashscope/base.py
  llama-index-integrations/llms/llama-index-llms-dashscope/pyproject.toml
Labels: lgtm, size:XS

#16979 New structured data extraction tutorial, cleanup and crosslinks
  docs/docs/examples/structured_outputs/structured_outputs.ipynb
  docs/docs/module_guides/querying/structured_outputs/index.md
  docs/docs/module_guides/querying/structured_outputs/pydantic_program.md
  docs/docs/understanding/extraction/index.md
  docs/docs/understanding/extraction/lower_level.md
  docs/docs/understanding/extraction/structured_llms.md
  docs/docs/understanding/extraction/structured_prediction.md
  docs/docs/use_cases/extraction.md
  docs/mkdocs.yml
Labels: lgtm, size:XL

#16969 Pipeshift Integration docs related fixes
  docs/docs/examples/llm/pipeshift.ipynb
  llama-index-integrations/llms/llama-index-llms-pipeshift/README.md
  llama-index-integrations/llms/llama-index-llms-pipeshift/llama_index/llms/pipeshift/base.py
Labels: lgtm, size:L

#16968 change available_models to return List[Model], previously List[str]
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/llama_index/multi_modal_llms/nvidia/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/tests/test_available_models.py
Labels: lgtm, size:S

#16976 Add Custom Prompt Parameter
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-vectara/tests/test_indices_managed_vectara.py
Labels: lgtm, size:S

#16961 feat[confluence]: Permit passing params to Confluence client
  llama-index-integrations/readers/llama-index-readers-confluence/README.md
  llama-index-integrations/readers/llama-index-readers-confluence/llama_index/readers/confluence/base.py
  llama-index-integrations/readers/llama-index-readers-confluence/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-confluence/tests/test_readers_confluence.py
Labels: lgtm, size:M

#16973 chore: drop support for 3.8
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:S

#16991 Add support for mistral latest models
  docs/docs/examples/multi_modal/mistral_multi_modal.ipynb
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/llama_index/multi_modal_llms/mistralai/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/pyproject.toml
Labels: lgtm, size:XS

#16993 title change for mistral multimodal notebook
  docs/docs/examples/multi_modal/mistral_multi_modal.ipynb
Labels: size:XS

#16955 Bedrock Cross-Region support
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
Labels: lgtm, size:M

#16952 support for Deeplake v4 api
  llama-index-integrations/vector_stores/llama-index-vector-stores-deeplake/llama_index/vector_stores/deeplake/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-deeplake/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-deeplake/tests/test_vector_stores_deeplake.py
Labels: lgtm, size:L

#16930 Improvement/sambanova integration sambastudio
  docs/docs/api_reference/llms/sambanovasystems.md
  docs/docs/examples/llm/sambanova.ipynb
  docs/docs/examples/llm/sambanovasystems.ipynb
  docs/mkdocs.yml
  llama-index-integrations/llms/llama-index-llms-sambanovacloud/llama_index/llms/sambanovacloud/__init__.py
  llama-index-integrations/llms/llama-index-llms-sambanovacloud/llama_index/llms/sambanovacloud/base.py
  llama-index-integrations/llms/llama-index-llms-sambanovasystems/.gitignore
  llama-index-integrations/llms/llama-index-llms-sambanovasystems/BUILD
  llama-index-integrations/llms/llama-index-llms-sambanovasystems/Makefile
  llama-index-integrations/llms/llama-index-llms-sambanovasystems/README.md
  llama-index-integrations/llms/llama-index-llms-sambanovasystems/llama_index/llms/sambanovasystems/BUILD
  llama-index-integrations/llms/llama-index-llms-sambanovasystems/llama_index/llms/sambanovasystems/__init__.py
  llama-index-integrations/llms/llama-index-llms-sambanovasystems/llama_index/llms/sambanovasystems/base.py
  llama-index-integrations/llms/llama-index-llms-sambanovasystems/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-sambanovasystems/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-sambanovasystems/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-sambanovasystems/tests/test_llms_sambanovasystems.py
Labels: lgtm, size:XXL

#16918 Feature/elevenlabs tool integration
  llama-index-integrations/tools/llama-index-tools-elevenlabs/.gitignore
  llama-index-integrations/tools/llama-index-tools-elevenlabs/BUILD
  llama-index-integrations/tools/llama-index-tools-elevenlabs/CHANGELOG.md
  llama-index-integrations/tools/llama-index-tools-elevenlabs/Makefile
  llama-index-integrations/tools/llama-index-tools-elevenlabs/README.md
  llama-index-integrations/tools/llama-index-tools-elevenlabs/examples/elevenlabs_speech.ipynb
  llama-index-integrations/tools/llama-index-tools-elevenlabs/llama_index/tools/elevenlabs/BUILD
  llama-index-integrations/tools/llama-index-tools-elevenlabs/llama_index/tools/elevenlabs/__init__.py
  llama-index-integrations/tools/llama-index-tools-elevenlabs/llama_index/tools/elevenlabs/base.py
  llama-index-integrations/tools/llama-index-tools-elevenlabs/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-elevenlabs/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-elevenlabs/tests/__init__.py
  llama-index-integrations/tools/llama-index-tools-elevenlabs/tests/test_tools_elevenlabs.py
Labels: size:L

#17001 api_key typo in llama-cloud-index
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/base.py
Labels: size:XS

#16998 Fix: Correct typo in replicate multi modal package
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-replicate/llama_index/multi_modal_llms/replicate/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-replicate/pyproject.toml
Labels: size:XS

#17007 add get_nodes to pinecone
  docs/docs/examples/vector_stores/PineconeIndexDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/llama_index/vector_stores/pinecone/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/pyproject.toml
Labels: size:L

#17008 fix samba api docs
  docs/docs/api_reference/llms/sambanovasystems.md
Labels: size:XS

#16992 feat[react-multimodal]: add gemini support for images in MultimodalReActAgentWorker
  llama-index-core/llama_index/core/agent/react_multimodal/step.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/llama_index/multi_modal_llms/gemini/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/tests/test_multi-modal-llms_gemini_utils.py
Labels: lgtm, size:M

#16996 zhipuai add stop param to api
  llama-index-integrations/llms/llama-index-llms-zhipuai/README.md
  llama-index-integrations/llms/llama-index-llms-zhipuai/llama_index/llms/zhipuai/base.py
  llama-index-integrations/llms/llama-index-llms-zhipuai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-zhipuai/tests/test_llms_zhipuai.py
Labels: lgtm, size:L

#16975 Policy for removing stale packages
  STALE.md
  scripts/integration_health_check.py
Labels: lgtm, size:L

#16783 Feature/integration nebius
  docs/docs/api_reference/embeddings/nebius.md
  docs/docs/api_reference/llms/nebius.md
  docs/docs/api_reference/multi_modal_llms/nebius.md
  docs/docs/examples/embeddings/nebius.ipynb
  docs/docs/examples/llm/nebius.ipynb
  docs/docs/examples/multi_modal/nebius_multi_modal.ipynb
  docs/mkdocs.yml
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/embeddings/llama-index-embeddings-nebius/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-nebius/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-nebius/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-nebius/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-nebius/llama_index/embeddings/nebius/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-nebius/llama_index/embeddings/nebius/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-nebius/llama_index/embeddings/nebius/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nebius/llama_index/embeddings/nebius/utils.py
  llama-index-integrations/embeddings/llama-index-embeddings-nebius/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nebius/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-nebius/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-nebius/tests/test_embeddings_nebius.py
  llama-index-integrations/llms/llama-index-llms-nebius/.gitignore
  llama-index-integrations/llms/llama-index-llms-nebius/BUILD
  llama-index-integrations/llms/llama-index-llms-nebius/Makefile
  llama-index-integrations/llms/llama-index-llms-nebius/README.md
  llama-index-integrations/llms/llama-index-llms-nebius/llama_index/llms/nebius/BUILD
  llama-index-integrations/llms/llama-index-llms-nebius/llama_index/llms/nebius/__init__.py
  llama-index-integrations/llms/llama-index-llms-nebius/llama_index/llms/nebius/base.py
  llama-index-integrations/llms/llama-index-llms-nebius/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-nebius/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-nebius/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-nebius/tests/test_llms_nebius.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nebius/.gitignore
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nebius/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nebius/Makefile
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nebius/README.md
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nebius/llama_index/multi_modal_llms/nebius/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nebius/llama_index/multi_modal_llms/nebius/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nebius/llama_index/multi_modal_llms/nebius/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nebius/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nebius/tests/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nebius/tests/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nebius/tests/test_multi_modal_llms_nebius.py
Labels: lgtm, size:XXL

#16962 feat: Multimodal Node
  .gitignore
  .pre-commit-config.yaml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/bridge/pydantic.py
  llama-index-core/llama_index/core/schema.py
  llama-index-core/pyproject.toml
  llama-index-core/tests/BUILD
  llama-index-core/tests/schema/BUILD
  llama-index-core/tests/schema/__init__.py
  llama-index-core/tests/schema/data/data.txt
  llama-index-core/tests/schema/test_base_component.py
  llama-index-core/tests/schema/test_base_node.py
  llama-index-core/tests/schema/test_media_resource.py
  llama-index-core/tests/schema/test_node.py
  llama-index-core/tests/schema/test_schema.py
  llama-index-integrations/node_parser/llama-index-node-parser-docling/tests/test_node_parser_docling.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-colpali-rerank/tests/test_postprocessor_colpali_rerank.py
  llama-index-integrations/readers/llama-index-readers-docling/tests/test_readers_docling.py
Labels: lgtm, size:XL

#17015 improve function calling check for legacy openai agents
  llama-index-integrations/agent/llama-index-agent-openai-legacy/llama_index/agent/openai_legacy/context_retriever_agent.py
  llama-index-integrations/agent/llama-index-agent-openai-legacy/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:XS

#17018 v0.12.1
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/tools/elevenlabs.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#17034 Feat: IBM watsonx.ai acomplete & achat integration
  llama-index-integrations/llms/llama-index-llms-ibm/llama_index/llms/ibm/base.py
  llama-index-integrations/llms/llama-index-llms-ibm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ibm/tests/test_ibm.py
Labels: lgtm, size:M

#17040 improve traceback logging for workflows
  llama-index-core/llama_index/core/instrumentation/dispatcher.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-integrations/embeddings/llama-index-embeddings-nebius/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-nebius/pyproject.toml
Labels: size:M

#17047 [fix] Handling of WorkflowDone exception
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_streaming.py
  llama-index-core/tests/workflow/test_workflow.py
  llama-index-integrations/embeddings/llama-index-embeddings-nebius/pyproject.toml
Labels: lgtm, size:S

#17051 update contributing guide and dev deps
  CONTRIBUTING.md
  docs/docs/CONTRIBUTING.md
  poetry.lock
  pyproject.toml
Labels: size:M

#15265 [Feature] MongoDB Atlas: Adds search index commands and tests/examples of metadata filters
  docs/docs/examples/vector_stores/MongoDBAtlasVectorSearch.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/llama_index/vector_stores/mongodb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/llama_index/vector_stores/mongodb/index.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/llama_index/vector_stores/mongodb/pipelines.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/conftest.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/test_filters.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/test_index_commands.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/test_integration.py
Labels: lgtm, size:XL

#17054 Add property graph Memgraph jupyter notebook example to the docs
  docs/mkdocs.yml
Labels: lgtm, size:XS

#17058 fixes tool_choice in certain scenarios for openai
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/program/llama-index-program-openai/llama_index/program/openai/base.py
  llama-index-integrations/program/llama-index-program-openai/pyproject.toml
Labels: size:M

#17057 deeplake v3 backward compatibility
  llama-index-integrations/vector_stores/llama-index-vector-stores-deeplake/llama_index/vector_stores/deeplake/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-deeplake/pyproject.toml
Labels: lgtm, size:M

#17045 Fix: update perplexity models, add unit tests and minor fixes
  llama-index-integrations/llms/llama-index-llms-perplexity/llama_index/llms/perplexity/base.py
  llama-index-integrations/llms/llama-index-llms-perplexity/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-perplexity/tests/test_perplexity.py
Labels: lgtm, size:L

#17042 - chore: remove example notebook on deprecated pinecone reader
  docs/docs/examples/data_connectors/PineconeDemo.ipynb
Labels: size:L

#17061 Fix box api - mypy breakage
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxAPI/box_api.py
  llama-index-integrations/readers/llama-index-readers-box/pyproject.toml
Labels: lgtm, size:S

#17060 mark code splitter tests as optional
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  llama-index-core/tests/text_splitter/test_code_splitter.py
  poetry.lock
  pyproject.toml
Labels: size:S

#17062 Fix base component tests
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  llama-index-core/tests/schema/test_base_component.py
Labels: size:S

#17006 [Feature] Checkpointing with Workflows
  docs/docs/examples/workflow/checkpointing_workflows.ipynb
  docs/docs/examples/workflow/parallel_execution.ipynb
  docs/docs/module_guides/workflow/index.md
  docs/docs/understanding/workflows/observability.md
  llama-index-core/llama_index/core/workflow/__init__.py
  llama-index-core/llama_index/core/workflow/checkpointer.py
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/llama_index/core/workflow/errors.py
  llama-index-core/llama_index/core/workflow/handler.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_checkpointer.py
Labels: lgtm, size:XXL

#17067 [DOCS] remove Argilla legacy callback and add to instrumentation
  docs/docs/api_reference/callbacks/argilla.md
Labels: lgtm, size:XS

#17031 Add stream_chat and conditionally set AutoModelClass to MllamaForConditionalGeneration
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/llama_index/multi_modal_llms/huggingface/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/pyproject.toml
Labels: lgtm, size:S

#16997 Upgrading pyarrow to v18 to allow usage of numpy >= 2.0
  llama-index-integrations/embeddings/llama-index-embeddings-vertex/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-vertex/pyproject.toml
  poetry.lock
Labels: size:XS

#17039 feat: Make `ChatMessage` use `ContentBlock`s for data storage
  .github/workflows/unit_test.yml
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/llama_index/core/memory/vector_memory.py
  llama-index-core/tests/base/__init__.py
  llama-index-core/tests/base/llms/BUILD
  llama-index-core/tests/base/llms/__init__.py
  llama-index-core/tests/base/llms/test_types.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/tests/test_chat_store_postgres_chat_store.py
Labels: lgtm, size:L

#17079 ci: manually install pants
  .github/workflows/coverage.yml
  .github/workflows/unit_test.yml
Labels: lgtm, size:M

#17083 Remove unused `store_checkpoints` var in tests and example notebook
  docs/docs/examples/workflow/checkpointing_workflows.ipynb
  docs/docs/examples/workflow/parallel_execution.ipynb
  llama-index-core/tests/workflow/test_checkpointer.py
Labels: size:S

#17078 [Integrations]: Bump version for Kùzu
  llama-index-integrations/graph_stores/llama-index-graph-stores-kuzu/pyproject.toml
Labels: lgtm, size:XS

#17080 [DOCS] Add Argilla to integration docs
  docs/docs/_static/integrations/argilla.png
  docs/docs/module_guides/observability/index.md
Labels: lgtm, size:M

#17073 fix/anyscale-embbeding-retry
  llama-index-integrations/embeddings/llama-index-embeddings-anyscale/llama_index/embeddings/anyscale/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-anyscale/pyproject.toml
Labels: lgtm, size:L

#17072 fix/openai-embbeding-retry
  llama-index-integrations/embeddings/llama-index-embeddings-openai/llama_index/embeddings/openai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-openai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-openai/tests/test_embeddings_openai.py
  llama-index-integrations/embeddings/llama-index-embeddings-openai/tests/test_utils.py
Labels: lgtm, size:L

#17081 Update upstage solar pro model tokenizer
  llama-index-integrations/llms/llama-index-llms-upstage/llama_index/llms/upstage/utils.py
  llama-index-integrations/llms/llama-index-llms-upstage/pyproject.toml
Labels: lgtm, size:XS

#17092 fix: use prepared statement in DuckDBRetriever
  llama-index-integrations/retrievers/llama-index-retrievers-duckdb-retriever/llama_index/retrievers/duckdb_retriever/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-duckdb-retriever/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-duckdb-retriever/tests/test_retrievers_bm25_retriever.py
Labels: lgtm, size:M

#17097 fix: Broken links in documentation
  docs/docs/module_guides/deploying/agents/index.md
  docs/docs/module_guides/deploying/agents/modules.md
  docs/docs/use_cases/agents.md
Labels: lgtm, size:XS

#17110 [FIX] Move `JSONalyzeQueryEngine` to experimental
  llama-index-core/llama_index/core/query_engine/__init__.py
  llama-index-core/llama_index/core/query_engine/jsonalyze/BUILD
  llama-index-core/llama_index/core/query_engine/jsonalyze/__init__.py
  llama-index-core/llama_index/core/query_engine/jsonalyze/jsonalyze_query_engine.py
  llama-index-experimental/llama_index/experimental/query_engine/jsonalyze/BUILD
  llama-index-experimental/llama_index/experimental/query_engine/jsonalyze/__init__.py
  llama-index-experimental/llama_index/experimental/query_engine/jsonalyze/jsonalyze_query_engine.py
  llama-index-experimental/pyproject.toml
Labels: lgtm, size:M

#17100 Create tables for pgvector regardless of schema status
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: size:M

#17114 Remove forgotten print in ChatMemoryBuffer
  llama-index-core/llama_index/core/memory/chat_memory_buffer.py
Labels: lgtm, size:XS
