Repository run-llama/llama_index, pull requests merged in 2024-01, with the labels that each got.

#9782 add missing azure openai model context sizes
  llama_index/llms/openai_utils.py
Labels: size:XS

#9786 Fix recursive retreiver notebooks
  docs/examples/retrievers/recursive_retriever_nodes.ipynb
Labels: size:L

#9779 add concurrency limit for data generation
  llama_index/llama_dataset/generator.py
Labels: size:S

#9787 Igore `_static`, the folder for NLTK & Tiktoken caches
  .gitignore
Labels: size:XS

#9791 chore: + the linter `mypy` as a pre-commit hook
  .pre-commit-config.yaml
  llama_index/embeddings/pooling.py
  tests/vector_stores/test_elasticsearch.py
Labels: size:S

#9798 Update ElasticsearchStore base class for ingestion pipeline
  llama_index/vector_stores/elasticsearch.py
Labels: size:M

#9790 Fixing `description` error management in Issue #9777
  docs/examples/output_parsing/openai_pydantic_program.ipynb
  llama_index/llms/openai_utils.py
  llama_index/program/openai_program.py
  tests/llms/test_openai_utils.py
Labels: size:L

#9789 bugfix: `_verify_source_safety` should detect calls to private functions with AST, not regexes
  llama_index/exec_utils.py
  tests/test_exec_utils.py
Labels: size:M

#9805 Update default embedding batch size for OpenAI embeddings
  llama_index/embeddings/openai.py
Labels: lgtm, size:XS

#9804 Pierre/fix markdown element
  llama_index/node_parser/relational/markdown_element.py
  tests/node_parser/test_markdown_element.py
Labels: lgtm, size:L

#9754 jaguar vector store
  docs/community/integrations/vector_stores.md
  docs/examples/vector_stores/JaguarIndexDemo.ipynb
  docs/module_guides/storing/customization.md
  docs/module_guides/storing/vector_stores.md
  llama_index/readers/jaguar.py
  llama_index/vector_stores/jaguar.py
  llama_index/vector_stores/registry.py
  tests/readers/test_jaguar.py
  tests/vector_stores/test_jaguar.py
Labels: vector store, lgtm, size:XXL

#9810 Update cosine distance operator for Lantern
  llama_index/vector_stores/lantern.py
Labels: lgtm, size:XS

#9808 Update README.md
  README.md
Labels: lgtm, size:XS

#9806 fix mongoDB doc imports
  docs/examples/data_connectors/MongoDemo.ipynb
  docs/examples/data_connectors/WebPageDemo.ipynb
Labels: size:S

#9801 Integrations/deepeval observability
  docs/module_guides/observability/observability.md
  llama_index/callbacks/deepeval_callback.py
  llama_index/callbacks/global_handlers.py
Labels: lgtm, size:M

#9814 Upd batch size for qdrant vdb for ingestion
  llama_index/vector_stores/qdrant.py
Labels: lgtm, size:S

#9815 [version] bump to v0.9.25
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#9807 add multimodal react agent
  docs/examples/multi_modal/mm_agent.ipynb
  docs/use_cases/multimodal.md
  llama_index/agent/__init__.py
  llama_index/agent/react_multimodal/__init__.py
  llama_index/agent/react_multimodal/prompts.py
  llama_index/agent/react_multimodal/step.py
  llama_index/agent/runner/base.py
Labels: size:XXL

#9817 [version] bump version to 0.9.25.post1
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#9825 Agents were accidentally omitted from API reference
  docs/api_reference/index.rst
Labels: lgtm, size:XS

#9821 (docs) Fix documentation link
  docs/examples/metadata_extraction/EntityExtractionClimate.ipynb
Labels: lgtm, size:XS

#9838 added an example of query filter to jaguar vector store
  docs/examples/vector_stores/JaguarIndexDemo.ipynb
Labels: lgtm, size:M

#9833 chore: add llm kwargs for program
  llama_index/program/llm_program.py
  llama_index/program/lmformatenforcer_program.py
  llama_index/program/multi_modal_llm_program.py
  llama_index/program/openai_program.py
Labels: lgtm, size:M

#9836 Adds the column name to the text if using the database reader
  llama_index/readers/database.py
Labels: lgtm, size:XS

#9832 elasticsearch user agent regex update (#9831)
  tests/vector_stores/test_elasticsearch.py
Labels: lgtm, size:XS

#9488 Support for Nvidia Triton LLM
  .gitignore
  docs/examples/llm/nvidia_triton.ipynb
  docs/module_guides/models/llms/modules.md
  llama_index/llms/__init__.py
  llama_index/llms/nvidia_triton.py
  llama_index/llms/nvidia_triton_utils.py
  poetry.lock
Labels: size:XL, nvidia_genai

#9844 Add prompt formatting to langchain llm
  llama_index/llms/langchain.py
Labels: lgtm, size:M

#9846 Create BaseAutoRetriever base class
  llama_index/core/__init__.py
  llama_index/core/base_auto_retriever.py
  llama_index/indices/vector_store/retrievers/auto_retriever/auto_retriever.py
Labels: lgtm, size:L

#9845 Enable passing `tree_sitter` parser instance to `CodeSplitter`
  llama_index/node_parser/text/code.py
  tests/text_splitter/test_code_splitter.py
Labels: lgtm, size:L

#9824 Update notebook for Google Semantic Retriever
  docs/examples/managed/GoogleDemo.ipynb
Labels: lgtm, size:L

#9849 Documentation fixes
  CHANGELOG.md
  CONTRIBUTING.md
  docs/DOCS_README.md
Labels: lgtm, size:XS

#9840 Update description in docs/examples/managed/zcpDemo.ipynb
  docs/community/integrations/managed_indices.md
  docs/examples/managed/zcpDemo.ipynb
Labels: lgtm, size:M

#9852 Add missing dependency for `docs` group: `sphinx-automodapi`
  poetry.lock
  pyproject.toml
Labels: size:XS

#9854 return actual node ids in weaviate
  llama_index/vector_stores/weaviate.py
Labels: lgtm, size:XS

#9858 fix: typo
  docs/module_guides/evaluating/evaluating_with_llamadatasets.md
Labels: lgtm, size:XS

#9861 Add back erroneously deleted Retriever Eval notebook
  docs/examples/evaluation/retrieval/retriever_eval.ipynb
Labels: lgtm, size:L

#9860 docker-compose.yml moved (#9859)
  tests/docker-compose.yml
  tests/vector_stores/test_elasticsearch.py
Labels: size:XS

#9863 Add `BaseChatStore` and `SimpleChatStore` for storing conversation history
  docs/examples/query_engine/sec_tables/tesla_10q_table.ipynb
  docs/module_guides/storing/chat_stores.md
  docs/module_guides/storing/storing.md
  llama_index/memory/chat_memory_buffer.py
  llama_index/memory/types.py
  llama_index/storage/chat_store/__init__.py
  llama_index/storage/chat_store/base.py
  llama_index/storage/chat_store/loading.py
  llama_index/storage/chat_store/simple_chat_store.py
  tests/storage/chat_store/__init__.py
  tests/storage/chat_store/test_simple_chat_store.py
Labels: lgtm, size:L

#9847 make text storage optional on docstore
  llama_index/ingestion/pipeline.py
  llama_index/storage/docstore/keyval_docstore.py
  llama_index/storage/docstore/types.py
Labels: size:M

#9830 Feat/update guidance lib
  llama_index/program/guidance_program.py
  llama_index/prompts/guidance_utils.py
  llama_index/question_gen/guidance_generator.py
  llama_index/question_gen/prompts.py
  tests/program/test_guidance.py
  tests/question_gen/test_guidance_generator.py
Labels: size:M

#9870 [version] bump to v0.9.26
  CHANGELOG.md
  llama_index/VERSION
  llama_index/storage/chat_store/simple_chat_store.py
  pyproject.toml
Labels: size:S

#9869 Fix (#9867) sync_to_async to avoid blocking during asynchronous calls
  llama_index/tools/function_tool.py
Labels: lgtm, size:XS

#9866 A single node passed into compute_scores returns as a float
  llama_index/postprocessor/flag_embedding_reranker.py
Labels: lgtm, size:XS

#9878 Remove extra linting steps
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  Makefile
Labels: size:XS

#9880 Redis Chat Store support
  docs/module_guides/storing/chat_stores.md
  llama_index/storage/chat_store/__init__.py
  llama_index/storage/chat_store/redis_chat_store.py
  tests/storage/chat_store/test_redis_chat_store.py
Labels: lgtm, size:L

#9886 add vectara links
  docs/community/integrations/managed_indices.md
  docs/module_guides/querying/retriever/retrievers.md
Labels: size:XS

#9885 Added __init__.py in question_gen module
  llama_index/question_gen/__init__.py
Labels: lgtm, size:S

#9892 fix custom extractor docs
  docs/module_guides/indexing/metadata_extraction.md
Labels: size:XS

#9895 Qdrant Text Match Filter
  llama_index/vector_stores/qdrant.py
  llama_index/vector_stores/types.py
Labels: lgtm, size:XS

#9894 Fusion top k for hybrid search
  llama_index/vector_stores/qdrant.py
  llama_index/vector_stores/types.py
Labels: lgtm, size:XS

#9900 Fix incorrect id assignment in MyScale query result
  llama_index/vector_stores/myscale.py
Labels: lgtm, size:XS

#9897 added NE filter for qdrant payloads
  llama_index/vector_stores/qdrant.py
Labels: lgtm, size:S

#9907 filter out negative indexes from faiss query
  llama_index/vector_stores/faiss.py
Labels: size:S

#9906 add postgres docker
  poetry.lock
  pyproject.toml
  tests/docker-compose.yml
  tests/initialization/postgres/Dockerfile
  tests/initialization/postgres/postgres_init.sql
Labels: size:S

#9901 Propagate `tool_choice` flag to downstream APIs
  llama_index/agent/runner/base.py
Labels: lgtm, size:XS

#9890 Fix 9219: OpenAIAgent using AzureOpenAI not working with stream_chat and astream_chat
  llama_index/llms/openai.py
Labels: lgtm, size:S

#9908 add query pipeline
  docs/examples/pipeline/query_pipeline.ipynb
  docs/module_guides/querying/pipeline/module_usage.md
  docs/module_guides/querying/pipeline/modules.md
  docs/module_guides/querying/pipeline/root.md
  docs/module_guides/querying/pipeline/usage_pattern.md
  docs/module_guides/querying/querying.md
  llama_index/core/base_query_engine.py
  llama_index/core/base_retriever.py
  llama_index/core/query_pipeline/__init__.py
  llama_index/core/query_pipeline/query_component.py
  llama_index/indices/query/query_transform/base.py
  llama_index/llms/ai21.py
  llama_index/llms/anthropic.py
  llama_index/llms/base.py
  llama_index/llms/bedrock.py
  llama_index/llms/clarifai.py
  llama_index/llms/cohere.py
  llama_index/llms/custom.py
  llama_index/llms/gemini.py
  llama_index/llms/gradient.py
  llama_index/llms/huggingface.py
  llama_index/llms/konko.py
  llama_index/llms/langchain.py
  llama_index/llms/litellm.py
  llama_index/llms/llama_api.py
  llama_index/llms/llama_cpp.py
  llama_index/llms/llm.py
  llama_index/llms/mistral.py
  llama_index/llms/mock.py
  llama_index/llms/monsterapi.py
  llama_index/llms/nvidia_triton.py
  llama_index/llms/ollama.py
  llama_index/llms/openai.py
  llama_index/llms/openllm.py
  llama_index/llms/palm.py
  llama_index/llms/perplexity.py
  llama_index/llms/portkey.py
  llama_index/llms/predibase.py
  llama_index/llms/replicate.py
  llama_index/llms/rungpt.py
  llama_index/llms/vertex.py
  llama_index/llms/vllm.py
  llama_index/llms/watsonx.py
  llama_index/llms/xinference.py
  llama_index/output_parsers/base.py
  llama_index/output_parsers/guardrails.py
  llama_index/output_parsers/langchain.py
  llama_index/output_parsers/pydantic.py
  llama_index/postprocessor/types.py
  llama_index/prompts/base.py
  llama_index/query_pipeline/__init__.py
  llama_index/query_pipeline/query.py
  llama_index/response_synthesizers/base.py
  poetry.lock
  pyproject.toml
  tests/llms/test_custom.py
  tests/query_pipeline/__init__.py
  tests/query_pipeline/query.py
Labels: size:XXL

#9909 add hybrid search to qdrant table
  docs/module_guides/storing/vector_stores.md
Labels: lgtm, size:XS

#9910 [version] bump version to 0.9.27
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#9922 pop uneeded embedding args for huggingface embeddings
  llama_index/embeddings/huggingface.py
  llama_index/embeddings/huggingface_optimum.py
Labels: size:XS

#9917 Fix init reader bug
  llama_index/__init__.py
Labels: lgtm, size:S

#9916 Add doc id for different readers
  llama_index/readers/discord_reader.py
  llama_index/readers/elasticsearch.py
  llama_index/readers/google_readers/gsheets.py
  llama_index/readers/slack.py
  llama_index/readers/web.py
  llama_index/readers/wikipedia.py
Labels: lgtm, size:M

#9919 add streaming support to QueryPipeline
  docs/examples/pipeline/query_pipeline.ipynb
  llama_index/core/query_pipeline/query_component.py
  llama_index/llms/llm.py
Labels: lgtm, size:L

#9921 How to tell if streaming is not implemented
  docs/module_guides/deploying/query_engine/streaming.md
Labels: size:XS

#9923 Add doc_id for more readers
  llama_index/readers/google_readers/gdocs.py
  llama_index/readers/notion.py
  llama_index/readers/web.py
  llama_index/readers/youtube_transcript.py
Labels: lgtm, size:S

#9928 BugFix: Instantiate ChatMemoryBuffer with chat_store_key using from_defaults.
  llama_index/memory/chat_memory_buffer.py
Labels: size:XS

#9936 Fix typo in chat_stores doc
  docs/module_guides/storing/chat_stores.md
Labels: lgtm, size:XS

#9925 Fix: Allow `model_name` for `OpenAIEmbedding`
  llama_index/embeddings/openai.py
Labels: lgtm, size:XS

#9842 Support for Nvidia TensorRT-LLM Inference
  docs/examples/llm/nvidia_tensorrt.ipynb
  docs/module_guides/models/llms/modules.md
  llama_index/llms/__init__.py
  llama_index/llms/nvidia_tensorrt.py
  llama_index/llms/nvidia_tensorrt_utils.py
  poetry.lock
  pyproject.toml
Labels: lgtm, size:XL

#9937 [version] bump to v0.9.28
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#9939 Logan/tool choice patch, version bump to v0.9.28.post1
  llama_index/VERSION
  llama_index/agent/runner/base.py
  pyproject.toml
Labels: size:S

#9940 Add ProgressBar for CLI downloads of llama-datasets
  llama_index/command_line/command_line.py
  llama_index/llama_dataset/download.py
Labels: lgtm, size:XS

#9613 Fix #9612: Set node content for astra db
  llama_index/vector_stores/astra.py
Labels: lgtm, size:S

#9942 Especify timeout for ollama example
  docs/examples/llm/ollama.ipynb
Labels: lgtm, size:XS

#9946 remove tensorrt as dep to avoid failing download (version bump)
  llama_index/VERSION
  poetry.lock
  pyproject.toml
Labels: lgtm, size:XS

#9920 Parallelize IngestionPipeline.run
  docs/examples/ingestion/parallel_execution_ingestion_pipeline.ipynb
  docs/module_guides/loading/ingestion_pipeline/root.md
  llama_index/ingestion/pipeline.py
  tests/ingestion/test_pipeline.py
Labels: lgtm, size:XXL

#9827 :sparkles: DocumentStore / KVStore | Batch Writes & Async Support
  llama_index/storage/docstore/dynamodb_docstore.py
  llama_index/storage/docstore/firestore_docstore.py
  llama_index/storage/docstore/keyval_docstore.py
  llama_index/storage/docstore/mongo_docstore.py
  llama_index/storage/docstore/redis_docstore.py
  llama_index/storage/docstore/simple_docstore.py
  llama_index/storage/docstore/types.py
  llama_index/storage/kvstore/dynamodb_kvstore.py
  llama_index/storage/kvstore/firestore_kvstore.py
  llama_index/storage/kvstore/mongodb_kvstore.py
  llama_index/storage/kvstore/redis_kvstore.py
  llama_index/storage/kvstore/s3_kvstore.py
  llama_index/storage/kvstore/simple_kvstore.py
  llama_index/storage/kvstore/types.py
  tests/storage/docstore/test_firestore_docstore.py
  tests/storage/kvstore/test_firestore_kvstore.py
  tests/storage/kvstore/test_redis_kvstore.py
Labels: lgtm, size:XL

#9953 skip empty nodes
  llama_index/indices/vector_store/base.py
  llama_index/node_parser/text/token.py
Labels: size:S

#9962 Logan/together ai
  docs/examples/embeddings/together.ipynb
  docs/examples/llm/together.ipynb
  docs/module_guides/models/embeddings.md
  docs/module_guides/models/llms/modules.md
  llama_index/embeddings/__init__.py
  llama_index/embeddings/together.py
  llama_index/llms/__init__.py
  llama_index/llms/generic_utils.py
  llama_index/llms/openai_like.py
  llama_index/llms/together.py
Labels: size:XL

#9952 add query components: function, argpack, kwargpack
  llama_index/core/query_pipeline/components.py
  llama_index/core/query_pipeline/query_component.py
  llama_index/query_pipeline/__init__.py
  tests/query_pipeline/components.py
  tests/query_pipeline/query.py
Labels: size:L

#9955 Fix typo in docs
  docs/module_guides/models/llms/modules.md
Labels: lgtm, size:XS

#9964 update langchain imports
  llama_index/bridge/langchain.py
Labels: size:S

#9956 nit: fix set callback handler in base synthesizer
  llama_index/response_synthesizers/base.py
Labels: size:XS

#9963 Fix link to Paul Graham's essay on Starter Tutorial
  docs/getting_started/starter_example.md
Labels: size:XS

#9966 [version] bump to v0.9.29
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#9976 Update together.ipynb
  docs/examples/llm/together.ipynb
Labels: lgtm, size:XS

#9974 do not force delete an index in milvus
  llama_index/vector_stores/milvus.py
Labels: size:XS

#9975 Update together.ipynb
  docs/examples/embeddings/together.ipynb
Labels: lgtm, size:XS

#9965 Parallel Loading with SimpleDirectoryReader
  docs/examples/data_connectors/simple_directory_reader_parallel.ipynb
  docs/module_guides/loading/simpledirectoryreader.md
  llama_index/readers/file/base.py
  tests/readers/test_file.py
Labels: lgtm, size:L

#9977 :bug: fixing init
  llama_index/embeddings/text_embeddings_inference.py
Labels: lgtm, size:XS

#9967 add auto-async execution to query pipelines
  docs/examples/pipeline/query_pipeline_async.ipynb
  llama_index/core/query_pipeline/components.py
  llama_index/query_pipeline/query.py
  tests/query_pipeline/query.py
Labels: lgtm, size:L

#9982 :bug: fixing batch size
  llama_index/storage/kvstore/firestore_kvstore.py
Labels: lgtm, size:XS

#9980 - fix inconsistent name "text_parser" in section "Use a Text Splitter…
  docs/examples/low_level/ingestion.ipynb
Labels: lgtm, size:XS

#9987 Fix: `language` used before assignment in `CodeSplitter`
  llama_index/node_parser/text/code.py
Labels: lgtm, size:XS

#9470 Add Anyscale Embedding model support
  docs/examples/embeddings/Anyscale.ipynb
  docs/module_guides/models/embeddings.md
  llama_index/embeddings/__init__.py
  llama_index/embeddings/anyscale.py
  llama_index/llms/anyscale_utils.py
Labels: size:L

#9988 Implements a Node Parser using embeddings for Semantic Splitting
  docs/examples/node_parsers/semantic_chunking.ipynb
  docs/module_guides/loading/node_parsers/modules.md
  llama_index/node_parser/__init__.py
  llama_index/node_parser/text/__init__.py
  llama_index/node_parser/text/semantic_splitter.py
  tests/node_parser/test_semantic_splitter.py
  tests/playground/test_base.py
Labels: lgtm, size:XL

#9944 Bugfix: sphinx generation errors
  docs/community/integrations/vector_stores.md
  docs/module_guides/loading/documents_and_nodes/root.md
  docs/module_guides/querying/pipeline/root.md
  docs/module_guides/storing/vector_stores.md
  llama_index/node_parser/relational/hierarchical.py
  llama_index/readers/qdrant.py
  llama_index/vector_stores/cassandra.py
Labels: lgtm, size:S

#9993 Fix corner case for qdrant hybrid search
  llama_index/vector_stores/qdrant.py
  llama_index/vector_stores/qdrant_utils.py
  tests/vector_stores/test_qdrant.py
Labels: lgtm, size:M

#9912 Fix: Token counting bug
  llama_index/callbacks/token_counting.py
Labels: lgtm, size:XS

#10001 nit: fix pandas get prompt
  llama_index/query_engine/pandas_query_engine.py
  tests/query_engine/test_pandas.py
Labels: size:S

#10002 [version] bump version to 0.9.30
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: lgtm, size:S

#10010 docs: added notebook with openllmetry example
  docs/examples/callbacks/OpenLLMetry.ipynb
  docs/module_guides/observability/observability.md
Labels: lgtm, size:XL

#9983 :sparkles: adding async support to the docstore
  docs/module_guides/loading/node_parsers/modules.md
  llama_index/storage/docstore/keyval_docstore.py
  llama_index/storage/docstore/types.py
  llama_index/storage/kvstore/dynamodb_kvstore.py
  llama_index/storage/kvstore/firestore_kvstore.py
  llama_index/storage/kvstore/mongodb_kvstore.py
  llama_index/storage/kvstore/redis_kvstore.py
  llama_index/storage/kvstore/s3_kvstore.py
  llama_index/storage/kvstore/simple_kvstore.py
  llama_index/storage/kvstore/types.py
  tests/agent/openai/test_openai_agent.py
  tests/storage/docstore/test_firestore_docstore.py
Labels: lgtm, size:XL

#10016 Update PandasQueryEngine to work better with more LLMs.
  llama_index/output_parsers/utils.py
  llama_index/prompts/default_prompts.py
  llama_index/query_engine/pandas_query_engine.py
Labels: lgtm, size:M

#10014 Implement mongodb kvstore put all method
  llama_index/storage/kvstore/mongodb_kvstore.py
Labels: lgtm, size:S

#10017 Add Neutrino Integration with Example
  docs/examples/llm/neutrino.ipynb
  docs/module_guides/models/llms/modules.md
  llama_index/llms/__init__.py
  llama_index/llms/neutrino.py
Labels: lgtm, size:L

#10015 Truncate SQL results based on max_string_length
  llama_index/utilities/sql_wrapper.py
  tests/utilities/test_sql_wrapper.py
Labels: lgtm, size:M

#10000 Tonic Validate Evaluators
  docs/examples/evaluation/TonicValidateEvaluators.ipynb
  llama_index/evaluation/__init__.py
  llama_index/evaluation/tonic_validate/answer_consistency.py
  llama_index/evaluation/tonic_validate/answer_consistency_binary.py
  llama_index/evaluation/tonic_validate/answer_similarity.py
  llama_index/evaluation/tonic_validate/augmentation_accuracy.py
  llama_index/evaluation/tonic_validate/augmentation_precision.py
  llama_index/evaluation/tonic_validate/retrieval_precision.py
  llama_index/evaluation/tonic_validate/tonic_validate_evaluator.py
Labels: lgtm, size:XXL

#9991 upgrade __init__ in query pipeline
  llama_index/core/query_pipeline/query_component.py
  llama_index/query_pipeline/__init__.py
  llama_index/query_pipeline/query.py
  tests/query_pipeline/test_query.py
Labels: size:L

#10023 fix QA links
  docs/use_cases/q_and_a.md
Labels: size:XS

#10027 Remove outdated docs
  docs/community/integrations/vector_stores.md
  docs/examples/composable_indices/city_analysis/PineconeDemo-CityAnalysis.ipynb
Labels: lgtm, size:XXL

#10026 Fixe ImageNode.resolve_img() for base64 image strings
  llama_index/schema.py
Labels: size:XS

#10025 [WIP] improve pandas query engine
  docs/examples/query_engine/pandas_query_engine.ipynb
  llama_index/core/query_pipeline/query_component.py
  llama_index/indices/struct_store/pandas.py
  llama_index/prompts/base.py
  llama_index/query_engine/__init__.py
  llama_index/query_engine/pandas/__init__.py
  llama_index/query_engine/pandas/output_parser.py
  llama_index/query_engine/pandas/pandas_query_engine.py
  tests/query_engine/test_pandas.py
Labels: size:XL

#10029 add pandas query engine notebook with query pipeline syntax
  docs/examples/pipeline/query_pipeline_pandas.ipynb
  docs/examples/query_engine/pandas_query_engine.ipynb
  docs/module_guides/querying/pipeline/modules.md
Labels: size:L

#10033 fix: use Answer: instead of Response: in ReAct agent
  llama_index/agent/react/types.py
Labels: lgtm, size:XS

#10024 add support for newer langchain streaming
  llama_index/llms/langchain.py
Labels: lgtm, size:M

#10035 fix: fixes typo in default token limit ratio
  llama_index/memory/chat_memory_buffer.py
Labels: lgtm, size:XS

#10020 Fix Cohere system prompt role. (#9881)
  llama_index/chat_engine/condense_plus_context.py
  llama_index/chat_engine/context.py
  llama_index/chat_engine/simple.py
  llama_index/core/llms/types.py
  llama_index/llms/cohere.py
Labels: lgtm, size:S

#8866 Optimized function schema message for `ToolMetadata`
  llama_index/tools/types.py
  tests/tools/test_base.py
Labels: lgtm

#10037 KnowledgeGraphIndex: Make parsing of triplet response more relaxed to support more models
  llama_index/indices/knowledge_graph/base.py
  tests/indices/knowledge_graph/conftest.py
  tests/indices/knowledge_graph/test_base.py
Labels: lgtm, size:M

#10030 add text-to-sql query pipeline
  docs/examples/pipeline/query_pipeline_sql.ipynb
  docs/module_guides/querying/pipeline/modules.md
  llama_index/core/query_pipeline/query_component.py
  llama_index/objects/base.py
Labels: lgtm, size:XL

#10041 qdrant sparse only search
  llama_index/vector_stores/qdrant.py
Labels: lgtm, size:M

#10040 Minor refactor of LangChain utilities/bridge to support LC ChatMessage
  llama_index/bridge/langchain.py
  llama_index/llms/langchain_utils.py
  tests/llms/test_langchain.py
Labels: lgtm, size:L

#10045 add "to-scratch" tutorials for text-to-sql and text-to-pandas
  docs/optimizing/building_rag_from_scratch.md
Labels: size:S

#9979 Add selectors/routing to query pipeline
  docs/examples/pipeline/query_pipeline_routing.ipynb
  llama_index/core/query_pipeline/query_component.py
  llama_index/query_pipeline/__init__.py
  llama_index/query_pipeline/components/__init__.py
  llama_index/query_pipeline/components/router.py
  llama_index/selectors/types.py
  tests/query_pipeline/test_components.py
Labels: size:XL

#10039 community:Updating Konko Integration
  docs/examples/llm/Konko.ipynb
  docs/examples/llm/konko.ipynb
  llama_index/llms/konko.py
  llama_index/llms/konko_utils.py
  tests/llms/test_konko.py
Labels: lgtm, size:XXL

#10043 Changes mirroring langchain to allow for serverless open search
  llama_index/vector_stores/opensearch.py
Labels: lgtm, size:S

#10053 remove tokenizer call in _merge of SentenceSplitter
  llama_index/node_parser/text/sentence.py
Labels: size:S

#10028 Added example of extracting data from email in JSON format
  docs/examples/data/email/ark-trading-jan-12-2024.eml
  docs/examples/data/email/ark-trading-jan-12-2024.msg
  docs/examples/data/images/ark_email_sample.PNG
  docs/examples/usecases/email_data_extraction.ipynb
  docs/use_cases/extraction.md
Labels: lgtm, size:XXL

#10055 [version] bump to v0.9.31
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#10058 ReActive Agents w/ Context + updated stale link
  CONTRIBUTING.md
  docs/examples/agent/react_agent_with_initial_context.ipynb
  docs/module_guides/deploying/agents/modules.md
  llama_index/agent/react/base.py
  llama_index/agent/react/formatter.py
  llama_index/agent/react/prompts.py
Labels: lgtm, size:L

#10064 slight cleanup
  README.md
Labels: lgtm, size:XS

#10062 Fix a typo (avoiding the use of hardcoded constants) in recursive_retriever_nodes.ipynb
  docs/examples/retrievers/recursive_retriever_nodes.ipynb
Labels: lgtm, size:XS

#10057 jaguar vector store add text_tag to add_kwargs in add()
  llama_index/vector_stores/jaguar.py
Labels: lgtm, size:XS

#10019 Recursive retriever all the things
  docs/examples/multi_modal/llava_demo.ipynb
  docs/examples/multi_modal/llava_multi_modal_tesla_10q.ipynb
  docs/examples/query_engine/multi_doc_auto_retrieval/multi_doc_auto_retrieval.ipynb
  docs/examples/query_engine/recursive_retriever_agents.ipynb
  docs/examples/retrievers/composable_retrievers.ipynb
  docs/module_guides/indexing/vector_store_index.md
  docs/module_guides/querying/retriever/retrievers.md
  docs/optimizing/advanced_retrieval/advanced_retrieval.md
  llama_index/core/base_retriever.py
  llama_index/indices/base.py
  llama_index/indices/document_summary/base.py
  llama_index/indices/document_summary/retrievers.py
  llama_index/indices/keyword_table/base.py
  llama_index/indices/keyword_table/retrievers.py
  llama_index/indices/knowledge_graph/base.py
  llama_index/indices/knowledge_graph/retrievers.py
  llama_index/indices/list/base.py
  llama_index/indices/list/retrievers.py
  llama_index/indices/managed/colbert_index/base.py
  llama_index/indices/managed/colbert_index/retriever.py
  llama_index/indices/tree/all_leaf_retriever.py
  llama_index/indices/tree/base.py
  llama_index/indices/tree/select_leaf_retriever.py
  llama_index/indices/tree/tree_root_retriever.py
  llama_index/indices/vector_store/base.py
  llama_index/indices/vector_store/retrievers/auto_retriever/auto_retriever.py
  llama_index/indices/vector_store/retrievers/retriever.py
  llama_index/llms/__init__.py
  llama_index/node_parser/relational/base_element.py
  llama_index/retrievers/auto_merging_retriever.py
  llama_index/retrievers/bm25_retriever.py
  llama_index/retrievers/fusion_retriever.py
  llama_index/retrievers/router_retriever.py
  llama_index/retrievers/transform_retriever.py
  llama_index/schema.py
  llama_index/storage/docstore/__init__.py
  llama_index/vector_stores/weaviate.py
  tests/retrievers/__init__.py
  tests/retrievers/test_composable_retriever.py
Labels: size:XXL

#10022 Pinecone examples updates
  docs/examples/vector_stores/PineconeIndexDemo-0.6.0.ipynb
  docs/examples/vector_stores/PineconeIndexDemo-Hybrid.ipynb
  docs/examples/vector_stores/PineconeIndexDemo.ipynb
Labels: lgtm, size:XL

#9995 Ensure backwards compatibility with new Pinecone client version bifucation
  llama_index/vector_stores/pinecone.py
  llama_index/vector_stores/pinecone_utils.py
  tests/indices/vector_store/utils.py
  tests/vector_stores/test_pinecone.py
Labels: size:L

#10075 Update pinecone example notebooks
  docs/_static/sitemap.xml
  docs/examples/vector_stores/PineconeIndexDemo-0.6.0.ipynb
  docs/examples/vector_stores/PineconeIndexDemo-Hybrid.ipynb
  docs/examples/vector_stores/PineconeIndexDemo.ipynb
  docs/examples/vector_stores/pinecone_auto_retriever.ipynb
  docs/examples/vector_stores/pinecone_metadata_filter.ipynb
Labels: lgtm, size:XL

#10077 some nits to improve query pipeline docs
  docs/module_guides/querying/pipeline/usage_pattern.md
  docs/understanding/querying/querying.md
Labels: size:M

#10080 nit: clear cell query pipeline
  docs/examples/pipeline/query_pipeline_sql.ipynb
Labels: lgtm, size:M

#10065 extend auto-retrieval notebook
  docs/examples/vector_stores/pinecone_auto_retriever.ipynb
Labels: size:L

#10071 Setting event on exception raise to unlock waiting threads
  llama_index/chat_engine/types.py
Labels: lgtm, size:XS

#10084 Fix Together AI example docs title typo
  docs/examples/llm/together.ipynb
Labels: lgtm, size:XS

#9926 BugFix: When using markdown element parser on a table containing comma
  llama_index/node_parser/relational/markdown_element.py
  tests/node_parser/test_markdown_element.py
Labels: size:S

#10054 Init RankGPT
  docs/examples/node_postprocessor/rankGPT.ipynb
  docs/module_guides/querying/node_postprocessors/node_postprocessors.md
  llama_index/postprocessor/__init__.py
  llama_index/postprocessor/rankGPT_rerank.py
  llama_index/prompts/default_prompts.py
  llama_index/prompts/prompt_type.py
Labels: lgtm, size:XL

#10066 [version] bump version to 0.9.32
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#10096 Fix get_single_table_info schema bug
  llama_index/utilities/sql_wrapper.py
Labels: lgtm, size:XS

#10097 Fix fine tuning embedding example
  docs/examples/finetuning/embeddings/finetune_embedding.ipynb
Labels: lgtm, size:L

#10081 Add async mongodb, fix batch insert
  llama_index/ingestion/pipeline.py
  llama_index/storage/kvstore/mongodb_kvstore.py
  poetry.lock
  pyproject.toml
  tests/storage/kvstore/mock_mongodb.py
Labels: lgtm, size:L

#10083 Fix Qdrant Race Condition
  llama_index/vector_stores/qdrant.py
  tests/vector_stores/test_qdrant.py
Labels: lgtm, size:L
