Repository run-llama/llama_index, pull requests merged in 2024-02, with the labels that each got.

#10384 [Cohere] Add client name to Cohere calls
  llama_index/embeddings/cohereai.py
  llama_index/finetuning/rerankers/cohere_reranker.py
  llama_index/llms/cohere.py
Labels: lgtm, size:XS

#10388 Nomic Embed
  docs/examples/embeddings/nomic.ipynb
  docs/module_guides/models/embeddings.md
  llama_index/embeddings/__init__.py
  llama_index/embeddings/nomic.py
Labels: lgtm, size:L

#10395 Simple web page reader - Document was appended twice, Deleted extra append statement
  llama_index/readers/web.py
Labels: lgtm, size:XS

#10386 dashvector support sparse vector
  docs/community/integrations/vector_stores.md
  docs/examples/data_connectors/DashvectorReaderDemo.ipynb
  docs/examples/vector_stores/DashvectorIndexDemo-Hybrid.ipynb
  docs/examples/vector_stores/DashvectorIndexDemo.ipynb
  docs/module_guides/storing/vector_stores.md
  llama_index/readers/dashvector.py
  llama_index/vector_stores/dashvector.py
Labels: lgtm, size:L

#10390 patch condense question custom llm in RAG CLI
  llama_index/chat_engine/condense_question.py
  llama_index/command_line/rag.py
Labels: lgtm, size:M

#10399 Fixed ImportError - cannot import name 'Vector' from 'azure.search.documents.models'
  llama_index/vector_stores/cogsearch.py
Labels: lgtm, size:XS

#10398 get full node content in KeywordExtractor
  llama_index/extractors/metadata_extractors.py
Labels: lgtm, size:XS

#10382 Init Table QA with MarkDownParser and Benchmarking
  docs/examples/query_engine/pdf_tables/table_qa.ipynb
  llama_index/node_parser/relational/base_element.py
Labels: lgtm, size:XXL

#10400 [Version] Update version to 0.9.41
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: lgtm, size:S

#10385 add DashScope qwen llms and multi modal llms qwen-vl
  docs/examples/llm/dashscope.ipynb
  docs/examples/multi_modal/dashscope_multi_modal.ipynb
  llama_index/llms/__init__.py
  llama_index/llms/dashscope.py
  llama_index/llms/dashscope_utils.py
  llama_index/multi_modal_llms/__init__.py
  llama_index/multi_modal_llms/dashscope.py
  llama_index/multi_modal_llms/dashscope_utils.py
Labels: lgtm, size:XXL

#10412 Update openai_utils.py
  llama_index/llms/openai_utils.py
Labels: lgtm, size:XS

#10407 fix ollama stream_chat, explicitly raise error in `CondenseQuestionQueryEngine`
  llama_index/chat_engine/condense_question.py
  llama_index/chat_engine/types.py
  llama_index/llms/ollama.py
Labels: size:S

#10405 feat: Add create-llama option to RagCLI
  docs/use_cases/q_and_a/rag_cli.md
  llama_index/command_line/rag.py
Labels: lgtm, size:L

#10404 LanceDBVectorStore bug fixes
  llama_index/vector_stores/lancedb.py
Labels: lgtm, size:M

#10415 bump version v0.9.42
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#10418 Aysnc for Base nodes parser
  llama_index/node_parser/relational/base_element.py
  tests/param_tuner/test_base.py
Labels: lgtm, size:M

#10408 Fixing a minor grammatical mistake
  docs/use_cases/q_and_a/rag_cli.md
Labels: lgtm, size:XS

#10419 [Version] Bump to 0.9.42.post1
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#10421 fix: model_name validation error and nomic embed model name
  llama_index/embeddings/nomic.py
Labels: lgtm, size:XS

#10423 [Astra DB] Use the "indexing" API option to unlock storage of long document texts in vector store
  llama_index/vector_stores/astra.py
  tests/vector_stores/test_astra.py
Labels: lgtm, size:L

#10424 doc: Updating konko jupyter notebook documentation
  docs/examples/llm/konko.ipynb
Labels: lgtm, size:M

#10426 bug fix - make sure no embedding is required with OpenAI
  llama_index/indices/managed/vectara/base.py
Labels: lgtm, size:XS

#10422 Sammy/text generation support hf chat
  llama_index/llms/huggingface.py
  tests/llms/test_huggingface.py
Labels: size:M

#10427 small bump
  llama_index/VERSION
  pyproject.toml
Labels: size:XS

#10435 update base class for astradb
  llama_index/vector_stores/astra.py
Labels: size:S

#10434 Add multi-modal ollama
  docs/examples/multi_modal/ollama_multi_modal.ipynb
  llama_index/multi_modal_llms/__init__.py
  llama_index/multi_modal_llms/generic_utils.py
  llama_index/multi_modal_llms/ollama.py
Labels: size:XL

#10436 [version] bump version to 0.9.43
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#10447 add local starter example
  docs/getting_started/installation.md
  docs/getting_started/starter_example.md
  docs/getting_started/starter_example_local.md
Labels: lgtm, size:M

#10438 ollama vision cookbook
  docs/examples/multi_modal/llava_multi_modal_tesla_10q.ipynb
  docs/examples/multi_modal/ollama_cookbook.ipynb
  docs/use_cases/multimodal.md
  llama_index/multi_modal_llms/base.py
  llama_index/program/multi_modal_llm_program.py
Labels: size:L

#10457 Support Gemini "transport" configuration
  llama_index/llms/gemini.py
  llama_index/multi_modal_llms/gemini.py
Labels: lgtm, size:XS

#10451 Add Upstash Vector
  docs/community/integrations/vector_stores.md
  docs/examples/vector_stores/UpstashVectorDemo.ipynb
  docs/module_guides/storing/customization.md
  docs/module_guides/storing/vector_stores.md
  llama_index/vector_stores/__init__.py
  llama_index/vector_stores/registry.py
  llama_index/vector_stores/upstash.py
  tests/vector_stores/test_upstash.py
Labels: lgtm, size:L

#10409 Fixing issue of ambiguous/duplicate knowledge triplet generation because of mismatched case or appended special character (double quotes) in generated entities (subject, predicate, object)
  llama_index/indices/knowledge_graph/base.py
  tests/indices/knowledge_graph/test_base.py
Labels: lgtm, size:S

#10462 refactor: Qdrant points upload implementation
  llama_index/vector_stores/qdrant.py
Labels: lgtm, size:M

#10458 [version] bump version to 0.9.44
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#10466 Support custom prompt formatting for non-chat LLMS
  llama_index/llms/huggingface.py
  tests/llms/test_huggingface.py
Labels: lgtm, size:S

#10465 remove exporter from arize-phoenix global callback handler
  llama_index/callbacks/arize_phoenix_callback.py
Labels: lgtm, size:XS

#10471 Fixing Dashscope qwen llm bug
  llama_index/llms/dashscope.py
Labels: lgtm, size:S

#10477 Add persist and load method for Colbert Index
  docs/examples/managed/ColBERT_demo.ipynb
  llama_index/indices/managed/colbert_index/base.py
Labels: lgtm, size:L

#10443 Fix: calling AWS Bedrock models
  docs/examples/embeddings/bedrock.ipynb
  docs/examples/llm/bedrock.ipynb
  llama_index/embeddings/bedrock.py
  llama_index/llms/bedrock.py
  tests/embeddings/test_bedrock.py
  tests/llms/test_bedrock.py
Labels: lgtm, size:XL

#10416 Update Azure AI Search (fka Azure Cognitive Search) vector store integration to latest client SDK 11.4.0 stable + updating jupyter notebook sample
  docs/community/integrations/vector_stores.md
  docs/examples/vector_stores/AzureAISearchIndexDemo.ipynb
  docs/examples/vector_stores/CognitiveSearchIndexDemo.ipynb
  docs/module_guides/storing/customization.md
  docs/module_guides/storing/vector_stores.md
  llama_index/vector_stores/__init__.py
  llama_index/vector_stores/azureaisearch.py
  poetry.lock
  tests/vector_stores/test_azureaisearch.py
Labels: lgtm, size:XXL

#10485 fix some imports
  docs/api_reference/query/query_engines/pandas_query_engine.rst
  llama_index/vector_stores/__init__.py
Labels: size:XS

#10452 Refactor: add AgentRunner.from_llm method
  docs/module_guides/deploying/agents/usage_pattern.md
  llama_index/agent/runner/base.py
  llama_index/indices/base.py
  tests/agent/runner/test_base.py
Labels: size:M

#10450 fix custom agent
  docs/examples/agent/custom_agent.ipynb
  docs/examples/agent/openai_agent.ipynb
  llama_index/agent/custom/simple.py
  llama_index/agent/runner/base.py
  tests/agent/openai/test_openai_agent.py
  tests/agent/react/test_react_agent.py
Labels: size:L

#10492 [version] bump version to 0.9.45
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#10491 Fix ImportError in MetadataExtractionSEC.ipynb (pypdf missing)
  docs/examples/metadata_extraction/MetadataExtractionSEC.ipynb
Labels: lgtm, size:S

#10504 upgraded deeplake vector database to use BasePydanticVectorStore
  llama_index/vector_stores/deeplake.py
Labels: size:S

#10488 Fix MD parser for inconsistency tables
  llama_index/node_parser/relational/base_element.py
  llama_index/node_parser/relational/markdown_element.py
  tests/node_parser/test_markdown_element.py
Labels: size:M

#10510 fix md element
  llama_index/node_parser/relational/markdown_element.py
Labels: size:XS

#10528 fix lint
  SECURITY.md
Labels: size:XS

#10523 Add Cohere section for llamaindex
  docs/module_guides/models/llms/modules.md
Labels: lgtm, size:XS

#10529 deeplake fixes
  llama_index/vector_stores/deeplake.py
Labels: size:M

#10519 move agent module guide up one-level
  docs/index.rst
  docs/module_guides/deploying/agents/root.md
  docs/module_guides/querying/querying.md
Labels: lgtm, size:XS

#10531 Update SECURITY.md
  SECURITY.md
Labels: lgtm, size:XS

#10530 Add Multimodal Video RAG example
  docs/community/integrations/vector_stores.md
  docs/examples/multi_modal/image_to_image_retrieval_lance.ipynb
  docs/examples/multi_modal/multi_modal_video_RAG.ipynb
Labels: lgtm, size:XS

#10536 Update pooling strategy for embeding models
  llama_index/embeddings/huggingface.py
  llama_index/embeddings/huggingface_optimum.py
  llama_index/embeddings/huggingface_utils.py
Labels: lgtm, size:M

#10520 add conditional links to query pipeline
  llama_index/core/query_pipeline/query_component.py
  llama_index/query_pipeline/query.py
  tests/query_pipeline/test_query.py
Labels: size:L

#10339 Add sleep to fix lag in chat stream
  llama_index/chat_engine/types.py
Labels: size:XS

#10543 Update Ingestion Pipeline to handle empty documents
  llama_index/ingestion/pipeline.py
Labels: lgtm, size:XS

#10541 OllamaMultiModal kwargs
  llama_index/multi_modal_llms/ollama.py
Labels: lgtm, size:S

#10516 Fixing minor spelling error
  benchmarks/struct_indices/spider/README.md
Labels: lgtm, size:XS

#10534 Docs/update slack demo colab
  docs/examples/data_connectors/SlackDemo.ipynb
Labels: size:M

#10544 refactor conditional links + add to cookbook
  docs/examples/pipeline/query_pipeline_routing.ipynb
  llama_index/core/query_pipeline/query_component.py
  llama_index/query_pipeline/query.py
  tests/query_pipeline/test_query.py
Labels: lgtm, size:XL

#10562 fix agent reset
  llama_index/agent/runner/base.py
  tests/agent/runner/test_base.py
Labels: lgtm, size:M

#10564 Fix MD duplicated Node id from multiple docs
  llama_index/node_parser/relational/markdown_element.py
Labels: lgtm, size:S

#10563 agent + query pipeline cleanups
  docs/examples/agent/agent_runner/query_pipeline_agent.ipynb
  llama_index/agent/custom/pipeline_worker.py
  llama_index/agent/custom/simple.py
  llama_index/agent/openai/step.py
  llama_index/agent/react/step.py
  llama_index/agent/react_multimodal/step.py
  llama_index/agent/runner/base.py
  llama_index/agent/types.py
Labels: size:XL

#10569 [version] bump version to 0.9.47
  CHANGELOG.md
  llama_index/VERSION
  pyproject.toml
Labels: size:S

#10581 add back deprecated api [v0.9.48]
  CHANGELOG.md
  llama_index/VERSION
  llama_index/embeddings/bedrock.py
  pyproject.toml
Labels: size:L

#10589 various fixes for v0.10.0
  .github/workflows/publish_release.yml
  .github/workflows/unit_test.yml
  Makefile
  docs/requirements.txt
Labels: size:S

#10553 Update link and fix typo in docs/examples/low_level/
  docs/examples/low_level/ingestion.ipynb
  docs/examples/low_level/oss_ingestion_retrieval.ipynb
Labels: lgtm, size:XS

#10597 Dedup logic for recursive retriever nodes
  llama-index-core/llama_index/core/retrievers/recursive_retriever.py
Labels: size:S

#10608 fix query pipeline agent
  docs/examples/agent/agent_runner/query_pipeline_agent.ipynb
  docs/examples/vector_stores/SimpleIndexDemo.ipynb
  llama-index-core/llama_index/core/query_pipeline/__init__.py
Labels: size:XL

#10609 fix base query pipeline notebook
  docs/examples/pipeline/query_pipeline.ipynb
  llama-index-core/llama_index/core/query_pipeline/__init__.py
Labels: size:L

#10611 Add back azure notebook
  docs/examples/vector_stores/AzureAISearchIndexDemo.ipynb
Labels: size:XL

#10605 fix as_chat_engine specifying the LLM
  llama-index-core/llama_index/core/chat_engine/condense_plus_context.py
  llama-index-core/llama_index/core/indices/base.py
Labels: size:M

#10601 Delete txtai.py from chatgpt-plugin-reader package directory
  llama-index-integrations/readers/llama-index-readers-chatgpt-plugin/llama_index/readers/txtai.py
Labels: lgtm, size:M

#10619 fix: add back resolve_embed_model
  llama-index-core/llama_index/core/embeddings/__init__.py
Labels: lgtm, size:XS

#10620 fix retrieval fusion notebooks
  docs/examples/retrievers/reciprocal_rerank_fusion.ipynb
  docs/examples/retrievers/simple_fusion.ipynb
Labels: lgtm, size:L

#10622 fix bm25 retriever notebook
  docs/examples/retrievers/bm25_retriever.ipynb
Labels: size:L

#10603 fix anthropic system prompt
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
Labels: lgtm, size:XS

#10625 TelegramReader fixes not transferred from llama-hub
  llama-index-integrations/readers/llama-index-readers-telegram/README.md
  llama-index-integrations/readers/llama-index-readers-telegram/llama_index/readers/telegram/base.py
  llama-index-integrations/readers/llama-index-readers-telegram/pyproject.toml
Labels: size:S

#10655 fix simple directory reader
  llama-index-core/llama_index/core/readers/file/base.py
  llama-index-integrations/readers/llama-index-readers-file/poetry.lock
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: size:S

#10656 Fix elasticsearch
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/pyproject.toml
Labels: size:XS

#10648 feat: add lazy LLM initialization in RankGPTRerank
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankgpt-rerank/llama_index/postprocessor/rankgpt_rerank/base.py
Labels: lgtm, size:S

#10627 Fixed some gramatical mistakes in several doc files
  docs/getting_started/discover_llamaindex.md
  docs/getting_started/installation.md
  docs/getting_started/reading.md
  docs/getting_started/starter_example.md
  docs/getting_started/starter_example_local.md
  docs/getting_started/v0_10_0_migration.md
Labels: lgtm, size:S

#10657 fixes #10654
  llama-index-core/llama_index/core/program/utils.py
Labels: lgtm, size:XS

#10660 Add OpensearchVectorClient to __init__
  docs/examples/vector_stores/OpensearchDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/CHANGELOG.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
Labels: lgtm, size:M

#10662 v0.10.3 version bump
  CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-core/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankgpt-rerank/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-telegram/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#10663 Make pants testing a bit more strict
  Makefile
Labels: size:XS

#10673 Add FunctionComponent alias
  llama-index-core/llama_index/core/query_pipeline/__init__.py
  llama-index-core/llama_index/core/query_pipeline/components/function.py
Labels: lgtm, size:S

#10675 fix the bug on vector_search_profile default(this profile did not exist) and add the possibility to choose language_analyzer of searchable fields, now on v0.10.3 format
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
Labels: lgtm, size:S

#10679 Update TensorRT-LLM version to 0.7.0 to resolve installation failures
  docs/examples/llm/nvidia_tensorrt.ipynb
Labels: lgtm, size:XS

#10711 Update Nomic Embeddings with v1.5
  llama-index-integrations/embeddings/llama-index-embeddings-nomic/llama_index/embeddings/nomic/base.py
Labels: lgtm, size:S

#10704 corrected import
  llama-index-core/llama_index/core/prompts/base.py
Labels: lgtm, size:XS

#10710 fix: add VllmServer to __init__.py to fix cannot import name 'VllmSer…
  llama-index-integrations/llms/llama-index-llms-vllm/llama_index/llms/vllm/__init__.py
Labels: lgtm, size:XS

#10701 fix: add back support for python 3.12
  pyproject.toml
Labels: lgtm, size:XS

#10674 Dwight/finance tool
  CONTRIBUTING.md
  llama-index-integrations/tools/llama-index-tools-yahoo-finance/.gitignore
  llama-index-integrations/tools/llama-index-tools-yahoo-finance/BUILD
  llama-index-integrations/tools/llama-index-tools-yahoo-finance/Makefile
  llama-index-integrations/tools/llama-index-tools-yahoo-finance/README.md
  llama-index-integrations/tools/llama-index-tools-yahoo-finance/examples/yahoo_finance.ipynb
  llama-index-integrations/tools/llama-index-tools-yahoo-finance/llama_index/tools/yahoo_finance/BUILD
  llama-index-integrations/tools/llama-index-tools-yahoo-finance/llama_index/tools/yahoo_finance/__init__.py
  llama-index-integrations/tools/llama-index-tools-yahoo-finance/llama_index/tools/yahoo_finance/base.py
  llama-index-integrations/tools/llama-index-tools-yahoo-finance/poetry.lock
  llama-index-integrations/tools/llama-index-tools-yahoo-finance/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-yahoo-finance/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-yahoo-finance/tests/__init__.py
  llama-index-integrations/tools/llama-index-tools-yahoo-finance/tests/test_tools_yahoo_finance.py
Labels: lgtm, size:L

#10600 Remove docker dependency from chromadb tests
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/tests/test_chromadb.py
Labels: size:M

#10698 Updated MongoDB Vector Store to Pydantic Vector Store BaseClass
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/llama_index/vector_stores/mongodb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/test_vector_stores_mongodb.py
Labels: lgtm, size:S

#10715 Add Corrective RAG LlamaPack
  llama-index-packs/llama-index-packs-corrective-rag/.gitignore
  llama-index-packs/llama-index-packs-corrective-rag/BUILD
  llama-index-packs/llama-index-packs-corrective-rag/Makefile
  llama-index-packs/llama-index-packs-corrective-rag/README.md
  llama-index-packs/llama-index-packs-corrective-rag/examples/BUILD
  llama-index-packs/llama-index-packs-corrective-rag/examples/corrective_rag.ipynb
  llama-index-packs/llama-index-packs-corrective-rag/examples/example.py
  llama-index-packs/llama-index-packs-corrective-rag/llama_index/packs/corrective_rag/BUILD
  llama-index-packs/llama-index-packs-corrective-rag/llama_index/packs/corrective_rag/__init__.py
  llama-index-packs/llama-index-packs-corrective-rag/llama_index/packs/corrective_rag/base.py
  llama-index-packs/llama-index-packs-corrective-rag/poetry.lock
  llama-index-packs/llama-index-packs-corrective-rag/pyproject.toml
  llama-index-packs/llama-index-packs-corrective-rag/tests/BUILD
  llama-index-packs/llama-index-packs-corrective-rag/tests/__init__.py
  llama-index-packs/llama-index-packs-corrective-rag/tests/test_packs_corrective_rag.py
Labels: lgtm, size:L

#10722 Updated MM video example
  docs/examples/multi_modal/multi_modal_video_RAG.ipynb
Labels: lgtm, size:L

#10733 Add __del__ at Vllm for deleting model
  llama-index-integrations/llms/llama-index-llms-vllm/llama_index/llms/vllm/base.py
Labels: size:S

#10725 [BUG-FIX] retriever_mode param missing when constructing KGTableRetriever
  llama-index-core/llama_index/core/indices/knowledge_graph/base.py
  llama-index-core/llama_index/core/indices/knowledge_graph/retrievers.py
Labels: lgtm, size:XS

#10735 Improved deeplake.py init documentation
  llama-index-integrations/vector_stores/llama-index-vector-stores-deeplake/llama_index/vector_stores/deeplake/base.py
Labels: size:M

#10629 Added Embeddings Option on custom Triplets
  llama-index-core/llama_index/core/indices/knowledge_graph/base.py
  llama-index-legacy/llama_index/legacy/indices/knowledge_graph/base.py
Labels: lgtm, size:M

#10623 Presidio integration
  docs/examples/node_postprocessor/PII.ipynb
  llama-index-integrations/postprocessor/llama-index-postprocessor-presidio/.gitignore
  llama-index-integrations/postprocessor/llama-index-postprocessor-presidio/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-presidio/Makefile
  llama-index-integrations/postprocessor/llama-index-postprocessor-presidio/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-presidio/llama_index/postprocessor/presidio/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-presidio/llama_index/postprocessor/presidio/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-presidio/llama_index/postprocessor/presidio/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-presidio/poetry.lock
  llama-index-integrations/postprocessor/llama-index-postprocessor-presidio/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-presidio/tests/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-presidio/tests/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-presidio/tests/test_postprocessor_presidio.py
Labels: lgtm, size:L

#10718 bump atlasdb version
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/pyproject.toml
Labels: lgtm, size:XS

#10742 Fix broken core link from integration docs to llamma-core folder
  llama-index-integrations/README.md
Labels: lgtm, size:XS

#10745 Update llama_2_llama_cpp.ipynb
  docs/examples/llm/llama_2_llama_cpp.ipynb
Labels: lgtm, size:XS

#10759 [FIX] Install correct clip dep for llama-index-embeddings-clip
  llama-index-integrations/embeddings/llama-index-embeddings-clip/CHANGELOG.md
  llama-index-integrations/embeddings/llama-index-embeddings-clip/llama_index/embeddings/clip/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-clip/poetry.lock
  llama-index-integrations/embeddings/llama-index-embeddings-clip/pyproject.toml
Labels: lgtm, size:S

#10744 Feat/minio reader noverify
  llama-index-integrations/readers/llama-index-readers-minio/llama_index/README.md
  llama-index-integrations/readers/llama-index-readers-minio/llama_index/readers/minio/minio_client/base.py
Labels: lgtm, size:S

#10762 feat: nomic embed v1.5 hf embeddings
  llama-index-integrations/embeddings/llama-index-embeddings-nomic/llama_index/embeddings/nomic/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nomic/pyproject.toml
Labels: lgtm, size:L

#10766 Fix the perf issue in building nodes from splits.
  llama-index-core/llama_index/core/node_parser/node_utils.py
Labels: lgtm, size:S

#10723 The llamaindex cli package
  llama-index-cli/.gitignore
  llama-index-cli/BUILD
  llama-index-cli/CHANGELOG.MD
  llama-index-cli/Makefile
  llama-index-cli/README.md
  llama-index-cli/llama_index/cli/BUILD
  llama-index-cli/llama_index/cli/__init__.py
  llama-index-cli/llama_index/cli/command_line.py
  llama-index-cli/llama_index/cli/new_package/BUILD
  llama-index-cli/llama_index/cli/new_package/__init__.py
  llama-index-cli/llama_index/cli/new_package/base.py
  llama-index-cli/llama_index/cli/new_package/common/.gitignore
  llama-index-cli/llama_index/cli/new_package/common/BUILD
  llama-index-cli/llama_index/cli/new_package/common/Makefile
  llama-index-cli/llama_index/cli/new_package/templates/BUILD
  llama-index-cli/llama_index/cli/new_package/templates/__init__.py
  llama-index-cli/llama_index/cli/new_package/templates/init.py
  llama-index-cli/llama_index/cli/new_package/templates/pyproject.py
  llama-index-cli/llama_index/cli/new_package/templates/readme.py
  llama-index-cli/llama_index/cli/rag/BUILD
  llama-index-cli/llama_index/cli/rag/__init__.py
  llama-index-cli/llama_index/cli/rag/base.py
  llama-index-cli/llama_index/cli/upgrade/BUILD
  llama-index-cli/llama_index/cli/upgrade/__init__.py
  llama-index-cli/llama_index/cli/upgrade/base.py
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-cli/poetry.lock
  llama-index-cli/pyproject.toml
  llama-index-cli/tests/BUILD
  llama-index-cli/tests/__init__.py
  llama-index-cli/tests/test_cli.py
Labels: lgtm, size:XXL

#10583 ClickHouse as a vector store
  docs/community/integrations/vector_stores.md
  docs/examples/data_connectors/MakeDemo.ipynb
  docs/examples/ingestion/async_ingestion_pipeline.ipynb
  docs/examples/vector_stores/ClickHouseIndexDemo.ipynb
  llama-index-core/llama_index/core/data_structs/struct_type.py
  llama-index-integrations/readers/llama-index-readers-clickhouse/.gitignore
  llama-index-integrations/readers/llama-index-readers-clickhouse/BUILD
  llama-index-integrations/readers/llama-index-readers-clickhouse/Makefile
  llama-index-integrations/readers/llama-index-readers-clickhouse/README.md
  llama-index-integrations/readers/llama-index-readers-clickhouse/llama_index/readers/clickhouse/BUILD
  llama-index-integrations/readers/llama-index-readers-clickhouse/llama_index/readers/clickhouse/__init__.py
  llama-index-integrations/readers/llama-index-readers-clickhouse/llama_index/readers/clickhouse/base.py
  llama-index-integrations/readers/llama-index-readers-clickhouse/poetry.lock
  llama-index-integrations/readers/llama-index-readers-clickhouse/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-clickhouse/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-clickhouse/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-clickhouse/tests/test_readers_clickhouse.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/docker-compose.yml
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/llama_index/vector_stores/clickhouse/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/llama_index/vector_stores/clickhouse/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/llama_index/vector_stores/clickhouse/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/tests/test_clickhouse.py
Labels: lgtm, size:XXL

#10432 Add Uptrain Callback Handler
  .gitignore
  docs/community/integrations/uptrain.md
  docs/examples/callbacks/UpTrainCallback.ipynb
  docs/examples/evaluation/UpTrain.ipynb
  llama-index-integrations/callbacks/llama-index-callbacks-uptrain/BUILD
  llama-index-integrations/callbacks/llama-index-callbacks-uptrain/Makefile
  llama-index-integrations/callbacks/llama-index-callbacks-uptrain/README.md
  llama-index-integrations/callbacks/llama-index-callbacks-uptrain/llama_index/callbacks/uptrain/BUILD
  llama-index-integrations/callbacks/llama-index-callbacks-uptrain/llama_index/callbacks/uptrain/__init__.py
  llama-index-integrations/callbacks/llama-index-callbacks-uptrain/llama_index/callbacks/uptrain/base.py
  llama-index-integrations/callbacks/llama-index-callbacks-uptrain/poetry.lock
  llama-index-integrations/callbacks/llama-index-callbacks-uptrain/pyproject.toml
  llama-index-integrations/callbacks/llama-index-callbacks-uptrain/tests/BUILD
  llama-index-integrations/callbacks/llama-index-callbacks-uptrain/tests/__init__.py
  llama-index-integrations/callbacks/llama-index-callbacks-uptrain/tests/test_uptrain_callback.py
  llama-index-legacy/llama_index/legacy/callbacks/__init__.py
  llama-index-legacy/llama_index/legacy/callbacks/global_handlers.py
Labels: lgtm, size:XL

#10500 Class for Optimum-Intel Embedding Model
  docs/examples/embeddings/optimum_intel.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/llama_index/embeddings/huggingface_optimum_intel/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/llama_index/embeddings/huggingface_optimum_intel/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/llama_index/embeddings/huggingface_optimum_intel/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/poetry.lock
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/tests/test_embeddings_huggingface_optimum.py
Labels: lgtm, size:L

#10770 [version bump] v0.10.5
  llama-index-core/pyproject.toml
  llama-index-finetuning/llama_index/finetuning/embeddings/adapter.py
  llama-index-finetuning/llama_index/finetuning/embeddings/adapter_utils.py
  llama-index-finetuning/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-adapter/llama_index/embeddings/adapter/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-adapter/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nomic/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/__pycache__/__init__.cpython-311.pyc
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/__pycache__/base.cpython-311.pyc
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/__pycache__/retriever.cpython-311.pyc
  llama-index-integrations/llms/llama-index-llms-nvidia-tensorrt/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-vllm/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-minio/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/pyproject.toml
  pyproject.toml
Labels: size:M

#10755 MongoDB RAG example with 0.10
  docs/examples/vector_stores/MongoDBAtlasVectorSearchRAGOpenAI.ipynb
Labels: lgtm, size:XXL

#10792 Add Nomic Embedding cookbook
  docs/examples/embeddings/nomic.ipynb
  docs/module_guides/models/embeddings.md
Labels: lgtm, size:L

#10799 Clickhouse package meta fix
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/pyproject.toml
Labels: lgtm, size:XS

#10800 Docs nits
  docs/examples/metadata_extraction/MetadataExtraction_LLMSurvey.ipynb
  docs/examples/query_engine/CustomRetrievers.ipynb
  docs/getting_started/customization.rst
Labels: size:L

#10778 Fix to SageMakerEmbedding class
  llama-index-integrations/embeddings/llama-index-embeddings-sagemaker-endpoint/llama_index/embeddings/sagemaker_endpoint/utils.py
Labels: lgtm, size:XS

#10807 bump various versions
  llama-index-integrations/readers/llama-index-readers-notion/llama_index/readers/notion/base.py
  llama-index-integrations/readers/llama-index-readers-notion/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/beautiful_soup_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/trafilatura_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/poetry.lock
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-youtube-transcript/llama_index/readers/youtube_transcript/base.py
  llama-index-integrations/readers/llama-index-readers-youtube-transcript/poetry.lock
  llama-index-integrations/readers/llama-index-readers-youtube-transcript/pyproject.toml
Labels: size:M

#10513 wip improved object retrieval
  llama-index-core/llama_index/core/schema.py
  llama-index-core/llama_index/core/vector_stores/utils.py
  llama-index-integrations/llms/llama-index-llms-litellm/BUILD
  llama-index-integrations/llms/llama-index-llms-litellm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-litellm/tests/BUILD
  llama-index-legacy/llama_index/legacy/core/base_retriever.py
  llama-index-legacy/llama_index/legacy/indices/base.py
Labels: size:M

#10809 remove metadata extractors from platform
  llama-index-core/llama_index/core/ingestion/transformations.py
Labels: lgtm, size:M

#10798 Updated file init.py
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/__init__.py
Labels: size:M

#10802 Fix llama-hub Data Loader "GPTRepo" encoding issue, supporting gemini embedding more configurations.
  llama-index-integrations/readers/llama-index-readers-gpt-repo/llama_index/readers/gpt_repo/base.py
  llama-index-legacy/llama_index/legacy/embeddings/gemini.py
Labels: lgtm, size:S

#10624 fix upgrade script (bm25 nits)
  docs/examples/retrievers/composable_retrievers.ipynb
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-core/llama_index/core/command_line/upgrade.py
Labels: lgtm, size:M

#10709 AzureAIsearchIndexDemo notebook updated to v0.10.3, AzureSearchvectorstore migrate to pydantic base and some others fixes
  docs/examples/vector_stores/AzureAISearchIndexDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/tests/test_vector_stores_cogsearch.py
Labels: lgtm, size:M

#10749 Fix Neo4jVector handling when multiple indexes are present in the db
  llama-index-integrations/vector_stores/llama-index-vector-stores-neo4jvector/llama_index/vector_stores/neo4jvector/base.py
Labels: size:XS

#10535 Added util functions to get nodes of different depth from a hierarchical nodes list
  llama-index-core/llama_index/core/embeddings/loading.py
  llama-index-core/llama_index/core/llms/loading.py
  llama-index-core/llama_index/core/node_parser/__init__.py
  llama-index-core/llama_index/core/node_parser/relational/hierarchical.py
  llama-index-core/tests/node_parser/test_hierarchical.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/beautiful_soup_web/base.py
Labels: lgtm, size:L

#10926 Update custom_agent.ipynb
  docs/examples/agent/custom_agent.ipynb
Labels: lgtm, size:XS

#10931 Update prompts.rst
  docs/api_reference/prompts.rst
Labels: lgtm

#10930 [version bump] v0.10.6
  CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/query_pipeline/components/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nomic/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-sagemaker-endpoint/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-sbert-rerank/llama_index/postprocessor/sbert_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-sbert-rerank/pyproject.toml
  llama-index-integrations/program/llama-index-program-openai/poetry.lock
  llama-index-integrations/program/llama-index-program-openai/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/llama_index/retrievers/bm25/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-neo4jvector/pyproject.toml
  pyproject.toml
Labels: size:M

#10932 small recursive retrieval fixes
  llama-index-core/llama_index/core/base/base_retriever.py
  llama-index-core/llama_index/core/schema.py
  llama-index-core/llama_index/core/storage/docstore/utils.py
  pyproject.toml
Labels: lgtm, size:S

#10933 toml mixup
  llama-index-core/pyproject.toml
  pyproject.toml
Labels: size:XS

#10936 Bump client version
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/poetry.lock
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
Labels: lgtm, size:XS

#10949 add back GitHub repo file filter
  llama-index-integrations/readers/llama-index-readers-github/llama_index/readers/github/repository/base.py
  llama-index-integrations/readers/llama-index-readers-github/pyproject.toml
Labels: size:L

#10951 Add Self-Discover LlamaPack
  llama-index-packs/llama-index-packs-self-discover/.gitignore
  llama-index-packs/llama-index-packs-self-discover/BUILD
  llama-index-packs/llama-index-packs-self-discover/Makefile
  llama-index-packs/llama-index-packs-self-discover/README.md
  llama-index-packs/llama-index-packs-self-discover/examples/self_discover.ipynb
  llama-index-packs/llama-index-packs-self-discover/llama_index/packs/self_discover/BUILD
  llama-index-packs/llama-index-packs-self-discover/llama_index/packs/self_discover/__init__.py
  llama-index-packs/llama-index-packs-self-discover/llama_index/packs/self_discover/base.py
  llama-index-packs/llama-index-packs-self-discover/poetry.lock
  llama-index-packs/llama-index-packs-self-discover/pyproject.toml
  llama-index-packs/llama-index-packs-self-discover/tests/BUILD
  llama-index-packs/llama-index-packs-self-discover/tests/__init__.py
  llama-index-packs/llama-index-packs-self-discover/tests/test_packs_self_discover.py
Labels: lgtm, size:XL

#10953 update github repo reader
  llama-index-integrations/readers/llama-index-readers-github/llama_index/readers/github/repository/base.py
  llama-index-integrations/readers/llama-index-readers-github/llama_index/readers/github/repository/github_client.py
  llama-index-integrations/readers/llama-index-readers-github/llama_index/readers/github/repository/utils.py
  llama-index-integrations/readers/llama-index-readers-github/pyproject.toml
Labels: size:L

#10805 Add: duckdb vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/examples/DuckDBDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/llama_index/vector_stores/duckdb/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/llama_index/vector_stores/duckdb/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/llama_index/vector_stores/duckdb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/poetry.lock
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/tests/test_duckdb.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/tests/test_vector_stores_duckdb.py
Labels: size:XL

#10753 Fix python package name for semantic chunking llama-pack
  llama-index-packs/llama-index-packs-node-parser-semantic-chunking/pyproject.toml
Labels: lgtm, size:XS

#10962 feat: using pack from llamaindex
  llama-index-packs/llama-index-packs-agent-search-retriever/examples/example.py
  llama-index-packs/llama-index-packs-arize-phoenix-query-engine/examples/example.py
  llama-index-packs/llama-index-packs-auto-merging-retriever/examples/example.py
  llama-index-packs/llama-index-packs-cogniswitch-agent/examples/example.py
  llama-index-packs/llama-index-packs-corrective-rag/examples/example.py
  llama-index-packs/llama-index-packs-dense-x-retrieval/examples/example.py
  llama-index-packs/llama-index-packs-rag-evaluator/examples/example.py
  llama-index-packs/llama-index-packs-rag-fusion-query-pipeline/examples/example.py
  llama-index-packs/llama-index-packs-voyage-query-engine/examples/example.py
Labels: lgtm, size:M

#10750 Feat/mymagicai
  docs/BUILD
  docs/examples/discover_llamaindex/document_management/BUILD
  docs/examples/finetuning/embeddings/BUILD
  docs/examples/llm/mymagic.ipynb
  docs/examples/output_parsing/BUILD
  llama-index-integrations/llms/llama-index-llms-mymagic/.gitignore
  llama-index-integrations/llms/llama-index-llms-mymagic/BUILD
  llama-index-integrations/llms/llama-index-llms-mymagic/Makefile
  llama-index-integrations/llms/llama-index-llms-mymagic/README.md
  llama-index-integrations/llms/llama-index-llms-mymagic/llama_index/llms/mymagic/BUILD
  llama-index-integrations/llms/llama-index-llms-mymagic/llama_index/llms/mymagic/__init__.py
  llama-index-integrations/llms/llama-index-llms-mymagic/llama_index/llms/mymagic/base.py
  llama-index-integrations/llms/llama-index-llms-mymagic/pyproject.toml
Labels: size:L

#10974 [FIX]Fix a NameError for llama-index-embeddings-clip
  llama-index-integrations/embeddings/llama-index-embeddings-clip/llama_index/embeddings/clip/base.py
Labels: lgtm, size:XS

#10971 Bug fixes
  docs/BUILD
  docs/examples/discover_llamaindex/document_management/BUILD
  docs/examples/finetuning/embeddings/BUILD
  docs/examples/output_parsing/BUILD
  docs/module_guides/models/llms/modules.md
  llama-index-core/llama_index/core/graph_stores/registry.py
  llama-index-core/llama_index/core/node_parser/text/sentence_window.py
  llama-index-core/llama_index/core/postprocessor/rankGPT_rerank.py
  llama-index-core/llama_index/core/query_engine/knowledge_graph_query_engine.py
  llama-index-core/llama_index/core/response_synthesizers/factory.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/poetry.lock
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-openai/llama_index/embeddings/openai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-openai/pyproject.toml
Labels: size:M

#10934 add subdoc summary pack
  llama-index-packs/llama-index-packs-subdoc-summary/BUILD
  llama-index-packs/llama-index-packs-subdoc-summary/Makefile
  llama-index-packs/llama-index-packs-subdoc-summary/README.md
  llama-index-packs/llama-index-packs-subdoc-summary/examples/subdoc-summary.ipynb
  llama-index-packs/llama-index-packs-subdoc-summary/llama_index/packs/subdoc_summary/BUILD
  llama-index-packs/llama-index-packs-subdoc-summary/llama_index/packs/subdoc_summary/__init__.py
  llama-index-packs/llama-index-packs-subdoc-summary/llama_index/packs/subdoc_summary/base.py
  llama-index-packs/llama-index-packs-subdoc-summary/pyproject.toml
  llama-index-packs/llama-index-packs-subdoc-summary/tests/__init__.py
Labels: size:XL

#10981 version bumps [v0.10.7]
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-clip/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-github/llama_index/readers/github/repository/github_client.py
  llama-index-integrations/readers/llama-index-readers-github/llama_index/readers/github/repository/utils.py
  llama-index-integrations/readers/llama-index-readers-github/pyproject.toml
  pyproject.toml
Labels: lgtm, size:M

#10983 changelog
  CHANGELOG.md
Labels: size:S

#10994 fix small client bug for edge case where playground pipeline exists with same name as the managed pipeline
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/retriever.py
Labels: lgtm, size:S
