Repository run-llama/llama_index, pull requests merged in 2024-07, with the labels that each got.

#13587 Add support for all languages in py-treesitter
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/code_hierarchy.py
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-c-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-c_sharp-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-cpp-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-elisp-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-elixir-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-elm-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-go-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-java-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-javascript-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-ocaml-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-php-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-python-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-ql-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-ruby-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-rust-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/pytree-sitter-queries/tree-sitter-typescript-tags.scm
  llama-index-packs/llama-index-packs-code-hierarchy/pyproject.toml
Labels: lgtm, size:XL

#14474 fix introspective agent - let reflection agent workers be used independently
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/reflective/self_reflection.py
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/reflective/tool_interactive_reflection.py
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/step.py
  llama-index-integrations/agent/llama-index-agent-introspective/tests/test_self_reflection.py
  llama-index-integrations/agent/llama-index-agent-introspective/tests/test_tool_interactive_reflection.py
Labels: lgtm, size:S

#14479 fix: handle empty response in Bedrock AnthropicProvider
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
Labels: lgtm, size:XS

#14488 Enhance Notion reader to list databases from workplace and pages for …
  docs/docs/examples/data_connectors/NotionDemo.ipynb
  llama-index-integrations/readers/llama-index-readers-notion/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-notion/llama_index/readers/notion/base.py
  llama-index-integrations/readers/llama-index-readers-notion/pyproject.toml
Labels: lgtm, size:L

#14478 Example of using the updated Yi model
  docs/docs/examples/llm/yi.ipynb
Labels: lgtm, size:L

#14452 Allowing Local Deployment of Firecrawl
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/firecrawl_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:S

#14477 Add Iceberg Reader integration to LLamaIndex
  llama-index-integrations/readers/llama-index-readers-iceberg/.gitignore
  llama-index-integrations/readers/llama-index-readers-iceberg/BUILD
  llama-index-integrations/readers/llama-index-readers-iceberg/Makefile
  llama-index-integrations/readers/llama-index-readers-iceberg/README.md
  llama-index-integrations/readers/llama-index-readers-iceberg/llama_index/readers/iceberg/BUILD
  llama-index-integrations/readers/llama-index-readers-iceberg/llama_index/readers/iceberg/__init__.py
  llama-index-integrations/readers/llama-index-readers-iceberg/llama_index/readers/iceberg/base.py
  llama-index-integrations/readers/llama-index-readers-iceberg/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-iceberg/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-iceberg/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-iceberg/tests/test_readers_iceberg.py
Labels: lgtm, size:L

#14495 fix score in nodes returned by the BM25 retriever
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/llama_index/retrievers/bm25/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/tests/test_retrievers_bm25_retriever.py
Labels: lgtm, size:S

#14513 Fixed load_data method removed reassignment of database_ids
  llama-index-integrations/readers/llama-index-readers-notion/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-notion/llama_index/readers/notion/base.py
  llama-index-integrations/readers/llama-index-readers-notion/pyproject.toml
Labels: lgtm, size:S

#14511 Kdbai rest compatible
  llama-index-integrations/vector_stores/llama-index-vector-stores-kdbai/llama_index/vector_stores/kdbai/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-kdbai/pyproject.toml
Labels: lgtm, size:M

#14501 Pandas excel reader load data fix
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/tabular/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:XS

#14502 [package upstage] Add upstage tokenizer and token counting method
  llama-index-integrations/llms/llama-index-llms-upstage/llama_index/llms/upstage/base.py
  llama-index-integrations/llms/llama-index-llms-upstage/poetry.lock
  llama-index-integrations/llms/llama-index-llms-upstage/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-upstage/tests/test_llms_upstage.py
Labels: lgtm, size:M

#14505 Fix several non-working examples
  docs/docs/examples/evaluation/multi_modal/multi_modal_rag_evaluation.ipynb
  docs/docs/examples/multi_modal/gpt4v_experiments_cot.ipynb
  docs/docs/examples/multi_modal/gpt4v_multi_modal_retrieval.ipynb
  docs/docs/examples/multi_modal/image_to_image_retrieval.ipynb
  docs/docs/examples/multi_modal/llava_demo.ipynb
  docs/docs/examples/multi_modal/mm_agent.ipynb
  docs/docs/examples/multi_modal/multi_modal_pydantic.ipynb
  docs/docs/examples/multi_modal/multi_modal_video_RAG.ipynb
  docs/docs/examples/multi_modal/ollama_cookbook.ipynb
  docs/docs/examples/multi_modal/openai_multi_modal.ipynb
  llama-index-integrations/tools/llama-index-tools-openai/examples/multimodal_openai_image.ipynb
Labels: lgtm, size:M

#14461 Neo4j vector context retriever bug fix
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: lgtm, size:S

#14500 Update fullstack_app_guide.md
  docs/docs/understanding/putting_it_all_together/apps/fullstack_app_guide.md
Labels: lgtm, size:XS

#14429 Enhance SlackReader to fetch Channel IDs from Channel Names/Patterns
  docs/docs/examples/data_connectors/SlackDemo.ipynb
  llama-index-integrations/readers/llama-index-readers-slack/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-slack/llama_index/readers/slack/base.py
  llama-index-integrations/readers/llama-index-readers-slack/pyproject.toml
Labels: lgtm, size:L

#14526 use latest version of arize
  llama-index-integrations/callbacks/llama-index-callbacks-arize-phoenix/llama_index/callbacks/arize_phoenix/base.py
  llama-index-integrations/callbacks/llama-index-callbacks-arize-phoenix/pyproject.toml
Labels: size:S

#14525 deprecate query pipeline agent
  docs/docs/examples/agent/agent_runner/query_pipeline_agent.ipynb
  llama-index-core/llama_index/core/agent/custom/pipeline_worker.py
  llama-index-core/llama_index/core/agent/custom/simple_function.py
Labels: lgtm, size:L

#14527 nit: add arize
  docs/docs/examples/agent/agent_runner/query_pipeline_agent.ipynb
Labels: lgtm, size:M

#14524 Fix bug in llama-cloud integration
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/api_utils.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
Labels: lgtm, size:XS

#14545 fix: typo in graph store
  llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/llama_index/graph_stores/nebula/nebula_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
Labels: lgtm, size:XS

#14532 update openvino dependency
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openvino/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/pyproject.toml
Labels: lgtm, size:S

#14523 Add support for LiteLLM Proxy Server
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/llama_index/embeddings/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/llama_index/embeddings/litellm/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/llama_index/embeddings/litellm/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/llama_index/embeddings/litellm/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/poetry.lock
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/tests/test_embeddings_litellm.py
Labels: lgtm, size:L

#14522 Fix: follow up with kwargs propagation due to change in parent class
  llama-index-integrations/indices/llama-index-indices-managed-colbert/llama_index/indices/managed/colbert/base.py
Labels: lgtm, size:XS

#14537 🐞 fix(core): fix file reader bug
  llama-index-core/llama_index/core/readers/file/base.py
Labels: lgtm, size:XS

#14547 fix: azure self.blob
  llama-index-integrations/readers/llama-index-readers-azstorage-blob/llama_index/readers/azstorage_blob/base.py
  llama-index-integrations/readers/llama-index-readers-azstorage-blob/pyproject.toml
Labels: lgtm, size:S

#14496 feat: add async methods to azure ai search
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
Labels: lgtm, size:L

#14546 Adding device choice from sentence_transformers
  llama-index-finetuning/llama_index/finetuning/embeddings/sentence_transformer.py
  llama-index-finetuning/pyproject.toml
Labels: lgtm, size:XS

#14549 Fix various issues for llama-agents
  llama-index-core/llama_index/core/llms/llm.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:S

#14550 v0.10.52
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/litellm.md
  docs/docs/api_reference/llms/cleanlab.md
  docs/docs/api_reference/readers/iceberg.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-core/tests/agent/custom/test_query_pipeline.py
  llama-index-integrations/readers/llama-index-readers-llama-parse/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:L

#14554 🐞 fix(integrations): add fs arg to PandasExcelReader.load_data
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/tabular/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-file/tests/test_file.py
Labels: lgtm, size:M

#14556 fix handling of react agent worker for llama-agents
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/llms/llm.py
  llama-index-core/pyproject.toml
Labels: lgtm, size:S

#14569 fix: crash LLMMetadata
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/llama_index/llms/text_generation_inference/base.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/pyproject.toml
Labels: lgtm, size:XS

#14565 🐞 fix(core): add the missing arg verbose when ReActAgent calling super().__init__
  llama-index-core/llama_index/core/agent/react/base.py
Labels: lgtm, size:XS

#14575 deprecate knowledgegraphindex, tweak docs
  docs/docs/community/integrations.md
  docs/docs/module_guides/storing/index.md
  docs/docs/understanding/putting_it_all_together/graphs.md
  docs/docs/understanding/putting_it_all_together/index.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/indices/knowledge_graph/base.py
  llama-index-core/llama_index/core/indices/knowledge_graph/retrievers.py
  llama-index-core/llama_index/core/query_engine/knowledge_graph_query_engine.py
Labels: size:M

#14563 Fix Issue #14014: ChatSummaryMemoryBuffer fails to summary chat history with tool callings
  llama-index-core/llama_index/core/memory/chat_summary_memory_buffer.py
  llama-index-core/tests/memory/test_chat_summary_memory_buffer.py
Labels: lgtm, size:M

#14564 refactor: Don't swallow exceptions from Qdrant collection_exists
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
Labels: size:S

#14596 Integration: Fix MessageRole import from the wrong package in AI21 Package
  llama-index-integrations/llms/llama-index-llms-ai21/llama_index/llms/ai21/base.py
  llama-index-integrations/llms/llama-index-llms-ai21/pyproject.toml
Labels: lgtm, size:XS

#14497 feat: scrape sharepoint by site/doc library
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/llama_index/readers/microsoft_sharepoint/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/tests/test_readers_microsoft_sharepoint.py
Labels: lgtm, size:L

#14581 Update BM25Retriever to use newer (and faster) bm25s library
  docs/docs/examples/retrievers/bm25_retriever.ipynb
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/llama_index/retrievers/bm25/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/pyproject.toml
Labels: size:XL

#14594 add claude 3.5 sonnet support to Bedrock InvokeAPI
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
Labels: size:XS

#14592 Remove hf embeddings dep from text-embeddings-inference
  llama-index-integrations/embeddings/llama-index-embeddings-text-embeddings-inference/llama_index/embeddings/text_embeddings_inference/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-text-embeddings-inference/pyproject.toml
Labels: size:M

#14595 Make LongContextReorder.ipynb more descriptive
  docs/docs/examples/node_postprocessor/LongContextReorder.ipynb
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/pyproject.toml
Labels: size:XS

#14585 Fix pip install command for Jina Rerank module
  llama-index-integrations/postprocessor/llama-index-postprocessor-jinaai-rerank/README.md
Labels: lgtm, size:XS

#14578 update yi llm context_window
  llama-index-integrations/llms/llama-index-llms-yi/llama_index/llms/yi/base.py
  llama-index-integrations/llms/llama-index-llms-yi/pyproject.toml
Labels: lgtm, size:XS

#14566 DynamicLLMPathExtractor for Entity Detection With a Schema inferred by LLMs on the fly
  docs/docs/examples/property_graph/Dynamic_KG_Extraction.ipynb
  docs/docs/module_guides/indexing/lpg_index_guide.md
  llama-index-core/llama_index/core/indices/property_graph/__init__.py
  llama-index-core/llama_index/core/indices/property_graph/transformations/__init__.py
  llama-index-core/llama_index/core/indices/property_graph/transformations/dynamic_llm.py
  llama-index-core/llama_index/core/prompts/default_prompts.py
Labels: lgtm, size:XL

#14599 Nit: Cleanup README in IcebergReader
  llama-index-integrations/readers/llama-index-readers-iceberg/README.md
Labels: lgtm, size:XS

#14553 add optimum intel with ipex backend to llama-index-integration
  docs/docs/examples/llm/optimum_intel.ipynb
  llama-index-integrations/llms/llama-index-llms-optimum-intel/.gitignore
  llama-index-integrations/llms/llama-index-llms-optimum-intel/BUILD
  llama-index-integrations/llms/llama-index-llms-optimum-intel/Makefile
  llama-index-integrations/llms/llama-index-llms-optimum-intel/README.md
  llama-index-integrations/llms/llama-index-llms-optimum-intel/llama_index/llms/optimum_intel/BUILD
  llama-index-integrations/llms/llama-index-llms-optimum-intel/llama_index/llms/optimum_intel/__init__.py
  llama-index-integrations/llms/llama-index-llms-optimum-intel/llama_index/llms/optimum_intel/base.py
  llama-index-integrations/llms/llama-index-llms-optimum-intel/pyproject.toml
Labels: lgtm, size:L

#14414 add baidu-qianfan llm
  docs/docs/examples/llm/qianfan.ipynb
  llama-index-integrations/llms/llama-index-llms-qianfan/.gitignore
  llama-index-integrations/llms/llama-index-llms-qianfan/BUILD
  llama-index-integrations/llms/llama-index-llms-qianfan/Makefile
  llama-index-integrations/llms/llama-index-llms-qianfan/README.md
  llama-index-integrations/llms/llama-index-llms-qianfan/llama_index/llms/qianfan/BUILD
  llama-index-integrations/llms/llama-index-llms-qianfan/llama_index/llms/qianfan/__init__.py
  llama-index-integrations/llms/llama-index-llms-qianfan/llama_index/llms/qianfan/base.py
  llama-index-integrations/llms/llama-index-llms-qianfan/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-qianfan/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-qianfan/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-qianfan/tests/test_llms_qianfan.py
  llama-index-utils/llama-index-utils-qianfan/.gitignore
  llama-index-utils/llama-index-utils-qianfan/BUILD
  llama-index-utils/llama-index-utils-qianfan/Makefile
  llama-index-utils/llama-index-utils-qianfan/README.md
  llama-index-utils/llama-index-utils-qianfan/llama_index/utils/qianfan/BUILD
  llama-index-utils/llama-index-utils-qianfan/llama_index/utils/qianfan/__init__.py
  llama-index-utils/llama-index-utils-qianfan/llama_index/utils/qianfan/apis.py
  llama-index-utils/llama-index-utils-qianfan/llama_index/utils/qianfan/authorization.py
  llama-index-utils/llama-index-utils-qianfan/llama_index/utils/qianfan/client.py
  llama-index-utils/llama-index-utils-qianfan/pyproject.toml
  llama-index-utils/llama-index-utils-qianfan/tests/BUILD
  llama-index-utils/llama-index-utils-qianfan/tests/__init__.py
  llama-index-utils/llama-index-utils-qianfan/tests/test_apis.py
  llama-index-utils/llama-index-utils-qianfan/tests/test_authorization.py
  llama-index-utils/llama-index-utils-qianfan/tests/test_client.py
Labels: lgtm, size:XXL

#14577 add support for qdrant bm42
  docs/docs/examples/vector_stores/qdrant_bm42.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
Labels: size:XL

#14600 Adding citations and FCS
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/query.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-vectara/tests/test_indices_managed_vectara.py
Labels: lgtm, size:M

#14608 add cloud document converter
  llama-index-core/llama_index/core/schema.py
Labels: lgtm, size:S

#14612 Make MetadataReplacementDemo.ipynb Clearer
  docs/docs/examples/node_postprocessor/MetadataReplacementDemo.ipynb
Labels: lgtm, size:XS

#14615 Add explanation to OptimizerDemo.ipynb
  docs/docs/examples/node_postprocessor/OptimizerDemo.ipynb
Labels: lgtm, size:XS

#14625 updating terms and definitions tutorial doc
  docs/docs/understanding/putting_it_all_together/q_and_a/terms_definitions_tutorial.md
Labels: lgtm, size:M

#14619 🐞 fix(Core): fix KnowledgeGraphIndex arg 'kg_triple_extract_template' typo error
  llama-index-core/llama_index/core/indices/knowledge_graph/base.py
  llama-index-core/tests/indices/knowledge_graph/test_base.py
Labels: lgtm, size:S

#14632 Conditions logging to promptlayer on successful request.
  llama-index-integrations/callbacks/llama-index-callbacks-promptlayer/llama_index/callbacks/promptlayer/base.py
  llama-index-integrations/callbacks/llama-index-callbacks-promptlayer/pyproject.toml
Labels: lgtm, size:M

#14390 UnstructuredReader enhancements.
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/unstructured/README.md
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/unstructured/base.py
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/unstructured/requirements.txt
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:L

#14606 Fix: Update code due to change in unstructured
  llama-index-core/llama_index/core/node_parser/relational/unstructured_element.py
Labels: lgtm, size:S

#14373 Update to extend support for MonsterAPI new LLM APIs
  docs/docs/examples/llm/monsterapi.ipynb
  llama-index-integrations/llms/llama-index-llms-monsterapi/README.md
  llama-index-integrations/llms/llama-index-llms-monsterapi/llama_index/llms/monsterapi/base.py
  llama-index-integrations/llms/llama-index-llms-monsterapi/pyproject.toml
  llama-index-legacy/tests/BUILD
  llama-index-legacy/tests/embeddings/BUILD
  llama-index-legacy/tests/indices/vector_store/BUILD
  llama-index-legacy/tests/llms/BUILD
  llama-index-legacy/tests/node_parser/BUILD
  llama-index-legacy/tests/query_engine/BUILD
  llama-index-legacy/tests/readers/BUILD
  llama-index-legacy/tests/vector_stores/BUILD
Labels: lgtm, size:L

#14590 Add integration embeddings databricks
  docs/docs/examples/embeddings/databricks.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-databricks/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-databricks/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-databricks/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-databricks/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-databricks/llama_index/embeddings/databricks/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-databricks/llama_index/embeddings/databricks/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-databricks/llama_index/embeddings/databricks/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-databricks/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-databricks/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-databricks/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-databricks/tests/test_embeddings_databricks.py
  llama-index-integrations/embeddings/llama-index-embeddings-databricks/tests/test_integration_databricks.py
Labels: lgtm, size:L

#14603 problem in lancedb base,slove error in logger
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/llama_index/vector_stores/lancedb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/pyproject.toml
Labels: lgtm, size:XS

#14587 Update ReAct Step to solve issue with uncomplete generation
  llama-index-core/llama_index/core/agent/react/step.py
Labels: lgtm, size:M

#14636 Add Explanation to bm25_retriever.ipynb
  docs/docs/examples/retrievers/bm25_retriever.ipynb
Labels: lgtm, size:XS

#14638 v0.10.53
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/databricks.md
  docs/docs/api_reference/llms/OptimumIntelLLM.md
  docs/docs/api_reference/llms/qianfan.md
  docs/docs/api_reference/readers/web.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-monsterapi/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#14642 fix unstructured import in simple file reader
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/unstructured/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: size:S

#14641 Fix #14637 Llamaindex managed Vertex AI index needs to be updated.
  docs/docs/examples/agent/agentic_rag_using_vertex_ai.ipynb
  docs/docs/examples/managed/VertexAIDemo.ipynb
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/llama_index/indices/managed/vertexai/base.py
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/llama_index/indices/managed/vertexai/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/pyproject.toml
Labels: lgtm, size:L

#14648 📃 docs(docs): add getting_started/concepts missing quotation mark
  docs/docs/getting_started/concepts.md
Labels: lgtm, size:XS

#14658 To add Yi model to the list of supported LLMs
  docs/docs/module_guides/models/llms/modules.md
Labels: lgtm, size:XS

#14655 Added support for custom index settings
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py
Labels: lgtm, size:XS

#14663 fix: name - typo in the example
  docs/docs/examples/vector_stores/ChromaIndexDemo.ipynb
Labels: lgtm, size:XS

#14670 bump version llama-index-embeddings-huggingface-optimum-intel
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/llama_index/embeddings/huggingface_optimum_intel/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/pyproject.toml
Labels: lgtm, size:S

#14674 fix: update operator logic for simple vector store filter
  llama-index-core/llama_index/core/vector_stores/simple.py
  llama-index-core/tests/vector_stores/test_simple.py
Labels: lgtm, size:S

#14675 clean up llama-cloud usage in core, move to dev
  llama-index-core/llama_index/core/evaluation/eval_utils.py
  llama-index-core/llama_index/core/ingestion/api_utils.py
  llama-index-core/llama_index/core/ingestion/pipeline.py
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  llama-index-core/tests/evaluation/test_platform_eval.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
Labels: size:M

#14681 [version] bump version to 0.10.54
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/callbacks/agentops.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-fastembed/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/pyproject.toml
  pyproject.toml
Labels: size:M

#14676 Add user configurations for Cleanlab LLM integration
  docs/docs/examples/llm/cleanlab.ipynb
  llama-index-integrations/llms/llama-index-llms-cleanlab/llama_index/llms/cleanlab/base.py
  llama-index-integrations/llms/llama-index-llms-cleanlab/pyproject.toml
Labels: lgtm, size:L

#14687 fix docs
  docs/docs/api_reference/llms/cleanlab.md
  docs/docs/api_reference/llms/optimum_intel.md
  docs/mkdocs.yml
  llama-index-integrations/llms/llama-index-llms-optimum-intel/pyproject.toml
Labels: lgtm, size:XS

#14686 fix: race between concurrent pptx readers over a single temp filename.
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/slides/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:S

#14697 Documentation: update huggingface.ipynb
  docs/docs/examples/embeddings/huggingface.ipynb
Labels: lgtm, size:XS

#14696 Upgrade llama-cloud client to 0.0.9 and support `retrieval_mode` and `files_top_k`
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
Labels: lgtm, size:S

#14692 update observability docs
  docs/docs/api_reference/embeddings/ibm.md
  docs/docs/api_reference/llms/ibm.md
  docs/docs/module_guides/observability/index.md
Labels: lgtm, size:M

#14688 These docs have been supplanted by the full llamaparse docs site
  docs/docs/module_guides/loading/connector/llama_parse.md
Labels: lgtm, size:M

#14690 changes to Exa search tool getting started and example notebook
  llama-index-integrations/tools/llama-index-tools-exa/README.md
  llama-index-integrations/tools/llama-index-tools-exa/examples/exa.ipynb
  llama-index-integrations/tools/llama-index-tools-exa/llama_index/tools/exa/base.py
  llama-index-integrations/tools/llama-index-tools-exa/pyproject.toml
Labels: lgtm, size:L

#14704 Add a sample notebook to show llamaindex agents used for managed vertex ai index
  docs/docs/examples/agent/agentic_rag_with_llamaindex_and_vertexai_managed_index.ipynb
  docs/docs/examples/managed/VertexAIDemo.ipynb
Labels: lgtm, size:XL

#14485 feat(ci): cache `poetry` in CI
  .github/workflows/build_package.yml
  .github/workflows/lint.yml
  .github/workflows/publish_release.yml
  .github/workflows/publish_sub_package.yml
  .github/workflows/unit_test.yml
Labels: lgtm, size:M

#14709 v0.10.55
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:M

#14710 fix fastembed python version
  llama-index-integrations/embeddings/llama-index-embeddings-fastembed/pyproject.toml
Labels: lgtm, size:XS

#14685 Box reader
  llama-index-integrations/readers/llama-index-readers-box/.gitignore
  llama-index-integrations/readers/llama-index-readers-box/BUILD
  llama-index-integrations/readers/llama-index-readers-box/Makefile
  llama-index-integrations/readers/llama-index-readers-box/README.md
  llama-index-integrations/readers/llama-index-readers-box/__init__.py
  llama-index-integrations/readers/llama-index-readers-box/examples/BUILD
  llama-index-integrations/readers/llama-index-readers-box/examples/box_reader.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BUILD
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxAPI/BUILD
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxAPI/__init.py__
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxAPI/box_ai_extract_beta.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxAPI/box_api.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReader/BUILD
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReader/README.md
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReader/__init.py__
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReader/base.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderAIExtraction/BUILD
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderAIExtraction/README.md
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderAIExtraction/__init__.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderAIExtraction/base.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderAIPrompt/BUILD
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderAIPrompt/README.md
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderAIPrompt/__init__.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderAIPrompt/base.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderTextExtraction/BUILD
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderTextExtraction/README.md
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderTextExtraction/__init__.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxReaderTextExtraction/base.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/__init__.py
  llama-index-integrations/readers/llama-index-readers-box/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-box/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-box/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-box/tests/conftest.py
  llama-index-integrations/readers/llama-index-readers-box/tests/test_readers_box_ai_extract.py
  llama-index-integrations/readers/llama-index-readers-box/tests/test_readers_box_ai_prompt.py
  llama-index-integrations/readers/llama-index-readers-box/tests/test_readers_box_jwt.py
  llama-index-integrations/readers/llama-index-readers-box/tests/test_readers_box_reader.py
  llama-index-integrations/readers/llama-index-readers-box/tests/test_readers_box_text_extraction.py
Labels: lgtm, size:XXL

#14737 remove flakey and unhelpful tests
  llama-index-integrations/readers/llama-index-readers-web/tests/readers/web/spider_web/BUILD
  llama-index-integrations/readers/llama-index-readers-web/tests/readers/web/spider_web/__init__.py
  llama-index-integrations/readers/llama-index-readers-web/tests/readers/web/spider_web/test_base.py
Labels: size:XS

#14714 Update simple_summarize.py
  llama-index-core/llama_index/core/response_synthesizers/simple_summarize.py
Labels: lgtm, size:XS

#14693 feat: improve azureai search deleting
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
Labels: lgtm, size:L

#14740 Adds Quantization option to QdrantVectorStore
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
Labels: lgtm, size:S

#14752 Add GraphRAG Implementation
  docs/docs/examples/cookbooks/GraphRAG_v1.ipynb
Labels: lgtm, size:XXL

#14749 update docs for OpenAI/AzureOpenAI additional_kwargs
  docs/docs/examples/llm/azure_openai.ipynb
  docs/docs/examples/llm/openai.ipynb
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
Labels: lgtm, size:M

#14708 follow odata.nextLink
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/llama_index/readers/microsoft_sharepoint/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/pyproject.toml
Labels: lgtm, size:M

#14762 📃 docs(Learn): Loading Data
  docs/docs/examples/ingestion/document_management_pipeline.ipynb
  docs/docs/module_guides/loading/node_parsers/modules.md
  docs/docs/understanding/loading/loading.md
  docs/docs/understanding/using_llms/using_llms.md
Labels: lgtm, size:XS

#14770 [FIX] Issues with `llama-index-readers-box` pyproject.toml
  llama-index-integrations/readers/llama-index-readers-box/pyproject.toml
Labels: lgtm, size:XS

#14764 📃 docs(examples): fix KnowledgeGraphDemo link error
  docs/docs/examples/index_structs/knowledge_graph/KnowledgeGraphDemo.ipynb
Labels: lgtm, size:XS

#14761 Chore: restrict the scipy verstion to 1.12.0 to fix the error cannot import name triu from scipy.linalg
  docs/docs/examples/cookbooks/GraphRAG_v1.ipynb
Labels: lgtm, size:XS

#14735 Remove double curly replacing from output parser utils
  llama-index-core/llama_index/core/output_parsers/utils.py
  llama-index-core/tests/output_parsers/test_selection.py
Labels: lgtm, size:S

#14745 Fix OpenWeatherMapToolSpec.forecast_tommorrow_at_location
  llama-index-integrations/tools/llama-index-tools-weather/CHANGELOG.md
  llama-index-integrations/tools/llama-index-tools-weather/llama_index/tools/weather/base.py
  llama-index-integrations/tools/llama-index-tools-weather/pyproject.toml
Labels: lgtm, size:S

#14773 docs: Fix wrong Qdrant_metadata_filter doc
  docs/docs/examples/vector_stores/Qdrant_metadata_filter.ipynb
Labels: lgtm, size:XS

#14712 feat: azureaisearch support collection string
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
Labels: lgtm, size:M

#14787 feat: add azureaisearch supported conditions
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
Labels: lgtm, size:S

#14791 feat: Add NOT IN filter for Qdrant vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
Labels: lgtm, size:S

#14795 feat: add nested filters for azureaisearch
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
Labels: lgtm, size:XS

#14814 Improve output format system prompt in ReAct agent
  llama-index-core/llama_index/core/agent/react/templates/system_header_template.md
Labels: lgtm, size:XS

#14820 Add support for gpt-4o-mini
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/llama_index/multi_modal_llms/openai/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/pyproject.toml
Labels: lgtm, size:XS

#14812 Fix bug when sanitize is used in neo4j property graph
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: lgtm, size:XS

#14828 Fix AgentRunner AgentRunStepStartEvent dispatch
  llama-index-core/llama_index/core/agent/runner/base.py
  llama-index-core/tests/agent/runner/test_base.py
Labels: lgtm, size:M

#14799 Fix PineconeRetriever: remove usage of global variables, check embeddings - Init Pinecone properly
  docs/docs/examples/low_level/retrieval.ipynb
Labels: lgtm, size:S

#14833 Fix Azure OpenAI LLM and Embedding async client bug
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/llama_index/embeddings/azure_openai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-azure-openai/llama_index/llms/azure_openai/base.py
  llama-index-integrations/llms/llama-index-llms-azure-openai/pyproject.toml
Labels: lgtm, size:S

#14774 Add a notebook to show llamaindex agent works with graphRAG and Vertex AI
  docs/docs/examples/property_graph/agentic_graph_rag_vertex.ipynb
Labels: lgtm, size:XXL

#14835 Fix OpenAI Embedding async client bug
  llama-index-integrations/embeddings/llama-index-embeddings-openai/llama_index/embeddings/openai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-openai/pyproject.toml
Labels: lgtm, size:S

#14838 Integration notebook for RAGChecker
  docs/docs/examples/evaluation/RAGChecker.ipynb
  docs/docs/module_guides/evaluating/index.md
  docs/docs/module_guides/evaluating/modules.md
Labels: lgtm, size:L

#14844 add support for nvidia/nv-rerankqa-mistral-4b-v3
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/pyproject.toml
Labels: lgtm, size:XS

#14840 Update docstring for gmailtoolspec's search_messages tool
  llama-index-integrations/tools/llama-index-tools-google/llama_index/tools/google/gmail/base.py
  llama-index-integrations/tools/llama-index-tools-google/pyproject.toml
Labels: lgtm, size:S

#14439 Add Context-Only Response Synthesizer
  docs/docs/module_guides/querying/response_synthesizers/index.md
  llama-index-core/llama_index/core/response_synthesizers/context_only.py
  llama-index-core/llama_index/core/response_synthesizers/factory.py
  llama-index-core/llama_index/core/response_synthesizers/type.py
Labels: lgtm, size:M

#14313 Add new integration for YandexGPT Embedding Model
  docs/docs/examples/embeddings/yandexgpt.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-yandexgpt/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-yandexgpt/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-yandexgpt/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-yandexgpt/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-yandexgpt/llama_index/embeddings/yandexgpt/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-yandexgpt/llama_index/embeddings/yandexgpt/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-yandexgpt/llama_index/embeddings/yandexgpt/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-yandexgpt/llama_index/embeddings/yandexgpt/util.py
  llama-index-integrations/embeddings/llama-index-embeddings-yandexgpt/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-yandexgpt/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-yandexgpt/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-yandexgpt/tests/tests_embeddings_yandexgpt.py
Labels: lgtm, size:L

#14326 feat: ✨ Implement async functionality in `BedrockConverse`
  docs/docs/examples/llm/bedrock_converse.ipynb
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: lgtm, size:L

#14672 Azure AI Inference integration
  docs/docs/examples/llm/azure_inference.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/llama_index/embeddings/azure_inference/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/llama_index/embeddings/azure_inference/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/llama_index/embeddings/azure_inference/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/tests/test_embeddings_azure_inference.py
  llama-index-integrations/llms/llama-index-llms-azure-inference/.gitignore
  llama-index-integrations/llms/llama-index-llms-azure-inference/BUILD
  llama-index-integrations/llms/llama-index-llms-azure-inference/Makefile
  llama-index-integrations/llms/llama-index-llms-azure-inference/README.md
  llama-index-integrations/llms/llama-index-llms-azure-inference/llama_index/llms/azure_inference/BUILD
  llama-index-integrations/llms/llama-index-llms-azure-inference/llama_index/llms/azure_inference/__init__.py
  llama-index-integrations/llms/llama-index-llms-azure-inference/llama_index/llms/azure_inference/base.py
  llama-index-integrations/llms/llama-index-llms-azure-inference/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-azure-inference/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-azure-inference/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-azure-inference/tests/test_llms_azure_inference.py
Labels: lgtm, size:XXL

#14839 Fixing the issue where the _apply_node_postprocessors function was ca…
  llama-index-core/llama_index/core/tools/retriever_tool.py
Labels: lgtm, size:XS

#14732 chore: read AZURE_POOL_MANAGEMENT_ENDPOINT from env vars
  docs/docs/examples/tools/azure_code_interpreter.ipynb
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/README.md
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/llama_index/tools/azure_code_interpreter/base.py
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/pyproject.toml
Labels: lgtm, size:S

#14831 Add an optional parameter similarity_score to VectorContextRetrieve…
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/vector.py
Labels: lgtm, size:M

#14850 align deps
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/pyproject.toml
Labels: lgtm, size:XS

#14830 Bugfix: ollama streaming response would not return last object that i…
  llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
  llama-index-integrations/llms/llama-index-llms-ollama/pyproject.toml
Labels: lgtm, size:M

#14849 [version] bump version to 0.10.56
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/azure_inference.md
  docs/docs/api_reference/embeddings/yandexgpt.md
  docs/docs/api_reference/llms/azure_inference.md
  docs/docs/api_reference/readers/box.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#14852 CHANGELOG - unreleased section
  CHANGELOG.md
Labels: size:S

#14851 [version] bump version to 0.1.7 for MongoDB Vector Store
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/pyproject.toml
Labels: lgtm, size:XS

#14800 Implements `delete_nodes()` and `clear()` for Weviate, Opensearch, Milvus, Postgres, and Pinecone Vector Stores
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/tests/test_opensearch_client.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/llama_index/vector_stores/pinecone/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/test_postgres.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/pyproject.toml
Labels: lgtm, size:XL

#14856 MongoDB Atlas Vector Search: Enhanced Metadata Filtering
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/CHANGELOG.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/llama_index/vector_stores/mongodb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/llama_index/vector_stores/mongodb/pipelines.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/pyproject.toml
Labels: lgtm, size:L

#14858 optimize ingestion pipeline deduping
  llama-index-core/llama_index/core/ingestion/pipeline.py
Labels: size:S

#14859 Empty array being send to vector store
  llama-index-core/llama_index/core/ingestion/pipeline.py
Labels: lgtm, size:S

#14759 Add streaming for tool calling / structured extraction
  docs/docs/examples/llm/anthropic.ipynb
  docs/docs/examples/llm/mistralai.ipynb
  docs/docs/examples/llm/openai.ipynb
  docs/docs/examples/structured_outputs/structured_outputs.ipynb
  llama-index-core/llama_index/core/instrumentation/events/llm.py
  llama-index-core/llama_index/core/llms/function_calling.py
  llama-index-core/llama_index/core/llms/llm.py
  llama-index-core/llama_index/core/llms/structured_llm.py
  llama-index-core/llama_index/core/llms/utils.py
  llama-index-core/llama_index/core/program/function_program.py
  llama-index-core/llama_index/core/program/utils.py
  llama-index-core/llama_index/core/types.py
  llama-index-core/tests/agent/function_calling/test_step.py
  llama-index-integrations/callbacks/llama-index-callbacks-agentops/tests/test_instrumentation_agentops.py
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-deepinfra/llama_index/llms/deepinfra/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/base.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/llama_index/llms/text_generation_inference/base.py
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py
  llama-index-integrations/program/llama-index-program-openai/llama_index/program/openai/base.py
Labels: lgtm, size:XXL

#14861 update notion reader
  llama-index-integrations/readers/llama-index-readers-notion/llama_index/readers/notion/base.py
  llama-index-integrations/readers/llama-index-readers-notion/pyproject.toml
Labels: lgtm, size:M

#14860 fix unpicklable attributes
  llama-index-core/llama_index/core/schema.py
Labels: lgtm, size:M

#14863 Removed a dead link in Document Management Docs
  docs/docs/module_guides/indexing/document_management.md
Labels: lgtm, size:XS

#14879 bump langchain version in integration
  llama-index-integrations/llms/llama-index-llms-langchain/pyproject.toml
Labels: size:XS

#14867 📃 docs(unserstanding): typo link error
  docs/docs/getting_started/installation.md
  docs/docs/understanding/putting_it_all_together/index.md
Labels: lgtm, size:XS

#14869 Bugfix: AzureOpenAI may fail with custom azure_ad_token_provider
  llama-index-integrations/llms/llama-index-llms-azure-openai/llama_index/llms/azure_openai/base.py
  llama-index-integrations/llms/llama-index-llms-azure-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-azure-openai/tests/test_azure_openai.py
Labels: lgtm, size:M

#14888 Callbacks to Observability in the examples section
  docs/docs/CHANGELOG.md
  docs/docs/examples/observability/AimCallback.ipynb
  docs/docs/examples/observability/HoneyHiveLlamaIndexTracer.ipynb
  docs/docs/examples/observability/LangfuseCallbackHandler.ipynb
  docs/docs/examples/observability/LlamaDebugHandler.ipynb
  docs/docs/examples/observability/OpenInferenceCallback.ipynb
  docs/docs/examples/observability/OpenLLMetry.ipynb
  docs/docs/examples/observability/PromptLayerHandler.ipynb
  docs/docs/examples/observability/TokenCountingHandler.ipynb
  docs/docs/examples/observability/UpTrainCallback.ipynb
  docs/docs/examples/observability/WandbCallbackHandler.ipynb
  docs/mkdocs.yml
  docs/prepare_for_build.py
Labels: lgtm, size:M

#14747 WIP: update structured outputs syntax
  docs/docs/examples/llm/anthropic.ipynb
  docs/docs/examples/llm/mistralai.ipynb
  docs/docs/examples/llm/openai.ipynb
  docs/docs/examples/structured_outputs/structured_outputs.ipynb
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/llama_index/core/instrumentation/events/llm.py
  llama-index-core/llama_index/core/llms/function_calling.py
  llama-index-core/llama_index/core/llms/llm.py
  llama-index-core/llama_index/core/llms/structured_llm.py
  llama-index-core/llama_index/core/llms/utils.py
  llama-index-core/llama_index/core/program/function_program.py
  llama-index-core/llama_index/core/program/utils.py
  llama-index-core/llama_index/core/response_synthesizers/base.py
  llama-index-core/llama_index/core/types.py
  llama-index-core/tests/agent/function_calling/test_step.py
  llama-index-integrations/callbacks/llama-index-callbacks-agentops/tests/test_instrumentation_agentops.py
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-deepinfra/llama_index/llms/deepinfra/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/llama_index/llms/text_generation_inference/base.py
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py
  llama-index-integrations/program/llama-index-program-openai/llama_index/program/openai/base.py
Labels: size:XXL

#14707 add property extraction for KGs
  docs/docs/examples/property_graph/Dynamic_KG_Extraction.ipynb
  llama-index-core/llama_index/core/graph_stores/types.py
  llama-index-core/llama_index/core/indices/property_graph/transformations/dynamic_llm.py
  llama-index-core/llama_index/core/indices/property_graph/transformations/schema_llm.py
  llama-index-core/llama_index/core/indices/property_graph/transformations/utils.py
  llama-index-core/llama_index/core/prompts/default_prompts.py
Labels: size:XL

#14893 v0.10.57
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-deepinfra/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-huggingface/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-langchain/llama_index/llms/langchain/utils.py
  llama-index-integrations/llms/llama-index-llms-langchain/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-vertex/pyproject.toml
  llama-index-integrations/program/llama-index-program-openai/pyproject.toml
  llama-index-packs/llama-index-packs-resume-screener/pyproject.toml
  llama-index-packs/llama-index-packs-resume-screener/tests/BUILD
  llama-index-packs/llama-index-packs-resume-screener/tests/__init__.py
  llama-index-packs/llama-index-packs-resume-screener/tests/test_packs_resume_screener.py
  poetry.lock
  pyproject.toml
Labels: size:L

#14914 fireworks ai llama3.1
  llama-index-integrations/llms/llama-index-llms-fireworks/llama_index/llms/fireworks/utils.py
  llama-index-integrations/llms/llama-index-llms-fireworks/pyproject.toml
Labels: lgtm, size:XS

#14917 Update-mappings
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-cli/pyproject.toml
  llama-index-core/llama_index/core/command_line/mappings.json
Labels: lgtm, size:L

#14885 Fix TaskStepOutput sources bug
  llama-index-core/llama_index/core/agent/function_calling/step.py
  llama-index-core/llama_index/core/agent/runner/base.py
  llama-index-core/tests/agent/function_calling/test_step.py
  llama-index-core/tests/agent/runner/test_base.py
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/step.py
  llama-index-integrations/agent/llama-index-agent-openai/tests/test_openai_agent.py
Labels: lgtm, size:L

#14919 fix the initialization of Pinecone in the low-level ingestion notebook.
  docs/docs/examples/low_level/ingestion.ipynb
Labels: lgtm, size:S

#14920 Improved deeplake.get_nodes() performance
  llama-index-integrations/vector_stores/llama-index-vector-stores-deeplake/llama_index/vector_stores/deeplake/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-deeplake/pyproject.toml
Labels: lgtm, size:S

#14918 Bugfix: Don't pass empty list of embeddings to elasticsearch store when using sparse strategy
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/pyproject.toml
Labels: lgtm, size:XS
