Repository run-llama/llama_index, pull requests merged in 2024-12, with the labels that each got.

#17104 Allow install llama-index-packs-code-hierachy in python 3.12 env
  llama-index-packs/llama-index-packs-code-hierarchy/pyproject.toml
Labels: lgtm, size:XS

#17111 feat: improve ImageBlock
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/llama_index/core/bridge/pydantic.py
  llama-index-core/tests/base/llms/test_types.py
Labels: lgtm, size:M

#17128 Add support for IS_EMPTY metadata filters to Weaviate Vector Store integration
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/tests/test_vector_stores_weaviate.py
Labels: lgtm, size:S

#17126 fix(metrics): fixed NDCG calculation and added comprehensive test cases
  llama-index-core/llama_index/core/evaluation/retrieval/metrics.py
  llama-index-core/tests/evaluation/test_metrics.py
Labels: lgtm, size:M

#17129 Make Weaviate Vector Store integration work with complex properties
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/tests/test_vector_stores_weaviate.py
Labels: lgtm, size:M

#17139 Adding AWS Nova models to Bedrock Converse
  docs/docs/examples/llm/bedrock_converse.ipynb
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: lgtm, size:S

#17135 add trust_remote_code argument, make default = False for other classes
  llama-index-core/llama_index/core/postprocessor/sbert_rerank.py
  llama-index-integrations/llms/llama-index-llms-vllm/llama_index/llms/vllm/base.py
  llama-index-integrations/llms/llama-index-llms-vllm/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/llama_index/multi_modal_llms/huggingface/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openvino/llama_index/multi_modal_llms/openvino/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openvino/pyproject.toml
Labels: lgtm, size:S

#17143 chore: skip tests if ZEN_API_KEY is not set
  llama-index-packs/llama-index-packs-zenguard/pyproject.toml
  llama-index-packs/llama-index-packs-zenguard/tests/test_packs_zenguard.py
Labels: size:S

#17138 fix: make OpenAIMultiModal work with new ChatMessage
  docs/docs/examples/multi_modal/openai_multi_modal.ipynb
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/llama_index/core/llms/function_calling.py
  llama-index-core/llama_index/core/multi_modal_llms/base.py
  llama-index-core/tests/base/llms/test_types.py
  llama-index-integrations/llms/llama-index-llms-openai-like/tests/test_openai_like.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_utils.py
  llama-index-integrations/llms/llama-index-llms-upstage/tests/test_llms_upstage.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/llama_index/multi_modal_llms/openai/utils.py
Labels: lgtm, size:L

#17141 fix doc syntactic error
  docs/docs/understanding/extraction/structured_llms.md
  docs/docs/understanding/putting_it_all_together/agents.md
Labels: lgtm, size:XS

#17150 Ollama LLM: Added TypeError exception to _get_response_token_counts
  llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
  llama-index-integrations/llms/llama-index-llms-ollama/pyproject.toml
Labels: lgtm, size:XS

#17148 docs: rewrite image reasoning example without multimodal LLM
  docs/docs/examples/multi_modal/openai_multi_modal.ipynb
  llama-index-core/llama_index/core/llms/__init__.py
Labels: lgtm, size:XS

#17159 Fix mem0 version check
  llama-index-integrations/memory/llama-index-memory-mem0/llama_index/memory/mem0/base.py
  llama-index-integrations/memory/llama-index-memory-mem0/pyproject.toml
Labels: size:XS

#17158 proper auth token in TEI
  llama-index-integrations/embeddings/llama-index-embeddings-text-embeddings-inference/llama_index/embeddings/text_embeddings_inference/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-text-embeddings-inference/pyproject.toml
Labels: size:XS

#17163 max alpha not none in weaviate
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/pyproject.toml
Labels: size:XS

#17160 update doc id for unstructured reader
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/unstructured/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: size:XS

#17167 tests: update fastapi
  llama-index-networks/pyproject.toml
Labels: size:XS

#17168 ci: temprary fix nvidia tests
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
Labels: lgtm, size:XS

#17161 changes in openai identification in url
  llama-index-integrations/llms/llama-index-llms-sambanovasystems/llama_index/llms/sambanovasystems/base.py
  llama-index-integrations/llms/llama-index-llms-sambanovasystems/pyproject.toml
Labels: lgtm, size:S

#17156 chore: cover SimpleDirectoryReader with unit tests
  llama-index-core/llama_index/core/readers/base.py
  llama-index-core/llama_index/core/readers/download.py
  llama-index-core/llama_index/core/readers/file/base.py
  llama-index-core/llama_index/core/readers/loading.py
  llama-index-core/pyproject.toml
  llama-index-core/tests/readers/file/BUILD
  llama-index-core/tests/readers/file/__init__.py
  llama-index-core/tests/readers/file/data/empty/.gitkeep
  llama-index-core/tests/readers/file/data/excluded/excluded_1.txt
  llama-index-core/tests/readers/file/data/excluded_0.txt
  llama-index-core/tests/readers/file/data/file_0.md
  llama-index-core/tests/readers/file/data/file_0.xyz
  llama-index-core/tests/readers/file/data/sub/file_1.txt
  llama-index-core/tests/readers/file/test_base.py
  llama-index-core/tests/readers/test_json.py
  llama-index-core/tests/readers/test_load_reader.py
Labels: lgtm, size:L

#17134 [Integration] AWS Bedrock Reranker
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/.gitignore
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/Makefile
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/llama_index/postprocessor/bedrock_rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/llama_index/postprocessor/bedrock_rerank/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/llama_index/postprocessor/bedrock_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/tests/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/tests/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/tests/test_postprocessor_bedrock_rerank.py
Labels: lgtm, size:L

#17140 feat: add SafeFormatter
  llama-index-core/llama_index/core/output_parsers/langchain.py
Labels: lgtm, size:S

#17172 v0.12.3
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/callbacks/argilla.md
  docs/docs/api_reference/postprocessor/bedrock_rerank.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#17183 [fix] integration health check script
  scripts/integration_health_check.py
Labels: lgtm, size:M

#17182 Fix for Feature/perplexity
  llama-index-integrations/llms/llama-index-llms-perplexity/llama_index/llms/perplexity/base.py
  llama-index-integrations/llms/llama-index-llms-perplexity/pyproject.toml
Labels: lgtm, size:S

#17176 Add Verbose to Vectara as_query_engine
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/query.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-vectara/tests/test_indices_managed_vectara.py
Labels: lgtm, size:M

#17184 BUG FIX: llama-index-vectorstore-chromadb to work with chromadb v0.5.17
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/llama_index/vector_stores/chroma/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/pyproject.toml
Labels: lgtm, size:M

#17188 Update core structured predict streaming, add ollama structured predict
  llama-index-core/llama_index/core/program/function_program.py
  llama-index-core/llama_index/core/program/utils.py
  llama-index-core/tests/program/test_utils.py
  llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
Labels: size:XL

#17178 update tenacity dependency in llama-index-core
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
Labels: lgtm, size:XS

#17187 Add posibility to use URI as doc id in WholeSiteReader
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/whole_site/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:S

#17193 unpin pydantic
  llama-index-core/llama_index/core/schema.py
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
Labels: size:XS

#17197 refactor: Improve type safety in QdrantVectorStore client parameters
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
Labels: size:S

#17198 v0.12.4
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-ollama/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ollama/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#17195 Update pgvector dependency to version 0.3.6
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: lgtm, size:XS

#17203 Add unittests for milvus vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/tests/test_vector_stores_milvus.py
Labels: lgtm, size:L

#17210 fix: relax pin on openai dependency
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-azure-openai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nebius/pyproject.toml
Labels: lgtm, size:XS

#17209 chore: update lockfile to pull latest python-multipart
  docs/poetry.lock
Labels: lgtm, size:XS

#17192 feat: integration on pinecone hosted rerankers
  llama-index-integrations/postprocessor/llama-index-postprocessor-pinecone-native-rerank/.gitignore
  llama-index-integrations/postprocessor/llama-index-postprocessor-pinecone-native-rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-pinecone-native-rerank/Makefile
  llama-index-integrations/postprocessor/llama-index-postprocessor-pinecone-native-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-pinecone-native-rerank/llama_index/postprocessor/pinecone_native_rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-pinecone-native-rerank/llama_index/postprocessor/pinecone_native_rerank/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-pinecone-native-rerank/llama_index/postprocessor/pinecone_native_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-pinecone-native-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-pinecone-native-rerank/tests/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-pinecone-native-rerank/tests/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-pinecone-native-rerank/tests/test_pinecone_native_reranker.py
Labels: lgtm, size:L

#17208 Refined the default documentation generation for ReAct function tools
  llama-index-core/llama_index/core/tools/function_tool.py
  llama-index-core/llama_index/core/tools/types.py
Labels: lgtm, size:S

#17216 Allow skipping index creation for flows with read-only user
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: lgtm, size:S

#17213 v0.12.5
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/postprocessor/pinecone_native_rerank.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#17186 fix: jira safe get attributes
  llama-index-integrations/readers/llama-index-readers-jira/llama_index/readers/jira/base.py
  llama-index-integrations/readers/llama-index-readers-jira/pyproject.toml
Labels: lgtm, size:M

#17218 fix: merge text blocks into a plain string when role is assistant or …
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_utils.py
Labels: lgtm, size:S

#17223 Add cypher corrector and allow graph schema filtering
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/__init__.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/cypher_corrector.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: lgtm, size:L

#17233 bump postgres deps
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: size:XS

#17120 add support for voyageai >=0.3.0
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/pyproject.toml
Labels: lgtm, size:XS

#17222 Add `bottom_n`, `package_tuple_to_str`, and restrict `num_workers` to 1
  scripts/integration_health_check.py
Labels: lgtm, size:M

#17207 fix: Add input validation and retry mechanism to HuggingFaceEmbedding
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/llama_index/embeddings/huggingface/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/tests/test_embeddings_huggingface.py
Labels: lgtm, size:L

#17228 Fixed import errors for experimental JSONalyzeQueryEngine
  llama-index-experimental/llama_index/experimental/query_engine/__init__.py
  llama-index-experimental/llama_index/experimental/query_engine/jsonalyze/__init__.py
  llama-index-experimental/pyproject.toml
Labels: lgtm, size:XS

#17240 make openai content blocks optional
  llama-index-integrations/llms/llama-index-llms-cerebras/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-databricks/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-groq/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-nebius/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-neutrino/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai-like/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai-like/tests/test_openai_like.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_utils.py
  llama-index-integrations/llms/llama-index-llms-openllm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openrouter/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-paieas/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-pipeshift/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-together/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-upstage/tests/test_llms_upstage.py
Labels: size:L

#17229 refactor and optimize milvus code
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:L

#17220 Add async support to weaviate vector store integration
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/_exceptions.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/tests/test_to_weaviate_filter.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/tests/test_vector_stores_weaviate.py
Labels: lgtm, size:XXL

#17221 [Issue #17219] MilvusVectorStore Parse "milvus_search_config" out of "vector_store_kwargs"
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:S

#17204 refact: Refactor `Document` to be natively multimodal
  llama-index-core/llama_index/core/node_parser/node_utils.py
  llama-index-core/llama_index/core/schema.py
  llama-index-core/llama_index/core/storage/docstore/keyval_docstore.py
  llama-index-core/tests/schema/test_node.py
  llama-index-integrations/llms/llama-index-llms-modelscope/llama_index/llms/modelscope/base.py
  llama-index-integrations/llms/llama-index-llms-modelscope/pyproject.toml
  llama-index-integrations/node_parser/llama-index-node-parser-docling/tests/test_node_parser_docling.py
  llama-index-integrations/readers/llama-index-readers-docling/tests/test_readers_docling.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/test_vectorstore.py
Labels: lgtm, size:L

#17236 fix(metrics): fixed NDCG calculation and updated previous tests
  llama-index-core/llama_index/core/evaluation/retrieval/metrics.py
  llama-index-core/tests/evaluation/test_metrics.py
Labels: lgtm, size:M

#17246 fix: update unstructured dependency pin
  llama-index-packs/llama-index-packs-recursive-retriever/BUILD
  llama-index-packs/llama-index-packs-recursive-retriever/pyproject.toml
  llama-index-packs/llama-index-packs-recursive-retriever/requirements.txt
Labels: lgtm, size:S

#17244 fix: accept already base64-encoded data in ImageBlock
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/tests/base/llms/test_types.py
Labels: lgtm, size:S

#17211 Add ILIKE feature for PGVectorStore and NileVectorStore.
  llama-index-core/llama_index/core/vector_stores/types.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/llama_index/vector_stores/nile/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
Labels: lgtm, size:S

#17247 Fix content blocks again
  llama-index-integrations/llms/llama-index-llms-openai-like/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai-like/tests/test_openai_like.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_utils.py
Labels: size:L

#17245 feat: rewrite the example using AzureOpenAI
  docs/docs/examples/multi_modal/azure_openai_multi_modal.ipynb
Labels: docs, lgtm, size:M

#17242 Handle empty retrieved Pinecone index values
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/llama_index/vector_stores/pinecone/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/pyproject.toml
Labels: lgtm, size:XS

#17248 Update link for the Weaviate Python docs
  docs/docs/examples/data_connectors/WeaviateDemo.ipynb
Labels: size:XS

#17249 Gemini 2.0 support
  docs/docs/examples/agent/agentic_rag_using_vertex_ai.ipynb
  docs/docs/examples/agent/agentic_rag_with_llamaindex_and_vertexai_managed_index.ipynb
  docs/docs/examples/llm/vertex.ipynb
  docs/docs/examples/managed/VertexAIDemo.ipynb
  docs/docs/examples/property_graph/agentic_graph_rag_vertex.ipynb
  docs/docs/examples/retrievers/vertex_ai_search_retriever.ipynb
  docs/docs/examples/vector_stores/VertexAIVectorSearchDemo.ipynb
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py
  llama-index-integrations/llms/llama-index-llms-vertex/pyproject.toml
Labels: size:M

#17253 Adding llama 3.3-70b as function-calling-capable
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/utils.py
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
Labels: lgtm, size:XS

#17254 fix openai message dicts for tool calls
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_utils.py
Labels: size:XS

#17252 Fix: TGI context window
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/utils.py
  llama-index-integrations/llms/llama-index-llms-huggingface/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/llama_index/llms/text_generation_inference/base.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/llama_index/llms/text_generation_inference/utils.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/pyproject.toml
Labels: lgtm, size:M

#17259 fix: make `ImageDocument` derive from `Document`, backward compatible
  llama-index-core/llama_index/core/multi_modal_llms/base.py
  llama-index-core/llama_index/core/node_parser/node_utils.py
  llama-index-core/llama_index/core/schema.py
  llama-index-core/tests/schema/test_media_resource.py
  llama-index-core/tests/schema/test_node.py
  llama-index-core/tests/schema/test_schema.py
Labels: lgtm, size:L

#17270 feat: Add NOT filter condition to MetadataFilter and QdrantVectorStore
  llama-index-core/llama_index/core/vector_stores/types.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/tests/test_vector_stores_qdrant.py
Labels: lgtm, size:L

#17267 Add timeout config to neo4j graph
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/base.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: lgtm, size:S

#17261 Introducting VoyageAI's new multimodal embeddings model
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/llama_index/embeddings/voyageai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/pyproject.toml
Labels: lgtm, size:L

#17273 User vs tool
  llama-index-core/llama_index/core/agent/react/templates/system_header_template.md
  llama-index-core/llama_index/core/agent/react_multimodal/prompts.py
Labels: lgtm, size:XS

#17274 add content blocks to anthropic
  docs/docs/examples/cookbooks/contextual_retrieval.ipynb
  docs/docs/examples/llm/anthropic_prompt_caching.ipynb
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: size:L

#17278 Do not send blank content to anthropic
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: size:XS

#17279 fix links in RAG understanding
  docs/docs/understanding/rag/index.md
Labels: size:S

#17280 add tool call id/name to mistral chat messages
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/base.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
Labels: size:S

#17276 Support Confluence cookies
  llama-index-integrations/readers/llama-index-readers-confluence/README.md
  llama-index-integrations/readers/llama-index-readers-confluence/llama_index/readers/confluence/base.py
  llama-index-integrations/readers/llama-index-readers-confluence/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-confluence/tests/test_readers_confluence.py
Labels: lgtm, size:S

#17289 Add text and embedding type to neo4j enhanced schema
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: lgtm, size:M

#17285 Update Tavily integration documentation
  llama-index-integrations/tools/llama-index-tools-tavily-research/README.md
  llama-index-integrations/tools/llama-index-tools-tavily-research/examples/tavily.ipynb
Labels: lgtm, size:M

#17284 VoyageAI multimodal embedding, correction
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/llama_index/embeddings/voyageai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/pyproject.toml
Labels: lgtm, size:M

#17275 - add readme to google tools
  llama-index-integrations/tools/llama-index-tools-google/README.md
Labels: lgtm, size:M

#17296 fix: add a timeout to langchain callback handler
  llama-index-core/llama_index/core/langchain_helpers/streaming.py
Labels: lgtm, size:S

#17292 ScrapegraphAI link was not correct and I fix it
  llama-index-integrations/tools/llama-index-tools-scrapegraph/README.md
Labels: size:XS

#17300 [bug fix] Ensure that `StopEvent` gets cleared from `Context._in_progress["_done"]` after a Workflow run
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_context.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: lgtm, size:S

#17299 Update anthropic type imports for v0.41.0 release
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-portkey/pyproject.toml
Labels: lgtm, size:S

#17302 feat: Add tool support to AnthropicMultiModal
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/llama_index/multi_modal_llms/anthropic/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/tests/test_multi-modal-llms_anthropic.py
Labels: lgtm, size:M

#17301 Update Cerebras examples to use Llama 3.3 70b
  docs/docs/examples/llm/cerebras.ipynb
  llama-index-integrations/llms/llama-index-llms-cerebras/README.md
  llama-index-integrations/llms/llama-index-llms-cerebras/llama_index/llms/cerebras/base.py
  llama-index-integrations/llms/llama-index-llms-cerebras/pyproject.toml
Labels: lgtm, size:S

#17305 v0.12.6
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/tools/scrapegraph.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#17307 o1 models
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/llama_index/multi_modal_llms/openai/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/pyproject.toml
Labels: size:S

#17312 fix: make Document serialization backward compatible
  llama-index-core/llama_index/core/schema.py
  llama-index-core/tests/schema/test_schema.py
  llama-index-integrations/readers/llama-index-readers-docling/tests/test_readers_docling.py
Labels: lgtm, size:L

#17290 CosmosDB insertion bugfix
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosmongo/llama_index/vector_stores/azurecosmosmongo/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosmongo/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/llama_index/vector_stores/azurecosmosnosql/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/pyproject.toml
Labels: lgtm, size:XS

#17315 Exposing additional keyword arguments for VoyageAI's embedding model
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/llama_index/embeddings/voyageai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/tests/test_embeddings_voyageai.py
Labels: lgtm, size:M

#17310 VoyageAI Reranker optional API Key
  llama-index-integrations/postprocessor/llama-index-postprocessor-voyageai-rerank/llama_index/postprocessor/voyageai_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-voyageai-rerank/pyproject.toml
Labels: size:XS

#17295 feat: add py.typed for OpenAI and Gemini
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/BUILD
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/py.typed
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/BUILD
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/py.typed
Labels: lgtm, size:S

#17318 Update README.md
  llama-index-integrations/readers/llama-index-readers-gitlab/README.md
Labels: lgtm, size:XS

#17255 Doc Error: modify part 2 of advanced prompts
  docs/docs/examples/prompts/advanced_prompts.ipynb
Labels: lgtm, size:L

#17177 Vntuananhbui multimodal rag guardrail
  docs/docs/examples/multi_modal/multimodal_rag_guardrail_gemini_llmguard_llmguard.ipynb
Labels: lgtm, size:XXL

#16860 Feature/keywordsai llm
  llama-index-integrations/llms/llama-index-llms-keywordsai/.gitignore
  llama-index-integrations/llms/llama-index-llms-keywordsai/BUILD
  llama-index-integrations/llms/llama-index-llms-keywordsai/Makefile
  llama-index-integrations/llms/llama-index-llms-keywordsai/README.md
  llama-index-integrations/llms/llama-index-llms-keywordsai/llama_index/llms/keywordsai/BUILD
  llama-index-integrations/llms/llama-index-llms-keywordsai/llama_index/llms/keywordsai/__init__.py
  llama-index-integrations/llms/llama-index-llms-keywordsai/llama_index/llms/keywordsai/base.py
  llama-index-integrations/llms/llama-index-llms-keywordsai/llama_index/llms/keywordsai/utils.py
  llama-index-integrations/llms/llama-index-llms-keywordsai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-keywordsai/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-keywordsai/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-keywordsai/tests/test_llms_keywordsai.py
Labels: lgtm, size:XL

#16888 Add OCI Generative AI tool calling support
  docs/docs/examples/llm/oci_genai.ipynb
  llama-index-integrations/llms/llama-index-llms-oci-genai/llama_index/llms/oci_genai/base.py
  llama-index-integrations/llms/llama-index-llms-oci-genai/llama_index/llms/oci_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-oci-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-oci-genai/tests/test_oci_genai.py
Labels: lgtm, size:XL

#17320 v0.12.7
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/step.py
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#17327 NVIDIA Blueprint for content creation
  docs/docs/examples/agent/nvidia_document_research_blueprint_for_content_creation.ipynb
Labels: lgtm, size:XS

#17328 Tweak o1 function calling reqs
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:S

#17329 Fix NVIDIA Blueprint title
  docs/docs/examples/agent/nvidia_document_research_blueprint_for_content_creation.ipynb
Labels: lgtm, size:XS

#17338 Fix missing aput in awrite_response_to_history
  llama-index-core/llama_index/core/chat_engine/types.py
Labels: lgtm, size:XS

#17314 Cognee integration
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/.gitignore
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/BUILD
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/Makefile
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/README.md
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/BUILD
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/__init__.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/base.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/graph_rag.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/pyproject.toml
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/BUILD
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/__init__.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_add_data.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_get_graph_url.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_graph_rag_cognee.py
Labels: lgtm, size:XL

#17306 Update API Reference and Component Guides For Sambanova
  docs/docs/module_guides/models/llms/modules.md
  llama-index-integrations/llms/llama-index-llms-sambanovasystems/llama_index/llms/sambanovasystems/base.py
Labels: lgtm, size:L

#17342 v0.12.8
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/graph_rag/cognee.md
  docs/docs/api_reference/llms/keywordsai.md
  docs/mkdocs.yml
  docs/scripts/prepare_for_build.py
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#17351 Fix minor issues in rss
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/rss/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:S

#17346 example: VoyageAI's multimodal embeddings example
  docs/docs/examples/embeddings/voyageai.ipynb
Labels: lgtm, size:XS

#17347 implement client_kwargs["custom_batch"] for weaviate
  docs/docs/examples/vector_stores/WeaviateIndexDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/tests/test_vector_stores_weaviate.py
Labels: lgtm, size:L

#17340 bugfix when initializing with async aoss vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
Labels: size:M

#17321 TablestoreVectorStore check the Dimension of the embedding when writing it to store.
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/llama_index/vector_stores/tablestore/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/tests/test_vector_stores_tablestore.py
Labels: lgtm, size:M

#17335 `azureaisearch`: add semantic search mode support for async queries
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
Labels: lgtm, size:M

#17354 fixed the raptor example in llama-index-packs by updating the pip ins…
  llama-index-packs/llama-index-packs-raptor/examples/raptor.ipynb
Labels: lgtm, size:XS

#17361 chore: bump jinja version
  docs/poetry.lock
  docs/pyproject.toml
Labels: size:XS

#17362 chore: bump jinja2 version in lockfiles
  llama-index-core/poetry.lock
  poetry.lock
Labels: size:XS

#17364 Fix Regression on Tools use for Bedrock Converse
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: lgtm, size:S

#17360 fix: prevent infinite recursion in get_article_urls
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/knowledge_base/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:S

#17365 Fix typo in property name
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
Labels: size:XS

#17366 TablestoreVectorStore: support hybrid query, modify some documents.
  docs/docs/community/integrations/vector_stores.md
  docs/docs/examples/vector_stores/TablestoreDemo.ipynb
  docs/docs/module_guides/storing/vector_stores.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/llama_index/vector_stores/tablestore/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/tests/test_vector_stores_tablestore.py
Labels: lgtm, size:L

#17353 Fix IndexError in LLM Reranking when handling malformed LLM responses
  llama-index-core/llama_index/core/indices/utils.py
Labels: lgtm, size:S

#17377 qdrant filter fix for `query_str is None`
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
Labels: size:XS

#17378 feat: milvus async
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/tests/test_vector_stores_milvus.py
Labels: lgtm, size:XL

#17383 fix: Fix graphRAG notebook triplet extraction template
  docs/docs/examples/cookbooks/GraphRAG_v1.ipynb
  docs/docs/examples/cookbooks/GraphRAG_v2.ipynb
Labels: lgtm, size:XS

#17343 VoyageAIRerank constructor fix
  llama-index-integrations/postprocessor/llama-index-postprocessor-voyageai-rerank/llama_index/postprocessor/voyageai_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-voyageai-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-voyageai-rerank/tests/test_postprocessor_voyageai-rerank.py
Labels: lgtm, size:M

#17387 feat: refactoring of example and readme
  llama-index-integrations/tools/llama-index-tools-scrapegraph/README.md
  llama-index-integrations/tools/llama-index-tools-scrapegraph/examples/scrapegraph-llama-index.py
  llama-index-integrations/tools/llama-index-tools-scrapegraph/llama_index/tools/scrapegraph/__init__.py
  llama-index-integrations/tools/llama-index-tools-scrapegraph/llama_index/tools/scrapegraph/base.py
  llama-index-integrations/tools/llama-index-tools-scrapegraph/tests/test_tools_scrapegraph.py
Labels: lgtm, size:M

#17385 fix storeindex cosmosnosql query issue - (BadRequest) One of the inpu…
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/llama_index/vector_stores/azurecosmosnosql/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/pyproject.toml
Labels: lgtm, size:S

#12000 Pass aws_region_name to get_aws_service_client() in SageMakerLLM
  llama-index-integrations/llms/llama-index-llms-sagemaker-endpoint/llama_index/llms/sagemaker_endpoint/base.py
  llama-index-integrations/llms/llama-index-llms-sagemaker-endpoint/pyproject.toml
Labels: lgtm, size:S

#17391 update docstore.azurecosmosnosql pyproject.toml
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-azurecosmosnosql/pyproject.toml
Labels: lgtm, size:S

#17392 Fix: Properly add documents from Gitlab Repo
  llama-index-integrations/readers/llama-index-readers-gitlab/llama_index/readers/gitlab/repository/base.py
  llama-index-integrations/readers/llama-index-readers-gitlab/pyproject.toml
Labels: lgtm, size:XS

#17394 clean up type hints in schema extractor
  llama-index-core/llama_index/core/indices/property_graph/transformations/schema_llm.py
Labels: size:S

#17400 v0.12.9
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/storage/docstore/azurecosmosnosql.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L
