Repository run-llama/llama_index, pull requests merged in 2024-06, with the labels that each got.

#13879 Fix: Incorrect naming of acreate_plan in StructuredPlannerAgent
  llama-index-core/llama_index/core/agent/runner/planner.py
Labels: size:XS

#13875 Handle cases where type is missing (neo4j property graph)
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: lgtm, size:XS

#13888 Fix cur depth in simple property graph store
  llama-index-core/llama_index/core/graph_stores/simple_labelled.py
Labels: lgtm, size:XS

#13886 use default UUIDs when possible for pg vector stores
  llama-index-core/llama_index/core/graph_stores/types.py
  llama-index-core/llama_index/core/indices/property_graph/base.py
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/vector.py
Labels: size:M

#13804 Fix/OpenSearch filter logic
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
Labels: lgtm, size:S

#13894 Missing bumps
  llama-index-integrations/agent/llama-index-agent-openai-legacy/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-huggingface/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ipex-llm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-langchain/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-cohere-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-colbert-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-dashscope-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-flag-embedding-reranker/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-jinaai-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankgpt-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-sbert-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-voyageai-rerank/pyproject.toml
  llama-index-packs/llama-index-packs-cohere-citation-chat/pyproject.toml
Labels: size:M

#13895 Add backwards compatibility to `Dispatcher.get_dispatch_event()` method
  llama-index-core/llama_index/core/instrumentation/dispatcher.py
  llama-index-core/tests/instrumentation/test_dispatcher.py
Labels: lgtm, size:L

#13896 fix: ipex-llms broken CD build
  llama-index-integrations/llms/llama-index-llms-ipex-llm/pyproject.toml
Labels: size:XS

#13899 Feedback after running through property_graph_advanced tutorial
  docs/docs/examples/property_graph/graph_store.ipynb
  docs/docs/examples/property_graph/property_graph_advanced.ipynb
Labels: lgtm, size:XS

#13878 Improve the retry mechanism of OpenAI
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai.py
Labels: lgtm, size:M

#13897 AsyncWebPageReader: made it actually async; it was exhibiting blocking behavior
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/async_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:S

#13891 avoid empty or duplicate inserts in property graph index
  docs/docs/api_reference/storage/graph_stores/neo4j.md
  docs/docs/examples/property_graph/graph_store.ipynb
  docs/docs/examples/property_graph/property_graph_advanced.ipynb
  docs/docs/examples/property_graph/property_graph_basic.ipynb
  docs/docs/examples/property_graph/property_graph_custom_retriever.ipynb
  docs/docs/examples/property_graph/property_graph_neo4j.ipynb
  docs/docs/module_guides/indexing/lpg_index_guide.md
  llama-index-core/llama_index/core/indices/property_graph/base.py
  llama-index-core/tests/indices/property_graph/BUILD
  llama-index-core/tests/indices/property_graph/__init__.py
  llama-index-core/tests/indices/property_graph/test_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/__init__.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/tests/test_pg_stores_neo4j.py
Labels: lgtm, size:L

#13902 v0.10.43
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:M

#13920 Add Nomic multi modal embeddings
  llama-index-integrations/embeddings/llama-index-embeddings-nomic/llama_index/embeddings/nomic/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nomic/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nomic/tests/test_embeddings_nomic.py
Labels: lgtm, size:M

#13854 docs: changed nim language and added instructions to obtaining api key
  docs/docs/examples/llm/nvidia_nim.ipynb
Labels: lgtm, size:M

#13861 feat: add Jina Embeddings MultiModal
  llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-jinaai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-jinaai/tests/test_embeddings_jinaai.py
Labels: lgtm, size:L

#13916 feat: add spans for tools
  llama-index-core/llama_index/core/tools/types.py
Labels: lgtm, size:S

#13903 Better handling of Vectara API exceptions
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/retriever.py
  llama-index-packs/llama-index-packs-vectara-rag/README.md
Labels: lgtm, size:S

#13931 Fix typo in doc
  docs/docs/examples/multi_modal/gpt4v_experiments_cot.ipynb
Labels: lgtm, size:XS

#13917 feat: add exception events for streaming errors
  llama-index-core/llama_index/core/instrumentation/events/exception.py
  llama-index-core/llama_index/core/llms/callbacks.py
Labels: lgtm, size:L

#13884 feat: Add Google Maps Text Search Reader
  docs/docs/examples/data_connectors/GoogleMapsTextSearchReaderDemo.ipynb
  llama-index-integrations/readers/llama-index-readers-google/README.md
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/__init__.py
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/maps/BUILD
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/maps/README.md
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/maps/__init__.py
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/maps/base.py
  llama-index-integrations/readers/llama-index-readers-google/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-google/tests/test_readers_google_maps.py
Labels: lgtm, size:L

#13890 Jira personal access token with hosted instances
  llama-index-integrations/readers/llama-index-readers-jira/README.md
  llama-index-integrations/readers/llama-index-readers-jira/llama_index/readers/jira/base.py
  llama-index-integrations/readers/llama-index-readers-jira/pyproject.toml
Labels: lgtm, size:S

#13919 Fix: Llama Index Prem AI setting single response output
  llama-index-integrations/llms/llama-index-llms-premai/llama_index/llms/premai/base.py
Labels: lgtm, size:M

#13938 ensure cypher returns list before iterating
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: size:XS

#13941 bump again, whoops
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: size:XS

#13940 change to compact in auto prev next
  llama-index-core/llama_index/core/postprocessor/node.py
Labels: lgtm, size:XS

#13954 Add cookbook for prometheus-2 as LLM evaluator
  docs/docs/examples/cookbooks/prometheus2_cookbook.ipynb
Labels: lgtm, size:XL

#13955 missing vbumps
  llama-index-integrations/indices/llama-index-indices-managed-vectara/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-premai/pyproject.toml
Labels: size:XS

#13963 This key is necessary for sitemaps to be generated by mkdocs
  docs/mkdocs.yml
Labels: lgtm, size:XS

#13951 Update outdated docs
  docs/docs/examples/memory/ChatSummaryMemoryBuffer.ipynb
Labels: lgtm, size:XS

#13745 Support all filter operators for Milvus vector store
  llama-index-core/llama_index/core/vector_stores/types.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/tests/test_vector_stores_milvus.py
Labels: lgtm, size:L

#13966 feat: add spans for multimodal LLMs
  llama-index-core/llama_index/core/multi_modal_llms/base.py
Labels: lgtm, size:S

#13981 📝 Fix streaming example in "standalone usage" docs
  docs/docs/module_guides/models/llms/usage_standalone.md
Labels: lgtm, size:S

#13929 + DuckDBRetriever
  docs/docs/api_reference/retrievers/duckdb_retriever.md
  docs/mkdocs.yml
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/retrievers/llama-index-retrievers-duckdb-retriever/.gitignore
  llama-index-integrations/retrievers/llama-index-retrievers-duckdb-retriever/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-duckdb-retriever/Makefile
  llama-index-integrations/retrievers/llama-index-retrievers-duckdb-retriever/README.md
  llama-index-integrations/retrievers/llama-index-retrievers-duckdb-retriever/llama_index/retrievers/duckdb_retriever/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-duckdb-retriever/llama_index/retrievers/duckdb_retriever/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-duckdb-retriever/llama_index/retrievers/duckdb_retriever/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-duckdb-retriever/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-duckdb-retriever/tests/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-duckdb-retriever/tests/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-duckdb-retriever/tests/test_retrievers_bm25_retriever.py
Labels: lgtm, size:L

#13936 Broaden SQLAlchemy support in llama-index-vector-stores-postgres to 1.4+
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: lgtm, size:M

#13974 Update jina embedding notebook to include multimodal capability
  docs/docs/examples/embeddings/jinaai_embeddings.ipynb
Labels: lgtm, size:L

#13959 LlamaPacks: Add ZenGuard llamapack
  llama-index-packs/llama-index-packs-zenguard/.gitignore
  llama-index-packs/llama-index-packs-zenguard/BUILD
  llama-index-packs/llama-index-packs-zenguard/Makefile
  llama-index-packs/llama-index-packs-zenguard/README.md
  llama-index-packs/llama-index-packs-zenguard/examples/zenguard.ipynb
  llama-index-packs/llama-index-packs-zenguard/llama_index/packs/zenguard/BUILD
  llama-index-packs/llama-index-packs-zenguard/llama_index/packs/zenguard/__init__.py
  llama-index-packs/llama-index-packs-zenguard/llama_index/packs/zenguard/base.py
  llama-index-packs/llama-index-packs-zenguard/pyproject.toml
  llama-index-packs/llama-index-packs-zenguard/tests/BUILD
  llama-index-packs/llama-index-packs-zenguard/tests/__init__.py
  llama-index-packs/llama-index-packs-zenguard/tests/test_packs_zenguard.py
Labels: lgtm, size:XL

#13988 [llamapacks] fix the ZenGuard llampack package name
  llama-index-packs/llama-index-packs-zenguard/pyproject.toml
Labels: lgtm, size:XS

#14008 Add more embeddings to configurable transformations
  llama-index-core/llama_index/core/ingestion/transformations.py
Labels: lgtm, size:M

#14006 add option to specify embed_model to NLSQLTableQueryEngine
  llama-index-core/llama_index/core/indices/struct_store/sql_query.py
Labels: lgtm, size:XS

#14005 [ZenGuard LLamaPack] Add a colab link to README
  llama-index-packs/llama-index-packs-zenguard/README.md
Labels: lgtm, size:XS

#14001 Qdrant: Create payload index for doc_id
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
Labels: lgtm, size:M

#14000 Bind MongoDB primary key ID to Document object to ensure refresh_ref_docs only vectorizes changed data.
  llama-index-integrations/readers/llama-index-readers-mongodb/llama_index/readers/mongodb/base.py
  llama-index-integrations/readers/llama-index-readers-mongodb/pyproject.toml
Labels: lgtm, size:XS

#13998 fix(deepinfrallm): default max_tokens
  llama-index-integrations/llms/llama-index-llms-deepinfra/llama_index/llms/deepinfra/base.py
  llama-index-integrations/llms/llama-index-llms-deepinfra/llama_index/llms/deepinfra/constants.py
  llama-index-integrations/llms/llama-index-llms-deepinfra/pyproject.toml
Labels: lgtm, size:XS

#13997 Update lpg_index_guide.md (minor typo)
  docs/docs/module_guides/indexing/lpg_index_guide.md
Labels: lgtm, size:XS

#13993 Fix LanceDBVectorStore add logic (#13992)
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/llama_index/vector_stores/lancedb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/pyproject.toml
Labels: lgtm, size:S

#13970 Fix error when using azure_ad without setting the API key
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/llama_index/embeddings/azure_openai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/pyproject.toml
Labels: lgtm, size:S

#13947 Adding streaming support for SQLAutoVectorQueryEngine
  llama-index-core/llama_index/core/query_engine/sql_join_query_engine.py
Labels: lgtm, size:M

#13973 Improve type annotations
  llama-index-core/llama_index/core/evaluation/context_relevancy.py
  llama-index-core/llama_index/core/evaluation/dataset_generation.py
  llama-index-core/llama_index/core/evaluation/faithfulness.py
  llama-index-core/llama_index/core/evaluation/guideline.py
  llama-index-core/llama_index/core/evaluation/pairwise.py
  llama-index-core/llama_index/core/evaluation/relevancy.py
  llama-index-core/llama_index/core/evaluation/retrieval/metrics.py
  llama-index-core/llama_index/core/evaluation/retrieval/metrics_base.py
  llama-index-core/llama_index/core/indices/multi_modal/base.py
  llama-index-core/llama_index/core/indices/multi_modal/retriever.py
  llama-index-core/llama_index/core/llama_dataset/download.py
  llama-index-core/llama_index/core/query_engine/multi_modal.py
Labels: lgtm, size:M

#14003 refactor: add spans to `abstractmethods` via mixin
  llama-index-core/llama_index/core/base/agent/types.py
  llama-index-core/llama_index/core/base/base_query_engine.py
  llama-index-core/llama_index/core/base/base_retriever.py
  llama-index-core/llama_index/core/base/base_selector.py
  llama-index-core/llama_index/core/base/embeddings/base.py
  llama-index-core/llama_index/core/base/llms/base.py
  llama-index-core/llama_index/core/chat_engine/types.py
  llama-index-core/llama_index/core/image_retriever.py
  llama-index-core/llama_index/core/indices/query/query_transform/base.py
  llama-index-core/llama_index/core/indices/struct_store/sql_retriever.py
  llama-index-core/llama_index/core/instrumentation/__init__.py
  llama-index-core/llama_index/core/instrumentation/dispatcher.py
  llama-index-core/llama_index/core/multi_modal_llms/base.py
  llama-index-core/llama_index/core/postprocessor/types.py
  llama-index-core/llama_index/core/question_gen/types.py
  llama-index-core/llama_index/core/response_synthesizers/base.py
  llama-index-core/llama_index/core/selectors/types.py
  llama-index-core/llama_index/core/service_context_elements/llm_predictor.py
  llama-index-core/llama_index/core/tools/types.py
  llama-index-core/llama_index/core/types.py
  llama-index-core/tests/instrumentation/test_dispatcher.py
Labels: lgtm, size:L

#14021 Fix Non-English Display Name
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/maps/base.py
  llama-index-integrations/readers/llama-index-readers-google/pyproject.toml
Labels: lgtm, size:S

#14023 fix: typo in awsdocdb
  llama-index-integrations/vector_stores/llama-index-vector-stores-awsdocdb/llama_index/vector_stores/awsdocdb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-awsdocdb/pyproject.toml
Labels: lgtm, size:XS

#14037 [ZenGuard LlamaPack] Add keywords and update colab link
  llama-index-packs/llama-index-packs-zenguard/examples/zenguard.ipynb
  llama-index-packs/llama-index-packs-zenguard/pyproject.toml
Labels: lgtm, size:S

#14038 Add WEBP and GIF to supported image types for SimpleDirectoryReader
  llama-index-core/llama_index/core/readers/file/base.py
Labels: lgtm, size:XS

#14010 Add inclusion filter to chromadb
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/llama_index/vector_stores/chroma/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/pyproject.toml
Labels: lgtm, size:XS

#14041 fix(max-document-length): remove limit
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/maps/base.py
  llama-index-integrations/readers/llama-index-readers-google/pyproject.toml
Labels: lgtm, size:S

#14053 correct __del__ Vllm
  llama-index-integrations/llms/llama-index-llms-vllm/llama_index/llms/vllm/base.py
  llama-index-integrations/llms/llama-index-llms-vllm/pyproject.toml
Labels: lgtm, size:S

#14030 Integration: AI21 Labs Jamba-Instruct Support
  docs/docs/examples/llm/ai21.ipynb
  llama-index-integrations/llms/llama-index-llms-ai21/README.md
  llama-index-integrations/llms/llama-index-llms-ai21/llama_index/llms/ai21/base.py
  llama-index-integrations/llms/llama-index-llms-ai21/llama_index/llms/ai21/utils.py
  llama-index-integrations/llms/llama-index-llms-ai21/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ai21/tests/test_llms_ai21.py
Labels: lgtm, size:XL

#13961 Expand milvus vector store filter options
  docs/docs/examples/vector_stores/MilvusOperatorFunctionDemo.ipynb
  llama-index-core/llama_index/core/vector_stores/types.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/tests/test_vector_stores_milvus.py
  poetry.lock
Labels: lgtm, size:XL

#14061 Add api key as field in Gemini Embedding
  llama-index-integrations/embeddings/llama-index-embeddings-gemini/llama_index/embeddings/gemini/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-gemini/pyproject.toml
Labels: lgtm, size:XS

#14062 feat: add spans to ingestion pipline
  llama-index-core/llama_index/core/ingestion/pipeline.py
  llama-index-core/llama_index/core/schema.py
Labels: lgtm, size:XS

#14067 [Community] Update dependency of llama-index-embeddings-ipex-llm and llama-index-llms-ipex-llm on Intel GPUs for Windows Users
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ipex-llm/pyproject.toml
Labels: lgtm, size:S

#14079 Bumping Mendable version
  docs/docs/javascript/mendablesearch.js
Labels: lgtm, size:XS

#13991 Add PandasExcelReader class for parsing excel files
  llama-index-core/llama_index/core/readers/file/base.py
  llama-index-integrations/agent/llama-index-agent-openai/tests/test_openai_assistant_agent.py
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/__init__.py
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/tabular/__init__.py
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/tabular/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
  llama-index-packs/llama-index-packs-zenguard/tests/test_packs_zenguard.py
Labels: lgtm, size:L

#14064 Integration: Remove stacktrace from notebook in AI21
  docs/docs/examples/llm/ai21.ipynb
Labels: lgtm, size:M

#14055 Implement Bedrock Converse API for function calling
  docs/docs/examples/agent/bedrock_converse_agent.ipynb
  docs/docs/examples/llm/bedrock_converse.ipynb
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/.gitignore
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/BUILD
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/Makefile
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/README.md
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/BUILD
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/__init__.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/tests/test_llms_bedrock_converse.py
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/utils.py
Labels: lgtm, size:XXL

#14072 Add support for Llama 3 Instruct prompt format
  llama-index-integrations/llms/llama-index-llms-llama-cpp/llama_index/llms/llama_cpp/llama_utils.py
  llama-index-integrations/llms/llama-index-llms-llama-cpp/tests/test_llms_llama_cpp.py
Labels: lgtm, size:L

#14091 Update `anthropic` dependency to `0.26.2` minimum version
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: lgtm, size:XS

#14083 [ZenGuard LLamaPack] Update README and colab links
  llama-index-packs/llama-index-packs-zenguard/README.md
  llama-index-packs/llama-index-packs-zenguard/examples/zenguard.ipynb
Labels: lgtm, size:XS

#14086 nit: fix for pandas excel reader
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/tabular/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:XS

#14102 Feature/added trust remote code
  llama-index-finetuning/llama_index/finetuning/embeddings/sentence_transformer.py
  llama-index-finetuning/pyproject.toml
Labels: lgtm, size:XS

#14085 Remove unnecessary excluded from fields in Bedrock embedding
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/llama_index/embeddings/bedrock/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/pyproject.toml
Labels: lgtm, size:S

#14107 Wrong mongo name was used instead of Postgres
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-postgres/llama_index/storage/index_store/postgres/base.py
Labels: lgtm, size:XS

#14108 fix anthropic llm calls
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: size:S

#14111 Fix to milvus filter enum parsing
  .github/workflows/build_package.yml
  .github/workflows/lint.yml
  .github/workflows/publish_release.yml
  .github/workflows/publish_sub_package.yml
  .github/workflows/unit_test.yml
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:S

#14112 Add Mixture Of Agents paper implementation
  llama-index-packs/llama-index-packs-mixture-of-agents/.gitignore
  llama-index-packs/llama-index-packs-mixture-of-agents/BUILD
  llama-index-packs/llama-index-packs-mixture-of-agents/CHANGELOG.md
  llama-index-packs/llama-index-packs-mixture-of-agents/Makefile
  llama-index-packs/llama-index-packs-mixture-of-agents/README.md
  llama-index-packs/llama-index-packs-mixture-of-agents/llama_index/packs/mixture_of_agents/BUILD
  llama-index-packs/llama-index-packs-mixture-of-agents/llama_index/packs/mixture_of_agents/__init__.py
  llama-index-packs/llama-index-packs-mixture-of-agents/llama_index/packs/mixture_of_agents/base.py
  llama-index-packs/llama-index-packs-mixture-of-agents/pyproject.toml
  llama-index-packs/llama-index-packs-mixture-of-agents/requirements.txt
  llama-index-packs/llama-index-packs-mixture-of-agents/tests/BUILD
  llama-index-packs/llama-index-packs-mixture-of-agents/tests/__init__.py
  llama-index-packs/llama-index-packs-mixture-of-agents/tests/test_packs_mixture_of_agents.py
Labels: lgtm, size:L

#14126 Add Vector ESS Open Source Talk
  docs/docs/presentations/materials/2024-06-13-vector-ess-oss-tools.ipynb
  docs/docs/presentations/past_presentations.md
Labels: size:XXL

#14026 Fixed System Prompts for Structured Generation
  llama-index-core/llama_index/core/program/function_program.py
  llama-index-core/llama_index/core/program/llm_program.py
Labels: lgtm, size:XS

#14076 MilvusVectorStore: always include text_key in output_fields
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:S

#14080 Feature/add command r support oci genai
  llama-index-integrations/llms/llama-index-llms-oci-genai/llama_index/llms/oci_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-oci-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-oci-genai/tests/test_oci_genai.py
Labels: lgtm, size:M

#13626 feat: Add Managed Index for LlamaIndex on Vertex AI for RAG
  .gitignore
  docs/docs/api_reference/indices/vertexai.md
  docs/docs/community/integrations/managed_indices.md
  docs/docs/examples/managed/VertexAIDemo.ipynb
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/.gitignore
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/BUILD
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/Makefile
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/README.md
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/llama_index/indices/managed/vertexai/BUILD
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/llama_index/indices/managed/vertexai/__init__.py
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/llama_index/indices/managed/vertexai/base.py
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/llama_index/indices/managed/vertexai/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/tests/BUILD
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/tests/__init__.py
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/tests/test_indices_managed_vertexai.py
Labels: lgtm, size:XL

#14135 [ZenGuard LlamaPack] Create Colab link in the ZenGuard LLamaPack README
  llama-index-packs/llama-index-packs-zenguard/README.md
Labels: lgtm, size:XS

#14123 Fixes TypeError: sequence item : expected str instance, int found
  llama-index-integrations/readers/llama-index-readers-mongodb/README.md
  llama-index-integrations/readers/llama-index-readers-mongodb/llama_index/readers/mongodb/base.py
  llama-index-integrations/readers/llama-index-readers-mongodb/pyproject.toml
Labels: lgtm, size:XS

#14100 [Core][Retrieval] Implement NDCG metric
  docs/docs/examples/evaluation/retrieval/retriever_eval.ipynb
  llama-index-core/llama_index/core/evaluation/retrieval/metrics.py
  llama-index-core/tests/evaluation/test_metrics.py
Labels: lgtm, size:L

#14145 Fix missing notebook
  docs/mkdocs.yml
Labels: lgtm, size:XS

#14109 Fix parsing sql query.py
  llama-index-core/llama_index/core/indices/struct_store/sql_query.py
  llama-index-core/tests/indices/struct_store/test_sql_query.py
Labels: lgtm, size:M

#14149 Fix Qdrant nodes
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
Labels: lgtm, size:S

#14114 Fixing broken links and example for SecGPT llama-pack
  llama-index-packs/llama-index-packs-secgpt/README.md
  llama-index-packs/llama-index-packs-secgpt/examples/SecGPT.ipynb
Labels: lgtm, size:M

#14160 [version] bump version to 0.10.45
  CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-llama-cpp/pyproject.toml
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-postgres/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
  pyproject.toml
Labels: size:L

#14162 fix for batch_gather
  llama-index-core/llama_index/core/async_utils.py
  llama-index-core/tests/test_async_utils.py
Labels: lgtm, size:S

#14153 feat: support VectorStoreQueryMode.TEXT_SEARCH on OpenSearch VectorStore
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
Labels: lgtm, size:M

#14088 Enable Function calling and agent runner for Vertex AI
  docs/docs/examples/agent/agentic_rag_using_vertex_ai.ipynb
  llama-index-core/llama_index/core/utilities/gemini_utils.py
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/gemini_utils.py
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/utils.py
  llama-index-integrations/llms/llama-index-llms-vertex/pyproject.toml
Labels: size:XXL

#14166 Add missing @llm_chat_callback() to Gemini.stream_chat
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
Labels: lgtm, size:XS

#14172 docs: nim model name change
  docs/docs/examples/llm/nvidia.ipynb
  docs/docs/examples/llm/nvidia_nim.ipynb
Labels: lgtm, size:XS

#14170 [Core][Retrieval] Add precision and recall metrics
  docs/docs/examples/evaluation/retrieval/retriever_eval.ipynb
  llama-index-core/llama_index/core/evaluation/retrieval/metrics.py
  llama-index-core/tests/evaluation/test_metrics.py
Labels: lgtm, size:L

#14015 Changing BM25Retriever _retrieve to use numpy methods
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/llama_index/retrievers/bm25/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/pyproject.toml
Labels: lgtm, size:S

#14176 Restore Nomic Embed einops dependency
  llama-index-integrations/embeddings/llama-index-embeddings-nomic/pyproject.toml
Labels: lgtm, size:XS

#14177 Fixes a bug where there is a missing await.
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-azure/llama_index/storage/kvstore/azure/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-azure/pyproject.toml
Labels: lgtm, size:S

#13934 add news retriever
  docs/docs/examples/retrievers/you_retriever.ipynb
  llama-index-integrations/retrievers/llama-index-retrievers-you/llama_index/retrievers/you/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-you/pyproject.toml
Labels: lgtm, size:L

#14194 add support for nvidia/nv-embed-v1 (https://huggingface.co/nvidia/NV-Embed-v1)
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
Labels: lgtm, size:S

#14188 Bump core version in main package
  poetry.lock
  pyproject.toml
Labels: lgtm, size:XS

#14196 Use typical include llama_index/
  llama-index-utils/llama-index-utils-azure/pyproject.toml
Labels: size:XS

#14198 [version] vbump to v0.10.45post1
  pyproject.toml
Labels: size:XS

#14197 fix: :bug: Fix Bedrock Converse' `pyproject.toml` for the PyPI release
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: lgtm, size:XS

#14199 Update MistralAI
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/utils.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-mistralai/tests/BUILD
Labels: lgtm, size:S

#14204 Remove sentence-transformers dependency from HuggingFace utils package
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-api/pyproject.toml
  llama-index-utils/llama-index-utils-huggingface/pyproject.toml
Labels: lgtm, size:XS

#14206 fix docs build
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/ibm.md
  docs/docs/api_reference/llms/bedrock_converse.md
  docs/docs/api_reference/llms/ibm.md
  docs/docs/api_reference/readers/file.md
  docs/mkdocs.yml
Labels: lgtm, size:L

#14203 [FIX] Pin tenacity and numpy in core
  .github/workflows/unit_test.yml
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
Labels: size:XS

#14208 [version] bump to v0.10.46
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/huggingface.md
  docs/docs/api_reference/llms/huggingface.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#13415 Integrations: Upstage Layout Analysis Reader
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/poetry.lock
  llama-index-integrations/llms/llama-index-llms-upstage/poetry.lock
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/__init__.py
  llama-index-integrations/readers/llama-index-readers-upstage/.gitignore
  llama-index-integrations/readers/llama-index-readers-upstage/BUILD
  llama-index-integrations/readers/llama-index-readers-upstage/Makefile
  llama-index-integrations/readers/llama-index-readers-upstage/README.md
  llama-index-integrations/readers/llama-index-readers-upstage/examples/upstage.ipynb
  llama-index-integrations/readers/llama-index-readers-upstage/llama_index/readers/upstage/BUILD
  llama-index-integrations/readers/llama-index-readers-upstage/llama_index/readers/upstage/__init__.py
  llama-index-integrations/readers/llama-index-readers-upstage/llama_index/readers/upstage/base.py
  llama-index-integrations/readers/llama-index-readers-upstage/poetry.lock
  llama-index-integrations/readers/llama-index-readers-upstage/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-upstage/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-upstage/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-upstage/tests/test_readers_upstage.py
Labels: lgtm, size:XL

#14095 Add default node property to neo4j upsert relations
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: lgtm, size:XS

#14077 LanceDB: code cleanup, minor updates
  docs/docs/examples/vector_stores/LanceDBIndexDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/llama_index/vector_stores/lancedb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/tests/BUILD
Labels: lgtm, size:L

#14054 Added helper args to generate_qa_pairs
  llama-index-finetuning/llama_index/finetuning/embeddings/common.py
  llama-index-finetuning/pyproject.toml
Labels: lgtm, size:L

#14104 added method visualizing graph_store in jupyter notebooks
  docs/docs/examples/property_graph/jupyter_screenshot.png
  docs/docs/examples/property_graph/property_graph_basic_visualization.ipynb
  llama-index-core/llama_index/core/graph_stores/simple_labelled.py
Labels: lgtm, size:L

#14040 Correcting the behaviour of the constructor of llama_index.core.utils.GlobalsHelper
  llama-index-core/llama_index/core/utils.py
Labels: lgtm, size:XS

#14213 Logan/vbump issues
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-text-embeddings-inference/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-dashscope/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
Labels: size:S

#14105 Prem AI Templates Llama Index support
  docs/docs/examples/llm/premai.ipynb
  llama-index-integrations/llms/llama-index-llms-premai/llama_index/llms/premai/base.py
  llama-index-integrations/llms/llama-index-llms-premai/llama_index/llms/premai/utils.py
  llama-index-integrations/llms/llama-index-llms-premai/pyproject.toml
Labels: lgtm, size:L

#14217 Fix wrong calculation of average precision
  docs/docs/examples/evaluation/retrieval/retriever_eval.ipynb
  llama-index-core/llama_index/core/evaluation/retrieval/metrics.py
  llama-index-core/tests/evaluation/test_metrics.py
Labels: lgtm, size:M

#14127 Feat/deepinfra function calling
  llama-index-integrations/llms/llama-index-llms-deepinfra/llama_index/llms/deepinfra/base.py
  llama-index-integrations/llms/llama-index-llms-deepinfra/llama_index/llms/deepinfra/client.py
  llama-index-integrations/llms/llama-index-llms-deepinfra/llama_index/llms/deepinfra/constants.py
  llama-index-integrations/llms/llama-index-llms-deepinfra/llama_index/llms/deepinfra/types.py
  llama-index-integrations/llms/llama-index-llms-deepinfra/llama_index/llms/deepinfra/utils.py
  llama-index-integrations/llms/llama-index-llms-deepinfra/pyproject.toml
Labels: lgtm, size:L

#14134 Added re-ranking into the PostgresML Managed Index
  docs/docs/examples/managed/PostgresMLDemo.ipynb
  llama-index-integrations/indices/llama-index-indices-managed-postgresml/llama_index/indices/managed/postgresml/query.py
  llama-index-integrations/indices/llama-index-indices-managed-postgresml/llama_index/indices/managed/postgresml/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-postgresml/pyproject.toml
Labels: lgtm, size:L

#14193 Integration: Async AI21 Client
  docs/docs/examples/llm/ai21.ipynb
  llama-index-integrations/llms/llama-index-llms-ai21/README.md
  llama-index-integrations/llms/llama-index-llms-ai21/llama_index/llms/ai21/base.py
  llama-index-integrations/llms/llama-index-llms-ai21/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ai21/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-ai21/tests/test_llms_ai21.py
Labels: lgtm, size:L

#14117 enable stepwise execution of query pipelines
  docs/docs/examples/pipeline/query_pipeline.ipynb
  llama-index-core/llama_index/core/async_utils.py
  llama-index-core/llama_index/core/query_pipeline/query.py
Labels: lgtm, size:L

#14229 add confluence auth constructor args
  llama-index-integrations/readers/llama-index-readers-confluence/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-confluence/llama_index/readers/confluence/base.py
  llama-index-integrations/readers/llama-index-readers-confluence/pyproject.toml
Labels: lgtm, size:S

#14245 feat: Add metadata field "collection_name" to SimpleMongoReader
  llama-index-integrations/readers/llama-index-readers-mongodb/llama_index/readers/mongodb/base.py
  llama-index-integrations/readers/llama-index-readers-mongodb/pyproject.toml
Labels: lgtm, size:XS

#14207 community(you): Integrate You.com conversational APIs
  llama-index-integrations/llms/llama-index-llms-you/.gitignore
  llama-index-integrations/llms/llama-index-llms-you/BUILD
  llama-index-integrations/llms/llama-index-llms-you/Makefile
  llama-index-integrations/llms/llama-index-llms-you/README.md
  llama-index-integrations/llms/llama-index-llms-you/llama_index/llms/you/BUILD
  llama-index-integrations/llms/llama-index-llms-you/llama_index/llms/you/__init__.py
  llama-index-integrations/llms/llama-index-llms-you/llama_index/llms/you/base.py
  llama-index-integrations/llms/llama-index-llms-you/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-you/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-you/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-you/tests/test_llms_you.py
Labels: lgtm, size:L

#14248 Add notebook for Georgian Partners talk
  docs/docs/presentations/materials/2024-06-19-georgian-genai-bootcamp.ipynb
  docs/docs/presentations/past_presentations.md
Labels: size:XXL

#14246 Resolve dependabot issues
  docs/poetry.lock
  llama-index-core/poetry.lock
  llama-index-networks/poetry.lock
  llama-index-packs/llama-index-packs-diff-private-simple-dataset/poetry.lock
  llama-index-packs/llama-index-packs-koda-retriever/poetry.lock
  llama-index-packs/llama-index-packs-vanna/BUILD
  llama-index-packs/llama-index-packs-vanna/pyproject.toml
  llama-index-packs/llama-index-packs-vanna/requirements.txt
  poetry.lock
Labels: size:XS

#14131 Documentation update for IBM watsonx.ai
  docs/docs/api_reference/embeddings/ibm_watsonx.md
  docs/docs/api_reference/llms/ibm_watsonx.md
  docs/docs/api_reference/readers/upstage.md
  docs/docs/examples/embeddings/ibm_watsonx.ipynb
  docs/docs/examples/llm/ibm_watsonx.ipynb
  docs/mkdocs.yml
  docs/prepare_for_build.py
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/README.md
  llama-index-integrations/llms/llama-index-llms-ibm/README.md
Labels: lgtm, size:XL

#14161 feat: add mixedbread ai integration
  docs/docs/examples/embeddings/mixedbreadai.ipynb
  docs/docs/examples/node_postprocessor/MixedbreadAIRerank.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/llama_index/embeddings/mixedbreadai/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/llama_index/embeddings/mixedbreadai/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/llama_index/embeddings/mixedbreadai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/tests/test_embeddings_mixedbreadai.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-mixedbreadai-rerank/.gitignore
  llama-index-integrations/postprocessor/llama-index-postprocessor-mixedbreadai-rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-mixedbreadai-rerank/Makefile
  llama-index-integrations/postprocessor/llama-index-postprocessor-mixedbreadai-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-mixedbreadai-rerank/llama_index/postprocessor/mixedbreadai_rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-mixedbreadai-rerank/llama_index/postprocessor/mixedbreadai_rerank/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-mixedbreadai-rerank/llama_index/postprocessor/mixedbreadai_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-mixedbreadai-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-mixedbreadai-rerank/tests/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-mixedbreadai-rerank/tests/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-mixedbreadai-rerank/tests/test_postprocessor_mixedbreadai_rerank.py
Labels: lgtm, size:XXL

#14214 [Community] Enable selecting Intel GPU for `ipex-llm` integrations
  docs/docs/examples/embeddings/ipex_llm_gpu.ipynb
  docs/docs/examples/llm/ipex_llm_gpu.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/examples/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/examples/basic.py
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/llama_index/embeddings/ipex_llm/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ipex-llm/examples/README.md
  llama-index-integrations/llms/llama-index-llms-ipex-llm/examples/basic.py
  llama-index-integrations/llms/llama-index-llms-ipex-llm/examples/low_bit.py
  llama-index-integrations/llms/llama-index-llms-ipex-llm/examples/more_data_type.py
  llama-index-integrations/llms/llama-index-llms-ipex-llm/llama_index/llms/ipex_llm/base.py
  llama-index-integrations/llms/llama-index-llms-ipex-llm/pyproject.toml
Labels: lgtm, size:M

#14230 Fix DuckDBVectorStore
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/llama_index/vector_stores/duckdb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/tests/test_duckdb.py
Labels: lgtm, size:M

#14244 do not overwrite relations in graph
  llama-index-core/llama_index/core/graph_stores/types.py
Labels: size:M

#14169 Fix NLSQLTableQueryEngine response metadata
  llama-index-core/llama_index/core/indices/struct_store/sql_retriever.py
Labels: lgtm, size:S

#14249 chore: add option to customize default OpenSearch Client and Engine
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
Labels: lgtm, size:S

#14241 fix: :bug: Call sync methods while async isn't implemented for `BedrockConverse`
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: lgtm, size:M

#14218 Replace tenacity upper limit by only rejecting 8.4.0
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
Labels: lgtm, size:XS

#14242 fix issue 14240 incorrect casting to str of text nodes in sql retreiver
  llama-index-core/llama_index/core/base/query_pipeline/query.py
Labels: lgtm, size:XS

#14250 assign single input to root input
  llama-index-core/llama_index/core/query_pipeline/query.py
Labels: lgtm, size:XS

#14099 feat: add marker-pdf reader
  llama-index-integrations/readers/llama-index-readers-pdf-marker/.gitignore
  llama-index-integrations/readers/llama-index-readers-pdf-marker/BUILD
  llama-index-integrations/readers/llama-index-readers-pdf-marker/LICENSE
  llama-index-integrations/readers/llama-index-readers-pdf-marker/Makefile
  llama-index-integrations/readers/llama-index-readers-pdf-marker/README.md
  llama-index-integrations/readers/llama-index-readers-pdf-marker/llama_index/readers/pdf_marker/BUILD
  llama-index-integrations/readers/llama-index-readers-pdf-marker/llama_index/readers/pdf_marker/__init__.py
  llama-index-integrations/readers/llama-index-readers-pdf-marker/llama_index/readers/pdf_marker/base.py
  llama-index-integrations/readers/llama-index-readers-pdf-marker/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-pdf-marker/requirements.txt
Labels: lgtm, size:L

#14253 propagate error_on_no_tool_call kwarg
  llama-index-core/llama_index/core/llms/function_calling.py
Labels: size:S

#14256 nit fix: mistralai finetuning cookbook
  docs/docs/examples/finetuning/mistralai_fine_tuning.ipynb
Labels: size:XS

#14260 [Core][Retrieval] Improve efficiency of average precision
  llama-index-core/llama_index/core/evaluation/retrieval/metrics.py
Labels: lgtm, size:S

#14277 Add support for claude 3.5
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: lgtm, size:XS

#14266 add crewai + llamaindex cookbook
  docs/docs/examples/cookbooks/crewai_llamaindex.ipynb
Labels: size:XL

#14268 Update readme for MoA LlamaPack
  llama-index-packs/llama-index-packs-mixture-of-agents/README.md
  llama-index-packs/llama-index-packs-mixture-of-agents/pyproject.toml
Labels: lgtm, size:S

#14279 feat(schema): Add mimetype field to TextNode
  llama-index-core/llama_index/core/schema.py
Labels: lgtm, size:XS

#14271 Improve IBM watsonx.ai docs
  docs/docs/api_reference/embeddings/ibm.md
  docs/docs/api_reference/llms/ibm.md
  docs/docs/examples/llm/watsonx.ipynb
  docs/mkdocs.yml
Labels: lgtm, size:L

#14264 fix: documentation where parameters in load_index_from_storage function call were invalid
  docs/docs/examples/docstore/MongoDocstoreDemo.ipynb
Labels: lgtm, size:XS

#14292 Fixed issue #14178: Removed the broken link from docs.
  docs/mkdocs.yml
Labels: lgtm, size:XS

#14303 v0.10.48
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/packs/mixture_of_agents.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/llama_index/embeddings/ibm/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/llama_index/embeddings/ibm/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/llama_index/embeddings/ibm/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/llama_index/embeddings/ibm/utils.py
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/tests/test_embeddings_ibm.py
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/tests/test_ibm.py
  llama-index-integrations/llms/llama-index-llms-ibm/.gitignore
  llama-index-integrations/llms/llama-index-llms-ibm/BUILD
  llama-index-integrations/llms/llama-index-llms-ibm/Makefile
  llama-index-integrations/llms/llama-index-llms-ibm/README.md
  llama-index-integrations/llms/llama-index-llms-ibm/llama_index/llms/ibm/BUILD
  llama-index-integrations/llms/llama-index-llms-ibm/llama_index/llms/ibm/__init__.py
  llama-index-integrations/llms/llama-index-llms-ibm/llama_index/llms/ibm/base.py
  llama-index-integrations/llms/llama-index-llms-ibm/llama_index/llms/ibm/utils.py
  llama-index-integrations/llms/llama-index-llms-ibm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ibm/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-ibm/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-ibm/tests/test_ibm.py
  llama-index-integrations/llms/llama-index-llms-ibm/tests/test_llms_ibm.py
  poetry.lock
  pyproject.toml
Labels: size:XXL
