Repository run-llama/llama_index, pull requests merged in 2024-05, with the labels that each got.

#13109 add matching source_node.node_id verification
  llama-index-core/llama_index/core/node_parser/interface.py
Labels: lgtm, size:S

#13199 parameterize queries in pgvector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: size:M

#13197 add note on text-to-sql usage
  docs/docs/examples/agent/agent_runner/query_pipeline_agent.ipynb
  docs/docs/examples/agent/custom_agent.ipynb
  docs/docs/examples/agent/openai_agent_query_cookbook.ipynb
  docs/docs/examples/agent/openai_assistant_query_cookbook.ipynb
  docs/docs/examples/benchmarks/phi-3-mini-4k-instruct.ipynb
  docs/docs/examples/finetuning/gradient/gradient_text2sql.ipynb
  docs/docs/examples/index_structs/struct_indices/SQLIndexDemo.ipynb
  docs/docs/examples/index_structs/struct_indices/duckdb_sql_query.ipynb
  docs/docs/examples/pipeline/query_pipeline_sql.ipynb
  docs/docs/examples/query_engine/SQLAutoVectorQueryEngine.ipynb
  docs/docs/examples/query_engine/SQLJoinQueryEngine.ipynb
  docs/docs/examples/query_engine/SQLRouterQueryEngine.ipynb
  docs/docs/examples/query_engine/pgvector_sql_query_engine.ipynb
  docs/docs/understanding/putting_it_all_together/structured_data.md
  llama-index-core/llama_index/core/indices/struct_store/sql_query.py
Labels: size:L

#12048 Adding Firestore Vector Store
  docs/docs/examples/vector_stores/FirestoreVectorStore.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-firestore/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-firestore/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-firestore/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-firestore/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-firestore/llama_index/vector_stores/firestore/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-firestore/llama_index/vector_stores/firestore/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-firestore/llama_index/vector_stores/firestore/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-firestore/llama_index/vector_stores/firestore/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-firestore/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-firestore/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-firestore/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-firestore/tests/test_firestore.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-firestore/tests/test_utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-firestore/tests/test_vector_store_firestore.py
Labels: lgtm, size:XL

#13206 Logan/postgres fix v 2
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: size:XS

#12997 Retrieval Metrics: Updating HitRate and MRR for Evaluation@K documents retrieved. Also adding RR as a separate metric
  llama-index-core/llama_index/core/evaluation/retrieval/metrics.py
  llama-index-core/tests/evaluation/test_rr_mrr_hitrate.py
Labels: lgtm, size:L

#12471 Add tool usage support with text-generation-inference integration from Hugging Face
  docs/docs/examples/llm/huggingface.ipynb
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/__init__.py
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/utils.py
  llama-index-integrations/llms/llama-index-llms-huggingface/pyproject.toml
Labels: lgtm, size:XL

#13201 fix redis kvstore key that was in bytes
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-redis/llama_index/storage/kvstore/redis/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-redis/pyproject.toml
Labels: size:XS

#12975 Added YouTube Metadata Reader
  llama-index-integrations/readers/llama-index-readers-youtube-metadata/.gitignore
  llama-index-integrations/readers/llama-index-readers-youtube-metadata/.pre-commit-config.yaml
  llama-index-integrations/readers/llama-index-readers-youtube-metadata/BUILD
  llama-index-integrations/readers/llama-index-readers-youtube-metadata/Makefile
  llama-index-integrations/readers/llama-index-readers-youtube-metadata/README.md
  llama-index-integrations/readers/llama-index-readers-youtube-metadata/llama_index/readers/youtube_metadata/BUILD
  llama-index-integrations/readers/llama-index-readers-youtube-metadata/llama_index/readers/youtube_metadata/__init__.py
  llama-index-integrations/readers/llama-index-readers-youtube-metadata/llama_index/readers/youtube_metadata/base.py
  llama-index-integrations/readers/llama-index-readers-youtube-metadata/pants
  llama-index-integrations/readers/llama-index-readers-youtube-metadata/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-youtube-metadata/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-youtube-metadata/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-youtube-metadata/tests/test_readers_youtube_metadata.py
Labels: lgtm, size:XL

#12877 feat: Browserbase Web Reader
  docs/docs/examples/data_connectors/WebPageDemo.ipynb
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/__init__.py
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/browserbase_web/BUILD
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/browserbase_web/README.md
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/browserbase_web/__init__.py
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/browserbase_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/browserbase_web/requirements.txt
Labels: lgtm, size:L

#13155 Add chat summary memory buffer
  docs/docs/examples/memory/ChatSummaryMemoryBuffer.ipynb
  llama-index-core/llama_index/core/memory/__init__.py
  llama-index-core/llama_index/core/memory/chat_summary_memory_buffer.py
  llama-index-core/tests/memory/test_chat_memory_buffer.py
  llama-index-core/tests/memory/test_chat_summary_memory_buffer.py
Labels: lgtm, size:XL

#13123 Support passing sqlalchemy.URL for connection string in Postgres
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
Labels: lgtm, size:S

#13105 Integrate mistral.rs LLM
  llama-index-integrations/llms/llama-index-llms-mistral-rs/.gitignore
  llama-index-integrations/llms/llama-index-llms-mistral-rs/BUILD
  llama-index-integrations/llms/llama-index-llms-mistral-rs/Makefile
  llama-index-integrations/llms/llama-index-llms-mistral-rs/README.md
  llama-index-integrations/llms/llama-index-llms-mistral-rs/examples/plain.ipynb
  llama-index-integrations/llms/llama-index-llms-mistral-rs/examples/streaming.ipynb
  llama-index-integrations/llms/llama-index-llms-mistral-rs/examples/xlora_gguf.ipynb
  llama-index-integrations/llms/llama-index-llms-mistral-rs/llama_index/llms/mistral_rs/BUILD
  llama-index-integrations/llms/llama-index-llms-mistral-rs/llama_index/llms/mistral_rs/__init__.py
  llama-index-integrations/llms/llama-index-llms-mistral-rs/llama_index/llms/mistral_rs/base.py
  llama-index-integrations/llms/llama-index-llms-mistral-rs/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-mistral-rs/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-mistral-rs/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-mistral-rs/tests/test_llms_mistral-rs.py
Labels: lgtm, size:XL

#13122 Add hybrid retrieval mode to MilvusVectorStore.
  docs/docs/examples/vector_stores/MilvusHybridIndexDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/tests/BUILD
Labels: lgtm, size:XL

#13228 update base class for planner agent
  docs/docs/examples/agent/structured_planner.ipynb
  llama-index-core/llama_index/core/agent/runner/base.py
  llama-index-core/llama_index/core/agent/runner/parallel.py
  llama-index-core/llama_index/core/agent/runner/planner.py
  llama-index-core/tests/agent/runner/test_planner.py
Labels: lgtm, size:XXL

#13207 [Community] Add streaming for maritalk
  docs/docs/examples/llm/maritalk.ipynb
  llama-index-integrations/llms/llama-index-llms-maritalk/README.md
  llama-index-integrations/llms/llama-index-llms-maritalk/llama_index/llms/maritalk/base.py
  llama-index-integrations/llms/llama-index-llms-maritalk/pyproject.toml
Labels: lgtm, size:L

#13215 fix: Respect filter condition for Azure AI Search
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
Labels: lgtm, size:XS

#13234 docs: add tips of installing integrations
  docs/docs/getting_started/starter_example_local.md
Labels: lgtm, size:S

#13235 v0.10.34
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/llms/mistral_rs.md
  docs/docs/api_reference/readers/pinecone.md
  docs/docs/api_reference/readers/youtube_metadata.md
  docs/docs/api_reference/storage/vector_store/firestore.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-youtube-metadata/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:L

#13108 Add CRITIC agent integration
  docs/docs/examples/agent/introspective_agent_toxicity_reduction.ipynb
  docs/docs/module_guides/deploying/agents/modules.md
  docs/mkdocs.yml
  llama-index-integrations/agent/llama-index-agent-introspective/.gitignore
  llama-index-integrations/agent/llama-index-agent-introspective/BUILD
  llama-index-integrations/agent/llama-index-agent-introspective/Makefile
  llama-index-integrations/agent/llama-index-agent-introspective/README.md
  llama-index-integrations/agent/llama-index-agent-introspective/examples/toxicity_reduction.ipynb
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/BUILD
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/__init__.py
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/reflective/BUILD
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/reflective/__init__.py
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/reflective/self_reflection.py
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/reflective/tool_interactive_reflection.py
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/step.py
  llama-index-integrations/agent/llama-index-agent-introspective/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-introspective/tests/BUILD
  llama-index-integrations/agent/llama-index-agent-introspective/tests/__init__.py
  llama-index-integrations/agent/llama-index-agent-introspective/tests/test_agent_critic.py
Labels: size:XXL

#13236 chore: fix link to example notebook for introspective agent
  llama-index-integrations/agent/llama-index-agent-introspective/README.md
Labels: size:XS

#13248 fix import for web readers
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/__init__.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: size:XS

#13247 fix: AzStorageBlobReader (#13246)
  llama-index-integrations/readers/llama-index-readers-azstorage-blob/llama_index/readers/azstorage_blob/base.py
  llama-index-integrations/readers/llama-index-readers-azstorage-blob/pyproject.toml
Labels: lgtm, size:XS

#13242 fix(docs): langfuse API reference page
  docs/docs/api_reference/callbacks/langfuse.md
Labels: lgtm, size:XS

#13245 Argilla Callback Handler README updated
  llama-index-integrations/callbacks/llama-index-callbacks-argilla/README.md
  llama-index-integrations/callbacks/llama-index-callbacks-argilla/pyproject.toml
Labels: lgtm, size:M

#13238 Fix log message for retrieved nodes count in chromadb
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/llama_index/vector_stores/chroma/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/pyproject.toml
  llama-index-legacy/llama_index/legacy/vector_stores/chroma.py
Labels: lgtm, size:XS

#13250 add mistralrs example to docs
  docs/docs/api_reference/agent/introspective.md
  docs/docs/examples/llm/mistral_rs.ipynb
  docs/mkdocs.yml
Labels: size:L

#13178 add nvidia nim rerank support
  docs/docs/examples/node_postprocessor/NVIDIARerank.ipynb
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/__pycache__/__init__.cpython-311.pyc
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/__pycache__/base.cpython-311.pyc
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/__pycache__/retriever.cpython-311.pyc
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/.gitignore
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/Makefile
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/conftest.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_api_key.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_available_models.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_mode_switch.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_postprocessor_nvidia_rerank.py
Labels: lgtm, size:XL

#13186 Add support for Vertex AI Vector Search as Vector Store
  docs/docs/examples/vector_stores/VertexAIVectorSearchDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-vertexaivectorsearch/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-vertexaivectorsearch/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-vertexaivectorsearch/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-vertexaivectorsearch/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-vertexaivectorsearch/llama_index/vector_stores/vertexaivectorsearch/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-vertexaivectorsearch/llama_index/vector_stores/vertexaivectorsearch/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-vertexaivectorsearch/llama_index/vector_stores/vertexaivectorsearch/_sdk_manager.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-vertexaivectorsearch/llama_index/vector_stores/vertexaivectorsearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-vertexaivectorsearch/llama_index/vector_stores/vertexaivectorsearch/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-vertexaivectorsearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-vertexaivectorsearch/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-vertexaivectorsearch/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-vertexaivectorsearch/tests/test_vector_stores_vertexaivectorsearch.py
Labels: lgtm, size:XXL

#13177 add nvidia nim embeddings support
  docs/docs/examples/embeddings/nvidia.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/conftest.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_api_key.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_available_models.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_embeddings_nvidia.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_mode_switch.py
Labels: lgtm, size:XXL

#13172 feat: add encoding_type parameters in JinaEmbedding class
  llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-jinaai/pyproject.toml
Labels: lgtm, size:M

#13252 FIX: `is_done` undefined error with ToolInteractiveReflectionAgent + Unit tests
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/reflective/self_reflection.py
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/reflective/tool_interactive_reflection.py
  llama-index-integrations/agent/llama-index-agent-introspective/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-introspective/tests/test_agent_classes.py
  llama-index-integrations/agent/llama-index-agent-introspective/tests/test_introspective.py
  llama-index-integrations/agent/llama-index-agent-introspective/tests/test_self_reflection.py
  llama-index-integrations/agent/llama-index-agent-introspective/tests/test_tool_interactive_reflection.py
Labels: lgtm, size:L

#13270 chore: remove errors from example
  docs/docs/module_guides/models/embeddings.md
Labels: lgtm, size:XS

#13254 [docs] Add Vertex AI Vector Search to the Vector Store documentation …
  docs/docs/community/integrations/vector_stores.md
  docs/docs/module_guides/storing/vector_stores.md
Labels: lgtm, size:S

#13262 Fix bedrock notebook retrieve call and add llamahub doc improvement
  docs/docs/examples/retrievers/bedrock_retriever.ipynb
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/README.md
Labels: lgtm, size:M

#13213 Add VectorStore integration for Vespa
  docs/docs/examples/vector_stores/VespaIndexDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-vespa/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-vespa/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-vespa/CHANGELOG.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-vespa/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-vespa/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-vespa/llama_index/vector_stores/vespa/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-vespa/llama_index/vector_stores/vespa/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-vespa/llama_index/vector_stores/vespa/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-vespa/llama_index/vector_stores/vespa/templates.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-vespa/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-vespa/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-vespa/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-vespa/tests/test_vespavectorstore.py
Labels: lgtm, size:XXL

#13267 fix: azure openai api key not picking up env var
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/llama_index/embeddings/azure_openai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/tests/test_azure_openai.py
  llama-index-integrations/llms/llama-index-llms-azure-openai/llama_index/llms/azure_openai/base.py
  llama-index-integrations/llms/llama-index-llms-azure-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-azure-openai/tests/test_azure_openai.py
Labels: lgtm, size:S

#13273 docstring typo
  llama-index-packs/llama-index-packs-tables/llama_index/packs/tables/chain_of_table/base.py
Labels: lgtm, size:XS

#13275 Fix the import of Pydantic
  llama-index-packs/llama-index-packs-resume-screener/llama_index/packs/resume_screener/base.py
Labels: lgtm, size:XS

#13292 Fix async issue when streaming with Mistral AI
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/base.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
Labels: lgtm, size:XS

#13285 Fix incorrect link in the docs/use_cases/agents.md
  docs/docs/use_cases/agents.md
Labels: lgtm, size:XS

#13281 Handle llm properly for QASummaryQueryEngineBuilder and RouterQueryEngine
  llama-index-core/llama_index/core/composability/joint_qa_summary.py
  llama-index-core/llama_index/core/query_engine/router_query_engine.py
Labels: lgtm, size:XS

#13277 Fix Bug in sql join statement
  llama-index-core/llama_index/core/utilities/sql_wrapper.py
Labels: lgtm, size:XS

#13282 Update Milvus hybrid retrieval information in related documentations.
  docs/docs/community/integrations/vector_stores.md
  docs/docs/module_guides/storing/vector_stores.md
  docs/docs/optimizing/advanced_retrieval/advanced_retrieval.md
  docs/docs/optimizing/basic_strategies/basic_strategies.md
Labels: lgtm, size:XS

#13300 Fixed spelling
  docs/docs/module_guides/deploying/agents/modules.md
Labels: lgtm, size:XS

#13301 Bump version
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:XS

#13302 expand instrumentation payloads
  docs/docs/examples/instrumentation/instrumentation_observability_rundown.ipynb
  docs/docs/module_guides/observability/index.md
  docs/docs/module_guides/observability/instrumentation.md
  llama-index-core/llama_index/core/agent/react/step.py
  llama-index-core/llama_index/core/agent/runner/base.py
  llama-index-core/llama_index/core/agent/runner/planner.py
  llama-index-core/llama_index/core/agent/types.py
  llama-index-core/llama_index/core/base/agent/BUILD
  llama-index-core/llama_index/core/base/agent/__init__.py
  llama-index-core/llama_index/core/base/agent/types.py
  llama-index-core/llama_index/core/base/base_query_engine.py
  llama-index-core/llama_index/core/base/embeddings/base.py
  llama-index-core/llama_index/core/chat_engine/types.py
  llama-index-core/llama_index/core/instrumentation/events/agent.py
  llama-index-core/llama_index/core/instrumentation/events/chat_engine.py
  llama-index-core/llama_index/core/instrumentation/events/embedding.py
  llama-index-core/llama_index/core/instrumentation/events/llm.py
  llama-index-core/llama_index/core/instrumentation/events/query.py
  llama-index-core/llama_index/core/instrumentation/events/rerank.py
  llama-index-core/llama_index/core/instrumentation/events/retrieval.py
  llama-index-core/llama_index/core/instrumentation/events/span.py
  llama-index-core/llama_index/core/instrumentation/events/synthesis.py
  llama-index-core/llama_index/core/llms/callbacks.py
  llama-index-core/llama_index/core/llms/llm.py
  llama-index-core/llama_index/core/response_synthesizers/refine.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-cohere-rerank/llama_index/postprocessor/cohere_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-colbert-rerank/llama_index/postprocessor/colbert_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-flag-embedding-reranker/llama_index/postprocessor/flag_embedding_reranker/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-jinaai-rerank/llama_index/postprocessor/jinaai_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/llama_index/postprocessor/openvino_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankgpt-rerank/llama_index/postprocessor/rankgpt_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/llama_index/postprocessor/rankllm_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-sbert-rerank/llama_index/postprocessor/sbert_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-voyageai-rerank/llama_index/postprocessor/voyageai_rerank/base.py
Labels: lgtm, size:XXL

#13321 Remove Global Logging Config from All Production Files
  llama-index-integrations/readers/llama-index-readers-openalex/llama_index/readers/openalex/base.py
  llama-index-integrations/readers/llama-index-readers-openalex/pyproject.toml
  llama-index-packs/llama-index-packs-raft-dataset/llama_index/packs/raft_dataset/base.py
  llama-index-packs/llama-index-packs-raft-dataset/pyproject.toml
Labels: lgtm, size:S

#13315 fix: fix encoding type access in JinaEmbeddings
  llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-jinaai/pyproject.toml
Labels: lgtm, size:M

#13327 Update MarkdownReader to parse text before first header
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/markdown/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-file/tests/test_markdown.py
Labels: lgtm, size:L

#13309 Fix asyncio.run() in async context.
  llama-index-core/llama_index/core/agent/react/step.py
  llama-index-core/llama_index/core/agent/runner/base.py
  llama-index-core/llama_index/core/agent/runner/parallel.py
  llama-index-core/llama_index/core/async_utils.py
  llama-index-core/llama_index/core/base/response/schema.py
  llama-index-core/llama_index/core/chat_engine/condense_plus_context.py
  llama-index-core/llama_index/core/chat_engine/context.py
  llama-index-core/llama_index/core/chat_engine/simple.py
  llama-index-core/llama_index/core/evaluation/base.py
  llama-index-core/llama_index/core/evaluation/batch_runner.py
  llama-index-core/llama_index/core/evaluation/dataset_generation.py
  llama-index-core/llama_index/core/evaluation/eval_utils.py
  llama-index-core/llama_index/core/evaluation/retrieval/base.py
  llama-index-core/llama_index/core/extractors/interface.py
  llama-index-core/llama_index/core/llama_dataset/generator.py
  llama-index-core/llama_index/core/node_parser/relational/base_element.py
  llama-index-core/tests/indices/query/test_compose_vector.py
  llama-index-core/tests/indices/response/test_response_builder.py
  llama-index-core/tests/indices/struct_store/test_json_query.py
  llama-index-core/tests/indices/struct_store/test_sql_query.py
Labels: size:L

#13345 v0.10.35
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/nvidia.md
  docs/docs/api_reference/llms/nvidia.md
  docs/docs/api_reference/postprocessor/nvidia_rerank.md
  docs/docs/api_reference/readers/web.md
  docs/docs/api_reference/storage/vector_store/vertexaivectorsearch.md
  docs/docs/api_reference/storage/vector_store/vespa.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-openai-legacy/llama_index/agent/openai_legacy/openai_agent.py
  llama-index-integrations/agent/llama-index-agent-openai-legacy/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/step.py
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
  llama-index-packs/llama-index-packs-cohere-citation-chat/llama_index/packs/cohere_citation_chat/citations_context_chat_engine.py
  llama-index-packs/llama-index-packs-cohere-citation-chat/pyproject.toml
  llama-index-packs/llama-index-packs-resume-screener/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:L

#13349 patch async utils
  llama-index-core/llama_index/core/async_utils.py
  llama-index-core/pyproject.toml
Labels: size:S

#13346 Fix docs: replace borken notion links
  README.md
  docs/docs/getting_started/installation.md
  docs/docs/module_guides/indexing/llama_cloud_index.md
  docs/docs/module_guides/loading/connector/llama_parse.md
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/README.md
  llama-index-integrations/readers/llama-index-readers-llama-parse/README.md
Labels: lgtm, size:S

#13337 feature: add missing openai model token context
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
Labels: lgtm, size:XS

#13336 Fix add llama-3 models to Anyscale class
  llama-index-integrations/llms/llama-index-llms-anyscale/llama_index/llms/anyscale/utils.py
  llama-index-integrations/llms/llama-index-llms-anyscale/pyproject.toml
Labels: lgtm, size:XS

#13326 Add Vespa Vector Store to module guide
  docs/docs/module_guides/storing/vector_stores.md
Labels: size:XS

#13367 fix truncate passing for aget_query_embedding and get_text_embedding_batch
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_truncate.py
Labels: lgtm, size:M

#13351 Fix hidden temp directory issue for arxiv reader
  llama-index-integrations/readers/llama-index-readers-papers/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-papers/llama_index/readers/papers/arxiv/base.py
  llama-index-integrations/readers/llama-index-readers-papers/pyproject.toml
Labels: lgtm, size:S

#13371 set default max_tokens to 1024
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/base.py
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
Labels: lgtm, size:XS

#13329 feat: add attribution tag for pinecone
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/llama_index/vector_stores/pinecone/base.py
  llama-index-legacy/llama_index/legacy/vector_stores/pinecone.py
Labels: lgtm, size:M

#13366 Add ``fail_on_http_error`` arg to github repository reader.
  docs/BUILD
  llama-index-integrations/readers/llama-index-readers-github/llama_index/readers/github/repository/github_client.py
  llama-index-integrations/readers/llama-index-readers-github/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-github/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-github/tests/test_github_repository_reader.py
Labels: size:L

#13370 add sync httpx client support for openai/azure
  llama-index-integrations/llms/llama-index-llms-azure-openai/llama_index/llms/azure_openai/base.py
  llama-index-integrations/llms/llama-index-llms-azure-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:S

#13369 Fix bug where PDFReader ignores extra_info
  llama-index-integrations/readers/llama-index-readers-file/BUILD
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/docs/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-file/tests/test_docs.py
Labels: lgtm, size:L

#13368 use handlers from global default
  llama-index-core/llama_index/core/callbacks/base.py
Labels: lgtm, size:XS

#13229 Update WeaviateVectorStore to use weaviate client version to v4
  docs/docs/examples/vector_stores/WeaviateIndexDemo-Hybrid.ipynb
  docs/docs/examples/vector_stores/WeaviateIndexDemo.ipynb
  docs/docs/examples/vector_stores/WeaviateIndex_auto_retriever.ipynb
  docs/docs/examples/vector_stores/WeaviateIndex_metadata_filter.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/llama_index/vector_stores/weaviate/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-weaviate/pyproject.toml
Labels: lgtm, size:L

#13373 udpates to multion tool to align with updated api/sdk
  llama-index-integrations/tools/llama-index-tools-multion/README.md
  llama-index-integrations/tools/llama-index-tools-multion/examples/multion.ipynb
  llama-index-integrations/tools/llama-index-tools-multion/llama_index/tools/multion/base.py
  llama-index-integrations/tools/llama-index-tools-multion/pyproject.toml
Labels: lgtm, size:L

#13377 Add `start_char_idx` and `end_char_idx`: `MarkdownElementNodeParser`
  llama-index-core/llama_index/core/node_parser/relational/base_element.py
  llama-index-core/llama_index/core/node_parser/relational/markdown_element.py
  llama-index-core/tests/node_parser/test_markdown_element.py
Labels: lgtm, size:M

#13286 Add VectorStore integration for alibaba cloud opensearch vector service
  docs/docs/community/integrations/vector_stores.md
  docs/docs/examples/vector_stores/AlibabaCloudOpenSearchIndexDemo.ipynb
  docs/docs/module_guides/storing/vector_stores.md
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/vector_stores/llama-index-vector-stores-alibabacloud-opensearch/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-alibabacloud-opensearch/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-alibabacloud-opensearch/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-alibabacloud-opensearch/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-alibabacloud-opensearch/llama_index/vector_stores/alibabacloud_opensearch/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-alibabacloud-opensearch/llama_index/vector_stores/alibabacloud_opensearch/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-alibabacloud-opensearch/llama_index/vector_stores/alibabacloud_opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-alibabacloud-opensearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-alibabacloud-opensearch/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-alibabacloud-opensearch/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-alibabacloud-opensearch/tests/test_vector_stores_alibabacloud_opensearch.py
Labels: lgtm, size:XXL

#13194 Kdb.ai
  docs/docs/examples/vector_stores/KDBAI_Advanced_RAG_Demo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-kdbai/llama_index/vector_stores/kdbai/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-kdbai/pyproject.toml
Labels: lgtm, size:M

#13196 Call Cohere RAG inference with `documents` argument
  llama-index-core/llama_index/core/prompts/default_prompt_selectors.py
  llama-index-integrations/llms/llama-index-llms-cohere/llama_index/llms/cohere/__init__.py
  llama-index-integrations/llms/llama-index-llms-cohere/llama_index/llms/cohere/base.py
  llama-index-integrations/llms/llama-index-llms-cohere/llama_index/llms/cohere/utils.py
  llama-index-integrations/llms/llama-index-llms-cohere/tests/test_llms_cohere.py
  llama-index-integrations/llms/llama-index-llms-cohere/tests/test_rag_inference.py
Labels: lgtm, size:L

#13128 Pebblo-Llama PebbloSafeReader
  llama-index-integrations/readers/llama-index-readers-pebblo/.gitignore
  llama-index-integrations/readers/llama-index-readers-pebblo/BUILD
  llama-index-integrations/readers/llama-index-readers-pebblo/Makefile
  llama-index-integrations/readers/llama-index-readers-pebblo/README.md
  llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/BUILD
  llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/__init__.py
  llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/base.py
  llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/utility.py
  llama-index-integrations/readers/llama-index-readers-pebblo/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-pebblo/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-pebblo/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-pebblo/tests/test_readers_pebblo.py
Labels: lgtm, size:XL

#13396 [version] bump version to 0.10.36
  CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-cohere/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openvino/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-openvino/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-openvino/tests/test_llms_openvino.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/pyproject.toml
  pyproject.toml
Labels: size:M

#13402 Rename OPENAI_API_TOKEN to OPENAI_API_KEY
  docs/docs/examples/finetuning/embeddings/finetune_embedding.ipynb
  docs/docs/examples/managed/manage_retrieval_benchmark.ipynb
  docs/docs/examples/multi_modal/gpt4v_experiments_cot.ipynb
  docs/docs/examples/multi_modal/gpt4v_multi_modal_retrieval.ipynb
  docs/docs/examples/multi_modal/image_to_image_retrieval.ipynb
  docs/docs/examples/multi_modal/llava_demo.ipynb
  docs/docs/examples/multi_modal/llava_multi_modal_tesla_10q.ipynb
  docs/docs/examples/multi_modal/multi_modal_pydantic.ipynb
  docs/docs/examples/multi_modal/multi_modal_video_RAG.ipynb
  docs/docs/examples/multi_modal/openai_multi_modal.ipynb
  docs/docs/examples/node_postprocessor/FlagEmbeddingReranker.ipynb
  docs/docs/examples/node_postprocessor/rankGPT.ipynb
  docs/docs/examples/node_postprocessor/rankLLM.ipynb
  docs/docs/module_guides/models/multi_modal.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/examples/rankLLM.ipynb
Labels: lgtm, size:M

#13400 Add CallbackManager to MultiModalLLM
  llama-index-core/llama_index/core/multi_modal_llms/base.py
Labels: lgtm, size:S

#13398 add dynamic model listing support
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/base.py
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_integration.py
Labels: lgtm, size:M

#13386 Await Firestores's AsyncDocumentReference before converting to dict
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-firestore/llama_index/storage/kvstore/firestore/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-firestore/pyproject.toml
Labels: lgtm, size:XS

#13403 This example is about Llama 3, not 2
  docs/docs/examples/llm/ollama.ipynb
Labels: lgtm, size:XS

#13394 fix: missing authorized_user_info check on GoogleDriveReader
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/drive/base.py
Labels: lgtm, size:S

#13342 Add Dynamic Sessions Integration
  docs/docs/examples/tools/azure_code_interpreter.ipynb
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/.gitignore
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/BUILD
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/CHANGELOG.md
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/Makefile
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/README.md
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/llama_index/tools/azure_code_interpreter/BUILD
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/llama_index/tools/azure_code_interpreter/__init__.py
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/llama_index/tools/azure_code_interpreter/base.py
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/tests/__init__.py
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/tests/test_tools_azure_aca_session.py
Labels: lgtm, size:XL

#13409 Fix retriever integration
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/retriever.py
Labels: lgtm, size:S

#13410 Fix Cohere Rerank bug
  docs/docs/examples/node_postprocessor/CohereRerank.ipynb
  llama-index-integrations/postprocessor/llama-index-postprocessor-cohere-rerank/llama_index/postprocessor/cohere_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-cohere-rerank/pyproject.toml
Labels: lgtm, size:L

#13414 [Dynamic Session] Fixed some indexing issue and resolved a runtime error message
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/llama_index/tools/azure_code_interpreter/base.py
  llama-index-integrations/tools/llama-index-tools-azure-code-interpreter/pyproject.toml
Labels: lgtm, size:M

#13417 vbump cohere llm
  llama-index-integrations/llms/llama-index-llms-cohere/pyproject.toml
  llama-index-packs/llama-index-packs-cohere-citation-chat/pyproject.toml
Labels: lgtm, size:XS

#13418 Update multi_modal_rag_evaluation.ipynb
  docs/docs/examples/evaluation/multi_modal/multi_modal_rag_evaluation.ipynb
Labels: lgtm, size:XS

#12943 Implement async methods in RedisKVStore
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-redis/llama_index/storage/kvstore/redis/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-redis/pyproject.toml
Labels: lgtm, size:M

#13075 Add support for Relyt as a Vector Store
  docs/docs/community/integrations/vector_stores.md
  docs/docs/examples/vector_stores/RelytDemo.ipynb
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/vector_stores/llama-index-vector-stores-relyt/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-relyt/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-relyt/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-relyt/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-relyt/llama_index/vector_stores/relyt/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-relyt/llama_index/vector_stores/relyt/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-relyt/llama_index/vector_stores/relyt/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-relyt/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-relyt/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-relyt/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-relyt/tests/test_vector_stores_relyt.py
Labels: lgtm, size:XL

#13170 Update ZCP Managed Index & Milvus Index demos
  docs/docs/examples/managed/zcpDemo.ipynb
  docs/docs/examples/vector_stores/MilvusIndexDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
Labels: lgtm, size:M

#13420 Update `llama-index-llms-huggingface` dependency
  llama-index-integrations/llms/llama-index-llms-huggingface/pyproject.toml
Labels: lgtm, size:XS

#12854 Adds Unit and Integration tests for MongoDBAtlasVectorSearch
  llama-index-integrations/embeddings/llama-index-embeddings-openai/llama_index/embeddings/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/llama_index/vector_stores/mongodb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/conftest.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/test_integration.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/test_vector_stores_mongodb.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/test_vectorstore.py
Labels: lgtm, size:L

#13430 Add nb for RBC talk/workshop
  docs/docs/presentations/materials/2024-05-10-rbc-llm-workshop.ipynb
  docs/docs/presentations/past_presentations.md
Labels: size:XXL

#13427 add llama3 cookbook
  docs/docs/examples/cookbooks/llama3_cookbook_ollama_replicate.ipynb
Labels: lgtm, size:XXL

#13433 nit: add colab badge
  docs/docs/examples/cookbooks/llama3_cookbook_ollama_replicate.ipynb
Labels: lgtm, size:XS

#13436 llama3 groq cookbook
  docs/docs/examples/cookbooks/llama3_cookbook_groq.ipynb
Labels: size:XXL

#13435 Fix AzureAiSearchVectorStore metadata f-string
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
Labels: lgtm, size:XS

#13432 fix: user_message does not exist bug
  llama-index-core/llama_index/core/llms/chatml_utils.py
Labels: lgtm, size:XS

#13445 update: bump version!
  llama-index-integrations/readers/llama-index-readers-google/pyproject.toml
Labels: lgtm, size:XS

#13448 fix: Corrected connection parameters in connections.connect()
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:XS

#13456 edit llama3 notebooks
  docs/docs/examples/cookbooks/llama3_cookbook_groq.ipynb
  docs/docs/examples/cookbooks/llama3_cookbook_ollama_replicate.ipynb
Labels: lgtm, size:L

#13231 Created an integration to use llms built for Apple's MLX library
  llama-index-integrations/llms/llama-index-llms-mlx/.gitignore
  llama-index-integrations/llms/llama-index-llms-mlx/BUILD
  llama-index-integrations/llms/llama-index-llms-mlx/Makefile
  llama-index-integrations/llms/llama-index-llms-mlx/README.md
  llama-index-integrations/llms/llama-index-llms-mlx/llama_index/llms/mlx/BUILD
  llama-index-integrations/llms/llama-index-llms-mlx/llama_index/llms/mlx/__init__.py
  llama-index-integrations/llms/llama-index-llms-mlx/llama_index/llms/mlx/base.py
  llama-index-integrations/llms/llama-index-llms-mlx/llama_index/llms/mlx/tokenizer_utils.py
  llama-index-integrations/llms/llama-index-llms-mlx/llama_index/llms/mlx/utils.py
  llama-index-integrations/llms/llama-index-llms-mlx/pyproject.toml
Labels: lgtm, size:XXL

#13323 Add New Integration for DeepInfra Embedding Model
  llama-index-integrations/embeddings/llama-index-embeddings-deepinfra/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-deepinfra/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-deepinfra/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-deepinfra/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-deepinfra/llama_index/embeddings/deepinfra/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-deepinfra/llama_index/embeddings/deepinfra/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-deepinfra/llama_index/embeddings/deepinfra/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-deepinfra/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-deepinfra/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-deepinfra/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-deepinfra/tests/test_embeddings_deepinfra.py
Labels: lgtm, size:L

#13341 fix: update `OpenAIAssistantAgent` to use `attachments` rather than `file_ids`
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/openai_assistant_agent.py
  llama-index-integrations/agent/llama-index-agent-openai/tests/test_openai_assistant_agent.py
Labels: lgtm, size:M

#13413 Fix the RAG fusion pipeline
  llama-index-packs/llama-index-packs-rag-fusion-query-pipeline/llama_index/packs/rag_fusion_query_pipeline/base.py
  llama-index-packs/llama-index-packs-rag-fusion-query-pipeline/pyproject.toml
Labels: lgtm, size:M

#13463 gpt-4o support
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/llama_index/multi_modal_llms/openai/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/pyproject.toml
Labels: size:XS

#13465 bump rerank versions
  llama-index-integrations/postprocessor/llama-index-postprocessor-cohere-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-colbert-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-flag-embedding-reranker/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-jinaai-rerank/llama_index/postprocessor/jinaai_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-jinaai-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankgpt-rerank/llama_index/postprocessor/rankgpt_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankgpt-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/llama_index/postprocessor/rankllm_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-sbert-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-voyageai-rerank/llama_index/postprocessor/voyageai_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-voyageai-rerank/pyproject.toml
Labels: lgtm, size:M

#13405 Add support for prompt kwarg
  llama-index-core/llama_index/core/llms/callbacks.py
  llama-index-core/tests/llms/test_callbacks.py
Labels: lgtm, size:M

#13486 Fix RuntimeError by switching to asyncio from threading
  llama-index-core/llama_index/core/chat_engine/condense_plus_context.py
  llama-index-core/llama_index/core/chat_engine/condense_question.py
  llama-index-core/llama_index/core/chat_engine/context.py
  llama-index-core/llama_index/core/chat_engine/simple.py
Labels: lgtm, size:M

#13479 integrations: Update UpTrain Callback Handler to support the new UpTrain evaluation schema and dashboard
  docs/docs/community/integrations/uptrain.md
  docs/docs/examples/callbacks/UpTrainCallback.ipynb
  docs/docs/examples/evaluation/UpTrain.ipynb
  llama-index-integrations/callbacks/llama-index-callbacks-uptrain/llama_index/callbacks/uptrain/base.py
  llama-index-integrations/callbacks/llama-index-callbacks-uptrain/pyproject.toml
Labels: lgtm, size:L

#13482 Update README.md
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/README.md
Labels: lgtm, size:XS

#13476 Fix #9522 - SQLAlchemy warning when using hybrid search on postgres or lantern vector-store integration #9522
  llama-index-integrations/vector_stores/llama-index-vector-stores-lantern/llama_index/vector_stores/lantern/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-lantern/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: lgtm, size:S

#13454 Trafilatura kwargs and progress bar for trafilatura web reader
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/trafilatura_web/README.md
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/trafilatura_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:S

#13442 Remove "Truncate" parameter from Bedrock Cohere invoke model request.
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/llama_index/embeddings/bedrock/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
Labels: lgtm, size:XS

#13467 Add `image_documents` at call time for `MultiModalLLMCompletionProgram`
  llama-index-core/llama_index/core/program/multi_modal_llm_program.py
Labels: lgtm, size:XS

#13492 [version] bump version to 0.10.37
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/deepinfra.md
  docs/docs/api_reference/llms/mlx.md
  docs/docs/api_reference/readers/pebblo.md
  docs/docs/api_reference/storage/vector_store/alibabacloud_opensearch.md
  docs/docs/api_reference/storage/vector_store/relyt.md
  docs/docs/api_reference/tools/azure_code_interpreter.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-deepinfra/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
  pyproject.toml
Labels: lgtm, size:XL

#13489 Example: GPT4o for DataExtraction from PaperCards
  docs/docs/examples/multi_modal/gpt4o_mm_structured_outputs.ipynb
Labels: size:XS

#13422 Avoid unexpected error when stream chat doesn't yield
  llama-index-core/llama_index/core/instrumentation/events/llm.py
  llama-index-core/llama_index/core/llms/callbacks.py
  llama-index-core/llama_index/core/llms/mock.py
  llama-index-core/tests/llms/test_callbacks.py
Labels: lgtm, size:M

#13501 chore: grammar fixes and add colab badge to nb
  docs/docs/examples/multi_modal/gpt4o_mm_structured_outputs.ipynb
Labels: size:S

#13516 Update kuzu version for new storage layer
  llama-index-integrations/graph_stores/llama-index-graph-stores-kuzu/pyproject.toml
Labels: lgtm, size:XS

#13522 fix for pydantic tool calling with a single argument
  llama-index-core/llama_index/core/tools/calling.py
Labels: lgtm, size:S

#13511 [Community] Resolve releasing error for `llama-index-embeddings-ipex-llm` with Intel GPU supports
  docs/docs/examples/embeddings/ipex_llm_gpu.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/pyproject.toml
Labels: lgtm, size:S

#13291 Integrate VectorStore from Elasticsearch client
  docs/docs/examples/vector_stores/ElasticsearchIndexDemo.ipynb
  docs/docs/examples/vector_stores/Elasticsearch_demo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/tests/docker-compose.yml
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/tests/test_vector_stores_elasticsearch.py
Labels: lgtm, size:XXL

#13459 ReAct output parser changes
  llama-index-core/llama_index/core/agent/react/output_parser.py
  llama-index-core/tests/agent/react/test_react_output_parser.py
Labels: lgtm, size:S

#13523 remove exec from download_integration
  llama-index-core/llama_index/core/download/integration.py
Labels: size:XS

#13483 Update Milvus & Zilliz Cloud demos for latest release
  docs/docs/examples/managed/zcpDemo.ipynb
  docs/docs/examples/vector_stores/MilvusIndexDemo.ipynb
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/llama_index/indices/managed/zilliz/base.py
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:XL

#13520 Add missing type in `breakpoint_percentile_threshold` field
  llama-index-core/llama_index/core/node_parser/text/semantic_splitter.py
Labels: lgtm, size:XS

#13514 Improve SentenceEmbeddingOptimizer to respect Settings.embed_model
  llama-index-core/llama_index/core/postprocessor/optimizer.py
Labels: lgtm, size:XS

#13539 feat: add gemini new models to multimodal LLM and regular
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/llama_index/multi_modal_llms/gemini/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/pyproject.toml
Labels: lgtm, size:S

#13543 chore: Add colab badge introspective-agent notebook
  docs/docs/examples/agent/introspective_agent_toxicity_reduction.ipynb
Labels: size:XS

#13535 Updated Browserbase web reader
  docs/docs/api_reference/readers/web.md
  docs/docs/examples/data_connectors/WebPageDemo.ipynb
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/browserbase_web/README.md
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/browserbase_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:M

#13531 Allow querying AzureAISearch without non-null metadata field
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
Labels: lgtm, size:S

#13424 Add BaseFilesystemReader interface + implement in SimpleDirectoryReader
  llama-index-core/llama_index/core/readers/__init__.py
  llama-index-core/llama_index/core/readers/base.py
  llama-index-core/llama_index/core/readers/file/base.py
  llama-index-core/pyproject.toml
Labels: lgtm, size:L

#13558 chore: correct the image folder
  docs/docs/examples/multi_modal/gpt4o_mm_structured_outputs.ipynb
Labels: lgtm, size:XS

#13560 Feat/Added firecrawl search mode
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/firecrawl_web/README.md
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/firecrawl_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:M

#13408 Implement BaseFilesystemReader in S3Reader and SharePoint Reader
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-file/tests/test_file.py
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/llama_index/readers/microsoft_sharepoint/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-s3/llama_index/readers/s3/base.py
  llama-index-integrations/readers/llama-index-readers-s3/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-s3/tests/test_readers_s3.py
Labels: lgtm, size:L

#13555 add snowflake/arctic-embed-l support
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_integration.py
Labels: lgtm, size:M

#13564 chore: remove duplicate achat
  llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
  llama-index-integrations/llms/llama-index-llms-ollama/pyproject.toml
Labels: lgtm, size:M

#13566 fix: enable tool use
  llama-index-integrations/llms/llama-index-llms-groq/llama_index/llms/groq/base.py
  llama-index-integrations/llms/llama-index-llms-groq/pyproject.toml
Labels: lgtm, size:XS

#13572 Deprecate mode() in favor of __init__(base_url=...) for NVIDIA, NVIDIAEmbedding, NVIDIARerank
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/conftest.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_api_key.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_available_models.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_integration.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_mode_switch.py
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/base.py
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/conftest.py
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_additional_kwargs.py
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_api_key.py
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_available_models.py
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_integration.py
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_mode_switch.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/conftest.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_api_key.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_available_models.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_mode_switch.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_postprocessor_nvidia_rerank.py
Labels: lgtm, size:XL

#13578 fix: (ArxivReader) set exclude_hidden to False when reading data from hidden directory
  llama-index-integrations/readers/llama-index-readers-papers/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-papers/llama_index/readers/papers/arxiv/base.py
  llama-index-integrations/readers/llama-index-readers-papers/pyproject.toml
Labels: lgtm, size:S

#13584 docs: add gpt4o_mm_structured_outputs.ipynb to Examples >> MultiModal section
  docs/mkdocs.yml
Labels: size:XS

#13538 Fix errors in Kuzu example notebook for latest version
  docs/docs/examples/index_structs/knowledge_graph/KuzuGraphDemo.ipynb
  docs/docs/examples/index_structs/knowledge_graph/kuzugraph_draw.html
Labels: lgtm, size:L

#13193 Integrations: upstage LLM and Embeddings
  docs/docs/api_reference/embeddings/upstage.md
  docs/docs/api_reference/llms/upstage.md
  docs/docs/examples/embeddings/upstage.ipynb
  docs/docs/examples/llm/solar.ipynb
  docs/docs/examples/llm/upstage.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/llama_index/embeddings/upstage/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/llama_index/embeddings/upstage/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/llama_index/embeddings/upstage/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/llama_index/embeddings/upstage/utils.py
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/tests/integration_tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/tests/integration_tests/test_integrations.py
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/tests/unit_tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/tests/unit_tests/test_embeddings_upstage.py
  llama-index-integrations/llms/llama-index-llms-solar/llama_index/llms/solar/base.py
  llama-index-integrations/llms/llama-index-llms-upstage/.gitignore
  llama-index-integrations/llms/llama-index-llms-upstage/BUILD
  llama-index-integrations/llms/llama-index-llms-upstage/Makefile
  llama-index-integrations/llms/llama-index-llms-upstage/README.md
  llama-index-integrations/llms/llama-index-llms-upstage/llama_index/llms/upstage/BUILD
  llama-index-integrations/llms/llama-index-llms-upstage/llama_index/llms/upstage/__init__.py
  llama-index-integrations/llms/llama-index-llms-upstage/llama_index/llms/upstage/base.py
  llama-index-integrations/llms/llama-index-llms-upstage/llama_index/llms/upstage/utils.py
  llama-index-integrations/llms/llama-index-llms-upstage/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-upstage/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-upstage/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-upstage/tests/test_llms_upstage.py
  llama-index-integrations/llms/llama-index-llms-upstage/tests/test_upstage.py
Labels: lgtm, size:XXL

#13548 fix: sec_filings reader when making requests to sec.gov
  llama-index-integrations/readers/llama-index-readers-sec-filings/llama_index/readers/sec_filings/sec_filings.py
  llama-index-integrations/readers/llama-index-readers-sec-filings/pyproject.toml
Labels: lgtm, size:XS

#13567 Pass 'exclude_llm_metadata_keys' and 'exclude_embed_metadata_keys' in Node Parsers
  llama-index-core/llama_index/core/node_parser/relational/base_element.py
  llama-index-core/llama_index/core/node_parser/relational/llama_parse_json_element.py
  llama-index-core/llama_index/core/node_parser/relational/markdown_element.py
  llama-index-core/llama_index/core/node_parser/relational/unstructured_element.py
Labels: lgtm, size:S

#13583 Integration: Bump duckduckgo-search package
  llama-index-integrations/tools/llama-index-tools-duckduckgo/llama_index/tools/duckduckgo/base.py
  llama-index-integrations/tools/llama-index-tools-duckduckgo/pyproject.toml
Labels: lgtm, size:S

#13590 docs: add upstage llm and embeddings
  docs/docs/module_guides/models/embeddings.md
  docs/docs/module_guides/models/llms/modules.md
Labels: lgtm, size:XS

#13602 add reqs to sec fillings
  llama-index-integrations/readers/llama-index-readers-sec-filings/llama_index/readers/sec_filings/sec_filings.py
  llama-index-integrations/readers/llama-index-readers-sec-filings/pyproject.toml
Labels: size:XS

#13605 fix docs build
  docs/docs/api_reference/embeddings/huggingface_openvino.md
  docs/docs/api_reference/postprocessor/dashscope_rerank.md
  docs/mkdocs.yml
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: size:S

#13591 Fix the expression construction of Milvus vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:S

#13596 Fix: Limit the number of generated questions
  llama-index-core/llama_index/core/llama_dataset/generator.py
  llama-index-core/llama_index/core/llama_dataset/legacy/embedding.py
  llama-index-finetuning/llama_index/finetuning/cross_encoders/dataset_gen.py
  llama-index-finetuning/llama_index/finetuning/embeddings/common.py
  llama-index-finetuning/pyproject.toml
  llama-index-packs/llama-index-packs-raft-dataset/llama_index/packs/raft_dataset/base.py
  llama-index-packs/llama-index-packs-raft-dataset/pyproject.toml
Labels: lgtm, size:M
