Repository run-llama/llama_index, pull requests merged in 2024-09, with the labels that each got.

#15763 Support image type detection without knowing the file name
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/llama_index/multi_modal_llms/anthropic/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/pyproject.toml
Labels: lgtm, size:M

#15765 [fix] remove `__init__.py` to fix embedding integration path issues
  llama-index-integrations/embeddings/llama-index-embeddings-openai/llama_index/embeddings/__init__.py
Labels: lgtm, size:XS

#15747 fix: GitHub Models metadata retrieval
  docs/docs/examples/llm/azure_inference.ipynb
  llama-index-integrations/llms/llama-index-llms-azure-inference/llama_index/llms/azure_inference/base.py
  llama-index-integrations/llms/llama-index-llms-azure-inference/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-azure-inference/tests/test_llms_azure_inference.py
Labels: lgtm, size:M

#15770 add `dimensions` param to `LiteLLMEmbedding`, fix a bug that prevents reading vars from env
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/llama_index/embeddings/litellm/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-litellm/pyproject.toml
Labels: lgtm, size:M

#15767 Bugfix upstage embedding when initializing the UpstageEmbedding class
  docs/docs/examples/embeddings/upstage.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/llama_index/embeddings/upstage/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/tests/integration_tests/test_integrations.py
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/tests/unit_tests/test_embeddings_upstage.py
Labels: lgtm, size:L

#15778 Fix Sagemaker Field required issue
  llama-index-integrations/embeddings/llama-index-embeddings-sagemaker-endpoint/llama_index/embeddings/sagemaker_endpoint/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-sagemaker-endpoint/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-sagemaker-endpoint/llama_index/llms/sagemaker_endpoint/base.py
  llama-index-integrations/llms/llama-index-llms-sagemaker-endpoint/pyproject.toml
Labels: lgtm, size:S

#15776 fix: remove context after running workflow
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_streaming.py
Labels: lgtm, size:S

#15769 fix relations upsert
  llama-index-integrations/graph_stores/llama-index-graph-stores-falkordb/llama_index/graph_stores/falkordb/falkordb_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-falkordb/pyproject.toml
Labels: lgtm, size:XS

#15775 Add text to sql advanced workflow nb
  docs/docs/examples/workflow/advanced_text_to_sql.ipynb
  docs/docs/module_guides/workflow/index.md
Labels: lgtm, size:XXL

#15773 add ollama response usage
  llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
  llama-index-integrations/llms/llama-index-llms-ollama/pyproject.toml
Labels: lgtm, size:S

#15745 NVIDIA: LLM Structured Output Notebook, test cases
  docs/docs/examples/output_parsing/nvidia_output_parsing.ipynb
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_structured_output.py
Labels: lgtm, size:XL

#15783 FunctionCallingAgent sources bug + light wrapper to create agent
  docs/docs/examples/agent/agentic_rag_using_vertex_ai.ipynb
  docs/docs/examples/agent/agentic_rag_with_llamaindex_and_vertexai_managed_index.ipynb
  docs/docs/examples/agent/anthropic_agent.ipynb
  docs/docs/examples/agent/bedrock_converse_agent.ipynb
  docs/docs/examples/agent/memory/composable_memory.ipynb
  docs/docs/examples/agent/mistral_agent.ipynb
  docs/docs/examples/agent/nvidia_agent.ipynb
  docs/docs/examples/agent/return_direct_agent.ipynb
  docs/docs/examples/cookbooks/mistralai.ipynb
  docs/docs/examples/property_graph/agentic_graph_rag_vertex.ipynb
  docs/docs/presentations/materials/2024-06-13-vector-ess-oss-tools.ipynb
  llama-index-core/llama_index/core/agent/__init__.py
  llama-index-core/llama_index/core/agent/function_calling/base.py
  llama-index-core/llama_index/core/agent/function_calling/step.py
Labels: size:L

#15752 Fix incorrect instrumentation fields and types
  llama-index-core/llama_index/core/instrumentation/span/base.py
Labels: lgtm, size:XS

#15788 v0.11.4
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/selectors/notdiamond.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/agent/function_calling/step.py
  llama-index-core/llama_index/core/agent/runner/base.py
  llama-index-core/llama_index/core/chat_engine/types.py
  llama-index-core/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-openai/pyproject.toml
  llama-index-integrations/graph_stores/llama-index-graph-stores-falkordb/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-llama-parse/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#15564 Add MariaDB vector store integration package
  docs/docs/community/integrations/vector_stores.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/llama_index/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/llama_index/py.typed
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/llama_index/vector_stores/mariadb/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/llama_index/vector_stores/mariadb/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/llama_index/vector_stores/mariadb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/tests/docker-compose.yaml
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/tests/test_mariadb.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/tests/test_vector_stores_mariadb.py
Labels: lgtm, size:XL

#15790 Add missing openai agent dep
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:XS

#15791 update azure openai llm to use latest openai llm version
  llama-index-integrations/llms/llama-index-llms-azure-openai/pyproject.toml
Labels: size:XS

#15796 Fix import path and query engine call
  docs/docs/examples/property_graph/property_graph_kuzu.ipynb
  llama-index-integrations/graph_stores/llama-index-graph-stores-kuzu/pyproject.toml
Labels: lgtm, size:S

#15802 NVIDIA llm: Add Completion for starcoder models
  docs/docs/examples/llm/nvidia_text_completion.ipynb
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/base.py
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/utils.py
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_text-completion.py
Labels: lgtm, size:L

#15807 Fix typo in tools.md
  docs/docs/module_guides/deploying/agents/tools.md
Labels: lgtm, size:XS

#15806 fix: convert Document id from int to string in DiscordReader
  llama-index-integrations/readers/llama-index-readers-discord/llama_index/readers/discord/base.py
  llama-index-integrations/readers/llama-index-readers-discord/pyproject.toml
Labels: lgtm, size:XS

#15800 Update llama-index-readers-dashscope base.py
  llama-index-integrations/readers/llama-index-readers-dashscope/llama_index/readers/dashscope/base.py
  llama-index-integrations/readers/llama-index-readers-dashscope/pyproject.toml
Labels: lgtm, size:S

#15811 Nav was wrong for unbound functions
  docs/mkdocs.yml
Labels: lgtm, size:XS

#15815 update openai base.py to use all_kwargs
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:XS

#15819 Update pyproject.toml
  llama-index-integrations/readers/llama-index-readers-minio/pyproject.toml
Labels: lgtm, size:XS

#15816 fix json schema for fastapi return types
  llama-index-core/llama_index/core/schema.py
Labels: size:S

#15826 enable async tests for structured output and tools
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_structured_output.py
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_tools.py
Labels: lgtm, size:L

#15833 make graphs serialize again
  llama-index-core/llama_index/core/graph_stores/types.py
Labels: size:XS

#15832 remove unneeded assert
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/base.py
Labels: size:XS

#15834 v0.11.5
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/storage/vector_store/mariadb.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:M

#15836 Box bug fix 202409
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxAPI/box_llama_adaptors.py
  llama-index-integrations/readers/llama-index-readers-box/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-box/tests/test_readers_box_reader.py
  llama-index-integrations/tools/llama-index-tools-box/llama_index/tools/box/search/base.py
  llama-index-integrations/tools/llama-index-tools-box/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-box/tests/test_tools_box_search.py
Labels: lgtm, size:M

#15845 Add oreilly course cookbooks
  docs/docs/examples/cookbooks/oreilly_cource_cookbooks_docs/Module-2/Components_Of_LlamaIndex.ipynb
  docs/docs/examples/cookbooks/oreilly_cource_cookbooks_docs/Module-3/Evaluating_RAG_Systems.ipynb
  docs/docs/examples/cookbooks/oreilly_cource_cookbooks_docs/Module-4/Ingestion_Pipeline.ipynb
  docs/docs/examples/cookbooks/oreilly_cource_cookbooks_docs/Module-4/Metadata_Extraction.ipynb
  docs/docs/examples/cookbooks/oreilly_cource_cookbooks_docs/Module-5/Observability.ipynb
  docs/docs/examples/cookbooks/oreilly_cource_cookbooks_docs/Module-6/Agents.ipynb
  docs/docs/examples/cookbooks/oreilly_cource_cookbooks_docs/Module-6/Router_And_SubQuestion_QueryEngine.ipynb
  docs/docs/examples/cookbooks/oreilly_cource_cookbooks_docs/Module-7/Multi_Modal_RAG_System.ipynb
  docs/docs/examples/cookbooks/oreilly_cource_cookbooks_docs/Module-8/Advanced_RAG_with_LlamaParse.ipynb
  docs/docs/examples/cookbooks/oreilly_cource_cookbooks_docs/README.md
Labels: lgtm, size:XXL

#15859 correct course name
  docs/docs/examples/cookbooks/oreilly_course_cookbooks/Module-2/Components_Of_LlamaIndex.ipynb
  docs/docs/examples/cookbooks/oreilly_course_cookbooks/Module-3/Evaluating_RAG_Systems.ipynb
  docs/docs/examples/cookbooks/oreilly_course_cookbooks/Module-4/Ingestion_Pipeline.ipynb
  docs/docs/examples/cookbooks/oreilly_course_cookbooks/Module-4/Metadata_Extraction.ipynb
  docs/docs/examples/cookbooks/oreilly_course_cookbooks/Module-5/Observability.ipynb
  docs/docs/examples/cookbooks/oreilly_course_cookbooks/Module-6/Agents.ipynb
  docs/docs/examples/cookbooks/oreilly_course_cookbooks/Module-6/Router_And_SubQuestion_QueryEngine.ipynb
  docs/docs/examples/cookbooks/oreilly_course_cookbooks/Module-7/Multi_Modal_RAG_System.ipynb
  docs/docs/examples/cookbooks/oreilly_course_cookbooks/Module-8/Advanced_RAG_with_LlamaParse.ipynb
  docs/docs/examples/cookbooks/oreilly_course_cookbooks/README.md
Labels: size:XS

#15794 clone llama-deploy docs during docs builds
  .readthedocs.yaml
  docs/merge_llama_deploy_docs.py
Labels: size:L

#15848 Update ImageReader file loading logic
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/image/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:XS

#15861 Minor bug in SQQE
  docs/docs/examples/workflow/sub_question_query_engine.ipynb
Labels: lgtm, size:XS

#15863 v0.11.6
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/merge_llama_deploy_docs.py
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#15864 remove widgets from recent notebooks
  docs/docs/examples/cookbooks/oreilly_course_cookbooks/Module-3/Evaluating_RAG_Systems.ipynb
  docs/docs/examples/cookbooks/oreilly_course_cookbooks/Module-5/Observability.ipynb
Labels: size:XXL

#15857 Fix image document deserialization issue
  llama-index-core/llama_index/core/schema.py
  llama-index-core/llama_index/core/storage/docstore/utils.py
Labels: lgtm, size:S

#15846 Bugfix: Remove warnings during data insertion for Hybrid Search due to duplicated columns in the schema
  llama-index-integrations/vector_stores/llama-index-vector-stores-kdbai/llama_index/vector_stores/kdbai/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-kdbai/pyproject.toml
Labels: lgtm, size:XS

#15657 Add TablestoreVectorStore.
  docs/docs/api_reference/storage/vector_store/tablestore.md
  docs/docs/community/integrations/vector_stores.md
  docs/docs/examples/vector_stores/TablestoreDemo.ipynb
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/llama_index/vector_stores/tablestore/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/llama_index/vector_stores/tablestore/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/llama_index/vector_stores/tablestore/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-tablestore/tests/test_vector_stores_tablestore.py
Labels: lgtm, size:XXL

#15869 Removed unused `llama-index-llms-anthropic` dependency from Bedrock Converse
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: lgtm, size:XS

#15879 Update bedrock.py
  llama-index-legacy/llama_index/legacy/llms/bedrock.py
Labels: size:XS

#15842 Add tool calling example in NVIDIA notebook
  docs/docs/examples/llm/nvidia.ipynb
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/base.py
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
Labels: lgtm, size:M

#15820 NVIDIA: Completion fixes
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/base.py
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/utils.py
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_text-completion.py
Labels: lgtm, size:M

#15886 Fix PGVectorStore with latest pydantic, update pydantic imports
  docs/docs/examples/llm/openai.ipynb
  docs/docs/examples/property_graph/property_graph_neptune.ipynb
  docs/docs/module_guides/indexing/lpg_index_guide.md
  llama-index-core/llama_index/core/llms/llm.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: size:S

#15887 add type ignore for streaming agents
  llama-index-core/llama_index/core/agent/runner/base.py
  llama-index-core/llama_index/core/agent/runner/parallel.py
Labels: size:S

#15706 [wip] force openai structured output
  docs/docs/examples/chat_engine/chat_engine_condense_plus_context.ipynb
  llama-index-core/llama_index/core/llms/llm.py
  llama-index-core/llama_index/core/llms/structured_llm.py
  llama-index-core/llama_index/core/program/function_program.py
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
Labels: lgtm, size:M

#15882 feature: Make SentenceSplitter's secondary_chunking_regex optional
  llama-index-core/llama_index/core/node_parser/text/sentence.py
Labels: lgtm, size:S

#15889 Bug fix for KuzuPropertyGraphStore: Allow upserting relations even when chunks are absent
  llama-index-integrations/graph_stores/llama-index-graph-stores-kuzu/llama_index/graph_stores/kuzu/kuzu_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-kuzu/pyproject.toml
Labels: lgtm, size:S

#15890 Missing tablestore
  docs/mkdocs.yml
Labels: size:XS

#15891 v0.11.7
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#15901 nit: extend workflow tutorial
  docs/docs/understanding/workflows/index.md
Labels: lgtm, size:XS

#15904 Modify generate_qa_embedding_pairs to use LLM from Settings
  llama-index-core/llama_index/core/llama_dataset/legacy/embedding.py
Labels: lgtm, size:XS

#15912 docs: document how to disable global timeout along with more docs
  llama-index-core/llama_index/core/workflow/workflow.py
Labels: docs, lgtm, size:M, topic:workflows

#15907 fix: model_name property and pydantic v2 in Azure Inference package
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/llama_index/embeddings/azure_inference/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/tests/test_embeddings_azure_inference.py
  llama-index-integrations/llms/llama-index-llms-azure-inference/llama_index/llms/azure_inference/base.py
  llama-index-integrations/llms/llama-index-llms-azure-inference/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-azure-inference/tests/test_llms_azure_inference.py
Labels: lgtm, size:M

#15921 Add InternalServerError to retry decorator
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/utils.py
  llama-index-integrations/llms/llama-index-llms-vertex/pyproject.toml
Labels: lgtm, size:XS

#14158 Adding vector store for Azure Cosmos DB NoSql
  docs/docs/examples/vector_stores/AzureCosmosDBNoSqlDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/llama_index/vector_stores/azurecosmosnosql/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/llama_index/vector_stores/azurecosmosnosql/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/llama_index/vector_stores/azurecosmosnosql/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/tests/test_azurecosmosnosql.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/tests/test_vector_stores_azurecosmosnosql.py
Labels: lgtm, size:XL

#15928 Add doc.id to Langchain format conversions
  llama-index-core/llama_index/core/schema.py
Labels: lgtm, size:XS

#15892 Update RankLLM with new rerankers
  docs/docs/examples/node_postprocessor/rankLLM.ipynb
  docs/docs/module_guides/querying/node_postprocessors/node_postprocessors.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/llama_index/postprocessor/rankllm_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/llama_index/postprocessor/rankllm_rerank/test.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/tests/BUILD
Labels: lgtm, size:L

#15917 Feature Request #15810 :: Add DynamoDBChatStore
  docs/docs/module_guides/storing/chat_stores.md
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/.gitignore
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/Makefile
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/README.md
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/llama_index/storage/chat_store/dynamodb/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/llama_index/storage/chat_store/dynamodb/__init__.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/llama_index/storage/chat_store/dynamodb/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/pyproject.toml
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/tests/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/tests/__init__.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/tests/test_chat_store_dynamodb_chat_store.py
Labels: lgtm, size:XL

#15868 Fix error handling in sharepoint reader
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/llama_index/readers/microsoft_sharepoint/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/pyproject.toml
Labels: lgtm, size:M

#15850 feat: add llama-index llms alibabacloud_aisearch integration
  llama-index-integrations/llms/llama-index-llms-alibabacloud-aisearch/.gitignore
  llama-index-integrations/llms/llama-index-llms-alibabacloud-aisearch/BUILD
  llama-index-integrations/llms/llama-index-llms-alibabacloud-aisearch/Makefile
  llama-index-integrations/llms/llama-index-llms-alibabacloud-aisearch/README.md
  llama-index-integrations/llms/llama-index-llms-alibabacloud-aisearch/llama_index/llms/alibabacloud_aisearch/BUILD
  llama-index-integrations/llms/llama-index-llms-alibabacloud-aisearch/llama_index/llms/alibabacloud_aisearch/__init__.py
  llama-index-integrations/llms/llama-index-llms-alibabacloud-aisearch/llama_index/llms/alibabacloud_aisearch/base.py
  llama-index-integrations/llms/llama-index-llms-alibabacloud-aisearch/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-alibabacloud-aisearch/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-alibabacloud-aisearch/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-alibabacloud-aisearch/tests/test_llms_alibabacloud_aisearch.py
Labels: lgtm, size:L

#15899 Opensearch Serverless filtered query support using knn_score script
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/CHANGELOG.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
Labels: lgtm, size:M

#15906 Mistral AI LLM Integration fixes
  docs/docs/examples/llm/mistralai.ipynb
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/base.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
Labels: lgtm, size:XS

#15931 Fix RagCLI
  llama-index-cli/llama_index/cli/rag/base.py
  llama-index-cli/pyproject.toml
Labels: size:XS

#15933 v0.11.8
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/storage/vector_store/azurecosmosnosql.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/pyproject.toml
  pants.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#15938 docs: document retry policy
  docs/docs/api_reference/workflow/retry_policy.md
  docs/docs/module_guides/workflow/index.md
  docs/mkdocs.yml
Labels: docs, lgtm, size:M

#15937 docs: update AI21 docs and readme
  docs/docs/examples/llm/ai21.ipynb
  llama-index-integrations/llms/llama-index-llms-ai21/README.md
Labels: lgtm, size:L

#15934 Add four alibabacloud-aisearch llama-index integrations: rerank, node_parser, readers, embeddings
  llama-index-integrations/embeddings/llama-index-embeddings-alibabacloud-aisearch/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-alibabacloud-aisearch/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-alibabacloud-aisearch/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-alibabacloud-aisearch/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-alibabacloud-aisearch/llama_index/embeddings/alibabacloud_aisearch/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-alibabacloud-aisearch/llama_index/embeddings/alibabacloud_aisearch/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-alibabacloud-aisearch/llama_index/embeddings/alibabacloud_aisearch/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-alibabacloud-aisearch/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-alibabacloud-aisearch/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-alibabacloud-aisearch/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-alibabacloud-aisearch/tests/test_embeddings_alibabacloud_aisearch.py
  llama-index-integrations/llms/llama-index-llms-alibabacloud-aisearch/README.md
  llama-index-integrations/llms/llama-index-llms-alibabacloud-aisearch/llama_index/llms/alibabacloud_aisearch/base.py
  llama-index-integrations/node_parser/llama-index-node-parser-alibabacloud-aisearch/.gitignore
  llama-index-integrations/node_parser/llama-index-node-parser-alibabacloud-aisearch/BUILD
  llama-index-integrations/node_parser/llama-index-node-parser-alibabacloud-aisearch/Makefile
  llama-index-integrations/node_parser/llama-index-node-parser-alibabacloud-aisearch/README.md
  llama-index-integrations/node_parser/llama-index-node-parser-alibabacloud-aisearch/llama_index/node_parser/alibabacloud_aisearch/BUILD
  llama-index-integrations/node_parser/llama-index-node-parser-alibabacloud-aisearch/llama_index/node_parser/alibabacloud_aisearch/__init__.py
  llama-index-integrations/node_parser/llama-index-node-parser-alibabacloud-aisearch/llama_index/node_parser/alibabacloud_aisearch/base.py
  llama-index-integrations/node_parser/llama-index-node-parser-alibabacloud-aisearch/pyproject.toml
  llama-index-integrations/node_parser/llama-index-node-parser-alibabacloud-aisearch/tests/BUILD
  llama-index-integrations/node_parser/llama-index-node-parser-alibabacloud-aisearch/tests/__init__.py
  llama-index-integrations/node_parser/llama-index-node-parser-alibabacloud-aisearch/tests/test_node_parser_alibabacloud_aisearch.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-alibabacloud-aisearch-rerank/.gitignore
  llama-index-integrations/postprocessor/llama-index-postprocessor-alibabacloud-aisearch-rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-alibabacloud-aisearch-rerank/Makefile
  llama-index-integrations/postprocessor/llama-index-postprocessor-alibabacloud-aisearch-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-alibabacloud-aisearch-rerank/llama_index/postprocessor/alibabacloud_aisearch_rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-alibabacloud-aisearch-rerank/llama_index/postprocessor/alibabacloud_aisearch_rerank/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-alibabacloud-aisearch-rerank/llama_index/postprocessor/alibabacloud_aisearch_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-alibabacloud-aisearch-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-alibabacloud-aisearch-rerank/tests/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-alibabacloud-aisearch-rerank/tests/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-alibabacloud-aisearch-rerank/tests/test_postprocessor_alibabacloud_aisearch_rerank.py
  llama-index-integrations/readers/llama-index-readers-alibabacloud-aisearch/.gitignore
  llama-index-integrations/readers/llama-index-readers-alibabacloud-aisearch/BUILD
  llama-index-integrations/readers/llama-index-readers-alibabacloud-aisearch/Makefile
  llama-index-integrations/readers/llama-index-readers-alibabacloud-aisearch/README.md
  llama-index-integrations/readers/llama-index-readers-alibabacloud-aisearch/llama_index/readers/alibabacloud_aisearch/BUILD
  llama-index-integrations/readers/llama-index-readers-alibabacloud-aisearch/llama_index/readers/alibabacloud_aisearch/__init__.py
  llama-index-integrations/readers/llama-index-readers-alibabacloud-aisearch/llama_index/readers/alibabacloud_aisearch/base.py
  llama-index-integrations/readers/llama-index-readers-alibabacloud-aisearch/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-alibabacloud-aisearch/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-alibabacloud-aisearch/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-alibabacloud-aisearch/tests/test_readers_alibabacloud_aisearch.py
Labels: lgtm, size:XL

#15945 Differentiate sync and async calls in OpenSearchVectorClient
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/tests/test_opensearch_client.py
Labels: lgtm, size:L

#15951 feat(postgres): add support for engine parameters
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: lgtm, size:S

#15940 update falkordb client
  llama-index-integrations/graph_stores/llama-index-graph-stores-falkordb/llama_index/graph_stores/falkordb/falkordb_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-falkordb/pyproject.toml
Labels: lgtm, size:M

#15961 fix attribute error in PGVectorStore
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: size:XS

#15979 Add support for o1 openai models
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:M

#15983 force temp to 1.0 for o1
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:XS

#15988 Fix the import path example for SimpleMongoReader
  llama-index-integrations/readers/llama-index-readers-mongodb/README.md
Labels: lgtm, size:XS

#15986 Do not pass system prompt from fn calling runner to fn calling worker
  llama-index-core/llama_index/core/agent/function_calling/base.py
Labels: size:XS

#15990 Add callback manager to retriever query engine from args
  llama-index-core/llama_index/core/query_engine/retriever_query_engine.py
Labels: lgtm, size:XS

#15992 v0.11.9
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/alibabacloud_aisearch.md
  docs/docs/api_reference/llms/alibabacloud_aisearch.md
  docs/docs/api_reference/node_parser/alibabacloud_aisearch.md
  docs/docs/api_reference/postprocessor/alibabacloud_aisearch_rerank.md
  docs/docs/api_reference/readers/alibabacloud_aisearch.md
  docs/docs/api_reference/storage/chat_store/dynamodb.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#16006 Fix: get all documents from Elasticsearch KVStore
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-elasticsearch/llama_index/storage/kvstore/elasticsearch/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-elasticsearch/pyproject.toml
Labels: lgtm, size:S

#15993 Fix Pydantic numeric validation in openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:S

#16000 feat: add quip reader
  llama-index-integrations/readers/llama-index-readers-quip/.gitignore
  llama-index-integrations/readers/llama-index-readers-quip/BUILD
  llama-index-integrations/readers/llama-index-readers-quip/Makefile
  llama-index-integrations/readers/llama-index-readers-quip/README.md
  llama-index-integrations/readers/llama-index-readers-quip/llama_index/readers/quip/BUILD
  llama-index-integrations/readers/llama-index-readers-quip/llama_index/readers/quip/__init__.py
  llama-index-integrations/readers/llama-index-readers-quip/llama_index/readers/quip/base.py
  llama-index-integrations/readers/llama-index-readers-quip/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-quip/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-quip/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-quip/tests/test_readers_quip.py
Labels: lgtm, size:L

#16011 [docs/example] Human in loop workflow example
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/readers/quip.md
  docs/docs/examples/workflow/human_in_the_loop_story_crafting.ipynb
  docs/docs/module_guides/workflow/index.md
  docs/mkdocs.yml
Labels: lgtm, size:XL

#16012 fix: removed author info from quip reader
  llama-index-integrations/readers/llama-index-readers-quip/pyproject.toml
Labels: lgtm, size:XS

#16015 Hotfix: Fix Citations Text
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-vectara/tests/test_indices_managed_vectara.py
Labels: lgtm, size:S

#16007 Jacques/opik integration
  docs/docs/_static/integrations/opik.png
  docs/docs/api_reference/callbacks/opik.md
  docs/docs/community/integrations.md
  docs/docs/examples/observability/OpikCallback.ipynb
  docs/docs/module_guides/observability/index.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/callbacks/global_handlers.py
  llama-index-integrations/callbacks/llama-index-callbacks-opik/.gitignore
  llama-index-integrations/callbacks/llama-index-callbacks-opik/BUILD
  llama-index-integrations/callbacks/llama-index-callbacks-opik/Makefile
  llama-index-integrations/callbacks/llama-index-callbacks-opik/README.md
  llama-index-integrations/callbacks/llama-index-callbacks-opik/examples/BUILD
  llama-index-integrations/callbacks/llama-index-callbacks-opik/examples/opik_example.py
  llama-index-integrations/callbacks/llama-index-callbacks-opik/llama_index/callbacks/opik/BUILD
  llama-index-integrations/callbacks/llama-index-callbacks-opik/llama_index/callbacks/opik/__init__.py
  llama-index-integrations/callbacks/llama-index-callbacks-opik/llama_index/callbacks/opik/base.py
  llama-index-integrations/callbacks/llama-index-callbacks-opik/pyproject.toml
Labels: lgtm, size:L

#15996 update llamacloud index with image nodes
  llama-index-core/llama_index/core/schema.py
  llama-index-core/tests/test_schema.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
Labels: lgtm, size:L

#16025 chore: add o1 models pinned versions
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:XS

#16018 add sparse embedding abstraction
  llama-index-core/llama_index/core/base/embeddings/base_sparse.py
  llama-index-core/llama_index/core/instrumentation/events/embedding.py
  llama-index-core/llama_index/core/sparse_embeddings/BUILD
  llama-index-core/llama_index/core/sparse_embeddings/__init__.py
  llama-index-core/llama_index/core/sparse_embeddings/mock_sparse_embedding.py
  llama-index-core/tests/sparse_embeddings/BUILD
  llama-index-core/tests/sparse_embeddings/__init__.py
  llama-index-core/tests/sparse_embeddings/test_mock_sparse_embeddings.py
  llama-index-integrations/sparse_embeddings/llama-index-sparse-embeddings-fastembed/BUILD
  llama-index-integrations/sparse_embeddings/llama-index-sparse-embeddings-fastembed/Makefile
  llama-index-integrations/sparse_embeddings/llama-index-sparse-embeddings-fastembed/README.md
  llama-index-integrations/sparse_embeddings/llama-index-sparse-embeddings-fastembed/llama_index/sparse_embeddings/fastembed/BUILD
  llama-index-integrations/sparse_embeddings/llama-index-sparse-embeddings-fastembed/llama_index/sparse_embeddings/fastembed/__init__.py
  llama-index-integrations/sparse_embeddings/llama-index-sparse-embeddings-fastembed/llama_index/sparse_embeddings/fastembed/base.py
  llama-index-integrations/sparse_embeddings/llama-index-sparse-embeddings-fastembed/pyproject.toml
  llama-index-integrations/sparse_embeddings/llama-index-sparse-embeddings-fastembed/tests/BUILD
  llama-index-integrations/sparse_embeddings/llama-index-sparse-embeddings-fastembed/tests/__init__.py
  llama-index-integrations/sparse_embeddings/llama-index-sparse-embeddings-fastembed/tests/test_sparse_embeddings_fastembed.py
Labels: lgtm, size:XL

#16026 Implement `get_nodes` on `PGVectorStore`
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/test_postgres.py
Labels: lgtm, size:L

#16031 Update docstring in base.py in MilvusVectorStore adding COSINE as available similarity metric
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
Labels: lgtm, size:XS

#16037 Fix: unnecessary warning issue in HuggingFace LLM when tokenizer is provided as argument(#16035)
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface/pyproject.toml
Labels: lgtm, size:XS

#16036 Attempt #3 of context/result refactor
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/llama_index/core/workflow/handler.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_streaming.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: lgtm, size:L

#16045 temporarily limit lancedb version
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/pyproject.toml
Labels: size:XS

#16053 Fix serde issue for huggingface inference API embedding
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-api/llama_index/embeddings/huggingface_api/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-api/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-api/tests/test_hf_inference.py
Labels: size:S

#16002 fix: fix regression in OctoAI llm provider after 0.11
  llama-index-integrations/llms/llama-index-llms-octoai/llama_index/llms/octoai/base.py
  llama-index-integrations/llms/llama-index-llms-octoai/llama_index/llms/octoai/utils.py
  llama-index-integrations/llms/llama-index-llms-octoai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-octoai/tests/test_llms_octoai.py
Labels: lgtm, size:M

#16057 update LanceDB integration
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/llama_index/vector_stores/lancedb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/pyproject.toml
Labels: lgtm, size:S

#16060 Adding docstring inside preprocess base code.
  llama-index-integrations/readers/llama-index-readers-preprocess/llama_index/readers/preprocess/base.py
Labels: lgtm, size:M

#16067 Add default to optional args for BedrockEmbedding
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/llama_index/embeddings/bedrock/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/tests/test_bedrock.py
Labels: size:S

#16069 fix vertex pydantic arguments
  llama-index-integrations/embeddings/llama-index-embeddings-vertex/llama_index/embeddings/vertex/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-vertex/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-vertex/tests/test_embeddings_vertex.py
Labels: size:S

#16078 Fix result order
  llama-index-integrations/graph_stores/llama-index-graph-stores-falkordb/llama_index/graph_stores/falkordb/falkordb_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-falkordb/pyproject.toml
Labels: lgtm, size:XS

#16083 fix elasticsearch embedding async function
  llama-index-integrations/embeddings/llama-index-embeddings-elasticsearch/llama_index/embeddings/elasticsearch/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-elasticsearch/pyproject.toml
Labels: lgtm, size:XS

#16081 docs: add decorators to the api reference
  docs/docs/api_reference/workflow/decorators.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/workflow/decorators.py
  llama-index-core/llama_index/core/workflow/retry_policy.py
Labels: docs, lgtm, size:S, topic:workflows

#16080 fix incorrect parameters in VertexAIIndex
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/llama_index/indices/managed/vertexai/base.py
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/pyproject.toml
Labels: lgtm, size:XS

#15971 feat: update JinaEmbedding for v3 release
  docs/docs/examples/embeddings/jinaai_embeddings.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-jinaai/pyproject.toml
Labels: lgtm, size:L

#16084 Mistralai enable custom endpoint from env
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/base.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
Labels: lgtm, size:S

#16091 Implement async for multi modal ollama
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-ollama/llama_index/multi_modal_llms/ollama/base.py
Labels: lgtm, size:M

#16070 Remove circular package dep
  llama-index-experimental/pyproject.toml
  llama-index-experimental/tests/BUILD
  llama-index-experimental/tests/param_tuner/BUILD
  llama-index-experimental/tests/param_tuner/__init__.py
  llama-index-experimental/tests/param_tuner/test_base.py
  llama-index-experimental/tests/param_tuner/test_param_tuner_classes.py
  llama-index-finetuning/pyproject.toml
  llama-index-finetuning/tests/BUILD
  llama-index-finetuning/tests/__init__.py
  llama-index-finetuning/tests/azure_openai/BUILD
  llama-index-finetuning/tests/azure_openai/__init__.py
  llama-index-finetuning/tests/azure_openai/test_azure_openai_classes.py
  llama-index-finetuning/tests/callbacks/BUILD
  llama-index-finetuning/tests/callbacks/__init__.py
  llama-index-finetuning/tests/callbacks/test_callback_classes.py
  llama-index-finetuning/tests/cross_encoders/BUILD
  llama-index-finetuning/tests/cross_encoders/__init__.py
  llama-index-finetuning/tests/cross_encoders/test_cross_encoder_classes.py
  llama-index-finetuning/tests/embeddings/BUILD
  llama-index-finetuning/tests/embeddings/__init__.py
  llama-index-finetuning/tests/embeddings/test_embeddings_classes.py
  llama-index-finetuning/tests/mistralai/BUILD
  llama-index-finetuning/tests/mistralai/__init__.py
  llama-index-finetuning/tests/mistralai/test_mistralai_classes.py
  llama-index-finetuning/tests/openai/BUILD
  llama-index-finetuning/tests/openai/__init__.py
  llama-index-finetuning/tests/openai/test_openai_classes.py
  llama-index-finetuning/tests/rerankers/BUILD
  llama-index-finetuning/tests/rerankers/__init__.py
  llama-index-finetuning/tests/rerankers/test_rerankers_classes.py
  llama-index-finetuning/tests/test_base.py
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/utils.py
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-adapter/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:L

#16101 [chore] fix incorrect `handler.context` for `handler.ctx` in docs
  docs/docs/module_guides/workflow/index.md
  docs/docs/understanding/workflows/observability.md
Labels: lgtm, size:XS

#16096 fix bug missing import
  llama-index-integrations/readers/llama-index-readers-box/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/image/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:XS

#16102 Add more workflow references to docs
  docs/docs/module_guides/workflow/index.md
  docs/docs/understanding/agent/basic_agent.md
  docs/docs/understanding/index.md
  docs/docs/use_cases/agents.md
  docs/docs/use_cases/q_and_a/index.md
  docs/mkdocs.yml
Labels: lgtm, size:M

#16104 fix cohere tests
  llama-index-integrations/llms/llama-index-llms-cohere/tests/test_llms_cohere.py
Labels: size:XS

#16105 Fix mongodb hybrid search, also pass hybrid_top_k in vector retriever
  llama-index-core/llama_index/core/indices/vector_store/retrievers/retriever.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/llama_index/vector_stores/mongodb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/pyproject.toml
Labels: size:S

#16112 bump openai agent deps
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
Labels: size:XS

#16113 Fixed up test_vectorstore.
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/conftest.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/test_vectorstore.py
Labels: lgtm, size:S

#16072 Issue 16071: wordpress requires username, password
  llama-index-integrations/readers/llama-index-readers-wordpress/README.md
  llama-index-integrations/readers/llama-index-readers-wordpress/llama_index/readers/wordpress/base.py
  llama-index-integrations/readers/llama-index-readers-wordpress/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-wordpress/tests/test_readers_wordpress.py
Labels: lgtm, size:S

#16050 feat: add configurable base_url field in rerank
  llama-index-integrations/postprocessor/llama-index-postprocessor-cohere-rerank/llama_index/postprocessor/cohere_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-cohere-rerank/pyproject.toml
Labels: lgtm, size:XS

#16052 Enhance Pandas Query Engine Output Processor
  llama-index-experimental/llama_index/experimental/query_engine/pandas/output_parser.py
  llama-index-experimental/pyproject.toml
Labels: lgtm, size:S

#16117 fix workflow docs
  docs/docs/index.md
  docs/mkdocs.yml
Labels: lgtm, size:XS

#16128 Wordpress: Allow control of whether Pages and/or Posts are retrieved
  llama-index-integrations/readers/llama-index-readers-wordpress/README.md
  llama-index-integrations/readers/llama-index-readers-wordpress/llama_index/readers/wordpress/base.py
  llama-index-integrations/readers/llama-index-readers-wordpress/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-wordpress/tests/test_readers_wordpress.py
Labels: lgtm, size:L

#16127 Async achat put operation
  llama-index-core/llama_index/core/chat_engine/condense_plus_context.py
  llama-index-core/llama_index/core/chat_engine/condense_question.py
  llama-index-core/llama_index/core/chat_engine/context.py
  llama-index-core/llama_index/core/chat_engine/simple.py
  llama-index-core/llama_index/core/memory/chat_summary_memory_buffer.py
  llama-index-core/llama_index/core/memory/simple_composable_memory.py
  llama-index-core/llama_index/core/memory/types.py
  llama-index-core/llama_index/core/storage/chat_store/base.py
  llama-index-core/llama_index/core/storage/chat_store/simple_chat_store.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azure/llama_index/storage/chat_store/azure/base.py
Labels: lgtm, size:L

#16115 [fix] handler.stream_events() doesn't yield `StopEvent`
  llama-index-core/llama_index/core/workflow/handler.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_streaming.py
Labels: lgtm, size:S

#16109 Improved TLM Rag cookbook
  docs/docs/examples/cookbooks/cleanlab_tlm_rag.ipynb
Labels: lgtm, size:L

#15969 Update chat message class for multi-modal
  llama-index-core/llama_index/core/agent/legacy/react/base.py
  llama-index-core/llama_index/core/agent/react/step.py
  llama-index-core/llama_index/core/agent/react_multimodal/step.py
  llama-index-core/llama_index/core/base/llms/base.py
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/llama_index/core/chat_engine/simple.py
  llama-index-core/llama_index/core/llms/function_calling.py
  llama-index-core/llama_index/core/llms/llm.py
  llama-index-core/llama_index/core/memory/chat_summary_memory_buffer.py
  llama-index-core/llama_index/core/prompts/base.py
  llama-index-core/llama_index/core/types.py
  llama-index-core/llama_index/core/utilities/token_counting.py
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/reflective/self_reflection.py
Labels: size:L

#16108 Add support for Path for SimpleDirectoryReader
  llama-index-core/llama_index/core/readers/file/base.py
  llama-index-integrations/readers/llama-index-readers-file/tests/test_file.py
Labels: lgtm, size:M

#16131 Add TopicNodeParser based on MedGraphRAG paper
  docs/docs/examples/node_parsers/topic_parser.ipynb
  llama-index-integrations/node_parser/llama-index-node-parser-topic/.gitignore
  llama-index-integrations/node_parser/llama-index-node-parser-topic/BUILD
  llama-index-integrations/node_parser/llama-index-node-parser-topic/Makefile
  llama-index-integrations/node_parser/llama-index-node-parser-topic/README.md
  llama-index-integrations/node_parser/llama-index-node-parser-topic/llama_index/node_parser/topic/BUILD
  llama-index-integrations/node_parser/llama-index-node-parser-topic/llama_index/node_parser/topic/__init__.py
  llama-index-integrations/node_parser/llama-index-node-parser-topic/llama_index/node_parser/topic/base.py
  llama-index-integrations/node_parser/llama-index-node-parser-topic/pyproject.toml
  llama-index-integrations/node_parser/llama-index-node-parser-topic/tests/BUILD
  llama-index-integrations/node_parser/llama-index-node-parser-topic/tests/__init__.py
  llama-index-integrations/node_parser/llama-index-node-parser-topic/tests/test_node_parser_topic.py
Labels: lgtm, size:XL

#16103 Sql markdown response
  llama-index-core/llama_index/core/indices/struct_store/sql_query.py
  llama-index-core/tests/indices/struct_store/test_sql_query.py
Labels: lgtm, size:M

#16134 v0.11.11
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/node_parser/topic.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-ollama/pyproject.toml
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azure/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#16141 Correct Pydantic warning(s) issed for llama-index-llms-ibm
  llama-index-integrations/llms/llama-index-llms-ibm/llama_index/llms/ibm/base.py
  llama-index-integrations/llms/llama-index-llms-ibm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ibm/tests/test_ibm.py
Labels: lgtm, size:M

#16150 Introducing new VoyageAI models
  docs/docs/examples/embeddings/voyageai.ipynb
  docs/docs/examples/node_postprocessor/VoyageAIRerank.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/llama_index/embeddings/voyageai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/pyproject.toml
Labels: lgtm, size:S

#16152 Add `required_exts` option to SharePoint reader
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/llama_index/readers/microsoft_sharepoint/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/tests/test_readers_microsoft_sharepoint.py
Labels: lgtm, size:M

#16151 User-defined schema in MilvusVectorStore
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:M

#15734 safe format prompt variables in strings with JSON
  llama-index-core/llama_index/core/llms/structured_llm.py
  llama-index-core/llama_index/core/prompts/base.py
  llama-index-core/llama_index/core/prompts/utils.py
  llama-index-core/tests/llms/test_structured_llm.py
  llama-index-core/tests/prompts/test_base.py
Labels: size:L

#16157 account for tools in prompt helper
  llama-index-core/llama_index/core/indices/common/struct_store/base.py
  llama-index-core/llama_index/core/indices/common_tree/base.py
  llama-index-core/llama_index/core/indices/prompt_helper.py
  llama-index-core/llama_index/core/indices/tree/inserter.py
  llama-index-core/llama_index/core/indices/tree/select_leaf_retriever.py
  llama-index-core/llama_index/core/program/function_program.py
  llama-index-core/llama_index/core/response_synthesizers/accumulate.py
  llama-index-core/llama_index/core/response_synthesizers/compact_and_accumulate.py
  llama-index-core/llama_index/core/response_synthesizers/compact_and_refine.py
  llama-index-core/llama_index/core/response_synthesizers/refine.py
  llama-index-core/llama_index/core/response_synthesizers/simple_summarize.py
  llama-index-core/llama_index/core/response_synthesizers/tree_summarize.py
  llama-index-core/llama_index/core/utilities/token_counting.py
  llama-index-core/tests/indices/response/test_tree_summarize.py
  llama-index-core/tests/tools/test_types.py
Labels: size:L

#16159 v0.11.12
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#16168 [docs] add cookbook about tracing LlamaIndex applications with Langfuse and PostHog
  docs/docs/examples/observability/LangfuseCallbackHandler.ipynb
  docs/docs/examples/observability/LangfuseMistralPostHog.ipynb
  docs/docs/examples/observability/img/dashboard-posthog-1.png
  docs/docs/examples/observability/img/dashboard-posthog-2.png
  docs/docs/examples/observability/img/integration-posthog-llamaindex-mistral.png
  docs/docs/module_guides/observability/index.md
Labels: lgtm, size:L

#16169 [Refactor] upgrading box sdk to >= 1.5.0
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxAPI/box_ai_extract_beta.py
  llama-index-integrations/readers/llama-index-readers-box/llama_index/readers/box/BoxAPI/box_api.py
  llama-index-integrations/readers/llama-index-readers-box/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-box/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-box/tests/test_tools_box_ai_extract.py
  llama-index-integrations/tools/llama-index-tools-box/tests/test_tools_box_ai_prompt.py
Labels: lgtm, size:L

#16137 Fixed issue #16089 where Neptune was adding additional labels
  docs/docs/examples/property_graph/property_graph_neptune.ipynb
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/analytics_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/base_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/database_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/pyproject.toml
Labels: lgtm, size:M

#16139 Async support for redis, dynamodb
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/llama_index/storage/chat_store/dynamodb/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/pyproject.toml
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-redis/llama_index/storage/chat_store/redis/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-redis/pyproject.toml
Labels: lgtm, size:L

#16153 [Vertex AI] Pass safety_settings to send_message methods to fix settings not being sent to API
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/utils.py
  llama-index-integrations/llms/llama-index-llms-vertex/pyproject.toml
Labels: size:S

#16164 feat: Depend on AstraPy 1.5 and above for AstraDBVectorStore
  docs/docs/examples/vector_stores/AstraDBIndexDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-astra-db/llama_index/vector_stores/astra_db/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-astra-db/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-astra-db/tests/test_astra_db.py
Labels: lgtm, size:S

#16100 Revert unintended consequence of string node representation update
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/base.py
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/custom.py
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/cypher_template.py
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/llm_synonym.py
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/text_to_cypher.py
  llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/vector.py
Labels: lgtm, size:M

#16172 markdown element node parser reliability
  llama-index-core/llama_index/core/instrumentation/events/llm.py
  llama-index-core/llama_index/core/node_parser/relational/base_element.py
  llama-index-core/llama_index/core/response_synthesizers/refine.py
Labels: size:M

#16179 Ollama Multimodal request timeout
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-ollama/llama_index/multi_modal_llms/ollama/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-ollama/pyproject.toml
Labels: lgtm, size:XS

#16189 add typing annotations
  llama-index-integrations/vector_stores/llama-index-vector-stores-timescalevector/llama_index/vector_stores/timescalevector/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-timescalevector/pyproject.toml
Labels: lgtm, size:S

#16190 v0.11.13
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/pyproject.toml
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-redis/llama_index/storage/chat_store/redis/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-redis/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#16193 allow non-flat metadata in mongodb
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/llama_index/vector_stores/mongodb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/pyproject.toml
Labels: size:XS

#16192 allow passing in httpx clients to llama-cloud
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/ingestion/api_utils.py
  llama-index-core/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/base.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
Labels: size:M

#16191 Add support for Mistral Multi modal LLM
  docs/docs/examples/multi_modal/mistral_multi_modal.ipynb
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/.gitignore
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/Makefile
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/README.md
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/llama_index/multi_modal_llms/mistralai/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/llama_index/multi_modal_llms/mistralai/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/llama_index/multi_modal_llms/mistralai/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/llama_index/multi_modal_llms/mistralai/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/tests/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/tests/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/tests/test_multi-modal-llms_mistral.py
Labels: lgtm, size:XL
