Repository run-llama/llama_index, pull requests merged in 2024-04, with the labels that each got.

#12300 [ReAct][Robustness++] When LLM failed to follow the response template, tell it so
  llama-index-core/llama_index/core/agent/react/base.py
  llama-index-core/llama_index/core/agent/react/step.py
  llama-index-core/tests/agent/react/test_react_agent.py
Labels: lgtm, size:L

#12452 v0.10.26
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/huggingface_itrex.md
  docs/docs/api_reference/llms/ipex_llm.md
  docs/docs/api_reference/postprocessor/rankllm_rerank.md
  docs/docs/api_reference/storage/vector_store/analyticdb.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ipex-llm/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-ipex-llm/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-ipex-llm/tests/test_llms_ipex_llm.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-kdbai/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#12469 Pydantic Fixes
  llama-index-core/llama_index/core/instrumentation/events/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/llama_index/embeddings/voyageai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/pyproject.toml
Labels: lgtm, size:S

#12470 alter qa embedding pair prompt
  llama-index-finetuning/llama_index/finetuning/embeddings/common.py
Labels: lgtm, size:XS

#12473 Fix bug with GCSReader
  llama-index-integrations/readers/llama-index-readers-gcs/llama_index/readers/gcs/base.py
Labels: lgtm, size:XS

#12417 Add `span_id` attribute to Events (instrumentation)
  llama-index-core/llama_index/core/agent/runner/base.py
  llama-index-core/llama_index/core/base/base_query_engine.py
  llama-index-core/llama_index/core/base/base_retriever.py
  llama-index-core/llama_index/core/base/embeddings/base.py
  llama-index-core/llama_index/core/chat_engine/types.py
  llama-index-core/llama_index/core/instrumentation/__init__.py
  llama-index-core/llama_index/core/instrumentation/dispatcher.py
  llama-index-core/llama_index/core/instrumentation/events/base.py
  llama-index-core/llama_index/core/instrumentation/events/llm.py
  llama-index-core/llama_index/core/instrumentation/events/span.py
  llama-index-core/llama_index/core/instrumentation/span/simple.py
  llama-index-core/llama_index/core/instrumentation/span_handlers/base.py
  llama-index-core/llama_index/core/instrumentation/span_handlers/null.py
  llama-index-core/llama_index/core/instrumentation/span_handlers/simple.py
  llama-index-core/llama_index/core/llms/callbacks.py
  llama-index-core/llama_index/core/llms/llm.py
  llama-index-core/llama_index/core/response_synthesizers/base.py
  llama-index-core/llama_index/core/response_synthesizers/refine.py
  llama-index-core/tests/instrumentation/test_dispatcher.py
  llama-index-integrations/callbacks/llama-index-callbacks-aim/tests/BUILD
  llama-index-integrations/callbacks/llama-index-callbacks-aim/tests/__init__.py
  llama-index-integrations/callbacks/llama-index-callbacks-aim/tests/test_aim_callback.py
Labels: lgtm, size:XL

#12496 Fix typo ; Update index.md
  docs/docs/index.md
Labels: lgtm, size:XS

#12488 Update documentation to include instructions for setting OPENAI_API_KEY for Qdrant Vector Store
  docs/docs/examples/vector_stores/QdrantIndexDemo.ipynb
Labels: lgtm, size:M

#12493 Updated Watsonx foundation models
  llama-index-integrations/llms/llama-index-llms-watsonx/llama_index/llms/watsonx/utils.py
  llama-index-integrations/llms/llama-index-llms-watsonx/pyproject.toml
Labels: lgtm, size:S

#12491 Updated base model name on watsonx integration
  llama-index-integrations/llms/llama-index-llms-watsonx/llama_index/llms/watsonx/base.py
  llama-index-integrations/llms/llama-index-llms-watsonx/pyproject.toml
Labels: lgtm, size:XS

#12457 docs: document duplicate strategies
  llama-index-core/llama_index/core/ingestion/pipeline.py
Labels: lgtm, size:XS

#12446 feat: text embedding integration: Cloudflare Workers AI
  docs/docs/examples/embeddings/cloudflare_workersai.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-cloudflare-workersai/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-cloudflare-workersai/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-cloudflare-workersai/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-cloudflare-workersai/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-cloudflare-workersai/llama_index/embeddings/cloudflare_workersai/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-cloudflare-workersai/llama_index/embeddings/cloudflare_workersai/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-cloudflare-workersai/llama_index/embeddings/cloudflare_workersai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-cloudflare-workersai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-cloudflare-workersai/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-cloudflare-workersai/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-cloudflare-workersai/tests/test_embeddings_cloudflare-workersai.py
Labels: lgtm, size:L

#12437 Resolve ImportError for 'MessageContentText' Due to Typing Update in openai.types.beta.threads
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/openai_assistant_agent.py
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
Labels: lgtm, size:XS

#12507 vbump openai agent
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
Labels: size:XS

#12434 Replace redis driver with FalkorDB driver
  llama-index-integrations/graph_stores/llama-index-graph-stores-falkordb/llama_index/graph_stores/falkordb/base.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-falkordb/pyproject.toml
Labels: lgtm, size:XS

#12423 Add support for Neptune Analytics as a Vector Store
  docs/docs/community/integrations/graph_stores.md
  docs/docs/community/integrations/vector_stores.md
  docs/docs/examples/vector_stores/AmazonNeptuneVectorDemo.ipynb
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/analytics.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/database.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-neptune/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-neptune/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-neptune/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-neptune/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-neptune/llama_index/vector_stores/neptune/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-neptune/llama_index/vector_stores/neptune/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-neptune/llama_index/vector_stores/neptune/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-neptune/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-neptune/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-neptune/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-neptune/tests/test_vector_stores_neptune.py
Labels: lgtm, size:XL

#12432 Integrations with DataBricks
  docs/docs/examples/llm/databricks.ipynb
  llama-index-integrations/llms/llama-index-llms-databricks/.gitignore
  llama-index-integrations/llms/llama-index-llms-databricks/BUILD
  llama-index-integrations/llms/llama-index-llms-databricks/Makefile
  llama-index-integrations/llms/llama-index-llms-databricks/README.md
  llama-index-integrations/llms/llama-index-llms-databricks/llama_index/llms/databricks/BUILD
  llama-index-integrations/llms/llama-index-llms-databricks/llama_index/llms/databricks/__init__.py
  llama-index-integrations/llms/llama-index-llms-databricks/llama_index/llms/databricks/base.py
  llama-index-integrations/llms/llama-index-llms-databricks/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-databricks/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-databricks/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-databricks/tests/test_integration_databricks.py
  llama-index-integrations/llms/llama-index-llms-databricks/tests/test_llms_databricks.py
Labels: lgtm, size:L

#12103 Add tidb vector indtroduction in module guides
  docs/docs/community/integrations/vector_stores.md
  docs/docs/examples/vector_stores/TiDBVector.ipynb
  docs/docs/module_guides/storing/vector_stores.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/llama_index/vector_stores/tidbvector/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-tidbvector/pyproject.toml
Labels: lgtm, size:S

#12503 FLAREInstructQueryEngine : delegating retriever api if the query engine supports it
  llama-index-core/llama_index/core/query_engine/flare/base.py
Labels: lgtm, size:S

#12530 chore: bumps langfuse version to 2.21.2
  llama-index-integrations/callbacks/llama-index-callbacks-langfuse/pyproject.toml
Labels: lgtm, size:XS

#12529 update low-level fusion notebook
  docs/docs/examples/low_level/fusion_retriever.ipynb
Labels: size:L

#12528 Fixes a typo in docstores.md
  docs/docs/module_guides/storing/docstores.md
Labels: lgtm, size:XS

#12527 Add OTPP Presentation notebook
  docs/docs/presentations/materials/2024-04-02-otpp.ipynb
Labels: lgtm, size:XL

#12521 Mistaken word , soon --> sun
  docs/docs/getting_started/reading.md
Labels: lgtm, size:XS

#12526 Make chat message to dict safer
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/pyproject.toml
  pants.toml
Labels: size:XS

#12520 Readability web page reader fix playwright async api bug
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/readability_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-web/requirements.txt
Labels: lgtm, size:M

#12475 Add RankGPT support inside RankLLM
  docs/docs/examples/node_postprocessor/rankLLM.ipynb
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/examples/rankLLM.ipynb
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/llama_index/postprocessor/rankllm_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/pyproject.toml
Labels: lgtm, size:M

#12515 Kdbai changes
  docs/docs/examples/vector_stores/KDBAI_Advanced_RAG_Demo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-kdbai/llama_index/vector_stores/kdbai/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-kdbai/pyproject.toml
Labels: lgtm, size:S

#12559 pants fixes
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-itrex/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-itrex/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-itrex/tests/test_embeddings_huggingface_itrex.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum/tests/test_embeddings_huggingface_optimum.py
  llama-index-integrations/llms/llama-index-llms-nvidia-triton/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-nvidia-triton/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-nvidia-triton/tests/test_llms_nvidia_triton.py
  pants.toml
Labels: size:S

#12562 vbump to revert duckdb breaking changes
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/pyproject.toml
Labels: size:XS

#12561 Add public method to set Qdrant query functions
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
Labels: lgtm, size:S

#12558 Add ability to pass custom HTTP headers to Anthropic client
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: lgtm, size:S

#12563 fix check in batch eval runner for multi-kwargs
  llama-index-core/llama_index/core/evaluation/batch_runner.py
Labels: lgtm, size:XS

#12581 Add support for Cohere Command R+ model
  llama-index-integrations/llms/llama-index-llms-cohere/llama_index/llms/cohere/utils.py
  llama-index-integrations/llms/llama-index-llms-cohere/pyproject.toml
Labels: lgtm, size:XS

#12586 Add notebook for vector pe lab talk
  docs/docs/presentations/materials/2024-04-04-vector-pe-lab.ipynb
  docs/docs/presentations/past_presentations.md
Labels: size:XL

#12583 fix(postgres): numeric metadata filters
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: lgtm, size:S

#12570 Minor lint improvements to Dockerfiles
  llama-index-legacy/tests/initialization/postgres/Dockerfile
  llama-index-networks/examples/demo/contributor-1/Dockerfile
  llama-index-networks/examples/demo/contributor-2/Dockerfile
Labels: lgtm, size:S

#12577 Added support to load clip model from local file path
  llama-index-integrations/embeddings/llama-index-embeddings-clip/llama_index/embeddings/clip/base.py
Labels: lgtm, size:XS

#12566 Fixes #11389 (agent_react_multimodal_step.py bug)
  llama-index-core/llama_index/core/agent/react_multimodal/step.py
Labels: lgtm, size:S

#12590 v0.10.27
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/cloudflare_workersai.md
  docs/docs/api_reference/llms/databricks.md
  docs/docs/api_reference/storage/vector_store/neptune.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-finetuning/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-clip/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#12591 add anthropic tool calling
  docs/docs/examples/agent/anthropic_agent.ipynb
  docs/mkdocs.yml
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: size:XL

#12611 Bug fix - Similarity metric is always IP for MilvusVectorStore
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:S

#12607 Add streaming support for DenseXRetrievalPack
  llama-index-packs/llama-index-packs-dense-x-retrieval/README.md
  llama-index-packs/llama-index-packs-dense-x-retrieval/llama_index/packs/dense_x_retrieval/base.py
  llama-index-packs/llama-index-packs-dense-x-retrieval/pyproject.toml
Labels: lgtm, size:S

#12606 bump google-generativeai to 0.4
  llama-index-integrations/embeddings/llama-index-embeddings-gemini/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-google/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-palm/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-google/pyproject.toml
Labels: lgtm, size:S

#12595 Update DataBricks to Databricks and renamed environment variables
  llama-index-integrations/llms/llama-index-llms-databricks/README.md
  llama-index-integrations/llms/llama-index-llms-databricks/llama_index/llms/databricks/__init__.py
  llama-index-integrations/llms/llama-index-llms-databricks/llama_index/llms/databricks/base.py
  llama-index-integrations/llms/llama-index-llms-databricks/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-databricks/tests/test_integration_databricks.py
  llama-index-integrations/llms/llama-index-llms-databricks/tests/test_llms_databricks.py
Labels: lgtm, size:M

#12594 Update bagel ml (#4)
  docs/docs/examples/vector_stores/BagelAutoRetriever.ipynb
  docs/docs/examples/vector_stores/BagelIndexDemo.ipynb
Labels: lgtm, size:M

#12615 Fix MarkdownNodeParser ref_doc_id
  llama-index-core/llama_index/core/node_parser/relational/markdown_element.py
  llama-index-core/tests/node_parser/test_markdown_element.py
Labels: lgtm, size:S

#12616 Added multilingual support for the Wikipedia reader.
  llama-index-integrations/readers/llama-index-readers-wikipedia/llama_index/readers/wikipedia/base.py
  llama-index-integrations/readers/llama-index-readers-wikipedia/pyproject.toml
Labels: lgtm, size:S

#12622 Update base.py
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/drive/README.md
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/drive/base.py
Labels: lgtm, size:S

#12620 Add async_postprocess_nodes at RankGPT Postprocessor Nodes
  llama-index-core/llama_index/core/postprocessor/rankGPT_rerank.py
  llama-index-core/tests/postprocessor/test_rankgpt_rerank.py
Labels: lgtm, size:L

#12636 Update query engine initialization to use Settings.llm
  docs/docs/examples/agent/multi_document_agents.ipynb
Labels: lgtm, size:XS

#12624 Fix ErrorHandling: adding err handling in eval_utils default_parser for correctness
  llama-index-core/llama_index/core/evaluation/eval_utils.py
Labels: lgtm, size:S

#12589 Coroutine-safe Spans
  llama-index-core/llama_index/core/async_utils.py
  llama-index-core/llama_index/core/instrumentation/dispatcher.py
  llama-index-core/llama_index/core/instrumentation/span_handlers/base.py
  llama-index-core/tests/instrumentation/test_dispatcher.py
Labels: lgtm, size:L

#12645 fix llama-index-multi-modal-llms-gemini dependency
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/pyproject.toml
Labels: lgtm, size:XS

#12635 [community] add more data types support to `ipex-llm` llm integration
  docs/docs/examples/llm/ipex_llm.ipynb
  llama-index-integrations/llms/llama-index-llms-ipex-llm/README.md
  llama-index-integrations/llms/llama-index-llms-ipex-llm/examples/BUILD
  llama-index-integrations/llms/llama-index-llms-ipex-llm/examples/README.md
  llama-index-integrations/llms/llama-index-llms-ipex-llm/examples/more_data_type.py
  llama-index-integrations/llms/llama-index-llms-ipex-llm/llama_index/llms/ipex_llm/base.py
  llama-index-integrations/llms/llama-index-llms-ipex-llm/pyproject.toml
Labels: lgtm, size:L

#12655 Fix many GitHub issues
  llama-index-core/llama_index/core/node_parser/text/sentence.py
  llama-index-core/llama_index/core/response_synthesizers/__init__.py
  llama-index-core/llama_index/core/response_synthesizers/simple_summarize.py
  llama-index-integrations/llms/llama-index-llms-openllm/llama_index/llms/openllm/base.py
  llama-index-integrations/llms/llama-index-llms-openllm/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/docs/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
  llama-index-packs/llama-index-packs-llama-dataset-metadata/llama_index/packs/llama_dataset_metadata/base.py
  llama-index-packs/llama-index-packs-llama-dataset-metadata/pyproject.toml
Labels: size:M

#12658 Update index.md - fix typo
  docs/docs/index.md
Labels: lgtm, size:XS

#12638 Thread-safe instrumentation
  llama-index-core/llama_index/core/instrumentation/dispatcher.py
  llama-index-core/llama_index/core/instrumentation/span_handlers/base.py
  llama-index-core/llama_index/core/instrumentation/span_handlers/simple.py
  llama-index-core/tests/instrumentation/test_dispatcher.py
Labels: lgtm, size:L

#12661 Update broken link for JSON Loader
  docs/docs/module_guides/loading/simpledirectoryreader.md
Labels: lgtm, size:XS

#12647 Add retry for batch runner
  llama-index-core/llama_index/core/evaluation/batch_runner.py
Labels: lgtm, size:S

#12587 Tool return direct
  docs/docs/examples/agent/return_direct_agent.ipynb
  docs/docs/module_guides/deploying/agents/usage_pattern.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/agent/function_calling/step.py
  llama-index-core/llama_index/core/agent/react/step.py
  llama-index-core/llama_index/core/agent/react/types.py
  llama-index-core/llama_index/core/agent/react_multimodal/step.py
  llama-index-core/llama_index/core/agent/runner/base.py
  llama-index-core/llama_index/core/chat_engine/types.py
  llama-index-core/llama_index/core/tools/calling.py
  llama-index-core/llama_index/core/tools/function_tool.py
  llama-index-core/llama_index/core/tools/ondemand_loader_tool.py
  llama-index-core/llama_index/core/tools/query_engine.py
  llama-index-core/llama_index/core/tools/types.py
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/step.py
Labels: lgtm, size:XL

#12663 Add missing node postprocessor in CondensePlusContextChatEngine async mode.
  llama-index-core/llama_index/core/chat_engine/condense_plus_context.py
Labels: lgtm, size:XS

#12654 query pipeline memory loop example
  docs/docs/examples/pipeline/query_pipeline_memory.ipynb
  docs/docs/module_guides/querying/pipeline/modules.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/query_pipeline/components/argpacks.py
Labels: size:L

#12626 Added support to retrieve metadata fields from milvus
  llama-index-core/llama_index/core/indices/vector_store/retrievers/retriever.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:S

#12646 Fix incomplete json output in guideline evaluator
  llama-index-core/llama_index/core/evaluation/guideline.py
Labels: lgtm, size:XS

#12393 Support indented code block fences
  llama-index-core/llama_index/core/node_parser/file/markdown.py
  llama-index-core/tests/node_parser/test_markdown.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:M

#12643 Add OpenVINO embedding
  docs/docs/examples/embeddings/openvino.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/llama_index/embeddings/huggingface_openvino/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/llama_index/embeddings/huggingface_openvino/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/llama_index/embeddings/huggingface_openvino/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/tests/test_embeddings_huggingface_openvino.py
Labels: lgtm, size:L

#12664 Improve efficiency of MongoDB reader
  llama-index-integrations/readers/llama-index-readers-mongodb/llama_index/readers/mongodb/base.py
  llama-index-integrations/readers/llama-index-readers-mongodb/pyproject.toml
Labels: lgtm, size:XS

#12672 fix: elasticsearch indexstore for collection name to index
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-elasticsearch/llama_index/storage/index_store/elasticsearch/base.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-elasticsearch/pyproject.toml
Labels: lgtm, size:XS

#12678 v0.10.28
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/openvino.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/llama_index/multi_modal_llms/openai/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:L

#12639 Add OpenVINO LLMs
  docs/docs/examples/llm/openvino.ipynb
  llama-index-integrations/llms/llama-index-llms-openvino/.gitignore
  llama-index-integrations/llms/llama-index-llms-openvino/BUILD
  llama-index-integrations/llms/llama-index-llms-openvino/Makefile
  llama-index-integrations/llms/llama-index-llms-openvino/README.md
  llama-index-integrations/llms/llama-index-llms-openvino/llama_index/llms/openvino/BUILD
  llama-index-integrations/llms/llama-index-llms-openvino/llama_index/llms/openvino/__init__.py
  llama-index-integrations/llms/llama-index-llms-openvino/llama_index/llms/openvino/base.py
  llama-index-integrations/llms/llama-index-llms-openvino/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openvino/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-openvino/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-openvino/tests/test_llms_openvino.py
Labels: lgtm, size:XL

#12676 Modernize GuardrailsOutputParser
  docs/docs/examples/output_parsing/GuardrailsDemo.ipynb
  llama-index-integrations/output_parsers/llama-index-output-parsers-guardrails/llama_index/output_parsers/guardrails/base.py
  llama-index-integrations/output_parsers/llama-index-output-parsers-guardrails/pyproject.toml
Labels: lgtm, size:L

#12687 Fix docs build
  docs/docs/api_reference/embeddings/openvino.md
  docs/mkdocs.yml
Labels: size:XS

#12691 return_direct notebook nits
  docs/docs/examples/agent/return_direct_agent.ipynb
Labels: lgtm, size:XS

#12512 refactor: Switch default Qdrant sparse encoder
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
Labels: lgtm, size:M

#12684 [openvino embedding]avoid model compiling during saving
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/llama_index/embeddings/huggingface_openvino/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/pyproject.toml
Labels: lgtm, size:XS

#12704 small milvus bug fix
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: size:XS

#12681 Refactor kvdocstore delete methods
  llama-index-core/llama_index/core/storage/docstore/keyval_docstore.py
  llama-index-core/tests/storage/docstore/test_simple_docstore.py
Labels: lgtm, size:L

#12688 Add openvino rerank support
  docs/docs/examples/node_postprocessor/openvino_rerank.ipynb
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/Makefile
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/llama_index/postprocessor/openvino_rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/llama_index/postprocessor/openvino_rerank/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/llama_index/postprocessor/openvino_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/tests/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/tests/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/tests/test_postprocessor_openvino_rerank.py
Labels: lgtm, size:XL

#12386 Update redis vector store
  docs/docs/community/integrations/vector_stores.md
  docs/docs/examples/ingestion/ingestion_gdrive.ipynb
  docs/docs/examples/ingestion/redis_ingestion_pipeline.ipynb
  docs/docs/examples/vector_stores/RedisIndexDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/schema.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/pyproject.toml
Labels: lgtm, size:XXL

#12416 Update embedding field to use fixed array size
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/llama_index/vector_stores/duckdb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/tests/test_duckdb.py
Labels: lgtm, size:M

#12695 Fix elasticsearch hybrid rrf window_size
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/tests/test_vector_stores_elasticsearch.py
Labels: lgtm, size:S

#12714 [#12713] Fix documentation for Postgres classes
  llama-index-core/llama_index/core/storage/docstore/postgres_docstore.py
  llama-index-core/llama_index/core/storage/kvstore/postgres_kvstore.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-postgres/llama_index/storage/docstore/postgres/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-postgres/llama_index/storage/kvstore/postgres/base.py
Labels: lgtm, size:M

#12741 doc nit: rearrange module guide
  docs/mkdocs.yml
Labels: lgtm, size:M

#12736 [BUGFIX] Update LlamaIndex-Predibase Integration
  docs/docs/examples/llm/predibase.ipynb
  llama-index-integrations/llms/llama-index-llms-predibase/llama_index/llms/predibase/base.py
  llama-index-integrations/llms/llama-index-llms-predibase/pyproject.toml
Labels: lgtm, size:M

#12705 Update cohere and add async support
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/llama_index/embeddings/cohere/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/pyproject.toml
Labels: lgtm, size:M

#12746 Revert _
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/llama_index/embeddings/cohere/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/pyproject.toml
Labels: lgtm, size:S

#12742 fix multidoc hyde notebook
  docs/docs/examples/agent/agent_runner/agent_around_query_pipeline_with_HyDE_for_PDFs.ipynb
Labels: lgtm, size:XS

#12747 fix(docs): langfuse link to notebook on observability page
  docs/docs/module_guides/observability/index.md
Labels: lgtm, size:XS

#12739 nit: custom agent pass kwargs
  llama-index-core/llama_index/core/agent/custom/simple.py
Labels: size:XS

#12737 Add Amazon Bedrock knowledge base integration as retriever
  docs/docs/examples/retrievers/bedrock_retriever.ipynb
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/.gitignore
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/Makefile
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/README.md
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/llama_index/retrievers/bedrock/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/llama_index/retrievers/bedrock/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/llama_index/retrievers/bedrock/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/tests/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/tests/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/tests/test_retrievers_bedrock.py
Labels: lgtm, size:L

#12763 Use None as the default value for s3_endpoint_url in S3Reader
  llama-index-integrations/readers/llama-index-readers-s3/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-s3/llama_index/readers/s3/base.py
  llama-index-integrations/readers/llama-index-readers-s3/pyproject.toml
Labels: lgtm, size:S

#12757 Chain-of-Abstraction Agent Pack
  docs/docs/api_reference/instrumentation/event_handlers.md
  docs/docs/api_reference/instrumentation/event_types.md
  docs/docs/api_reference/instrumentation/span_handlers.md
  docs/docs/api_reference/instrumentation/span_types.md
  docs/docs/api_reference/llms/openvino.md
  docs/docs/api_reference/packs/agents_coa.md
  docs/docs/api_reference/postprocessor/openvino_rerank.md
  docs/docs/examples/agent/coa_agent.ipynb
  docs/mkdocs.yml
  llama-index-packs/llama-index-packs-agents-coa/.gitignore
  llama-index-packs/llama-index-packs-agents-coa/BUILD
  llama-index-packs/llama-index-packs-agents-coa/Makefile
  llama-index-packs/llama-index-packs-agents-coa/README.md
  llama-index-packs/llama-index-packs-agents-coa/llama_index/packs/agents_coa/BUILD
  llama-index-packs/llama-index-packs-agents-coa/llama_index/packs/agents_coa/__init__.py
  llama-index-packs/llama-index-packs-agents-coa/llama_index/packs/agents_coa/base.py
  llama-index-packs/llama-index-packs-agents-coa/llama_index/packs/agents_coa/output_parser.py
  llama-index-packs/llama-index-packs-agents-coa/llama_index/packs/agents_coa/prompts.py
  llama-index-packs/llama-index-packs-agents-coa/llama_index/packs/agents_coa/step.py
  llama-index-packs/llama-index-packs-agents-coa/llama_index/packs/agents_coa/utils.py
  llama-index-packs/llama-index-packs-agents-coa/pyproject.toml
  llama-index-packs/llama-index-packs-agents-coa/tests/BUILD
  llama-index-packs/llama-index-packs-agents-coa/tests/__init__.py
  llama-index-packs/llama-index-packs-agents-coa/tests/test_packs_agents.py
Labels: lgtm, size:XXL

#12800 nit: COA colab badge
  docs/docs/examples/agent/coa_agent.ipynb
Labels: size:XS

#12519 Add mongodb atlas bm25 retriever
  llama-index-integrations/retrievers/llama-index-retrievers-mongodb-atlas-bm25-retriever/.gitignore
  llama-index-integrations/retrievers/llama-index-retrievers-mongodb-atlas-bm25-retriever/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-mongodb-atlas-bm25-retriever/Makefile
  llama-index-integrations/retrievers/llama-index-retrievers-mongodb-atlas-bm25-retriever/README.md
  llama-index-integrations/retrievers/llama-index-retrievers-mongodb-atlas-bm25-retriever/llama_index/retrievers/mongodb_atlas_bm25_retriever/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-mongodb-atlas-bm25-retriever/llama_index/retrievers/mongodb_atlas_bm25_retriever/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-mongodb-atlas-bm25-retriever/llama_index/retrievers/mongodb_atlas_bm25_retriever/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-mongodb-atlas-bm25-retriever/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-mongodb-atlas-bm25-retriever/tests/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-mongodb-atlas-bm25-retriever/tests/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-mongodb-atlas-bm25-retriever/tests/test_retrievers_bm25_retriever.py
Labels: lgtm, size:L

#12803 fix: wrong doc id when using default s3 endpoint in S3Reader
  llama-index-integrations/readers/llama-index-readers-s3/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-s3/llama_index/readers/s3/base.py
  llama-index-integrations/readers/llama-index-readers-s3/pyproject.toml
Labels: lgtm, size:S

#12789 [FEATURE] Enable choice of either Predibase-hosted or HuggingFace-hosted fine-tuned adapters in LlamaIndex-Predibase integration.
  docs/docs/examples/llm/predibase.ipynb
  llama-index-integrations/llms/llama-index-llms-predibase/llama_index/llms/predibase/base.py
  llama-index-integrations/llms/llama-index-llms-predibase/pyproject.toml
Labels: lgtm, size:M

#12802 fix message serialization in redis chat store
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-redis/llama_index/storage/chat_store/redis/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-redis/pyproject.toml
Labels: size:XS

#12773 fix wrong params
  llama-index-integrations/llms/llama-index-llms-openai-like/llama_index/llms/openai_like/base.py
Labels: lgtm, size:XS

#12752 Update VoyageAI embeddings example
  docs/docs/examples/embeddings/voyageai.ipynb
Labels: size:XS

#12758 make pip check work for optional pdf packages
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: size:XS

#12715 Fix chunking error
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/code_hierarchy.py
  llama-index-packs/llama-index-packs-code-hierarchy/pyproject.toml
  llama-index-packs/llama-index-packs-code-hierarchy/tests/test_code_parse_nodes_special_characters.py
Labels: lgtm, size:M

#12804 Support for Mistral Large from Bedrock
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
Labels: lgtm, size:XS

#12771 Update bedrock notebook to use the retriever with bedrock llms
  docs/docs/examples/retrievers/bedrock_retriever.ipynb
Labels: lgtm, size:M

#12792 Relax dependency version to accept astrapy 1.*
  llama-index-integrations/readers/llama-index-readers-astra-db/Makefile
  llama-index-integrations/readers/llama-index-readers-astra-db/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-astra-db/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-astra-db/tests/test_astra_db.py
  llama-index-integrations/readers/llama-index-readers-astra-db/tests/test_readers_astra_db.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-astra-db/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-astra-db/llama_index/vector_stores/astra_db/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-astra-db/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-astra-db/tests/test_vector_stores_astra_db.py
Labels: lgtm, size:L

#12751 Fix bug in raft dataset generator - multiple system prompts
  llama-index-packs/llama-index-packs-raft-dataset/llama_index/packs/raft_dataset/base.py
  llama-index-packs/llama-index-packs-raft-dataset/pyproject.toml
Labels: lgtm, size:XS

#12680 Add support for Couchbase as a Vector Store
  docs/docs/community/integrations/vector_stores.md
  docs/docs/examples/vector_stores/CouchbaseVectorStoreDemo.ipynb
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/llama_index/vector_stores/couchbase/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/llama_index/vector_stores/couchbase/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/llama_index/vector_stores/couchbase/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/tests/test_vector_stores_couchbase.py
Labels: lgtm, size:XXL

#12812 update async utils
  llama-index-core/llama_index/core/async_utils.py
Labels: lgtm, size:S

#12762 fix pyproject.toml in core for 3.12
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/tests/test_embeddings_huggingface_openvino.py
  poetry.lock
Labels: lgtm, size:S

#12805 fix for complex conditional links in query pipeline
  llama-index-core/llama_index/core/query_pipeline/query.py
  llama-index-core/tests/query_pipeline/test_query.py
Labels: size:L

#12817 v0.10.29
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/ipex_llm.md
  docs/docs/api_reference/retrievers/bedrock.md
  docs/docs/api_reference/retrievers/mongodb_atlas_bm25_retriever.md
  docs/docs/api_reference/storage/vector_store/couchbase.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#12821 Clarify Token Reservation Comment
  docs/docs/module_guides/supporting_modules/settings.md
Labels: lgtm, size:XS

#12823 add OR filter condition support to simple vector store
  llama-index-core/llama_index/core/vector_stores/simple.py
  llama-index-core/tests/vector_stores/test_simple.py
Labels: lgtm, size:M

#12824 nits: agent / tool imports, custom agent callbacks
  llama-index-core/llama_index/core/agent/__init__.py
  llama-index-core/llama_index/core/agent/custom/simple.py
  llama-index-core/llama_index/core/tools/__init__.py
Labels: lgtm, size:S

#10972 add vearch to vector store
  docs/docs/examples/vector_stores/VearchDemo.ipynb
  docs/docs/module_guides/storing/vector_stores.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-vearch/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-vearch/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-vearch/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-vearch/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-vearch/examples/VearchDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-vearch/llama_index/vector_stores/vearch/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-vearch/llama_index/vector_stores/vearch/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-vearch/llama_index/vector_stores/vearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-vearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-vearch/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-vearch/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-vearch/tests/test_vector_stores_vearch.py
Labels: lgtm, size:XL

#12740 [Community] add `ipex-llm` embedding integration
  docs/docs/examples/embeddings/ipex_llm.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/llama_index/embeddings/ipex_llm/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/llama_index/embeddings/ipex_llm/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/llama_index/embeddings/ipex_llm/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/llama_index/embeddings/ipex_llm/utils.py
  llama-index-integrations/embeddings/llama-index-embeddings-ipex-llm/pyproject.toml
Labels: lgtm, size:L

#12785 [community] add support for loading "low-bit format" model to `IpexLLM` integration
  docs/docs/examples/llm/ipex_llm.ipynb
  llama-index-integrations/llms/llama-index-llms-ipex-llm/examples/README.md
  llama-index-integrations/llms/llama-index-llms-ipex-llm/examples/more_data_type.py
  llama-index-integrations/llms/llama-index-llms-ipex-llm/llama_index/llms/ipex_llm/base.py
  llama-index-integrations/llms/llama-index-llms-ipex-llm/pyproject.toml
Labels: lgtm, size:L

#12808 fix: pipline load without docstore
  llama-index-core/llama_index/core/ingestion/pipeline.py
  llama-index-core/tests/ingestion/test_pipeline.py
Labels: lgtm, size:M

#12825 feat: Firecrawl Web Loader
  docs/docs/examples/data_connectors/WebPageDemo.ipynb
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/__init__.py
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/firecrawl_web/BUILD
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/firecrawl_web/README.md
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/firecrawl_web/__init__.py
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/firecrawl_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/firecrawl_web/requirements.txt
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:L

#12819 Add the ability to pass custom headers to Anthropic LLM requests
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  llama-index-legacy/llama_index/legacy/llms/anthropic.py
Labels: lgtm, size:S

#12846 Use async `_aprocess_actions` in `_arun_step_stream`
  llama-index-core/llama_index/core/agent/react/step.py
Labels: lgtm, size:XS

#12847 Fix generate_openai_multi_modal_chat_message import in examples doc
  docs/docs/examples/multi_modal/openai_multi_modal.ipynb
Labels: lgtm, size:XS

#12837 fix: batch insertions into Milvus vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:S

#12844 Update base.py
  llama-index-integrations/readers/llama-index-readers-smart-pdf-loader/llama_index/readers/smart_pdf_loader/base.py
  llama-index-integrations/readers/llama-index-readers-smart-pdf-loader/pyproject.toml
Labels: lgtm, size:XS

#12818 Expose azure_ad_token_provider argument to support token expiration
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/llama_index/embeddings/azure_openai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-azure-openai/llama_index/llms/azure_openai/base.py
  llama-index-integrations/llms/llama-index-llms-azure-openai/pyproject.toml
Labels: lgtm, size:S

#12683 Add intermediate outputs to QueryPipeline
  docs/docs/examples/pipeline/query_pipeline.ipynb
  docs/docs/module_guides/querying/pipeline/usage_pattern.md
  llama-index-core/llama_index/core/base/query_pipeline/query.py
  llama-index-core/llama_index/core/query_pipeline/query.py
  llama-index-core/tests/query_pipeline/test_query.py
Labels: lgtm, size:L

#12848 feat: add retry on pypdf
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/docs/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:S

#12861 Find Import Bug
  docs/docs/module_guides/querying/node_postprocessors/index.md
Labels: lgtm, size:XS

#12857 Octoai embeddings
  docs/docs/examples/embeddings/octoai.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-octoai/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-octoai/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-octoai/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-octoai/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-octoai/llama_index/embeddings/octoai/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-octoai/llama_index/embeddings/octoai/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-octoai/llama_index/embeddings/octoai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-octoai/llama_index/embeddings/octoai/utils.py
  llama-index-integrations/embeddings/llama-index-embeddings-octoai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-octoai/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-octoai/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-octoai/tests/test_embeddings_octoai.py
Labels: lgtm, size:L

#12882 Catch validation errors
  llama-index-core/llama_index/core/ingestion/data_sinks.py
  llama-index-core/llama_index/core/ingestion/data_sources.py
  llama-index-core/llama_index/core/ingestion/transformations.py
Labels: size:M

#12894 Update mistralai api
  docs/docs/examples/cookbooks/mistralai.ipynb
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/utils.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
Labels: lgtm, size:L

#12897 Fix show progress being out of order
  llama-index-core/llama_index/core/async_utils.py
Labels: size:XS

#12896 Add httpx_async_client option
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/llama_index/embeddings/cohere/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/tests/test_embeddings.py
Labels: lgtm, size:M

#12856 Add changes for bedrock documentation and notebook
  docs/docs/examples/retrievers/bedrock_retriever.ipynb
  docs/docs/module_guides/querying/retriever/retrievers.md
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/pyproject.toml
Labels: lgtm, size:S

#12902 fix bug in load and search tool spec
  llama-index-core/llama_index/core/tools/tool_spec/load_and_search/base.py
Labels: size:XS

#12735 [WIP] LATS agent pack
  docs/docs/examples/agent/lats_agent.ipynb
  llama-index-core/llama_index/core/agent/__init__.py
  llama-index-core/llama_index/core/agent/custom/simple.py
  llama-index-core/llama_index/core/agent/react/__init__.py
  llama-index-packs/llama-index-packs-agents-lats/.gitignore
  llama-index-packs/llama-index-packs-agents-lats/BUILD
  llama-index-packs/llama-index-packs-agents-lats/Makefile
  llama-index-packs/llama-index-packs-agents-lats/README.md
  llama-index-packs/llama-index-packs-agents-lats/llama_index/packs/agents_lats/BUILD
  llama-index-packs/llama-index-packs-agents-lats/llama_index/packs/agents_lats/__init__.py
  llama-index-packs/llama-index-packs-agents-lats/llama_index/packs/agents_lats/base.py
  llama-index-packs/llama-index-packs-agents-lats/llama_index/packs/agents_lats/step.py
  llama-index-packs/llama-index-packs-agents-lats/llama_index/packs/agents_lats/types.py
  llama-index-packs/llama-index-packs-agents-lats/pyproject.toml
  llama-index-packs/llama-index-packs-agents-lats/tests/BUILD
  llama-index-packs/llama-index-packs-agents-lats/tests/__init__.py
  llama-index-packs/llama-index-packs-agents-lats/tests/test_packs_lats.py
Labels: size:XL

#12862 Update pheonix pyproject.toml to support py3.12
  llama-index-integrations/callbacks/llama-index-callbacks-arize-phoenix/pyproject.toml
Labels: lgtm, size:XS

#12903 v0.10.30
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/octoai.md
  docs/docs/api_reference/packs/agents_lats.md
  docs/docs/api_reference/retrievers/bedrock.md
  docs/docs/api_reference/storage/vector_store/vearch.md
  docs/mkdocs.yml
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-cli/pyproject.toml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#11375 OctoAI Integration
  docs/docs/examples/llm/octoai.ipynb
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-octoai/.gitignore
  llama-index-integrations/llms/llama-index-llms-octoai/BUILD
  llama-index-integrations/llms/llama-index-llms-octoai/Makefile
  llama-index-integrations/llms/llama-index-llms-octoai/README.md
  llama-index-integrations/llms/llama-index-llms-octoai/llama_index/llms/octoai/BUILD
  llama-index-integrations/llms/llama-index-llms-octoai/llama_index/llms/octoai/__init__.py
  llama-index-integrations/llms/llama-index-llms-octoai/llama_index/llms/octoai/base.py
  llama-index-integrations/llms/llama-index-llms-octoai/llama_index/llms/octoai/utils.py
  llama-index-integrations/llms/llama-index-llms-octoai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-octoai/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-octoai/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-octoai/tests/test_llms_octoai.py
Labels: lgtm, size:XL

#12910 Fix Bedrock KB retriever
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/llama_index/retrievers/bedrock/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-bedrock/tests/test_retrievers_bedrock.py
Labels: size:S

#12942 Add Llama3 cookbook
  docs/docs/examples/cookbooks/llama3_cookbook.ipynb
Labels: lgtm, size:L

#12916 fix: Check for old sparse vector qdrant.base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
Labels: lgtm, size:XS

#12923 Neo4j metadata filtering support
  docs/docs/examples/vector_stores/neo4j_metadata_filter.ipynb
  docs/docs/module_guides/storing/vector_stores.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-neo4jvector/llama_index/vector_stores/neo4jvector/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-neo4jvector/pyproject.toml
Labels: lgtm, size:XL

#12952 llama3 cookbook nits
  docs/docs/examples/cookbooks/llama3_cookbook.ipynb
Labels: size:M

#12961 fix dependabot alerts
  docs/poetry.lock
  llama-index-core/poetry.lock
  llama-index-integrations/agent/llama-index-agent-openai/poetry.lock
  llama-index-integrations/llms/llama-index-llms-llamafile/poetry.lock
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-elasticsearch/poetry.lock
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-elasticsearch/poetry.lock
  llama-index-integrations/tools/llama-index-tools-passio-nutrition-ai/poetry.lock
  llama-index-networks/examples/demo/contributor-1/poetry.lock
  llama-index-networks/examples/demo/contributor-2/poetry.lock
  llama-index-networks/examples/demo/contributor-3/poetry.lock
  llama-index-networks/examples/privacy_safe_retrieval/contributor-1/poetry.lock
  llama-index-networks/examples/privacy_safe_retrieval/contributor-2/poetry.lock
  llama-index-networks/poetry.lock
  llama-index-networks/pyproject.toml
Labels: size:XS

#12953 fix async streaming response from query engine
  llama-index-core/llama_index/core/base/response/schema.py
  llama-index-core/llama_index/core/response/utils.py
  llama-index-core/llama_index/core/response_synthesizers/base.py
  llama-index-core/llama_index/core/response_synthesizers/refine.py
  llama-index-core/llama_index/core/response_synthesizers/tree_summarize.py
Labels: size:S

#12951 enforce uuid in element node parsers
  llama-index-core/llama_index/core/node_parser/relational/base_element.py
  llama-index-core/llama_index/core/node_parser/relational/markdown_element.py
  llama-index-core/llama_index/core/node_parser/relational/unstructured_element.py
Labels: size:S

#12941 bug(codeHierarchy): fixed bug when function is defined twice
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/code_hierarchy.py
  llama-index-packs/llama-index-packs-code-hierarchy/pyproject.toml
  llama-index-packs/llama-index-packs-code-hierarchy/tests/test_code_hierarchy_with_skeleton.py
Labels: lgtm, size:M

#12922 [docs] Add CouchbaseVectorStore to the Vector Store documentation pages
  docs/docs/community/integrations/vector_stores.md
  docs/docs/module_guides/storing/vector_stores.md
Labels: lgtm, size:S

#12947 Don't retry on all OpenAI APIStatusError exceptions - just InternalServerError
  llama-index-integrations/embeddings/llama-index-embeddings-openai/llama_index/embeddings/openai/utils.py
  llama-index-integrations/embeddings/llama-index-embeddings-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:XS
