Repository run-llama/llama_index, pull requests merged in 2025-04, with the labels that each got.

#18331 Add more unit tests for milvus vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/tests/test_vector_stores_milvus.py
Labels: lgtm, size:L

#18330 Support multi-modal agents
  docs/docs/module_guides/deploying/agents/index.md
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
Labels: size:M

#18309 prompt docs update
  docs/docs/examples/customization/prompts/chat_prompts.ipynb
  docs/docs/examples/customization/prompts/completion_prompts.ipynb
  docs/docs/examples/prompts/advanced_prompts.ipynb
  docs/docs/examples/prompts/emotion_prompt.ipynb
  docs/docs/examples/prompts/prompt_mixin.ipynb
  docs/docs/examples/prompts/prompt_optimization.ipynb
  docs/docs/examples/prompts/prompts_rag.ipynb
  docs/docs/examples/prompts/rich_prompt_template_features.ipynb
  docs/docs/module_guides/models/llms/usage_custom.md
  docs/docs/module_guides/models/prompts/index.md
  docs/docs/module_guides/models/prompts/usage_pattern.md
  docs/docs/optimizing/basic_strategies/basic_strategies.md
  docs/docs/use_cases/prompting.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/prompts/rich.py
Labels: size:XXL

#18329 add a code act agent
  docs/docs/examples/agent/code_act_agent.ipynb
  docs/docs/examples/agent/from_scratch_code_act_agent.ipynb
  docs/docs/module_guides/deploying/agents/index.md
  docs/docs/module_guides/deploying/agents/modules.md
  docs/docs/module_guides/workflow/index.md
  docs/docs/understanding/agent/multi_agent.md
  llama-index-core/llama_index/core/agent/workflow/__init__.py
  llama-index-core/llama_index/core/agent/workflow/codeact_agent.py
  llama-index-core/llama_index/core/tools/function_tool.py
  llama-index-core/tests/agent/workflow/test_code_act_agent.py
Labels: size:XXL

#18339 fix lancedb tests
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/tests/conftest.py
Labels: size:S

#18200 Update IpexLLM base.py
  llama-index-integrations/llms/llama-index-llms-ipex-llm/llama_index/llms/ipex_llm/base.py
  llama-index-integrations/llms/llama-index-llms-ipex-llm/pyproject.toml
Labels: lgtm, size:XS

#18340 v0.12.28
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/agent/index.md
  docs/docs/api_reference/llms/asi.md
  docs/docs/api_reference/readers/myscale.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/agent/workflow/react_agent.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#18348 update NovitaAI class documentation
  llama-index-integrations/llms/llama-index-llms-novita/llama_index/llms/novita/base.py
Labels: lgtm, size:M

#18343 Improve ASI streaming implementation and update documentation
  llama-index-integrations/llms/llama-index-llms-asi/README.md
  llama-index-integrations/llms/llama-index-llms-asi/llama_index/llms/asi/base.py
  llama-index-integrations/llms/llama-index-llms-asi/pyproject.toml
Labels: lgtm, size:L

#18350 cache watsonx context window
  llama-index-integrations/llms/llama-index-llms-ibm/llama_index/llms/ibm/base.py
  llama-index-integrations/llms/llama-index-llms-ibm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ibm/tests/test_ibm.py
Labels: size:S

#18352 fix openai json decode error
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:XS

#18355 remove org id kwarg
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/api_utils.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
Labels: lgtm, size:XS

#18357 Fix Sharepoint folder path encoding issue
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/llama_index/readers/microsoft_sharepoint/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-sharepoint/pyproject.toml
Labels: lgtm, size:S

#18362 fix: use defusexml instead of xml.etree
  llama-index-integrations/readers/llama-index-readers-papers/llama_index/readers/papers/pubmed/base.py
  llama-index-integrations/readers/llama-index-readers-papers/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-stripe-docs/llama_index/readers/stripe_docs/base.py
  llama-index-integrations/readers/llama-index-readers-stripe-docs/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/sitemap/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:M

#18358 Update Milvus tutorials
  docs/docs/community/integrations/vector_stores.md
  docs/docs/examples/vector_stores/MilvusAsyncAPIDemo.ipynb
  docs/docs/examples/vector_stores/MilvusFullTextSearchDemo.ipynb
  docs/docs/examples/vector_stores/MilvusHybridIndexDemo.ipynb
  docs/docs/module_guides/storing/vector_stores.md
Labels: lgtm, size:XL

#18344 fix(llms-vertex): Add `ImageBlock` and `TextBlock` support for Gemini models
  docs/docs/examples/llm/vertex.ipynb
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/gemini_utils.py
  llama-index-integrations/llms/llama-index-llms-vertex/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-vertex/tests/test_gemini_utils.py
Labels: lgtm, size:L

#18347 Fix draw_all_possible_flows for custom StopEvents
  llama-index-utils/llama-index-utils-workflow/llama_index/utils/workflow/draw.py
  llama-index-utils/llama-index-utils-workflow/pyproject.toml
Labels: lgtm, size:M

#18359 Fix the costly pop(0) in SentenceSplitter when parsing numerous texts
  llama-index-core/llama_index/core/node_parser/text/sentence.py
Labels: lgtm, size:XS

#18354 chore: add title and keywords to semantic config
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
Labels: size:S

#18364 Add OpenAILikeEmbedding, update docs
  docs/docs/api_reference/embeddings/openai_like.md
  docs/docs/api_reference/readers/myscale.md
  docs/docs/getting_started/starter_example.md
  docs/mkdocs.yml
  docs/scripts/prepare_for_build.py
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/LICENSE
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/llama_index/embeddings/openai_like/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/llama_index/embeddings/openai_like/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/llama_index/embeddings/openai_like/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/tests/test_embeddings_openai_like.py
  llama-index-integrations/llms/llama-index-llms-openai-like/README.md
Labels: size:L

#18365 fill in index pages
  docs/docs/examples/agent/agent_workflow_basic.ipynb
  docs/docs/examples/index.md
  docs/docs/module_guides/index.md
  docs/docs/use_cases/index.md
Labels: size:L

#18373 feature: add multi-modal support for bedrock converse
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/tests/test_bedrock_converse_utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/tests/test_llms_bedrock_converse.py
Labels: lgtm, size:L

#18356 Add uniprot reader
  llama-index-integrations/readers/llama-index-readers-uniprot/BUILD
  llama-index-integrations/readers/llama-index-readers-uniprot/README.md
  llama-index-integrations/readers/llama-index-readers-uniprot/llama_index/readers/uniprot/BUILD
  llama-index-integrations/readers/llama-index-readers-uniprot/llama_index/readers/uniprot/__init__.py
  llama-index-integrations/readers/llama-index-readers-uniprot/llama_index/readers/uniprot/base.py
  llama-index-integrations/readers/llama-index-readers-uniprot/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-uniprot/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-uniprot/tests/test_uniprot_reader.py
Labels: lgtm, size:XL

#18382 Update to Kuzu 0.9.0
  llama-index-integrations/graph_stores/llama-index-graph-stores-kuzu/llama_index/graph_stores/kuzu/utils.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-kuzu/pyproject.toml
Labels: size:XS

#18377 Bug Fix: Fixed the broken guide link in OpenLLMetry section of module…
  docs/docs/module_guides/observability/index.md
Labels: lgtm, size:XS

#18389 Fix docs build for Milvus Async API notebook
  docs/mkdocs.yml
Labels: lgtm, size:XS

#18226 waiting for events refactor
  docs/docs/examples/agent/agent_workflow_basic.ipynb
  docs/docs/understanding/agent/human_in_the_loop.md
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/tests/workflow/test_context.py
Labels: size:L

#18398 update huggingface deps
  llama-index-integrations/llms/llama-index-llms-gaudi/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/__init__.py
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/utils.py
  llama-index-integrations/llms/llama-index-llms-huggingface/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-huggingface/tests/test_huggingface.py
  llama-index-integrations/llms/llama-index-llms-huggingface/tests/test_llms_huggingface.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/llama_index/llms/text_generation_inference/base.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/llama_index/llms/text_generation_inference/utils.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/pyproject.toml
Labels: size:XL

#18391 Remove Managed Index ZillizCloudPipelineIndex
  docs/docs/api_reference/indices/zilliz.md
  docs/docs/community/integrations/managed_indices.md
  docs/docs/examples/managed/zcpDemo.ipynb
  docs/mkdocs.yml
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-core/llama_index/core/data_structs/struct_type.py
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/.gitignore
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/BUILD
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/LICENSE
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/Makefile
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/README.md
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/llama_index/indices/managed/zilliz/BUILD
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/llama_index/indices/managed/zilliz/__init__.py
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/llama_index/indices/managed/zilliz/base.py
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/llama_index/indices/managed/zilliz/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/tests/BUILD
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/tests/__init__.py
  llama-index-integrations/indices/llama-index-indices-managed-zilliz/tests/test_indices_managed_zilliz.py
Labels: lgtm, size:XXL

#18393 Fix/milvus filters
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/tests/test_vector_stores_milvus.py
Labels: lgtm, size:S

#18402 enable openai responses override
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/responses.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:S

#18395 fix: cleanup pyproject.toml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  pants.toml
Labels: lgtm, size:M

#18401 WatsonxLLM/WatsonxEmbeddings: persistent_connection configurable
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/llama_index/embeddings/ibm/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ibm/llama_index/llms/ibm/base.py
  llama-index-integrations/llms/llama-index-llms-ibm/pyproject.toml
Labels: lgtm, size:S

#18351 fix: isolate event buffers to avoid interferences between steps
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/llama_index/core/workflow/errors.py
  llama-index-core/poetry.lock
  llama-index-core/tests/workflow/test_context.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: size:L

#18404 add option to toggle progress bars in HuggingFaceEmbedding
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/llama_index/embeddings/huggingface/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/pyproject.toml
Labels: size:S

#18405 fix overwrite vs append logic in LanceDB
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/llama_index/vector_stores/lancedb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/pyproject.toml
Labels: size:S

#18399 better enforce agent handoffs
  Makefile
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
Labels: size:S

#18407 fix pass by reference errors with tools in OpenAIResponses
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:XS

#18410 Smabbler doc update
  llama-index-integrations/retrievers/llama-index-retrievers-galaxia/README.md
  llama-index-integrations/retrievers/llama-index-retrievers-galaxia/llama_index/retrievers/galaxia/base.py
Labels: lgtm, size:XS

#18415 Connect new phoenix tracing option
  llama-index-integrations/callbacks/llama-index-callbacks-arize-phoenix/llama_index/callbacks/arize_phoenix/base.py
  llama-index-integrations/callbacks/llama-index-callbacks-arize-phoenix/pyproject.toml
Labels: lgtm, size:XS

#18423 fix nebula properties get
  llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/llama_index/graph_stores/nebula/nebula_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/pyproject.toml
Labels: lgtm, size:XS

#18430 v0.12.30
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/llama_index/postprocessor/bedrock_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#18431 Add ASI notebook to LLM integrations documentation
  docs/docs/examples/llm/asi1.ipynb
  docs/docs/module_guides/models/llms/modules.md
Labels: lgtm, size:XXL

#18437 Fix LlamaAPI integration by wrapping OpenAI
  llama-index-integrations/llms/llama-index-llms-llama-api/llama_index/llms/llama_api/base.py
  llama-index-integrations/llms/llama-index-llms-llama-api/pyproject.toml
Labels: size:L

#18445 Update modules.md to consolidate Google presence
  docs/docs/module_guides/models/llms/modules.md
Labels: lgtm, size:XS

#18438 add async to memory and postprocessor base classes
  Makefile
  llama-index-core/llama_index/core/agent/workflow/codeact_agent.py
  llama-index-core/llama_index/core/agent/workflow/function_agent.py
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-core/llama_index/core/memory/types.py
  llama-index-core/llama_index/core/postprocessor/types.py
  llama-index-core/llama_index/core/storage/chat_store/base.py
  llama-index-core/tests/agent/workflow/test_code_act_agent.py
Labels: size:L

#18455 support new 4.1 models
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:XS

#18456 Added model names for OpenAI 4.1 support
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:XS

#18454 feat(elasticsearch): implement missing BasePydanticVectorStore methods
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/tests/test_vector_stores_elasticsearch.py
Labels: lgtm, size:L

#18442 Update Perplexity Implementation
  docs/docs/examples/llm/perplexity.ipynb
  llama-index-integrations/llms/llama-index-llms-perplexity/README.md
  llama-index-integrations/llms/llama-index-llms-perplexity/llama_index/llms/perplexity/base.py
  llama-index-integrations/llms/llama-index-llms-perplexity/pyproject.toml
Labels: lgtm, size:L

#18432 Feat add sqlite chat store
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-sqlite/.gitignore
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-sqlite/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-sqlite/LICENSE
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-sqlite/Makefile
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-sqlite/README.md
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-sqlite/llama_index/storage/chat_store/sqlite/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-sqlite/llama_index/storage/chat_store/sqlite/__init__.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-sqlite/llama_index/storage/chat_store/sqlite/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-sqlite/pyproject.toml
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-sqlite/tests/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-sqlite/tests/__init__.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-sqlite/tests/conftest.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-sqlite/tests/test_chat_store_sqlite_chat_store.py
Labels: lgtm, size:XL

#18447 Fix/memory multimodal content serialization
  llama-index-core/llama_index/core/memory/vector_memory.py
  llama-index-core/llama_index/core/vector_stores/utils.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/llama_index/storage/chat_store/postgres/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/pyproject.toml
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/tests/test_chat_store_postgres_chat_store.py
Labels: size:M

#18461 fix nebula index ddl
  llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/llama_index/graph_stores/nebula/nebula_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/pyproject.toml
Labels: lgtm, size:S

#18466 Fix/llama index callbacks arize phoenix python version
  llama-index-integrations/callbacks/llama-index-callbacks-arize-phoenix/pyproject.toml
Labels: lgtm, size:XS

#18473 o3 and o4-mini support
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:XS

#18472 Added llm_name argument for Vectara
  llama-index-integrations/indices/llama-index-indices-managed-vectara/Changelog.md
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/pyproject.toml
Labels: lgtm, size:M

#18471 Don't create a sync openai client when using async methods with Azure
  llama-index-integrations/llms/llama-index-llms-azure-openai/tests/test_azure_openai.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:L

#18474 v0.12.31
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/storage/chat_store/sqlite.md
  docs/docs/api_reference/storage/vector_store/ApertureDB.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-experimental/pyproject.toml
  llama-index-finetuning/llama_index/finetuning/mistralai/base.py
  llama-index-finetuning/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#18460 MilvusVectorStore: BM25 as default sparse embedding function
  docs/docs/examples/vector_stores/MilvusAsyncAPIDemo.ipynb
  docs/docs/examples/vector_stores/MilvusFullTextSearchDemo.ipynb
  docs/docs/examples/vector_stores/MilvusHybridIndexDemo.ipynb
  docs/docs/examples/vector_stores/MilvusIndexDemo.ipynb
  docs/docs/examples/vector_stores/MilvusOperatorFunctionDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/CHANGELOG.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:XL

#18484 Close "session" in VectaraIndex on GC
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/base.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/pyproject.toml
Labels: lgtm, size:S

#18481 fix the openvino llm initialize issue
  llama-index-integrations/llms/llama-index-llms-openvino-genai/llama_index/llms/openvino_genai/base.py
  llama-index-integrations/llms/llama-index-llms-openvino-genai/pyproject.toml
Labels: lgtm, size:XS

#18495 allow content blocks in openai assistant messages
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:XS

#18494 fix react agent prompt updates
  llama-index-core/llama_index/core/agent/workflow/react_agent.py
  llama-index-core/tests/agent/workflow/test_react_agent.py
Labels: size:M

#18499 v0.12.32
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/understanding/agent/rag_agent.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#18502 Milvus Vector Store: Update metadata filtering demo
  docs/docs/examples/vector_stores/MilvusOperatorFunctionDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:L

#18482 Cortex Enhancements
  llama-index-integrations/llms/llama-index-llms-cortex/README.md
  llama-index-integrations/llms/llama-index-llms-cortex/llama_index/llms/cortex/base.py
  llama-index-integrations/llms/llama-index-llms-cortex/llama_index/llms/cortex/utils.py
  llama-index-integrations/llms/llama-index-llms-cortex/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-cortex/tests/test_integration_cortex.py
  llama-index-integrations/llms/llama-index-llms-cortex/tests/test_utils.py
Labels: lgtm, size:L

#18509 v0.12.33
  .github/workflows/publish_release.yml
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/llama_cloud/llama_parse.md
  llama-index-core/.gitignore
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/utils.py
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#18512 Prevent MCP Connections Hang
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/client.py
  llama-index-integrations/tools/llama-index-tools-mcp/pyproject.toml
Labels: lgtm, size:M

#18507 Allow PGVectorStore to allow passing in engines
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/test_postgres.py
Labels: size:L

#18527 [google genai] merge tool messages properly
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
Labels: size:L

#18515 Implement aget_nodes and adelete in PGVectorStore
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: lgtm, size:M

#18533 unlock pillow dep in google genai llm
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
Labels: size:XS

#18540 vbump genai
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
Labels: size:XS

#18538 Code Hierarchy Agent Pack Issue with Empty and different enconding based files
  llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/code_hierarchy.py
  llama-index-packs/llama-index-packs-code-hierarchy/pyproject.toml
Labels: lgtm, size:XS

#18537 Enhance DatabaseReader with new features and improved documentation
  llama-index-integrations/readers/llama-index-readers-database/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-database/README.md
  llama-index-integrations/readers/llama-index-readers-database/llama_index/readers/database/base.py
  llama-index-integrations/readers/llama-index-readers-database/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-database/tests/test_readers_database.py
Labels: lgtm, size:L

#18528 aextract_table_summaries cause unwanted output when showprogress is False
  llama-index-core/llama_index/core/node_parser/relational/base_element.py
Labels: lgtm, size:S

#18556 CI: make dependabot update all the packages in one PR
  .github/dependabot.yml
Labels: lgtm, size:S

#18558 docs: migrate contributing guidelines to uv
  CONTRIBUTING.md
Labels: lgtm, size:L

#18557 Doc typo fix
  docs/docs/examples/agent/react_agent.ipynb
  docs/docs/examples/agent/react_agent_with_query_engine.ipynb
  docs/docs/getting_started/async_python.md
Labels: lgtm, size:S

#18567 remove tree-sitter from top-level deps
  pyproject.toml
  uv.lock
Labels: size:XS

#18545 new sql db chat store
  llama-index-core/.gitignore
  llama-index-core/llama_index/core/storage/chat_store/base_db.py
  llama-index-core/llama_index/core/storage/chat_store/sql.py
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  llama-index-core/tests/storage/chat_store/test_sql.py
Labels: size:XL

#18575 feat(llama-index-llms-google-genai): 2.5-flash-preview tests
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/base.py
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-google-genai/tests/test_llms_google_genai.py
  llama-index-integrations/llms/llama-index-llms-google-genai/tests/test_llms_google_genai_vertex.py
  llama-index-integrations/llms/llama-index-llms-google-genai/uv.lock
Labels: lgtm, size:XL

#18571 ci: implement proper dependency graph walker
  .github/workflows/scripts_tests.yml
  .github/workflows/unit_test.yml
  pyproject.toml
  scripts/run_ci_tests.py
  scripts/tests/README.md
  scripts/tests/data/llama-index-integrations/storage/subcat/pkg2/.gitkeep
  scripts/tests/data/llama-index-integrations/storage/subcat/pkg2/tests/.gitkeep
  scripts/tests/data/llama-index-integrations/vector_stores/pkg1/.gitkeep
  scripts/tests/data/llama-index-integrations/vector_stores/pkg1/tests/.gitkeep
  scripts/tests/data/llama-index-packs/not_a_pack/.gitkeep
  scripts/tests/data/llama-index-packs/pack1/tests/.gitkeep
  scripts/tests/data/llama-index-packs/pack2/tests/.gitkeep
  scripts/tests/data/llama-index-utils/not_a_util/.gitkeep
  scripts/tests/data/llama-index-utils/util/tests/.gitkeep
  scripts/tests/test_run_ci_tests.py
  uv.lock
Labels: lgtm, size:L

#18581 fix broken publish workflows
  .github/workflows/publish_release.yml
  .github/workflows/publish_sub_package.yml
Labels: size:M

#18584 ensure paths are strings before sorting
  scripts/run_ci_tests.py
Labels: size:XS

#18579 update default model version to v3.0 in CohereRerank
  llama-index-integrations/postprocessor/llama-index-postprocessor-cohere-rerank/llama_index/postprocessor/cohere_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-cohere-rerank/pyproject.toml
Labels: lgtm, size:XS
