Repository run-llama/llama_index, pull requests merged in 2025-10, with the labels that each got.

#19916 Bug Fix :- Not Able to Fetch Page whose latest is empty or null
  llama-index-integrations/readers/llama-index-readers-service-now/llama_index/readers/service_now/base.py
  llama-index-integrations/readers/llama-index-readers-service-now/pyproject.toml
Labels: lgtm, size:XS

#19974 feat: update scrapegraphai
  llama-index-integrations/tools/llama-index-tools-scrapegraph/examples/complete-scrapegraph-examples.py
  llama-index-integrations/tools/llama-index-tools-scrapegraph/examples/scrapegraph-agentic-scraper-llama-index.py
  llama-index-integrations/tools/llama-index-tools-scrapegraph/examples/scrapegraph-markdowinify-llama-index.py
  llama-index-integrations/tools/llama-index-tools-scrapegraph/examples/scrapegraph-scrape-llama-index.py
  llama-index-integrations/tools/llama-index-tools-scrapegraph/examples/scrapegraph-search-llama-index.py
  llama-index-integrations/tools/llama-index-tools-scrapegraph/examples/scrapegraph-smartscraper-lama-index.py
  llama-index-integrations/tools/llama-index-tools-scrapegraph/llama_index/tools/scrapegraph/base.py
  llama-index-integrations/tools/llama-index-tools-scrapegraph/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-scrapegraph/tests/test_integration.py
  llama-index-integrations/tools/llama-index-tools-scrapegraph/tests/test_tools_scrapegraph.py
Labels: lgtm, size:XXL

#19990 Update core/indices/base.py to remove depreciation warning
  llama-index-core/llama_index/core/indices/base.py
Labels: lgtm, size:S

#20003 Changelog format
  docs/src/content/docs/framework/CHANGELOG.md
  docs/src/content/docs/framework/CONTRIBUTING.md
Labels: lgtm, size:XS

#20007 remove release requirement for core to be on a branch
  llama-dev/llama_dev/release/check.py
  llama-dev/tests/release/test_check.py
Labels: size:M

#20016 grant release workflow attestation permissions
  .github/workflows/release.yml
Labels: size:XS

#20000 Remove debug print
  llama-index-core/llama_index/core/storage/kvstore/simple_kvstore.py
Labels: lgtm, size:XS

#20020 Added Sglang llm integration
  llama-index-integrations/llms/llama-index-llms-sglang/.gitignore
  llama-index-integrations/llms/llama-index-llms-sglang/Makefile
  llama-index-integrations/llms/llama-index-llms-sglang/README.md
  llama-index-integrations/llms/llama-index-llms-sglang/llama_index/llms/sglang/__init__.py
  llama-index-integrations/llms/llama-index-llms-sglang/llama_index/llms/sglang/base.py
  llama-index-integrations/llms/llama-index-llms-sglang/llama_index/llms/sglang/utils.py
  llama-index-integrations/llms/llama-index-llms-sglang/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-sglang/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-sglang/tests/test_llms_sglang.py
Labels: lgtm, size:XL

#19985 Clean up Azure PostgreSQL notebook
  docs/examples/vector_stores/azurepostgresql.ipynb
Labels: lgtm, size:M

#20030 merge instead of ovewrwrite when aggregating changelog items
  llama-dev/llama_dev/release/changelog.py
Labels: size:XS

#20034 Update LlamaParse documentation link
  docs/src/content/docs/framework/index.md
  docs/src/content/docs/framework/llama_cloud/llama_parse.md
Labels: lgtm, size:XS

#20031 safely initialize RefDocInfo in Docstore
  llama-index-core/llama_index/core/storage/docstore/keyval_docstore.py
Labels: size:XS

#20037 fix collecting final response with openai responses streaming
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/responses.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_responses.py
Labels: size:S

#20039 vbump the JSON reader
  llama-index-integrations/readers/llama-index-readers-json/pyproject.toml
Labels: size:XS

#20042 Baseten provider Kimi K2 0711, Llama 4 Maverick and Llama 4 Scout Model APIs deprecation
  llama-index-integrations/llms/llama-index-llms-baseten/llama_index/llms/baseten/utils.py
  llama-index-integrations/llms/llama-index-llms-baseten/pyproject.toml
Labels: lgtm, size:XS

#20005 fix(qdrant): Allow async-only initialization with hybrid search
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/tests/conftest.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/tests/test_vector_stores_qdrant.py
Labels: lgtm, size:L
