Repository run-llama/llama_index, pull requests merged in 2025-05, with the labels that each got.

#18570 Update README.md
  llama-index-integrations/llms/llama-index-llms-modelscope/README.md
Labels: lgtm, size:XS

#18574 Add provider support to HuggingFaceInferenceAPI
  llama-index-integrations/llms/llama-index-llms-huggingface-api/README.md
  llama-index-integrations/llms/llama-index-llms-huggingface-api/llama_index/llms/huggingface_api/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface-api/pyproject.toml
Labels: lgtm, size:S

#18568 docs: update AIMon evaluation example notebook
  docs/docs/examples/evaluation/AIMon.ipynb
Labels: lgtm, size:L

#18560 [BUGFIX] Add OpensearchVectorClient to conditionally check index existence for AOSS
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
Labels: lgtm, size:S

#18552 feat: add is_chat_model option
  llama-index-integrations/llms/llama-index-llms-vllm/llama_index/llms/vllm/base.py
  llama-index-integrations/llms/llama-index-llms-vllm/pyproject.toml
Labels: lgtm, size:S

#18551 Fix Cohere Embedding Multiprocessing with Custom Endpoint
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/llama_index/embeddings/cohere/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/tests/test_embeddings.py
Labels: lgtm, size:M

#18586 v0.12.34
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/CONTRIBUTING.md
  docs/docs/api_reference/embeddings/openvino_genai.md
  docs/mkdocs.yml
  llama-index-core/.gitignore
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-core/uv.lock
  pyproject.toml
  uv.lock
Labels: size:L

#18585 Support Llama-api as an LLM provider
  llama-index-integrations/llms/llama-index-llms-meta/.gitignore
  llama-index-integrations/llms/llama-index-llms-meta/BUILD
  llama-index-integrations/llms/llama-index-llms-meta/LICENSE
  llama-index-integrations/llms/llama-index-llms-meta/Makefile
  llama-index-integrations/llms/llama-index-llms-meta/README.md
  llama-index-integrations/llms/llama-index-llms-meta/llama_index/llms/meta/BUILD
  llama-index-integrations/llms/llama-index-llms-meta/llama_index/llms/meta/__init__.py
  llama-index-integrations/llms/llama-index-llms-meta/llama_index/llms/meta/base.py
  llama-index-integrations/llms/llama-index-llms-meta/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-meta/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-meta/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-meta/tests/test_llms_llama.py
  llama-index-integrations/llms/llama-index-llms-meta/uv.lock
Labels: lgtm, size:L

#18578 Support for Autoembeddings embeddings integration and MarkItDown reader integration
  llama-index-integrations/embeddings/llama-index-embeddings-autoembeddings/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-autoembeddings/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-autoembeddings/LICENSE
  llama-index-integrations/embeddings/llama-index-embeddings-autoembeddings/MAKEFILE
  llama-index-integrations/embeddings/llama-index-embeddings-autoembeddings/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-autoembeddings/llama_index/embeddings/autoembeddings/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-autoembeddings/llama_index/embeddings/autoembeddings/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-autoembeddings/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-autoembeddings/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-autoembeddings/tests/test_autoembeddings.py
  llama-index-integrations/embeddings/llama-index-embeddings-autoembeddings/uv.lock
  llama-index-integrations/readers/llama-index-readers-markitdown/.gitignore
  llama-index-integrations/readers/llama-index-readers-markitdown/BUILD
  llama-index-integrations/readers/llama-index-readers-markitdown/LICENSE
  llama-index-integrations/readers/llama-index-readers-markitdown/MAKEFILE
  llama-index-integrations/readers/llama-index-readers-markitdown/README.md
  llama-index-integrations/readers/llama-index-readers-markitdown/llama_index/readers/markitdown/__init__.py
  llama-index-integrations/readers/llama-index-readers-markitdown/llama_index/readers/markitdown/base.py
  llama-index-integrations/readers/llama-index-readers-markitdown/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-markitdown/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-markitdown/tests/test_markitdownreader.py
  llama-index-integrations/readers/llama-index-readers-markitdown/uv.lock
Labels: lgtm, size:XL

#18591 Fix link to "any other LLM"
  docs/docs/understanding/agent/index.md
Labels: lgtm, size:XS

#18593 Linting + Docs fixes
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/autoembeddings.md
  docs/docs/api_reference/llms/meta.md
  docs/docs/api_reference/readers/markitdown.md
  docs/docs/api_reference/storage/vector_store/gel.md
  docs/mkdocs.yml
  docs/scripts/prepare_for_build.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-gel/llama_index/storage/chat_store/gel/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-gel/tests/test_chat_store_gel_chat_store.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-gel/llama_index/storage/docstore/gel/base.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-gel/tests/test_gel.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-gel/llama_index/storage/index_store/gel/base.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-gel/tests/test_gel.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-gel/llama_index/storage/kvstore/gel/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-gel/tests/test_gel.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-gel/llama_index/vector_stores/gel/base.py
Labels: size:L

#18588 Cortex enhancements 2
  llama-index-integrations/llms/llama-index-llms-cortex/README.md
  llama-index-integrations/llms/llama-index-llms-cortex/llama_index/llms/cortex/base.py
  llama-index-integrations/llms/llama-index-llms-cortex/llama_index/llms/cortex/utils.py
  llama-index-integrations/llms/llama-index-llms-cortex/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-cortex/tests/test_integration_cortex.py
  llama-index-integrations/llms/llama-index-llms-cortex/tests/test_utils.py
Labels: lgtm, size:L

#18594 memory revamp
  llama-index-core/llama_index/core/memory/memory.py
  llama-index-core/llama_index/core/storage/chat_store/base_db.py
  llama-index-core/llama_index/core/storage/chat_store/sql.py
  llama-index-core/pyproject.toml
  llama-index-core/tests/memory/test_memory_base.py
  llama-index-core/tests/memory/test_memory_blocks_base.py
  llama-index-core/tests/storage/chat_store/test_sql.py
  llama-index-core/uv.lock
Labels: size:XXL

#18605 fix openai tests hanging
  .gitignore
  llama-index-core/.gitignore
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/step.py
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
Labels: size:XS

#18611 Fix last_msg indexing.
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-google-genai/tests/test_llms_google_genai.py
Labels: lgtm, size:M

#18615 feat: introduce llama-dev
  llama-dev/.gitignore
  llama-dev/LICENSE
  llama-dev/README.md
  llama-dev/llama_dev/__init__.py
  llama-dev/llama_dev/__main__.py
  llama-dev/llama_dev/cli.py
  llama-dev/llama_dev/pkg/__init__.py
  llama-dev/llama_dev/pkg/cmd_exec.py
  llama-dev/llama_dev/pkg/info.py
  llama-dev/llama_dev/test/__init__.py
  llama-dev/llama_dev/utils.py
  llama-dev/pyproject.toml
  llama-dev/tests/conftest.py
  llama-dev/tests/data/llama-index-integrations/not_a_category
  llama-dev/tests/data/llama-index-integrations/storage/subcat/pkg2/pyproject.toml
  llama-dev/tests/data/llama-index-integrations/storage/subcat/pkg2/tests/.gitkeep
  llama-dev/tests/data/llama-index-integrations/vector_stores/pkg1/pyproject.toml
  llama-dev/tests/data/llama-index-integrations/vector_stores/pkg1/tests/.gitkeep
  llama-dev/tests/data/llama-index-packs/not_a_pack/.gitkeep
  llama-dev/tests/data/llama-index-packs/pack1/pyproject.toml
  llama-dev/tests/data/llama-index-packs/pack1/tests/.gitkeep
  llama-dev/tests/data/llama-index-packs/pack2/pyproject.toml
  llama-dev/tests/data/llama-index-utils/not_a_util/.gitkeep
  llama-dev/tests/data/llama-index-utils/util/pyproject.toml
  llama-dev/tests/data/llama-index-utils/util/tests/.gitkeep
  llama-dev/tests/test_llama_dev.py
  llama-dev/tests/test_utils.py
  llama-dev/uv.lock
Labels: lgtm, size:XXL

#18613 Fix MarkItDown Reader bugs
  llama-index-integrations/readers/llama-index-readers-markitdown/llama_index/readers/markitdown/base.py
  llama-index-integrations/readers/llama-index-readers-markitdown/pyproject.toml
Labels: lgtm, size:M

#18610 Bugfix in using cutoff argument with chain reranker in Vectara
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/pyproject.toml
Labels: lgtm, size:XS

#18603 Add a notebook for more setup instructions, and support filter based on metadata.
  docs/docs/examples/vector_stores/ApertureDBVectorStoreDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-ApertureDB/llama_index/vector_stores/ApertureDB/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-ApertureDB/pyproject.toml
Labels: lgtm, size:L

#18608 [BUG#18598] update ChatResponse to include additional_kwargs and bump…
  llama-index-integrations/llms/llama-index-llms-dashscope/llama_index/llms/dashscope/utils.py
  llama-index-integrations/llms/llama-index-llms-dashscope/pyproject.toml
Labels: lgtm, size:XS

#18616 Fix modifying object references in google-genai llm
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
Labels: size:XS

#18617 [Docs] Update llms llama-api README
  llama-index-integrations/llms/llama-index-llms-meta/README.md
Labels: lgtm, size:M

#18618 chore: use `llama-dev` to run the tests
  .github/workflows/llama_dev_tests.yml
  .github/workflows/unit_test.yml
  llama-dev/llama_dev/test/__init__.py
  llama-dev/pyproject.toml
  llama-dev/uv.lock
  scripts/run_ci_tests.py
  scripts/tests/README.md
  scripts/tests/data/llama-index-integrations/storage/subcat/pkg2/.gitkeep
  scripts/tests/data/llama-index-integrations/storage/subcat/pkg2/tests/.gitkeep
  scripts/tests/data/llama-index-integrations/vector_stores/pkg1/.gitkeep
  scripts/tests/data/llama-index-integrations/vector_stores/pkg1/tests/.gitkeep
  scripts/tests/data/llama-index-packs/not_a_pack/.gitkeep
  scripts/tests/data/llama-index-packs/pack1/tests/.gitkeep
  scripts/tests/data/llama-index-packs/pack2/tests/.gitkeep
  scripts/tests/data/llama-index-utils/not_a_util/.gitkeep
  scripts/tests/data/llama-index-utils/util/tests/.gitkeep
  scripts/tests/test_run_ci_tests.py
Labels: lgtm, size:XL

#18604 Adding FunctionAgent import
  docs/docs/understanding/agent/index.md
Labels: lgtm, size:XS

#18619 Docs fix 2
  CONTRIBUTING.md
  docs/docs/understanding/agent/index.md
Labels: lgtm, size:XS

#18622 fix: `--base-ref` cannot be empty
  llama-dev/.gitignore
  llama-dev/llama_dev/pkg/__init__.py
  llama-dev/llama_dev/test/__init__.py
  llama-dev/pyproject.toml
  llama-dev/tests/__init__.py
  llama-dev/tests/pkg/test_cmd_exec.py
  llama-dev/tests/pkg/test_info.py
  llama-dev/tests/test/test_test.py
  llama-dev/tests/test_cli.py
Labels: lgtm, size:XL

#18623 ci: skip workflow on main
  .github/workflows/unit_test.yml
Labels: lgtm, size:XS

#18626 check for no tests ran
  llama-dev/llama_dev/test/__init__.py
Labels: size:XS

#18621 make memory serialization great again
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-core/llama_index/core/workflow/context.py
Labels: size:M

#18606 Adding VoyageAI MultiModal example
  docs/docs/examples/index.md
  docs/docs/examples/multi_modal/llamaindex_mongodb_voyageai_multimodal.ipynb
Labels: lgtm, size:XS

#18627 nit notebook logs
  docs/docs/examples/multi_modal/llamaindex_mongodb_voyageai_multimodal.ipynb
Labels: size:XS

#18607 add prebuilt memory blocks
  llama-index-core/llama_index/core/async_utils.py
  llama-index-core/llama_index/core/memory/__init__.py
  llama-index-core/llama_index/core/memory/memory.py
  llama-index-core/llama_index/core/memory/memory_blocks/__init__.py
  llama-index-core/llama_index/core/memory/memory_blocks/fact.py
  llama-index-core/llama_index/core/memory/memory_blocks/static.py
  llama-index-core/llama_index/core/memory/memory_blocks/vector.py
  llama-index-core/llama_index/core/storage/chat_store/sql.py
  llama-index-core/tests/memory/blocks/test_fact.py
  llama-index-core/tests/memory/blocks/test_static.py
  llama-index-core/tests/memory/blocks/test_vector.py
  llama-index-core/tests/storage/chat_store/test_sql.py
Labels: size:XXL

#18641 llama-dev: improve exec command
  llama-dev/llama_dev/cli.py
  llama-dev/llama_dev/pkg/cmd_exec.py
  llama-dev/tests/pkg/test_cmd_exec.py
Labels: lgtm, size:M

#18642 llama-dev: do not print full path on tests reports
  llama-dev/llama_dev/test/__init__.py
Labels: lgtm, size:S

#18628 make memory serialization great again
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-core/llama_index/core/workflow/context.py
Labels: size:M

#18630 Fix: Add follow_redirects=True to GitHubIssuesClient to handle GitHub…
  llama-index-integrations/readers/llama-index-readers-github/llama_index/readers/github/issues/github_client.py
  llama-index-integrations/readers/llama-index-readers-github/pyproject.toml
Labels: lgtm, size:XS

#18631 Fix: Updated the doc string for Pandas query engine to match the constructor
  llama-index-experimental/llama_index/experimental/query_engine/pandas/pandas_query_engine.py
Labels: lgtm, size:S

#18639 Fix/docling node parser metadata
  llama-index-integrations/node_parser/llama-index-node-parser-docling/llama_index/node_parser/docling/base.py
  llama-index-integrations/node_parser/llama-index-node-parser-docling/pyproject.toml
Labels: lgtm, size:S

#18634 Fix/react agent max iterations skipping (#18597)
  llama-index-core/llama_index/core/agent/react/step.py
  llama-index-core/tests/agent/react/test_react_agent.py
Labels: lgtm, size:M

#18653 Tool arguments async
  llama-index-integrations/llms/llama-index-llms-litellm/llama_index/llms/litellm/base.py
  llama-index-integrations/llms/llama-index-llms-litellm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-litellm/tests/test_llms_litellm.py
Labels: lgtm, size:M

#18595 add indexed metadata fields
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/test_postgres.py
Labels: lgtm, size:L

#18655 update test instructions for pgvector
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/README.md
Labels: lgtm, size:XS

#18657 anthropic citations and tool calls
  docs/docs/examples/llm/anthropic.ipynb
  llama-index-integrations/llms/llama-index-llms-anthropic/README.md
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: size:L

#18658 add support for partial tool kwargs
  llama-index-core/llama_index/core/tools/function_tool.py
  llama-index-core/tests/tools/test_base.py
Labels: size:M

#18662 Huggingface API fixes
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-api/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-huggingface-api/llama_index/llms/huggingface_api/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface-api/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-huggingface-api/tests/test_huggingface_api.py
Labels: size:M

#18638 Add Faiss Map Vector store and fix missing index_struct delete (#18583)
  docs/docs/community/integrations/vector_stores.md
  llama-index-core/llama_index/core/indices/vector_store/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-faiss/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-faiss/llama_index/vector_stores/faiss/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-faiss/llama_index/vector_stores/faiss/map_store.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-faiss/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-faiss/tests/test_vector_stores_faiss.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-faiss/uv.lock
Labels: lgtm, size:XL

#18644 New memory docs
  docs/docs/examples/agent/memory/chat_memory_buffer.ipynb
  docs/docs/examples/agent/memory/composable_memory.ipynb
  docs/docs/examples/agent/memory/summary_memory_buffer.ipynb
  docs/docs/examples/agent/memory/vector_memory.ipynb
  docs/docs/examples/memory/custom_memory.ipynb
  docs/docs/examples/memory/memory.ipynb
  docs/docs/module_guides/deploying/agents/memory.md
  llama-index-core/llama_index/core/memory/memory.py
  llama-index-core/llama_index/core/memory/memory_blocks/vector.py
  llama-index-core/tests/memory/blocks/test_vector.py
  llama-index-core/tests/memory/test_memory_base.py
  llama-index-core/tests/memory/test_memory_blocks_base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/uv.lock
Labels: size:XXL

#18646 Fixes improper invocation of Firecrawl library
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/firecrawl_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: size:S

#18664 [FIX] update llama-index-llms-meta version to v0.1.1
  llama-index-integrations/llms/llama-index-llms-meta/pyproject.toml
Labels: lgtm, size:XS

#18660 Fix event colors of draw_all_possible_flows
  llama-index-utils/llama-index-utils-workflow/llama_index/utils/workflow/draw.py
  llama-index-utils/llama-index-utils-workflow/pyproject.toml
Labels: lgtm, size:S

#18620 feat(node_parser): add SlideNodeParser integration
  docs/docs/api_reference/node_parser/slide.md
  llama-index-integrations/node_parser/llama-index-node-parser-slide/.gitignore
  llama-index-integrations/node_parser/llama-index-node-parser-slide/LICENSE
  llama-index-integrations/node_parser/llama-index-node-parser-slide/Makefile
  llama-index-integrations/node_parser/llama-index-node-parser-slide/README.md
  llama-index-integrations/node_parser/llama-index-node-parser-slide/llama_index/node_parser/slide/__init__.py
  llama-index-integrations/node_parser/llama-index-node-parser-slide/llama_index/node_parser/slide/base.py
  llama-index-integrations/node_parser/llama-index-node-parser-slide/pyproject.toml
  llama-index-integrations/node_parser/llama-index-node-parser-slide/tests/__init__.py
  llama-index-integrations/node_parser/llama-index-node-parser-slide/tests/test_node_parser_slide.py
Labels: lgtm, size:XL

#18665 v0.12.35
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/CONTRIBUTING.md
  docs/docs/examples/llm/databricks.ipynb
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-core/uv.lock
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  pyproject.toml
Labels: size:L

#18674 Update release notes generation
  .github/workflows/publish_release.yml
Labels: size:XS

#18483 [LLM integration]: Update package name and models
  docs/docs/module_guides/models/llms/modules.md
  llama-index-integrations/llms/llama-index-llms-cleanlab/llama_index/llms/cleanlab/base.py
  llama-index-integrations/llms/llama-index-llms-cleanlab/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-cleanlab/tests/test_llms_cleanlab.py
Labels: lgtm, size:L

#18647 Update human_in_the_loop.md
  docs/docs/understanding/agent/human_in_the_loop.md
Labels: lgtm, size:XS

#18659 log deprecation warning for TextGenerationInference
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/README.md
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/llama_index/llms/text_generation_inference/__init__.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/llama_index/llms/text_generation_inference/base.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/pyproject.toml
Labels: lgtm, size:M

#18649 feat: legacy_office, Apache Tika based .doc reader
  docs/docs/api_reference/readers/legacy_office.md
  docs/docs/examples/data_connectors/lagecy_office_reader.ipynb
  docs/mkdocs.yml
  llama-index-integrations/readers/llama-index-readers-legacy-office/.gitignore
  llama-index-integrations/readers/llama-index-readers-legacy-office/README.md
  llama-index-integrations/readers/llama-index-readers-legacy-office/llama_index/readers/legacy_office/__init__.py
  llama-index-integrations/readers/llama-index-readers-legacy-office/llama_index/readers/legacy_office/reader.py
  llama-index-integrations/readers/llama-index-readers-legacy-office/pyproject.toml
Labels: lgtm, size:XL

#18667 Add IS_EMPTY support for PGVectorStore
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/test_postgres.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/uv.lock
Labels: lgtm, size:M

#18672 [`docs`] Add docs explaining how to easily use ONNX/OpenVINO for local embeddings
  benchmarks/embeddings/bench_embeddings.py
  docs/docs/examples/embeddings/huggingface.ipynb
  docs/docs/module_guides/models/embeddings.md
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum/llama_index/embeddings/huggingface_optimum/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/pyproject.toml
Labels: lgtm, size:XL

#18656 Removes llama-index-llms-text-generation-inference
  .github/pull_request_template.md
  docs/docs/api_reference/llms/text_generation_inference.md
  docs/docs/examples/llm/huggingface.ipynb
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/.gitignore
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/LICENSE
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/Makefile
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/llama_index/llms/text_generation_inference/__init__.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/llama_index/llms/text_generation_inference/base.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/llama_index/llms/text_generation_inference/utils.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/tests/test_llms_text_generation_inference.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/tests/test_tgi_utils.py
  llama-index-integrations/llms/llama-index-llms-text-generation-inference/uv.lock
Labels: lgtm, size:XXL

#18678 add pruning
  docs/docs/api_reference/tools/query_plan.md
  docs/mkdocs.yml
Labels: size:XS

#18679 add edge case handling in StreamingAgentChatResponse
  llama-index-core/llama_index/core/chat_engine/types.py
Labels: size:S

#18680 use fs to check ingestion pipeline path
  llama-index-core/llama_index/core/ingestion/pipeline.py
Labels: size:XS

#18686 llama-dev: add bump command
  llama-dev/llama_dev/pkg/__init__.py
  llama-dev/llama_dev/pkg/bump.py
  llama-dev/tests/data/llama-index-utils/util/pyproject.toml
  llama-dev/tests/pkg/test_bump.py
  scripts/bump_packages.py
Labels: lgtm, size:L

#18689 [Community integration]: Minor re-organize of Cleanlab defaults
  llama-index-integrations/llms/llama-index-llms-cleanlab/llama_index/llms/cleanlab/base.py
  llama-index-integrations/llms/llama-index-llms-cleanlab/pyproject.toml
Labels: lgtm, size:S

#18684 docs: add a badge to the social network Twitter
  README.md
Labels: lgtm, size:XS

#18682 [Community notebook]: Cleanlab Evaluation Notebook
  docs/docs/examples/evaluation/Cleanlab.ipynb
  docs/docs/module_guides/evaluating/index.md
  docs/docs/module_guides/evaluating/modules.md
Labels: lgtm, size:XL

#18681 feat Improve OpenAPI and Requests tool capabilities and reliability
  llama-index-integrations/tools/llama-index-tools-openapi/CHANGELOG.md
  llama-index-integrations/tools/llama-index-tools-openapi/llama_index/tools/openapi/base.py
  llama-index-integrations/tools/llama-index-tools-openapi/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-openapi/tests/example.json
  llama-index-integrations/tools/llama-index-tools-openapi/tests/test_tools_openapi.py
  llama-index-integrations/tools/llama-index-tools-requests/CHANGELOG.md
  llama-index-integrations/tools/llama-index-tools-requests/llama_index/tools/requests/base.py
  llama-index-integrations/tools/llama-index-tools-requests/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-requests/tests/test_tools_requests.py
Labels: lgtm, size:XXL

#18687 fix: Handle possible OverflowError when getting Neptune node properties
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/neptune.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/pyproject.toml
Labels: lgtm, size:XS

#18696 chore: fix lagecy office reader bloated metadata
  llama-index-integrations/readers/llama-index-readers-legacy-office/llama_index/readers/legacy_office/reader.py
  llama-index-integrations/readers/llama-index-readers-legacy-office/pyproject.toml
Labels: lgtm, size:M

#18695 Bugfix: FastEmbedEmbedding was missing code to pass extra arguments to the api
  llama-index-integrations/embeddings/llama-index-embeddings-fastembed/llama_index/embeddings/fastembed/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-fastembed/pyproject.toml
Labels: lgtm, size:XS

#18703 look for azure openai key env var in auzre embeddings
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/llama_index/embeddings/azure_openai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/pyproject.toml
Labels: size:XS

#18704 update mkdocs and api_reference
  docs/docs/api_reference/memory/memory.md
  docs/docs/api_reference/storage/chat_store/async_sql.md
  docs/docs/module_guides/deploying/agents/memory.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/memory/__init__.py
  llama-index-core/llama_index/core/memory/chat_memory_buffer.py
  llama-index-core/llama_index/core/memory/chat_summary_memory_buffer.py
  llama-index-core/llama_index/core/memory/simple_composable_memory.py
  llama-index-core/llama_index/core/memory/vector_memory.py
Labels: size:M

#18711 Added Feature: Async methods for BaseIndex
  llama-index-core/llama_index/core/indices/base.py
  llama-index-core/llama_index/core/storage/index_store/keyval_index_store.py
  llama-index-core/llama_index/core/storage/index_store/types.py
  llama-index-core/tests/indices/vector_store/test_simple_async.py
Labels: enhancement, lgtm, size:L, P0

#18717 404 not anymore
  docs/docs/examples/agent/agent_workflow_multi.ipynb
Labels: lgtm, size:XS

#18720 `llama-index-embeddings-azure-openai`: fix typo of the if branch of get `api_key` if not use azure_ad
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/llama_index/embeddings/azure_openai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/pyproject.toml
Labels: lgtm, size:XS

#18464 Support Cohere V4 embeddings and V2 client
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/llama_index/embeddings/cohere/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/tests/test_embeddings.py
Labels: size:L

#18726 Update memory.md code block
  docs/docs/module_guides/deploying/agents/memory.md
Labels: size:S

#18728 LlamaIndex & Weaviate QueryAgent mult-agent
  docs/docs/_static/agents/workflow-weaviate-multiagent.png
  docs/docs/examples/agent/multi_agent_workflow_with_weaviate_queryagent.ipynb
  docs/mkdocs.yml
Labels: size:XL

#18729 MCP one-liners
  docs/docs/examples/tools/mcp.ipynb
  llama-index-integrations/tools/llama-index-tools-mcp/README.md
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/__init__.py
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/utils.py
  llama-index-integrations/tools/llama-index-tools-mcp/pyproject.toml
Labels: size:L

#18675 Adding Async Redis Vector Store
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/tests/conftest.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/tests/test_vector_stores_redis.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/uv.lock
Labels: lgtm, size:L

#18727 Add Meta header
  llama-index-integrations/llms/llama-index-llms-meta/llama_index/llms/meta/__init__.py
  llama-index-integrations/llms/llama-index-llms-meta/llama_index/llms/meta/base.py
  llama-index-integrations/llms/llama-index-llms-meta/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-meta/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-meta/tests/test_llms_llama.py
Labels: lgtm, size:XS

#18685 Add Vectorize retriever
  llama-index-integrations/retrievers/llama-index-retrievers-vectorize/.gitignore
  llama-index-integrations/retrievers/llama-index-retrievers-vectorize/Makefile
  llama-index-integrations/retrievers/llama-index-retrievers-vectorize/README.md
  llama-index-integrations/retrievers/llama-index-retrievers-vectorize/llama_index/retrievers/vectorize/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-vectorize/llama_index/retrievers/vectorize/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-vectorize/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-vectorize/tests/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-vectorize/tests/research.pdf
  llama-index-integrations/retrievers/llama-index-retrievers-vectorize/tests/test_retrievers_vectorize.py
  llama-index-integrations/retrievers/llama-index-retrievers-vectorize/uv.lock
Labels: lgtm, size:XL

#18690 Feature/brightdata integration
  llama-index-integrations/tools/llama-index-tools-brightdata/.gitignore
  llama-index-integrations/tools/llama-index-tools-brightdata/LICENSE
  llama-index-integrations/tools/llama-index-tools-brightdata/Makefile
  llama-index-integrations/tools/llama-index-tools-brightdata/README.md
  llama-index-integrations/tools/llama-index-tools-brightdata/llama_index/tools/brightdata/__init__.py
  llama-index-integrations/tools/llama-index-tools-brightdata/llama_index/tools/brightdata/base.py
  llama-index-integrations/tools/llama-index-tools-brightdata/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-brightdata/tests/__init__.py
  llama-index-integrations/tools/llama-index-tools-brightdata/tests/test_tools_brightdata.py
  llama-index-integrations/tools/llama-index-tools-brightdata/uv.lock
Labels: lgtm, size:XL

#18719 Add feature: support for DocumentBlock in OpenAI, Google GenAI, Anthropic and Bedrock Converse
  llama-dev/llama_dev/test/__init__.py
  llama-dev/tests/test/test_test.py
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/llama_index/core/extractors/document_context.py
  llama-index-core/llama_index/core/llms/__init__.py
  llama-index-core/llama_index/core/memory/memory.py
  llama-index-core/tests/base/llms/test_types.py
  llama-index-integrations/agent/llama-index-agent-openai/uv.lock
  llama-index-integrations/embeddings/llama-index-embeddings-fastembed/uv.lock
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-api/uv.lock
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum/uv.lock
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/uv.lock
  llama-index-integrations/embeddings/llama-index-embeddings-vllm/uv.lock
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/uv.lock
  llama-index-integrations/indices/llama-index-indices-managed-vectara/uv.lock
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/uv.lock
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/tests/test_bedrock_converse_utils.py
  llama-index-integrations/llms/llama-index-llms-cleanlab/uv.lock
  llama-index-integrations/llms/llama-index-llms-dashscope/uv.lock
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/utils.py
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-google-genai/uv.lock
  llama-index-integrations/llms/llama-index-llms-huggingface-api/uv.lock
  llama-index-integrations/llms/llama-index-llms-litellm/uv.lock
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
Labels: enhancement, lgtm, size:L, P0

#18730 make vector memory block multi-tennant
  llama-index-core/llama_index/core/memory/memory.py
  llama-index-core/llama_index/core/memory/memory_blocks/vector.py
Labels: size:M

#18734 llama-dev: add `--debug` flag and trim tests output to 50 lines
  .github/workflows/unit_test.yml
  llama-dev/llama_dev/cli.py
  llama-dev/llama_dev/test/__init__.py
  llama-dev/tests/test/test_test.py
Labels: size:M

#18739 Bumping versions of updated LLM packages so that they support also DocumentBlock
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-anthropic/uv.lock
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/uv.lock
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-google-genai/uv.lock
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/uv.lock
  uv.lock
Labels: bug, lgtm, size:S, P2

#18745 Add check for empty tool call delta, bump version
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:XS

#18740 Fix typos
  docs/docs/examples/evaluation/prometheus_evaluation.ipynb
  docs/docs/examples/finetuning/cross_encoder_finetuning/cross_encoder_finetuning.ipynb
  docs/docs/examples/llama_dataset/downloading_llama_datasets.ipynb
  docs/docs/examples/llm/google_genai.ipynb
  docs/docs/examples/llm/vllm.ipynb
  docs/docs/examples/memory/memory.ipynb
  docs/docs/examples/multi_modal/ChromaMultiModalDemo.ipynb
  docs/docs/examples/multi_modal/gpt4v_experiments_cot.ipynb
  docs/docs/examples/observability/MLflow.ipynb
  docs/docs/examples/observability/TokenCountingHandler.ipynb
  docs/docs/examples/query_engine/JSONalyze_query_engine.ipynb
  docs/docs/examples/retrievers/bm25_retriever.ipynb
  docs/docs/examples/tools/cassandra.ipynb
  docs/docs/examples/vector_stores/ChromaFireworksNomic.ipynb
  docs/docs/examples/vector_stores/ChromaIndexDemo.ipynb
  docs/docs/examples/vector_stores/qdrant_hybrid.ipynb
  docs/docs/examples/workflow/JSONalyze_query_engine.ipynb
  docs/docs/module_guides/querying/node_postprocessors/node_postprocessors.md
  docs/docs/understanding/agent/human_in_the_loop.md
  docs/docs/understanding/agent/index.md
  llama-index-core/llama_index/core/graph_stores/simple_labelled.py
  llama-index-core/llama_index/core/graph_stores/types.py
  llama-index-core/llama_index/core/storage/storage_context.py
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_nvidia.py
  llama-index-integrations/llms/llama-index-llms-oci-genai/llama_index/llms/oci_genai/base.py
  llama-index-integrations/tools/llama-index-tools-openapi/examples/openapi_and_requests.ipynb
  llama-index-integrations/tools/llama-index-tools-text-to-image/examples/text_to_image-pg.ipynb
  llama-index-integrations/tools/llama-index-tools-text-to-image/examples/text_to_image.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-lindorm/tests/test_lindorm_client.py
  llama-index-packs/llama-index-packs-zenguard/examples/zenguard.ipynb
Labels: lgtm, size:M

#18732 Rename couchbase vector store name
  docs/docs/api_reference/storage/vector_store/couchbase.md
  docs/docs/community/integrations/vector_stores.md
  docs/docs/examples/vector_stores/CouchbaseVectorStoreDemo.ipynb
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/llama_index/vector_stores/couchbase/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/llama_index/vector_stores/couchbase/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/tests/test_vector_stores_couchbase.py
Labels: lgtm, size:L

#18702 fix(chunking): Ensure correct handling of multi-byte characters during AST node chunking
  llama-index-core/llama_index/core/node_parser/text/code.py
Labels: lgtm, size:S

#18747 Pass agent workflow kwargs into start event
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
Labels: size:XS

#18722 Use `get_tqdm_iterable` in SimpleDirectoryReader
  llama-index-core/llama_index/core/readers/file/base.py
Labels: size:S

#18764 fix: broken hotpotqa dataset
  llama-index-core/llama_index/core/evaluation/benchmarks/hotpotqa.py
Labels: lgtm, size:XS

#18768 feat: add missing client params for bedrock
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: lgtm, size:M

#18780 support sqlalchemy v1 in chat store
  llama-index-core/llama_index/core/storage/chat_store/sql.py
Labels: size:S

#18782 reset next_agent in multi agent workflows
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
Labels: size:XS

#18781 Fix for issue [18775](https://github.com/run-llama/llama_index/issues/18775#issuecomment-2890774335)
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: size:S

#18784 Remove tool-length check in openai
  llama-index-integrations/llms/llama-index-llms-openai-like/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:XS

#18738 Feature/desearch integration
  llama-index-integrations/tools/llama-index-tools-desearch/.gitignore
  llama-index-integrations/tools/llama-index-tools-desearch/LICENSE
  llama-index-integrations/tools/llama-index-tools-desearch/Makefile
  llama-index-integrations/tools/llama-index-tools-desearch/README.md
  llama-index-integrations/tools/llama-index-tools-desearch/examples/desearch.ipynb
  llama-index-integrations/tools/llama-index-tools-desearch/llama_index/tools/desearch/__init__.py
  llama-index-integrations/tools/llama-index-tools-desearch/llama_index/tools/desearch/base.py
  llama-index-integrations/tools/llama-index-tools-desearch/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-desearch/tests/__init__.py
  llama-index-integrations/tools/llama-index-tools-desearch/tests/test_tools_desearch.py
Labels: lgtm, size:XL

#18785 v0.12.37
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/tools/desearch.md
  docs/docs/examples/memory/custom_multi_turn_memory.ipynb
  docs/docs/module_guides/deploying/agents/memory.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai-like/uv.lock
  llama-index-integrations/tools/llama-index-tools-desearch/pyproject.toml
  pyproject.toml
  uv.lock
Labels: size:XL

#18783 Allow `ctx` in BaseToolSpec functions, other ctx + tool calling overhauls
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-core/llama_index/core/tools/function_tool.py
  llama-index-core/llama_index/core/tools/tool_spec/base.py
  llama-index-core/tests/agent/workflow/test_multi_agent_workflow.py
  llama-index-core/tests/tools/test_base.py
  llama-index-core/tests/tools/tool_spec/test_base.py
Labels: lgtm, size:L

#18788 chore: fix broken URL
  docs/docs/understanding/agent/index.md
Labels: lgtm, size:XS

#18778 feature/featherless-llm-integration
  docs/docs/examples/llm/featherlessai.ipynb
  llama-index-integrations/llms/llama-index-llms-featherlessai/.gitignore
  llama-index-integrations/llms/llama-index-llms-featherlessai/LICENSE
  llama-index-integrations/llms/llama-index-llms-featherlessai/Makefile
  llama-index-integrations/llms/llama-index-llms-featherlessai/README.md
  llama-index-integrations/llms/llama-index-llms-featherlessai/llama_index/llms/featherlessai/__init__.py
  llama-index-integrations/llms/llama-index-llms-featherlessai/llama_index/llms/featherlessai/base.py
  llama-index-integrations/llms/llama-index-llms-featherlessai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-featherlessai/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-featherlessai/tests/test_llms_featherlessai.py
  llama-index-integrations/llms/llama-index-llms-featherlessai/uv.lock
Labels: lgtm, size:XL

#18790 Skip tool description length check in OpenAI agent
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/step.py
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
Labels: lgtm, size:XS

#18772 feat: add azure foundry agent integration
  llama-index-integrations/agent/llama-index-agent-azure/.gitignore
  llama-index-integrations/agent/llama-index-agent-azure/Makefile
  llama-index-integrations/agent/llama-index-agent-azure/README.md
  llama-index-integrations/agent/llama-index-agent-azure/llama_index/agent/azure_foundry_agent/__init__.py
  llama-index-integrations/agent/llama-index-agent-azure/llama_index/agent/azure_foundry_agent/base.py
  llama-index-integrations/agent/llama-index-agent-azure/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-azure/tests/test_azure_foundry_agent.py
Labels: lgtm, size:XXL

#18791 Fixing DocumentBlock usage within Bedrock Converse
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: bug, lgtm, size:S, P1

#18794 Bumping Bedrock version
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: lgtm, size:XS

#18795 docs: added badge and link to build package workflow
  README.md
Labels: lgtm, size:XS

#18793 Introducing voyage-3.5 models
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/llama_index/embeddings/voyageai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/pyproject.toml
Labels: lgtm, size:S

#18796 Fix get_function_tool in function_program.py when schema doesn't have "title" key
  llama-index-core/llama_index/core/program/function_program.py
Labels: lgtm, size:XS

#18798 Create PostgresKVStore from existing SQLAlchemy Engine
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-postgres/llama_index/storage/kvstore/postgres/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-postgres/pyproject.toml
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-postgres/uv.lock
Labels: lgtm, size:S

#18744 Add feature: OpenTelemetry integration for observability
  .gitignore
  llama-index-core/llama_index/core/instrumentation/events/llm.py
  llama-index-integrations/llms/llama-index-llms-anthropic/uv.lock
  llama-index-integrations/llms/llama-index-llms-openai/uv.lock
  llama-index-integrations/observability/llama-index-observability-otel/.gitignore
  llama-index-integrations/observability/llama-index-observability-otel/LICENSE
  llama-index-integrations/observability/llama-index-observability-otel/Makefile
  llama-index-integrations/observability/llama-index-observability-otel/README.md
  llama-index-integrations/observability/llama-index-observability-otel/llama_index/observability/otel/__init__.py
  llama-index-integrations/observability/llama-index-observability-otel/llama_index/observability/otel/base.py
  llama-index-integrations/observability/llama-index-observability-otel/llama_index/observability/otel/utils.py
  llama-index-integrations/observability/llama-index-observability-otel/pyproject.toml
  llama-index-integrations/observability/llama-index-observability-otel/tests/test_initialization.py
  llama-index-integrations/observability/llama-index-observability-otel/uv.lock
Labels: enhancement, size:XL

#18754 [Community integration] Update Cleanlab docs
  docs/docs/examples/cookbooks/cleanlab_tlm_rag.ipynb
  docs/docs/examples/evaluation/Cleanlab.ipynb
  docs/docs/examples/llm/cleanlab.ipynb
Labels: lgtm, size:L

#18801 Cleaning up the initialization of the PostgresKVStore class
  llama-index-core/uv.lock
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-postgres/pyproject.toml
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-postgres/llama_index/storage/kvstore/postgres/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-postgres/pyproject.toml
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-postgres/tests/test_postgres.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-postgres/tests/test_storage_kvstore_postgres.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-postgres/uv.lock
Labels: bug, lgtm, size:M

#18802 Use global llama_index tokenizer in Raptor clustering
  llama-index-packs/llama-index-packs-raptor/llama_index/packs/raptor/clustering.py
  llama-index-packs/llama-index-packs-raptor/pyproject.toml
Labels: lgtm, size:XS

#18805 dont pass in both extra_info and metadata in vector stores
  llama-index-integrations/vector_stores/llama-index-vector-stores-lindorm/llama_index/vector_stores/lindorm/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-lindorm/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
Labels: size:XS

#18810 Adding new OpenAI responses features (image gen, mcp call, code interpreter)
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/responses.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_responses.py
  llama-index-integrations/llms/llama-index-llms-openai/uv.lock
  llama-index-packs/llama-index-packs-raptor/tests/test_packs_raptor.py
Labels: enhancement, lgtm, size:M, P1

#18817 update for claude 4 support in Anthropic LLM
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-anthropic/uv.lock
Labels: size:M

#18815 use default temp in ollama models
  llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
  llama-index-integrations/llms/llama-index-llms-ollama/pyproject.toml
Labels: size:S

#18820 Update/fix claude-4 support
  docs/docs/examples/llm/anthropic.ipynb
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: size:L

#18821 fix once and for all
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: size:S

#18824 Fix: Update OpenAI response type imports for latest openai library compatibility
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/responses.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_responses.py
  llama-index-integrations/llms/llama-index-llms-openai/uv.lock
Labels: lgtm, size:M

#18822 Attempt to automatically set context window in ollama
  llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
  llama-index-integrations/llms/llama-index-llms-ollama/pyproject.toml
Labels: size:S

#18818 Fix: Reduce issues when parsing "Thought/Action/Action Input" completions (#12699, #14736)
  llama-index-core/llama_index/core/agent/react/templates/system_header_template.md
Labels: lgtm, size:XS

#18827 feature/add-claude4-model-support
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: lgtm, size:XS

#18807 [Documentation] Add missing documentation for new Featherless LLM provider
  docs/docs/api_reference/llms/featherlessai.md
  docs/docs/module_guides/models/llms/modules.md
  docs/mkdocs.yml
  llama-index-cli/llama_index/cli/upgrade/mappings.json
Labels: lgtm, size:XS

#18825 Strip code block backticks from QueryFusionRetriever llm response
  llama-index-core/llama_index/core/retrievers/fusion_retriever.py
Labels: lgtm, size:XS

#18808 feat: Optimize get_biggest_prompt for readability and efficiency
  llama-index-core/llama_index/core/prompts/prompt_utils.py
Labels: lgtm, size:XS

#18819 Throw error if resolve methods yield empty bytes
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/tests/base/llms/test_types.py
Labels: enhancement, lgtm, size:M, P0

#18834 fix thinking + tool calls in anthropic
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: size:XS

#18838 check thinking is non-null in anthropic messages
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: lgtm, size:XS

#18833 mcp client upgrade
  docs/docs/examples/tools/mcp.ipynb
  llama-index-integrations/tools/llama-index-tools-mcp/README.md
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/__init__.py
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/base.py
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/client.py
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/utils.py
  llama-index-integrations/tools/llama-index-tools-mcp/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-mcp/tests/server.py
  llama-index-integrations/tools/llama-index-tools-mcp/tests/test_client.py
  llama-index-integrations/tools/llama-index-tools-mcp/uv.lock
Labels: size:XL

#18844 fix resuming AgentWorkflow from ctx during hitl
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-core/tests/agent/workflow/test_multi_agent_workflow.py
Labels: size:M

#18846 add gemini embeddings tests and retry configs
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/llama_index/embeddings/google_genai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/tests/test_embeddings_gemini.py
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/uv.lock
Labels: size:L

#18831 Updated RankLLM integration into llama_index
  docs/docs/examples/node_postprocessor/rankLLM.ipynb
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/examples/rankLLM.ipynb
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/llama_index/postprocessor/rankllm_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/llama_index/postprocessor/rankllm_rerank/test.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/pyproject.toml
Labels: lgtm, size:L

#18841 feat: add Servam AI LLM integration with OpenAI-like interface
  llama-index-integrations/llms/llama-index-llms-sarvam/.gitignore
  llama-index-integrations/llms/llama-index-llms-sarvam/Makefile
  llama-index-integrations/llms/llama-index-llms-sarvam/README.md
  llama-index-integrations/llms/llama-index-llms-sarvam/llama_index/llms/servam/__init__.py
  llama-index-integrations/llms/llama-index-llms-sarvam/llama_index/llms/servam/base.py
  llama-index-integrations/llms/llama-index-llms-sarvam/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-sarvam/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-sarvam/tests/test_llms_servam.py
  llama-index-integrations/llms/llama-index-llms-sarvam/uv.lock
Labels: lgtm, size:L

#18829 feat: add configurable allow_parallel_tool_calls to FunctionAgent
  llama-index-core/llama_index/core/agent/workflow/function_agent.py
Labels: lgtm, size:XS

#18809 llm-compiler support stream_step/astream_step
  llama-index-integrations/agent/llama-index-agent-llm-compiler/llama_index/agent/llm_compiler/step.py
  llama-index-integrations/agent/llama-index-agent-llm-compiler/pyproject.toml
Labels: lgtm, size:L

#18816 Fix: Metadata and filename in azstorageblobreader
  llama-index-integrations/readers/llama-index-readers-azstorage-blob/llama_index/readers/azstorage_blob/base.py
  llama-index-integrations/readers/llama-index-readers-azstorage-blob/pyproject.toml
Labels: lgtm, size:M

#18857 Docs: fix markdown syntax for proper rendering
  docs/docs/getting_started/starter_tools/index.md
Labels: lgtm, size:XS

#18862 Fix/llama index readers file pptx
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/slides/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:XS

#18871 Update ModelScope.ipynb
  docs/docs/examples/llm/modelscope.ipynb
Labels: lgtm, size:XS

#18874 Add retrievers in NLSQLTableQueryEngine
  llama-index-core/llama_index/core/indices/struct_store/sql_query.py
Labels: lgtm, size:XS

#18882 ci: fix debug logging
  .github/workflows/unit_test.yml
Labels: lgtm, size:XS

#18881 fix: Pass http_client & async_http_client to parent for OpenAILikeEmbedding
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/llama_index/embeddings/openai_like/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/pyproject.toml
Labels: lgtm, size:XS

#18867 add client support for search_filters_inference_schema
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/tests/test_indices_managed_llama_cloud.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/uv.lock
Labels: lgtm, size:M

#18879 fix: McpToolSpec fetch all tools given the empty allowed_tools list
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/base.py
  llama-index-integrations/tools/llama-index-tools-mcp/tests/test_tools_mcp.py
Labels: lgtm, size:L

#18868 feat: enhance SSE endpoint detection for broader compatibility
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/client.py
  llama-index-integrations/tools/llama-index-tools-mcp/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-mcp/tests/test_client.py
Labels: lgtm, size:M
