Repository run-llama/llama_index, pull requests merged in 2025-07, with the labels that each got.

#19279 Support loading Node from ingestion cache
  llama-index-core/llama_index/core/storage/docstore/utils.py
Labels: lgtm, size:XS

#19283 v0.12.45
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-core/uv.lock
  pyproject.toml
  uv.lock
Labels: size:L

#19286 Fix inconsistent ref node handling
  llama-index-core/llama_index/core/storage/docstore/keyval_docstore.py
Labels: lgtm, size:S

#19295 Bug fix: embedding model with custom endpoints 404 error
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/conftest.py
Labels: lgtm, size:XS

#19304 bump min google-genai version
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/uv.lock
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-google-genai/uv.lock
Labels: size:XS

#19307 bug_fix: configuring resources from the mcp server correctly
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/base.py
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/client.py
  llama-index-integrations/tools/llama-index-tools-mcp/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-mcp/uv.lock
Labels: lgtm, size:S

#19311 fix raptor tests?
  llama-index-packs/llama-index-packs-raptor/pyproject.toml
  llama-index-packs/llama-index-packs-raptor/uv.lock
Labels: size:XS

#19312 v0.12.46
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  pyproject.toml
  uv.lock
Labels: size:M

#19317 vbump llama-cloud
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/uv.lock
Labels: size:XS

#19306 Add support of Image prompt for OCI generative AI Llama models
  docs/docs/examples/llm/oci_genai.ipynb
  llama-index-integrations/llms/llama-index-llms-oci-genai/llama_index/llms/oci_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-oci-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-oci-genai/tests/test_oci_genai.py
  llama-index-integrations/llms/llama-index-llms-oci-genai/uv.lock
Labels: lgtm, size:L

#19318 fix: fixed parsing of empty list
  llama-index-core/llama_index/core/output_parsers/utils.py
Labels: lgtm, size:XS

#19232 Adding an integration for LanceDB MultiModal AI LakeHouse
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/.gitignore
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/LICENSE
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/Makefile
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/README.md
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/llama_index/indices/managed/lancedb/__init__.py
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/llama_index/indices/managed/lancedb/base.py
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/llama_index/indices/managed/lancedb/query_engine.py
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/llama_index/indices/managed/lancedb/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/llama_index/indices/managed/lancedb/utils.py
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/llama_index/py.typed
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/tests/__init__.py
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/tests/test_index.py
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/uv.lock
Labels: lgtm, size:XXL

#19203 Add firecrawl integration source
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/firecrawl_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:M

#19325 fix missing raw in agent workflow events
  llama-index-core/llama_index/core/agent/workflow/workflow_events.py
Labels: size:XS

#19035 add default max iterations of 20 for agents
  llama-index-core/llama_index/core/agent/workflow/base_agent.py
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-core/llama_index/core/agent/workflow/workflow_events.py
  llama-index-core/tests/agent/workflow/test_multi_agent_workflow.py
  llama-index-core/tests/agent/workflow/test_single_agent_workflow.py
Labels: lgtm, size:L

#19341 Fix documentation for MultiModal inference with mistral AI
  docs/docs/api_reference/multi_modal_llms/mistralai.md
Labels: lgtm, size:XS

#19335 fix: Ensure CallbackManager is applied to default embed_model
  llama-index-core/llama_index/core/indices/vector_store/base.py
Labels: lgtm, size:XS

#19352 Fix broken lancedb tests
  llama-index-integrations/indices/llama-index-indices-managed-lancedb/tests/test_index.py
Labels: size:M

#19351 Fix IntelEmbedding base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/llama_index/embeddings/huggingface_optimum_intel/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-optimum-intel/pyproject.toml
Labels: size:S

#19347 [DOCS] update Hugging Face Inference example
  docs/docs/examples/llm/huggingface.ipynb
Labels: lgtm, size:L

#19343 Don't store Copy of document in metadata and properly return Nodes
  llama-index-core/llama_index/core/storage/docstore/utils.py
  llama-index-core/llama_index/core/vector_stores/utils.py
Labels: lgtm, size:S

#19365 Update asyncpg
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-postgres/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-lantern/pyproject.toml
Labels: lgtm, size:XS

#19373 docs: Fix broken 'Quick Start Guide' link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size:XS

#19361 Add Cached Content Support to GoogleGenAI LLM Integration
  docs/docs/examples/llm/google_genai.ipynb
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/base.py
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-google-genai/tests/test_llms_google_genai.py
  llama-index-integrations/llms/llama-index-llms-google-genai/tests/test_llms_google_genai_vertex.py
Labels: lgtm, size:XL

#19377 DuckDB Small clean-up and add embeddings to returned nodes
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/llama_index/vector_stores/duckdb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/tests/test_duckdb.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/tests/test_vector_stores_duckdb.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/uv.lock
Labels: size:S

#19366 nvidia-llm : Adding support to use llm models outside default list
  llama-index-integrations/llms/llama-index-llms-nvidia/README.md
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/base.py
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_unknown_models.py
Labels: lgtm, size:M

#19376 Fix bugs in tool calling for OCI generative AI Llama models
  docs/docs/examples/llm/oci_genai.ipynb
  llama-index-integrations/llms/llama-index-llms-oci-genai/llama_index/llms/oci_genai/base.py
  llama-index-integrations/llms/llama-index-llms-oci-genai/llama_index/llms/oci_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-oci-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-oci-genai/tests/test_llms_oci_genai.py
Labels: size:M

#19380 Retriever Query Engine should use async node postprocessors
  llama-index-core/llama_index/core/query_engine/retriever_query_engine.py
Labels: lgtm, size:S

#19369 Fix BedrockConverse streaming token counting by handling messageStop …
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/tests/test_llms_bedrock_converse.py
Labels: lgtm, size:L

#19383 DuckDB Async and Faster Cosine Similarity
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/llama_index/vector_stores/duckdb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/tests/test_duckdb.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/uv.lock
Labels: lgtm, size:L

#19282 Add DuckDB KV, Document, and Index Store
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-duckdb/.gitignore
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-duckdb/LICENSE
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-duckdb/Makefile
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-duckdb/README.md
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-duckdb/llama_index/storage/docstore/duckdb/__init__.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-duckdb/llama_index/storage/docstore/duckdb/base.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-duckdb/pyproject.toml
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-duckdb/tests/__init__.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-duckdb/tests/test_storage_docstore_duckdb.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-duckdb/uv.lock
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-duckdb/.gitignore
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-duckdb/LICENSE
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-duckdb/Makefile
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-duckdb/README.md
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-duckdb/llama_index/storage/index_store/duckdb/__init__.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-duckdb/llama_index/storage/index_store/duckdb/base.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-duckdb/pyproject.toml
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-duckdb/tests/__init__.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-duckdb/tests/test_storage_index_store_duckdb.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-duckdb/uv.lock
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/.gitignore
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/LICENSE
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/Makefile
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/README.md
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/llama_index/storage/kvstore/duckdb/__init__.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/llama_index/storage/kvstore/duckdb/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/pyproject.toml
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/tests/__init__.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/tests/test_storage_kvstore_duckdb.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/uv.lock
Labels: lgtm, size:XXL

#19382 Refactor vector index retrieval
  llama-index-core/llama_index/core/indices/vector_store/retrievers/retriever.py
  llama-index-core/tests/indices/vector_store/test_retrievers.py
Labels: lgtm, size:L

#19386 Add FlashRank Rerank
  llama-index-integrations/postprocessor/llama-index-postprocessor-flashrank-rerank/.gitignore
  llama-index-integrations/postprocessor/llama-index-postprocessor-flashrank-rerank/LICENSE
  llama-index-integrations/postprocessor/llama-index-postprocessor-flashrank-rerank/Makefile
  llama-index-integrations/postprocessor/llama-index-postprocessor-flashrank-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-flashrank-rerank/llama_index/postprocessor/flashrank_rerank/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-flashrank-rerank/llama_index/postprocessor/flashrank_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-flashrank-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-flashrank-rerank/tests/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-flashrank-rerank/tests/test_postprocessor_flashrank_rerank.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-flashrank-rerank/uv.lock
Labels: lgtm, size:L

#19391 Improvements for DuckDB thread safety and embed dimension handling
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/llama_index/storage/kvstore/duckdb/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/pyproject.toml
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/uv.lock
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/llama_index/vector_stores/duckdb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/tests/test_duckdb.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/uv.lock
Labels: lgtm, size:M

#19399 fix: Fix broken document links
  docs/mkdocs.yml
Labels: size:XS

#19394 chore: modifying raptors dependencies with stricter rules to avoid test failures
  llama-index-packs/llama-index-packs-raptor/pyproject.toml
  llama-index-packs/llama-index-packs-raptor/uv.lock
Labels: size:XS

#19349 feat: Add Moorcheh vector store integration
  docs/docs/examples/vector_stores/MoorchehDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-moorcheh/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-moorcheh/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-moorcheh/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-moorcheh/llama_index/py.typed
  llama-index-integrations/vector_stores/llama-index-vector-stores-moorcheh/llama_index/vector_stores/moorcheh/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-moorcheh/llama_index/vector_stores/moorcheh/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-moorcheh/llama_index/vector_stores/moorcheh/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-moorcheh/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-moorcheh/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-moorcheh/tests/test_vector_stores_moorcheh.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-moorcheh/uv.lock
Labels: lgtm, size:XXL

#19401 DuckDB: Deadlocks-b-gone
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/llama_index/storage/kvstore/duckdb/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/pyproject.toml
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-duckdb/tests/test_storage_kvstore_duckdb.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/llama_index/vector_stores/duckdb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/tests/test_duckdb.py
Labels: lgtm, size:XXL

#19409 Fix: prevent duplicate triplets in SimpleGraphStore.upsert_triplet (#19404)
  llama-index-core/llama_index/core/graph_stores/simple.py
Labels: lgtm, size:XS

#19414 fix: fix structured output
  llama-index-core/llama_index/core/agent/utils.py
  llama-index-core/llama_index/core/agent/workflow/base_agent.py
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-core/tests/agent/utils/test_agent_utils.py
Labels: lgtm, size:L

#19421 v0.12.49
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/postprocessor/flashrank_rerank.md
  docs/docs/api_reference/storage/docstore/duckdb.md
  docs/docs/api_reference/storage/index_store/duckdb.md
  docs/docs/api_reference/storage/kvstore/duckdb.md
  docs/docs/api_reference/storage/vector_store/moorcheh.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  pyproject.toml
  uv.lock
Labels: size:L

#19415 fix: make get_cache_dir() function more secure
  llama-index-core/llama_index/core/utils.py
  llama-index-core/pyproject.toml
  llama-index-core/tests/test_utils.py
  llama-index-core/uv.lock
Labels: lgtm, size:L

#19406 Add google_search Tool Support to GoogleGenAI LLM Integration
  docs/docs/examples/llm/google_genai.ipynb
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/base.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-google-genai/tests/test_llms_google_genai.py
  llama-index-integrations/llms/llama-index-llms-google-genai/uv.lock
Labels: size:XL

#19444 fix: use a private folder to store NTLK cache
  llama-index-core/llama_index/core/utils.py
Labels: lgtm, size:S

#19413 Fix/make sure to stop agent on function tool return direct
  llama-index-core/llama_index/core/agent/workflow/base_agent.py
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-core/pyproject.toml
  llama-index-core/tests/agent/workflow/test_function_call.py
  llama-index-core/tests/agent/workflow/test_return_direct_e2e.py
  llama-index-core/uv.lock
Labels: lgtm, size:XL

#19424 Confluence reader enhancements
  llama-index-integrations/readers/llama-index-readers-confluence/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-confluence/README.md
  llama-index-integrations/readers/llama-index-readers-confluence/llama_index/readers/confluence/base.py
  llama-index-integrations/readers/llama-index-readers-confluence/llama_index/readers/confluence/event.py
  llama-index-integrations/readers/llama-index-readers-confluence/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-confluence/tests/run_basic_tests.py
  llama-index-integrations/readers/llama-index-readers-confluence/tests/test_integration.py
  llama-index-integrations/readers/llama-index-readers-confluence/tests/test_new_features.py
  llama-index-integrations/readers/llama-index-readers-confluence/tests/test_readers_confluence.py
Labels: size:XXL

#19435 fix: add structured output to multi agent also from secondary constructor + tests
  docs/docs/understanding/agent/multi_agent.md
  docs/docs/understanding/agent/structured_output.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/agent/workflow/__init__.py
  llama-index-core/llama_index/core/agent/workflow/base_agent.py
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-core/llama_index/core/agent/workflow/workflow_events.py
  llama-index-core/tests/agent/workflow/test_agent_with_structured_output.py
  llama-index-core/tests/agent/workflow/test_events.py
Labels: size:L

#19439 Muhammadk 03/fix llamadev no tests skip
  llama-dev/llama_dev/test/__init__.py
  llama-dev/tests/test/test_test.py
Labels: lgtm, size:L

#19449 feat: support html table extraction in MarkdownElementNodeParser
  llama-index-core/llama_index/core/node_parser/relational/markdown_element.py
  llama-index-core/tests/node_parser/test_markdown_element.py
Labels: lgtm, size:L

#19448 fix: handle ID type mismatch in Faiss retriever (fixes #19445)
  llama-index-core/llama_index/core/indices/vector_store/retrievers/retriever.py
  llama-index-core/tests/indices/vector_store/test_retrievers.py
Labels: lgtm, size:M

#19456 s3 vectors support
  docs/docs/examples/vector_stores/S3VectorStore.ipynb
  docs/docs/module_guides/storing/vector_stores.md
  docs/mkdocs.yml
  llama-index-integrations/vector_stores/llama-index-vector-stores-s3/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-s3/LICENSE
  llama-index-integrations/vector_stores/llama-index-vector-stores-s3/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-s3/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-s3/llama_index/py.typed
  llama-index-integrations/vector_stores/llama-index-vector-stores-s3/llama_index/vector_stores/s3/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-s3/llama_index/vector_stores/s3/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-s3/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-s3/tests/test_s3_vector_store.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-s3/uv.lock
Labels: lgtm, size:XXL

#19464 Remove load_kwargs from WikipediaToolSpec.load_data tool
  llama-index-integrations/tools/llama-index-tools-wikipedia/llama_index/tools/wikipedia/base.py
  llama-index-integrations/tools/llama-index-tools-wikipedia/pyproject.toml
Labels: size:S

#19469 remove some stray debug prints from AGUI
  llama-index-integrations/protocols/llama-index-protocols-ag-ui/llama_index/protocols/ag_ui/router.py
  llama-index-integrations/protocols/llama-index-protocols-ag-ui/llama_index/protocols/ag_ui/utils.py
  llama-index-integrations/protocols/llama-index-protocols-ag-ui/pyproject.toml
Labels: size:XS

#19468 state docs nits
  docs/docs/examples/agent/agent_workflow_basic.ipynb
  docs/docs/examples/agent/agent_workflow_multi.ipynb
  docs/docs/examples/agent/agents_as_tools.ipynb
  docs/docs/examples/agent/custom_multi_agent.ipynb
  docs/docs/module_guides/workflow/index.md
  docs/docs/understanding/agent/multi_agent.md
  docs/docs/understanding/agent/state.md
  docs/docs/understanding/workflows/state.md
Labels: size:L

#19470 Fix workflow agents as MCP servers
  llama-index-core/llama_index/core/agent/workflow/base_agent.py
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
Labels: size:M

#19472 Fix milvus tests
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/tests/test_vector_stores_milvus.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/uv.lock
Labels: size:XXL

#19466 refactor: update document store import to use BaseDocumentStore in DocumentContextExtractor
  llama-index-core/llama_index/core/extractors/document_context.py
Labels: lgtm, size:XS

#19461 Update Moorcheh Vector Store
  llama-index-integrations/vector_stores/llama-index-vector-stores-moorcheh/llama_index/vector_stores/moorcheh/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-moorcheh/pyproject.toml
Labels: size:M

#19484 Add Documentation and Tests for Code Execution Tool in GoogleGenAI Integration
  docs/docs/examples/llm/google_genai.ipynb
  llama-index-integrations/llms/llama-index-llms-google-genai/tests/test_llms_google_genai.py
Labels: size:L

#19479 Enhance FunctionTool with auto type conversion for basic Python types like `date` (Fixes #19452)
  llama-index-core/llama_index/core/tools/utils.py
  llama-index-core/tests/tools/test_utils.py
Labels: lgtm, size:M

#19485 docs: structured input
  docs/docs/examples/prompts/structured_input.ipynb
  docs/docs/understanding/extraction/lower_level.md
  docs/docs/understanding/extraction/structured_input.md
  docs/mkdocs.yml
Labels: lgtm, size:L

#19476 Fix retriever KeyError when using FAISS
  llama-index-core/llama_index/core/indices/vector_store/retrievers/retriever.py
  llama-index-core/tests/indices/vector_store/test_retrievers.py
Labels: lgtm, size:S

#19491 Fix metadata serialization issue in AzStorageBlobReader
  llama-index-integrations/readers/llama-index-readers-azstorage-blob/llama_index/readers/azstorage_blob/base.py
  llama-index-integrations/readers/llama-index-readers-azstorage-blob/pyproject.toml
Labels: lgtm, size:M

#19494 Fix/metadata serialization issue
  llama-index-integrations/readers/llama-index-readers-azstorage-blob/llama_index/readers/azstorage_blob/base.py
  llama-index-integrations/readers/llama-index-readers-azstorage-blob/pyproject.toml
Labels: lgtm, size:XS

#19492 v0.12.51
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  pyproject.toml
  uv.lock
Labels: size:M

#19501 Properly raise errors from docstore -- Fix Vector Index Retrieval
  llama-index-core/llama_index/core/indices/vector_store/retrievers/retriever.py
  llama-index-core/llama_index/core/storage/docstore/types.py
  llama-index-core/tests/indices/vector_store/test_retrievers.py
Labels: size:L

#19498 llama-index-integrations-neo4j - Patch Neo4jVector Call version
  llama-index-integrations/vector_stores/llama-index-vector-stores-neo4jvector/llama_index/vector_stores/neo4jvector/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-neo4jvector/pyproject.toml
Labels: lgtm, size:S

#19496 feat: optimize memory usage for BGEM3Index persistence (based on pickle)
  llama-index-integrations/indices/llama-index-indices-managed-bge-m3/llama_index/indices/managed/bge_m3/base.py
  llama-index-integrations/indices/llama-index-indices-managed-bge-m3/pyproject.toml
Labels: lgtm, size:S

#19504 Fix missing prompt in async MultiModalLLMProgram calls
  llama-index-core/llama_index/core/program/multi_modal_llm_program.py
Labels: lgtm, size:XS

#19503 Add timeout to webpage readers
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/async_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/simple_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-web/tests/test_async_web.py
  llama-index-integrations/readers/llama-index-readers-web/uv.lock
Labels: lgtm, size:M

#19507 v0.12.52
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/tools/jira_issue.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-core/uv.lock
  pyproject.toml
  uv.lock
Labels: size:M

#19520 Fix heading level for `DynamicLLMPathExtractor` in Property Graph docs
  docs/docs/module_guides/indexing/lpg_index_guide.md
Labels: lgtm, size:XS

#19519 Update mixedbread embeddings and rerank
  docs/docs/examples/embeddings/mixedbreadai.ipynb
  docs/docs/examples/node_postprocessor/MixedbreadAIRerank.ipynb
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/llama_index/embeddings/mixedbreadai/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/llama_index/embeddings/mixedbreadai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/tests/test_embeddings_mixedbreadai.py
  llama-index-integrations/embeddings/llama-index-embeddings-mixedbreadai/uv.lock
  llama-index-integrations/postprocessor/llama-index-postprocessor-mixedbreadai-rerank/llama_index/postprocessor/mixedbreadai_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-mixedbreadai-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-mixedbreadai-rerank/uv.lock
Labels: lgtm, size:L

#19541 Update Oxylabs integration documentation
  docs/docs/examples/data_connectors/WebPageDemo.ipynb
  llama-index-integrations/readers/llama-index-readers-oxylabs/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/oxylabs_web/base.py
Labels: lgtm, size:S

#19538 feat: Update Valyu tool to 0.3.0
  llama-index-integrations/tools/llama-index-tools-valyu/README.md
  llama-index-integrations/tools/llama-index-tools-valyu/llama_index/tools/valyu/base.py
  llama-index-integrations/tools/llama-index-tools-valyu/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-valyu/tests/test_tools_valyu.py
  llama-index-integrations/tools/llama-index-tools-valyu/uv.lock
Labels: lgtm, size:L

#19489 feat: adding first implementation of gemini live
  llama-index-integrations/voice_agents/llama-index-voice-agents-gemini-live/.gitignore
  llama-index-integrations/voice_agents/llama-index-voice-agents-gemini-live/LICENSE
  llama-index-integrations/voice_agents/llama-index-voice-agents-gemini-live/Makefile
  llama-index-integrations/voice_agents/llama-index-voice-agents-gemini-live/README.md
  llama-index-integrations/voice_agents/llama-index-voice-agents-gemini-live/llama_index/voice_agents/gemini_live/__init__.py
  llama-index-integrations/voice_agents/llama-index-voice-agents-gemini-live/llama_index/voice_agents/gemini_live/audio_interface.py
  llama-index-integrations/voice_agents/llama-index-voice-agents-gemini-live/llama_index/voice_agents/gemini_live/base.py
  llama-index-integrations/voice_agents/llama-index-voice-agents-gemini-live/llama_index/voice_agents/gemini_live/events.py
  llama-index-integrations/voice_agents/llama-index-voice-agents-gemini-live/llama_index/voice_agents/gemini_live/utils.py
  llama-index-integrations/voice_agents/llama-index-voice-agents-gemini-live/pyproject.toml
  llama-index-integrations/voice_agents/llama-index-voice-agents-gemini-live/tests/test_audio_interface.py
  llama-index-integrations/voice_agents/llama-index-voice-agents-gemini-live/tests/test_utils.py
Labels: lgtm, size:XL

#19526 add new upstage model(solar-pro2)
  llama-index-integrations/llms/llama-index-llms-upstage/llama_index/llms/upstage/utils.py
  llama-index-integrations/llms/llama-index-llms-upstage/pyproject.toml
Labels: lgtm, size:S

#19524 fix: add ```base_url``` property to nvidia class to fix test compatibility
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_base_url.py
Labels: lgtm, size:XS

#19521 fix(core): Handle empty prompt in MockLLM.stream_complete
  llama-index-core/llama_index/core/llms/mock.py
  llama-index-core/tests/llms/test_mock.py
Labels: lgtm, size:S

#19514 Where can we easily put LLMs txt?
  docs/docs/llms.txt
Labels: size:L

#19545 Support default managed embeddings in LlamaCloudIndex
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/README.md
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/api_utils.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/base.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/tests/test_indices_managed_llama_cloud.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/uv.lock
Labels: size:M

#19550 reduce some metadata keys from S3VectorStore to save space
  llama-index-integrations/vector_stores/llama-index-vector-stores-s3/llama_index/vector_stores/s3/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-s3/pyproject.toml
Labels: size:S

#19549 FIX: Bump Valyu SDK Version
  llama-index-integrations/tools/llama-index-tools-valyu/pyproject.toml
Labels: size:XS

#19505 Add Thought Summaries for Gemini.
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/base.py
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-google-genai/tests/test_llms_google_genai.py
  llama-index-integrations/llms/llama-index-llms-google-genai/uv.lock
Labels: lgtm, size:L

#19546 feat(s3): add support for region_name via client_kwargs in S3Reader (#19530)
  llama-index-integrations/readers/llama-index-readers-s3/llama_index/readers/s3/base.py
  llama-index-integrations/readers/llama-index-readers-s3/pyproject.toml
Labels: size:S

#19543 Github Reader enhancements
  llama-index-integrations/readers/llama-index-readers-github/README.md
  llama-index-integrations/readers/llama-index-readers-github/llama_index/readers/github/repository/base.py
  llama-index-integrations/readers/llama-index-readers-github/llama_index/readers/github/repository/event.py
  llama-index-integrations/readers/llama-index-readers-github/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-github/tests/test_github_repository_reader.py
Labels: size:XXL

#19555 Add support for specifying `partition_names` in Milvus search configuration
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/uv.lock
Labels: lgtm, size:XS

#19570 feat: bigquery vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/LICENSE
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/llama_index/py.typed
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/llama_index/vector_stores/bigquery/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/llama_index/vector_stores/bigquery/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/llama_index/vector_stores/bigquery/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/tests/conftest.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/tests/sql_assertions.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/tests/test_add.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/tests/test_delete.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/tests/test_delete_nodes.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/tests/test_get_nodes.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/tests/test_parameterized_queries.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/tests/test_vector_search.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/tests/test_vector_stores_bigquery.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-bigquery/uv.lock
Labels: lgtm, size:XXL

#19569 Add vercel ai gateway provider
  docs/docs/api_reference/llms/vercel_ai_gateway.md
  docs/docs/examples/llm/vercel-ai-gateway.ipynb
  docs/docs/module_guides/models/llms/modules.md
  docs/mkdocs.yml
  docs/mkdocs_api_only.yml
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/llms/llama-index-llms-vercel-ai-gateway/LICENSE
  llama-index-integrations/llms/llama-index-llms-vercel-ai-gateway/Makefile
  llama-index-integrations/llms/llama-index-llms-vercel-ai-gateway/README.md
  llama-index-integrations/llms/llama-index-llms-vercel-ai-gateway/llama_index/llms/vercel_ai_gateway/__init__.py
  llama-index-integrations/llms/llama-index-llms-vercel-ai-gateway/llama_index/llms/vercel_ai_gateway/base.py
  llama-index-integrations/llms/llama-index-llms-vercel-ai-gateway/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-vercel-ai-gateway/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-vercel-ai-gateway/tests/test_vercel_ai_gateway.py
  llama-index-integrations/llms/llama-index-llms-vercel-ai-gateway/uv.lock
Labels: lgtm, size:XXL
