Repository run-llama/llama_index, pull requests merged in 2025-06, with the labels that each got.

#18923 Handle untested no tools scenario for anthropic tool config
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-anthropic/tests/test_llms_anthropic.py
  llama-index-integrations/llms/llama-index-llms-anthropic/uv.lock
Labels: lgtm, size:M

#18922 Add compatibility check before providing tool_required
  llama-index-core/llama_index/core/llms/function_calling.py
  llama-index-core/tests/llms/test_function_calling.py
Labels: lgtm, size:L

#18915 fix(cohere-embedding): add batch size validation with 96 limit for Cohere API
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/llama_index/embeddings/cohere/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/tests/test_embeddings.py
Labels: lgtm, size:M

#18918 Fix some field types of OpenAI LLM API
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:S

#18919 Add headers handling to BasicMCPClient
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/client.py
  llama-index-integrations/tools/llama-index-tools-mcp/pyproject.toml
Labels: lgtm, size:S

#18935 Support passing static AWS credentials to Anthropic Bedrock
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-anthropic/tests/test_llms_anthropic.py
  llama-index-integrations/llms/llama-index-llms-anthropic/uv.lock
Labels: lgtm, size:S

#18932 Add StopEvent step validation
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: lgtm, size:M

#18909 Add weather, climate, air quality and geocoding tool from Measure Space
  llama-index-integrations/tools/llama-index-tools-measurespace/.gitignore
  llama-index-integrations/tools/llama-index-tools-measurespace/CHANGELOG.md
  llama-index-integrations/tools/llama-index-tools-measurespace/LICENSE
  llama-index-integrations/tools/llama-index-tools-measurespace/Makefile
  llama-index-integrations/tools/llama-index-tools-measurespace/README.md
  llama-index-integrations/tools/llama-index-tools-measurespace/examples/example.ipynb
  llama-index-integrations/tools/llama-index-tools-measurespace/examples/example.py
  llama-index-integrations/tools/llama-index-tools-measurespace/llama_index/tools/measurespace/__init__.py
  llama-index-integrations/tools/llama-index-tools-measurespace/llama_index/tools/measurespace/base.py
  llama-index-integrations/tools/llama-index-tools-measurespace/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-measurespace/uv.lock
Labels: lgtm, size:XL

#18950 Obsidian reader checks and skips hardlinks
  llama-index-integrations/readers/llama-index-readers-obsidian/llama_index/readers/obsidian/base.py
  llama-index-integrations/readers/llama-index-readers-obsidian/pyproject.toml
Labels: lgtm, size:S

#18945 Using httpx instead of urllib in llama-index-readers-web
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/sitemap/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:XS

#18893 Add MutableMappingKVStore
  llama-index-core/llama_index/core/storage/docstore/simple_docstore.py
  llama-index-core/llama_index/core/storage/index_store/simple_index_store.py
  llama-index-core/llama_index/core/storage/kvstore/simple_kvstore.py
  llama-index-core/llama_index/core/storage/kvstore/types.py
  llama-index-core/tests/node_parser/sentence_window.py
  llama-index-core/tests/storage/kvstore/test_mutable_mapping_kvstore.py
Labels: lgtm, size:L

#18943 Adding warning in the docstring of JsonPickleSerializer for the user to deserialize only safe things
  llama-index-core/llama_index/core/workflow/context_serializers.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: lgtm, size:S

#18951 Fix overwriting of LLM callback manager from Settings
  llama-index-core/llama_index/core/llms/utils.py
Labels: lgtm, size:XS

#18956 Fix/skip tool description length check in openai response api
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/responses.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:XS

#18927 Adding support for log recording during MCP tool calls
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/client.py
  llama-index-integrations/tools/llama-index-tools-mcp/pyproject.toml
Labels: lgtm, size:M

#18955 feat: Add DocumentBlock support to LiteLLM integration
  llama-index-integrations/llms/llama-index-llms-litellm/llama_index/llms/litellm/utils.py
  llama-index-integrations/llms/llama-index-llms-litellm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-litellm/tests/conftest.py
  llama-index-integrations/llms/llama-index-llms-litellm/tests/test_llms_litellm.py
  llama-index-integrations/llms/llama-index-llms-litellm/tests/test_utils.py
  llama-index-integrations/llms/llama-index-llms-litellm/uv.lock
Labels: lgtm, size:L

#18897 feat: add OpenAI JSON Schema structured output support
  llama-index-core/llama_index/core/llms/llm.py
  llama-index-core/llama_index/core/program/streaming_utils.py
  llama-index-core/tests/program/test_streaming_utils.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai.py
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_utils.py
Labels: lgtm, size:XL

#18970 migrate llama-index-cli to uv
  llama-index-cli/pyproject.toml
Labels: size:L

#18973 chore: composite retrieval add ReRankConfig
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/composite_retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/tests/test_indices_managed_llama_cloud.py
Labels: lgtm, size:S

#18972 simple wording improvements for Cleanlab tutorial
  docs/docs/examples/evaluation/Cleanlab.ipynb
Labels: lgtm, size:S

#18975 Azure api-key and azure-endpoint resolution fixes
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/llama_index/embeddings/azure_openai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/pyproject.toml
Labels: size:S

#18976 (temp) pin llama-index-readers-file pandas for now
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-file/uv.lock
Labels: size:XS

#18977 Update ChromaVectorStore port field and argument
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/llama_index/vector_stores/chroma/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/pyproject.toml
Labels: lgtm, size:S

#18982 Correcting Redis URL/Client handling
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/llama_index/vector_stores/redis/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/pyproject.toml
Labels: size:XS

#18749 Aperturedb propertygraph
  llama-index-integrations/graph_stores/llama-index-graph-stores-ApertureDB/LICENSE
  llama-index-integrations/graph_stores/llama-index-graph-stores-ApertureDB/Makefile
  llama-index-integrations/graph_stores/llama-index-graph-stores-ApertureDB/README.md
  llama-index-integrations/graph_stores/llama-index-graph-stores-ApertureDB/llama_index/graph_stores/ApertureDB/__init__.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-ApertureDB/llama_index/graph_stores/ApertureDB/property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-ApertureDB/pyproject.toml
  llama-index-integrations/graph_stores/llama-index-graph-stores-ApertureDB/tests/test_pg_stores_ApertureDB.py
Labels: lgtm, size:XL

#18987 llama-index-readers-gcs: Allow newer versions of gcsfs
  llama-index-integrations/readers/llama-index-readers-gcs/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-gcs/uv.lock
Labels: lgtm, size:XS

#18991 docs: update resources docs
  docs/docs/module_guides/workflow/index.md
  docs/docs/understanding/workflows/resources.md
Labels: lgtm, size:M

#18967 ElevenLabs integration
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/.gitignore
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/LICENSE
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/Makefile
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/README.md
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/llama_index/voice_agents/elevenlabs/__init__.py
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/llama_index/voice_agents/elevenlabs/base.py
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/llama_index/voice_agents/elevenlabs/utils.py
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/pyproject.toml
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/tests/__init__.py
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/tests/test_utils.py
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/uv.lock
Labels: lgtm, size:XL

#18994 Update custom_multi_turn_memory.ipynb
  docs/docs/examples/memory/custom_multi_turn_memory.ipynb
Labels: lgtm, size:XS

#19001 actually format the args into a start event instance
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/utils.py
  llama-index-integrations/tools/llama-index-tools-mcp/pyproject.toml
Labels: size:XS

#19000 fix: async functions in tool specs
  llama-index-core/llama_index/core/tools/tool_spec/base.py
  llama-index-core/llama_index/core/vector_stores/types.py
  llama-index-core/tests/readers/file/test_base.py
  llama-index-core/tests/tools/tool_spec/test_base.py
  llama-index-integrations/tools/llama-index-tools-playwright/README.md
  llama-index-packs/llama-index-packs-raptor/pyproject.toml
Labels: size:M

#19002 v0.12.41
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/packs/searchain.md
  docs/docs/api_reference/storage/graph_stores/ApertureDB.md
  docs/docs/api_reference/voice_agents/elevenlabs.md
  docs/mkdocs.yml
  docs/scripts/prepare_for_build.py
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/llama_index/embeddings/azure_openai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-azure-openai/llama_index/llms/azure_openai/base.py
  llama-index-integrations/llms/llama-index-llms-azure-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/pyproject.toml
  pyproject.toml
  uv.lock
Labels: size:L

#19012 feat: Extract instrumentation from core into a standalone package
  llama-dev/llama_dev/utils.py
  llama-dev/tests/test_utils.py
  llama-index-instrumentation/.gitignore
  llama-index-instrumentation/README.md
  llama-index-instrumentation/pyproject.toml
  llama-index-instrumentation/src/llama_index_instrumentation/__init__.py
  llama-index-instrumentation/src/llama_index_instrumentation/base/__init__.py
  llama-index-instrumentation/src/llama_index_instrumentation/base/event.py
  llama-index-instrumentation/src/llama_index_instrumentation/base/handler.py
  llama-index-instrumentation/src/llama_index_instrumentation/dispatcher.py
  llama-index-instrumentation/src/llama_index_instrumentation/event_handlers/__init__.py
  llama-index-instrumentation/src/llama_index_instrumentation/event_handlers/base.py
  llama-index-instrumentation/src/llama_index_instrumentation/event_handlers/null.py
  llama-index-instrumentation/src/llama_index_instrumentation/events/__init__.py
  llama-index-instrumentation/src/llama_index_instrumentation/events/span.py
  llama-index-instrumentation/src/llama_index_instrumentation/span/__init__.py
  llama-index-instrumentation/src/llama_index_instrumentation/span/base.py
  llama-index-instrumentation/src/llama_index_instrumentation/span/simple.py
  llama-index-instrumentation/src/llama_index_instrumentation/span_handlers/__init__.py
  llama-index-instrumentation/src/llama_index_instrumentation/span_handlers/base.py
  llama-index-instrumentation/src/llama_index_instrumentation/span_handlers/null.py
  llama-index-instrumentation/src/llama_index_instrumentation/span_handlers/simple.py
  llama-index-instrumentation/tests/test_dispatcher.py
  llama-index-instrumentation/tests/test_manager.py
  llama-index-instrumentation/uv.lock
Labels: lgtm, size:XXL

#19014 Corrections + integrating tools for ElevenLabs integration
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/README.md
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/llama_index/voice_agents/elevenlabs/base.py
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/llama_index/voice_agents/elevenlabs/utils.py
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/pyproject.toml
  llama-index-integrations/voice_agents/llama-index-voice-agents-elevenlabs/uv.lock
Labels: lgtm, size:M

#19027 feat: Add label truncation to workflow visualization (#18741)
  docs/docs/understanding/workflows/basic_flow.md
  llama-index-utils/llama-index-utils-workflow/README.md
  llama-index-utils/llama-index-utils-workflow/llama_index/utils/workflow/draw.py
  llama-index-utils/llama-index-utils-workflow/tests/test_drawing.py
Labels: lgtm, size:L

#19018 feat: Add ability to exclude source fields from query response
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/tests/docker-compose.yml
  llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/tests/test_opensearch_client.py
Labels: lgtm, size:L

#19016 feat: Prefer 'BedrockRerank' over 'AWSBedrockRerank'
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/llama_index/postprocessor/bedrock_rerank/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-bedrock-rerank/tests/test_postprocessor_bedrock_rerank.py
Labels: lgtm, size:S

#19017 figure retrieval SDK integration
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/api_utils.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/composite_retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/tests/data/image_figure_slides.pdf
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/tests/test_indices_managed_llama_cloud.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/uv.lock
Labels: lgtm, size:L

#19034 fix workflow learn more link
  docs/docs/getting_started/concepts.md
Labels: size:XS

#19032 use async memory operations within async functions
  llama-index-core/llama_index/core/agent/legacy/react/base.py
  llama-index-core/llama_index/core/agent/runner/base.py
  llama-index-core/llama_index/core/agent/runner/parallel.py
  llama-index-core/llama_index/core/chat_engine/condense_plus_context.py
  llama-index-core/llama_index/core/chat_engine/condense_question.py
  llama-index-core/llama_index/core/chat_engine/context.py
  llama-index-core/llama_index/core/chat_engine/simple.py
  llama-index-core/llama_index/core/memory/chat_memory_buffer.py
  llama-index-integrations/agent/llama-index-agent-lats/llama_index/agent/lats/step.py
  llama-index-integrations/agent/llama-index-agent-lats/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-openai-legacy/llama_index/agent/openai_legacy/openai_agent.py
  llama-index-integrations/agent/llama-index-agent-openai-legacy/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/step.py
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-openai/tests/test_openai_agent.py
Labels: size:M

#19048 Add reasoning support to mistralai LLM + magistral
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/base.py
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/utils.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-mistralai/tests/test_llms_mistral.py
Labels: size:L

#19049 Example order completion agent with the new artifact editot tool
  docs/docs/examples/tools/order_completion_agent_with_artifact_editor.ipynb
Labels: lgtm, size:L

#19053 Return empty list when argument raw_figure_nodes is None type in page_figure_nodes_to_node_with_score
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/api_utils.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/base.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/uv.lock
Labels: size:M

#18997 LlamaIndex multi_modal_integration: openai_like
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai-like/.gitignore
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai-like/LICENSE
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai-like/Makefile
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai-like/README.md
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai-like/llama_index/multi_modal_llms/openai_like/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai-like/llama_index/multi_modal_llms/openai_like/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai-like/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai-like/tests/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai-like/tests/test_multi_modal_llms_openai_like.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai-like/uv.lock
Labels: lgtm, size:XL

#19056 v0.12.42
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/multi_modal_llms/openai_like.md
  docs/docs/api_reference/tools/artifact_editor.md
  docs/mkdocs.yml
  docs/scripts/prepare_for_build.py
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-core/tests/objects/storage/object_node_mapping.pickle
  llama-index-core/uv.lock
  llama-index-utils/llama-index-utils-workflow/pyproject.toml
  pyproject.toml
  uv.lock
Labels: size:L

#19059 fix: update modelscope dependencies
  llama-index-integrations/embeddings/llama-index-embeddings-modelscope/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-modelscope/uv.lock
Labels: size:XS

#19068 fix raptor tests?
  llama-index-packs/llama-index-packs-raptor/tests/test_packs_raptor.py
  llama-index-packs/llama-index-packs-raptor/uv.lock
Labels: size:XS

#19069 Logan/fix some tests again
  llama-index-integrations/readers/llama-index-readers-file/tests/test_file.py
  llama-index-packs/llama-index-packs-raptor/pyproject.toml
  llama-index-packs/llama-index-packs-raptor/uv.lock
Labels: size:S

#19062 chore: move instrumentation code out to its own package
  llama-index-core/llama_index/core/instrumentation/__init__.py
  llama-index-core/llama_index/core/instrumentation/base_handler.py
  llama-index-core/llama_index/core/instrumentation/dispatcher.py
  llama-index-core/llama_index/core/instrumentation/event_handlers/__init__.py
  llama-index-core/llama_index/core/instrumentation/event_handlers/base.py
  llama-index-core/llama_index/core/instrumentation/event_handlers/null.py
  llama-index-core/llama_index/core/instrumentation/events/base.py
  llama-index-core/llama_index/core/instrumentation/events/span.py
  llama-index-core/llama_index/core/instrumentation/span/__init__.py
  llama-index-core/llama_index/core/instrumentation/span/base.py
  llama-index-core/llama_index/core/instrumentation/span/simple.py
  llama-index-core/llama_index/core/instrumentation/span_handlers/__init__.py
  llama-index-core/llama_index/core/instrumentation/span_handlers/base.py
  llama-index-core/llama_index/core/instrumentation/span_handlers/null.py
  llama-index-core/llama_index/core/instrumentation/span_handlers/simple.py
  llama-index-core/pyproject.toml
  llama-index-core/tests/instrumentation/test_dispatcher.py
  llama-index-core/tests/instrumentation/test_manager.py
  llama-index-core/uv.lock
Labels: lgtm, size:XXL

#19084 improve empty tool call handling in bedrock converse
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/tests/test_llms_bedrock_converse.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/uv.lock
Labels: size:M

#19094 fix openai responses some more
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_responses.py
Labels: size:S

#19090 Fix Typo in Environment Variable Name in README
  llama-index-networks/examples/privacy_safe_retrieval/README.md
Labels: lgtm, size:XS

#19083 feat: draw mermaid diagram
  llama-index-utils/llama-index-utils-workflow/llama_index/utils/workflow/__init__.py
  llama-index-utils/llama-index-utils-workflow/llama_index/utils/workflow/draw.py
  llama-index-utils/llama-index-utils-workflow/pyproject.toml
  llama-index-utils/llama-index-utils-workflow/tests/test_drawing.py
Labels: lgtm, size:XL

#19022 Perf/improve robustness of perplexity llm integration
  llama-index-integrations/llms/llama-index-llms-perplexity/llama_index/llms/perplexity/base.py
  llama-index-integrations/llms/llama-index-llms-perplexity/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-perplexity/tests/test_perplexity.py
Labels: lgtm, size:XL

#19102 some small updates
  llama-index-integrations/protocols/llama-index-protocols-ag-ui/llama_index/protocols/ag_ui/__init__.py
  llama-index-integrations/protocols/llama-index-protocols-ag-ui/llama_index/protocols/ag_ui/agent.py
  llama-index-integrations/protocols/llama-index-protocols-ag-ui/llama_index/protocols/ag_ui/router.py
  llama-index-integrations/protocols/llama-index-protocols-ag-ui/llama_index/protocols/ag_ui/utils.py
  llama-index-integrations/protocols/llama-index-protocols-ag-ui/pyproject.toml
Labels: size:M

#19104 vbump ag-ui
  llama-index-integrations/protocols/llama-index-protocols-ag-ui/pyproject.toml
Labels: size:XS

#19043 chore: move out Workflows code keeping backward compatibility
  llama-index-core/llama_index/core/agent/workflow/base_agent.py
  llama-index-core/llama_index/core/workflow/__init__.py
  llama-index-core/llama_index/core/workflow/checkpointer.py
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/llama_index/core/workflow/context_serializers.py
  llama-index-core/llama_index/core/workflow/decorators.py
  llama-index-core/llama_index/core/workflow/errors.py
  llama-index-core/llama_index/core/workflow/events.py
  llama-index-core/llama_index/core/workflow/handler.py
  llama-index-core/llama_index/core/workflow/resource.py
  llama-index-core/llama_index/core/workflow/retry_policy.py
  llama-index-core/llama_index/core/workflow/service.py
  llama-index-core/llama_index/core/workflow/types.py
  llama-index-core/llama_index/core/workflow/utils.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/pyproject.toml
  llama-index-core/tests/workflow/__init__.py
  llama-index-core/tests/workflow/conftest.py
  llama-index-core/tests/workflow/test_checkpointer.py
  llama-index-core/tests/workflow/test_context.py
  llama-index-core/tests/workflow/test_decorator.py
  llama-index-core/tests/workflow/test_event.py
  llama-index-core/tests/workflow/test_handler.py
  llama-index-core/tests/workflow/test_resources.py
  llama-index-core/tests/workflow/test_retry_policy.py
  llama-index-core/tests/workflow/test_service.py
  llama-index-core/tests/workflow/test_stepwise.py
  llama-index-core/tests/workflow/test_streaming.py
  llama-index-core/tests/workflow/test_utils.py
  llama-index-core/tests/workflow/test_workflow.py
  llama-index-core/tests/workflow/test_workflow_postponed_annotations.py
  llama-index-core/uv.lock
Labels: size:XXL

#19024 add openGauss integration
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/LICENSE
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/llama_index/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/llama_index/py.typed
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/llama_index/vector_stores/openGauss/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/llama_index/vector_stores/openGauss/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/llama_index/vector_stores/openGauss/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/tests/conftest.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/tests/test_opengauss.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-openGauss/tests/test_vector_stores_opengauss.py
Labels: lgtm, size:XL

#19029 Add Hive Intelligence tool
  llama-index-integrations/tools/llama-index-tools-hive/examples/hive_demo.py
  llama-index-integrations/tools/llama-index-tools-hive/llama_index/tools/hive/__init__.py
  llama-index-integrations/tools/llama-index-tools-hive/llama_index/tools/hive/base.py
  llama-index-integrations/tools/llama-index-tools-hive/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-hive/readme.md
  llama-index-integrations/tools/llama-index-tools-hive/uv.lock
Labels: lgtm, size:L

#19064 fix: create table with pre-defined schema
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/llama_index/vector_stores/lancedb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/tests/test_vector_stores_lancedb.py
Labels: size:L

#19118 Fix error getting metadata file IDs in google drive reader
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/drive/base.py
  llama-index-integrations/readers/llama-index-readers-google/pyproject.toml
Labels: size:XS

#19117 add python notebook for fig retrieval
  docs/docs/examples/data/figures/image_figure_slides.pdf
  docs/docs/examples/llama_cloud/figure_retrieval.ipynb
Labels: size:L

#19130 Fix ollama tests
  llama-index-integrations/llms/llama-index-llms-ollama/tests/test_llms_ollama.py
  llama-index-integrations/llms/llama-index-llms-ollama/uv.lock
Labels: size:M

#19113 [DOCS] Added Agenta Observability Integration
  docs/docs/_static/integrations/agenta.png
  docs/docs/module_guides/observability/index.md
Labels: lgtm, size:M

#19131 Making the progress bar of title extractor unified
  llama-index-core/llama_index/core/extractors/metadata_extractors.py
Labels: lgtm, size:S

#19133 Add Klavis integration notebook
  docs/docs/examples/tools/Use_Klavis_with_LlamaIndex.ipynb
  docs/mkdocs.yml
Labels: lgtm, size:L

#19134 v0.12.43
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/storage/vector_store/openGauss.md
  docs/docs/api_reference/tools/hive.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-core/uv.lock
  llama-index-integrations/tools/llama-index-tools-hive/pyproject.toml
  pyproject.toml
  uv.lock
Labels: size:L

#19137 fix coa agent
  llama-index-integrations/agent/llama-index-agent-coa/README.md
  llama-index-integrations/agent/llama-index-agent-coa/llama_index/agent/coa/output_parser.py
  llama-index-integrations/agent/llama-index-agent-coa/llama_index/agent/coa/prompts.py
  llama-index-integrations/agent/llama-index-agent-coa/pyproject.toml
  llama-index-packs/llama-index-packs-agents-coa/llama_index/packs/agents_coa/output_parser.py
  llama-index-packs/llama-index-packs-agents-coa/llama_index/packs/agents_coa/prompts.py
  llama-index-packs/llama-index-packs-agents-coa/pyproject.toml
Labels: size:M

#19143 Fix typo: Correct "prediciton" to "prediction" in docstrings
  llama-index-core/llama_index/core/llama_dataset/base.py
Labels: lgtm, size:XS

#19142 Remove breakpoints from CoA code
  llama-index-integrations/agent/llama-index-agent-coa/llama_index/agent/coa/output_parser.py
  llama-index-integrations/agent/llama-index-agent-coa/pyproject.toml
  llama-index-packs/llama-index-packs-agents-coa/llama_index/packs/agents_coa/output_parser.py
  llama-index-packs/llama-index-packs-agents-coa/pyproject.toml
Labels: lgtm, size:M

#19101 Adding visualization functions for single/multi agent workflows
  llama-index-utils/llama-index-utils-workflow/llama_index/utils/workflow/draw.py
  llama-index-utils/llama-index-utils-workflow/pyproject.toml
Labels: lgtm, size:XXL

#19163 support pinecone v7
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/llama_index/vector_stores/pinecone/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/llama_index/vector_stores/pinecone/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/tests/test_vector_stores_pinecone.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/uv.lock
Labels: size:L

#19176 quick update doc with upgraded SDK
  docs/docs/examples/tools/Use_Klavis_with_LlamaIndex.ipynb
Labels: lgtm, size:S

#19174 Fix: Minor typo fixes in documentation
  llama-index-integrations/memory/llama-index-memory-mem0/README.md
  llama-index-integrations/readers/llama-index-readers-microsoft-onedrive/README.md
Labels: lgtm, size:XS

#19150 Exclude raw field in AgentStream event to fix potential serialization issue
  llama-index-core/llama_index/core/agent/workflow/workflow_events.py
Labels: lgtm, size:XS

#19186 build: support python version >=3.9,<4.0 for llama-index-vector-stores-pinecone
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/pyproject.toml
Labels: lgtm, size:XS

#19139 Fix image url handling in Mistral AI
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/base.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-mistralai/tests/test_llms_mistral.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/pyproject.toml
Labels: size:M

#19147 Add Batch Support for FastEmbed
  llama-index-integrations/embeddings/llama-index-embeddings-fastembed/llama_index/embeddings/fastembed/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-fastembed/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-fastembed/tests/test_embeddings_fastembed.py
  llama-index-integrations/embeddings/llama-index-embeddings-fastembed/uv.lock
Labels: lgtm, size:L

#19179 Remove old CONTRIBUTING.md
  llama-index-core/CONTRIBUTING.md
Labels: lgtm, size:L

#19196 Setting up System instruction properly for google genai client
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-google-genai/tests/test_llms_google_genai.py
Labels: lgtm, size:M

#19202 Adding opentelemetry integration docs
  docs/docs/module_guides/observability/index.md
Labels: lgtm, size:M

#19192 Fixed string striping
  llama-index-core/llama_index/core/agent/react/step.py
Labels: lgtm, size:XS

#19190 Fix ReActOutputParser when no "Thought:" prefix is produced by the LLM
  llama-index-core/llama_index/core/agent/react/output_parser.py
  llama-index-core/tests/agent/react/test_react_output_parser.py
Labels: lgtm, size:S

#19158 fix react system header formatting in workflow agent
  llama-index-core/llama_index/core/agent/workflow/react_agent.py
Labels: size:S

#19209 Fix a minor issue in class SimpleDirectoryReader comment string
  llama-index-core/llama_index/core/readers/file/base.py
Labels: size:XS

#19205 Mark older agent architectures in core as deprecated
  docs/docs/examples/agent/react_agent.ipynb
  docs/docs/module_guides/deploying/agents/index.md
  docs/docs/understanding/agent/index.md
  llama-index-core/llama_index/core/agent/function_calling/base.py
  llama-index-core/llama_index/core/agent/legacy/react/base.py
  llama-index-core/llama_index/core/agent/react/base.py
  llama-index-core/llama_index/core/agent/runner/base.py
  llama-index-core/llama_index/core/agent/runner/parallel.py
  llama-index-core/llama_index/core/agent/runner/planner.py
  pyproject.toml
Labels: size:M

#19207 Add async batching for huggingface
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/llama_index/embeddings/huggingface/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/pyproject.toml
Labels: lgtm, size:XS

#19219 Updating docs for Azure Cosmos DB
  docs/docs/community/integrations/vector_stores.md
  docs/docs/module_guides/storing/vector_stores.md
Labels: lgtm, size:L

#19193 Adding a cache control block
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/llama_index/core/extractors/document_context.py
  llama-index-core/llama_index/core/llms/__init__.py
  llama-index-core/llama_index/core/memory/memory.py
  llama-index-core/tests/base/llms/test_types.py
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/tests/test_llms_anthropic.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/tests/test_bedrock_converse_utils.py
Labels: lgtm, size:L

#19217 Auto-detect PPLX_API_KEY (#19213)
  llama-index-integrations/llms/llama-index-llms-perplexity/llama_index/llms/perplexity/base.py
  llama-index-integrations/llms/llama-index-llms-perplexity/pyproject.toml
Labels: lgtm, size:XS

#19225 remove redundant text for function parameter descriptions
  llama-index-core/llama_index/core/readers/file/base.py
Labels: lgtm, size:M

#19230 Correct failing test for OpenAi VoiceAgent
  llama-index-integrations/voice_agents/llama-index-voice-agents-openai/tests/test_serialization.py
Labels: size:XS

#19233 Adding new Claude models available on Bedrock
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: size:XS

#19238 change package name beautifulsoup4 to bs4 so tests could pass
  llama-index-core/tests/node_parser/test_html.py
Labels: lgtm, size:S

#19237 feat: Update aioboto3 dependency
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/uv.lock
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/uv.lock
Labels: lgtm, size:XS

#19241 Fix pg vector store sparse query
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: lgtm, size:S

#19246 Fix for google search tool
  llama-index-integrations/tools/llama-index-tools-google/llama_index/tools/google/search/base.py
  llama-index-integrations/tools/llama-index-tools-google/pyproject.toml
Labels: lgtm, size:S

#19244 Adding docs on updated prompt caching strategy in Anthtropic
  docs/docs/examples/llm/anthropic_prompt_caching.ipynb
Labels: lgtm, size:M

#19248 fix: Sync uv.lock for llama-index-core 0.12.44
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/uv.lock
Labels: size:XS

#19250 Add proper async google search to tool spec
  llama-index-integrations/tools/llama-index-tools-google/llama_index/tools/google/search/base.py
  llama-index-integrations/tools/llama-index-tools-google/pyproject.toml
Labels: size:M

#19258 edit: llamacloud docs
  docs/docs/index.md
  docs/mkdocs.yml
Labels: size:S

#19249 deprecate older agent packages
  llama-index-integrations/agent/llama-index-agent-coa/llama_index/agent/coa/step.py
  llama-index-integrations/agent/llama-index-agent-coa/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-dashscope/llama_index/agent/dashscope/base.py
  llama-index-integrations/agent/llama-index-agent-dashscope/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-introspective/llama_index/agent/introspective/step.py
  llama-index-integrations/agent/llama-index-agent-introspective/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-lats/llama_index/agent/lats/step.py
  llama-index-integrations/agent/llama-index-agent-lats/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-llm-compiler/llama_index/agent/llm_compiler/step.py
  llama-index-integrations/agent/llama-index-agent-openai-legacy/llama_index/agent/openai_legacy/context_retriever_agent.py
  llama-index-integrations/agent/llama-index-agent-openai-legacy/llama_index/agent/openai_legacy/openai_agent.py
  llama-index-integrations/agent/llama-index-agent-openai-legacy/llama_index/agent/openai_legacy/retriever_openai_agent.py
  llama-index-integrations/agent/llama-index-agent-openai-legacy/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/base.py
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/openai_assistant_agent.py
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/step.py
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
Labels: size:L

#19265 allow tools to output content blocks
  docs/docs/api_reference/llms/index.md
  llama-index-core/llama_index/core/agent/react/step.py
  llama-index-core/llama_index/core/agent/workflow/base_agent.py
  llama-index-core/llama_index/core/agent/workflow/codeact_agent.py
  llama-index-core/llama_index/core/agent/workflow/function_agent.py
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/llama_index/core/llms/__init__.py
  llama-index-core/llama_index/core/memory/memory.py
  llama-index-core/llama_index/core/tools/calling.py
  llama-index-core/llama_index/core/tools/function_tool.py
  llama-index-core/llama_index/core/tools/ondemand_loader_tool.py
  llama-index-core/llama_index/core/tools/query_engine.py
  llama-index-core/llama_index/core/tools/retriever_tool.py
  llama-index-core/llama_index/core/tools/types.py
  llama-index-core/tests/tools/test_base.py
Labels: lgtm, size:L

#19242 feat: Add chat UI events and models to core package
  llama-index-core/llama_index/core/chat_ui/__init__.py
  llama-index-core/llama_index/core/chat_ui/events.py
  llama-index-core/llama_index/core/chat_ui/models/__init__.py
  llama-index-core/llama_index/core/chat_ui/models/artifact.py
Labels: lgtm, size:M

#19275 remove references to deprecated Context API
  docs/docs/examples/agent/agent_workflow_basic.ipynb
  docs/docs/examples/agent/agent_workflow_multi.ipynb
  docs/docs/examples/agent/agents_as_tools.ipynb
  docs/docs/examples/agent/custom_multi_agent.ipynb
  docs/docs/examples/agent/from_scratch_code_act_agent.ipynb
  docs/docs/examples/agent/multi_agent_workflow_with_weaviate_queryagent.ipynb
  docs/docs/examples/agent/nvidia_document_research_assistant_for_blog_creation.ipynb
  docs/docs/examples/agent/nvidia_sub_question_query_engine.ipynb
  docs/docs/examples/evaluation/step_back_argilla.ipynb
  docs/docs/examples/workflow/JSONalyze_query_engine.ipynb
  docs/docs/examples/workflow/citation_query_engine.ipynb
  docs/docs/examples/workflow/corrective_rag_pack.ipynb
  docs/docs/examples/workflow/function_calling_agent.ipynb
  docs/docs/examples/workflow/human_in_the_loop_story_crafting.ipynb
  docs/docs/examples/workflow/multi_step_query_engine.ipynb
  docs/docs/examples/workflow/multi_strategy_workflow.ipynb
  docs/docs/examples/workflow/parallel_execution.ipynb
  docs/docs/examples/workflow/planning_workflow.ipynb
  docs/docs/examples/workflow/rag.ipynb
  docs/docs/examples/workflow/react_agent.ipynb
  docs/docs/examples/workflow/reflection.ipynb
  docs/docs/examples/workflow/router_query_engine.ipynb
  docs/docs/examples/workflow/self_discover_workflow.ipynb
  docs/docs/examples/workflow/sub_question_query_engine.ipynb
  docs/docs/examples/workflow/workflows_cookbook.ipynb
  docs/docs/module_guides/deploying/agents/memory.md
  docs/docs/module_guides/workflow/index.md
  docs/docs/understanding/agent/multi_agent.md
  docs/docs/understanding/agent/state.md
  docs/docs/understanding/workflows/state.md
  llama-index-core/llama_index/core/agent/workflow/base_agent.py
  llama-index-core/llama_index/core/agent/workflow/codeact_agent.py
  llama-index-core/llama_index/core/agent/workflow/function_agent.py
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-core/llama_index/core/agent/workflow/react_agent.py
  llama-index-core/tests/agent/workflow/test_code_act_agent.py
Labels: size:XL

#19271 docs: Dragonfly Index Demo notebook added
  docs/docs/examples/vector_stores/DragonflyIndexDemo.ipynb
Labels: size:XL
