Repository run-llama/llama_index, pull requests merged in 2025-01, with the labels that each got.

#17402 Document Research Assistant for Blog Creation update
  docs/docs/examples/agent/nvidia_document_research_assistant_for_blog_creation.ipynb
Labels: lgtm, size:XS

#17406 Fix for llama_index.packs.raptor tree_traversal retrieval
  llama-index-packs/llama-index-packs-raptor/llama_index/packs/raptor/base.py
  llama-index-packs/llama-index-packs-raptor/pyproject.toml
  llama-index-packs/llama-index-packs-raptor/tests/test_packs_raptor.py
Labels: lgtm, size:S

#17405 Add support for gpt-4o-2024-08-06 to multi modal llms
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/llama_index/multi_modal_llms/openai/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/pyproject.toml
Labels: lgtm, size:XS

#17410 NVIDIA Support for v2 Embedding & Reranking NIMs
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_integration.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/base.py
Labels: lgtm, size:M

#17411 feat: support typing.Annotated for adding parameter descriptions
  llama-index-core/llama_index/core/tools/utils.py
  llama-index-core/tests/tools/test_utils.py
Labels: lgtm, size:M

#17412 Fix bug 17398
  llama-index-core/llama_index/core/readers/file/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:XS

#17418 vbump scrapegraph
  llama-index-integrations/tools/llama-index-tools-scrapegraph/pyproject.toml
Labels: size:XS

#17420 nvidia Document Research Assistant for Blog Creation ntbk arch diagram update
  docs/docs/examples/agent/nvidia_document_research_assistant_for_blog_creation.ipynb
Labels: lgtm, size:XS

#17421 updating notebook to automode off
  docs/docs/examples/agent/nvidia_document_research_assistant_for_blog_creation.ipynb
Labels: lgtm, size:XS

#17419 update deps of OpenVINO packages
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface-openvino/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-openvino-rerank/pyproject.toml
Labels: size:XS

#17425 remove asserts from schema llm extractor
  llama-index-core/llama_index/core/indices/property_graph/transformations/schema_llm.py
Labels: size:XS

#17426 v0.12.10
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#17431 remove unnecessary exclude line in pre-commit-config; update docs
  .pre-commit-config.yaml
  docs/docs/community/integrations/vector_stores.md
  docs/docs/module_guides/storing/vector_stores.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift/.gitignore
Labels: lgtm, size:XS

#17432 more exception handling in schema llm extractor
  llama-index-core/llama_index/core/indices/property_graph/transformations/schema_llm.py
Labels: size:XS

#17433 unpin huggingface hub deps
  llama-index-integrations/extractors/llama-index-extractors-entity/pyproject.toml
  llama-index-integrations/extractors/llama-index-extractors-relik/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-gaudi/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-huggingface-api/llama_index/llms/huggingface_api/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface-api/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-huggingface-api/tests/test_huggingface_api.py
  llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-huggingface/tests/test_huggingface.py
  llama-index-integrations/readers/llama-index-readers-huggingface-fs/pyproject.toml
Labels: size:L

#17443 Corrected a mistake in the documentation
  docs/docs/module_guides/indexing/lpg_index_guide.md
Labels: size:XS

#17448 Fix neo4j schema bug
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
Labels: lgtm, size:XS

#17453 adjust openai model temperature to accept values between 0 and 2
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:XS

#17460 bugfix: Fix upstage embedding available model mapping
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/llama_index/embeddings/upstage/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-upstage/tests/unit_tests/test_embeddings_upstage.py
Labels: lgtm, size:S

#17463 multimodal huggingface embeddings
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/llama_index/embeddings/huggingface/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/tests/test_embeddings_huggingface.py
Labels: size:M

#17466 add example notebook; add quickstart link
  docs/docs/community/integrations/vector_stores.md
  docs/docs/module_guides/storing/vector_stores.md
Labels: lgtm, size:XS

#17449 feat: async semantic splitter noder parser
  llama-index-core/llama_index/core/node_parser/text/semantic_splitter.py
Labels: lgtm, size:M

#17375 Async memory management for OpenAIAgentWorker
  llama-index-core/llama_index/core/agent/runner/base.py
  llama-index-core/llama_index/core/base/agent/types.py
  llama-index-core/llama_index/core/chat_engine/types.py
  llama-index-core/llama_index/core/memory/types.py
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/step.py
Labels: lgtm, size:M

#17477 feat: support adding images to ChatMessage through additional_kwargs
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/tests/base/llms/test_types.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/tests/test_multi-modal-llms_gemini_utils.py
Labels: lgtm, size:M

#17429 Fixed issue #17397 by updating the markdown format in MarkdownReader
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/markdown/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:XS

#17481 note on contributing integrations
  CONTRIBUTING.md
  README.md
Labels: size:XS

#17440 bugfix: Duplicated citation nodes
  llama-index-core/llama_index/core/query_engine/citation_query_engine.py
Labels: lgtm, size:XS

#17486 small nit on step decorator in notebook
  docs/docs/examples/workflow/multi_step_query_engine.ipynb
Labels: size:XS

#17485 add test, fix missing method
  llama-index-integrations/vector_stores/llama-index-vector-stores-neptune/llama_index/vector_stores/neptune/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-neptune/pyproject.toml
Labels: size:XS

#17484 update language and embedding model
  docs/docs/examples/agent/nvidia_document_research_assistant_for_blog_creation.ipynb
Labels: lgtm, size:XS

#17482 Cognee integration update
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/README.md
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/graph_rag.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/pyproject.toml
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_add_data.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_get_graph_url.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_graph_rag_cognee.py
Labels: lgtm, size:L

#17483 docs: remove duplicate word
  docs/docs/getting_started/installation.md
Labels: lgtm, size:XS

#17498 docs: reword framework definition
  docs/docs/index.md
Labels: docs, lgtm, size:S

#17491 Resolve issue with documentation in Nvidia multi modal notebook.
  docs/docs/examples/multi_modal/nvidia_multi_modal.ipynb
Labels: lgtm, size:XS

#17490 Add new operator for Qdrant Vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
Labels: lgtm, size:XS

#17488 Fix typos in docs transformations.md and PsychicDemo.ipynb
  docs/docs/examples/data_connectors/PsychicDemo.ipynb
  docs/docs/module_guides/loading/ingestion_pipeline/transformations.md
Labels: lgtm, size:XS

#17473 Tablestore Support ChatStore/KvStore/DocStore/IndexStore.
  docs/docs/api_reference/storage/chat_store/tablestore.md
  docs/docs/api_reference/storage/docstore/tablestore.md
  docs/docs/api_reference/storage/index_store/tablestore.md
  docs/docs/api_reference/storage/kvstore/tablestore.md
  docs/docs/examples/docstore/TablestoreDocstoreDemo.ipynb
  docs/docs/module_guides/storing/chat_stores.md
  docs/docs/module_guides/storing/customization.md
  docs/docs/module_guides/storing/docstores.md
  docs/docs/module_guides/storing/index_stores.md
  docs/docs/module_guides/storing/kv_stores.md
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-tablestore/.gitignore
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-tablestore/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-tablestore/Makefile
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-tablestore/README.md
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-tablestore/llama_index/storage/chat_store/tablestore/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-tablestore/llama_index/storage/chat_store/tablestore/__init__.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-tablestore/llama_index/storage/chat_store/tablestore/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-tablestore/pyproject.toml
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-tablestore/tests/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-tablestore/tests/__init__.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-tablestore/tests/test_chat_store_tablestore_chat_store.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-tablestore/.gitignore
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-tablestore/BUILD
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-tablestore/Makefile
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-tablestore/README.md
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-tablestore/llama_index/storage/docstore/tablestore/BUILD
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-tablestore/llama_index/storage/docstore/tablestore/__init__.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-tablestore/llama_index/storage/docstore/tablestore/base.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-tablestore/pyproject.toml
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-tablestore/tests/BUILD
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-tablestore/tests/__init__.py
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-tablestore/tests/test_storage_docstore_tablestore.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-tablestore/.gitignore
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-tablestore/BUILD
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-tablestore/Makefile
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-tablestore/README.md
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-tablestore/llama_index/storage/index_store/tablestore/BUILD
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-tablestore/llama_index/storage/index_store/tablestore/__init__.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-tablestore/llama_index/storage/index_store/tablestore/base.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-tablestore/pyproject.toml
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-tablestore/tests/BUILD
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-tablestore/tests/__init__.py
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-tablestore/tests/test_storage_index_store_tablestore.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-tablestore/.gitignore
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-tablestore/BUILD
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-tablestore/Makefile
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-tablestore/README.md
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-tablestore/llama_index/storage/kvstore/tablestore/BUILD
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-tablestore/llama_index/storage/kvstore/tablestore/__init__.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-tablestore/llama_index/storage/kvstore/tablestore/base.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-tablestore/pyproject.toml
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-tablestore/tests/BUILD
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-tablestore/tests/__init__.py
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-tablestore/tests/test_storage_kvstore_tablestore.py
Labels: lgtm, size:XXL

#17451 Add Multi Modal Bedrock Integration
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-bedrock/.gitignore
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-bedrock/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-bedrock/Makefile
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-bedrock/README.md
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-bedrock/llama_index/multi_modal_llms/bedrock/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-bedrock/llama_index/multi_modal_llms/bedrock/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-bedrock/llama_index/multi_modal_llms/bedrock/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-bedrock/llama_index/multi_modal_llms/bedrock/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-bedrock/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-bedrock/tests/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-bedrock/tests/__init__.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-bedrock/tests/test_multi_modal_llms_bedrock.py
Labels: lgtm, size:XL

#17510 Cognee integration update + notebook
  docs/docs/examples/graph_rag/llama_index_cognee_integration.ipynb
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/pyproject.toml
Labels: size:XS

#17512 Add a required package in notebook for finetuning embeddings.
  docs/docs/examples/finetuning/embeddings/finetune_embedding.ipynb
Labels: lgtm, size:XS

#17511 handle pandas errors in md to df
  llama-index-core/llama_index/core/node_parser/relational/utils.py
Labels: size:XS

#17509 fix: bug in MediaResource validator
  llama-index-core/llama_index/core/schema.py
  llama-index-core/tests/schema/test_media_resource.py
Labels: lgtm, size:M

#17497 Support MariaDB 11.7 in the MariaDB vector store integration
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/llama_index/vector_stores/mariadb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/tests/docker-compose.yaml
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/tests/test_mariadb.py
Labels: lgtm, size:L

#17524 v0.12.11
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/CONTRIBUTING.md
  docs/docs/api_reference/embeddings/opea.md
  docs/docs/api_reference/llms/opea.md
  docs/docs/api_reference/multi_modal_llms/bedrock.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-slack/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#17501 refact: make GeminiMultiModal a thin wrapper around Gemini
  docs/docs/examples/multi_modal/gemini.ipynb
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/llama_index/core/llms/custom.py
  llama-index-core/llama_index/core/utilities/gemini_utils.py
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/utils.py
  llama-index-integrations/llms/llama-index-llms-gemini/tests/test_llms_gemini.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/llama_index/multi_modal_llms/gemini/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/llama_index/multi_modal_llms/gemini/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/tests/test_multi-modal-llms_gemini.py
Labels: size:XL

#17518 Deepseek-v3 is now supported by fireworks.
  llama-index-integrations/llms/llama-index-llms-fireworks/llama_index/llms/fireworks/utils.py
  llama-index-integrations/llms/llama-index-llms-fireworks/pyproject.toml
Labels: lgtm, size:XS

#17514 feat: add stepfun integrations
  docs/docs/api_reference/llms/stepfun.md
  llama-index-integrations/llms/llama-index-llms-stepfun/.gitignore
  llama-index-integrations/llms/llama-index-llms-stepfun/BUILD
  llama-index-integrations/llms/llama-index-llms-stepfun/Makefile
  llama-index-integrations/llms/llama-index-llms-stepfun/README.md
  llama-index-integrations/llms/llama-index-llms-stepfun/llama_index/llms/stepfun/BUILD
  llama-index-integrations/llms/llama-index-llms-stepfun/llama_index/llms/stepfun/__init__.py
  llama-index-integrations/llms/llama-index-llms-stepfun/llama_index/llms/stepfun/base.py
  llama-index-integrations/llms/llama-index-llms-stepfun/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-stepfun/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-stepfun/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-stepfun/tests/test_llms_stepfun.py
Labels: size:L

#17489 feat: Hyperbrowser Web Reader
  docs/docs/api_reference/readers/web.md
  docs/docs/examples/data_connectors/WebPageDemo.ipynb
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/__init__.py
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/hyperbrowser_web/BUILD
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/hyperbrowser_web/README.md
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/hyperbrowser_web/__init__.py
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/hyperbrowser_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/hyperbrowser_web/requirements.txt
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:L

#17538 fix and update pants/cicd
  llama-index-experimental/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-gemini/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-google/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-mistralai/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-vertex/tests/BUILD
  llama-index-integrations/evaluation/llama-index-evaluation-tonic-validate/tests/BUILD
  llama-index-integrations/extractors/llama-index-extractors-marvin/tests/BUILD
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/BUILD
  llama-index-integrations/indices/llama-index-indices-managed-google/tests/BUILD
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-cohere/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-gemini/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-ibm/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-litellm/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-llama-api/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-mistralai/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-palm/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-siliconflow/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-vertex/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-zhipuai/tests/BUILD
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/tests/BUILD
  llama-index-integrations/node_parser/llama-index-node-parser-docling/tests/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-rankllm-rerank/tests/BUILD
  llama-index-integrations/program/llama-index-program-guidance/tests/BUILD
  llama-index-integrations/question_gen/llama-index-question-gen-guidance/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-docling/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-firebase-realtimedb/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-firestore/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-gcs/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-google/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-lilac/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-pathway/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-sec-filings/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-whatsapp/tests/BUILD
  llama-index-integrations/response_synthesizers/llama-index-response-synthesizers-google/tests/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-pathway/tests/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-vertexai-search/tests/BUILD
  llama-index-integrations/selectors/llama-index-selectors-notdiamond/tests/BUILD
  llama-index-integrations/storage/docstore/llama-index-storage-docstore-firestore/tests/BUILD
  llama-index-integrations/storage/index_store/llama-index-storage-index-store-firestore/tests/BUILD
  llama-index-integrations/storage/kvstore/llama-index-storage-kvstore-firestore/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-google/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-scrapegraph/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-text-to-image/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-deeplake/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-google/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-vertexaivectorsearch/tests/BUILD
  llama-index-packs/llama-index-packs-cohere-citation-chat/tests/BUILD
  llama-index-packs/llama-index-packs-deeplake-deepmemory-retriever/tests/BUILD
  llama-index-packs/llama-index-packs-deeplake-multimodal-retrieval/tests/BUILD
  llama-index-packs/llama-index-packs-gmail-openai-agent/tests/BUILD
  llama-index-packs/llama-index-packs-panel-chatbot/tests/BUILD
  llama-index-packs/llama-index-packs-ragatouille-retriever/tests/BUILD
  llama-index-packs/llama-index-packs-zenguard/tests/BUILD
  pants.toml
Labels: size:M

#17537 fix gigachat llm install
  llama-index-integrations/llms/llama-index-llms-gigachat/README.md
  llama-index-integrations/llms/llama-index-llms-gigachat/llama_index/llms/gigachat/base.py
  llama-index-integrations/llms/llama-index-llms-gigachat/pyproject.toml
Labels: size:XS

#17506 feat: support direct PDF handling for Anthropic
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: lgtm, size:M

#17542 fix: align stepfun llm integration versioning
  llama-index-integrations/llms/llama-index-llms-stepfun/pyproject.toml
Labels: size:XS

#17237 MultiAgentWorkflow
  .github/workflows/core-typecheck.yml
  docs/docs/api_reference/agent/workflow.md
  docs/docs/examples/agent/agent_workflow_basic.ipynb
  docs/docs/examples/agent/agent_workflow_multi.ipynb
  docs/docs/understanding/agent/multi_agents.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/agent/workflow/BUILD
  llama-index-core/llama_index/core/agent/workflow/__init__.py
  llama-index-core/llama_index/core/agent/workflow/base_agent.py
  llama-index-core/llama_index/core/agent/workflow/function_agent.py
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-core/llama_index/core/agent/workflow/react_agent.py
  llama-index-core/llama_index/core/agent/workflow/workflow_events.py
  llama-index-core/llama_index/core/postprocessor/sbert_rerank.py
  llama-index-core/llama_index/core/tools/function_tool.py
  llama-index-core/llama_index/core/tools/types.py
  llama-index-core/llama_index/core/tools/utils.py
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/llama_index/core/workflow/context_serializers.py
  llama-index-core/llama_index/core/workflow/utils.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/pyproject.toml
  llama-index-core/tests/agent/workflow/BUILD
  llama-index-core/tests/agent/workflow/__init__.py
  llama-index-core/tests/agent/workflow/test_multi_agent_workflow.py
  llama-index-core/tests/workflow/test_context.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-kuzu/tests/test_graph_stores_kuzu.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/tests/test_graph_stores_memgraph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/tests/test_graph_stores_nebula.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/tests/test_graph_stores_neo4j.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/tests/test_graph_stores_neptune.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-tidb/tests/test_graph_stores_tidb.py
  llama-index-integrations/readers/llama-index-readers-airbyte-cdk/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-airbyte-cdk/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-airbyte-gong/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-airbyte-gong/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-airbyte-hubspot/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-airbyte-hubspot/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-airbyte-salesforce/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-airbyte-salesforce/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-airbyte-shopify/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-airbyte-shopify/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-airbyte-stripe/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-airbyte-stripe/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-airbyte-typeform/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-airbyte-typeform/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-airbyte-zendesk-support/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-airbyte-zendesk-support/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-bilibili/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-bilibili/tests/test_readers_bilibili.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-oceanbase/tests/BUILD
Labels: size:XXL

#17531 Add longllmlingua2 integration
  llama-index-integrations/postprocessor/llama-index-postprocessor-longllmlingua/.gitignore
  llama-index-integrations/postprocessor/llama-index-postprocessor-longllmlingua/examples/longllmlingua2.ipynb
  llama-index-integrations/postprocessor/llama-index-postprocessor-longllmlingua/llama_index/postprocessor/longllmlingua/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-longllmlingua/pyproject.toml
Labels: size:M

#17547 chore: docs readme
  README.md
Labels: lgtm, size:XS

#17545 API Migration
  docs/docs/examples/managed/vectaraDemo.ipynb
  llama-index-integrations/indices/llama-index-indices-managed-vectara/Changelog.md
  llama-index-integrations/indices/llama-index-indices-managed-vectara/README.md
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/base.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/query.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-vectara/tests/test_indices_managed_vectara.py
  llama-index-integrations/tools/llama-index-tools-vectara-query/README.md
  llama-index-integrations/tools/llama-index-tools-vectara-query/examples/vectara_query.ipynb
  llama-index-integrations/tools/llama-index-tools-vectara-query/llama_index/tools/vectara_query/base.py
  llama-index-integrations/tools/llama-index-tools-vectara-query/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-vectara-query/tests/test_tools_vectara_query.py
  llama-index-packs/llama-index-packs-vectara-rag/README.md
  llama-index-packs/llama-index-packs-vectara-rag/pyproject.toml
Labels: lgtm, size:XXL

#17554 fix typo
  docs/docs/module_guides/loading/documents_and_nodes/usage_documents.md
Labels: lgtm, size:XS

#17558 Fix image-path validation in ImageNode
  llama-index-core/llama_index/core/schema.py
Labels: lgtm, size:XS

#17561 v0.12.12
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ibm/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-gemini/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/llama_index/retrievers/bm25/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#17562 Improves connections for neo4j objects and adds some tests
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/base.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/llama_index/graph_stores/neo4j/neo4j_property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/pyproject.toml
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/tests/test_graph_stores_neo4j.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neo4j/tests/test_pg_stores_neo4j.py
Labels: size:XL

#17367 Contextual Retrieval
  docs/docs/api_reference/extractors/documentcontext.md
  docs/docs/examples/data/paul_graham/paul_graham_essay_ambiguated.txt
  docs/docs/examples/metadata_extraction/DocumentContextExtractor.ipynb
  llama-index-core/llama_index/core/extractors/__init__.py
  llama-index-core/llama_index/core/extractors/document_context.py
  llama-index-core/llama_index/core/schema.py
  llama-index-core/tests/extractors/BUILD
  llama-index-core/tests/extractors/test_document_context_extractor.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/llama_index/embeddings/huggingface/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/pyproject.toml
Labels: lgtm, size:XL

#17563 Use correct colab url for Qdrant_metadata_filter
  docs/docs/examples/vector_stores/Qdrant_metadata_filter.ipynb
Labels: lgtm, size:XS

#17566 get valid string when streaming
  llama-index-integrations/llms/llama-index-llms-langchain/llama_index/llms/langchain/base.py
  llama-index-integrations/llms/llama-index-llms-langchain/pyproject.toml
Labels: size:XS

#17572 fix: update vcrpy in vllm tests
  llama-index-integrations/llms/llama-index-llms-vllm/pyproject.toml
Labels: lgtm, size:XS

#17575 feat: Agentql Web Loader
  docs/docs/examples/data_connectors/WebPageDemo.ipynb
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/__init__.py
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/agentql_web/BUILD
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/agentql_web/README.md
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/agentql_web/__init__.py
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/agentql_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:L

#17536 Add framework integration for composite retrieval
  docs/docs/module_guides/indexing/llama_cloud_index.md
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/__init__.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/api_utils.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/base.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/composite_retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/poetry.lock
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/tests/test_indices_managed_llama_cloud.py
Labels: lgtm, size:XL

#17570 Vector index support for Memgraph's integration
  docs/docs/examples/property_graph/property_graph_memgraph.ipynb
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/llama_index/graph_stores/memgraph/property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/pyproject.toml
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/tests/test_pg_stores_memgraph.py
Labels: lgtm, size:L

#17556 fix: :bug: [#17555] fix openai.BadRequestError: Invalid value for 'content': expected a string, got null.
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_utils.py
Labels: lgtm, size:M

#17591 Fix 2 links in agentworkflow notebook
  docs/docs/examples/agent/agent_workflow_multi.ipynb
Labels: lgtm, size:XS

#17587 build: 🆙 replace `pinecone-client` with `pinecone` package
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/pyproject.toml
Labels: lgtm, size:XS

#17603 support content blocks in chat templates
  llama-index-core/llama_index/core/prompts/base.py
Labels: size:M

#17596 fix reconstructing a tool in AgentWorkflow
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
Labels: lgtm, size:XS

#17604 update function calling models in mistral
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/utils.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
Labels: size:XS

#17541 add linkup tool
  docs/docs/api_reference/tools/linkup_research.md
  llama-index-cli/llama_index/cli/upgrade/mappings.json
  llama-index-core/llama_index/core/command_line/mappings.json
  llama-index-integrations/tools/llama-index-tools-linkup-research/.gitignore
  llama-index-integrations/tools/llama-index-tools-linkup-research/BUILD
  llama-index-integrations/tools/llama-index-tools-linkup-research/CHANGELOG.md
  llama-index-integrations/tools/llama-index-tools-linkup-research/Makefile
  llama-index-integrations/tools/llama-index-tools-linkup-research/README.md
  llama-index-integrations/tools/llama-index-tools-linkup-research/examples/linkup.ipynb
  llama-index-integrations/tools/llama-index-tools-linkup-research/llama_index/tools/linkup_research/BUILD
  llama-index-integrations/tools/llama-index-tools-linkup-research/llama_index/tools/linkup_research/__init__.py
  llama-index-integrations/tools/llama-index-tools-linkup-research/llama_index/tools/linkup_research/base.py
  llama-index-integrations/tools/llama-index-tools-linkup-research/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-linkup-research/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-linkup-research/tests/__init__.py
  llama-index-integrations/tools/llama-index-tools-linkup-research/tests/test_tools_linkup_research.py
Labels: lgtm, size:L

#17521 Made the message role of ReAct observation configurable
  docs/docs/examples/agent/react_agent.ipynb
  llama-index-core/llama_index/core/agent/react/formatter.py
Labels: lgtm, size:M

#17534 Add support for halfvec vector type
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/test_postgres.py
Labels: lgtm, size:L

#17529 fix: correct the input params of "load_data" in NotionPageReader
  llama-index-integrations/tools/llama-index-tools-notion/llama_index/tools/notion/base.py
  llama-index-integrations/tools/llama-index-tools-notion/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-notion/tests/test_tools_notion.py
Labels: lgtm, size:M

#17508 refactor: Refactor markdown_to_tups method to better handle multi-lev…
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/markdown/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-file/tests/test_markdown.py
Labels: lgtm, size:L

#17479 Advanced text to sql sample rows
  llama-index-core/llama_index/core/indices/struct_store/sql_query.py
  llama-index-core/llama_index/core/indices/struct_store/sql_retriever.py
  llama-index-core/tests/indices/struct_store/test_sql_query.py
Labels: lgtm, size:L

#17602 Fixing header_path bug re: markdown level vs. stack depth
  llama-index-core/llama_index/core/node_parser/file/markdown.py
  llama-index-core/tests/node_parser/test_markdown.py
Labels: lgtm, size:M

#17605 v0.12.13
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/examples/agent/agent_workflow_basic.ipynb
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-experimental/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#17607 Improving example code for Anthropic
  llama-index-integrations/llms/llama-index-llms-anthropic/README.md
Labels: lgtm, size:XS

#17613 Fix prompt stacking in bedrock converse
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: lgtm, size:S

#17610 Implement async bedrock embeddings
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/llama_index/embeddings/bedrock/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-bedrock/tests/test_bedrock_async.py
Labels: lgtm, size:L

#17611 Add linkup tool
  docs/docs/api_reference/tools/linkup_research.md
Labels: lgtm, size:XS

#17617 Nebius examples fixed
  docs/docs/examples/embeddings/nebius.ipynb
  docs/docs/examples/llm/nebius.ipynb
  docs/docs/examples/multi_modal/nebius_multi_modal.ipynb
Labels: lgtm, size:L

#17625 DeepSeek official API LLM
  docs/docs/api_reference/llms/deepseek.md
  docs/docs/examples/llm/deepseek.ipynb
  docs/mkdocs.yml
  llama-index-integrations/llms/llama-index-llms-deepseek/.gitignore
  llama-index-integrations/llms/llama-index-llms-deepseek/BUILD
  llama-index-integrations/llms/llama-index-llms-deepseek/Makefile
  llama-index-integrations/llms/llama-index-llms-deepseek/README.md
  llama-index-integrations/llms/llama-index-llms-deepseek/llama_index/llms/deepseek/BUILD
  llama-index-integrations/llms/llama-index-llms-deepseek/llama_index/llms/deepseek/__init__.py
  llama-index-integrations/llms/llama-index-llms-deepseek/llama_index/llms/deepseek/base.py
  llama-index-integrations/llms/llama-index-llms-deepseek/llama_index/llms/deepseek/utils.py
  llama-index-integrations/llms/llama-index-llms-deepseek/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-deepseek/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-deepseek/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-deepseek/tests/test_llms_deepseek.py
Labels: size:XL

#17620 GoogleDriveReader support file extensions
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/drive/base.py
  llama-index-integrations/readers/llama-index-readers-google/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-google/tests/test_readers_google_drive.py
Labels: lgtm, size:M

#17628 notebook nits
  docs/docs/examples/agent/agent_workflow_basic.ipynb
  docs/docs/examples/agent/agent_workflow_multi.ipynb
Labels: size:L

#17631 Fix agentworkflow handoffs
  llama-index-core/llama_index/core/agent/workflow/base_agent.py
  llama-index-core/llama_index/core/agent/workflow/function_agent.py
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-core/llama_index/core/agent/workflow/react_agent.py
Labels: size:M

#17632 v0.12.14
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:M

#17635 .get_nodes now accepts include_values param to return embeddings
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/llama_index/vector_stores/pinecone/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/pyproject.toml
Labels: lgtm, size:S

#17645 fix repeated sources when doing parallel tool calling
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/step.py
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
Labels: lgtm, size:XS

#17644 small typo fix in the default plan refine prompt
  llama-index-core/llama_index/core/agent/runner/planner.py
Labels: lgtm, size:XS

#17647 update llama-cpp integration + docs
  docs/docs/examples/llm/llama_2_llama_cpp.ipynb
  docs/docs/examples/llm/llama_cpp.ipynb
  docs/docs/module_guides/models/llms/modules.md
  docs/mkdocs.yml
  llama-index-integrations/llms/llama-index-llms-llama-cpp/README.md
  llama-index-integrations/llms/llama-index-llms-llama-cpp/pyproject.toml
Labels: size:XXL

#17658 fix bedrock function calling
  llama-index-core/llama_index/core/llms/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: size:M

#17657 Deepseek-r1 is now supported by fireworks
  llama-index-integrations/llms/llama-index-llms-fireworks/llama_index/llms/fireworks/utils.py
  llama-index-integrations/llms/llama-index-llms-fireworks/pyproject.toml
Labels: lgtm, size:XS

#17652 removed a dead link from fine-tuning.md in docs
  docs/docs/optimizing/fine-tuning/fine-tuning.md
Labels: lgtm, size:XS

#17660 [docs] Fix 404 link for Q&A Patterns
  docs/docs/understanding/putting_it_all_together/index.md
Labels: lgtm, size:XS

#17577 Fix: [Bug] NameError: name 'p' is not defined #15581
  llama-index-core/llama_index/core/output_parsers/utils.py
  llama-index-experimental/llama_index/experimental/query_engine/pandas/output_parser.py
Labels: lgtm, size:XS

#17585 Add Snowflake Cortex Integration
  llama-index-integrations/llms/llama-index-llms-cortex/.gitignore
  llama-index-integrations/llms/llama-index-llms-cortex/BUILD
  llama-index-integrations/llms/llama-index-llms-cortex/Makefile
  llama-index-integrations/llms/llama-index-llms-cortex/README.md
  llama-index-integrations/llms/llama-index-llms-cortex/llama_index/llms/cortex/BUILD
  llama-index-integrations/llms/llama-index-llms-cortex/llama_index/llms/cortex/__init__.py
  llama-index-integrations/llms/llama-index-llms-cortex/llama_index/llms/cortex/base.py
  llama-index-integrations/llms/llama-index-llms-cortex/llama_index/llms/cortex/utils.py
  llama-index-integrations/llms/llama-index-llms-cortex/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-cortex/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-cortex/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-cortex/tests/test_integration_cortex.py
  llama-index-integrations/llms/llama-index-llms-cortex/tests/test_llms_cortex.py
  llama-index-integrations/llms/llama-index-llms-cortex/tests/test_utils.py
Labels: lgtm, size:XL

#17598 Add endpoint parameter to TextEmbeddingsInference
  llama-index-integrations/embeddings/llama-index-embeddings-text-embeddings-inference/llama_index/embeddings/text_embeddings_inference/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-text-embeddings-inference/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-text-embeddings-inference/tests/test_embeddings_text_embeddings_inference.py
Labels: lgtm, size:M

#17664 Remove API key and fix colab link in `deepseek.ipynb`
  docs/docs/examples/llm/deepseek.ipynb
Labels: lgtm, size:XS

#17665 [Fix] deps in `llama-index-networks/examples`
  llama-index-networks/examples/demo/contributor-1/poetry.lock
  llama-index-networks/examples/demo/contributor-1/pyproject.toml
  llama-index-networks/examples/demo/contributor-2/poetry.lock
  llama-index-networks/examples/demo/contributor-2/pyproject.toml
  llama-index-networks/examples/demo/contributor-3/poetry.lock
  llama-index-networks/examples/demo/contributor-3/pyproject.toml
  llama-index-networks/examples/privacy_safe_retrieval/contributor-1/poetry.lock
  llama-index-networks/examples/privacy_safe_retrieval/contributor-1/pyproject.toml
  llama-index-networks/examples/privacy_safe_retrieval/contributor-2/poetry.lock
  llama-index-networks/examples/privacy_safe_retrieval/contributor-2/pyproject.toml
  llama-index-networks/poetry.lock
Labels: lgtm, size:M

#17656 feat: allow to exclude empty file simple directory reader
  docs/docs/examples/data_connectors/simple_directory_reader.ipynb
  llama-index-core/llama_index/core/readers/file/base.py
  llama-index-integrations/readers/llama-index-readers-file/tests/test_file.py
Labels: lgtm, size:M

#17676 fix: make ctx._events_buffer json-serializable
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/tests/workflow/test_context.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: lgtm, size:M

#17668 [docs] Fix typo in BM25 Retriever Example
  docs/docs/examples/retrievers/bm25_retriever.ipynb
Labels: lgtm, size:XS

#17679 Get description from pydantic field
  llama-index-core/llama_index/core/tools/utils.py
  llama-index-core/tests/tools/test_utils.py
Labels: lgtm, size:S

#17678 Fixed issue #17671 by adding the required decorators
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
Labels: lgtm, size:XS

#17663 Add `error_on_tool_error` param to `FunctionCallingLLM.predict_and_call`
  CONTRIBUTING.md
  llama-index-core/llama_index/core/llms/function_calling.py
  llama-index-core/tests/llms/test_function_calling.py
Labels: lgtm, size:L

#17683 Feat/fix Azure AI Search Hybrid Semantic Search Unusability due to hardcoded parameter
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/tests/test_azureaisearch.py
Labels: lgtm, size:M

#17686 Fix workflow module guide doc
  docs/docs/module_guides/workflow/index.md
Labels: lgtm, size:XS

#17688 v0.12.15
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/CONTRIBUTING.md
  docs/docs/api_reference/llms/cortex.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#17689 o3 mini support
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/llama_index/multi_modal_llms/openai/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/pyproject.toml
Labels: size:XS

#17690 Fix user_msg vs chat_history AgentWorkflow inputs
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
Labels: size:M
