Repository run-llama/llama_index, pull requests merged in 2025-02, with the labels that each got.

#17692 tweak to deepseek function calling support
  llama-index-integrations/llms/llama-index-llms-deepseek/llama_index/llms/deepseek/base.py
  llama-index-integrations/llms/llama-index-llms-deepseek/llama_index/llms/deepseek/utils.py
  llama-index-integrations/llms/llama-index-llms-deepseek/pyproject.toml
Labels: size:XS

#17691 Fixing broken link
  docs/docs/examples/agent/agent_workflow_multi.ipynb
Labels: lgtm, size:XS

#17694 fix max_tokens, add reasoning_effort for openai reasoning models
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:S

#17698 small async voyageai fix
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/llama_index/embeddings/voyageai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/pyproject.toml
Labels: size:XS

#17703 fix: max_tokens in O1
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:XS

#17701 Be more lenient with leading whitespaces emitted by some models when doing ReAct
  llama-index-core/llama_index/core/agent/react/step.py
Labels: lgtm, size:XS

#17675 Add vLLM offline inference supports for embedding
  llama-index-integrations/embeddings/llama-index-embeddings-vllm/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-vllm/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-vllm/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-vllm/llama_index/embeddings/vllm/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-vllm/llama_index/embeddings/vllm/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-vllm/llama_index/embeddings/vllm/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-vllm/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-vllm/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-vllm/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-vllm/tests/test_embeddings_vllm.py
Labels: lgtm, size:L

#17699 Improved Obsidian Reader
  llama-index-integrations/readers/llama-index-readers-obsidian/README.md
  llama-index-integrations/readers/llama-index-readers-obsidian/llama_index/readers/obsidian/base.py
  llama-index-integrations/readers/llama-index-readers-obsidian/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-obsidian/tests/test_readers_obsidian.py
Labels: lgtm, size:L

#17243 Add OCI Data Science Model Deployment Embedding Integration
  docs/docs/examples/embeddings/oci_data_science.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/llama_index/embeddings/oci_data_science/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/llama_index/embeddings/oci_data_science/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/llama_index/embeddings/oci_data_science/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/llama_index/embeddings/oci_data_science/client.py
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/llama_index/embeddings/oci_data_science/utils.py
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/tests/test_embeddings_oci_data_science.py
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/tests/test_oci_data_science_client.py
Labels: lgtm, size:XXL

#17695 [oci-genai] Option to pass auth_file_location, in-order to overwrite default config file location i.e. ~/.oci/config
  docs/docs/examples/llm/oci_genai.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-oci-genai/llama_index/embeddings/oci_genai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-oci-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-oci-genai/llama_index/llms/oci_genai/base.py
  llama-index-integrations/llms/llama-index-llms-oci-genai/llama_index/llms/oci_genai/utils.py
Labels: lgtm, size:M

#17241 Add OCI Data Science Model Deployment LLM Integration
  docs/docs/examples/llm/oci_data_science.ipynb
  llama-index-integrations/llms/llama-index-llms-oci-data-science/.gitignore
  llama-index-integrations/llms/llama-index-llms-oci-data-science/BUILD
  llama-index-integrations/llms/llama-index-llms-oci-data-science/Makefile
  llama-index-integrations/llms/llama-index-llms-oci-data-science/README.md
  llama-index-integrations/llms/llama-index-llms-oci-data-science/llama_index/llms/oci_data_science/BUILD
  llama-index-integrations/llms/llama-index-llms-oci-data-science/llama_index/llms/oci_data_science/__init__.py
  llama-index-integrations/llms/llama-index-llms-oci-data-science/llama_index/llms/oci_data_science/base.py
  llama-index-integrations/llms/llama-index-llms-oci-data-science/llama_index/llms/oci_data_science/client.py
  llama-index-integrations/llms/llama-index-llms-oci-data-science/llama_index/llms/oci_data_science/utils.py
  llama-index-integrations/llms/llama-index-llms-oci-data-science/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-oci-data-science/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-oci-data-science/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-oci-data-science/tests/test_llms_oci_data_science.py
  llama-index-integrations/llms/llama-index-llms-oci-data-science/tests/test_oci_data_science_client.py
  llama-index-integrations/llms/llama-index-llms-oci-data-science/tests/test_oci_data_science_utils.py
Labels: lgtm, size:XXL

#17720 gemini 2.0 support
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
Labels: size:XS

#17696 feat: support basic function call for gemini (google-generativeai)
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/utils.py
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-gemini/tests/test_llms_gemini.py
Labels: lgtm, size:L

#17709 feat: add new scrapegraph endpoint
  llama-index-integrations/tools/llama-index-tools-scrapegraph/examples/scrapegraph-search-llama-index.py
  llama-index-integrations/tools/llama-index-tools-scrapegraph/llama_index/tools/scrapegraph/base.py
  llama-index-integrations/tools/llama-index-tools-scrapegraph/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-scrapegraph/tests/test_tools_scrapegraph.py
Labels: lgtm, size:M

#17722 v0.12.16
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/oci_data_science.md
  docs/docs/api_reference/embeddings/vllm.md
  docs/docs/api_reference/llms/oci_data_science.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-oci-data-science/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-oci-data-science/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
  llama-index-integrations/llms/llama-index-llms-ollama/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#17724 Fix: [Bug]: SimpleDirectoryReader metadata handles timezones inconsistently #17715
  docs/docs/module_guides/loading/simpledirectoryreader.md
  llama-index-core/llama_index/core/readers/file/base.py
Labels: lgtm, size:M

#17706 feat: playwright browser tool
  llama-index-integrations/tools/llama-index-tools-playwright/.gitignore
  llama-index-integrations/tools/llama-index-tools-playwright/BUILD
  llama-index-integrations/tools/llama-index-tools-playwright/Makefile
  llama-index-integrations/tools/llama-index-tools-playwright/README.md
  llama-index-integrations/tools/llama-index-tools-playwright/examples/BUILD
  llama-index-integrations/tools/llama-index-tools-playwright/examples/web_browsing.py
  llama-index-integrations/tools/llama-index-tools-playwright/llama_index/tools/playwright/BUILD
  llama-index-integrations/tools/llama-index-tools-playwright/llama_index/tools/playwright/__init__.py
  llama-index-integrations/tools/llama-index-tools-playwright/llama_index/tools/playwright/base.py
  llama-index-integrations/tools/llama-index-tools-playwright/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-playwright/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-playwright/tests/__init__.py
  llama-index-integrations/tools/llama-index-tools-playwright/tests/test_tools_playwright.py
Labels: lgtm, size:XL

#17733 fix reasoning_effort in openai-ish apis
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:S

#17737 fix deps for cortex
  llama-index-integrations/llms/llama-index-llms-cortex/pyproject.toml
Labels: size:XS

#17747 fix gemini tool choice
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
Labels: size:L

#17740 feat: Add more social media links
  README.md
Labels: lgtm, size:XS

#17648 revamped getting started
  docs/docs/getting_started/async_python.md
  docs/docs/getting_started/concepts.md
  docs/docs/getting_started/create_llama.md
  docs/docs/getting_started/installation.md
  docs/docs/getting_started/starter_example.md
  docs/docs/getting_started/starter_example_local.md
  docs/docs/module_guides/models/embeddings.md
  docs/docs/module_guides/models/llms.md
Labels: size:XL

#17725 Update react_agent.ipynb
  docs/docs/examples/workflow/react_agent.ipynb
Labels: lgtm, size:XS

#17729 added additional parameters in openai assistant agent
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/openai_assistant_agent.py
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-openai/tests/test_openai_assistant_agent.py
Labels: lgtm, size:S

#17714 Add llama-index-llms-openvino-genai package
  docs/docs/examples/llm/openvino-genai.ipynb
  llama-index-integrations/llms/llama-index-llms-openvino-genai/.gitignore
  llama-index-integrations/llms/llama-index-llms-openvino-genai/BUILD
  llama-index-integrations/llms/llama-index-llms-openvino-genai/Makefile
  llama-index-integrations/llms/llama-index-llms-openvino-genai/README.md
  llama-index-integrations/llms/llama-index-llms-openvino-genai/llama_index/llms/openvino_genai/BUILD
  llama-index-integrations/llms/llama-index-llms-openvino-genai/llama_index/llms/openvino_genai/__init__.py
  llama-index-integrations/llms/llama-index-llms-openvino-genai/llama_index/llms/openvino_genai/base.py
  llama-index-integrations/llms/llama-index-llms-openvino-genai/pyproject.toml
Labels: lgtm, size:XL

#17727 fix: update the upsert_triplet method in neptune integration
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/base.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/pyproject.toml
Labels: lgtm, size:S

#17757 Fix: update documentation to add poetry shell plugin
  docs/docs/CONTRIBUTING.md
  docs/docs/getting_started/installation.md
Labels: lgtm, size:S

#17753 fix(mem0): get crashed when get api_version for memory client
  llama-index-integrations/memory/llama-index-memory-mem0/llama_index/memory/mem0/base.py
  llama-index-integrations/memory/llama-index-memory-mem0/pyproject.toml
Labels: lgtm, size:XS

#17750 missed keyword suffix for delete query
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/pyproject.toml
Labels: lgtm, size:XS

#17754 Avoid async race conditions in aput_messages
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/step.py
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
Labels: lgtm, size:XS

#17643 BM25Retriever: UnicodeError Handling and Encoding Flexibility Improvement
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/llama_index/retrievers/bm25/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/pyproject.toml
Labels: lgtm, size:S

#17759 Ollama Native Multimodal
  docs/docs/examples/llm/ollama.ipynb
  docs/docs/examples/multi_modal/ollama_cookbook.ipynb
  docs/docs/use_cases/multimodal.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/types.py
  llama-index-core/tests/output_parsers/test_pydantic.py
  llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
  llama-index-integrations/llms/llama-index-llms-ollama/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-ollama/llama_index/multi_modal_llms/ollama/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-ollama/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-ollama/tests/test_multi_modal_llms_ollama.py
Labels: size:L

#17764 fix gemini multi-turn tool calling
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/utils.py
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-gemini/tests/test_llms_gemini.py
Labels: size:S

#17762 chore: add tests for latest gemini structured gen
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/utils.py
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-gemini/tests/test_llms_gemini.py
Labels: lgtm, size:L

#17774 fixing a link
  docs/docs/use_cases/agents.md
Labels: lgtm, size:XS

#17763 [Feature] Jira tools integration
  llama-index-integrations/tools/llama-index-tools-jira/BUILD
  llama-index-integrations/tools/llama-index-tools-jira/Makefile
  llama-index-integrations/tools/llama-index-tools-jira/README.md
  llama-index-integrations/tools/llama-index-tools-jira/llama_index/tools/jira/BUILD
  llama-index-integrations/tools/llama-index-tools-jira/llama_index/tools/jira/__init__.py
  llama-index-integrations/tools/llama-index-tools-jira/llama_index/tools/jira/base.py
  llama-index-integrations/tools/llama-index-tools-jira/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-jira/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-jira/tests/__init__.py
  llama-index-integrations/tools/llama-index-tools-jira/tests/test_tools_jira.py
Labels: size:L

#17773 fixed several typos in tool descriptions and names
  llama-index-integrations/tools/llama-index-tools-code-interpreter/llama_index/tools/code_interpreter/base.py
  llama-index-integrations/tools/llama-index-tools-weather/README.md
  llama-index-integrations/tools/llama-index-tools-weather/llama_index/tools/weather/base.py
  llama-index-integrations/tools/llama-index-tools-yelp/llama_index/tools/yelp/base.py
Labels: lgtm, size:S

#17778 Add OpenAI Whisper Reader
  llama-index-integrations/readers/llama-index-readers-whisper/.gitignore
  llama-index-integrations/readers/llama-index-readers-whisper/BUILD
  llama-index-integrations/readers/llama-index-readers-whisper/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-whisper/Makefile
  llama-index-integrations/readers/llama-index-readers-whisper/README.md
  llama-index-integrations/readers/llama-index-readers-whisper/llama_index/readers/whisper/BUILD
  llama-index-integrations/readers/llama-index-readers-whisper/llama_index/readers/whisper/__init__.py
  llama-index-integrations/readers/llama-index-readers-whisper/llama_index/readers/whisper/base.py
  llama-index-integrations/readers/llama-index-readers-whisper/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-whisper/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-whisper/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-whisper/tests/test_readers_whisper.py
Labels: size:L

#17783 Add fs kwarg to flatreader and docling
  llama-index-integrations/readers/llama-index-readers-docling/llama_index/readers/docling/base.py
  llama-index-integrations/readers/llama-index-readers-docling/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-docling/tests/test_readers_docling.py
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/flat/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: size:M

#17770 Update the llama-index-llms-langchain to latest langchain API - removes the deprication warning
  llama-index-integrations/llms/llama-index-llms-langchain/llama_index/llms/langchain/base.py
  llama-index-integrations/llms/llama-index-llms-langchain/pyproject.toml
Labels: lgtm, size:XS

#17782 Adding dependencies that are causing import errors
  docs/docs/examples/finetuning/embeddings/finetune_embedding.ipynb
Labels: lgtm, size:XS

#17767 feat: Make start and stop events user-configurable in Workflows
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/llama_index/core/workflow/errors.py
  llama-index-core/llama_index/core/workflow/events.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/conftest.py
  llama-index-core/tests/workflow/test_streaming.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: lgtm, size:L

#17769 Cognee integration version update
  docs/docs/examples/graph_rag/llama_index_cognee_integration.ipynb
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/graph_rag.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/pyproject.toml
Labels: lgtm, size:S

#17771 Add retry logic to siliconflow llm and embeddings
  llama-index-integrations/embeddings/llama-index-embeddings-siliconflow/llama_index/embeddings/siliconflow/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-siliconflow/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-siliconflow/llama_index/llms/siliconflow/base.py
  llama-index-integrations/llms/llama-index-llms-siliconflow/pyproject.toml
Labels: lgtm, size:L

#17789 docs link nit
  docs/docs/understanding/putting_it_all_together/index.md
Labels: size:XS

#17780 add audio support to openai
  docs/docs/examples/llm/openai.ipynb
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/llama_index/core/extractors/document_context.py
  llama-index-core/llama_index/core/llms/__init__.py
  llama-index-core/llama_index/core/utils.py
  llama-index-core/tests/base/llms/test_types.py
  llama-index-integrations/llms/llama-index-llms-gemini/tests/test_llms_gemini.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_utils.py
Labels: lgtm, size:L

#17792 adding OpenAI API key to environment
  docs/docs/examples/agent/agent_builder.ipynb
  docs/docs/examples/agent/openai_agent_context_retrieval.ipynb
  docs/docs/examples/agent/openai_agent_lengthy_tools.ipynb
  docs/docs/examples/agent/openai_agent_query_plan.ipynb
Labels: lgtm, size:M

#17793 v0.12.17
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/CONTRIBUTING.md
  docs/docs/api_reference/llms/openvino_genai.md
  docs/docs/api_reference/readers/whisper.md
  docs/docs/api_reference/retrievers/kendra.md
  docs/docs/api_reference/tools/jira.md
  docs/docs/api_reference/tools/playwright.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/node_parser/file/html.py
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/poetry.lock
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-networks/examples/demo/contributor-1/poetry.lock
  llama-index-networks/examples/demo/contributor-2/poetry.lock
  llama-index-networks/examples/demo/contributor-3/poetry.lock
  llama-index-networks/examples/privacy_safe_retrieval/contributor-1/poetry.lock
  llama-index-networks/examples/privacy_safe_retrieval/contributor-2/poetry.lock
  llama-index-networks/poetry.lock
  poetry.lock
  pyproject.toml
Labels: size:L

#17790 Add Google AlloyDB integration documentation
  docs/docs/community/integrations/vector_stores.md
  docs/docs/examples/chat_store/AlloyDBChatStoreDemo.ipynb
  docs/docs/examples/data_connectors/AlloyDBReaderDemo.ipynb
  docs/docs/examples/docstore/AlloyDBDocstoreDemo.ipynb
  docs/docs/examples/vector_stores/AlloyDBVectorStoreDemo.ipynb
  docs/docs/module_guides/loading/connector/modules.md
  docs/docs/module_guides/storing/chat_stores.md
  docs/docs/module_guides/storing/docstores.md
  docs/docs/module_guides/storing/index_stores.md
  docs/docs/module_guides/storing/vector_stores.md
Labels: lgtm, size:XXL

#17811 Expand AzureAISearchVectorStore filter options
  docs/docs/examples/vector_stores/AzureAISearchIndexDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
Labels: size:M

#17806 Update GoogleDriveDemo.ipynb colab link
  docs/docs/examples/data_connectors/GoogleDriveDemo.ipynb
Labels: lgtm, size:XS

#17808 Fix: Change Playwright browser tool from sync to async
  llama-index-integrations/tools/llama-index-tools-playwright/README.md
  llama-index-integrations/tools/llama-index-tools-playwright/examples/BUILD
  llama-index-integrations/tools/llama-index-tools-playwright/examples/playwright_browser_agent.ipynb
  llama-index-integrations/tools/llama-index-tools-playwright/examples/web_browsing.py
  llama-index-integrations/tools/llama-index-tools-playwright/llama_index/tools/playwright/base.py
  llama-index-integrations/tools/llama-index-tools-playwright/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-playwright/tests/test_tools_playwright.py
Labels: lgtm, size:XL

#17791 MariaDB Vector Store Integration: Add tuning parameters and utility functions
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/llama_index/vector_stores/mariadb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-mariadb/tests/test_mariadb.py
Labels: lgtm, size:L

#17795 feat: add mcp tool spec
  llama-index-integrations/tools/llama-index-tools-mcp/.gitignore
  llama-index-integrations/tools/llama-index-tools-mcp/BUILD
  llama-index-integrations/tools/llama-index-tools-mcp/CHANGELOG.md
  llama-index-integrations/tools/llama-index-tools-mcp/Makefile
  llama-index-integrations/tools/llama-index-tools-mcp/README.md
  llama-index-integrations/tools/llama-index-tools-mcp/examples/.env.example
  llama-index-integrations/tools/llama-index-tools-mcp/examples/BUILD
  llama-index-integrations/tools/llama-index-tools-mcp/examples/mcp.ipynb
  llama-index-integrations/tools/llama-index-tools-mcp/examples/mcp_server.py
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/BUILD
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/__init__.py
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/base.py
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/client.py
  llama-index-integrations/tools/llama-index-tools-mcp/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-mcp/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-mcp/tests/__init__.py
  llama-index-integrations/tools/llama-index-tools-mcp/tests/test_tools_mcp.py
Labels: lgtm, size:XL

#17803 Added the AIMon Evaluation notebook in the evaluation examples.
  docs/docs/examples/evaluation/AIMon.ipynb
Labels: lgtm, size:XL

#17807 azure ai search: add default to `None` for semantic configuration name
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/tests/test_azureaisearch.py
Labels: size:M

#17813 Add Google Cloud SQL for PostgreSQL integration documentation
  docs/docs/community/integrations/vector_stores.md
  docs/docs/examples/chat_store/CloudSQLPgChatStoreDemo.ipynb
  docs/docs/examples/data_connectors/CloudSQLPgReaderDemo.ipynb
  docs/docs/examples/docstore/CloudSQLPgDocstoreDemo.ipynb
  docs/docs/examples/vector_stores/CloudSQLPgVectorStoreDemo.ipynb
  docs/docs/module_guides/loading/connector/modules.md
  docs/docs/module_guides/storing/chat_stores.md
  docs/docs/module_guides/storing/docstores.md
  docs/docs/module_guides/storing/index_stores.md
  docs/docs/module_guides/storing/vector_stores.md
Labels: lgtm, size:XXL

#17812 Keep a reference to asyncio tasks in astream_chat()
  llama-index-core/llama_index/core/agent/legacy/react/base.py
  llama-index-core/llama_index/core/agent/react/step.py
  llama-index-core/llama_index/core/chat_engine/condense_question.py
  llama-index-core/llama_index/core/chat_engine/simple.py
  llama-index-core/llama_index/core/chat_engine/types.py
  llama-index-core/tests/chat_engine/test_simple.py
  llama-index-integrations/agent/llama-index-agent-openai-legacy/llama_index/agent/openai_legacy/openai_agent.py
  llama-index-integrations/agent/llama-index-agent-openai/llama_index/agent/openai/step.py
Labels: lgtm, size:L

#17814 Add textnode metadata
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/llama_index/indices/managed/vertexai/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-vertexai/tests/test_indices_managed_vertexai.py
Labels: lgtm, size:S

#17816 Silence nltk downloader
  llama-index-core/llama_index/core/utils.py
Labels: lgtm, size:XS

#17672 (feat) NVIDIA connectors update
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/utils.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/conftest.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_base_url.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_embeddings_nvidia.py
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/base.py
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/utils.py
  llama-index-integrations/llms/llama-index-llms-nvidia/poetry.lock
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/conftest.py
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_api_key.py
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_base_url.py
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_mode_switch.py
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_nvidia.py
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_structured_output.py
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_text-completion.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/utils.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_base_url.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_postprocessor_nvidia_rerank.py
Labels: lgtm, size:XXL

#17818 feat: :sparkles: add support to anthropic `claude-3-5-haiku-latest` model name
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: lgtm, size:XS

#17827 Improve error logs for llamacloud indices
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/base.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
Labels: lgtm, size:S

#17824 Feat: add new gemini models
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
Labels: lgtm, size:XS

#17823 include file & page metadata when returning image node from llamacloud retriever
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/api_utils.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
Labels: lgtm, size:S

#17828 Fix: Broken Nebius Colab Link & Update LLM Integration Docs
  docs/docs/examples/llm/nebius.ipynb
  docs/docs/module_guides/models/llms/modules.md
Labels: lgtm, size:XS

#17612 `azureaisearch`: prefer using hybrid_top_k over similarity_top_k for hybrid search
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
Labels: lgtm, size:XS

#17829 feat: add Microsoft Outlook Email Reader integration with tests and r…
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/.gitignore
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/BUILD
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/Makefile
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/README.md
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/llama_index/readers/outlook_emails/BUILD
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/llama_index/readers/outlook_emails/__init__.py
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/llama_index/readers/outlook_emails/base.py
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/tests/test_readers_microsoft_outlook_mails.py
Labels: lgtm, size:L

#17817 Retain return type from @dispatcher.span
  llama-index-core/llama_index/core/chat_engine/condense_plus_context.py
  llama-index-core/llama_index/core/evaluation/retrieval/evaluator.py
  llama-index-core/llama_index/core/extractors/metadata_extractors.py
  llama-index-core/llama_index/core/indices/common_tree/base.py
  llama-index-core/llama_index/core/instrumentation/dispatcher.py
  llama-index-core/llama_index/core/llms/llm.py
  llama-index-core/llama_index/core/output_parsers/pydantic.py
  llama-index-core/llama_index/core/program/function_program.py
  llama-index-core/llama_index/core/program/llm_program.py
  llama-index-core/llama_index/core/program/utils.py
  llama-index-core/llama_index/core/query_engine/retry_source_query_engine.py
  llama-index-core/llama_index/core/query_engine/sql_join_query_engine.py
  llama-index-core/llama_index/core/query_pipeline/query.py
  llama-index-core/llama_index/core/response_synthesizers/tree_summarize.py
  llama-index-core/llama_index/core/tools/retriever_tool.py
  llama-index-core/llama_index/core/types.py
  llama-index-integrations/node_parser/llama-index-node-parser-docling/pyproject.toml
  llama-index-integrations/node_parser/llama-index-node-parser-docling/tests/test_node_parser_docling.py
Labels: size:L

#17831 improve prompt helper multimodal support
  llama-index-core/llama_index/core/indices/prompt_helper.py
  llama-index-core/llama_index/core/prompts/utils.py
Labels: size:S

#17833 openai developer message fix
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:XS

#17834 v0.12.18
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/readers/microsoft_outlook_emails.md
  docs/docs/api_reference/tools/mcp.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  llama-index-integrations/agent/llama-index-agent-openai/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: lgtm, size:L

#17832 NVIDIARerank add http_client parameter to pass custom clients
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_api_key.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_available_models.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_base_url.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_postprocessor_nvidia_rerank.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_truncate.py
Labels: lgtm, size:L

#17842 fix version on memgraph
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/pyproject.toml
Labels: size:XS

#17843 update from scratch agent examples
  docs/docs/examples/workflow/function_calling_agent.ipynb
  docs/docs/examples/workflow/react_agent.ipynb
Labels: size:L

#17844 Image Metadata Test + Sync Implementation
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/api_utils.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/tests/data/Simple PDF Slides.pdf
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/tests/test_indices_managed_llama_cloud.py
Labels: lgtm, size:M

#17847 mistral saba support
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/utils.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
Labels: size:S

#16637 Function tool callback
  docs/docs/examples/tools/function_tool_callback.ipynb
  llama-index-core/llama_index/core/tools/function_tool.py
  llama-index-core/llama_index/core/tools/types.py
Labels: lgtm, size:L

#15642 Experimental natural language retrievers using duck db
  llama-index-experimental/llama_index/experimental/retrievers/natrual_language/BUILD
  llama-index-experimental/llama_index/experimental/retrievers/natrual_language/README.md
  llama-index-experimental/llama_index/experimental/retrievers/natrual_language/__init__.py
  llama-index-experimental/llama_index/experimental/retrievers/natrual_language/nl_csv_retriever.py
  llama-index-experimental/llama_index/experimental/retrievers/natrual_language/nl_data_frame_retierver.py
  llama-index-experimental/llama_index/experimental/retrievers/natrual_language/nl_json_retriever.py
  llama-index-experimental/pyproject.toml
Labels: lgtm, size:L

#17848 v0.12.19
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/prompts/utils.py
  llama-index-core/pyproject.toml
  llama-index-core/tests/prompts/test_base.py
  poetry.lock
  pyproject.toml
Labels: size:M

#17866 fix: bump python-jose
  llama-index-networks/pyproject.toml
Labels: size:XS

#17868 attach more metadata to retrieved image node
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/api_utils.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/tests/test_indices_managed_llama_cloud.py
Labels: lgtm, size:S

#17867 Path was incorrect for microsoft_outlook_emails integration
  docs/mkdocs.yml
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/llama_index/readers/microsoft_outlook_emails/BUILD
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/llama_index/readers/microsoft_outlook_emails/__init__.py
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/llama_index/readers/microsoft_outlook_emails/base.py
Labels: lgtm, size:XS

#17884 fix: `FunctionAgent` and `ReActAgent` error out when LLM response contains no chat messages
  llama-index-core/llama_index/core/agent/workflow/function_agent.py
  llama-index-core/llama_index/core/agent/workflow/react_agent.py
  llama-index-core/tests/agent/workflow/test_multi_agent_workflow.py
Labels: size:L

#17911 feat(bedrock-converse): add Claude 3.7 Sonnet model support
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: lgtm, size:XS

#17888 fix: Convert Embedding Functions to Async
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/llama_index/embeddings/huggingface/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-huggingface/pyproject.toml
Labels: lgtm, size:XS

#17912 fix: python version requirement in redis vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-redis/pyproject.toml
Labels: size:XS

#17919 fix: fix tests on `main` branch
  llama-index-integrations/readers/llama-index-readers-docling/tests/test_readers_docling.py
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/llama_index/readers/microsoft_outlook_emails/__init__.py
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-microsoft-outlook-emails/tests/test_readers_microsoft_outlook_mails.py
Labels: size:M

#17923 v0.12.20
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/mkdocs.yml
  docs/scripts/prepare_for_build.py
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#17929 fix: typo workflow/index.md
  docs/docs/module_guides/workflow/index.md
Labels: lgtm, size:XS

#17938 safer workflow cancel + fix restored context bug
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
  llama-index-core/llama_index/core/workflow/workflow.py
Labels: size:S

#17855 Support text-only prompts for LlamaMultiModal class
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/llama_index/multi_modal_llms/huggingface/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-huggingface/pyproject.toml
Labels: lgtm, size:S

#17889 feat: add tests for gemini, fix function calling parameters
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-gemini/tests/test_llms_gemini.py
Labels: size:L

#17904 llamaindex-cli to handle glob patterns correctly
  docs/docs/getting_started/starter_tools/rag_cli.md
  llama-index-cli/llama_index/cli/rag/base.py
  llama-index-cli/pyproject.toml
  llama-index-cli/tests/test_rag.py
Labels: lgtm, size:M

#17914 fix: stepwise execution breaks when steps do async work
  docs/docs/module_guides/workflow/index.md
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/llama_index/core/workflow/events.py
  llama-index-core/llama_index/core/workflow/handler.py
  llama-index-core/llama_index/core/workflow/utils.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_stepwise.py
Labels: lgtm, size:L, topic:workflows

#17915 feat(bedrock converse): add Meta Llama 3.3 70B instruct model support
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: lgtm, size:XS

#17921 Fix "Invalid value for 'content': expected a string, got null." openai error in case of empty assistant messages
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_utils.py
Labels: lgtm, size:S

#17930 fix: make base64 detection more robust across the board
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-core/llama_index/core/schema.py
  llama-index-core/llama_index/core/utils.py
Labels: lgtm, size:M

#17928 fix: tools param cannot be Null when calling Anthropic Messages API
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-anthropic/tests/test_llms_anthropic.py
Labels: lgtm, size:M

#17872 tl;dw AI Integration for Retrievers
  llama-index-integrations/retrievers/llama-index-retrievers-tldw/.gitignore
  llama-index-integrations/retrievers/llama-index-retrievers-tldw/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-tldw/Makefile
  llama-index-integrations/retrievers/llama-index-retrievers-tldw/README.md
  llama-index-integrations/retrievers/llama-index-retrievers-tldw/llama_index/retrievers/tldw/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-tldw/llama_index/retrievers/tldw/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-tldw/llama_index/retrievers/tldw/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-tldw/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-tldw/tests/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-tldw/tests/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-tldw/tests/test_retrievers_tldw_retriever.py
Labels: lgtm, size:L

#17908 `azureaisearch`: add default `mySemanticConfig` as name when creating index
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/pyproject.toml
Labels: size:XS

#17927 fix: openai-like openai agent streaming over vLLM
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:S

#17845 fix ChatSummaryMemoryBuffer._summarize_oldest_chat_history
  llama-index-core/llama_index/core/memory/chat_summary_memory_buffer.py
  llama-index-core/tests/memory/test_chat_summary_memory_buffer.py
Labels: lgtm, size:S

#17890 fix: fix adelete method and add delete_nodes to elasticsearch vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/tests/test_vector_stores_elasticsearch.py
Labels: lgtm, size:L

#17897 Fix CitationQueryEngine init function for response_synthesizer
  llama-index-core/llama_index/core/query_engine/citation_query_engine.py
Labels: lgtm, size:XS

#17901 only modify delta if 'Answer:' was actually detected
  llama-index-core/llama_index/core/agent/react/step.py
Labels: lgtm, size:XS

#17909 Feature/remove retriever tool template override
  llama-index-core/llama_index/core/tools/retriever_tool.py
  llama-index-core/tests/tools/test_base.py
  llama-index-core/tests/tools/test_retriever_tool.py
Labels: lgtm, size:M

#17865 feat: auto-detect custom start and stop events in workflow classes
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/conftest.py
  llama-index-core/tests/workflow/test_decorator.py
  llama-index-core/tests/workflow/test_service.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: size:L, topic:workflows

#17942 fix: take step workers into account when running a workflow step-wise
  llama-index-core/llama_index/core/workflow/context.py
Labels: lgtm, size:S, topic:workflows

#17954 gpt-4.5-preview
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:XS

#17900 feat: Add `ibm-watsonx-ai` rerank integration
  docs/docs/examples/node_postprocessor/ibm_watsonx.ipynb
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/.gitignore
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/Makefile
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/llama_index/postprocessor/ibm/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/llama_index/postprocessor/ibm/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/llama_index/postprocessor/ibm/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/llama_index/postprocessor/ibm/utils.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/tests/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/tests/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/tests/test_ibm.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/tests/test_postprocessor_ibm_rerank.py
Labels: lgtm, size:XXL

#17953 fix: escape user input before shelling out command
  llama-index-cli/llama_index/cli/rag/base.py
  llama-index-cli/pyproject.toml
Labels: size:S

#17952 fix: escape params in SQL queries in DuckDB vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/llama_index/vector_stores/duckdb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-duckdb/pyproject.toml
Labels: lgtm, size:L

#17950 feat(bedrock): add Claude 3.7 Sonnet model support
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
Labels: lgtm, size:XS

#17949 fix: respect max_depth in KnowledgeBaseWebReader
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/knowledge_base/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:S

#17943 fix: remove warnings from workflow tests
  llama-index-core/tests/workflow/test_checkpointer.py
  llama-index-core/tests/workflow/test_context.py
  llama-index-core/tests/workflow/test_decorator.py
  llama-index-core/tests/workflow/test_event.py
  llama-index-core/tests/workflow/test_streaming.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: lgtm, size:M, topic:workflows

#17934 Support for custom vectara_base_url
  llama-index-integrations/indices/llama-index-indices-managed-vectara/Changelog.md
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/base.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-vectara/tests/test_indices_managed_vectara.py
Labels: lgtm, size:M

#17892 feat: Add Valyu Integration
  llama-index-integrations/tools/llama-index-tools-valyu/.gitignore
  llama-index-integrations/tools/llama-index-tools-valyu/BUILD
  llama-index-integrations/tools/llama-index-tools-valyu/CHANGELOG.md
  llama-index-integrations/tools/llama-index-tools-valyu/Makefile
  llama-index-integrations/tools/llama-index-tools-valyu/README.md
  llama-index-integrations/tools/llama-index-tools-valyu/examples/BUILD
  llama-index-integrations/tools/llama-index-tools-valyu/examples/context.py
  llama-index-integrations/tools/llama-index-tools-valyu/llama_index/tools/valyu/BUILD
  llama-index-integrations/tools/llama-index-tools-valyu/llama_index/tools/valyu/__init__.py
  llama-index-integrations/tools/llama-index-tools-valyu/llama_index/tools/valyu/base.py
  llama-index-integrations/tools/llama-index-tools-valyu/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-valyu/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-valyu/tests/__init__.py
  llama-index-integrations/tools/llama-index-tools-valyu/tests/test_tools_valyu.py
Labels: lgtm, size:L

#17947 fix: Remove `cache_dir` Pydantic field validation
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/llama_index/embeddings/gaudi/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-gaudi/pyproject.toml
Labels: lgtm, size:XS

#17951 refactor openai multimodal
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-azure-openai/llama_index/multi_modal_llms/azure_openai/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-azure-openai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-azure-openai/tests/test_multi-modal-llms_azure_openai.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nebius/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nebius/tests/test_multi_modal_llms_nebius.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/llama_index/multi_modal_llms/openai/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/llama_index/multi_modal_llms/openai/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/tests/test_multi-modal-llms_openai.py
Labels: size:XL

#17839 Update `WatsonxLLM.metadata` property to avoid validation error when `model_limits` field isn't present
  llama-index-integrations/llms/llama-index-llms-ibm/llama_index/llms/ibm/base.py
  llama-index-integrations/llms/llama-index-llms-ibm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ibm/tests/test_ibm.py
Labels: lgtm, size:L

#17958 v0.12.21
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/postprocessor/ibm.md
  docs/docs/api_reference/retrievers/tldw.md
  docs/docs/api_reference/tools/valyu.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#17968 fix agentworkflow tool call tracking
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
Labels: size:S

#17959 Ensure that Github reader uses timeout and retries params
  llama-index-integrations/readers/llama-index-readers-github/llama_index/readers/github/repository/base.py
  llama-index-integrations/readers/llama-index-readers-github/llama_index/readers/github/repository/utils.py
  llama-index-integrations/readers/llama-index-readers-github/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-github/tests/test_github_repository_reader.py
Labels: lgtm, size:M

#17957 chore: update FireCrawlWebReader integration
  docs/docs/examples/data_connectors/WebPageDemo.ipynb
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/firecrawl_web/README.md
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/firecrawl_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/scrapfly_web/README.md
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:L
