Repository run-llama/llama_index, pull requests merged in 2025-08, with the labels that each got.

#19577 fix: BM25 Retriever allow top_k value greater than number of nodes added
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/llama_index/retrievers/bm25/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/tests/test_retrievers_bm25_retriever.py
Labels: size:M

#19581 fix: change ts_query definition to avoid double-stemming
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: size:S

#19587 feat(baiduvectordb): add wait logic for critical operations
  llama-index-integrations/vector_stores/llama-index-vector-stores-baiduvectordb/llama_index/vector_stores/baiduvectordb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-baiduvectordb/pyproject.toml
Labels: lgtm, size:L

#19586 feat: Add metadata filtering support to BM25 Retriever and update documentation
  docs/docs/examples/retrievers/bm25_retriever.ipynb
  llama-index-core/llama_index/core/vector_stores/simple.py
  llama-index-core/llama_index/core/vector_stores/utils.py
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/llama_index/retrievers/bm25/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/tests/test_retrievers_bm25_retriever.py
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/uv.lock
Labels: lgtm, size:L

#19594 add notebook for gpt-oss with ollama
  docs/docs/examples/cookbooks/ollama_gpt_oss_cookbook.ipynb
  docs/mkdocs.yml
Labels: size:L

#19598 Enabled partially formatted system prompt for ReAct agent
  llama-index-core/llama_index/core/agent/workflow/react_agent.py
  llama-index-core/tests/agent/react/test_prompt_customization.py
Labels: lgtm, size:S

#19604 chore(oci): update list of supported LLMs for OCI integration
  llama-index-integrations/llms/llama-index-llms-oci-genai/llama_index/llms/oci_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-oci-genai/pyproject.toml
Labels: lgtm, size:XS

#19592 Add multimodal and multiple tool calling documentation to GoogleGenAI
  docs/docs/examples/llm/google_genai.ipynb
Labels: lgtm, size:M

#19590 chore: bump version to 0.4.1 and update model name conditions in VoyageEmbedding class
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/llama_index/embeddings/voyageai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-voyageai/pyproject.toml
Labels: lgtm, size:XS

#19584 Support presidio entities
  llama-index-integrations/postprocessor/llama-index-postprocessor-presidio/llama_index/postprocessor/presidio/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-presidio/pyproject.toml
Labels: size:S

#19612 docs: add zeroentropy cookbook to mkdocs
  docs/mkdocs.yml
Labels: size:XS

#19613 add gpt-5
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: lgtm, size:S

#19617 fix isinstance check in openai
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:XS

#19618 feat: add support for gpt-oss NIM
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/utils.py
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
Labels: lgtm, size:S

#19576 feat:heroku llm integration
  llama-index-integrations/llms/llama-index-llms-heroku/.gitignore
  llama-index-integrations/llms/llama-index-llms-heroku/LICENSE
  llama-index-integrations/llms/llama-index-llms-heroku/Makefile
  llama-index-integrations/llms/llama-index-llms-heroku/README.md
  llama-index-integrations/llms/llama-index-llms-heroku/llama_index/llms/heroku/__init__.py
  llama-index-integrations/llms/llama-index-llms-heroku/llama_index/llms/heroku/base.py
  llama-index-integrations/llms/llama-index-llms-heroku/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-heroku/tests/conftest.py
  llama-index-integrations/llms/llama-index-llms-heroku/tests/test_api_key.py
  llama-index-integrations/llms/llama-index-llms-heroku/tests/test_integration.py
  llama-index-integrations/llms/llama-index-llms-heroku/uv.lock
Labels: lgtm, size:XL

#19621 Fixed special character bug in PGVectorStore query
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: lgtm, size:S

#19536 fix: Order preservation and fetching in batch non-cached embeddings in a/get_text_embedding_batch()
  llama-index-core/llama_index/core/base/embeddings/base.py
  llama-index-core/tests/embeddings/test_with_cache.py
Labels: lgtm, size:L

#19624 anthropic citation update
  docs/docs/examples/llm/anthropic.ipynb
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-anthropic/uv.lock
Labels: size:L

#19626 v0.13.1
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/llms/heroku.md
  docs/docs/api_reference/readers/oxylabs.md
  docs/docs/api_reference/storage/vector_store/bigquery.md
  docs/docs/api_reference/tools/aws_bedrock_agentcore.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/uv.lock
  pyproject.toml
  uv.lock
Labels: size:L

#19627 move cognee to stale
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/.gitignore
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/LICENSE
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/Makefile
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/README.md
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/__init__.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/base.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/graph_rag.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/poetry.lock
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/pyproject.toml
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/__init__.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_add_data.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_get_graph_url.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_graph_rag_cognee.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/uv.lock
Labels: size:XL

#19628 remove cognee from docs/repo
  docs/docs/api_reference/graph_rag/cognee.md
  docs/docs/examples/graph_rag/llama_index_cognee_integration.ipynb
  docs/mkdocs.yml
  docs/mkdocs_api_only.yml
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/.gitignore
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/LICENSE
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/Makefile
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/README.md
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/__init__.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/base.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/graph_rag.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/pyproject.toml
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/__init__.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_add_data.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_get_graph_url.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_graph_rag_cognee.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/uv.lock
Labels: size:XL

#19630 fix experimental and finetuning deps
  llama-index-experimental/pyproject.toml
  llama-index-experimental/uv.lock
  llama-index-finetuning/pyproject.toml
  llama-index-finetuning/uv.lock
Labels: size:L

#19635 Access embeddin output
  llama-index-integrations/embeddings/llama-index-embeddings-ollama/llama_index/embeddings/ollama/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-ollama/pyproject.toml
Labels: size:XS

#19637 Add other special characters in ts_query normalization
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/test_postgres.py
Labels: lgtm, size:L

#19647 Updates to ClickHouse integration based on new vector search capabilities in ClickHouse
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/llama_index/vector_stores/clickhouse/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/tests/test_clickhouse.py
Labels: lgtm, size:L

#19633 Fix AzureOpenAI streaming token usage
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_llms_openai.py
Labels: lgtm, size:M

#19649 chore: context window for claude 4 sonnet to 1 mln tokens
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: size:S

#19601 [MCP] Handlers for custom types and pydantic models
  llama-index-integrations/tools/llama-index-tools-mcp/CHANGELOG.md
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/base.py
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/tool_spec_mixins.py
  llama-index-integrations/tools/llama-index-tools-mcp/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-mcp/tests/schemas.py
  llama-index-integrations/tools/llama-index-tools-mcp/tests/server.py
  llama-index-integrations/tools/llama-index-tools-mcp/tests/test_tools_mcp.py
  llama-index-integrations/tools/llama-index-tools-mcp/uv.lock
Labels: size:L

#19651 add stalebot action
  .github/workflows/stale_bot.yml
Labels: size:S

#19650 Update and fix cognee integration
  docs/docs/api_reference/graph_rag/cognee.md
  docs/docs/examples/graph_rag/llama_index_cognee_integration.ipynb
  docs/mkdocs.yml
  docs/mkdocs_api_only.yml
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/.gitignore
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/LICENSE
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/Makefile
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/README.md
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/example.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/graph_visualization.html
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/__init__.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/base.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/llama_index/graph_rag/cognee/graph_rag.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/pyproject.toml
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/__init__.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_add_data.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_graph_rag_cognee.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/tests/test_visualize_graph.py
  llama-index-integrations/graph_rag/llama-index-graph-rag-cognee/uv.lock
Labels: size:XXL

#19653 feat: add openai-oss models to BedrockConverse
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: size:XS

#19478 feat: enhance PowerPoint reader with comprehensive content extraction…
  llama-index-integrations/readers/llama-index-readers-file/README.md
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/slides/__init__.py
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/slides/base.py
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/slides/content_extractor.py
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/slides/image_extractor.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-file/tests/generate_test_ppt.py
  llama-index-integrations/readers/llama-index-readers-file/tests/test_slides.py
  llama-index-integrations/readers/llama-index-readers-file/uv.lock
Labels: size:XXL

#19657 fix persist load for bm25
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/llama_index/retrievers/bm25/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/tests/test_retrievers_bm25_retriever.py
Labels: size:M

#19654 add mcp docs hub to python docs
  docs/docs/module_guides/mcp/convert_existing.md
  docs/docs/module_guides/mcp/index.md
  docs/docs/module_guides/mcp/llamacloud_mcp.md
  docs/docs/module_guides/mcp/llamaindex_mcp.md
  docs/mkdocs.yml
Labels: size:L

#19640 docs: Add docs for MCP Toolbox + LlamaIndex
  docs/docs/community/integrations.md
  docs/docs/examples/tools/mcp_toolbox.ipynb
Labels: size:L

#19658 feat: backfill gaps to support more models on the api catalog
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/utils.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/uv.lock
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/utils.py
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-nvidia/tests/test_unknown_models.py
  llama-index-integrations/llms/llama-index-llms-nvidia/uv.lock
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/llama_index/multi_modal_llms/nvidia/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/uv.lock
Labels: lgtm, size:L

#19667 bump openai-like embedding version
  llama-index-integrations/embeddings/llama-index-embeddings-openai-like/pyproject.toml
Labels: size:XS

#19669 docs: update docker image and new method to setup in JaguarDB documentation
  docs/docs/examples/vector_stores/JaguarIndexDemo.ipynb
Labels: lgtm, size:S

#19671 Logan/fix ollama role
  llama-index-core/llama_index/core/utilities/token_counting.py
  llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
  llama-index-integrations/llms/llama-index-llms-ollama/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ollama/tests/test_llms_ollama.py
  llama-index-integrations/llms/llama-index-llms-ollama/uv.lock
  llama-index-packs/llama-index-packs-resume-screener/pyproject.toml
  llama-index-packs/llama-index-packs-resume-screener/uv.lock
Labels: size:S

#19636 feat(retrievers-superlinked): add Superlinked retriever integration (new package)
  .gitignore
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/LICENSE
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/README.md
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/examples/steam_games_example.ipynb
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/examples/steam_games_example.py
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/src/llama_index/retrievers/superlinked/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/src/llama_index_retrievers_superlinked/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/src/llama_index_retrievers_superlinked/retriever.py
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/tests/test_integration_superlinked_retriever.py
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/tests/test_unit_superlinked_retriever.py
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/uv.lock
Labels: lgtm, size:XL

#19672 v0.13.2
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/retrievers/superlinked.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-core/uv.lock
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  pyproject.toml
  uv.lock
Labels: size:L

#19673 fix superlinked package
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/examples/steam_games_example.ipynb
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/examples/steam_games_example.py
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/llama_index/retrievers/superlinked/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/llama_index/retrievers/superlinked/retriever.py
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/src/llama_index/retrievers/superlinked/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/src/llama_index_retrievers_superlinked/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/tests/test_integration_superlinked_retriever.py
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/tests/test_unit_superlinked_retriever.py
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/uv.lock
Labels: size:M

#19680 Rename build_knowldege_graph_with_no4j_llamacloud.ipynb
  docs/docs/examples/cookbooks/build_knowldege_graph_with_neo4j_llamacloud.ipynb
  docs/mkdocs.yml
Labels: lgtm, size:XS

#19681 Neo4j llamacloud example typos
  docs/docs/examples/cookbooks/build_knowledge_graph_with_neo4j_llamacloud.ipynb
  docs/mkdocs.yml
Labels: size:S

#19676 Small changes in doc for better understanding
  docs/docs/understanding/extraction/structured_input.md
  docs/docs/understanding/extraction/structured_llms.md
Labels: lgtm, size:XS

#19684 Update steam_games_example.ipynb
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/examples/steam_games_example.ipynb
Labels: lgtm, size:XS

#19683 unlock pypdf dep
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-file/uv.lock
Labels: size:XS

#19687 feat: add gpt-5-chat-latest model support
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_utils.py
  llama-index-integrations/llms/llama-index-llms-openai/uv.lock
Labels: lgtm, size:M

#19685 Adds support for HerokuEmbeddings
  docs/docs/api_reference/embeddings/heroku.md
  docs/docs/examples/embeddings/heroku.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-heroku/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-heroku/LICENSE
  llama-index-integrations/embeddings/llama-index-embeddings-heroku/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-heroku/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-heroku/examples/async_usage.py
  llama-index-integrations/embeddings/llama-index-embeddings-heroku/examples/basic_usage.py
  llama-index-integrations/embeddings/llama-index-embeddings-heroku/llama_index/embeddings/heroku/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-heroku/llama_index/embeddings/heroku/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-heroku/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-heroku/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-heroku/tests/test_heroku_embeddings.py
  llama-index-integrations/embeddings/llama-index-embeddings-heroku/uv.lock
Labels: lgtm, size:XXL

#19702 add heroku embedding path to mkdocs
  docs/mkdocs.yml
Labels: size:XS

#19705 fix(SageMakerLLM): fix constructor region read to not read region_name before is popped from kwargs, and fix assign to super
  llama-index-integrations/llms/llama-index-llms-sagemaker-endpoint/llama_index/llms/sagemaker_endpoint/base.py
  llama-index-integrations/llms/llama-index-llms-sagemaker-endpoint/pyproject.toml
Labels: lgtm, size:S

#19720 Support Azure OpenAPI in MongoDB integration tests
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/conftest.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/test_integration.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/test_vectorstore.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/uv.lock
Labels: lgtm, size:M

#19717 Added Maxim AI Observability Support Documentation
  docs/docs/examples/observability/Maxim-Instrumentation.ipynb
  docs/docs/module_guides/observability/index.md
  docs/mkdocs.yml
Labels: lgtm, size:XL

#19652 Qdrant sharding
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/tests/conftest.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/tests/test_vector_stores_qdrant.py
Labels: size:XL

#19727 v0.13.3
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/DOCS_README.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/download/utils.py
  llama-index-core/llama_index/core/multi_modal_llms/generic_utils.py
  llama-index-core/llama_index/core/response/notebook_utils.py
  llama-index-core/llama_index/core/schema.py
  llama-index-core/llama_index/core/utils.py
  llama-index-core/pyproject.toml
  llama-index-core/tests/agent/workflow/test_return_direct_e2e.py
  llama-index-integrations/tools/llama-index-tools-playwright/tests/test_tools_playwright.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
  pyproject.toml
  uv.lock
Labels: size:L

#19710 Feature/baseten integration
  docs/docs/examples/embeddings/baseten.ipynb
  docs/docs/examples/llm/baseten.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-baseten/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-baseten/LICENSE
  llama-index-integrations/embeddings/llama-index-embeddings-baseten/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-baseten/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-baseten/llama_index/embeddings/baseten/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-baseten/llama_index/embeddings/baseten/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-baseten/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-baseten/uv.lock
  llama-index-integrations/llms/llama-index-llms-baseten/.gitignore
  llama-index-integrations/llms/llama-index-llms-baseten/BUILD
  llama-index-integrations/llms/llama-index-llms-baseten/LICENSE
  llama-index-integrations/llms/llama-index-llms-baseten/Makefile
  llama-index-integrations/llms/llama-index-llms-baseten/README.md
  llama-index-integrations/llms/llama-index-llms-baseten/llama_index/llms/baseten/BUILD
  llama-index-integrations/llms/llama-index-llms-baseten/llama_index/llms/baseten/__init__.py
  llama-index-integrations/llms/llama-index-llms-baseten/llama_index/llms/baseten/base.py
  llama-index-integrations/llms/llama-index-llms-baseten/llama_index/llms/baseten/utils.py
  llama-index-integrations/llms/llama-index-llms-baseten/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-baseten/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-baseten/tests/test_llms_baseten.py
  llama-index-integrations/llms/llama-index-llms-baseten/uv.lock
Labels: lgtm, size:XXL

#19728 feat: add amazon.nova-premier-v1:0 to BEDROCK_MODELS
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: lgtm, size:XS

#19731 add mmr search to chroma
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/llama_index/vector_stores/chroma/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/tests/test_mmr.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/uv.lock
Labels: lgtm, size:L

#19746 feat: add missing sync wrapper of put_messages in memory
  llama-index-core/llama_index/core/memory/memory.py
Labels: lgtm, size:XS

#19741 Add PostgreSQL schema support to Memory and SQLAlchemyChatStore
  llama-index-core/llama_index/core/memory/memory.py
  llama-index-core/llama_index/core/storage/chat_store/sql.py
  llama-index-core/tests/memory/test_memory_schema.py
  llama-index-core/tests/storage/chat_store/test_sql_schema.py
  llama-index-core/uv.lock
Labels: lgtm, size:L

#19743 Payload indexes support to QdrantVectorStore
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/tests/conftest.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/tests/test_vector_stores_qdrant.py
Labels: size:L

#19754 fix: rebranding of Azure AI Studio to Azure AI Foundry
  docs/docs/examples/llm/azure_inference.ipynb
Labels: lgtm, size:XS

#19750 Add documentation for W&B Weave
  docs/docs/_static/integrations/weave/weave_quickstart.png
  docs/docs/module_guides/observability/index.md
Labels: lgtm, size:M

#19762 Updates to neo4j cookbook
  docs/docs/examples/cookbooks/build_knowledge_graph_with_neo4j_llamacloud.ipynb
Labels: lgtm, size:L

#19749 feat[IBM]: Support for additional/external urls, make instance_id deprecated
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/llama_index/embeddings/ibm/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/llama_index/embeddings/ibm/utils.py
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/tests/test_ibm.py
  llama-index-integrations/embeddings/llama-index-embeddings-ibm/uv.lock
  llama-index-integrations/llms/llama-index-llms-ibm/llama_index/llms/ibm/base.py
  llama-index-integrations/llms/llama-index-llms-ibm/llama_index/llms/ibm/utils.py
  llama-index-integrations/llms/llama-index-llms-ibm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ibm/tests/test_ibm.py
  llama-index-integrations/llms/llama-index-llms-ibm/uv.lock
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/llama_index/postprocessor/ibm/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/llama_index/postprocessor/ibm/utils.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/tests/test_ibm.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-ibm/uv.lock
Labels: lgtm, size:L

#19756 fix: fix SentenceTransformerRerank init
  llama-index-integrations/postprocessor/llama-index-postprocessor-sbert-rerank/llama_index/postprocessor/sbert_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-sbert-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-sbert-rerank/tests/test_postprocessor_sbert_rerank.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-sbert-rerank/uv.lock
Labels: lgtm, size:M
