Repository run-llama/llama_index, pull requests merged in 2025-03, with the labels that each got.

#17969 v0.12.22
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-huggingface-api/llama_index/llms/huggingface_api/base.py
  llama-index-integrations/llms/llama-index-llms-huggingface-api/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-huggingface-api/tests/test_huggingface_api.py
  poetry.lock
  pyproject.toml
Labels: size:M

#17974 fix: Added missing dependencies to Chatbot_SEC.ipynb example
  docs/docs/examples/agent/Chatbot_SEC.ipynb
Labels: size:XS

#17984 starter typo fix
  docs/docs/getting_started/starter_example.md
  docs/docs/getting_started/starter_example_local.md
Labels: size:XS

#17995 add PropertyGraphStore class in graph_stores index.md
  docs/docs/api_reference/storage/graph_stores/index.md
Labels: lgtm, size:XS

#17997 MistralAI MultImodal content blocks
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/base.py
  llama-index-integrations/llms/llama-index-llms-mistralai/llama_index/llms/mistralai/utils.py
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/llama_index/multi_modal_llms/mistralai/base.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/llama_index/multi_modal_llms/mistralai/utils.py
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-mistralai/tests/test_multi-modal-llms_mistral.py
Labels: size:XL

#17996 Add base_url to AzureOpenAI
  llama-index-integrations/llms/llama-index-llms-azure-openai/llama_index/llms/azure_openai/base.py
  llama-index-integrations/llms/llama-index-llms-azure-openai/pyproject.toml
Labels: lgtm, size:S

#17970 Bugfix: Use torch.no grad() in inference in ImageVisionLLMReader when PyTorch is installed
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/image_vision_llm/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-file/tests/test_image_vision_llm.py
Labels: lgtm, size:L

#17999 LLM Docs Nits
  docs/docs/examples/llm/openai.ipynb
  docs/docs/getting_started/starter_example.md
  docs/docs/understanding/using_llms/using_llms.md
  llama-index-integrations/llms/llama-index-llms-openai-like/llama_index/llms/openai_like/base.py
  llama-index-integrations/llms/llama-index-llms-openai-like/pyproject.toml
Labels: size:L

#18003 Update agent documentation links in starter example guides
  docs/docs/getting_started/starter_example.md
  docs/docs/getting_started/starter_example_local.md
Labels: lgtm, size:XS

#18004 Doc fixes titles
  docs/docs/getting_started/starter_example.md
  docs/docs/getting_started/starter_example_local.md
Labels: lgtm, size:XS

#17979 Feat/mongo chat store
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-mongo/.gitignore
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-mongo/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-mongo/LICENSE
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-mongo/Makefile
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-mongo/README.md
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-mongo/llama_index/storage/chat_store/mongo/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-mongo/llama_index/storage/chat_store/mongo/__init__.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-mongo/llama_index/storage/chat_store/mongo/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-mongo/pyproject.toml
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-mongo/tests/BUILD
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-mongo/tests/__init__.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-mongo/tests/test_chat_store_mongo_chat_store.py
Labels: lgtm, size:XL

#18006 do not convert raw tool output in AgentWorkflow
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
Labels: size:XS

#18005 Add code snippet in tool agent docs for clarity
  docs/docs/understanding/agent/tools.md
Labels: lgtm, size:XS

#18007 Make `request_timeout` in Ollama LLM optional
  llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
  llama-index-integrations/llms/llama-index-llms-ollama/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ollama/tests/test_llms_ollama.py
Labels: lgtm, size:M

#18010 chore: break down deeplake tests
  llama-index-integrations/vector_stores/llama-index-vector-stores-deeplake/tests/test_vector_stores_deeplake.py
Labels: size:L

#18001 feat: return event instance from run() when stop event is custom
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/llama_index/core/workflow/handler.py
  llama-index-core/llama_index/core/workflow/types.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: lgtm, size:M

#18016 Remove large, legacy dependency
  llama-index-integrations/callbacks/llama-index-callbacks-arize-phoenix/pyproject.toml
Labels: lgtm, size:XS

#18021 Update variable name in workflow code example
  docs/docs/module_guides/workflow/index.md
Labels: lgtm, size:XS

#18008 support caching of anthropic system prompt
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: lgtm, size:M

#17964 [MarkdownNodeParser] Adding customizable header path separator char
  llama-index-core/llama_index/core/node_parser/file/markdown.py
  llama-index-core/tests/node_parser/test_markdown.py
Labels: lgtm, size:M

#18023 Ensure resuming a workflow actually works
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_workflow.py
Labels: size:M

#18028 [anthropic] allow caching of tool results
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: lgtm, size:XS

#18039 anthropic caching and thinking updates
  docs/docs/examples/llm/anthropic.ipynb
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py
  llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
Labels: size:XL

#18034 docs: document custom start/stop events
  docs/docs/module_guides/workflow/index.md
Labels: lgtm, size:L

#18031 Remove base url validation
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/llama_index/embeddings/nvidia/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-nvidia/tests/test_base_url.py
  llama-index-integrations/llms/llama-index-llms-nvidia/llama_index/llms/nvidia/base.py
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/llama_index/postprocessor/nvidia_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-nvidia-rerank/tests/test_base_url.py
Labels: lgtm, size:L

#18037 AzureOpenAI: api_base and azure_endpoint are mutually exclusive
  llama-index-integrations/llms/llama-index-llms-azure-openai/llama_index/llms/azure_openai/base.py
  llama-index-integrations/llms/llama-index-llms-azure-openai/pyproject.toml
Labels: lgtm, size:XS

#18015 chore: skip deeplake tests when running on CI
  llama-index-integrations/vector_stores/llama-index-vector-stores-deeplake/tests/test_vector_stores_deeplake.py
Labels: lgtm, size:S

#18038 Add support for running single-agent workflows within the BaseWorkflowAgent class
  llama-index-core/llama_index/core/agent/workflow/base_agent.py
  llama-index-core/llama_index/core/agent/workflow/function_agent.py
  llama-index-core/llama_index/core/agent/workflow/react_agent.py
  llama-index-core/llama_index/core/agent/workflow/single_agent_workflow.py
  llama-index-core/tests/agent/workflow/test_single_agent_workflow.py
Labels: size:L

#18041 Fix the error raised when ReactAgent is created without an explicit system message
  llama-index-core/llama_index/core/agent/workflow/react_agent.py
Labels: size:XS

#18027 added merging_separator argument to allow for specifying chunk merge
  llama-index-core/llama_index/core/node_parser/text/semantic_double_merging_splitter.py
Labels: lgtm, size:M

#18047 chore: bump jinja version in docs dependencies
  docs/poetry.lock
  docs/pyproject.toml
Labels: size:XS

#18042 Change `AgentWorkflow` to `FunctionAgent` in documentation.
  docs/docs/getting_started/starter_example.md
  docs/docs/getting_started/starter_example_local.md
  docs/docs/understanding/agent/human_in_the_loop.md
  docs/docs/understanding/agent/index.md
  docs/docs/understanding/agent/streaming.md
  docs/docs/understanding/agent/tools.md
  llama-index-core/llama_index/core/agent/workflow/base_agent.py
  llama-index-core/llama_index/core/agent/workflow/multi_agent_workflow.py
Labels: size:L

#18050 v0.12.23
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/storage/chat_store/mongo.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/readers/file/base.py
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-oci-genai/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#18052 Update mongo as supporting hybrid search
  docs/docs/module_guides/storing/vector_stores.md
Labels: lgtm, size:XS

#18059 Logan/readme update for genai
  llama-index-integrations/llms/llama-index-llms-google-genai/README.md
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
Labels: size:M

#18065 fix link to llama_deploy doc
  docs/docs/module_guides/workflow/index.md
Labels: lgtm, size:XS

#18017 Update workflow example to include the `stepwise=True` parameter
  docs/docs/understanding/workflows/observability.md
Labels: size:S

#18070 [BUG FIX] Google genai vertexai error
  docs/docs/examples/llm/google_genai.ipynb
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/base.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
Labels: lgtm, size:L

#18051 Fix the TypeError in the upsert_triplet method of the NeptuneBaseGrap…
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/base.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/pyproject.toml
Labels: lgtm, size:XS

#18066 - Mem0Memory Integration Issue: Update Required for Mem0 API Parameter Changes
  llama-index-integrations/memory/llama-index-memory-mem0/llama_index/memory/mem0/base.py
  llama-index-integrations/memory/llama-index-memory-mem0/pyproject.toml
  llama-index-integrations/memory/llama-index-memory-mem0/tests/test_mem0.py
Labels: lgtm, size:M

#18079 Google genai embeddings
  docs/docs/examples/embeddings/gemini.ipynb
  docs/docs/examples/embeddings/google_genai.ipynb
  docs/docs/examples/embeddings/google_palm.ipynb
  llama-index-integrations/embeddings/llama-index-embeddings-gemini/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/.gitignore
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/LICENSE
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/Makefile
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/README.md
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/llama_index/embeddings/google_genai/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/llama_index/embeddings/google_genai/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/llama_index/embeddings/google_genai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/tests/__init__.py
  llama-index-integrations/embeddings/llama-index-embeddings-google-genai/tests/test_embeddings_gemini.py
  llama-index-integrations/embeddings/llama-index-embeddings-google/README.md
Labels: size:XL

#18081 remove
  docs/docs/examples/llm/google_genai.ipynb
Labels: size:XS

#18080 improve MCP README
  llama-index-integrations/tools/llama-index-tools-mcp/README.md
  llama-index-integrations/tools/llama-index-tools-mcp/examples/mcp.ipynb
Labels: size:M

#18076 - fix: rssReader support customized user-agent
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/rss/README.md
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/rss/base.py
  llama-index-integrations/readers/llama-index-readers-web/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-web/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-web/tests/test_readers_rss.py
Labels: size:M

#18108 fix gemini roles
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
Labels: size:S

#18075 Contextual reranker
  llama-index-integrations/llms/llama-index-llms-contextual/poetry.lock
  llama-index-integrations/postprocessor/llama-index-postprocessor-contextual-rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-contextual-rerank/LICENSE
  llama-index-integrations/postprocessor/llama-index-postprocessor-contextual-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-contextual-rerank/llama_index/postprocessor/contextual_rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-contextual-rerank/llama_index/postprocessor/contextual_rerank/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-contextual-rerank/llama_index/postprocessor/contextual_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-contextual-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-contextual-rerank/tests/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-contextual-rerank/tests/test.py
Labels: size:L

#17913 Contextual Generate model
  llama-index-integrations/llms/llama-index-llms-contextual/BUILD
  llama-index-integrations/llms/llama-index-llms-contextual/README.md
  llama-index-integrations/llms/llama-index-llms-contextual/llama_index/llms/contextual/BUILD
  llama-index-integrations/llms/llama-index-llms-contextual/llama_index/llms/contextual/__init__.py
  llama-index-integrations/llms/llama-index-llms-contextual/llama_index/llms/contextual/base.py
  llama-index-integrations/llms/llama-index-llms-contextual/llama_index/llms/contextual/test-contextual.ipynb
  llama-index-integrations/llms/llama-index-llms-contextual/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-contextual/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-contextual/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-contextual/tests/test.py
Labels: size:L

#18103 Fix typo in comment of LlamaIndex model guide (multi-modal code)
  docs/docs/module_guides/models/multi_modal.md
Labels: lgtm, size:XS

#18106 Fix the redundancy of ElasticsearchReader.
  llama-index-integrations/readers/llama-index-readers-elasticsearch/llama_index/readers/elasticsearch/base.py
  llama-index-integrations/readers/llama-index-readers-elasticsearch/pyproject.toml
Labels: lgtm, size:S

#18097 Use int type for redirect URI port
  llama-index-integrations/readers/llama-index-readers-google/llama_index/readers/google/docs/base.py
  llama-index-integrations/readers/llama-index-readers-google/pyproject.toml
Labels: lgtm, size:XS

#18043 fix(multimodal): check image path is file before open
  llama-index-core/llama_index/core/multi_modal_llms/generic_utils.py
  llama-index-core/tests/multi_modal_llms/test_generic_utils.py
Labels: lgtm, size:S

#17976 Update Vectara Index to return both document level and page level metadata
  docs/docs/community/integrations/managed_indices.md
  llama-index-integrations/indices/llama-index-indices-managed-vectara/README.md
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/base.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/llama_index/indices/managed/vectara/retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-vectara/pyproject.toml
  llama-index-integrations/indices/llama-index-indices-managed-vectara/tests/test_indices_managed_vectara.py
Labels: lgtm, size:L

#18046 fix bugs and optimize extraction prompt and parse_fn
  docs/docs/examples/cookbooks/GraphRAG_v1.ipynb
  docs/docs/examples/cookbooks/GraphRAG_v2.ipynb
Labels: lgtm, size:L

#18074 Update UA of AzureCosmosDBMongoDBVectorSearch
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosmongo/llama_index/vector_stores/azurecosmosmongo/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosmongo/pyproject.toml
Labels: lgtm, size:XS

#18082 fix: make run_step return all the events produced by a step
  docs/docs/module_guides/workflow/index.md
  docs/docs/understanding/workflows/observability.md
  llama-index-core/llama_index/core/workflow/checkpointer.py
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/llama_index/core/workflow/handler.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_checkpointer.py
  llama-index-core/tests/workflow/test_context.py
  llama-index-core/tests/workflow/test_event.py
  llama-index-core/tests/workflow/test_handler.py
  llama-index-core/tests/workflow/test_stepwise.py
  llama-index-core/tests/workflow/test_workflow.py
  llama-index-integrations/embeddings/llama-index-embeddings-gemini/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-google/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-palm/tests/BUILD
  llama-index-integrations/readers/llama-index-readers-gcs/tests/BUILD
  llama-index-integrations/retrievers/llama-index-retrievers-vertexai-search/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-playwright/tests/test_tools_playwright.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb/pyproject.toml
Labels: lgtm, size:L

#18112 remove assert for multimodal llms
  llama-index-core/llama_index/core/indices/multi_modal/base.py
Labels: size:S

#18110 fix get content node metadata
  llama-index-core/llama_index/core/schema.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/tests/test_vectorstore.py
Labels: size:S

#18132 fix: Update AgentQLWebReader on llamahub
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
Labels: lgtm, size:XS

#18131 feat: Add AgentQL Tool
  llama-index-integrations/tools/llama-index-tools-agentql/.gitignore
  llama-index-integrations/tools/llama-index-tools-agentql/BUILD
  llama-index-integrations/tools/llama-index-tools-agentql/Makefile
  llama-index-integrations/tools/llama-index-tools-agentql/README.md
  llama-index-integrations/tools/llama-index-tools-agentql/examples/AgentQL_browser_agent.ipynb
  llama-index-integrations/tools/llama-index-tools-agentql/llama_index/tools/agentql/BUILD
  llama-index-integrations/tools/llama-index-tools-agentql/llama_index/tools/agentql/__init__.py
  llama-index-integrations/tools/llama-index-tools-agentql/llama_index/tools/agentql/agentql_browser_tool/BUILD
  llama-index-integrations/tools/llama-index-tools-agentql/llama_index/tools/agentql/agentql_browser_tool/__init__.py
  llama-index-integrations/tools/llama-index-tools-agentql/llama_index/tools/agentql/agentql_browser_tool/base.py
  llama-index-integrations/tools/llama-index-tools-agentql/llama_index/tools/agentql/agentql_rest_api_tool/BUILD
  llama-index-integrations/tools/llama-index-tools-agentql/llama_index/tools/agentql/agentql_rest_api_tool/__init__.py
  llama-index-integrations/tools/llama-index-tools-agentql/llama_index/tools/agentql/agentql_rest_api_tool/base.py
  llama-index-integrations/tools/llama-index-tools-agentql/llama_index/tools/agentql/const.py
  llama-index-integrations/tools/llama-index-tools-agentql/llama_index/tools/agentql/messages.py
  llama-index-integrations/tools/llama-index-tools-agentql/llama_index/tools/agentql/utils.py
  llama-index-integrations/tools/llama-index-tools-agentql/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-agentql/tests/BUILD
  llama-index-integrations/tools/llama-index-tools-agentql/tests/__init__.py
  llama-index-integrations/tools/llama-index-tools-agentql/tests/conftest.py
  llama-index-integrations/tools/llama-index-tools-agentql/tests/test_browser_spec.py
  llama-index-integrations/tools/llama-index-tools-agentql/tests/test_rest_api_spec.py
Labels: lgtm, size:XXL

#18133 ensure lock agentql works
  llama-index-integrations/tools/llama-index-tools-agentql/pyproject.toml
Labels: size:XS

#18126 Update Vectara Tool for Metadata Changes to VectaraIndex
  llama-index-integrations/tools/llama-index-tools-vectara-query/examples/vectara_query.ipynb
  llama-index-integrations/tools/llama-index-tools-vectara-query/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-vectara-query/tests/test_tools_vectara_query.py
Labels: lgtm, size:M

#18121 Fix #18117
  llama-index-integrations/readers/llama-index-readers-docling/llama_index/readers/docling/base.py
  llama-index-integrations/readers/llama-index-readers-docling/pyproject.toml
Labels: lgtm, size:XS

#18120 Fix: AzureCosmosNoSQL vector_store; delete based on ref_doc_id
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/llama_index/vector_stores/azurecosmosnosql/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/pyproject.toml
Labels: lgtm, size:XS

#18113 bump compatible pinecone version
  llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/pyproject.toml
Labels: lgtm, size:XS

#18087 AIMon reranker integration into LlamaIndex node postprocessors
  llama-index-integrations/postprocessor/llama-index-postprocessor-aimon-rerank/.gitignore
  llama-index-integrations/postprocessor/llama-index-postprocessor-aimon-rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-aimon-rerank/LICENSE
  llama-index-integrations/postprocessor/llama-index-postprocessor-aimon-rerank/Makefile
  llama-index-integrations/postprocessor/llama-index-postprocessor-aimon-rerank/README.md
  llama-index-integrations/postprocessor/llama-index-postprocessor-aimon-rerank/llama_index/postprocessor/aimon_rerank/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-aimon-rerank/llama_index/postprocessor/aimon_rerank/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-aimon-rerank/llama_index/postprocessor/aimon_rerank/base.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-aimon-rerank/pyproject.toml
  llama-index-integrations/postprocessor/llama-index-postprocessor-aimon-rerank/tests/BUILD
  llama-index-integrations/postprocessor/llama-index-postprocessor-aimon-rerank/tests/__init__.py
  llama-index-integrations/postprocessor/llama-index-postprocessor-aimon-rerank/tests/test_postprocessor_aimon_rerank.py
Labels: lgtm, size:L

#18135 nit google genai
  docs/docs/examples/llm/google_genai.ipynb
Labels: size:L

#18136 feat: Add a `clear` method to the Context class
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/tests/workflow/test_context.py
Labels: lgtm, size:M

#18138 genai image output
  docs/docs/examples/llm/google_genai.ipynb
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/llama_index/core/utilities/gemini_utils.py
  llama-index-core/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
Labels: size:M

#18088 AIMonRerank.ipynb notebook added to LlamaIndex docs/examples
  docs/docs/examples/node_postprocessor/AIMonRerank.ipynb
Labels: lgtm, size:L

#18141 fix kwargs for LlamaCloudCompositeRetriever
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/api_utils.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/composite_retriever.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
Labels: lgtm, size:M

#18142 fix: Set proper origin for requests from WebReader
  llama-index-integrations/readers/llama-index-readers-web/llama_index/readers/web/agentql_web/base.py
  llama-index-integrations/readers/llama-index-readers-web/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-agentql/README.md
  llama-index-integrations/tools/llama-index-tools-agentql/examples/AgentQL_browser_agent.ipynb
Labels: lgtm, size:S

#18146 agentql docs
  docs/docs/api_reference/postprocessor/aimon_rerank.md
  docs/docs/api_reference/readers/web.md
  docs/docs/api_reference/tools/agentql.md
  docs/docs/examples/tools/AgentQL_browser_agent.ipynb
  docs/mkdocs.yml
Labels: size:XL

#18063 feat(mongo reader): field_extractors
  llama-index-integrations/readers/llama-index-readers-mongodb/llama_index/readers/mongodb/base.py
  llama-index-integrations/readers/llama-index-readers-mongodb/pyproject.toml
Labels: lgtm, size:S

#18145 fixes for contextual glm
  llama-index-integrations/llms/llama-index-llms-contextual/README.md
  llama-index-integrations/llms/llama-index-llms-contextual/llama_index/llms/contextual/base.py
  llama-index-integrations/llms/llama-index-llms-contextual/llama_index/llms/contextual/test-contextual.ipynb
  llama-index-integrations/llms/llama-index-llms-contextual/pyproject.toml
Labels: lgtm, size:M

#18148 add token counts to the chat and achat methods of BedrockConverse
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: size:S

#18165 update ClipEmbedding deps
  llama-index-integrations/embeddings/llama-index-embeddings-clip/pyproject.toml
Labels: size:XS

#18170 fix: Optimize memory management of the Context object
  llama-index-core/llama_index/core/workflow/checkpointer.py
  llama-index-core/llama_index/core/workflow/context.py
  llama-index-core/llama_index/core/workflow/handler.py
  llama-index-core/llama_index/core/workflow/workflow.py
  llama-index-core/tests/workflow/test_handler.py
  llama-index-core/tests/workflow/test_streaming.py
  llama-index-integrations/embeddings/llama-index-embeddings-cohere/tests/BUILD
  llama-index-integrations/embeddings/llama-index-embeddings-vertex/tests/BUILD
Labels: lgtm, size:L

#18153 Improved Annotations and Error Handling in utils.py and exec_utils.py
  llama-index-core/llama_index/core/exec_utils.py
  llama-index-core/llama_index/core/img_utils.py
  llama-index-core/llama_index/core/node_parser/text/code.py
  llama-index-core/llama_index/core/node_parser/text/utils.py
  llama-index-core/llama_index/core/workflow/utils.py
Labels: lgtm, size:L

#18054 Ensuring original text is preserved in CHUNKING_REGEX
  llama-index-core/llama_index/core/node_parser/text/sentence.py
  llama-index-core/tests/text_splitter/test_sentence_splitter.py
Labels: lgtm, size:S

#18173 use SimpleDirectoryReader without llama-index-readers-file package
  llama-index-core/llama_index/core/readers/file/base.py
Labels: size:S

#18174 fix: allow streaming events from context after workflows ends
  llama-index-core/llama_index/core/workflow/context.py
Labels: lgtm, size:S

#18169 Replace deprecated predict with invoke in llama-index-llms-langchain
  llama-index-integrations/llms/llama-index-llms-langchain/llama_index/llms/langchain/base.py
  llama-index-integrations/llms/llama-index-llms-langchain/pyproject.toml
Labels: lgtm, size:XS

#18177 v0.12.25
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/netmind.md
  docs/docs/api_reference/llms/netmind.md
  docs/docs/api_reference/llms/novita.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#18187 handle chat message as user msg in converse
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: size:XS

#18191 Fix `api_base` parameter in AzureOpenAIEmbedding class
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/llama_index/embeddings/azure_openai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/pyproject.toml
Labels: lgtm, size:XS

#18192 update qdrant to always prefer named vectors
  docs/docs/examples/vector_stores/QdrantIndexDemo.ipynb
  docs/docs/examples/vector_stores/qdrant_hybrid.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/tests/conftest.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/tests/test_vector_stores_qdrant.py
Labels: size:XL

#18045 Add new apac bedrock llms
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
Labels: lgtm, size:S

#18084 feat: Add TTL support for DynamoDB chat store
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/llama_index/storage/chat_store/dynamodb/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/pyproject.toml
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-dynamodb/tests/test_chat_store_dynamodb_chat_store.py
Labels: lgtm, size:L

#18207 add o1-pro support
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:XS

#18201 [Bugfix]: Vertex LLM does Handle FunctionCall tools #16678
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py
  llama-index-integrations/llms/llama-index-llms-vertex/pyproject.toml
Labels: lgtm, size:XS

#18214 sanity bump on converse
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: size:XS

#18210 deprecate older google and bedrock packages
  llama-index-integrations/embeddings/llama-index-embeddings-gemini/llama_index/embeddings/gemini/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-gemini/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-google/llama_index/embeddings/google/gemini.py
  llama-index-integrations/embeddings/llama-index-embeddings-google/llama_index/embeddings/google/palm.py
  llama-index-integrations/embeddings/llama-index-embeddings-google/llama_index/embeddings/google/univ_sent_encoder.py
  llama-index-integrations/embeddings/llama-index-embeddings-google/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-vertex/llama_index/embeddings/vertex/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-vertex/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py
  llama-index-integrations/llms/llama-index-llms-vertex/pyproject.toml
Labels: size:M

#18196 [BUG#18182] add astream_chat astream_complete for dashscope llm
  llama-index-integrations/llms/llama-index-llms-dashscope/llama_index/llms/dashscope/base.py
  llama-index-integrations/llms/llama-index-llms-dashscope/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-dashscope/tests/test_dashscope.py
Labels: lgtm, size:L

#18194 Update to SentenceTransformersFinetuneEngine to expose transformer checkpoint related arguments
  llama-index-finetuning/llama_index/finetuning/embeddings/sentence_transformer.py
  llama-index-finetuning/pyproject.toml
Labels: lgtm, size:S

#18219 Fix `api_base` and `azure_deployment` mutually exclusive in AzureOpenAIEmbedding class
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/llama_index/embeddings/azure_openai/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/pyproject.toml
Labels: lgtm, size:XS

#18216 add implementation for structured llm reranker
  docs/docs/examples/node_postprocessor/Structured-LLMReranker-Lyft-10k.ipynb
  llama-index-core/llama_index/core/postprocessor/__init__.py
  llama-index-core/llama_index/core/postprocessor/structured_llm_rerank.py
  llama-index-core/llama_index/core/prompts/default_prompts.py
  llama-index-core/tests/postprocessor/test_structured_llm_rerank.py
Labels: lgtm, size:XL

#18231 fix: support anyof, optional and union in google-genai
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/base.py
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-google-genai/tests/test_llms_google_genai.py
Labels: lgtm, size:L

#18213 feat:add Bedrock application inference profile support
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/__init__.py
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock/tests/test_bedrock.py
Labels: lgtm, size:L

#18218 Add AgentQL Research Assistant example
  docs/docs/examples/agent/agent_workflow_research_assistant.ipynb
Labels: lgtm, size:L

#18242 fix google genai tool description
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
Labels: size:S

#18233 feat: improve data retrieval by adding headers with the columns
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/tabular/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: lgtm, size:M

#18258 improve default image quality in openai llm
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_utils.py
Labels: size:S

#18178 Introduce RichPromptTemplate
  llama-index-core/llama_index/core/prompts/rich.py
  llama-index-core/poetry.lock
  llama-index-core/pyproject.toml
  llama-index-core/tests/prompts/test_rich.py
Labels: size:L

#18244 Escape single quotes in milvus filters
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:XS

#18229 Fix typo DocstoreDemo.ipynb
  docs/docs/examples/docstore/DocstoreDemo.ipynb
Labels: lgtm, size:XS

#18243 Speed up Milvus async_add
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/tests/test_vector_stores_milvus.py
Labels: lgtm, size:L

#18236 Fix #18204: Add collect_events method to Context class documentation
  docs/docs/api_reference/workflow/context.md
  llama-index-core/llama_index/core/workflow/context.py
Labels: lgtm, size:S

#18246 fix(llms-gemini): Ensure stream_complete accumulates text and sets delta
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/utils.py
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-gemini/tests/test_llms_gemini.py
Labels: size:M

#18273 bump qdrant version python deps
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
Labels: size:XS

#18285 Add deprecation message to Bedrock integration example
  docs/docs/examples/llm/bedrock.ipynb
Labels: lgtm, size:XS

#18283 Fixed provider-resolution for `foundation-model` ARNs
  llama-index-integrations/llms/llama-index-llms-bedrock/CHANGELOG.md
  llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock/tests/test_utils.py
Labels: lgtm, size:M

#18274 Fix Runtime Warning for Coroutine never awaited in Redis chat store
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-redis/llama_index/storage/chat_store/redis/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-redis/pyproject.toml
Labels: lgtm, size:S

#18281 Milvus Vector Store: Support full-text search by BM25
  docs/docs/examples/vector_stores/MilvusFullTextSearchDemo.ipynb
  docs/docs/examples/vector_stores/MilvusHybridIndexDemo.ipynb
  docs/docs/examples/vector_stores/MilvusIndexDemo.ipynb
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/utils.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/tests/test_vector_stores_milvus.py
Labels: lgtm, size:XXL

#18235 feat: added tool calling support for LiteLLM
  llama-index-integrations/llms/llama-index-llms-litellm/llama_index/llms/litellm/base.py
  llama-index-integrations/llms/llama-index-llms-litellm/llama_index/llms/litellm/utils.py
  llama-index-integrations/llms/llama-index-llms-litellm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-litellm/tests/test_llms_litellm.py
  llama-index-integrations/llms/llama-index-llms-litellm/tests/test_utils.py
Labels: lgtm, size:L

#18290 type safe structured predict in overriden methods
  llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
  llama-index-integrations/llms/llama-index-llms-gemini/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/base.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
  llama-index-integrations/llms/llama-index-llms-ollama/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
Labels: size:L

#18225 support postponed type hints in step signatures
  llama-index-core/llama_index/core/workflow/utils.py
  llama-index-core/tests/workflow/test_utils.py
  llama-index-core/tests/workflow/test_workflow_postponed_annotations.py
Labels: lgtm, size:M

#18296 add more redirects
  docs/mkdocs.yml
Labels: size:S

#18297 fix docs build
  docs/mkdocs.yml
Labels: size:XS

#18305 chore: move llama-index-vector-stores-myscale to stale
  llama-index-integrations/vector_stores/llama-index-vector-stores-myscale/.gitignore
  llama-index-integrations/vector_stores/llama-index-vector-stores-myscale/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-myscale/LICENSE
  llama-index-integrations/vector_stores/llama-index-vector-stores-myscale/Makefile
  llama-index-integrations/vector_stores/llama-index-vector-stores-myscale/README.md
  llama-index-integrations/vector_stores/llama-index-vector-stores-myscale/llama_index/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-myscale/llama_index/py.typed
  llama-index-integrations/vector_stores/llama-index-vector-stores-myscale/llama_index/vector_stores/myscale/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-myscale/llama_index/vector_stores/myscale/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-myscale/llama_index/vector_stores/myscale/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-myscale/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-myscale/tests/BUILD
  llama-index-integrations/vector_stores/llama-index-vector-stores-myscale/tests/__init__.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-myscale/tests/test_vector_stores_myscale.py
Labels: lgtm, size:L

#18300 Support OpenAI responses API
  docs/docs/api_reference/llms/openai.md
  docs/docs/examples/llm/openai_responses.ipynb
  docs/mkdocs.yml
  llama-index-core/llama_index/core/base/llms/generic_utils.py
  llama-index-core/llama_index/core/base/llms/types.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/__init__.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/responses.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/tests/test_openai_responses.py
Labels: size:XXL

#18289 optimize initial imports
  llama-index-core/llama_index/core/BUILD
  llama-index-core/llama_index/core/node_parser/text/semantic_double_merging_splitter.py
  llama-index-core/llama_index/core/node_parser/text/utils.py
  llama-index-core/llama_index/core/postprocessor/optimizer.py
  llama-index-core/llama_index/core/prompts/__init__.py
  llama-index-core/llama_index/core/utils.py
  llama-index-core/tests/BUILD
Labels: size:L

#18307 v0.12.27
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/agent/coa.md
  docs/docs/api_reference/agent/dashscope.md
  docs/docs/api_reference/agent/function.md
  docs/docs/api_reference/agent/index.md
  docs/docs/api_reference/agent/introspective.md
  docs/docs/api_reference/agent/lats.md
  docs/docs/api_reference/agent/llm_compiler.md
  docs/docs/api_reference/agent/openai.md
  docs/docs/api_reference/agent/openai_legacy.md
  docs/docs/api_reference/agent/react.md
  docs/docs/api_reference/agent/workflow.md
  docs/docs/api_reference/storage/vector_store/myscale.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: size:L

#18310 add providers kwarg
  llama-index-integrations/embeddings/llama-index-embeddings-fastembed/llama_index/embeddings/fastembed/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-fastembed/pyproject.toml
Labels: size:S

#18292 Feature/asi llm integration
  llama-index-integrations/llms/llama-index-llms-asi/.gitignore
  llama-index-integrations/llms/llama-index-llms-asi/BUILD
  llama-index-integrations/llms/llama-index-llms-asi/LICENSE
  llama-index-integrations/llms/llama-index-llms-asi/Makefile
  llama-index-integrations/llms/llama-index-llms-asi/README.md
  llama-index-integrations/llms/llama-index-llms-asi/llama_index/llms/asi/BUILD
  llama-index-integrations/llms/llama-index-llms-asi/llama_index/llms/asi/__init__.py
  llama-index-integrations/llms/llama-index-llms-asi/llama_index/llms/asi/base.py
  llama-index-integrations/llms/llama-index-llms-asi/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-asi/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-asi/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-asi/tests/test_integration_asi.py
  llama-index-integrations/llms/llama-index-llms-asi/tests/test_llms_asi.py
Labels: size:XL

#18303 Include Node metadata in hash calculation
  llama-index-core/llama_index/core/schema.py
  llama-index-core/tests/ingestion/test_pipeline.py
Labels: lgtm, size:M

#18312 test: add test cases for Load and Search tool
  llama-index-core/tests/tools/tool_spec/test_load_and_search.py
Labels: lgtm, size:L

#18306 Fixed case when json_type is a list (multiple possible types)
  llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/base.py
  llama-index-integrations/tools/llama-index-tools-mcp/pyproject.toml
Labels: lgtm, size:XS

#18311 Update DashScope integration with new tool handling and dependency version bump
  llama-index-integrations/llms/llama-index-llms-dashscope/llama_index/llms/dashscope/base.py
  llama-index-integrations/llms/llama-index-llms-dashscope/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-dashscope/tests/test_dashscope.py
Labels: lgtm, size:L

#18304 Fix `Context._events_queue` when loaded from `Context.from_dict`
  llama-index-core/llama_index/core/workflow/context.py
Labels: lgtm, size:S

#18314 LiteLLM: better support tools streaming, and support multimodal inputs
  llama-index-integrations/llms/llama-index-llms-litellm/llama_index/llms/litellm/base.py
  llama-index-integrations/llms/llama-index-llms-litellm/llama_index/llms/litellm/utils.py
  llama-index-integrations/llms/llama-index-llms-litellm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-litellm/tests/BUILD
  llama-index-integrations/llms/llama-index-llms-litellm/tests/conftest.py
  llama-index-integrations/llms/llama-index-llms-litellm/tests/test_llms_litellm.py
  llama-index-integrations/llms/llama-index-llms-litellm/tests/test_utils.py
Labels: lgtm, size:XL

#18323 misc fixes in constructing client
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/api_utils.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/base.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
Labels: lgtm, size:S

#18320 fix: prevent path traversal from symlinks
  llama-index-integrations/readers/llama-index-readers-obsidian/llama_index/readers/obsidian/base.py
  llama-index-integrations/readers/llama-index-readers-obsidian/pyproject.toml
Labels: lgtm, size:M

#18318 fix: make filename hashing more robust
  llama-index-integrations/readers/llama-index-readers-papers/llama_index/readers/papers/arxiv/base.py
  llama-index-integrations/readers/llama-index-readers-papers/pyproject.toml
Labels: lgtm, size:S

#18321 docs: add Langfuse instrumentation
  docs/docs/examples/observability/Langfuse-Instrumentation.ipynb
  docs/docs/examples/observability/LangfuseCallbackHandler.ipynb
  docs/docs/module_guides/observability/index.md
  docs/mkdocs.yml
Labels: lgtm, size:L

#18316 fix: patch multiple sql-injection vulnerabilities
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/llama_index/vector_stores/clickhouse/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-clickhouse/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/llama_index/vector_stores/couchbase/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-couchbase/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-deeplake/llama_index/vector_stores/deeplake/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-deeplake/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-jaguar/llama_index/vector_stores/jaguar/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-jaguar/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-lantern/llama_index/vector_stores/lantern/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-lantern/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/llama_index/vector_stores/nile/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-nile/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-oracledb/llama_index/vector_stores/oracledb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-oracledb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-singlestoredb/llama_index/vector_stores/singlestoredb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-singlestoredb/pyproject.toml
Labels: lgtm, size:XL

#18319 Update Memgraph integration
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/llama_index/graph_stores/memgraph/property_graph.py
  llama-index-integrations/graph_stores/llama-index-graph-stores-memgraph/pyproject.toml
Labels: lgtm, size:M

#18315 [bugfix] Milvus create index when existed
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/pyproject.toml
Labels: lgtm, size:XS
