Repository run-llama/llama_index, pull requests merged in 2025-09, with the labels that each got.

#19775 Update some llama-cloud-index docs
  docs/docs/examples/llama_cloud/figure_retrieval.ipynb
  docs/docs/examples/llm/asi1.ipynb
  docs/docs/examples/llm/openai.ipynb
  docs/docs/getting_started/installation.md
  docs/docs/module_guides/indexing/llama_cloud_index.md
  docs/docs/understanding/loading/llamacloud.md
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/README.md
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/llama_index/indices/managed/llama_cloud/base.py
  llama-index-integrations/indices/llama-index-indices-managed-llama-cloud/pyproject.toml
Labels: size:M

#19776 v0.13.4
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/embeddings/baseten.md
  docs/docs/api_reference/llms/baseten.md
  docs/docs/api_reference/readers/web.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
  pyproject.toml
  uv.lock
Labels: size:L

#19785 add thinking_delta field to AgentStream events to expose Ollama's reasoning (feat: [19270])
  llama-index-core/llama_index/core/agent/workflow/codeact_agent.py
  llama-index-core/llama_index/core/agent/workflow/function_agent.py
  llama-index-core/llama_index/core/agent/workflow/react_agent.py
  llama-index-core/llama_index/core/agent/workflow/workflow_events.py
  llama-index-core/tests/agent/workflow/test_thinking_delta.py
  llama-index-core/uv.lock
Labels: lgtm, size:L

#19787 fix(litellm): Fix critical context window calculation
  llama-index-integrations/llms/llama-index-llms-litellm/llama_index/llms/litellm/utils.py
  llama-index-integrations/llms/llama-index-llms-litellm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-litellm/tests/test_llms_litellm.py
  llama-index-integrations/llms/llama-index-llms-litellm/tests/test_utils.py
Labels: lgtm, size:S

#19789 fix(litellm): Handle missing tool call IDs with UUID fallback
  llama-index-integrations/llms/llama-index-llms-litellm/llama_index/llms/litellm/base.py
  llama-index-integrations/llms/llama-index-llms-litellm/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-litellm/tests/test_llms_litellm.py
Labels: size:M

#19781 fix: make postgres regex punctuation handling consistent with plainto_tsquery
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/test_postgres.py
  pyproject.toml
Labels: lgtm, size:S

#19768 Yugabytedb chat store
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-yugabytedb/.gitignore
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-yugabytedb/LICENSE
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-yugabytedb/Makefile
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-yugabytedb/README.md
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-yugabytedb/llama_index/storage/chat_store/yugabytedb/__init__.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-yugabytedb/llama_index/storage/chat_store/yugabytedb/base.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-yugabytedb/pyproject.toml
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-yugabytedb/tests/__init__.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-yugabytedb/tests/conftest.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-yugabytedb/tests/test_chat_store_yugabytedb_chat_store.py
  llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-yugabytedb/uv.lock
Labels: lgtm, size:XL

#19792 Fix incorrect example usage of llm.stream and llm.stream_predict
  llama-index-core/llama_index/core/llms/llm.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
Labels: lgtm, size:XS

#19794 fix path handling in SimpleDirectoryReader and PDFReader path fix
  llama-index-core/llama_index/core/readers/file/base.py
  llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/docs/base.py
  llama-index-integrations/readers/llama-index-readers-file/pyproject.toml
Labels: size:M

#19737 Feat: add system prompt / tool caching to BedrockConverse
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/base.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/tests/test_bedrock_converse_utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/tests/test_llms_bedrock_converse.py
Labels: lgtm, size:M

#19796 v0.13.5
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/storage/chat_store/yugabytedb.md
  docs/mkdocs.yml
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
  pyproject.toml
  uv.lock
Labels: size:M

#19793 feat: Add CometAPI LLM integration
  docs/docs/api_reference/llms/cometapi.md
  docs/docs/examples/llm/cometapi.ipynb
  docs/docs/module_guides/models/llms/modules.md
  docs/mkdocs.yml
  docs/mkdocs_api_only.yml
  llama-index-integrations/llms/llama-index-llms-cometapi/.gitignore
  llama-index-integrations/llms/llama-index-llms-cometapi/LICENSE
  llama-index-integrations/llms/llama-index-llms-cometapi/Makefile
  llama-index-integrations/llms/llama-index-llms-cometapi/README.md
  llama-index-integrations/llms/llama-index-llms-cometapi/llama_index/llms/cometapi/__init__.py
  llama-index-integrations/llms/llama-index-llms-cometapi/llama_index/llms/cometapi/base.py
  llama-index-integrations/llms/llama-index-llms-cometapi/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-cometapi/tests/__init__.py
  llama-index-integrations/llms/llama-index-llms-cometapi/tests/test_llms_cometapi.py
  llama-index-integrations/llms/llama-index-llms-cometapi/uv.lock
Labels: lgtm, size:XL

#19805 fix auto tool caching in bedrock-converse
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/llama_index/llms/bedrock_converse/utils.py
  llama-index-integrations/llms/llama-index-llms-bedrock-converse/pyproject.toml
Labels: size:S

#19804 v0.13.6
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  pyproject.toml
  uv.lock
Labels: size:M

#19818 staggler updates for 0.14.x
  llama-index-integrations/retrievers/llama-index-retrievers-bm25/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-superlinked/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-aws-bedrock-agentcore/pyproject.toml
Labels: size:S

#19822 handle positional args and kwargs both in tool calling
  llama-index-core/llama_index/core/program/function_program.py
Labels: lgtm, size:XS

#19831 docs: pull Workflows api reference from workflows-py
  docs/.gitignore
  docs/docs/api_reference/workflow/.gitkeep
  docs/docs/api_reference/workflow/context.md
  docs/docs/api_reference/workflow/decorators.md
  docs/docs/api_reference/workflow/events.md
  docs/docs/api_reference/workflow/retry_policy.md
  docs/docs/api_reference/workflow/workflow.md
  docs/scripts/merge_external_docs.py
Labels: docs, lgtm, size:M

#19832 use the checked out version of workflows to build docs
  docs/poetry.lock
  docs/pyproject.toml
Labels: lgtm, size:XS

#19825 Async dispatch
  llama-index-instrumentation/src/llama_index_instrumentation/dispatcher.py
  llama-index-instrumentation/src/llama_index_instrumentation/event_handlers/base.py
  llama-index-instrumentation/tests/test_dispatcher.py
Labels: lgtm, size:L

#19828 Bug fix agent streaming thinking delta pydantic validation
  llama-index-core/llama_index/core/agent/workflow/codeact_agent.py
  llama-index-core/llama_index/core/agent/workflow/function_agent.py
  llama-index-core/llama_index/core/agent/workflow/react_agent.py
  llama-index-core/llama_index/core/agent/workflow/workflow_events.py
  llama-index-core/tests/agent/workflow/test_thinking_delta.py
Labels: lgtm, size:M

#19824 Bump version constraint for `atlassian-python-api` to include 4.x
  llama-index-integrations/readers/llama-index-readers-confluence/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-confluence/uv.lock
Labels: lgtm, size:XS

#19834 core release action
  .github/workflows/release_core.yml
  llama-index-core/llama_index/core/utils.py
Labels: size:M

#19835 v0.14.1 core
  llama-index-core/llama_index/core/__init__.py
  llama-index-core/pyproject.toml
  llama-index-core/uv.lock
  llama-index-integrations/readers/llama-index-readers-web/tests/test_async_web.py
  llama-index-integrations/tools/llama-index-tools-playwright/tests/test_tools_playwright.py
Labels: size:XS

#19837 lock
  llama-index-core/uv.lock
Labels: size:XS

#19842 update readme
  README.md
Labels: size:S

#19867 lock again?
  docs/poetry.lock
  docs/pyproject.toml
Labels: size:XS

#19876 pass context_window to super in deepseek llm
  llama-index-integrations/llms/llama-index-llms-deepseek/llama_index/llms/deepseek/base.py
  llama-index-integrations/llms/llama-index-llms-deepseek/pyproject.toml
Labels: size:XS

#19868 Update IngestionPipeline async document store insertion
  llama-index-core/llama_index/core/ingestion/pipeline.py
  llama-index-core/tests/ingestion/test_pipeline.py
Labels: lgtm, size:L

#19798 Add llama-index-retriever integration for HPE AlletraMP X10000
  llama-index-integrations/retrievers/llama-index-retrievers-alletra-x10000/.gitignore
  llama-index-integrations/retrievers/llama-index-retrievers-alletra-x10000/LICENSE
  llama-index-integrations/retrievers/llama-index-retrievers-alletra-x10000/Makefile
  llama-index-integrations/retrievers/llama-index-retrievers-alletra-x10000/README.md
  llama-index-integrations/retrievers/llama-index-retrievers-alletra-x10000/llama_index/retrievers/alletra_x10000_retriever/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-alletra-x10000/llama_index/retrievers/alletra_x10000_retriever/base.py
  llama-index-integrations/retrievers/llama-index-retrievers-alletra-x10000/pyproject.toml
  llama-index-integrations/retrievers/llama-index-retrievers-alletra-x10000/tests/__init__.py
  llama-index-integrations/retrievers/llama-index-retrievers-alletra-x10000/tests/test_base.py
  llama-index-integrations/retrievers/llama-index-retrievers-alletra-x10000/uv.lock
Labels: lgtm, size:L

#19878 make fastembed cpu or gpu optional
  llama-index-integrations/embeddings/llama-index-embeddings-fastembed/llama_index/embeddings/fastembed/base.py
  llama-index-integrations/embeddings/llama-index-embeddings-fastembed/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-fastembed/tests/test_embeddings_fastembed.py
Labels: size:S

#19856 better resolve binary
  llama-index-core/llama_index/core/utils.py
  llama-index-core/tests/base/llms/test_types.py
Labels: size:M

#19880 v0.14.2
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/docs/api_reference/readers/solr.md
  docs/docs/api_reference/retrievers/alletra_x10000_retriever.md
  docs/mkdocs.yml
  llama-index-integrations/callbacks/llama-index-callbacks-deepeval/LICENSE
  llama-index-integrations/callbacks/llama-index-callbacks-deepeval/Makefile
  llama-index-integrations/callbacks/llama-index-callbacks-deepeval/README.md
  llama-index-integrations/callbacks/llama-index-callbacks-deepeval/llama_index/callbacks/deepeval/__init__.py
  llama-index-integrations/callbacks/llama-index-callbacks-deepeval/llama_index/callbacks/deepeval/base.py
  llama-index-integrations/callbacks/llama-index-callbacks-deepeval/pyproject.toml
  llama-index-integrations/callbacks/llama-index-callbacks-deepeval/uv.lock
  llama-index-integrations/readers/llama-index-readers-solr/pyproject.toml
  pyproject.toml
  uv.lock
Labels: size:L

#19827 [New Package] Add PaddleOCR Reader for extracting text from images in PDFs
  llama-index-integrations/readers/llama-index-readers-paddle-ocr/.gitignore
  llama-index-integrations/readers/llama-index-readers-paddle-ocr/CHANGELOG.md
  llama-index-integrations/readers/llama-index-readers-paddle-ocr/LICENSE
  llama-index-integrations/readers/llama-index-readers-paddle-ocr/Makefile
  llama-index-integrations/readers/llama-index-readers-paddle-ocr/README.md
  llama-index-integrations/readers/llama-index-readers-paddle-ocr/llama_index/readers/paddle_ocr/__init__.py
  llama-index-integrations/readers/llama-index-readers-paddle-ocr/llama_index/readers/paddle_ocr/base.py
  llama-index-integrations/readers/llama-index-readers-paddle-ocr/pyproject.toml
  llama-index-integrations/readers/llama-index-readers-paddle-ocr/tests/__init__.py
  llama-index-integrations/readers/llama-index-readers-paddle-ocr/tests/test_readers_paddle_ocr.py
  llama-index-integrations/readers/llama-index-readers-paddle-ocr/uv.lock
Labels: lgtm, size:XL

#19882 Add compat
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/tests/test_vector_stores_qdrant.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/uv.lock
Labels: lgtm, size:L

#19883 Add GitHub Actions workflow for Developer Hub deployment
  .github/workflows/deploy-developer-hub.yml
Labels: lgtm, size:S

#19885 All tips and important blocks to Starlight built-ins
  docs/docs/getting_started/concepts.mdx
  docs/docs/getting_started/faq.mdx
  docs/docs/getting_started/installation.mdx
  docs/docs/getting_started/starter_example.mdx
  docs/docs/getting_started/starter_example_local.mdx
  docs/docs/module_guides/deploying/agents/index.mdx
  docs/docs/module_guides/deploying/agents/memory.mdx
  docs/docs/module_guides/deploying/chat_engines/index.mdx
  docs/docs/module_guides/deploying/chat_engines/usage_pattern.mdx
  docs/docs/module_guides/deploying/query_engine/index.mdx
  docs/docs/module_guides/deploying/query_engine/usage_pattern.mdx
  docs/docs/module_guides/indexing/vector_store_index.mdx
  docs/docs/module_guides/loading/connector/index.mdx
  docs/docs/module_guides/querying/node_postprocessors/index.mdx
  docs/docs/module_guides/querying/response_synthesizers/index.mdx
  docs/docs/module_guides/querying/retriever/index.mdx
  docs/docs/module_guides/querying/structured_outputs/pydantic_program.mdx
  docs/docs/module_guides/querying/structured_outputs/query_engine.mdx
  docs/docs/module_guides/supporting_modules/settings.mdx
  docs/docs/module_guides/workflow/index.mdx
  docs/docs/understanding/agent/index.mdx
  docs/docs/understanding/agent/streaming.mdx
  docs/docs/understanding/index.mdx
  docs/docs/understanding/rag/index.mdx
  docs/docs/understanding/rag/indexing/index.mdx
  docs/docs/understanding/rag/querying/index.mdx
  docs/docs/understanding/rag/storing/index.mdx
  docs/docs/understanding/using_llms.mdx
  docs/docs/understanding/workflows/stream.mdx
Labels: lgtm, size:L

#19892 added kimik2 0905 and reordered list for validation
  llama-index-integrations/llms/llama-index-llms-baseten/llama_index/llms/baseten/utils.py
  llama-index-integrations/llms/llama-index-llms-baseten/pyproject.toml
Labels: lgtm, size:XS

#19893 Baseten Dynamic Model APIs Validation
  llama-index-integrations/llms/llama-index-llms-baseten/llama_index/llms/baseten/base.py
  llama-index-integrations/llms/llama-index-llms-baseten/llama_index/llms/baseten/utils.py
  llama-index-integrations/llms/llama-index-llms-baseten/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-baseten/tests/test_baseten_dynamic.py
  llama-index-integrations/llms/llama-index-llms-baseten/tests/test_coverage_comprehensive.py
Labels: lgtm, size:XL

#19891 Fix Gemini thought signature serialization
  llama-index-core/llama_index/core/base/llms/types.py
Labels: lgtm, size:XS

#19897 Add missing FileAPI support for documents
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/utils.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
Labels: size:S

#19920 llama-dev: Add `release check` command and run it before releasing the package via CI
  .github/workflows/release_core.yml
  llama-dev/llama_dev/cli.py
  llama-dev/llama_dev/release/__init__.py
  llama-dev/llama_dev/release/check.py
  llama-dev/tests/conftest.py
  llama-dev/tests/release/test_check.py
Labels: lgtm, github_actions

#19914 Fix SQLi Vulnerability in SingleStore Db
  llama-index-integrations/vector_stores/llama-index-vector-stores-singlestoredb/llama_index/vector_stores/singlestoredb/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-singlestoredb/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-singlestoredb/tests/test_vector_stores_singlestoredb.py
Labels: lgtm, size:L

#19938 Fix `TypeError: unhashable type: 'dict'` in Ollama stream chat with tools
  llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
  llama-index-integrations/llms/llama-index-llms-ollama/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-ollama/tests/test_llms_ollama.py
Labels: lgtm, size:S

#19940 chore: get `__version__` dynamically instead of hardcoding the value
  llama-dev/llama_dev/release/check.py
  llama-dev/tests/release/test_check.py
  llama-index-core/llama_index/core/__init__.py
Labels: size:M

#19946 chore: fix playwright tests
  llama-index-integrations/tools/llama-index-tools-playwright/tests/test_tools_playwright.py
Labels: size:XS

#19944 fix llm deps for openai
  llama-index-cli/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-anyscale/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-baseten/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-fireworks/pyproject.toml
  llama-index-integrations/embeddings/llama-index-embeddings-opea/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-anthropic/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-anyscale/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-azure-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-baseten/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-deepinfra/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-everlyai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-fireworks/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-keywordsai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-localai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-mistralai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-monsterapi/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-nvidia/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai-like/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-perplexity/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-portkey/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-upstage/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-yi/pyproject.toml
  llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/pyproject.toml
  llama-index-integrations/selectors/llama-index-selectors-notdiamond/pyproject.toml
  llama-index-integrations/tools/llama-index-tools-agentql/pyproject.toml
  llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/pyproject.toml
  pyproject.toml
  uv.lock
Labels: size:L

#19932 fixed Sarvam Integration and Typos (Fixes #19931)
  llama-index-integrations/llms/llama-index-llms-sarvam/README.md
  llama-index-integrations/llms/llama-index-llms-sarvam/llama_index/llms/sarvam/__init__.py
  llama-index-integrations/llms/llama-index-llms-sarvam/llama_index/llms/sarvam/base.py
  llama-index-integrations/llms/llama-index-llms-sarvam/llama_index/llms/servam/__init__.py
  llama-index-integrations/llms/llama-index-llms-sarvam/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-sarvam/tests/test_llms_servam.py
Labels: lgtm, size:M

#19943 [CI]: Pre-release workflow
  .github/workflows/pre_release.yml
  llama-dev/llama_dev/pkg/bump.py
  llama-dev/llama_dev/release/__init__.py
  llama-dev/llama_dev/release/prepare.py
  llama-dev/llama_dev/utils.py
Labels: lgtm, size:L

#19950 [CI]: fix `gh` execution on CI
  .github/workflows/pre_release.yml
Labels: lgtm, size:XS

#19955 fix index creation in postgres vector store
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py
  llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/pyproject.toml
Labels: size:XS

#19954 Fix for ValueError: ChatMessage contains multiple blocks, use 'ChatMe…
  llama-index-integrations/llms/llama-index-llms-google-genai/llama_index/llms/google_genai/base.py
  llama-index-integrations/llms/llama-index-llms-google-genai/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-google-genai/uv.lock
Labels: lgtm, size:XS

#19959 llama-dev: Parametrize the release branch name, show release number in PR title
  .github/workflows/pre_release.yml
  llama-dev/llama_dev/pkg/info.py
Labels: size:M

#19967 feat(OpenAILike): support structured outputs
  llama-index-integrations/llms/llama-index-llms-openai-like/llama_index/llms/openai_like/base.py
  llama-index-integrations/llms/llama-index-llms-openai-like/pyproject.toml
  llama-index-integrations/llms/llama-index-llms-openai-like/tests/test_openai_like_grok.py
  llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py
Labels: size:L

#19973 docs: fix query method docstring in ChromaVectorStore Fixes #19969
  llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/llama_index/vector_stores/chroma/base.py
Labels: lgtm, size:S

#19991 Broken link
  docs/src/content/docs/framework/index.md
Labels: lgtm, size:XS
